#!/bin/bash
. /root/mysql_backup_auth
safe_dir=`mktemp -d`
nice -n 20 mysqldump -u$MYSQL_USER -p$MYSQL_PASS --all-databases |
  nice -n 20 bzip2 -9 |
  nice -n 20 gpg -e -r 'bw-admin-discussion@bewelcome.org' > $safe_dir/mysql_dump.`date +%FT%H%M`.bz2
#ssh -i /home/bwrox/.ssh/id_rsa -p 222 bwrox@goat.bewelcome.org "cat > /home/bull_backup/mysql_dump.`date +%FT%H%M`.bz2"
cd /
nice -n 20 tar cjf - etc |
  nice -n 20 gpg -e -r 'bw-admin-discussion@bewelcome.org' > $safe_dir/etc-`date +%FT%H%M`.tar.bz2
#ssh -i /home/bwrox/.ssh/id_rsa -p 222 bwrox@goat.bewelcome.org "cat > /home/bull_backup/etc-`date +%FT%H%M`.tar.gz"
cd /home/bwrox
nice -n 20 tar cjf - configs | gpg -e -r 'bw-admin-discussion@bewelcome.org' > $safe_dir/configs-`date +%FT%H%M`.tar.gz
scp -i /root/.ssh/id_rsa2 $safe_dir/* backup@mule.bewelcome.org:/var/backup/bull || echo "ERROR: could not copy files in $safe_dir to mule!"
rm -r $safe_dir
