services:
    Rox\Start\Controller\StartController:
        class: Rox\Start\Controller\StartController
        autowire: true
        parent: Rox\Core\Controller\AbstractController

    Rox\Start\Controller\TourController:
        class: Rox\Start\Controller\TourController
        autowire: true
        parent: Rox\Core\Controller\AbstractController

    Rox\Start\Controller\AboutController:
        class: Rox\Start\Controller\AboutController
        autowire: true
        parent: Rox\Core\Controller\AbstractController
