# config/packages/hwi_oauth.yaml

hwi_oauth:
    resource_owners:
        any_name:
            type:                github
            client_id:           <client_id>
            client_secret:       <client_secret>
            scope:               'user:email,public_repo'
