lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 604800 # 1 week, same as the cookie
    set_cookies:
        bewelcome:
            lifetime: 604800 # 1 week
            samesite: strict
    token_extractors:
        authorization_header:
            enabled: false
        cookie:
            enabled: true
            name: bewelcome
