login_gate:
    storages: ['orm']
    options:
        max_count_attempts: 3
        timeout: 600 # Ban period (in seconds: 600 = 10 minutes)
        watch_period: 3600
    username_resolver: App\Security\UsernameResolver
