# Twig Configuration
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  form_themes:
    - 'rox_form_theme.html.twig'
    - 'ckeditor/ckeditor.html.twig'

  paths:
      '%kernel.project_dir%/build': 'build'
      '%kernel.project_dir%/public/images': 'images'
      '%kernel.project_dir%/public': 'public'
