version: '3.4'

x-cache-from:
  - &cache-from
    cache_from:
      - ${NGINX_IMAGE:-bewelcome/nginx}
      - ${PHP_IMAGE:-bewelcome/php}

services:
  php:
    build:
      context: .
      target: bewelcome_php_dev
      <<: *cache-from
    image: ${PHP_IMAGE:-bewelcome/php}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - db
      - sphinx
      - mailer
    volumes:
      - .:/srv/bewelcome:rw,cached
      - ./docker/php/conf.d/bewelcome.dev.ini:/usr/local/etc/php/conf.d/bewelcome.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./var:/srv/bewelcome/var:rw

  web:
    build:
      context: .
      target: bewelcome_nginx
      <<: *cache-from
    image: ${NGINX_IMAGE:-bewelcome/nginx}
    depends_on:
      - php
    volumes:
      - ./public:/srv/bewelcome/public:ro

  db:
    image: mariadb:10.1.41
    environment:
      MYSQL_ROOT_PASSWORD: bewelcome_root_dev
      MYSQL_DATABASE: bewelcome
      MYSQL_USER: bewelcome
      MYSQL_PASSWORD: bewelcome
    volumes:
      - db-data:/var/lib/mysql:rw

  sphinx:
    image: stefobark/sphinxdocker

  mailer:
    image: tophfr/mailcatcher

volumes:
  db-data: {}
