x-cache-from:
  - &cache-from
    cache_from:
      - ${NGINX_IMAGE:-bewelcome/nginx}
      - ${PHP_IMAGE:-bewelcome/php}

services:
  php:
    build:
      context: .
      target: bewelcome_php_dev
      <<: *cache-from
    image: ${PHP_IMAGE:-bewelcome/php}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      test: ["NONE"]
    depends_on:
      - db
      - manticore
      - mailer
    volumes:
      - .:/srv/bewelcome:rw,cached
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./var:/srv/bewelcome/var:rw

  web:
    build:
      context: .
      target: bewelcome_nginx
      <<: *cache-from
    image: ${NGINX_IMAGE:-bewelcome/nginx}
    depends_on:
      - php
    volumes:
      - ./public:/srv/bewelcome/public:ro

  db:
    image: mariadb:11.6.2
    environment:
      MYSQL_ROOT_PASSWORD: bewelcome_root_dev
      MYSQL_DATABASE: bewelcome
      MYSQL_USER: bewelcome
      MYSQL_PASSWORD: bewelcome
    volumes:
      - db-data:/var/lib/mysql:rw

  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    restart: always
    ports:
      - "127.0.0.1:9306:9306"
      - "127.0.0.1:9308:9308"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/var/lib/manticore
      - ./docker/manticore/manticore.conf:/etc/manticoresearch/manticore.conf

  mailer:
    image: tophfr/mailcatcher

volumes:
  db-data: {}
  manticore-data: {}
