site_name: 'BeWelcome Rox'
dev_addr: '127.0.0.1:8080'
docs_dir: doc/book
site_dir: doc/html
theme: readthedocs
nav:
    - index.md
    - Reference:
      - 'Project Structure': structure.md
      - Permissions: permissions.md
      - Twig: twig.md
      - 'Error Handling': error_handling.md
    - Deprecated: deprecated.md
