##################################################
# Generated by phansible.com
##################################################

# Check to determine whether we're on a windows or linux/os-x host,
# later on we use this to launch ansible in the supported way
# source: https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each { |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable? exe
        }
    end
    return nil
end

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "bewelcome"
        v.customize [
            "modifyvm", :id,
            "--name", "bewelcome",
            "--memory", 1024,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
    end

    config.vm.box = "debian/jessie64"
    config.vm.box_version = "8.2.1"

    config.vm.network :private_network, ip: "192.168.33.10"
    config.ssh.forward_agent = true
    # config.vm.hostname = "bewelcome"

    # If ansible is in your path it will provision from your HOST machine
    # If ansible is not found in the path it will be instaled in the VM and provisioned from there
    # if which('ansible-playbook')
        config.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/playbook.yml"
            ansible.inventory_path = "ansible/inventories/dev"
            ansible.limit = 'all'
        end
    # else
    #    config.vm.provision :shell, path: "ansible/windows.sh", args: ["bewelcome"]
    # end

    config.vm.synced_folder "./", "/vagrant", :group=>"www-data", :mount_options=>["dmode=775","fmode=665"]
end
