; Xdebug configuration for development
; Disabled by default for performance. To enable, you can set XDEBUG_MODE=debug
xdebug.mode=off
xdebug.client_host=host.docker.internal
xdebug.start_with_request=yes
xdebug.discover_client_host=1
