---
- name: Install Apache
  sudo: yes
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

#
# Preventing "Apache is running a threaded MPM, but your PHP Module..."
# http://stackoverflow.com/questions/19185268/php-and-apache-thread-safe-error
- name: Disabling mpm_event module
  sudo: yes
  command: a2dismod mpm_event

- name: Enabling mpm_prefork module
  sudo: yes
  command: a2enmod mpm_prefork
  notify: restart apache
#

- shell: apache2 -v
  register: apache_version

- name: Change default apache2.4 site
  sudo: yes
  template: src=vhost24.conf.tpl dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.4.') != -1

- name: Change default apache2.2 site
  sudo: yes
  template: src=vhost22.conf.tpl dest=/etc/apache2/sites-available/default
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.2.') != -1
