services:
    Rox\Member\Controller\AvatarController:
        class: Rox\Member\Controller\AvatarController
        autowire: true

    Rox\Member\Controller\MemberController:
        class: Rox\Member\Controller\MemberController
        autowire: true
        parent: Rox\Core\Controller\AbstractController

    Rox\Member\Controller\CommentController:
        class: Rox\Member\Controller\CommentController
        autowire: true

    Rox\Member\Controller\HttpsCheckController:
        class: Rox\Member\Controller\HttpsCheckController

    Rox\Member\Controller\ChangePasswordController:
        class: Rox\Member\Controller\ChangePasswordController
        parent: Rox\Core\Controller\AbstractController
        arguments: ['@Rox\Member\Service\MemberService', '@security.encoder_factory', '@security.authentication.rememberme.services.simplehash.default']
        calls:
            - [setRememberMeFormParameter, ['%remember_me.form_parameter%']]
            - [setRememberMeCookieName, ['%remember_me.cookie_name%']]
