services:
    Rox\Member\Model\Member:
        class: Rox\Member\Model\Member
        autowiring_types: Rox\Member\Repository\MemberRepositoryInterface

    Rox\Member\Listener\HttpsCheckListener:
        class: Rox\Member\Listener\HttpsCheckListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    Rox\Member\Listener\UserListener:
        class: Rox\Member\Listener\UserListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    Rox\Member\Extension\MemberTwigExtension:
        class: Rox\Member\Extension\MemberTwigExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }
