<!DOCTYPE html>
<html lang="<?=PVars::get()->lang; ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/images/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/svg+xml" href="/images/favicon.svg" />
    <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />
    <meta name="apple-mobile-web-app-title" content="beWelcome" />
    <?php
    // Self-referencing canonical (BeWelcome/sysadmins-infra#654). Legacy pages may rely on the
    // query string, so only tracking parameters are dropped.
    $canonicalParts = parse_url($_SERVER['REQUEST_URI'] ?? '/');
    parse_str($canonicalParts['query'] ?? '', $canonicalQuery);
    $canonicalQuery = array_filter($canonicalQuery, function ($key) {
        return !preg_match('/^(utm_.*|gclid|gbraid|wbraid|fbclid|msclkid)$/', $key);
    }, ARRAY_FILTER_USE_KEY);
    $canonicalScheme = (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https' || !empty($_SERVER['HTTPS'])) ? 'https' : 'http';
    $canonicalUrl = $canonicalScheme . '://' . $_SERVER['HTTP_HOST'] . ($canonicalParts['path'] ?? '/')
        . ($canonicalQuery ? '?' . http_build_query($canonicalQuery) : '');
    ?>
    <link rel="canonical" href="<?= htmlspecialchars($canonicalUrl, ENT_QUOTES) ?>" />

    <link rel="stylesheet" href="/build/bewelcome.css" />

    <!-- this page is generated by "class <?=get_class($this) ?>" -->
    <!-- the controller was an instance of <?=(is_string($this->controller_classname) ? ('"class '.$this->controller_classname.'"') : '[unknown class]') ?> -->
    <?=(is_object($this->layoutkit) && is_object($this->layoutkit->mem_from_redirect) ? '
        <!--
        '.$this->layoutkit->mem_from_redirect->buffered_text.'
        -->' : '') ?>
    <?php
    $this->head();
    $this->includeJsConfig();
    $this->includeScriptfiles();
    ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/build/backwards.js"></script>
    <![endif]-->
</head>
<body>
<?= (is_object($this->layoutkit) && (is_object($this->layoutkit->mem_from_redirect))) ? $this->layoutkit->mem_from_redirect->buffered_text : '' ?>
test <?= $this->body() ?> test
<?= $this->includeLateScriptfiles() ?>

</body>
</html>
