services:
    Rox\Core\Factory\DatabaseFactory:
        class: Rox\Core\Factory\DatabaseFactory

    Illuminate\Database\Connection:
        class: Illuminate\Database\Connection
        factory: ['@Rox\Core\Factory\DatabaseFactory', __invoke]

    Rox\Core\Kernel\LegacyHttpKernel:
        class: Rox\Core\Kernel\LegacyHttpKernel
        arguments: ['@templating.engine.twig', '@event_dispatcher', '@controller_resolver', '@request_stack', '@argument_resolver']

    templating.engine.twig:
        class: Symfony\Bundle\TwigBundle\TwigEngine
        autowiring_types: Symfony\Component\Templating\EngineInterface
        arguments: ['@twig', '@templating.name_parser', '@templating.locator']

    Rox\Core\Extension\RoxTwigExtension:
        class: Rox\Core\Extension\RoxTwigExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.assets:
        class: Rox\Core\Extension\AssetExtension
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.form:
        class: Symfony\Bridge\Twig\Extension\FormExtension
        arguments: ['@twig.form.renderer']
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.trans:
        class: Symfony\Bridge\Twig\Extension\TranslationExtension
        arguments: ['@translator']
        public: false
        tags:
            - { name: twig.extension }

    form.factory:
        class: Symfony\Component\Form\FormFactory
        autowiring_types: Symfony\Component\Form\FormFactoryInterface
        arguments: ['@form.registry', '@form.resolved_type_factory']

    Rox\Core\Listener\LegacyDispatchListener:
        class: Rox\Core\Listener\LegacyDispatchListener
        arguments: ['@Rox\Core\Kernel\LegacyHttpKernel', '@session', '@security.token_storage' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    Rox\Core\Controller\AbstractController:
        abstract: true
        calls:
            - [setEngine, ['@templating']]
            - [setTokenStorage, ['@security.token_storage']]
            - [setSession, ['@session']]
            - [setRouter, ['@router']]
            - [setFormFactory, ['@form.factory']]
            - [setAuthChecker, ['@security.authorization_checker']]

#    Symfony\Bundle\FrameworkBundle\Controller\Controller:
#        abstract: true
#        calls:
#            - [setContainer, ['@service_container']]
