<?php


use Rox\Tools\RoxMigration;

class MoreMissingWordCodes extends RoxMigration
{
    public function up()
    {
        $this->AddWordCode('canofferneverask', 'Accommodation: No.', 'Tooltip for accommodation icons.');
        $this->AddWordCode('profile.contactinfo.socialmedia', 'Social Media', 'Headline on edit my profile');
        // $this->AddWordCode("activities", "Activities", "templates\\activity\\list.html.twig:21");
        // $this->AddWordCode("activities.number.attendees.yes", "%number%", "templates\\activity\\list.html.twig:49");
        // $this->AddWordCode("activities.number.attendees.maybe", "ActivitiesNumbAttendeesMaybe", "templates\\activity\\list.html.twig:50");
        // $this->AddWordCode("activity", "Activity", "templates\\activity\\show.html.twig:4");
        $this->AddWordCode("admin.checker.no.messages", "No messages have been reported as spam.", "templates\\admin\\checker\\index.html.twig:19");
        $this->AddWordCode("ok", "ok", "templates\\admin\\checker\\index.html.twig:35");
        $this->AddWordCode("spam", "spam", "templates\\admin\\checker\\index.html.twig:36");
        $this->AddWordCode("admin.comment.headline", "Admin - Comment", "templates\\admin\\comment\\comment.html.twig:5");
        $this->AddWordCode("admin.comments.to.all", "All comments to %username%", "templates\\admin\\comment\\comment.html.twig:25");
        $this->AddWordCode("admin.comments.from.all", "All comments from %username%", "templates\\admin\\comment\\comment.html.twig:26");
        $this->AddWordCode("admin.comments.all", "All Comments", "templates\\admin\\comment\\overview.html.twig:5");
        $this->AddWordCode("admin.comments.no.comments", "No comments found for these parameters.", "templates\\admin\\comment\\overview.html.twig:11");
        $this->AddWordCode("from", "from", "templates\\admin\\comment\\overview.html.twig:22");
        $this->AddWordCode("about", "about", "templates\\admin\\comment\\overview.html.twig:24");
        $this->AddWordCode("action", "action", "templates\\admin\\comment\\overview.html.twig:25");
        $this->AddWordCode("written", "written", "templates\\admin\\comment\\overview.html.twig:34");
        $this->AddWordCode("comment.quality", "Quality and Date", "templates\\admin\\comment\\overview.html.twig");
        $this->AddWordCode("comment.where.met", "Where we met", "templates\\admin\\comment\\overview.html.twig");
        $this->AddWordCode("comment.text", "Comment Text", "templates\\admin\\comment\\overview.html.twig");
        $this->AddWordCode("comment.know", "How we know each other", "templates\\admin\\comment\\overview.html.twig");
        $this->AddWordCode("admin.comment.edit", "Edit comment", "templates\\admin\\comment\\overview.html.twig:46");
        $this->AddWordCode("admin.comment.hide", "Hide", "templates\\admin\\comment\\overview.html.twig:48");
        $this->AddWordCode("admin.comment.show", "Show", "templates\\admin\\comment\\overview.html.twig:50");
        $this->AddWordCode("admin.comment.assign.safety", "Assign to safety team", "templates\\admin\\comment\\overview.html.twig:53");
        $this->AddWordCode("admin.comment.checked", "Mark as checked", "templates\\admin\\comment\\overview.html.twig:56");
        $this->AddWordCode("admin.community.news.headline", "Community News", "templates\\admin\\communitynews\\editcreate.html.twig:4");
        $this->AddWordCode("admin.logs.no.logs", "No logs found for these parameters.", "templates\\admin\\communitynews\\index.html.twig:25");
        $this->AddWordCode("create", "create", "templates\\admin\\communitynews\\list.html.twig:17");
        $this->AddWordCode("read.more", "Read more", "templates\\admin\\communitynews\\list.html.twig:39");
        $this->AddWordCode("admin.faq.edit.category", "Edit a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:13");
        $this->AddWordCode("admin.faq.create.category", "Create a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:15");
        $this->AddWordCode("admin.faq.category.update.order", "Update order", "templates\\admin\\faqs\\editcreate.category.html.twig:33");
        $this->AddWordCode("faq.create.category.label", "Create Category", "templates\\admin\\faqs\\sort.categories.html.twig:15");
        $this->AddWordCode("admin.faq.abstract", "This shows the list of all FAQ categories. You can drag the cards to change the sort order.", "templates\\admin\\faqs\\sort.categories.html.twig:31");
        $this->AddWordCode("admin.faq.edit", "Edit a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:13");
        $this->AddWordCode("admin.faq.create", "Create a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:15");
        $this->AddWordCode("admin.group.info", "Group Info", "templates\\admin\\groups\\approve.html.twig:16");
        $this->AddWordCode("admin.faq.sort.categories", "Sort categories", "Admin -> FAQ -> Category");
        $this->AddWordCode("admin.faq.sort.order.updated.flash", "Updated sort order of FAQ categories.", "src\\Controller\\Admin\\FaqController.php:376");
        $this->AddWordCode("admin.group.description", "Group Description", "templates\\admin\\groups\\approve.html.twig:17");
        $this->AddWordCode("admin.group.creator", "Creator", "templates\\admin\\groups\\approve.html.twig:18");
        $this->AddWordCode("admin.group.actions", "Actions", "templates\\admin\\groups\\approve.html.twig:19");
        $this->AddWordCode("admin.group.approve", "Approve group", "templates\\admin\\groups\\approve.html.twig:36");
        $this->AddWordCode("admin.group.dismiss", "Dismiss group", "templates\\admin\\groups\\approve.html.twig:37");
        $this->AddWordCode("admin.group.discussion", "Move group to discussion queue", "templates\\admin\\groups\\approve.html.twig:39");
        $this->AddWordCode("admin.group.no.group", "No groups need to be approved", "templates\\admin\\groups\\approve.html.twig:48");
        $this->AddWordCode("country", "Country", "templates\\admin\\tools\\age.country.html.twig:14");
        $this->AddWordCode("birth.year", "Birth Year", "templates\\admin\\tools\\age.country.html.twig:16");
        $this->AddWordCode("age", "Age", "templates\\admin\\tools\\age.country.html.twig:17");
        $this->AddWordCode("admin.feedback.no.feedback", "No feedback found for these parameters.", "templates\\admin\\tools\\check.feedback.html.twig:27");
        $this->AddWordCode("robots", "robots", "templates\\base-lite.html.twig:21");
        $this->AddWordCode("communitynews.comments", "%commentsCount% comments", "templates\\communitynews\\list.html.twig:21");
        $this->AddWordCode("email.greeting", "Dear %username%,", "templates\\emails\\reset.password.html.twig:4");
        $this->AddWordCode("email.reset.password.ignore", "If you received this email without asking for a password reset, please let us no on %link_start%Contact Us%link_end%", "Paragraph in the password reset email.");
        $this->AddWordCode("footer.site.language", "footer.site.language", "templates\\footer.html.twig:25");
        $this->AddWordCode("translation.information", "Translation information", "templates\\footer.html.twig:85");
        $this->AddWordCode("translation.translatable", "Translatable items", "templates\\footer.html.twig:104");
        $this->AddWordCode("translation.existing", "Existing translations", "templates\\footer.html.twig:156");
        $this->AddWordCode("translation.existing.info", "The list shows all translatable items that have an existing translation in the current locale.", "templates\\footer.html.twig:157");
        $this->AddWordCode("translation.fallback", "Fallback Translations", "templates\\footer.html.twig:171");
        $this->AddWordCode("translation.fallback.info", "The list shows all translations that match the English original text.", "templates\\footer.html.twig:172");
        $this->AddWordCode("translation.keyword.doesnt.exist", "Translations keyword doesn't exist", "templates\\footer.html.twig:185");
        $this->AddWordCode("default_meta_robots", "default_meta_robots", "templates\\home\\home.html.twig:13");
        $this->AddWordCode("The world is just one step from here", "The world is just one step from here", "templates\\home\\home.html.twig:125");
        $this->AddWordCode("indexpageword_share", "IndexPageWord_share", "templates\\home\\home.html.twig:137");
        $this->AddWordCode("choose.username", "Choose your username!", "templates\\home\\home.html.twig:140");
        $this->AddWordCode("search", "Search", "templates\\home\\home.html.twig:175");
        $this->AddWordCode("aboutuspage", "About Us", "templates\\home\\home.html.twig:192");
        $this->AddWordCode("termsofuse", "Terms Of Use", "templates\\home\\home.html.twig:193");
        $this->AddWordCode("copyrightbybv", "Copyright by BeVolunteer", "templates\\home\\home.html.twig:200");
        $this->AddWordCode("running.on", "Running on", "templates\\home\\home.html.twig:201");
        $this->AddWordCode("dashboard.donation.received", "dashboard.donation.received", "templates\\landing\\landing.html.twig:207");
        $this->AddWordCode("hosting", "hosting", "templates\\landing\\widget\\accommodation.html.twig:3");
        $this->AddWordCode("maybe hosting", "maybe hosting", "templates\\landing\\widget\\accommodation.html.twig:4");
        $this->AddWordCode("not hosting", "not hosting", "templates\\landing\\widget\\accommodation.html.twig:5");
        $this->AddWordCode("bewelcome", "BeWelcome", "templates\\loginbar.html.twig:8");
        $this->AddWordCode("login", "Login", "templates\\loginbar.html.twig:13");
        $this->AddWordCode("password.reset", "Reset Password", "templates\\member\\request.password.reset.html.twig:5");
        $this->AddWordCode("member", "Member", "templates\\member\\results.html.twig:11");
        $this->AddWordCode("profile.summary", "profile summary", "templates\\member\\results.html.twig:12");
        $this->AddWordCode("details", "details", "templates\\member\\results.html.twig:13");
        $this->AddWordCode("SearchYearsOld", "SearchYearsOld", "templates\\member\\results.html.twig:36");
        $this->AddWordCode("SearchCommentsInfo", "SearchCommentsInfo", "templates\\member\\results.html.twig:65");
        $this->AddWordCode("SearchMemberLastLoginInfo", "SearchMemberLastLoginInfo", "templates\\member\\results.html.twig:69");
        $this->AddWordCode("SearchMemberSinceInfo", "SearchMemberSinceInfo", "templates\\member\\results.html.twig:70");
        $this->AddWordCode("Date", "Date", "templates\\message\\index.html.twig:45");
        $this->AddWordCode("MessagesText", "MessagesText", "templates\\message\\index.html.twig:47");
        $this->AddWordCode("View", "View", "templates\\message\\index.html.twig:98");
        $this->AddWordCode("MessagesWarningConfirmDelete", "MessagesWarningConfirmDelete", "templates\\message\\index.html.twig:109");
        $this->AddWordCode("Profile", "Profile", "templates\\message\\thread.html.twig:23");
        $this->AddWordCode("Last login:", "Last login:", "templates\\profile\\cards\\hosting.html.twig:32");
        $this->AddWordCode("never", "never", "templates\\profile\\cards\\hosting.html.twig:32");
        $this->AddWordCode("MyPreferences", "MyPreferences", "templates\\profile\\view.html.twig:14");
        $this->AddWordCode("years old", "years old", "templates\\profile\\view.html.twig:57");
        $this->AddWordCode("EditMyProfile", "EditMyProfile", "templates\\profile\\view.html.twig:75");
        $this->AddWordCode("IndexPageTeaserOpenDoor", "IndexPageTeaserOpenDoor", "templates\\security\\login.html.twig:20");
        $this->AddWordCode("Username", "Username", "templates\\security\\login.html.twig:43");
        $this->AddWordCode("Password", "Password", "templates\\security\\login.html.twig:49");
        $this->AddWordCode("StayLoggedIn", "StayLoggedIn", "templates\\security\\login.html.twig:56");
        $this->AddWordCode("IndexPageLoginSubmit", "IndexPageLoginSubmit", "templates\\security\\login.html.twig:67");
        $this->AddWordCode("SignupNow", "SignupNow", "templates\\security\\login.html.twig:78");
        $this->AddWordCode("IndexPageWord17", "IndexPageWord17", "templates\\security\\login.html.twig:79");
        $this->AddWordCode("All trips", "All trips", "templates\\trip\\list.html.twig:4");
        $this->AddWordCode("trip.no_trips_found", "trip.no_trips_found", "templates\\trip\\list.html.twig:33");
        $this->AddWordCode("Trip", "Trip", "templates\\trip\\show.html.twig:4");
        $this->AddWordCode("FindMembers", "FindMembers", "templates\\twig\\base\\navigation.html.twig:12");
        $this->AddWordCode("MapSearch", "MapSearch", "templates\\twig\\base\\navigation.html.twig:15");
        $this->AddWordCode("TextSearch", "TextSearch", "templates\\twig\\base\\navigation.html.twig:16");
        $this->AddWordCode("BrowseCountries", "BrowseCountries", "templates\\twig\\base\\navigation.html.twig:17");
        $this->AddWordCode("CommunityMenu", "CommunityMenu", "templates\\twig\\base\\navigation.html.twig:22");
        $this->AddWordCode("AgoraTagLine", "AgoraTagLine", "templates\\twig\\base\\navigation.html.twig:25");
        $this->AddWordCode("CommunityDiscussions", "CommunityDiscussions", "templates\\twig\\base\\navigation.html.twig:25");
        $this->AddWordCode("GroupTagLine", "GroupTagLine", "templates\\twig\\base\\navigation.html.twig:26");
        $this->AddWordCode("Groups", "Groups", "templates\\twig\\base\\navigation.html.twig:26");
        $this->AddWordCode("Suggestions", "Suggestions", "templates\\twig\\base\\navigation.html.twig:28");
        $this->AddWordCode("Trips", "Trips", "templates\\twig\\base\\navigation.html.twig:29");
        $this->AddWordCode("Blogs", "Blogs", "templates\\twig\\base\\navigation.html.twig:30");
        $this->AddWordCode("Wiki", "Wiki", "templates\\twig\\base\\navigation.html.twig:31");
        $this->AddWordCode("Safety", "Safety", "templates\\twig\\base\\navigation.html.twig:36");
        $this->AddWordCode("GetAnswers", "GetAnswers", "templates\\twig\\base\\navigation.html.twig:40");
        $this->AddWordCode("FAQ", "FAQ", "templates\\twig\\base\\navigation.html.twig:42");
        $this->AddWordCode("ContactUs", "ContactUs", "templates\\twig\\base\\navigation.html.twig:43");
        $this->AddWordCode("About_GetActive", "About_GetActive", "templates\\twig\\base\\navigation.html.twig:44");
        $this->AddWordCode("DonateLink", "DonateLink", "templates\\twig\\base\\navigation.html.twig:45");
        $this->AddWordCode("Volunteer", "Volunteer", "templates\\twig\\base\\navigation.html.twig:55");
        $this->AddWordCode("MyMessages", "MyMessages", "templates\\twig\\base\\navigation.html.twig:79");
        $this->AddWordCode("ProfileMyNotes", "ProfileMyNotes", "templates\\twig\\base\\navigation.html.twig:80");
        $this->AddWordCode("MyGroups", "MyGroups", "templates\\twig\\base\\navigation.html.twig:81");
        $this->AddWordCode("Logout", "Logout", "templates\\twig\\base\\navigation.html.twig:82");
        $this->AddWordCode("toast.header", "toast.header", "templates\\widgets\\messages.toast.html.twig:3");
        $this->AddWordCode("toast.messages", "{0} There are no new messages|{1} There is one new message|]1,Inf[ There are %count% new messages", "templates\\widgets\\messages.toast.html.twig:10");
        $this->AddWordCode("toast.requests", "{0} There are no new requests|{1} There is one new request|]1,Inf[ There are %count% new requests", "templates\\widgets\\requests.toast.html.twig:10");
        $this->AddWordCode("Set spam status", "Set spam status", "src\\Controller\\Admin\\CheckerController.php:54");
        $this->AddWordCode("Comment is now hidden.", "Comment is now hidden.", "src\\Controller\\Admin\\CommentController.php:162");
        $this->AddWordCode("Comment is now visible again.", "Comment is now visible again.", "src\\Controller\\Admin\\CommentController.php:166");
        $this->AddWordCode("Comment can be edited by author now.", "Comment can be edited by author now.", "src\\Controller\\Admin\\CommentController.php:170");
        $this->AddWordCode("Comment is now locked.", "Comment is now locked.", "src\\Controller\\Admin\\CommentController.php:174");
        $this->AddWordCode("Comment was deleted.", "Comment was deleted.", "src\\Controller\\Admin\\CommentController.php:177");
        $this->AddWordCode("Comment has been assigned to safety team", "Comment has been assigned to safety team", "src\\Controller\\Admin\\CommentController.php:222");
        $this->AddWordCode("Comment has been marked as checked", "Comment has been marked as checked", "src\\Controller\\Admin\\CommentController.php:250");
        $this->AddWordCode("Comment has been hidden.", "Comment has been hidden.", "src\\Controller\\Admin\\CommentController.php:278");
        $this->AddWordCode("Comment is now visible.", "Comment is now visible.", "src\\Controller\\Admin\\CommentController.php:306");
        $this->AddWordCode("Something's weird", "Something's weird", "src\\Controller\\Admin\\TranslationController.php:251");
        $this->AddWordCode("Enabled translation mode", "Enabled translation mode", "src\\Controller\\Admin\\TranslationController.php:320");
        $this->AddWordCode("Disabled translation mode.", "Disabled translation mode.", "src\\Controller\\Admin\\TranslationController.php:322");
        $this->AddWordCode("admin.tools.not.allowed", "admin.tools.not.allowed", "src\\Controller\\Admin\\VolunteerToolController.php:49");
        $this->AddWordCode("Changed username for %oldname% to %newname%", "Changed username for %oldname% to %newname%", "src\\Controller\\Admin\\VolunteerToolController.php:99");
        $this->AddWordCode("Updated image information", "Updated image information", "src\\Controller\\GalleryController.php:47");
        $this->AddWordCode("Moved group %name% into the discussion queue", "Moved group %name% into the discussion queue", "src\\Controller\\GroupController.php:240");
        $this->AddWordCode("Dismissed group %name%", "Dismissed group %name%", "src\\Controller\\GroupController.php:277");
        $this->AddWordCode("Approved creation for group %name% ", "Approved creation for group %name% ", "src\\Controller\\GroupController.php:320");
        $this->AddWordCode("We just sent you a mail with a link that allows you to reset your password.", "We just sent you a mail with a link that allows you to reset your password.", "src\\Controller\\MemberController.php:111");
        $this->AddWordCode("Either username or key aren't valid to reset the password.", "Either username or key aren't valid to reset the password.", "src\\Controller\\MemberController.php:142");
        $this->AddWordCode("Your password has been reset. Please login now with the new password.", "Your password has been reset. Please login now with the new password.", "src\\Controller\\MemberController.php:165");
        $this->AddWordCode("Your feedback couldn't be sent. Please try again later.", "Your feedback couldn't be sent. Please try again later.", "src\\Controller\\MemberController.php:231");
        $this->AddWordCode("Your feedback has been forwarded to the Safety Team.", "Your feedback has been forwarded to the Safety Team.", "src\\Controller\\MemberController.php:238");
        $this->AddWordCode("This member doesn't exist", "This member doesn't exist", "src\\Controller\\RequestAndMessageController.php:171");
        $this->AddWordCode("You have exceeded your message limit. Try again later", "You have exceeded your message limit. Try again later", "src\\Controller\\RequestAndMessageController.php:183");
        $this->AddWordCode("Message has been sent.", "Message has been sent.", "src\\Controller\\RequestAndMessageController.php:211");
        $this->AddWordCode("4032e56", "Message has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:215");
        $this->AddWordCode("You can't send yourself a hosting request.", "You can't send yourself a hosting request.", "src\\Controller\\RequestAndMessageController.php:242");
        $this->AddWordCode("not browseable", "not browseable", "src\\Controller\\RequestAndMessageController.php:248");
        $this->AddWordCode("You have exceeded your request limit. Try again later.", "You have exceeded your request limit. Try again later.", "src\\Controller\\RequestAndMessageController.php:256");
        $this->AddWordCode("Request has been sent.", "Request has been sent.", "src\\Controller\\RequestAndMessageController.php:293");
        $this->AddWordCode("b8d2eff", "Request has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:295");
        $this->AddWordCode("Messages and/or requests permanently deleted.", "Messages and/or requests permanently deleted.", "src\\Controller\\RequestAndMessageController.php:424");
        $this->AddWordCode("Messages and/or requests undeleted (see respective folders).", "Messages and/or requests undeleted (see respective folders).", "src\\Controller\\RequestAndMessageController.php:432");
        $this->AddWordCode("Messages and/or requests deleted (see deleted folder).", "Messages and/or requests deleted (see deleted folder).", "src\\Controller\\RequestAndMessageController.php:435");
        $this->AddWordCode("Messages marked as regular messages (and moved to inbox).", "Messages marked as regular messages (and moved to inbox).", "src\\Controller\\RequestAndMessageController.php:441");
        $this->AddWordCode("Messages marked as spam messages (and moved to spam folder).", "Messages marked as spam messages (and moved to spam folder).", "src\\Controller\\RequestAndMessageController.php:444");
        $this->AddWordCode("Reply has been sent.", "Reply has been sent.", "src\\Controller\\RequestAndMessageController.php:517");
        $this->AddWordCode("f590237", "Reply has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:519");
        $this->AddWordCode("This request can't be replied to anymore as the hosting period already started.", "This request can't be replied to anymore as the hosting period already started.", "src\\Controller\\RequestAndMessageController.php:568");
        $this->AddWordCode("Notification with updated information has been sent.", "Notification with updated information has been sent.", "src\\Controller\\RequestAndMessageController.php:610");
        $this->AddWordCode("Provided key or username isn't correct", "Provided key or username isn't correct", "src\\Controller\\SignupController.php:100");
        $this->AddWordCode("6a05cb7", "You just confirmed your email address and your profile got activated. Please login now and update your profile.", "src\\Controller\\SignupController.php:113");
        $this->AddWordCode("Provided key isn't correct", "Provided key isn't correct", "src\\Controller\\SignupController.php:117");
        $this->AddWordCode("trip.updated_successfully", "trip.updated_successfully", "src\\Controller\\TripController.php:89");
        $this->AddWordCode("Couldn't process markup. Please check content and fix.", "Couldn't process markup. Please check content and fix.", "src\\Controller\\WikiController.php:54");
        $this->AddWordCode("Updated wiki text", "Updated wiki text", "src\\Controller\\WikiController.php:100");
        $this->AddWordCode("Created wiki page", "Created wiki page", "src\\Controller\\WikiController.php:144");
        $this->AddWordCode("DeleteComment", "DeleteComment", "src\\Form\\AdminCommentFormType.php:22");
        $this->AddWordCode("MoveToNegative", "MoveToNegative", "src\\Form\\AdminCommentFormType.php:22");
        $this->AddWordCode("MarkAsAbuse", "MarkAsAbuse", "src\\Form\\AdminCommentFormType.php:22");
        $this->AddWordCode("MarkAsChecked", "MarkAsChecked", "src\\Form\\AdminCommentFormType.php:22");
        $this->AddWordCode("hideComment", "hideComment", "src\\Form\\AdminCommentFormType.php:49");
        $this->AddWordCode("showComment", "showComment", "src\\Form\\AdminCommentFormType.php:55");
        $this->AddWordCode("disableEditing", "disableEditing", "src\\Form\\AdminCommentFormType.php:62");
        $this->AddWordCode("allowEditing", "allowEditing", "src\\Form\\AdminCommentFormType.php:68");
        $this->AddWordCode("change", "change", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->AddWordCode("newUsername", "newUsername", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->AddWordCode("oldUsername", "oldUsername", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->AddWordCode("Old Username", "Old Username", "src\\Form\\ChangeUsernameFormType.php:27");
        $this->AddWordCode("New Username", "New Username", "src\\Form\\ChangeUsernameFormType.php:35");
        $this->AddWordCode("noSpamMessages", "noSpamMessages", "src\\Form\\CheckerIndexFormType.php:18");
        $this->AddWordCode("spamMessages", "spamMessages", "src\\Form\\CheckerIndexFormType.php:18");
        $this->AddWordCode("CommunityNewsCommentCreate", "CommunityNewsCommentCreate", "src\\Form\\CommunityNewsCommentType.php:20");
        $this->AddWordCode("Enter the title of the community news", "Enter the title of the community news", "src\\Form\\CommunityNewsType.php:23");
        $this->AddWordCode("Shall the community be visible to regular members yet?", "Shall the community be visible to regular members yet?", "src\\Form\\CommunityNewsType.php:41");
        $this->AddWordCode("text", "text", "src\\Form\\CommunityNewsType.php:22");
        $this->AddWordCode("Please enter the title", "Please enter the title", "src\\Form\\CommunityNewsType.php:25");
        $this->AddWordCode("This will be the body of the community news.", "This will be the body of the community news.", "src\\Form\\CommunityNewsType.php:34");
        $this->AddWordCode("translation.wordcode", "translation.wordcode", "src\\Form\\EditTranslationFormType.php:22");
        $this->AddWordCode("translation.description", "translation.description", "src\\Form\\EditTranslationFormType.php:26");
        $this->AddWordCode("translation.englishText", "translation.englishText", "src\\Form\\EditTranslationFormType.php:30");
        $this->AddWordCode("translation.locale", "translation.locale", "src\\Form\\EditTranslationFormType.php:34");
        $this->AddWordCode("update", "update", "src\\Form\\EditTranslationFormType.php:21");
        $this->AddWordCode("translatedText", "translatedText", "src\\Form\\EditTranslationFormType.php:21");
        $this->AddWordCode("FaqCategoryWordCode", "FaqCategoryWordCode", "src\\Form\\FaqCategoryFormType.php:25");
        $this->AddWordCode("FaqCategoryDescription", "FaqCategoryDescription", "src\\Form\\FaqCategoryFormType.php:31");
        $this->AddWordCode("FaqCategoryCreate", "FaqCategoryCreate", "src\\Form\\FaqCategoryFormType.php:59");
        $this->AddWordCode("FaqCategoryUpdate", "FaqCategoryUpdate", "src\\Form\\FaqCategoryFormType.php:65");
        $this->AddWordCode("FaqCategory", "FaqCategory", "src\\Form\\FaqFormType.php:24");
        $this->AddWordCode("FaqWordCode", "FaqWordCode", "src\\Form\\FaqFormType.php:30");
        $this->AddWordCode("FaqQuestion", "FaqQuestion", "src\\Form\\FaqFormType.php:33");
        $this->AddWordCode("FaqAnswer", "FaqAnswer", "src\\Form\\FaqFormType.php:40");
        $this->AddWordCode("FaqActive", "FaqActive", "src\\Form\\FaqFormType.php:46");
        $this->AddWordCode("FaqCreate", "FaqCreate", "src\\Form\\FaqFormType.php:55");
        $this->AddWordCode("FaqUpdate", "FaqUpdate", "src\\Form\\FaqFormType.php:61");
        $this->AddWordCode("types", "types", "src\\Form\\FeedbackFormType.php:19");
        $this->AddWordCode("term", "term", "src\\Form\\FindUserFormType.php:20");
        $this->AddWordCode("Part of username", "Part of username", "src\\Form\\FindUserFormType.php:24");
        $this->AddWordCode("title", "title", "src\\Form\\GalleryEditImageFormType.php:21");
        $this->AddWordCode("Image Title", "Image Title", "src\\Form\\GalleryEditImageFormType.php:24");
        $this->AddWordCode("Image Description", "Image Description", "src\\Form\\GalleryEditImageFormType.php:29");
        $this->AddWordCode("GroupsJoinPublic", "GroupsJoinPublic", "src\\Form\\GroupType.php:36");
        $this->AddWordCode("GroupsJoinApproved", "GroupsJoinApproved", "src\\Form\\GroupType.php:36");
        $this->AddWordCode("GroupsVisiblePosts", "GroupsVisiblePosts", "src\\Form\\GroupType.php:45");
        $this->AddWordCode("GroupsInvisiblePosts", "GroupsInvisiblePosts", "src\\Form\\GroupType.php:45");
        $this->AddWordCode("Group name", "Group name", "src\\Form\\GroupType.php:23");
        $this->AddWordCode("GroupsJoinHeading", "GroupsJoinHeading", "src\\Form\\GroupType.php:35");
        $this->AddWordCode("GroupsVisiblePostsHeading", "GroupsVisiblePostsHeading", "src\\Form\\GroupType.php:44");
        $this->AddWordCode("picture", "picture", "src\\Form\\GroupType.php:22");
        $this->AddWordCode("Please enter a name for the group", "Please enter a name for the group", "src\\Form\\GroupType.php:25");
        $this->AddWordCode("Please provide a meaningful description for the new group.", "Please provide a meaningful description for the new group.", "src\\Form\\GroupType.php:31");
        $this->AddWordCode("group.choose.group.image", "group.choose.group.image", "src\\Form\\GroupType.php:56");
        $this->AddWordCode("message", "message", "src\\Form\\HostingRequestAbstractType.php:34");
        $this->AddWordCode("flexible", "flexible", "src\\Form\\HostingRequestType.php:23");
        $this->AddWordCode("Arrival (date)", "Arrival (date)", "src\\Form\\HostingRequestType.php:30");
        $this->AddWordCode("Departure (date)", "Departure (date)", "src\\Form\\HostingRequestType.php:46");
        $this->AddWordCode("#", "#", "src\\Form\\HostingRequestType.php:61");
        $this->AddWordCode("purge", "purge", "src\\Form\\MessageIndexFormType.php:35");
        $this->AddWordCode("messages", "messages", "src\\Form\\MessageIndexFormType.php:20");
        $this->AddWordCode("Please enter a message.", "Please enter a message.", "src\\Form\\MessageToMemberType.php:21");
        $this->AddWordCode("Feedback on Comment", "Feedback on Comment", "src\\Form\\ReportCommentType.php:21");
        $this->AddWordCode("SendFeedback", "SendFeedback", "src\\Form\\ReportCommentType.php:20");
        $this->AddWordCode("search.username.ascending", "search.username.ascending", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("search.username.descending", "search.username.descending", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Accommodation (Yes, Maybe, No)", "Accommodation (Yes, Maybe, No)", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Accommodation (No, Maybe, Yes)", "Accommodation (No, Maybe, Yes)", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Distance ascending", "Distance ascending", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Distance descending", "Distance descending", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Last login (oldest first)", "Last login (oldest first)", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Last login (latest first)", "Last login (latest first)", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Member since (older member first)", "Member since (older member first)", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Member since (newer member first)", "Member since (newer member first)", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Number of comments ascending", "Number of comments ascending", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("Number of comments descending", "Number of comments descending", "src\\Form\\SearchFormType.php:180");
        $this->AddWordCode("TextToFind", "TextToFind", "src\\Form\\SearchFormType.php:35");
        $this->AddWordCode("Minimum age", "Minimum age", "src\\Form\\SearchFormType.php:116");
        $this->AddWordCode("Maximum age", "Maximum age", "src\\Form\\SearchFormType.php:127");
        $this->AddWordCode("search.hosts_at_least", "search.hosts_at_least", "src\\Form\\SearchFormType.php:157");
        $this->AddWordCode("TypicOffer_dinner", "TypicOffer_dinner", "src\\Form\\SearchFormType.php:264");
        $this->AddWordCode("TypicOffer_guidedtour", "TypicOffer_guidedtour", "src\\Form\\SearchFormType.php:268");
        $this->AddWordCode("TypicOffer_CanHostWheelChair", "TypicOffer_CanHostWheelChair", "src\\Form\\SearchFormType.php:272");
        $this->AddWordCode("SearchIncludeInactive", "SearchIncludeInactive", "src\\Form\\SearchFormType.php:276");
        $this->AddWordCode("in a radius of", "in a radius of", "src\\Form\\SearchFormType.php:314");
        $this->AddWordCode("items", "items", "src\\Form\\SearchFormType.php:156");
        $this->AddWordCode("order", "order", "src\\Form\\SearchFormType.php:156");
        $this->AddWordCode("Where are you going?", "Where are you going?", "src\\Form\\SearchFormType.php:30");
        $this->AddWordCode("update_map", "update_map", "src\\Form\\SearchGotoLocationFormType.php:44");
        $this->AddWordCode("message.subject", "message.subject", "src\\Form\\SubjectType.php:20");
        $this->AddWordCode("TripsLocationOptionLookingForAHost", "TripsLocationOptionLookingForAHost", "src\\Form\\SubTripType.php:42");
        $this->AddWordCode("TripsLocationOptionLikeToMeetUp", "TripsLocationOptionLikeToMeetUp", "src\\Form\\SubTripType.php:42");
        $this->AddWordCode("Additional Info", "Additional Info", "src\\Form\\SubTripType.php:41");
        $this->AddWordCode("departure", "departure", "src\\Form\\SubTripType.php:25");
        $this->AddWordCode("arrival", "arrival", "src\\Form\\SubTripType.php:25");
        $this->AddWordCode("englishText", "englishText", "src\\Form\\TranslationFormType.php:23");
        $this->AddWordCode("TripsAdditionalInfoSingle", "TripsAdditionalInfoSingle", "src\\Form\\TripType.php:48");
        $this->AddWordCode("TripsAdditionalInfoCouple", "TripsAdditionalInfoCouple", "src\\Form\\TripType.php:48");
        $this->AddWordCode("TripsAdditionalInfoFriendsMixed", "TripsAdditionalInfoFriendsMixed", "src\\Form\\TripType.php:48");
        $this->AddWordCode("TripsAdditionalInfoFriendsSame", "TripsAdditionalInfoFriendsSame", "src\\Form\\TripType.php:48");
        $this->AddWordCode("TripsAdditionalInfoFamily", "TripsAdditionalInfoFamily", "src\\Form\\TripType.php:48");
        $this->AddWordCode("Summary", "Summary", "src\\Form\\TripType.php:23");
        $this->AddWordCode("Description", "Description", "src\\Form\\TripType.php:29");
        $this->AddWordCode("Travellers", "Travellers", "src\\Form\\TripType.php:35");
        $this->AddWordCode("Give a short summary of your trip", "Give a short summary of your trip", "src\\Form\\TripType.php:25");
        $this->AddWordCode("Let people know what your trip is all about", "Let people know what your trip is all about", "src\\Form\\TripType.php:31");
    }

    public function down()
    {
        $this->RemoveWordCode('canofferneverask', 'Accommodation: No.', 'Tooltip for accommodation icons.');
        $this->RemoveWordCode('profile.contactinfo.socialmedia', 'Social Media', 'Headline on edit my profile');
        // $this->RemoveWordCode("activities", "Activities", "templates\\activity\\list.html.twig:21");
        // $this->RemoveWordCode("activities.number.attendees.yes", "%number%", "templates\\activity\\list.html.twig:49");
        // $this->RemoveWordCode("activities.number.attendees.maybe", "ActivitiesNumbAttendeesMaybe", "templates\\activity\\list.html.twig:50");
        // $this->RemoveWordCode("activity", "Activity", "templates\\activity\\show.html.twig:4");
        $this->RemoveWordCode("admin.checker.no.messages", "No messages have been reported as spam.", "templates\\admin\\checker\\index.html.twig:19");
        $this->RemoveWordCode("ok", "ok", "templates\\admin\\checker\\index.html.twig:35");
        $this->RemoveWordCode("spam", "spam", "templates\\admin\\checker\\index.html.twig:36");
        $this->RemoveWordCode("admin.comment.headline", "Admin - Comment", "templates\\admin\\comment\\comment.html.twig:5");
        $this->RemoveWordCode("admin.comments.to.all", "All comments to %username%", "templates\\admin\\comment\\comment.html.twig:25");
        $this->RemoveWordCode("admin.comments.from.all", "All comments from %username%", "templates\\admin\\comment\\comment.html.twig:26");
        $this->RemoveWordCode("admin.comments.all", "All Comments", "templates\\admin\\comment\\overview.html.twig:5");
        $this->RemoveWordCode("admin.comments.no.comments", "No comments found for these parameters.", "templates\\admin\\comment\\overview.html.twig:11");
        $this->RemoveWordCode("from", "from", "templates\\admin\\comment\\overview.html.twig:22");
        $this->RemoveWordCode("about", "about", "templates\\admin\\comment\\overview.html.twig:24");
        $this->RemoveWordCode("action", "action", "templates\\admin\\comment\\overview.html.twig:25");
        $this->RemoveWordCode("written", "written", "templates\\admin\\comment\\overview.html.twig:34");
        $this->RemoveWordCode("comment.quality", "Quality and Date", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("comment.where.met", "Where we met", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("comment.text", "Comment Text", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("comment.know", "How we know each other", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("admin.comment.edit", "Edit comment", "templates\\admin\\comment\\overview.html.twig:46");
        $this->RemoveWordCode("admin.comment.hide", "Hide", "templates\\admin\\comment\\overview.html.twig:48");
        $this->RemoveWordCode("admin.comment.show", "Show", "templates\\admin\\comment\\overview.html.twig:50");
        $this->RemoveWordCode("admin.comment.assign.safety", "Assign to safety team", "templates\\admin\\comment\\overview.html.twig:53");
        $this->RemoveWordCode("admin.comment.checked", "Mark as checked", "templates\\admin\\comment\\overview.html.twig:56");
        $this->RemoveWordCode("admin.community.news.headline", "Community News", "templates\\admin\\communitynews\\editcreate.html.twig:4");
        $this->RemoveWordCode("admin.logs.no.logs", "No logs found for these parameters.", "templates\\admin\\communitynews\\index.html.twig:25");
        $this->RemoveWordCode("create", "create", "templates\\admin\\communitynews\\list.html.twig:17");
        $this->RemoveWordCode("read.more", "Read more", "templates\\admin\\communitynews\\list.html.twig:39");
        $this->RemoveWordCode("admin.faq.edit.category", "Edit a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:13");
        $this->RemoveWordCode("admin.faq.create.category", "Create a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:15");
        $this->RemoveWordCode("admin.faq.category.update.order", "Update order", "templates\\admin\\faqs\\editcreate.category.html.twig:33");
        $this->RemoveWordCode("faq.create.category.label", "Create Category", "templates\\admin\\faqs\\sort.categories.html.twig:15");
        $this->RemoveWordCode("admin.faq.abstract", "This shows the list of all FAQ categories. You can drag the cards to change the sort order.", "templates\\admin\\faqs\\sort.categories.html.twig:31");
        $this->RemoveWordCode("admin.faq.edit", "Edit a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:13");
        $this->RemoveWordCode("admin.faq.create", "Create a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:15");
        $this->RemoveWordCode("admin.group.info", "Group Info", "templates\\admin\\groups\\approve.html.twig:16");
        $this->RemoveWordCode("admin.faq.sort.categories", "Sort categories", "Admin -> FAQ -> Category");
        $this->RemoveWordCode("admin.faq.sort.order.updated.flash", "Updated sort order of FAQ categories.", "src\\Controller\\Admin\\FaqController.php:376");
        $this->RemoveWordCode("admin.group.description", "Group Description", "templates\\admin\\groups\\approve.html.twig:17");
        $this->RemoveWordCode("admin.group.creator", "Creator", "templates\\admin\\groups\\approve.html.twig:18");
        $this->RemoveWordCode("admin.group.actions", "Actions", "templates\\admin\\groups\\approve.html.twig:19");
        $this->RemoveWordCode("admin.group.approve", "Approve group", "templates\\admin\\groups\\approve.html.twig:36");
        $this->RemoveWordCode("admin.group.dismiss", "Dismiss group", "templates\\admin\\groups\\approve.html.twig:37");
        $this->RemoveWordCode("admin.group.discussion", "Move group to discussion queue", "templates\\admin\\groups\\approve.html.twig:39");
        $this->RemoveWordCode("admin.group.no.group", "No groups need to be approved", "templates\\admin\\groups\\approve.html.twig:48");
        $this->RemoveWordCode("country", "Country", "templates\\admin\\tools\\age.country.html.twig:14");
        $this->RemoveWordCode("birth.year", "Birth Year", "templates\\admin\\tools\\age.country.html.twig:16");
        $this->RemoveWordCode("age", "Age", "templates\\admin\\tools\\age.country.html.twig:17");
        $this->RemoveWordCode("admin.feedback.no.feedback", "No feedback found for these parameters.", "templates\\admin\\tools\\check.feedback.html.twig:27");
        $this->RemoveWordCode("robots", "robots", "templates\\base-lite.html.twig:21");
        $this->RemoveWordCode("communitynews.comments", "%commentsCount% comments", "templates\\communitynews\\list.html.twig:21");
        $this->RemoveWordCode("email.greeting", "Dear %username%,", "templates\\emails\\reset.password.html.twig:4");
        $this->RemoveWordCode("email.reset.password.ignore", "If you received this email without asking for a password reset, please let us no on %link_start%Contact Us%link_end%", "Paragraph in the password reset email.");
        $this->RemoveWordCode("footer.site.language", "footer.site.language", "templates\\footer.html.twig:25");
        $this->RemoveWordCode("translation.information", "Translation information", "templates\\footer.html.twig:85");
        $this->RemoveWordCode("translation.translatable", "Translatable items", "templates\\footer.html.twig:104");
        $this->RemoveWordCode("translation.existing", "Existing translations", "templates\\footer.html.twig:156");
        $this->RemoveWordCode("translation.existing.info", "The list shows all translatable items that have an existing translation in the current locale.", "templates\\footer.html.twig:157");
        $this->RemoveWordCode("translation.fallback", "Fallback Translations", "templates\\footer.html.twig:171");
        $this->RemoveWordCode("translation.fallback.info", "The list shows all translations that match the English original text.", "templates\\footer.html.twig:172");
        $this->RemoveWordCode("translation.keyword.doesnt.exist", "Translations keyword doesn't exist", "templates\\footer.html.twig:185");
        $this->RemoveWordCode("default_meta_robots", "default_meta_robots", "templates\\home\\home.html.twig:13");
        $this->RemoveWordCode("The world is just one step from here", "The world is just one step from here", "templates\\home\\home.html.twig:125");
        $this->RemoveWordCode("indexpageword_share", "IndexPageWord_share", "templates\\home\\home.html.twig:137");
        $this->RemoveWordCode("choose.username", "Choose your username!", "templates\\home\\home.html.twig:140");
        $this->RemoveWordCode("search", "Search", "templates\\home\\home.html.twig:175");
        $this->RemoveWordCode("aboutuspage", "About Us", "templates\\home\\home.html.twig:192");
        $this->RemoveWordCode("termsofuse", "Terms Of Use", "templates\\home\\home.html.twig:193");
        $this->RemoveWordCode("copyrightbybv", "Copyright by BeVolunteer", "templates\\home\\home.html.twig:200");
        $this->RemoveWordCode("running.on", "Running on", "templates\\home\\home.html.twig:201");
        $this->RemoveWordCode("dashboard.donation.received", "dashboard.donation.received", "templates\\landing\\landing.html.twig:207");
        $this->RemoveWordCode("hosting", "hosting", "templates\\landing\\widget\\accommodation.html.twig:3");
        $this->RemoveWordCode("maybe hosting", "maybe hosting", "templates\\landing\\widget\\accommodation.html.twig:4");
        $this->RemoveWordCode("not hosting", "not hosting", "templates\\landing\\widget\\accommodation.html.twig:5");
        $this->RemoveWordCode("bewelcome", "BeWelcome", "templates\\loginbar.html.twig:8");
        $this->RemoveWordCode("login", "Login", "templates\\loginbar.html.twig:13");
        $this->RemoveWordCode("password.reset", "Reset Password", "templates\\member\\request.password.reset.html.twig:5");
        $this->RemoveWordCode("member", "Member", "templates\\member\\results.html.twig:11");
        $this->RemoveWordCode("profile.summary", "profile summary", "templates\\member\\results.html.twig:12");
        $this->RemoveWordCode("details", "details", "templates\\member\\results.html.twig:13");
        $this->RemoveWordCode("SearchYearsOld", "SearchYearsOld", "templates\\member\\results.html.twig:36");
        $this->RemoveWordCode("SearchCommentsInfo", "SearchCommentsInfo", "templates\\member\\results.html.twig:65");
        $this->RemoveWordCode("SearchMemberLastLoginInfo", "SearchMemberLastLoginInfo", "templates\\member\\results.html.twig:69");
        $this->RemoveWordCode("SearchMemberSinceInfo", "SearchMemberSinceInfo", "templates\\member\\results.html.twig:70");
        $this->RemoveWordCode("Date", "Date", "templates\\message\\index.html.twig:45");
        $this->RemoveWordCode("MessagesText", "MessagesText", "templates\\message\\index.html.twig:47");
        $this->RemoveWordCode("View", "View", "templates\\message\\index.html.twig:98");
        $this->RemoveWordCode("MessagesWarningConfirmDelete", "MessagesWarningConfirmDelete", "templates\\message\\index.html.twig:109");
        $this->RemoveWordCode("Profile", "Profile", "templates\\message\\thread.html.twig:23");
        $this->RemoveWordCode("Last login:", "Last login:", "templates\\profile\\cards\\hosting.html.twig:32");
        $this->RemoveWordCode("never", "never", "templates\\profile\\cards\\hosting.html.twig:32");
        $this->RemoveWordCode("MyPreferences", "MyPreferences", "templates\\profile\\view.html.twig:14");
        $this->RemoveWordCode("years old", "years old", "templates\\profile\\view.html.twig:57");
        $this->RemoveWordCode("EditMyProfile", "EditMyProfile", "templates\\profile\\view.html.twig:75");
        $this->RemoveWordCode("IndexPageTeaserOpenDoor", "IndexPageTeaserOpenDoor", "templates\\security\\login.html.twig:20");
        $this->RemoveWordCode("Username", "Username", "templates\\security\\login.html.twig:43");
        $this->RemoveWordCode("Password", "Password", "templates\\security\\login.html.twig:49");
        $this->RemoveWordCode("StayLoggedIn", "StayLoggedIn", "templates\\security\\login.html.twig:56");
        $this->RemoveWordCode("IndexPageLoginSubmit", "IndexPageLoginSubmit", "templates\\security\\login.html.twig:67");
        $this->RemoveWordCode("SignupNow", "SignupNow", "templates\\security\\login.html.twig:78");
        $this->RemoveWordCode("IndexPageWord17", "IndexPageWord17", "templates\\security\\login.html.twig:79");
        $this->RemoveWordCode("All trips", "All trips", "templates\\trip\\list.html.twig:4");
        $this->RemoveWordCode("trip.no_trips_found", "trip.no_trips_found", "templates\\trip\\list.html.twig:33");
        $this->RemoveWordCode("Trip", "Trip", "templates\\trip\\show.html.twig:4");
        $this->RemoveWordCode("FindMembers", "FindMembers", "templates\\twig\\base\\navigation.html.twig:12");
        $this->RemoveWordCode("MapSearch", "MapSearch", "templates\\twig\\base\\navigation.html.twig:15");
        $this->RemoveWordCode("TextSearch", "TextSearch", "templates\\twig\\base\\navigation.html.twig:16");
        $this->RemoveWordCode("BrowseCountries", "BrowseCountries", "templates\\twig\\base\\navigation.html.twig:17");
        $this->RemoveWordCode("CommunityMenu", "CommunityMenu", "templates\\twig\\base\\navigation.html.twig:22");
        $this->RemoveWordCode("AgoraTagLine", "AgoraTagLine", "templates\\twig\\base\\navigation.html.twig:25");
        $this->RemoveWordCode("CommunityDiscussions", "CommunityDiscussions", "templates\\twig\\base\\navigation.html.twig:25");
        $this->RemoveWordCode("GroupTagLine", "GroupTagLine", "templates\\twig\\base\\navigation.html.twig:26");
        $this->RemoveWordCode("Groups", "Groups", "templates\\twig\\base\\navigation.html.twig:26");
        $this->RemoveWordCode("Suggestions", "Suggestions", "templates\\twig\\base\\navigation.html.twig:28");
        $this->RemoveWordCode("Trips", "Trips", "templates\\twig\\base\\navigation.html.twig:29");
        $this->RemoveWordCode("Blogs", "Blogs", "templates\\twig\\base\\navigation.html.twig:30");
        $this->RemoveWordCode("Wiki", "Wiki", "templates\\twig\\base\\navigation.html.twig:31");
        $this->RemoveWordCode("Safety", "Safety", "templates\\twig\\base\\navigation.html.twig:36");
        $this->RemoveWordCode("GetAnswers", "GetAnswers", "templates\\twig\\base\\navigation.html.twig:40");
        $this->RemoveWordCode("FAQ", "FAQ", "templates\\twig\\base\\navigation.html.twig:42");
        $this->RemoveWordCode("ContactUs", "ContactUs", "templates\\twig\\base\\navigation.html.twig:43");
        $this->RemoveWordCode("About_GetActive", "About_GetActive", "templates\\twig\\base\\navigation.html.twig:44");
        $this->RemoveWordCode("DonateLink", "DonateLink", "templates\\twig\\base\\navigation.html.twig:45");
        $this->RemoveWordCode("Volunteer", "Volunteer", "templates\\twig\\base\\navigation.html.twig:55");
        $this->RemoveWordCode("MyMessages", "MyMessages", "templates\\twig\\base\\navigation.html.twig:79");
        $this->RemoveWordCode("ProfileMyNotes", "ProfileMyNotes", "templates\\twig\\base\\navigation.html.twig:80");
        $this->RemoveWordCode("MyGroups", "MyGroups", "templates\\twig\\base\\navigation.html.twig:81");
        $this->RemoveWordCode("Logout", "Logout", "templates\\twig\\base\\navigation.html.twig:82");
        $this->RemoveWordCode("toast.header", "toast.header", "templates\\widgets\\messages.toast.html.twig:3");
        $this->RemoveWordCode("toast.messages", "{0} There are no new messages|{1} There is one new message|]1,Inf[ There are %count% new messages", "templates\\widgets\\messages.toast.html.twig:10");
        $this->RemoveWordCode("toast.requests", "{0} There are no new requests|{1} There is one new request|]1,Inf[ There are %count% new requests", "templates\\widgets\\requests.toast.html.twig:10");
        $this->RemoveWordCode("Set spam status", "Set spam status", "src\\Controller\\Admin\\CheckerController.php:54");
        $this->RemoveWordCode("Comment is now hidden.", "Comment is now hidden.", "src\\Controller\\Admin\\CommentController.php:162");
        $this->RemoveWordCode("Comment is now visible again.", "Comment is now visible again.", "src\\Controller\\Admin\\CommentController.php:166");
        $this->RemoveWordCode("Comment can be edited by author now.", "Comment can be edited by author now.", "src\\Controller\\Admin\\CommentController.php:170");
        $this->RemoveWordCode("Comment is now locked.", "Comment is now locked.", "src\\Controller\\Admin\\CommentController.php:174");
        $this->RemoveWordCode("Comment was deleted.", "Comment was deleted.", "src\\Controller\\Admin\\CommentController.php:177");
        $this->RemoveWordCode("Comment has been assigned to safety team", "Comment has been assigned to safety team", "src\\Controller\\Admin\\CommentController.php:222");
        $this->RemoveWordCode("Comment has been marked as checked", "Comment has been marked as checked", "src\\Controller\\Admin\\CommentController.php:250");
        $this->RemoveWordCode("Comment has been hidden.", "Comment has been hidden.", "src\\Controller\\Admin\\CommentController.php:278");
        $this->RemoveWordCode("Comment is now visible.", "Comment is now visible.", "src\\Controller\\Admin\\CommentController.php:306");
        $this->RemoveWordCode("Something's weird", "Something's weird", "src\\Controller\\Admin\\TranslationController.php:251");
        $this->RemoveWordCode("Enabled translation mode", "Enabled translation mode", "src\\Controller\\Admin\\TranslationController.php:320");
        $this->RemoveWordCode("Disabled translation mode.", "Disabled translation mode.", "src\\Controller\\Admin\\TranslationController.php:322");
        $this->RemoveWordCode("admin.tools.not.allowed", "admin.tools.not.allowed", "src\\Controller\\Admin\\VolunteerToolController.php:49");
        $this->RemoveWordCode("Changed username for %oldname% to %newname%", "Changed username for %oldname% to %newname%", "src\\Controller\\Admin\\VolunteerToolController.php:99");
        $this->RemoveWordCode("Updated image information", "Updated image information", "src\\Controller\\GalleryController.php:47");
        $this->RemoveWordCode("Moved group %name% into the discussion queue", "Moved group %name% into the discussion queue", "src\\Controller\\GroupController.php:240");
        $this->RemoveWordCode("Dismissed group %name%", "Dismissed group %name%", "src\\Controller\\GroupController.php:277");
        $this->RemoveWordCode("Approved creation for group %name% ", "Approved creation for group %name% ", "src\\Controller\\GroupController.php:320");
        $this->RemoveWordCode("We just sent you a mail with a link that allows you to reset your password.", "We just sent you a mail with a link that allows you to reset your password.", "src\\Controller\\MemberController.php:111");
        $this->RemoveWordCode("Either username or key aren't valid to reset the password.", "Either username or key aren't valid to reset the password.", "src\\Controller\\MemberController.php:142");
        $this->RemoveWordCode("Your password has been reset. Please login now with the new password.", "Your password has been reset. Please login now with the new password.", "src\\Controller\\MemberController.php:165");
        $this->RemoveWordCode("Your feedback couldn't be sent. Please try again later.", "Your feedback couldn't be sent. Please try again later.", "src\\Controller\\MemberController.php:231");
        $this->RemoveWordCode("Your feedback has been forwarded to the Safety Team.", "Your feedback has been forwarded to the Safety Team.", "src\\Controller\\MemberController.php:238");
        $this->RemoveWordCode("This member doesn't exist", "This member doesn't exist", "src\\Controller\\RequestAndMessageController.php:171");
        $this->RemoveWordCode("You have exceeded your message limit. Try again later", "You have exceeded your message limit. Try again later", "src\\Controller\\RequestAndMessageController.php:183");
        $this->RemoveWordCode("Message has been sent.", "Message has been sent.", "src\\Controller\\RequestAndMessageController.php:211");
        $this->RemoveWordCode("4032e56", "Message has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:215");
        $this->RemoveWordCode("You can't send yourself a hosting request.", "You can't send yourself a hosting request.", "src\\Controller\\RequestAndMessageController.php:242");
        $this->RemoveWordCode("not browseable", "not browseable", "src\\Controller\\RequestAndMessageController.php:248");
        $this->RemoveWordCode("You have exceeded your request limit. Try again later.", "You have exceeded your request limit. Try again later.", "src\\Controller\\RequestAndMessageController.php:256");
        $this->RemoveWordCode("Request has been sent.", "Request has been sent.", "src\\Controller\\RequestAndMessageController.php:293");
        $this->RemoveWordCode("b8d2eff", "Request has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:295");
        $this->RemoveWordCode("Messages and/or requests permanently deleted.", "Messages and/or requests permanently deleted.", "src\\Controller\\RequestAndMessageController.php:424");
        $this->RemoveWordCode("Messages and/or requests undeleted (see respective folders).", "Messages and/or requests undeleted (see respective folders).", "src\\Controller\\RequestAndMessageController.php:432");
        $this->RemoveWordCode("Messages and/or requests deleted (see deleted folder).", "Messages and/or requests deleted (see deleted folder).", "src\\Controller\\RequestAndMessageController.php:435");
        $this->RemoveWordCode("Messages marked as regular messages (and moved to inbox).", "Messages marked as regular messages (and moved to inbox).", "src\\Controller\\RequestAndMessageController.php:441");
        $this->RemoveWordCode("Messages marked as spam messages (and moved to spam folder).", "Messages marked as spam messages (and moved to spam folder).", "src\\Controller\\RequestAndMessageController.php:444");
        $this->RemoveWordCode("Reply has been sent.", "Reply has been sent.", "src\\Controller\\RequestAndMessageController.php:517");
        $this->RemoveWordCode("f590237", "Reply has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:519");
        $this->RemoveWordCode("This request can't be replied to anymore as the hosting period already started.", "This request can't be replied to anymore as the hosting period already started.", "src\\Controller\\RequestAndMessageController.php:568");
        $this->RemoveWordCode("Notification with updated information has been sent.", "Notification with updated information has been sent.", "src\\Controller\\RequestAndMessageController.php:610");
        $this->RemoveWordCode("Provided key or username isn't correct", "Provided key or username isn't correct", "src\\Controller\\SignupController.php:100");
        $this->RemoveWordCode("6a05cb7", "You just confirmed your email address and your profile got activated. Please login now and update your profile.", "src\\Controller\\SignupController.php:113");
        $this->RemoveWordCode("Provided key isn't correct", "Provided key isn't correct", "src\\Controller\\SignupController.php:117");
        $this->RemoveWordCode("trip.updated_successfully", "trip.updated_successfully", "src\\Controller\\TripController.php:89");
        $this->RemoveWordCode("Couldn't process markup. Please check content and fix.", "Couldn't process markup. Please check content and fix.", "src\\Controller\\WikiController.php:54");
        $this->RemoveWordCode("Updated wiki text", "Updated wiki text", "src\\Controller\\WikiController.php:100");
        $this->RemoveWordCode("Created wiki page", "Created wiki page", "src\\Controller\\WikiController.php:144");
        $this->RemoveWordCode("DeleteComment", "DeleteComment", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("MoveToNegative", "MoveToNegative", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("MarkAsAbuse", "MarkAsAbuse", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("MarkAsChecked", "MarkAsChecked", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("hideComment", "hideComment", "src\\Form\\AdminCommentFormType.php:49");
        $this->RemoveWordCode("showComment", "showComment", "src\\Form\\AdminCommentFormType.php:55");
        $this->RemoveWordCode("disableEditing", "disableEditing", "src\\Form\\AdminCommentFormType.php:62");
        $this->RemoveWordCode("allowEditing", "allowEditing", "src\\Form\\AdminCommentFormType.php:68");
        $this->RemoveWordCode("change", "change", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->RemoveWordCode("newUsername", "newUsername", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->RemoveWordCode("oldUsername", "oldUsername", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->RemoveWordCode("Old Username", "Old Username", "src\\Form\\ChangeUsernameFormType.php:27");
        $this->RemoveWordCode("New Username", "New Username", "src\\Form\\ChangeUsernameFormType.php:35");
        $this->RemoveWordCode("noSpamMessages", "noSpamMessages", "src\\Form\\CheckerIndexFormType.php:18");
        $this->RemoveWordCode("spamMessages", "spamMessages", "src\\Form\\CheckerIndexFormType.php:18");
        $this->RemoveWordCode("Title", "Title", "src\\Form\\CommunityNewsCommentType.php:21");
        $this->RemoveWordCode("CommunityNewsCommentCreate", "CommunityNewsCommentCreate", "src\\Form\\CommunityNewsCommentType.php:20");
        $this->RemoveWordCode("Enter the title of the community news", "Enter the title of the community news", "src\\Form\\CommunityNewsType.php:23");
        $this->RemoveWordCode("Shall the community be visible to regular members yet?", "Shall the community be visible to regular members yet?", "src\\Form\\CommunityNewsType.php:41");
        $this->RemoveWordCode("text", "text", "src\\Form\\CommunityNewsType.php:22");
        $this->RemoveWordCode("Please enter the title", "Please enter the title", "src\\Form\\CommunityNewsType.php:25");
        $this->RemoveWordCode("This will be the body of the community news.", "This will be the body of the community news.", "src\\Form\\CommunityNewsType.php:34");
        $this->RemoveWordCode("translation.wordcode", "translation.wordcode", "src\\Form\\EditTranslationFormType.php:22");
        $this->RemoveWordCode("translation.description", "translation.description", "src\\Form\\EditTranslationFormType.php:26");
        $this->RemoveWordCode("translation.englishText", "translation.englishText", "src\\Form\\EditTranslationFormType.php:30");
        $this->RemoveWordCode("translation.locale", "translation.locale", "src\\Form\\EditTranslationFormType.php:34");
        $this->RemoveWordCode("update", "update", "src\\Form\\EditTranslationFormType.php:21");
        $this->RemoveWordCode("translatedText", "translatedText", "src\\Form\\EditTranslationFormType.php:21");
        $this->RemoveWordCode("FaqCategoryWordCode", "FaqCategoryWordCode", "src\\Form\\FaqCategoryFormType.php:25");
        $this->RemoveWordCode("FaqCategoryDescription", "FaqCategoryDescription", "src\\Form\\FaqCategoryFormType.php:31");
        $this->RemoveWordCode("FaqCategoryCreate", "FaqCategoryCreate", "src\\Form\\FaqCategoryFormType.php:59");
        $this->RemoveWordCode("FaqCategoryUpdate", "FaqCategoryUpdate", "src\\Form\\FaqCategoryFormType.php:65");
        $this->RemoveWordCode("FaqCategory", "FaqCategory", "src\\Form\\FaqFormType.php:24");
        $this->RemoveWordCode("FaqWordCode", "FaqWordCode", "src\\Form\\FaqFormType.php:30");
        $this->RemoveWordCode("FaqQuestion", "FaqQuestion", "src\\Form\\FaqFormType.php:33");
        $this->RemoveWordCode("FaqAnswer", "FaqAnswer", "src\\Form\\FaqFormType.php:40");
        $this->RemoveWordCode("FaqActive", "FaqActive", "src\\Form\\FaqFormType.php:46");
        $this->RemoveWordCode("FaqCreate", "FaqCreate", "src\\Form\\FaqFormType.php:55");
        $this->RemoveWordCode("FaqUpdate", "FaqUpdate", "src\\Form\\FaqFormType.php:61");
        $this->RemoveWordCode("types", "types", "src\\Form\\FeedbackFormType.php:19");
        $this->RemoveWordCode("term", "term", "src\\Form\\FindUserFormType.php:20");
        $this->RemoveWordCode("Part of username", "Part of username", "src\\Form\\FindUserFormType.php:24");
        $this->RemoveWordCode("title", "title", "src\\Form\\GalleryEditImageFormType.php:21");
        $this->RemoveWordCode("Image Title", "Image Title", "src\\Form\\GalleryEditImageFormType.php:24");
        $this->RemoveWordCode("Image Description", "Image Description", "src\\Form\\GalleryEditImageFormType.php:29");
        $this->RemoveWordCode("GroupsJoinPublic", "GroupsJoinPublic", "src\\Form\\GroupType.php:36");
        $this->RemoveWordCode("GroupsJoinApproved", "GroupsJoinApproved", "src\\Form\\GroupType.php:36");
        $this->RemoveWordCode("GroupsVisiblePosts", "GroupsVisiblePosts", "src\\Form\\GroupType.php:45");
        $this->RemoveWordCode("GroupsInvisiblePosts", "GroupsInvisiblePosts", "src\\Form\\GroupType.php:45");
        $this->RemoveWordCode("Group name", "Group name", "src\\Form\\GroupType.php:23");
        $this->RemoveWordCode("GroupsJoinHeading", "GroupsJoinHeading", "src\\Form\\GroupType.php:35");
        $this->RemoveWordCode("GroupsVisiblePostsHeading", "GroupsVisiblePostsHeading", "src\\Form\\GroupType.php:44");
        $this->RemoveWordCode("picture", "picture", "src\\Form\\GroupType.php:22");
        $this->RemoveWordCode("Please enter a name for the group", "Please enter a name for the group", "src\\Form\\GroupType.php:25");
        $this->RemoveWordCode("Please provide a meaningful description for the new group.", "Please provide a meaningful description for the new group.", "src\\Form\\GroupType.php:31");
        $this->RemoveWordCode("group.choose.group.image", "group.choose.group.image", "src\\Form\\GroupType.php:56");
        $this->RemoveWordCode("message", "message", "src\\Form\\HostingRequestAbstractType.php:34");
        $this->RemoveWordCode("flexible", "flexible", "src\\Form\\HostingRequestType.php:23");
        $this->RemoveWordCode("Arrival (date)", "Arrival (date)", "src\\Form\\HostingRequestType.php:30");
        $this->RemoveWordCode("Departure (date)", "Departure (date)", "src\\Form\\HostingRequestType.php:46");
        $this->RemoveWordCode("#", "#", "src\\Form\\HostingRequestType.php:61");
        $this->RemoveWordCode("purge", "purge", "src\\Form\\MessageIndexFormType.php:35");
        $this->RemoveWordCode("messages", "messages", "src\\Form\\MessageIndexFormType.php:20");
        $this->RemoveWordCode("Please enter a message.", "Please enter a message.", "src\\Form\\MessageToMemberType.php:21");
        $this->RemoveWordCode("Feedback on Comment", "Feedback on Comment", "src\\Form\\ReportCommentType.php:21");
        $this->RemoveWordCode("SendFeedback", "SendFeedback", "src\\Form\\ReportCommentType.php:20");
        $this->RemoveWordCode("search.username.ascending", "search.username.ascending", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("search.username.descending", "search.username.descending", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Accommodation (Yes, Maybe, No)", "Accommodation (Yes, Maybe, No)", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Accommodation (No, Maybe, Yes)", "Accommodation (No, Maybe, Yes)", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Distance ascending", "Distance ascending", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Distance descending", "Distance descending", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Last login (oldest first)", "Last login (oldest first)", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Last login (latest first)", "Last login (latest first)", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Member since (older member first)", "Member since (older member first)", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Member since (newer member first)", "Member since (newer member first)", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Number of comments ascending", "Number of comments ascending", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("Number of comments descending", "Number of comments descending", "src\\Form\\SearchFormType.php:180");
        $this->RemoveWordCode("TextToFind", "TextToFind", "src\\Form\\SearchFormType.php:35");
        $this->RemoveWordCode("Minimum age", "Minimum age", "src\\Form\\SearchFormType.php:116");
        $this->RemoveWordCode("Maximum age", "Maximum age", "src\\Form\\SearchFormType.php:127");
        $this->RemoveWordCode("search.hosts_at_least", "search.hosts_at_least", "src\\Form\\SearchFormType.php:157");
        $this->RemoveWordCode("TypicOffer_dinner", "TypicOffer_dinner", "src\\Form\\SearchFormType.php:264");
        $this->RemoveWordCode("TypicOffer_guidedtour", "TypicOffer_guidedtour", "src\\Form\\SearchFormType.php:268");
        $this->RemoveWordCode("TypicOffer_CanHostWheelChair", "TypicOffer_CanHostWheelChair", "src\\Form\\SearchFormType.php:272");
        $this->RemoveWordCode("SearchIncludeInactive", "SearchIncludeInactive", "src\\Form\\SearchFormType.php:276");
        $this->RemoveWordCode("in a radius of", "in a radius of", "src\\Form\\SearchFormType.php:314");
        $this->RemoveWordCode("items", "items", "src\\Form\\SearchFormType.php:156");
        $this->RemoveWordCode("order", "order", "src\\Form\\SearchFormType.php:156");
        $this->RemoveWordCode("Where are you going?", "Where are you going?", "src\\Form\\SearchFormType.php:30");
        $this->RemoveWordCode("update_map", "update_map", "src\\Form\\SearchGotoLocationFormType.php:44");
        $this->RemoveWordCode("message.subject", "message.subject", "src\\Form\\SubjectType.php:20");
        $this->RemoveWordCode("TripsLocationOptionLookingForAHost", "TripsLocationOptionLookingForAHost", "src\\Form\\SubTripType.php:42");
        $this->RemoveWordCode("TripsLocationOptionLikeToMeetUp", "TripsLocationOptionLikeToMeetUp", "src\\Form\\SubTripType.php:42");
        $this->RemoveWordCode("Additional Info", "Additional Info", "src\\Form\\SubTripType.php:41");
        $this->RemoveWordCode("departure", "departure", "src\\Form\\SubTripType.php:25");
        $this->RemoveWordCode("arrival", "arrival", "src\\Form\\SubTripType.php:25");
        $this->RemoveWordCode("englishText", "englishText", "src\\Form\\TranslationFormType.php:23");
        $this->RemoveWordCode("TripsAdditionalInfoSingle", "TripsAdditionalInfoSingle", "src\\Form\\TripType.php:48");
        $this->RemoveWordCode("TripsAdditionalInfoCouple", "TripsAdditionalInfoCouple", "src\\Form\\TripType.php:48");
        $this->RemoveWordCode("TripsAdditionalInfoFriendsMixed", "TripsAdditionalInfoFriendsMixed", "src\\Form\\TripType.php:48");
        $this->RemoveWordCode("TripsAdditionalInfoFriendsSame", "TripsAdditionalInfoFriendsSame", "src\\Form\\TripType.php:48");
        $this->RemoveWordCode("TripsAdditionalInfoFamily", "TripsAdditionalInfoFamily", "src\\Form\\TripType.php:48");
        $this->RemoveWordCode("Summary", "Summary", "src\\Form\\TripType.php:23");
        $this->RemoveWordCode("Description", "Description", "src\\Form\\TripType.php:29");
        $this->RemoveWordCode("Travellers", "Travellers", "src\\Form\\TripType.php:35");
        $this->RemoveWordCode("Give a short summary of your trip", "Give a short summary of your trip", "src\\Form\\TripType.php:25");
        $this->RemoveWordCode("Let people know what your trip is all about", "Let people know what your trip is all about", "src\\Form\\TripType.php:31");
    }
}
