<?php


use Rox\Tools\RoxMigration;

class MoreMissingWordCodes extends RoxMigration
{
    public function up()
    {
        try {
            $this->AddWordCode('canofferneverask', 'Accommodation: No.', 'Tooltip for accommodation icons.');
            $this->AddWordCode('profile.contactinfo.socialmedia', 'Social Media', 'Headline on edit my profile');// $this->AddWordCode("activities", "Activities", "templates\\activity\\list.html.twig:21");
            // $this->AddWordCode("activities.number.attendees.yes", "%number%", "templates\\activity\\list.html.twig:49");
            // $this->AddWordCode("activities.number.attendees.maybe", "ActivitiesNumbAttendeesMaybe", "templates\\activity\\list.html.twig:50");
            // $this->AddWordCode("activity", "Activity", "templates\\activity\\show.html.twig:4");
            $this->AddWordCode("admin.checker.no.messages", "No messages have been reported as spam.", "templates\\admin\\checker\\index.html.twig:19");
            $this->AddWordCode("ok", "ok", "templates\\admin\\checker\\index.html.twig:35");
            $this->AddWordCode("spam", "spam", "templates\\admin\\checker\\index.html.twig:36");
            $this->AddWordCode("admin.comment.headline", "Admin - Comment", "templates\\admin\\comment\\comment.html.twig:5");
            $this->AddWordCode("admin.comments.to.all", "All comments to %username%", "templates\\admin\\comment\\comment.html.twig:25");
            $this->AddWordCode("admin.comments.from.all", "All comments from %username%", "templates\\admin\\comment\\comment.html.twig:26");
            $this->AddWordCode("admin.comments.all", "All Comments", "templates\\admin\\comment\\overview.html.twig:5");
            $this->AddWordCode("admin.comments.no.comments", "No comments found for these parameters.", "templates\\admin\\comment\\overview.html.twig:11");
            $this->AddWordCode("from", "from", "templates\\admin\\comment\\overview.html.twig:22");
            $this->AddWordCode("about", "about", "templates\\admin\\comment\\overview.html.twig:24");
            $this->AddWordCode("action", "action", "templates\\admin\\comment\\overview.html.twig:25");
            $this->AddWordCode("written", "written", "templates\\admin\\comment\\overview.html.twig:34");
            $this->AddWordCode("comment.quality", "Quality and Date", "templates\\admin\\comment\\overview.html.twig");
            $this->AddWordCode("comment.where.met", "Where we met", "templates\\admin\\comment\\overview.html.twig");
            $this->AddWordCode("comment.text", "Comment Text", "templates\\admin\\comment\\overview.html.twig");
            $this->AddWordCode("comment.know", "How we know each other", "templates\\admin\\comment\\overview.html.twig");
            $this->AddWordCode("admin.comment.edit", "Edit comment", "templates\\admin\\comment\\overview.html.twig:46");
            $this->AddWordCode("admin.comment.hide", "Hide", "templates\\admin\\comment\\overview.html.twig:48");
            $this->AddWordCode("admin.comment.show", "Show", "templates\\admin\\comment\\overview.html.twig:50");
            $this->AddWordCode("admin.comment.assign.safety", "Assign to safety team", "templates\\admin\\comment\\overview.html.twig:53");
            $this->AddWordCode("admin.comment.checked", "Mark as checked", "templates\\admin\\comment\\overview.html.twig:56");
            $this->AddWordCode("admin.community.news.headline", "Community News", "templates\\admin\\communitynews\\editcreate.html.twig:4");
            $this->AddWordCode("admin.community.news.no.news", "No community news exist.", "templates\\admin\\communitynews\\index.html.twig:25");
            $this->AddWordCode("admin.logs.no.logs", "No logs found for these parameters.", "templates\\admin\\logs\\index.html.twig:25");
            $this->AddWordCode("create", "create", "templates\\admin\\communitynews\\list.html.twig:17");
            $this->AddWordCode("read.more", "Read more", "templates\\admin\\communitynews\\list.html.twig:39");
            $this->AddWordCode("admin.faq.edit.category", "Edit a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:13");
            $this->AddWordCode("admin.faq.create.category", "Create a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:15");
            $this->AddWordCode("admin.faq.category.update.order", "Update order", "templates\\admin\\faqs\\editcreate.category.html.twig:33");
            $this->AddWordCode("label.faq.create.category", "Create Category", "templates\\admin\\faqs\\sort.categories.html.twig:15");
            $this->AddWordCode("admin.faq.abstract", "This shows the list of all FAQ categories. You can drag the cards to change the sort order.", "templates\\admin\\faqs\\sort.categories.html.twig:31");
            $this->AddWordCode("admin.faq.edit", "Edit a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:13");
            $this->AddWordCode("admin.faq.create", "Create a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:15");
            $this->AddWordCode("admin.group.info", "Group Info", "templates\\admin\\groups\\approve.html.twig:16");
            $this->AddWordCode("admin.faq.sort.categories", "Sort categories", "Admin -> FAQ -> Category");
            $this->AddWordCode("flash.admin.faq.sort.order.updated", "Updated sort order of FAQ categories.", "src\\Controller\\Admin\\FaqController.php:376");
            $this->AddWordCode("admin.group.description", "Group Description", "templates\\admin\\groups\\approve.html.twig:17");
            $this->AddWordCode("admin.group.creator", "Creator", "templates\\admin\\groups\\approve.html.twig:18");
            $this->AddWordCode("admin.group.actions", "Actions", "templates\\admin\\groups\\approve.html.twig:19");
            $this->AddWordCode("admin.group.approve", "Approve group", "templates\\admin\\groups\\approve.html.twig:36");
            $this->AddWordCode("admin.group.dismiss", "Dismiss group", "templates\\admin\\groups\\approve.html.twig:37");
            $this->AddWordCode("admin.group.discussion", "Move group to discussion queue", "templates\\admin\\groups\\approve.html.twig:39");
            $this->AddWordCode("admin.group.no.group", "No groups need to be approved", "templates\\admin\\groups\\approve.html.twig:48");
            $this->AddWordCode("country", "Country", "templates\\admin\\tools\\age.country.html.twig:14");
            $this->AddWordCode("number.members", "# members", "templates\\admin\\tools\\age.country.html.twig:15");
            $this->AddWordCode("birth.year", "Birth Year", "templates\\admin\\tools\\age.country.html.twig:16");
            $this->AddWordCode("age", "Age", "templates\\admin\\tools\\age.country.html.twig:17");
            $this->AddWordCode("admin.feedback.no.feedback", "No feedback found for these parameters.", "templates\\admin\\tools\\check.feedback.html.twig:27");
            $this->AddWordCode("robots", "robots", "templates\\base-lite.html.twig:21");
            $this->AddWordCode("communitynews.comments", "%commentsCount% comments", "templates\\communitynews\\list.html.twig:21");
            $this->AddWordCode("email.greeting", "Dear %username%,", "templates\\emails\\reset.password.html.twig:4");
            $this->AddWordCode("email.reset.password.ignore", "If you received this email without asking for a password reset, please let us no on %link_start%Contact Us%link_end%", "Paragraph in the password reset email.");
            $this->AddWordCode("footer.site.language", "footer.site.language", "templates\\footer.html.twig:25");
            $this->AddWordCode("translation.information", "Translation information", "templates\\footer.html.twig:85");
            $this->AddWordCode("translation.translatable", "Translatable items", "templates\\footer.html.twig:104");
            $this->AddWordCode("translation.existing", "Existing translations", "templates\\footer.html.twig:156");
            $this->AddWordCode("translation.existing.info", "The list shows all translatable items that have an existing translation in the current locale.", "templates\\footer.html.twig:157");
            $this->AddWordCode("translation.fallback", "Fallback Translations", "templates\\footer.html.twig:171");
            $this->AddWordCode("translation.fallback.info", "The list shows all translations that match the English original text.", "templates\\footer.html.twig:172");
            $this->AddWordCode("translation.keyword.doesnt.exist", "Translations keyword doesn't exist", "templates\\footer.html.twig:185");
            $this->AddWordCode("default_meta_robots", "default_meta_robots", "templates\\home\\home.html.twig:13");
            $this->AddWordCode("bewelcome.slogan", "The world is just one step from here", "templates\\home\\home.html.twig:125");
            $this->AddWordCode("indexpageword_share", "Share your home", "templates\\home\\home.html.twig:137");
            $this->AddWordCode("choose.username", "Choose your username!", "templates\\home\\home.html.twig:140");
            $this->AddWordCode("search", "Search", "templates\\home\\home.html.twig:175");
            $this->AddWordCode("running.on", "Running on", "templates\\home\\home.html.twig:201");
            $this->AddWordCode("dashboard.donation.received", "dashboard.donation.received", "templates\\landing\\landing.html.twig:207");
            $this->AddWordCode("hosting", "hosting", "templates\\landing\\widget\\accommodation.html.twig:3");
            $this->AddWordCode("maybe hosting", "maybe hosting", "templates\\landing\\widget\\accommodation.html.twig:4");
            $this->AddWordCode("not hosting", "not hosting", "templates\\landing\\widget\\accommodation.html.twig:5");
            $this->AddWordCode("bewelcome", "BeWelcome", "templates\\loginbar.html.twig:8");
            $this->AddWordCode("login", "Login", "templates\\loginbar.html.twig:13");
            $this->AddWordCode("password.reset", "Reset Password", "templates\\member\\request.password.reset.html.twig:5");
            $this->AddWordCode("member", "Member", "templates\\member\\results.html.twig:11");
            $this->AddWordCode("profile.summary", "profile summary", "templates\\member\\results.html.twig:12");
            $this->AddWordCode("details", "details", "templates\\member\\results.html.twig:13");
            $this->AddWordCode("last.login", "Last login:", "templates\\profile\\cards\\hosting.html.twig:32");
            $this->AddWordCode("never", "never", "templates\\profile\\cards\\hosting.html.twig:32");
            $this->AddWordCode("years.old", "years old", "templates\\profile\\view.html.twig:57");
            $this->AddWordCode("toast.header", "Notification", "templates\\widgets\\messages.toast.html.twig:3");
            $this->AddWordCode("toast.messages", "{0} There are no new messages|{1} There is one new message|]1,Inf[ There are %count% new messages", "templates\\widgets\\messages.toast.html.twig:10");
            $this->AddWordCode("toast.requests", "{0} There are no new requests|{1} There is one new request|]1,Inf[ There are %count% new requests", "templates\\widgets\\requests.toast.html.twig:10");
            $this->AddWordCode("admin.checker.set.status", "Set spam status", "src\\Controller\\Admin\\CheckerController.php:54");
            $this->AddWordCode("error.access.comment", "You need to have either Comments right or be a member of the Safety Team to access this.", "Access denied on admin pages");
            $this->AddWordCode("flash.admin.comment.hidden", "Comment is now hidden.", "src\\Controller\\Admin\\CommentController.php:162");
            $this->AddWordCode("flash.admin.comment.visible", "Comment is now visible again.", "src\\Controller\\Admin\\CommentController.php:166");
            $this->AddWordCode("flash.admin.comment.editable", "Comment can be edited by author now.", "src\\Controller\\Admin\\CommentController.php:170");
            $this->AddWordCode("flash.admin.comment.locked", "Comment is now locked.", "src\\Controller\\Admin\\CommentController.php:174");
            $this->AddWordCode("flash.admin.comment.deleted", "Comment was deleted.", "src\\Controller\\Admin\\CommentController.php:177");
            $this->AddWordCode("flash.admin.comment.safetyteam", "Comment has been assigned to safety team.", "src\\Controller\\Admin\\CommentController.php:222");
            $this->AddWordCode("flash.admin.comment.checked", "Comment has been marked as checked.", "src\\Controller\\Admin\\CommentController.php:250");
            $this->AddWordCode("flash.translation.weird", "Something's weird (language should never be English).", "src\\Controller\\Admin\\TranslationController.php:251");
            $this->AddWordCode("flash.translation.enabled", "Enabled translation mode", "src\\Controller\\Admin\\TranslationController.php:320");
            $this->AddWordCode("flash.translation.disabled", "Disabled translation mode.", "src\\Controller\\Admin\\TranslationController.php:322");
            $this->AddWordCode("flash.admin.tools.forbidden", "You do not have the needed permissions to access this tool.", "src\\Controller\\Admin\\VolunteerToolController.php:49");
            $this->AddWordCode("Changed username for %oldname% to %newname%", "Changed username for %oldname% to %newname%", "src\\Controller\\Admin\\VolunteerToolController.php:99");
            $this->AddWordCode("flash.gallery.information.update", "Updated image information", "src\\Controller\\GalleryController.php:47");
            $this->AddWordCode("flash.group.moved.discussion", "Moved group %name% into the discussion queue", "src\\Controller\\GroupController.php:240");
            $this->AddWordCode("flash.group.dismissed", "Dismissed group %name%", "src\\Controller\\GroupController.php:277");
            $this->AddWordCode("flash.group.approved", "Approved creation for group %name%", "src\\Controller\\GroupController.php:320");
            $this->AddWordCode("flash.email.reset.password", "We just sent you a mail with a link that allows you to reset your password.", "src\\Controller\\MemberController.php:111");
            $this->AddWordCode("flash.reset.password.invalid", "Either username or key aren't valid to reset the password.", "src\\Controller\\MemberController.php:142");
            $this->AddWordCode("flash.password.reset", "Your password has been reset. Please login now with the new password.", "src\\Controller\\MemberController.php:165");
            $this->AddWordCode("flash.feedback.not.sent", "Your feedback couldn't be sent. Please try again later.", "src\\Controller\\MemberController.php:231");
            $this->AddWordCode("flash.feedback.safetyteam", "Your feedback has been forwarded to the Safety Team.", "src\\Controller\\MemberController.php:238");
            $this->AddWordCode("flash.member.invalid", "This member doesn't exist", "src\\Controller\\RequestAndMessageController.php:171");
            $this->AddWordCode("flash.message.limit", "You have exceeded your message limit. Try again later.", "src\\Controller\\RequestAndMessageController.php:183");
            $this->AddWordCode("flash.message.sent", "Message has been sent.", "src\\Controller\\RequestAndMessageController.php:211");
            $this->AddWordCode("flash.message.stored", "Message has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:215");
            $this->AddWordCode("flash.request.self", "You can't send yourself a hosting request.", "src\\Controller\\RequestAndMessageController.php:242");
            $this->AddWordCode("flash.request.limit", "You have exceeded your request limit. Try again later.", "src\\Controller\\RequestAndMessageController.php:256");
            $this->AddWordCode("flash.request.sent", "Request has been sent.", "src\\Controller\\RequestAndMessageController.php:293");
            $this->AddWordCode("flash.request.stored", "Request has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:295");
            $this->AddWordCode("flash.purged", "Messages and/or requests permanently deleted.", "src\\Controller\\RequestAndMessageController.php:424");
            $this->AddWordCode("flash.undeleted", "Messages and/or requests undeleted (see respective folders).", "src\\Controller\\RequestAndMessageController.php:432");
            $this->AddWordCode("flash.deleted", "Messages and/or requests deleted (see deleted folder).", "src\\Controller\\RequestAndMessageController.php:435");
            $this->AddWordCode("flash.marked.no.spam", "Messages marked as regular messages (and moved to inbox).", "src\\Controller\\RequestAndMessageController.php:441");
            $this->AddWordCode("flash.marked.spam", "Messages marked as spam messages (and moved to spam folder).", "src\\Controller\\RequestAndMessageController.php:444");
            $this->AddWordCode("flash.reply.sent", "Reply has been sent.", "src\\Controller\\RequestAndMessageController.php:517");
            $this->AddWordCode("flash.reply.stored", "Reply has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:519");
            $this->AddWordCode("flash.request.expired", "This request can't be replied to anymore as the hosting period already ended. Please send a %link_start%message%link_end%", "Flash notice shown when the user tries to reply to a request when the hosting period expired.");
            $this->AddWordCode("flash.notification.updated", "Notification with updated information has been sent.", "src\\Controller\\RequestAndMessageController.php:610");
            $this->AddWordCode("flash.signup.activated", "You just confirmed your email address and your profile got activated. Please login now and update your profile.", "src\\Controller\\SignupController.php:113");
            $this->AddWordCode("flash.key.invalid", "Provided key isn't correct", "src\\Controller\\SignupController.php:117");
            $this->AddWordCode("flash.wiki.markup.invalid", "Couldn't process markup. Please check content and fix.", "src\\Controller\\WikiController.php:54");
            $this->AddWordCode("flash.wiki.updated", "Updated wiki text", "src\\Controller\\WikiController.php:100");
            $this->AddWordCode("flash.wiki.created", "Created wiki page", "src\\Controller\\WikiController.php:144");
            $this->AddWordCode("label.admin.comment.delete", "Delete Comment", "src\\Form\\AdminCommentFormType.php:22");
            $this->AddWordCode("label.admin.comment.move.negative", "Move To Negative", "src\\Form\\AdminCommentFormType.php:22");
            $this->AddWordCode("label.admin.comment.mark.abuse", "Mark As Abuse", "src\\Form\\AdminCommentFormType.php:22");
            $this->AddWordCode("label.admin.comment.mark.checked", "Mark As Checked", "src\\Form\\AdminCommentFormType.php:22");
            $this->AddWordCode("label.admin.comment.hide", "Hide Comment", "src\\Form\\AdminCommentFormType.php:49");
            $this->AddWordCode("label.admin.comment.show", "Show Comment", "src\\Form\\AdminCommentFormType.php:55");
            $this->AddWordCode("label.admin.comment.lock", "Disable Editing", "src\\Form\\AdminCommentFormType.php:62");
            $this->AddWordCode("label.admin.comment.mark.editable", "Allow Editing", "src\\Form\\AdminCommentFormType.php:68");
            $this->AddWordCode("label.admin.tools.change.username", "Change Username", "src\\Form\\ChangeUsernameFormType.php:21");
            $this->AddWordCode("new.username", "New Username", "src\\Form\\ChangeUsernameFormType.php:21");
            $this->AddWordCode("old.Username", "Old Username", "src\\Form\\ChangeUsernameFormType.php:21");
            $this->AddWordCode("label.nospam.messages", "noSpamMessages", "src\\Form\\CheckerIndexFormType.php:18");
            $this->AddWordCode("label.spam.messages", "spamMessages", "src\\Form\\CheckerIndexFormType.php:18");
            $this->AddWordCode("label.admin.communitynews.title", "Enter the title of the community news", "src\\Form\\CommunityNewsType.php:23");
            $this->AddWordCode("label.admin.communitynews.public", "Shall the community be visible to regular members yet?", "src\\Form\\CommunityNewsType.php:41");
            $this->AddWordCode("label.admin.communitynews.text", "text", "src\\Form\\CommunityNewsType.php:22");
            $this->AddWordCode("placeholder.admin.communitynews.title", "Please enter the title", "src\\Form\\CommunityNewsType.php:25");
            $this->AddWordCode("placeholder.admin.communitynews.text", "This will be the body of the community news.", "src\\Form\\CommunityNewsType.php:34");
            $this->AddWordCode("label.admin.translation.wordcode", "Translation ID", "src\\Form\\EditTranslationFormType.php:22");
            $this->AddWordCode("label.admin.translation.description", "Description", "src\\Form\\EditTranslationFormType.php:26");
            $this->AddWordCode("label.admin.translation.englishText", "English Original", "src\\Form\\EditTranslationFormType.php:30");
            $this->AddWordCode("label.admin.translation.locale", "Locale", "src\\Form\\EditTranslationFormType.php:34");
            $this->AddWordCode("label.admin.translation", "Translation", "src\\Form\\EditTranslationFormType.php:21");
            $this->AddWordCode("label.admin.faq.category.translation.id", "Translation ID", "src\\Form\\FaqCategoryFormType.php:25");
            $this->AddWordCode("label.admin.faq.category.description", "FaqCategoryDescription", "src\\Form\\FaqCategoryFormType.php:31");
            $this->AddWordCode("help.admin.faq.category.description", "The title of the category as shown in the menu of the faq pages.", "Help text for the FAQ category description text field.");
            $this->AddWordCode("help.admin.faq.category.translation.id","The word code to be used for the FAQ category. ('faq_cat_' will automatically be added at the start.)", "Help text for the FAQ category translation ID field.");
            $this->AddWordCode("error.admin.faq.transform.invalid", "Faq Category translation ID is invalid.", "Error message shown when faq category got corrupted.");
            $this->AddWordCode("label.admin.faq.update.order", "Update Order", "Button label FAQ admin interface");
            $this->AddWordCode("label.admin.faq.category", "Faq Category", "src\\Form\\FaqFormType.php:24");
            $this->AddWordCode("label.admin.faq.translation.id", "Translation ID", "src\\Form\\FaqFormType.php:30");
            $this->AddWordCode("label.admin.faq.question", "Question", "src\\Form\\FaqFormType.php:33");
            $this->AddWordCode("label.admin.faq.answer", "Answer", "src\\Form\\FaqFormType.php:40");
            $this->AddWordCode("label.admin.faq.active", "Active", "src\\Form\\FaqFormType.php:46");
            $this->AddWordCode("label.feedback.types", "types", "src\\Form\\FeedbackFormType.php:19");
            $this->AddWordCode("label.username.part", "Part of username", "src\\Form\\FindUserFormType.php:20");
            $this->AddWordCode("placeholder.username.part", "Part of username", "src\\Form\\FindUserFormType.php:24");
            $this->AddWordCode("label.gallery.title", "Title", "src\\Form\\GalleryEditImageFormType.php:21");
            $this->AddWordCode("placeholder.gallery.title", "Image Title", "src\\Form\\GalleryEditImageFormType.php:24");
            $this->AddWordCode("label.gallery.description", "Image Description", "src\\Form\\GalleryEditImageFormType.php:29");
            $this->AddWordCode("placeholder.gallery.description", "Image Description", "src\\Form\\GalleryEditImageFormType.php:29");
            $this->AddWordCode("label.group.name", "Group name", "src\\Form\\GroupType.php:23");
            $this->AddWordCode("placeholder.group.name", "Please enter a name for the group", "src\\Form\\GroupType.php:25");
            $this->AddWordCode("label.group.description", "Group description", "src\\Form\\GroupType.php:23");
            $this->AddWordCode("placeholder.group.description", "Please provide a meaningful description for the new group.", "src\\Form\\GroupType.php:31");
            $this->AddWordCode("group.choose.group.image", "group.choose.group.image", "src\\Form\\GroupType.php:56");
            $this->AddWordCode("label.group.picture", "Group picture", "src\\Form\\GroupType.php:56");
            $this->AddWordCode("label.message", "Message", "src\\Form\\HostingRequestAbstractType.php:34");
            $this->AddWordCode("label.flexible", "Flexible", "src\\Form\\HostingRequestType.php:23");
            $this->AddWordCode("placeholder.arrival", "Arrival (date)", "src\\Form\\HostingRequestType.php:30");
            $this->AddWordCode("placeholder.departure", "Departure (date)", "src\\Form\\HostingRequestType.php:46");
            $this->AddWordCode("placeholder.request.nbtravellers", "#", "src\\Form\\HostingRequestType.php:61");
            $this->AddWordCode("label.purge", "purge", "src\\Form\\MessageIndexFormType.php:35");
            $this->AddWordCode("label.messages", "Messages", "src\\Form\\MessageIndexFormType.php:20");
            $this->AddWordCode("Please enter a message.", "Please enter a message.", "src\\Form\\MessageToMemberType.php:21");
            $this->AddWordCode("label.feedback", "Feedback on Comment", "src\\Form\\ReportCommentType.php:21");
            $this->AddWordCode("label.send.feedback", "Send Feedback", "src\\Form\\ReportCommentType.php:20");
            $this->AddWordCode("label.radius", "in a radius of", "src\\Form\\SearchFormType.php:314");
            $this->AddWordCode("label.items", "items", "src\\Form\\SearchFormType.php:156");
            $this->AddWordCode("label.order", "order", "src\\Form\\SearchFormType.php:156");
            $this->AddWordCode("placeholder.location", "Where are you going?", "src\\Form\\SearchFormType.php:30");
            $this->AddWordCode("update_map", "update_map", "src\\Form\\SearchGotoLocationFormType.php:44");
            $this->AddWordCode("label.subject", "Subject", "src\\Form\\SubjectType.php:20");
            $this->AddWordCode("placeholder.subject", "Please give a meaningful subject", "src\\Form\\SubjectType.php:20");
            $this->AddWordCode("error.subject.blank", "The subject can't be empty.", "src\\Form\\SubjectType");
            $this->AddWordCode("signup.receive.newsletters", "I'd like to receive newsletters from BeWelcome.", "signup\\4");
            $this->AddWordCode("signup.receive.local-info", "I'd like to receive information about local events.", "signup\\4");
            $this->AddWordCode("reply", "Reply", "Used in the email template");
            $this->AddWordCode("label.submit", "Submit", "Button label to submit data. Used throughout the site.");
            $this->AddWordCode("label.create", "Create", "Button label to create something. Used throughout the site.");
            $this->AddWordCode("label.update", "Update", "Button label to update data. Used throughout the site.");
            $this->AddWordCode( "label.read.more", "Read more", "Label shown when ever text is truncated.");
            $this->AddWordCode("flash.added.translatable.item", "Added translatable item %code%", "Flash notice after adding a new translatable item (admin interface).");
            $this->AddWordCode("flash.group.create.successful", "The new group has been created but needs to be approved by the moderator team. Please be patient.", "Flash notice after creating a new group.");
        } catch (Exception $e) {
        }
    }

    public function down() {
        $this->RemoveWordCode('canofferneverask', 'Accommodation: No.', 'Tooltip for accommodation icons.');
        $this->RemoveWordCode('profile.contactinfo.socialmedia', 'Social Media', 'Headline on edit my profile');// $this->RemoveWordCode("activities", "Activities", "templates\\activity\\list.html.twig:21");
        // $this->RemoveWordCode("activities.number.attendees.yes", "%number%", "templates\\activity\\list.html.twig:49");
        // $this->RemoveWordCode("activities.number.attendees.maybe", "ActivitiesNumbAttendeesMaybe", "templates\\activity\\list.html.twig:50");
        // $this->RemoveWordCode("activity", "Activity", "templates\\activity\\show.html.twig:4");
        $this->RemoveWordCode("admin.checker.no.messages", "No messages have been reported as spam.", "templates\\admin\\checker\\index.html.twig:19");
        $this->RemoveWordCode("ok", "ok", "templates\\admin\\checker\\index.html.twig:35");
        $this->RemoveWordCode("spam", "spam", "templates\\admin\\checker\\index.html.twig:36");
        $this->RemoveWordCode("admin.comment.headline", "Admin - Comment", "templates\\admin\\comment\\comment.html.twig:5");
        $this->RemoveWordCode("admin.comments.to.all", "All comments to %username%", "templates\\admin\\comment\\comment.html.twig:25");
        $this->RemoveWordCode("admin.comments.from.all", "All comments from %username%", "templates\\admin\\comment\\comment.html.twig:26");
        $this->RemoveWordCode("admin.comments.all", "All Comments", "templates\\admin\\comment\\overview.html.twig:5");
        $this->RemoveWordCode("admin.comments.no.comments", "No comments found for these parameters.", "templates\\admin\\comment\\overview.html.twig:11");
        $this->RemoveWordCode("from", "from", "templates\\admin\\comment\\overview.html.twig:22");
        $this->RemoveWordCode("about", "about", "templates\\admin\\comment\\overview.html.twig:24");
        $this->RemoveWordCode("action", "action", "templates\\admin\\comment\\overview.html.twig:25");
        $this->RemoveWordCode("written", "written", "templates\\admin\\comment\\overview.html.twig:34");
        $this->RemoveWordCode("comment.quality", "Quality and Date", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("comment.where.met", "Where we met", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("comment.text", "Comment Text", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("comment.know", "How we know each other", "templates\\admin\\comment\\overview.html.twig");
        $this->RemoveWordCode("admin.comment.edit", "Edit comment", "templates\\admin\\comment\\overview.html.twig:46");
        $this->RemoveWordCode("admin.comment.hide", "Hide", "templates\\admin\\comment\\overview.html.twig:48");
        $this->RemoveWordCode("admin.comment.show", "Show", "templates\\admin\\comment\\overview.html.twig:50");
        $this->RemoveWordCode("admin.comment.assign.safety", "Assign to safety team", "templates\\admin\\comment\\overview.html.twig:53");
        $this->RemoveWordCode("admin.comment.checked", "Mark as checked", "templates\\admin\\comment\\overview.html.twig:56");
        $this->RemoveWordCode("admin.community.news.headline", "Community News", "templates\\admin\\communitynews\\editcreate.html.twig:4");
        $this->RemoveWordCode("admin.community.news.no.news", "No community news exist.", "templates\\admin\\communitynews\\index.html.twig:25");
        $this->RemoveWordCode("admin.logs.no.logs", "No logs found for these parameters.", "templates\\admin\\logs\\index.html.twig:25");
        $this->RemoveWordCode("create", "create", "templates\\admin\\communitynews\\list.html.twig:17");
        $this->RemoveWordCode("read.more", "Read more", "templates\\admin\\communitynews\\list.html.twig:39");
        $this->RemoveWordCode("admin.faq.edit.category", "Edit a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:13");
        $this->RemoveWordCode("admin.faq.create.category", "Create a FAQ category", "templates\\admin\\faqs\\editcreate.category.html.twig:15");
        $this->RemoveWordCode("admin.faq.category.update.order", "Update order", "templates\\admin\\faqs\\editcreate.category.html.twig:33");
        $this->RemoveWordCode("label.faq.create.category", "Create Category", "templates\\admin\\faqs\\sort.categories.html.twig:15");
        $this->RemoveWordCode("admin.faq.abstract", "This shows the list of all FAQ categories. You can drag the cards to change the sort order.", "templates\\admin\\faqs\\sort.categories.html.twig:31");
        $this->RemoveWordCode("admin.faq.edit", "Edit a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:13");
        $this->RemoveWordCode("admin.faq.create", "Create a FAQ", "templates\\admin\\faqs\\editcreate.faq.html.twig:15");
        $this->RemoveWordCode("admin.group.info", "Group Info", "templates\\admin\\groups\\approve.html.twig:16");
        $this->RemoveWordCode("admin.faq.sort.categories", "Sort categories", "Admin -> FAQ -> Category");
        $this->RemoveWordCode("flash.admin.faq.sort.order.updated", "Updated sort order of FAQ categories.", "src\\Controller\\Admin\\FaqController.php:376");
        $this->RemoveWordCode("admin.group.description", "Group Description", "templates\\admin\\groups\\approve.html.twig:17");
        $this->RemoveWordCode("admin.group.creator", "Creator", "templates\\admin\\groups\\approve.html.twig:18");
        $this->RemoveWordCode("admin.group.actions", "Actions", "templates\\admin\\groups\\approve.html.twig:19");
        $this->RemoveWordCode("admin.group.approve", "Approve group", "templates\\admin\\groups\\approve.html.twig:36");
        $this->RemoveWordCode("admin.group.dismiss", "Dismiss group", "templates\\admin\\groups\\approve.html.twig:37");
        $this->RemoveWordCode("admin.group.discussion", "Move group to discussion queue", "templates\\admin\\groups\\approve.html.twig:39");
        $this->RemoveWordCode("admin.group.no.group", "No groups need to be approved", "templates\\admin\\groups\\approve.html.twig:48");
        $this->RemoveWordCode("country", "Country", "templates\\admin\\tools\\age.country.html.twig:14");
        $this->RemoveWordCode("number.members", "# members", "templates\\admin\\tools\\age.country.html.twig:15");
        $this->RemoveWordCode("birth.year", "Birth Year", "templates\\admin\\tools\\age.country.html.twig:16");
        $this->RemoveWordCode("age", "Age", "templates\\admin\\tools\\age.country.html.twig:17");
        $this->RemoveWordCode("admin.feedback.no.feedback", "No feedback found for these parameters.", "templates\\admin\\tools\\check.feedback.html.twig:27");
        $this->RemoveWordCode("robots", "robots", "templates\\base-lite.html.twig:21");
        $this->RemoveWordCode("communitynews.comments", "%commentsCount% comments", "templates\\communitynews\\list.html.twig:21");
        $this->RemoveWordCode("email.greeting", "Dear %username%,", "templates\\emails\\reset.password.html.twig:4");
        $this->RemoveWordCode("email.reset.password.ignore", "If you received this email without asking for a password reset, please let us no on %link_start%Contact Us%link_end%", "Paragraph in the password reset email.");
        $this->RemoveWordCode("footer.site.language", "footer.site.language", "templates\\footer.html.twig:25");
        $this->RemoveWordCode("translation.information", "Translation information", "templates\\footer.html.twig:85");
        $this->RemoveWordCode("translation.translatable", "Translatable items", "templates\\footer.html.twig:104");
        $this->RemoveWordCode("translation.existing", "Existing translations", "templates\\footer.html.twig:156");
        $this->RemoveWordCode("translation.existing.info", "The list shows all translatable items that have an existing translation in the current locale.", "templates\\footer.html.twig:157");
        $this->RemoveWordCode("translation.fallback", "Fallback Translations", "templates\\footer.html.twig:171");
        $this->RemoveWordCode("translation.fallback.info", "The list shows all translations that match the English original text.", "templates\\footer.html.twig:172");
        $this->RemoveWordCode("translation.keyword.doesnt.exist", "Translations keyword doesn't exist", "templates\\footer.html.twig:185");
        $this->RemoveWordCode("default_meta_robots", "default_meta_robots", "templates\\home\\home.html.twig:13");
        $this->RemoveWordCode("bewelcome.slogan", "The world is just one step from here", "templates\\home\\home.html.twig:125");
        $this->RemoveWordCode("indexpageword_share", "Share your home", "templates\\home\\home.html.twig:137");
        $this->RemoveWordCode("choose.username", "Choose your username!", "templates\\home\\home.html.twig:140");
        $this->RemoveWordCode("search", "Search", "templates\\home\\home.html.twig:175");
        $this->RemoveWordCode("running.on", "Running on", "templates\\home\\home.html.twig:201");
        $this->RemoveWordCode("dashboard.donation.received", "dashboard.donation.received", "templates\\landing\\landing.html.twig:207");
        $this->RemoveWordCode("hosting", "hosting", "templates\\landing\\widget\\accommodation.html.twig:3");
        $this->RemoveWordCode("maybe hosting", "maybe hosting", "templates\\landing\\widget\\accommodation.html.twig:4");
        $this->RemoveWordCode("not hosting", "not hosting", "templates\\landing\\widget\\accommodation.html.twig:5");
        $this->RemoveWordCode("bewelcome", "BeWelcome", "templates\\loginbar.html.twig:8");
        $this->RemoveWordCode("login", "Login", "templates\\loginbar.html.twig:13");
        $this->RemoveWordCode("password.reset", "Reset Password", "templates\\member\\request.password.reset.html.twig:5");
        $this->RemoveWordCode("member", "Member", "templates\\member\\results.html.twig:11");
        $this->RemoveWordCode("profile.summary", "profile summary", "templates\\member\\results.html.twig:12");
        $this->RemoveWordCode("details", "details", "templates\\member\\results.html.twig:13");
        $this->RemoveWordCode("last.login", "Last login:", "templates\\profile\\cards\\hosting.html.twig:32");
        $this->RemoveWordCode("never", "never", "templates\\profile\\cards\\hosting.html.twig:32");
        $this->RemoveWordCode("years.old", "years old", "templates\\profile\\view.html.twig:57");
        $this->RemoveWordCode("toast.header", "Notification", "templates\\widgets\\messages.toast.html.twig:3");
        $this->RemoveWordCode("toast.messages", "{0} There are no new messages|{1} There is one new message|]1,Inf[ There are %count% new messages", "templates\\widgets\\messages.toast.html.twig:10");
        $this->RemoveWordCode("toast.requests", "{0} There are no new requests|{1} There is one new request|]1,Inf[ There are %count% new requests", "templates\\widgets\\requests.toast.html.twig:10");
        $this->RemoveWordCode("admin.checker.set.status", "Set spam status", "src\\Controller\\Admin\\CheckerController.php:54");
        $this->RemoveWordCode("error.access.comment", "You need to have either Comments right or be a member of the Safety Team to access this.", "Access denied on admin pages");
        $this->RemoveWordCode("flash.admin.comment.hidden", "Comment is now hidden.", "src\\Controller\\Admin\\CommentController.php:162");
        $this->RemoveWordCode("flash.admin.comment.visible", "Comment is now visible again.", "src\\Controller\\Admin\\CommentController.php:166");
        $this->RemoveWordCode("flash.admin.comment.editable", "Comment can be edited by author now.", "src\\Controller\\Admin\\CommentController.php:170");
        $this->RemoveWordCode("flash.admin.comment.locked", "Comment is now locked.", "src\\Controller\\Admin\\CommentController.php:174");
        $this->RemoveWordCode("flash.admin.comment.deleted", "Comment was deleted.", "src\\Controller\\Admin\\CommentController.php:177");
        $this->RemoveWordCode("flash.admin.comment.safetyteam", "Comment has been assigned to safety team.", "src\\Controller\\Admin\\CommentController.php:222");
        $this->RemoveWordCode("flash.admin.comment.checked", "Comment has been marked as checked.", "src\\Controller\\Admin\\CommentController.php:250");
        $this->RemoveWordCode("flash.translation.weird", "Something's weird (language should never be English).", "src\\Controller\\Admin\\TranslationController.php:251");
        $this->RemoveWordCode("flash.translation.enabled", "Enabled translation mode", "src\\Controller\\Admin\\TranslationController.php:320");
        $this->RemoveWordCode("flash.translation.disabled", "Disabled translation mode.", "src\\Controller\\Admin\\TranslationController.php:322");
        $this->RemoveWordCode("flash.admin.tools.forbidden", "You do not have the needed permissions to access this tool.", "src\\Controller\\Admin\\VolunteerToolController.php:49");
        $this->RemoveWordCode("Changed username for %oldname% to %newname%", "Changed username for %oldname% to %newname%", "src\\Controller\\Admin\\VolunteerToolController.php:99");
        $this->RemoveWordCode("flash.gallery.information.update", "Updated image information", "src\\Controller\\GalleryController.php:47");
        $this->RemoveWordCode("flash.group.moved.discussion", "Moved group %name% into the discussion queue", "src\\Controller\\GroupController.php:240");
        $this->RemoveWordCode("flash.group.dismissed", "Dismissed group %name%", "src\\Controller\\GroupController.php:277");
        $this->RemoveWordCode("flash.group.approved", "Approved creation for group %name%", "src\\Controller\\GroupController.php:320");
        $this->RemoveWordCode("flash.email.reset.password", "We just sent you a mail with a link that allows you to reset your password.", "src\\Controller\\MemberController.php:111");
        $this->RemoveWordCode("flash.reset.password.invalid", "Either username or key aren't valid to reset the password.", "src\\Controller\\MemberController.php:142");
        $this->RemoveWordCode("flash.password.reset", "Your password has been reset. Please login now with the new password.", "src\\Controller\\MemberController.php:165");
        $this->RemoveWordCode("flash.feedback.not.sent", "Your feedback couldn't be sent. Please try again later.", "src\\Controller\\MemberController.php:231");
        $this->RemoveWordCode("flash.feedback.safetyteam", "Your feedback has been forwarded to the Safety Team.", "src\\Controller\\MemberController.php:238");
        $this->RemoveWordCode("flash.member.invalid", "This member doesn't exist", "src\\Controller\\RequestAndMessageController.php:171");
        $this->RemoveWordCode("flash.message.limit", "You have exceeded your message limit. Try again later.", "src\\Controller\\RequestAndMessageController.php:183");
        $this->RemoveWordCode("flash.message.sent", "Message has been sent.", "src\\Controller\\RequestAndMessageController.php:211");
        $this->RemoveWordCode("flash.message.stored", "Message has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:215");
        $this->RemoveWordCode("flash.request.self", "You can't send yourself a hosting request.", "src\\Controller\\RequestAndMessageController.php:242");
        $this->RemoveWordCode("flash.request.limit", "You have exceeded your request limit. Try again later.", "src\\Controller\\RequestAndMessageController.php:256");
        $this->RemoveWordCode("flash.request.sent", "Request has been sent.", "src\\Controller\\RequestAndMessageController.php:293");
        $this->RemoveWordCode("flash.request.stored", "Request has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:295");
        $this->RemoveWordCode("flash.purged", "Messages and/or requests permanently deleted.", "src\\Controller\\RequestAndMessageController.php:424");
        $this->RemoveWordCode("flash.undeleted", "Messages and/or requests undeleted (see respective folders).", "src\\Controller\\RequestAndMessageController.php:432");
        $this->RemoveWordCode("flash.deleted", "Messages and/or requests deleted (see deleted folder).", "src\\Controller\\RequestAndMessageController.php:435");
        $this->RemoveWordCode("flash.marked.no.spam", "Messages marked as regular messages (and moved to inbox).", "src\\Controller\\RequestAndMessageController.php:441");
        $this->RemoveWordCode("flash.marked.spam", "Messages marked as spam messages (and moved to spam folder).", "src\\Controller\\RequestAndMessageController.php:444");
        $this->RemoveWordCode("flash.reply.sent", "Reply has been sent.", "src\\Controller\\RequestAndMessageController.php:517");
        $this->RemoveWordCode("flash.reply.stored", "Reply has been stored into the database. Mail notification couldn't be sent, though.", "src\\Controller\\RequestAndMessageController.php:519");
        $this->RemoveWordCode("flash.request.expired", "This request can't be replied to anymore as the hosting period already ended. Please send a %link_start%message%link_end%", "Flash notice shown when the user tries to reply to a request when the hosting period expired.");
        $this->RemoveWordCode("flash.notification.updated", "Notification with updated information has been sent.", "src\\Controller\\RequestAndMessageController.php:610");
        $this->RemoveWordCode("flash.signup.activated", "You just confirmed your email address and your profile got activated. Please login now and update your profile.", "src\\Controller\\SignupController.php:113");
        $this->RemoveWordCode("flash.key.invalid", "Provided key isn't correct", "src\\Controller\\SignupController.php:117");
        $this->RemoveWordCode("flash.wiki.markup.invalid", "Couldn't process markup. Please check content and fix.", "src\\Controller\\WikiController.php:54");
        $this->RemoveWordCode("flash.wiki.updated", "Updated wiki text", "src\\Controller\\WikiController.php:100");
        $this->RemoveWordCode("flash.wiki.created", "Created wiki page", "src\\Controller\\WikiController.php:144");
        $this->RemoveWordCode("label.admin.comment.delete", "Delete Comment", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("label.admin.comment.move.negative", "Move To Negative", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("label.admin.comment.mark.abuse", "Mark As Abuse", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("label.admin.comment.mark.checked", "Mark As Checked", "src\\Form\\AdminCommentFormType.php:22");
        $this->RemoveWordCode("label.admin.comment.hide", "Hide Comment", "src\\Form\\AdminCommentFormType.php:49");
        $this->RemoveWordCode("label.admin.comment.show", "Show Comment", "src\\Form\\AdminCommentFormType.php:55");
        $this->RemoveWordCode("label.admin.comment.lock", "Disable Editing", "src\\Form\\AdminCommentFormType.php:62");
        $this->RemoveWordCode("label.admin.comment.mark.editable", "Allow Editing", "src\\Form\\AdminCommentFormType.php:68");
        $this->RemoveWordCode("label.admin.tools.change.username", "Change Username", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->RemoveWordCode("new.username", "New Username", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->RemoveWordCode("old.Username", "Old Username", "src\\Form\\ChangeUsernameFormType.php:21");
        $this->RemoveWordCode("label.nospam.messages", "noSpamMessages", "src\\Form\\CheckerIndexFormType.php:18");
        $this->RemoveWordCode("label.spam.messages", "spamMessages", "src\\Form\\CheckerIndexFormType.php:18");
        $this->RemoveWordCode("label.admin.communitynews.title", "Enter the title of the community news", "src\\Form\\CommunityNewsType.php:23");
        $this->RemoveWordCode("label.admin.communitynews.public", "Shall the community be visible to regular members yet?", "src\\Form\\CommunityNewsType.php:41");
        $this->RemoveWordCode("label.admin.communitynews.text", "text", "src\\Form\\CommunityNewsType.php:22");
        $this->RemoveWordCode("placeholder.admin.communitynews.title", "Please enter the title", "src\\Form\\CommunityNewsType.php:25");
        $this->RemoveWordCode("placeholder.admin.communitynews.text", "This will be the body of the community news.", "src\\Form\\CommunityNewsType.php:34");
        $this->RemoveWordCode("label.admin.translation.wordcode", "Translation ID", "src\\Form\\EditTranslationFormType.php:22");
        $this->RemoveWordCode("label.admin.translation.description", "Description", "src\\Form\\EditTranslationFormType.php:26");
        $this->RemoveWordCode("label.admin.translation.englishText", "English Original", "src\\Form\\EditTranslationFormType.php:30");
        $this->RemoveWordCode("label.admin.translation.locale", "Locale", "src\\Form\\EditTranslationFormType.php:34");
        $this->RemoveWordCode("label.admin.translation", "Translation", "src\\Form\\EditTranslationFormType.php:21");
        $this->RemoveWordCode("label.admin.faq.category.translation.id", "Translation ID", "src\\Form\\FaqCategoryFormType.php:25");
        $this->RemoveWordCode("label.admin.faq.category.description", "FaqCategoryDescription", "src\\Form\\FaqCategoryFormType.php:31");
        $this->RemoveWordCode("help.admin.faq.category.description", "The title of the category as shown in the menu of the faq pages.", "Help text for the FAQ category description text field.");
        $this->RemoveWordCode("help.admin.faq.category.translation.id","The word code to be used for the FAQ category. ('faq_cat_' will automatically be added at the start.)", "Help text for the FAQ category translation ID field.");
        $this->RemoveWordCode("error.admin.faq.transform.invalid", "Faq Category translation ID is invalid.", "Error message shown when faq category got corrupted.");
        $this->RemoveWordCode("label.admin.faq.update.order", "Update Order", "Button label FAQ admin interface");
        $this->RemoveWordCode("label.admin.faq.category", "Faq Category", "src\\Form\\FaqFormType.php:24");
        $this->RemoveWordCode("label.admin.faq.translation.id", "Translation ID", "src\\Form\\FaqFormType.php:30");
        $this->RemoveWordCode("label.admin.faq.question", "Question", "src\\Form\\FaqFormType.php:33");
        $this->RemoveWordCode("label.admin.faq.answer", "Answer", "src\\Form\\FaqFormType.php:40");
        $this->RemoveWordCode("label.admin.faq.active", "Active", "src\\Form\\FaqFormType.php:46");
        $this->RemoveWordCode("label.feedback.types", "types", "src\\Form\\FeedbackFormType.php:19");
        $this->RemoveWordCode("label.username.part", "Part of username", "src\\Form\\FindUserFormType.php:20");
        $this->RemoveWordCode("placeholder.username.part", "Part of username", "src\\Form\\FindUserFormType.php:24");
        $this->RemoveWordCode("label.gallery.title", "Title", "src\\Form\\GalleryEditImageFormType.php:21");
        $this->RemoveWordCode("placeholder.gallery.title", "Image Title", "src\\Form\\GalleryEditImageFormType.php:24");
        $this->RemoveWordCode("label.gallery.description", "Image Description", "src\\Form\\GalleryEditImageFormType.php:29");
        $this->RemoveWordCode("placeholder.gallery.description", "Image Description", "src\\Form\\GalleryEditImageFormType.php:29");
        $this->RemoveWordCode("label.group.name", "Group name", "src\\Form\\GroupType.php:23");
        $this->RemoveWordCode("placeholder.group.name", "Please enter a name for the group", "src\\Form\\GroupType.php:25");
        $this->RemoveWordCode("label.group.description", "Group description", "src\\Form\\GroupType.php:23");
        $this->RemoveWordCode("placeholder.group.description", "Please provide a meaningful description for the new group.", "src\\Form\\GroupType.php:31");
        $this->RemoveWordCode("group.choose.group.image", "group.choose.group.image", "src\\Form\\GroupType.php:56");
        $this->RemoveWordCode("label.group.picture", "Group picture", "src\\Form\\GroupType.php:56");
        $this->RemoveWordCode("label.message", "Message", "src\\Form\\HostingRequestAbstractType.php:34");
        $this->RemoveWordCode("label.flexible", "Flexible", "src\\Form\\HostingRequestType.php:23");
        $this->RemoveWordCode("placeholder.arrival", "Arrival (date)", "src\\Form\\HostingRequestType.php:30");
        $this->RemoveWordCode("placeholder.departure", "Departure (date)", "src\\Form\\HostingRequestType.php:46");
        $this->RemoveWordCode("placeholder.request.nbtravellers", "#", "src\\Form\\HostingRequestType.php:61");
        $this->RemoveWordCode("label.purge", "purge", "src\\Form\\MessageIndexFormType.php:35");
        $this->RemoveWordCode("label.messages", "Messages", "src\\Form\\MessageIndexFormType.php:20");
        $this->RemoveWordCode("Please enter a message.", "Please enter a message.", "src\\Form\\MessageToMemberType.php:21");
        $this->RemoveWordCode("label.feedback", "Feedback on Comment", "src\\Form\\ReportCommentType.php:21");
        $this->RemoveWordCode("label.send.feedback", "Send Feedback", "src\\Form\\ReportCommentType.php:20");
        $this->RemoveWordCode("label.radius", "in a radius of", "src\\Form\\SearchFormType.php:314");
        $this->RemoveWordCode("label.items", "items", "src\\Form\\SearchFormType.php:156");
        $this->RemoveWordCode("label.order", "order", "src\\Form\\SearchFormType.php:156");
        $this->RemoveWordCode("placeholder.location", "Where are you going?", "src\\Form\\SearchFormType.php:30");
        $this->RemoveWordCode("update_map", "update_map", "src\\Form\\SearchGotoLocationFormType.php:44");
        $this->RemoveWordCode("label.subject", "Subject", "src\\Form\\SubjectType.php:20");
        $this->RemoveWordCode("placeholder.subject", "Please give a meaningful subject", "src\\Form\\SubjectType.php:20");
        $this->RemoveWordCode("error.subject.blank", "The subject can't be empty.", "src\\Form\\SubjectType");
        $this->RemoveWordCode("signup.receive.newsletters", "I'd like to receive newsletters from BeWelcome.", "signup\\4");
        $this->RemoveWordCode("signup.receive.local-info", "I'd like to receive information about local events.", "signup\\4");
        $this->RemoveWordCode("reply", "Reply", "Used in the email template");
        $this->RemoveWordCode("label.submit", "Submit", "Button label to submit data. Used throughout the site.");
        $this->RemoveWordCode("label.create", "Create", "Button label to create something. Used throughout the site.");
        $this->RemoveWordCode("label.update", "Update", "Button label to update data. Used throughout the site.");
        $this->RemoveWordCode( "label.read.more", "Read more", "Label shown when ever text is truncated.");
        $this->RemoveWordCode("flash.added.translatable.item", "Added translatable item %code%", "Flash notice after adding a new translatable item (admin interface).");
        $this->RemoveWordCode("flash.group.create.successful", "The new group has been created but needs to be approved by the moderator team. Please be patient.", "Flash notice after creating a new group.");
    }
}
