imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # locales should be determined from the DB in the future
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl
    app.notifications.email_sender: message@bewelcome.org
    node_modules: "%kernel.root_dir%/../node_modules"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    translator: { fallbacks: [en] }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    base_template_class: 'Rox\Core\Template\RoxTemplate'
    exception_controller:  twig.controller.exception:showAction
    form_themes:
      - '@forms/bs4.html.twig'
    paths:
        '%kernel.root_dir%/../templates/twig/forms': forms

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: 5.6

        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            enum:       string
            set:        string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: true

    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%node_modules%/.bin/uglifyjs"
        uglifycss:
            bin: "%node_modules%/.bin/uglifycss"

    assets:
        backwards_js:
            inputs:
                - "%node_modules%/html5shiv/dist/html5shiv.min.js"
                - "%node_modules%/respond.js/dest/respond.min.js"

        jquery_js:
            inputs:
                - "%node_modules%/jquery/dist/jquery.js"

        jquery_ui_js:
            inputs:
                - "%node_modules%/jquery-ui/ui/version.js"
                - "%node_modules%/jquery-ui/ui/widget.js"
                - "%node_modules%/jquery-ui/ui/position.js"
                - "%node_modules%/jquery-ui/ui/keycode.js"
                - "%node_modules%/jquery-ui/ui/unique-id.js"
                - "%node_modules%/jquery-ui/ui/safe-active-element.js"
                - "%node_modules%/jquery-ui/ui/widgets/menu.js"
                - "%node_modules%/jquery-ui/ui/widgets/autocomplete.js"
                - "%node_modules%/jquery-ui/ui/widgets/datepicker.js"

        jquery_ui_css:
            inputs:
                - "%node_modules%/jquery-ui/themes/base/theme.css"
                - "%node_modules%/jquery-ui/themes/base/core.css"
                - "%node_modules%/jquery-ui/themes/base/accordion.css"
                - "%node_modules%/jquery-ui/themes/base/autocomplete.css"
                - "%node_modules%/jquery-ui/themes/base/button.css"
                - "%node_modules%/jquery-ui/themes/base/checkboxradio.css"
                - "%node_modules%/jquery-ui/themes/base/controlgroup.css"
                - "%node_modules%/jquery-ui/themes/base/datepicker.css"
                - "%node_modules%/jquery-ui/themes/base/dialog.css"
                - "%node_modules%/jquery-ui/themes/base/draggable.css"
                - "%node_modules%/jquery-ui/themes/base/menu.css"
                - "%node_modules%/jquery-ui/themes/base/progressbar.css"
                - "%node_modules%/jquery-ui/themes/base/resizable.css"
                - "%node_modules%/jquery-ui/themes/base/selectable.css"
                - "%node_modules%/jquery-ui/themes/base/selectmenu.css"
                - "%node_modules%/jquery-ui/themes/base/sortable.css"
                - "%node_modules%/jquery-ui/themes/base/slider.css"
                - "%node_modules%/jquery-ui/themes/base/spinner.css"
                - "%node_modules%/jquery-ui/themes/base/tabs.css"
                - "%node_modules%/jquery-ui/themes/base/tooltip.css"

        tether_js:
            inputs:
                - "%node_modules%/tether/dist/js/tether.js"

        app_css:
            inputs:
                - "css/app.css"
                - "%node_modules%/tether/dist/css/tether.css"

        leaflet_js:
            inputs:
                - "%node_modules%/leaflet/dist/leaflet.js"
                - "%node_modules%/leaflet.markercluster/dist/leaflet.markercluster.js"

        leaflet_css:
            inputs:
                - "%node_modules%/leaflet/dist/leaflet.css"
                - "%node_modules%/leaflet.markercluster/dist/MarkerCluster.Default.css"
                - "%node_modules%/leaflet.markercluster/dist/MarkerCluster.css"

        bootstrap_js:
            inputs:
                - "%node_modules%/bootstrap/dist/js/bootstrap.js"

        select2_js:
            inputs:
                - "%node_modules%/select2/dist/js/select2.js"

        skrollr_js:
            inputs:
                - "%node_modules%/skrollr/dist/skrollr.min.js"
                - "%node_modules%/skrollr-menu/dist/skrollr.menu.min.js"
                - "%node_modules%/unslider/dist/js/unslider-min.js"
