# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    translation.loader.db:
        class: AppBundle\TranslationLoader\DatabaseLoader
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: translation.loader, alias: db}

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
           - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.userprovider:
        class: AppBundle\Provider\UserProvider
        arguments: ['@doctrine.orm.entity_manager']

#    rox.legacy_dispatch_listener:
#        class: AppBundle\EventListener\LegacyDispatchListener
#        arguments: ['@rox.legacy_kernel', '@session', '@security.token_storage' ]
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200000 }

    rox.legacy_kernel:
        class: AppBundle\LegacyKernel\LegacyHttpKernel
        arguments: ['@templating.engine.twig', '@event_dispatcher', '@controller_resolver', '@request_stack', '@argument_resolver', '@service_container']

    rox.legacy_password_encoder:
        class: AppBundle\Encoder\LegacyPasswordEncoder

    rox.legacy_loader:
        class: AppBundle\Routing\LegacyLoader
        tags:
            - { name: routing.loader }

    rox.legacy_controller:
        class: AppBundle\Controller\LegacyController
        calls:
            - [setContainer, ['@service_container']]

    rox.twig_extension:
        class: AppBundle\Twig\Extension
        arguments: ['@session', '@doctrine.orm.entity_manager']
        tags:
             - { name: 'twig.extension' }

    rox.member_twig_extension:
        class: AppBundle\Twig\MemberTwigExtension
        public: false
        arguments: ['@security.token_storage']
        tags:
            - { name: twig.extension }

    pagerfanta.bootstrap4.template:
        class: AppBundle\Pagerfanta\TwitterBootstrap4Template

    pagerfanta.bootstrap4.view:
        class: Pagerfanta\View\DefaultView
        public: false
        arguments:
            - "@pagerfanta.bootstrap4.template"
            - "@translator"
        tags: [{ name: pagerfanta.view, alias: twitter_bootstrap4_translated }]