<?php

namespace App\Repository;

/**
 * DonationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDonationListQuery()
    {
        $qb = $this->createQueryBuilder('d');
        $query = $qb
            ->orderBy('d.created', 'DESC')
            ->getQuery();

        return $query;
    }
}
