imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # locales should be determined from the DB in the future
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl
    app.notifications.email_sender: message@bewelcome.org
    node_modules: "%kernel.root_dir%/../node_modules"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller:  twig.controller.exception:showAction
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'ckeditor/ckeditor.html.twig'

#    paths:
#        '%kernel.root_dir%/../templates/twig/forms': forms

# Doctrine Configuration

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
