# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    translation.loader.db:
        class: App\TranslationLoader\DatabaseLoader
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: translation.loader, alias: db}

    app.locale_listener:
        class: App\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
           - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: App\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.userprovider:
        class: App\Provider\UserProvider
        arguments: ['@doctrine.orm.entity_manager']

#    rox.legacy_dispatch_listener:
#        class: App\EventListener\LegacyDispatchListener
#        arguments: ['@rox.legacy_kernel', '@session', '@security.token_storage' ]
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200000 }

    rox.legacy_kernel:
        class: App\LegacyKernel\LegacyHttpKernel
        arguments: ['@templating.engine.twig', '@event_dispatcher', '@controller_resolver', '@request_stack', '@argument_resolver', '@service_container']

    rox.legacy_password_encoder:
        class: App\Encoder\LegacyPasswordEncoder

    rox.legacy_loader:
        class: App\Routing\LegacyLoader
        tags:
            - { name: routing.loader }

    rox.legacy_controller:
        class: App\Controller\LegacyController
        calls:
            - [setContainer, ['@service_container']]

    rox.twig_extension:
        class: App\Twig\Extension
        arguments: ['@session', '@doctrine', '@translator']
        tags:
            - { name: 'twig.extension' }

    rox.member_twig_extension:
        class: App\Twig\MemberTwigExtension
        public: false
        arguments: ['@session', '@doctrine.orm.entity_manager', '@router', '@security.helper']
        tags:
            - { name: twig.extension }

    pagerfanta.bootstrap4.ajax.template:
        class: App\Pagerfanta\TwitterBootstrap4AjaxTemplate

    pagerfanta.bootstrap4.ajax.view:
        class: Pagerfanta\View\DefaultView
        public: false
        arguments:
            - "@pagerfanta.bootstrap4.ajax.template"
            - "@translator"
        tags: [{ name: pagerfanta.view, alias: twitter_bootstrap4_ajax_translated }]

    rox.logger:
        class: App\Logger\Logger
        arguments: ['@doctrine.orm.entity_manager', '@security.helper']

    rox.authentication_listener:
        class: App\EventListener\AuthListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    rox.datacollector_translator:
        class: Symfony\Component\Translation\DataCollectorTranslator
        decorates: translator
        arguments: ['@rox.datacollector_translator.inner']

    rox.user_checker:
        class: App\Security\UserChecker
        autowire: true

    intl.twig_extension:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: 'twig.extension' }

    doctrine.filter.configurator:
        class: App\Doctrine\Filter\Configurator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
            - "@annotation_reader"
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    rox.wiki.model:
        class: App\Model\WikiModel
        arguments:
            - "@doctrine.orm.entity_manager"
