message:
    path: /messages/{filter}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:index
        filter: inbox
        auth_state: auth
    requirements:
        filter: inbox|sent|spam

message/update:
    path: /messages/{filter}
    methods: [POST]
    defaults:
        _controller: Rox\Message\Controller\MessageController:update
        filter: inbox
        auth_state: auth
    requirements:
        filter: inbox|sent|spam

message/with:
    path: /messages/with/{username}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:with
        auth_state: auth

message/compose:
    path: /messages/compose/{username}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:compose
        auth_state: auth

message/view:
    path: /messages/{id}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:view
        auth_state: auth
