message:
    path: /messages/{filter}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:index
        filter: inbox
    requirements:
        filter: inbox|sent|spam

message/update:
    path: /messages/{filter}
    methods: [POST]
    defaults:
        _controller: Rox\Message\Controller\MessageController:update
        filter: inbox
    requirements:
        filter: inbox|sent|spam

message/with:
    path: /messages/with/{username}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:with

message/compose:
    path: /messages/compose/{username}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:compose

message/view:
    path: /messages/{id}
    methods: [GET]
    defaults:
        _controller: Rox\Message\Controller\MessageController:view
