---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add mysql key
  sudo: yes
  apt_key:
    id: 8C718D3B5072E1F5
    keyserver: pgp.mit.edu
    state: present

- name: mysql | Add MySQL 5.7 deb package
  sudo: yes
  apt_repository:
    repo: 'deb http://repo.mysql.com/apt/debian/ jessie mysql-5.7'
    state: present

- name: Update apt
  sudo: yes
  apt:
    update_cache: yes

- name: mysql | Install MySQL Packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: mysql | Create databases
  sudo: yes
  mysql_db:
    name: "{{ mysql.database }}"
    state: present
  register: db_created

- name: mysql | Set privileges
  sudo: yes
  mysql_user:
    name: "{{ mysql.user }}"
    password: "{{ mysql.password }}"
    priv: "{{ mysql.database }}.*:ALL"
    state: present
  notify: restart mysql

- name: mysql | Create db_dumps directory
  sudo: yes
  file:
    path: "{{ rox.root_folder }}/db_dumps"
    state: directory
    group: "www-data"
    mode: "664"

- name: mysql | Fetch dump files
  sudo: yes
  get_url:
    url: http://downloads.bewelcome.org/for_developers/rox_test_db/{{ item }}
    dest: "{{ rox.root_folder }}/db_dumps"
  with_flattened:
    - "{{ mysql.dump_root }}"
    - "{{ mysql.dump }}"
  when: db_created.changed

- name: mysql | Import root dump
  mysql_db:
    name: "{{ mysql.database }}"
    state: import
    target: "{{ rox.root_folder }}/db_dumps/{{ item }}"
  with_flattened: "{{ mysql.dump_root }}"
  when: db_created.changed

- name: mysql | Import normal dumps
  mysql_db:
    name: "{{ mysql.database }}"
    state: import
    login_user: "{{ mysql.user }}"
    login_password: "{{ mysql.password }}"
    target: "{{ rox.root_folder }}/db_dumps/{{ item }}"
  with_flattened: "{{ mysql.dump }}"
  when: db_created.changed
