---
server:
    install: '1'
    packages: [nodejs, git]
    timezone: Europe/Paris
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: jessie64, hostname: bewelcome, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: bewelcome
mysql:
    install: '1'
    database: bewelcome
    user: bewelcome
    password: bewelcome
    dump_root: [bewelcome.sql.bz2]
    dump: [
        languages.sql.bz2,
        words.sql.bz2
    ]
php:
    install: '1'
    packages: [
        php5-cli,
        php5-intl,
        php5-mcrypt,
        php5-mysql,
        php5-readline,
        php5-common,
        php5-gd,
        php5-dev,
        php5-curl,
        php5-xdebug,
        php5-xmlrpc,
        php5-ssh2
    ]
composer:
    install: '1'
js_packages:
    install: '1'
rox:
    root_folder: /vagrant
    working_files: [
        build/alias.cache.ini,
        build/autoload.cache.ini,
        modules/autoload.cache.ini,
        pthacks/autoload.cache.ini,
        tools/autoload.cache.ini,
        htdocs/exception.log,
    ]

