# SecurityBundle does not allow access_control to be merged from different
# files, so this file contains all the ACL from all modules.
security:
    access_control:
        # The bottom one matches all routes, ensuring the default behaviour is
        # that users must be logged in. Other rules above are then able to
        # whitelist anonymous accessible pages.
        #
        # Note: logged in members inherit the 'anonymous' role, so to allow
        # access to both members and guests, use IS_AUTHENTICATED_ANONYMOUSLY
        #
        # To disallow logged in members, use the "not has_role('ROLE_USER')"
        #
        # Beware using IS_AUTHENTICATED_FULLY - this excludes members whose
        # session has been started from a remember me cookie. We may want to use
        # this role in future for pages such as change email/password to require
        # reentering password before making changes.
        # See https://symfony.com/doc/current/cookbook/security/remember_me.html
        - { path: ^/$, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/login$, allow_if: "not has_role('ROLE_USER')" }

        - { path: ^/about, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tour, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rox/in, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: ROLE_USER }
