# @see http://symfony.com/doc/current/reference/configuration/framework.html

framework:
    secret: todo
    templating:
        engines:
            - twig

    router:
        resource: '%kernel.root_dir%/config/routes.global.yml'

    default_locale: en

    form:
        enabled: true

    session:
      name: sidTB
      # Set the save path to null so NativeFileSessionHandler will use the PHP
      # default. The default is %kernel.cache_dir%/sessions and FPM on vagrant
      # dev could not write to the file.
      save_path: null

parameters:
    database_host:      localhost
    database_name:      bewelcome
    database_user:      root
    database_password:  null

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum:       string
            set:       string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            # ...
            Rox\Core\Entity\Trip:
                type: annotation
                dir: '%kernel.root_dir%/module/Core/src/Entity'
                is_bundle: false
                prefix: Rox\Core\Entity\Trip
                alias: Trip
            Rox\Core\Entity\SubTrip:
                type: annotation
                dir: '%kernel.root_dir%/module/Core/src/Entity'
                is_bundle: false
                prefix: Rox\Core\Entity\SubTrip
                alias: SubTrip
            Rox\Core\Entity\Member:
                type: annotation
                dir: '%kernel.root_dir%/module/Core/src/Entity'
                is_bundle: false
                prefix: Rox\Core\Entity\Member
                alias: Member