# routes.yml

activity:
    resource: ../module/Activity/config/routes.yml

admin:
    resource: ../module/Admin/config/routes.yml

auth:
    resource: ../module/Auth/config/routes.yml

forum:
    resource: ../module/Forum/config/routes.yml

i18n:
    resource: ../module/I18n/config/routes.yml

member:
    resource: ../module/Member/config/routes.yml

message:
    resource: ../module/Message/config/routes.yml

start:
    resource: ../module/Start/config/routes.yml

communitynews:
    resource: ../module/CommunityNews/config/routes.yml

trip:
    resource: ../module/Trip/config/routes.yml
