# @see http://symfony.com/doc/current/reference/configuration/twig.html

twig:
    debug: true
    strict_variables: true
    cache: 'cache/%kernel.environment%/twig/'
    exception_controller:  twig.controller.exception:showAction
    paths:
        '%kernel.root_dir%/templates/twig/macros': macros

services:
    Twig_Extensions_Extension_Text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }