auth/authorize:
    path:     /login
    methods: [POST]

auth/login:
    path:     /login
    methods: [GET]
    defaults:
        access_denied_redirect: home
        _controller: Rox\Auth\Controller\LoginController:__invoke

auth/logout:
    path:     /logout
    methods: [GET]
