# The remember_me parameters below are extracted so they can be used to
# configure the remember_me feature of the firewall (below), and also be
# fetched by the ChangePasswordController to check for remember_me cookie.
parameters:
    # Checkbox name in form
    remember_me.form_parameter: remember
    # Cookie name
    remember_me.cookie_name: remember_me

security:
    providers:
        Rox\Auth\Provider\UserProvider:
            id: Rox\Auth\Provider\UserProvider

    encoders:
        # For the legacy MySQL PASSWORD()
        Rox\Auth\Encoder\LegacyPasswordEncoder:
            id: Rox\Auth\Encoder\LegacyPasswordEncoder

        # Default for all members
        Rox\Member\Model\Member:
            algorithm: bcrypt
            cost: 12

        # Stronger password cost for privileged members. See
        # Rox\Auth\Factory\EncoderFactory
        harsh:
            algorithm: bcrypt
            cost: 13

    firewalls:
        default:
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 31536000 # 1 year in seconds
                path: /
                remember_me_parameter: '%remember_me.form_parameter%'
                name: '%remember_me.cookie_name%'

            anonymous: ~
            form_login:
                login_path: auth/login
                check_path: auth/authorize
                username_parameter: username
                password_parameter: password
                default_target_path: /home

            logout:
                path:   /logout
                target: /
