services:
    security.token_storage:
        class: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
        autowiring_types: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface

    security.authentication_utils:
        class: Symfony\Component\Security\Http\Authentication\AuthenticationUtils
        arguments: ['@request_stack']

    Rox\Auth\Provider\UserProvider:
        class: Rox\Auth\Provider\UserProvider
        autowire: true

    Rox\Auth\Encoder\LegacyPasswordEncoder:
        class: AppBundle\Encoder\LegacyPasswordEncoder

    Rox\Auth\Listener\AccessDeniedRedirectListener:
        class: Rox\Auth\Listener\AccessDeniedRedirectListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 255 }

    Rox\Auth\Listener\AuthListener:
        class: Rox\Auth\Listener\AuthListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    Rox\Auth\Factory\EncoderFactory:
        class: Rox\Auth\Factory\EncoderFactory
        arguments: ['@security.encoder_factory']
