Rox: C:/xampp/htdocs/rox/build/rox/templates/_languageselector.helper.php File Reference
_languageselector.helper.php File Reference
Functions
_languageSelector ()
cmpLang ($a, $b)
_languageOptions ($words)
_languageSelectorDropDown ()
_languageFooterSelectorDropDown ()
Function Documentation
_languageFooterSelectorDropDown ()
Definition at line 80 of file _languageselector.helper.php.
References $words, and _languageOptions().
_languageOptions ($words)
Definition at line 36 of file _languageselector.helper.php.
References $_SESSION, $lang, $languages, $model, and $words.
Referenced by _languageFooterSelectorDropDown(), and _languageSelectorDropDown().
_languageSelector ()
Definition at line 3 of file _languageselector.helper.php.
References $_SESSION, $languages, $model, and $title.
_languageSelectorDropDown ()
Definition at line 66 of file _languageselector.helper.php.
References $words, and _languageOptions().
Referenced by PublicStartpage\quicksearch().
cmpLang ($a, $b)
Definition at line 28 of file _languageselector.helper.php.