Rox: C:/xampp/htdocs/rox/build/about/templates/about.php File Reference
about.php File Reference
Variables
$words = new MOD_words()
$words get("AboutUs_TheIdea")
</h3 > $words get("AboutUs_TheIdeaText")
</p > $words get("AboutUs_GetActive")
</h3 > $words get("AboutUs_GetActiveText")
</p > $words get("AboutUs_Greetings")
</p > $words get("AboutUs_GiveFeedback")
</h3 > $words get("AboutUs_GiveFeedbackText")
</p > $words get("AboutUs_HowOrganized")
</h3 > $words get("AboutUs_HowOrganizedText")
</p > $Blog = new Blog()
$postIt = $Blog->getTaggedPostsIt('Community News for the frontpage', true)
$format = array('short'=>$words->getSilent('DateFormatShort'))
$i =1
foreach ($postIt as $blog)
Variable Documentation
$words get ("AboutUs_TheIdea")</h3> $words get ("AboutUs_TheIdeaText")</p> $words get ("AboutUs_GetActive")</h3> $words get ("AboutUs_GetActiveText")</p> $words get ("AboutUs_Greetings")</p> $words get ("AboutUs_GiveFeedback")</h3> $words get ("AboutUs_GiveFeedbackText")</p> $words get ("AboutUs_HowOrganized")</h3> $words get ("AboutUs_HowOrganizedText")</p> $Blog = new Blog()
Definition at line 53 of file about.php.
Referenced by BlogCreatePage\column_col3(), and BlogView\createForm().
$format = array('short'=>$words->getSilent('DateFormatShort'))
Definition at line 55 of file about.php.
Referenced by ApiController\checkFormat(), ApiController\response(), and WordPrintStrategy_translate\showBufferedTranslationLinks().
$i =1
Definition at line 60 of file about.php.
Referenced by MOD_mail_Multipart\addAttachment(), MOD_mail_Multipart\addTextAttachment(), buildBirthYearOptions(), SignupPage\buildBirthYearOptions(), RoxModelBase\bulkLookup(), SimplePie_Misc\change_encoding(), SimplePie_Parse_Date\date_w3cdtf(), SimplePie_Decode_HTML_Entities\entity(), StatsModel\generateStatsImages(), SimplePie_Misc\get_element(), FullPagePager\getHtml(), HalfPagePager\getHtml(), LinkModel\getIdsFromPath(), StatsModel\getLanguages(), StatsModel\getMembersPerCountry(), Rox\getMembersPerCountry(), StatsModel\getPreferredLanguages(), RoxLocalSettingsImporter\importConfigPHP(), SimplePie\init(), json_encode(), ExceptionLogger\logException(), RequestRouter\matchRoute(), MagpieRSS\normalize(), LoginModel\randomString(), MOD_user\randomString(), SimplePie_IRI\remove_iunreserved_percent_encoded(), ExceptionPage\render(), GroupMemberlistWidget\render(), DonateModel\returnFromPayPal(), Rox\returnFromPayPal(), SafeHTML\SafeHTML(), ItemlistWithPagination\showPagination(), ExceptionPage\showTraceStep(), SimplePie_Sanitize\strip_tag(), and Forums\suggestTags().
$postIt = $Blog->getTaggedPostsIt('Community News for the frontpage', true)
Definition at line 54 of file about.php.
$words = new MOD_words()
Definition at line 24 of file about.php.
Referenced by VisualComponent\__call(), _languageFooterSelectorDropDown(), _languageOptions(), _languageSelectorDropDown(), PollsModel\AddChoice(), SuggestionsModel\addOption(), SuggestionsModel\addPost(), MembersModel\addRelation(), GeoView\admin(), MOD_layoutbits\ago(), SuggestionsModel\approveSuggestion(), SignupPrivacyPopup\body(), SignupTermsPopup\body(), GeoPopupPage\body(), GallerySetPage\breadcrumbs(), GalleryUserGalleriesPage\breadcrumbs(), GalleryUserPage\breadcrumbs(), TripSingleTripPage\column_col3(), AddRelationPage\column_col3(), MyVisitorsPage\column_col3(), GalleryFlickrPage\column_col3(), SignupClosedPage\column_col3(), SignupFinishPage\column_col3(), SignupProblemPage\column_col3(), GalleryAllImagesPage\column_col3(), SignupResentMailPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryUserOverviewPage\column_col3(), HellouniversePage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), LinkUpdatePage\column_col3(), GeoAdminPage\column_col3(), SignupMailConfirmPage\column_col3(), GalleryImageNotFoundPage\column_col3(), GalleryDeletePage\column_col3(), GallerySetDetailsPage\column_col3(), GalleryUploadPage\column_col3(), NotifyAdminSettingsPage\column_col3(), OnlinePage\column_col3(), MembersMembernotfoundPage\column_col3(), MessagesPageWithMailbox\column_col3(), GalleryGalleriesPage\column_col3(), GalleryPage\column_col3(), VerifyMembersNotActivePage\column_col3(), VerifyMyselfPage\column_col3(), GalleryManagePage\column_col3(), GalleryAllGalleriesPage\column_col3(), NotifyAdminPage\column_col3(), VerifiedApprovedVerifiers\column_col3(), GroupStartPage\column_col3(), ActivitiesFindPage\column_col3(), GroupDeletePage\column_col3(), AboutFaqPage\column_col3(), AdminNoRightsPage\column_col3(), GroupJoinPage\column_col3(), GroupMemberSettingsPage\column_col3(), SignupPage\column_col3(), GroupForumPage\column_col3(), GroupLeavePage\column_col3(), GroupDeleteRelatedGroupPage\column_col3(), GroupAddRelatedGroupPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), GroupWikiPage\column_col3(), AboutFaqsectionPage\column_col3(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), GalleryUserGalleriesPage\column_col3(), InvitePage\column_col3(), LastCommentsPage\column_col3(), GalleryOverviewPage\column_col3(), PollsPage\column_col3(), ReadMessagePage\column_col3(), VerifiedMembersViewPage\column_col3(), GroupSettingsPage\column_col3(), GroupInvitePage\column_col3(), HellouniverseTabbedPage\column_col3(), GroupMemberAdministrationPage\column_col3(), GroupForumsOverviewPage\column_col3(), GallerySetPage\column_col3(), TourPage\column_col3(), GalleryUserPage\column_col3(), InviteSentPage\column_col3(), ContactNotPossible\column_col3(), MessageSentPage\column_col3(), MembersModel\confirmRelation(), BlogView\createForm(), MembersModel\delete_translation_multiple(), BlogView\editForm(), GeoView\generateLocationOverview(), GeoView\generateLocationOverviewNoJs(), GeoView\GeoDisplayLocation(), Member\get_all_relations(), MembersModel\get_relation_between_members(), Member\get_trad_by_tradid(), Places\getContinents(), MOD_layoutbits\getGenderTranslated(), GetOfferIcons(), PageWithRoxLayout\getPage_meta_description(), PageWithRoxLayout\getPage_meta_keyword(), MembersMembernotfoundPage\getPageTitle(), UpdateMandatoryPage\getPageTitle(), CommunityPage\getPageTitle(), PublicStartpage\getPageTitle(), PersonalStartpage\getPageTitle(), VerifyMembersProceedPage\getPageTitle(), VerifyMembersFinishPage\getPageTitle(), CityPage\getPageTitle(), CountriesPage\getPageTitle(), CountryPage\getPageTitle(), RegionPage\getPageTitle(), SafetyBasePage\getPageTitle(), ActivitiesBasePage\getPageTitle(), SuggestionsBasePage\getPageTitle(), GroupsBasePage\getPageTitle(), PollsPage\getPageTitle(), SuggestionsModel\getRanksAsArray(), GetRestrictionIcons(), SuggestionOption\getStatesAsArray(), SuggestionsBasePage\getStateSelect(), DebugPage\getSubmenuItems(), GalleryUserPage\getSubmenuItems(), AboutBasePage\getSubmenuItems(), ActivitiesShowPage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), ActivitiesSearchResultPage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), SafetyBasePage\getSubmenuItems(), MemberPage\getSubmenuItems(), ActivitiesBasePage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), GroupsBasePage\getSubmenuItems(), MailboxWidget_Sent\getTableColumns(), MailboxWidget\getTableColumns(), MailboxWidget_WithMember\getTableColumns(), Note\getText(), GalleryBasePage\getUserLinksItems(), MessagesModel\hasMessageLimitExceeded(), SearchmembersController\index(), AboutFaqsectionPage\leftSidebar(), AboutFaqPage\leftSidebar(), GalleryOverviewPage\leftSidebar(), OnlinePage\leftSidebar(), InactiveProfilePage\leftsidebar(), AdminMassMailEnqueuePage\leftSidebar(), VerifyMembersPage\leftSidebar(), AdminMassMailDetailsPage\leftSidebar(), AdminMassMailEditCreatePage\leftSidebar(), VerifiedApprovedVerifiers\leftSidebar(), GroupsBasePage\leftSidebar(), GalleryUserPage\leftSidebar(), VerifiedMembersViewPage\leftSidebar(), PollsPage\leftSidebar(), MemberPage\leftsidebar(), MOD_layoutbits\linkWithPicture(), MOD_layoutbits\linkWithPictureVar(), PollsModel\LoadList(), LoginController\loginCallback(), MessagesController\mailBoxCallback(), MessagesContactboxPage\mailboxDescription(), GalleryController\manage(), AdminModel\massmailEditCreateVarsOk(), MessagesPageWithMailbox\messageActions(), NotifyAdminPage\notesActions(), GroupsModel\notifyGroupAdmins(), PublicStartpage\quicksearch(), PageWithRoxLayout\quicksearch(), SignupView\registerMail(), LoginFormWidget\render(), GeoController\SelectorInclude(), MembersModel\sendCommentNotification(), MOD_mail\sendEmail(), GroupsModel\sendInvitation(), VisualComponent\set_layoutkit(), Group\setDescription(), PageWithRoxLayout\SetMetaKey(), RoxControllerBase\setTitleTranslate(), NotifyMemberWidget\showItems(), MailboxWidget_Personalstart\showListItem(), NotifyMemberWidget\showListItem(), OnlineView\ShowOnline(), PageWithHTML\statusMessage(), PageWithRoxLayout\submenu(), NotifyAdminWidget\tableCell_checked(), MembersMembernotfoundPage\teaserContent(), InvitePage\teaserContent(), MessagesBasePage\teaserContent(), GroupSettingsPage\teaserContent(), GroupsMyGroupsPage\teaserContent(), GroupsCreationPage\teaserContent(), GroupInvitePage\teaserContent(), GroupsSearchPage\teaserContent(), GroupsFeaturedPage\teaserContent(), TourPage\teaserContent(), GroupsOverviewPage\teaserContent(), ActivitiesBasePage\teaserContent(), SafetyBasePage\teaserContent(), GroupMemberAdministrationPage\teaserContent(), LastCommentsPage\teaserContent(), GroupForumsOverviewPage\teaserContent(), InviteSentPage\teaserContent(), GroupsBasePage\teaserContent(), ResetPasswordPage\teaserHeadline(), ResetPasswordFinishPage\teaserHeadline(), SignupResentMailPage\teaserHeadline(), SignupProblemPage\teaserHeadline(), SignupMailConfirmPage\teaserHeadline(), SignupClosedPage\teaserHeadline(), SignupFinishPage\teaserHeadline(), GalleryPage\teaserHeadline(), SignupPage\teaserHeadline(), VerifyNoMemberSpecifiedPage\teaserHeadline(), GallerySetPage\teaserHeadline(), VerifyMembersNotActivePage\teaserHeadline(), SetLocationPage\teaserHeadline(), VerifyMyselfPage\teaserHeadline(), VerifyMembersPage\teaserHeadline(), CountriesPage\teaserHeadline(), CityPage\teaserHeadline(), CountryPage\teaserHeadline(), RegionPage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), SuggestionsBasePage\teaserHeadline(), GalleryUserPage\teaserHeadline(), VerifiedMembersViewPage\teaserHeadline(), PollsPage\teaserHeadline(), RoxView\teasermain(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), MOD_layoutbits\truncate_words(), PollsModel\UpdateChoice(), GroupMembership\updateMembership(), PollsModel\UpdatePoll(), MembersModel\updateProfile(), MembersModel\updateRelation(), GalleryController\upload(), GalleryController\uploadedProcess(), GalleryController\user(), and GalleryView\userOverviewSimple().
foreach($postIt as $blog)
Definition at line 61 of file about.php.