Rox: C:/xampp/htdocs/rox/build/activities/templates/activitiesshow.column_col3.php File Reference
activitiesshow.column_col3.php File Reference
Variables
$activityInTheFuture = (time() < strtotime($this->activity->dateTimeEnd))
$formkit = $this->layoutkit->formkit
$callbackTagsJoinEdit = $formkit->setPostCallback('ActivitiesController', 'joinLeaveActivityCallback')
$callbackTagsCancelUncancel = $formkit->setPostCallback('ActivitiesController', 'cancelUncancelActivityCallback')
$layoutbits = new Mod_layoutbits()
$request = PRequest::get()->request
$login_url = 'login/'.htmlspecialchars(implode('/', $request), ENT_QUOTES)
$purifier = MOD_htmlpure::getActivitiesHtmlPurifier()
$status = array()
if(isset($_SESSION['ActivityStatus']))
if(!empty($status)) if($this->
activity->status==1) $errors = $this->getRedirectedMem('errors')
if(!empty($errors)) $vars = $this->getRedirectedMem('vars')
if (empty($vars)) = $words->get('ActivityDateTime')
if($this->member) else
Variable Documentation
$activityInTheFuture = (time() < strtotime($this->activity->dateTimeEnd))
Definition at line 2 of file activitiesshow.column_col3.php.
$callbackTagsCancelUncancel = $formkit->setPostCallback('ActivitiesController', 'cancelUncancelActivityCallback')
Definition at line 5 of file activitiesshow.column_col3.php.
$callbackTagsJoinEdit = $formkit->setPostCallback('ActivitiesController', 'joinLeaveActivityCallback')
Definition at line 4 of file activitiesshow.column_col3.php.
if (isset($_SESSION['ActivityStatus'])) if (!empty($status)) if ($this->activity->status==1) $errors = $this->getRedirectedMem('errors')
Definition at line 23 of file activitiesshow.column_col3.php.
$formkit = $this->layoutkit->formkit
Definition at line 3 of file activitiesshow.column_col3.php.
$layoutbits = new Mod_layoutbits()
Definition at line 7 of file activitiesshow.column_col3.php.
Referenced by Forums\__construct(), Forums\adjustThreadsCountToShow(), TripSingleTripPage\column_col3(), MyVisitorsPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), Member\get_age(), MembersModel\getCommentGuidelinesRead(), VolunteerbarModel\getNumberSpamToBeChecked(), ActivitiesModel\getRadius(), VerifyMembersModel\LoadApprovedVerifiers(), ShowMembersAjax(), ShowMembersAjaxShort(), MailboxWidget\tableCell_from(), and MailboxWidget_WithMember\tableCell_from().
$login_url = 'login/'.htmlspecialchars(implode('/', $request), ENT_QUOTES)
Definition at line 9 of file activitiesshow.column_col3.php.
Referenced by PageWithRoxLayout\quicksearch(), and PageWithRoxLayout\topnav().
$purifier = MOD_htmlpure::getActivitiesHtmlPurifier()
Definition at line 10 of file activitiesshow.column_col3.php.
Referenced by MyVisitorsPage\column_col3(), ReadMessagePage\column_col3(), and GroupMemberAdministrationPage\column_col3().
$request = PRequest::get()->request
Definition at line 8 of file activitiesshow.column_col3.php.
Referenced by SearchmembersController\__construct(), RoxController\_redirectLevel(), GeoPopupPage\body(), VerifymembersController\checkPasswordCallback(), SignupPage\column_col2(), TourPage\column_col2(), TripSingleTripPage\column_col3(), PublicStartpage\column_col3(), SignupPage\column_col3(), BlogEditPage\column_col3(), BlogCreatePage\column_col3(), BlogController\commentProcess(), BlogView\createForm(), GalleryController\createGalleryCallback(), BlogController\createProcess(), GroupsController\delete(), TripView\displayTrips(), BlogView\editForm(), AboutController\feedbackCallback(), RequestRouter\findRoute(), GalleryController\gallerydetails(), BlogBasePage\getCustomElements(), MessagesController\getPageNumber(), NotifyController\getPageNumber(), GroupsController\groupSettings(), DebugController\index(), ExtensionsController\index(), AboutController\index(), CommunityController\index(), RssController\index(), OnlineController\index(), TourController\index(), HellouniverseController\index(), NewsletterController\index(), LastCommentsController\index(), NotifyController\index(), RightsController\index(), DonateController\index(), VerifymembersController\index(), PollsController\index(), TripController\index(), MessagesController\index(), BlogController\index(), ShoutsController\index(), GalleryController\index(), LinkController\index(), SignupController\index(), InviteController\index(), RoxController\index(), SearchmembersController\index(), GeoController\index(), UserController\index(), MembersController\index_loggedIn(), MembersController\index_loggedOut(), BlogView\linkRSS(), LoginController\loginCallback(), UserView\loginForm(), GalleryController\manageCallback(), GroupsController\memberSettings(), MessagesPageWithMailbox\messageActions(), MembersController\myPreferencesCallback(), PageWithRoxLayout\quicksearch(), RoxControllerBase\redirect(), RoxFrontRouter\route(), RoxFrontRouter\route_ajax(), RoxFrontRouter\route_normal(), RoxFrontRouter\runControllerMethod(), MembersController\setLocationCallback(), ForumsView\showExternal(), ForumsView\showForum(), ForumsView\showTopic(), ForumsView\showTopLevelCategories(), ForumsView\showTopLevelLandingPage(), ForumsView\showTopLevelRecentPosts(), SignupController\signupFormCallback(), ForumsView\teaser(), PublicStartpage\teaserContent(), PageWithRoxLayout\topnav(), translate(), GalleryController\updateGalleryCallback(), and VerifymembersController\verifyCallback().
$status = array()
Definition at line 11 of file activitiesshow.column_col3.php.
Referenced by ActivitiesModel\checkJoinLeaveActivityVarsOk(), Feedback\createNew(), BlogEntity\delete(), GalleryController\deleteGallery(), GroupMembership\getGroupMembers(), AdminModel\getMassmail(), AdminModel\getMassmailRecipientsCount(), AdminModel\getMassmailRecipientsInfo(), Group\getMemberCount(), GroupMembership\getMemberGroups(), Group\getMembers(), GroupsModel\getMembershipStatus(), GalleryController\index(), BlogEntity\insert(), Activity\insert(), GroupsModel\joinGroup(), ActivitiesModel\joinLeaveActivity(), Suggestion\loadEntity(), SuggestionOption\loadEntity(), BlogEntity\loadEntity(), Activity\loadEntity(), Group\loadEntity(), MagpieRSS\MagpieRSS(), GroupMembership\memberJoin(), Group\memberJoin(), RSSCache\RSSCache(), InviteModel\sendOrComplain(), SignupView\signupTeamMail(), BlogEntity\update(), Suggestion\update(), MembersModel\updateProfile(), and GroupMembership\updateStatus().
if (!empty($errors)) $vars = $this->getRedirectedMem('vars')
Definition at line 32 of file activitiesshow.column_col3.php.
if ($this->member) else
Initial value:
{
                        echo '<div class="row"><h3>' .  $words->get('ActivityAttendees') . '</h3>'
Definition at line 86 of file activitiesshow.column_col3.php.
if ($this->activity->attendeesYes!=0) if ($this->activity->attendeesMaybe!=0) if ($this->activity->attendeesNo!=0) if($this->member) = $words->get('ActivityDateTime')
Definition at line 33 of file activitiesshow.column_col3.php.