Rox: C:/xampp/htdocs/rox/build/activities/templates/activitiesactivitiesnearme.column_col3.php File Reference
activitiesactivitiesnearme.column_col3.php File Reference
Variables
$vars = $this->getRedirectedMem('vars')
if(empty($vars)) $radiusSelect = '<select name="activity-radius" id="activity-radius">'
$distance
endforeach
if(count($this->activities)==0) else
Variable Documentation
$distance
Initial value:
= array(
    0 => '0 km/0 mi',
    5  => '5 km/3 mi',
    10 => '10 km/6 mi',
    25 => '25 km/15 mi',
    50 => '50 km/30 mi',
    100 => '100 km/60 mi',
)
Definition at line 7 of file activitiesactivitiesnearme.column_col3.php.
Referenced by ActivitiesController\activitiesNearMe(), ActivitiesModel\getActivitiesNearMe(), ActivitiesModel\getActivitiesNearMeCount(), ActivitiesModel\getNearMeQuery(), and MOD_trips\RetrieveVisitorsInCityWithAPicture().
$radiusSelect = '<select name="activity-radius" id="activity-radius">'
Definition at line 6 of file activitiesactivitiesnearme.column_col3.php.
$vars = $this->getRedirectedMem('vars')
Definition at line 2 of file activitiesactivitiesnearme.column_col3.php.
Referenced by AdminView\activitylogs(), MembersModel\addComment(), VerifyMembersModel\AddNewVerified(), MembersModel\addRelation(), Forums\adjustThreadsCountToShow(), User\avatarProcess(), BlogController\categoryProcess(), Blog\categoryProcess(), SuggestionsModel\checkAddOptionVarsOk(), MembersModel\checkCommentForm(), SuggestionsModel\checkEditCreateSuggestionVarsOk(), MembersModel\checkMyPreferences(), VerifymembersController\checkPasswordCallback(), VerifyMembersModel\checkPasswordsOfMembers(), MembersModel\checkProfileForm(), SearchModel\checkSearchVarsOk(), VerifyMembersModel\checkVerificationForm(), RoxControllerBase\cleanVars(), TripSingleTripPage\column_col3(), SignupPage\column_col3(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), GalleryController\commentProcess(), BlogController\commentProcess(), Blog\commentProcess(), MembersModel\confirmRelation(), BlogView\createForm(), GalleryController\createGalleryCallback(), TripController\createProcess(), BlogController\createProcess(), Forums\createProcess(), Trip\createTrip(), BlogController\deleteProcess(), Trip\delProcess(), Blog\editFill(), BlogView\editForm(), GalleryController\editGalleryProcess(), EditProfilePage\editMyProfileFormPrepare(), ForumsView\editPost(), MembersModel\editPreferences(), Trip\editProcess(), BlogController\editProcess(), GalleryController\editProcess(), Forums\editProcess(), AdminModel\enqueueMassmail(), Forums\getEditData(), AdminModel\getEnqueueAction(), SearchModel\getResultsForLocation(), BlogController\index(), GalleryController\index(), SearchmembersController\index(), GroupsController\inviteMemberAjax(), User\loginProcess(), GalleryController\manageCallback(), AdminModel\massmailEditCreateVarsOk(), AdminModel\massmailEnqueueVarsOk(), RequestRouter\matchRoute(), ForumsView\ModeditPost(), Forums\ModeratorEditPostProcess(), Forums\ModeratorEditTagProcess(), MembersController\myPreferencesCallback(), MembersModel\polishProfileFormValues(), Trip\prepareEditData(), VerifyMembersModel\prepareVerificationData(), AdminModel\procActivitylogs(), GroupsController\realImg(), SignupModel\registerBWMember(), SignupView\registerForm(), SignupView\registerMail(), User\registerProcess(), SignupModel\registerProcess(), Forums\replyProcess(), Forums\reportpostProcess(), RoxFrontRouter\route_ajax(), RoxFrontRouter\route_normal(), Searchmembers\search(), SearchController\searchMembersCallback(), FeedbackModel\sendFeedback(), MessagesController\sendMessageCallback(), MembersModel\setLocation(), MembersController\setLocationCallback(), MembersModel\ShallICrypt(), ForumsView\showModeratorEditPost(), ForumsView\showModeratorEditTag(), ForumsView\showReportList(), ForumsView\showReportPost(), SignupController\signupFormCallback(), SignupView\signupTeamMail(), AdminModel\startDonationCampaign(), GroupsController\thumbImg(), AdminController\treasurerEditCreateDonationCallback(), AdminModel\treasurerEditCreateDonationVarsOk(), AdminController\treasurerStartDonationCampaignCallback(), AdminModel\treasurerStartDonationCampaignVarsOk(), GalleryController\updateGalleryCallback(), MembersModel\updateProfile(), MembersModel\updateRelation(), GalleryController\uploadedProcess(), GalleryModel\uploadProcess(), GalleryController\uploadProcess(), RequestRouter\url(), GalleryView\userOverviewSimple(), and VerifymembersController\verifyCallback().
if (count($this->activities)==0) else
Initial value:
{
    require_once('activitieslist.php')
Definition at line 33 of file activitiesactivitiesnearme.column_col3.php.
endforeach
Definition at line 21 of file activitiesactivitiesnearme.column_col3.php.
Referenced by NotifyAdminSettingsPage\column_col3(), and GroupMemberAdministrationPage\column_col3().