Rox: C:/xampp/htdocs/rox/build/members/templates/addcomment.column_col3.php File Reference
addcomment.column_col3.php File Reference
Variables
$words = $this->words
$ww = $this->ww
$layoutbits = new MOD_layoutbits()
$commenter = $this->loggedInMember->Username
$member = $this->member
$Username = $member->Username
$syshcvol = PVars::getObj('syshcvol')
$ttc = $syshcvol->LenghtComments
$max = count($ttc)
$comments = $member->get_comments_commenter($this->loggedInMember->id)
$TCom = (isset($comments[0])) ? $comments[0] : false
$edit_mode = $TCom
if(!$mem_redirect=$this->
layoutkit->formkit->
getMemFromRedirect()) else
$ttLenght = array()
for($ii=0;$ii< $max;$ii++) if(isset($vars['Quality']))
if(isset($vars['TextWhere']))
if(isset($vars['TextFree']))
if(isset($vars['AllowEdit'])) $replacePatterns
$replacements
$mem_redirect = $this->layoutkit->formkit->getMemFromRedirect()
$page_url = PVars::getObj('env')->baseuri . implode('/', PRequest::get()->request)
$formkit = $this->layoutkit->formkit
$callback_tag = $formkit->setPostCallback('MembersController', 'commentCallback')
for ($ii=0;$ii< $max;$ii++) =$words->get("CommentLength", $Username)
Variable Documentation
$callback_tag = $formkit->setPostCallback('MembersController', 'commentCallback')
Definition at line 84 of file addcomment.column_col3.php.
$commenter = $this->loggedInMember->Username
Definition at line 6 of file addcomment.column_col3.php.
$comments = $member->get_comments_commenter($this->loggedInMember->id)
Definition at line 13 of file addcomment.column_col3.php.
$edit_mode = $TCom
Definition at line 15 of file addcomment.column_col3.php.
$formkit = $this->layoutkit->formkit
Definition at line 83 of file addcomment.column_col3.php.
$layoutbits = new MOD_layoutbits()
Definition at line 4 of file addcomment.column_col3.php.
$max = count($ttc)
Definition at line 12 of file addcomment.column_col3.php.
$mem_redirect = $this->layoutkit->formkit->getMemFromRedirect()
Definition at line 79 of file addcomment.column_col3.php.
Referenced by GeoController\AdminCallback(), GeoPopupPage\body(), HellouniverseController\calculatorCallback(), BlogController\categoryProcess(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), VerifymembersController\checkPasswordCallback(), HellouniverseCalculatorPage\column_col3(), LinkShowFriendsPage\column_col3(), GeoAdminPage\column_col3(), GallerySetDetailsPage\column_col3(), LinkShowPage\column_col3(), GalleryManagePage\column_col3(), SignupPage\column_col3(), GalleryController\createGalleryCallback(), GroupsController\createGroupCallback(), BlogController\createProcess(), AboutController\feedbackCallback(), VerifymembersController\index(), InviteController\InviteCallback(), GroupsController\joined(), LinkController\LinkShowCallback(), LinkController\LinkShowFriendsCallback(), MessagesController\mailBoxCallback(), GalleryController\manageCallback(), MembersController\myPreferencesCallback(), NotifyController\NotifyAdminCallback(), LoginFormWidget\render(), GeoController\SelectorCallback(), GeoController\SelectorInclude(), MessagesController\sendMessageCallback(), MembersController\setLocationCallback(), SignupController\signupFormCallback(), GalleryController\updateGalleryCallback(), and VerifymembersController\verifyCallback().
$member = $this->member
Definition at line 7 of file addcomment.column_col3.php.
$page_url = PVars::getObj('env')->baseuri . implode('/', PRequest::get()->request)
Definition at line 81 of file addcomment.column_col3.php.
$replacements
Initial value:
= array(
    "\n\n",
    "\n\n",
    "\n",
    "\n",
    '$1'
)
Definition at line 59 of file addcomment.column_col3.php.
for ($ii=0;$ii< $max;$ii++) if (isset($vars['Quality'])) if (isset($vars['TextWhere'])) if (isset($vars['TextFree'])) if (isset($vars['AllowEdit'])) $replacePatterns
Initial value:
= array(
    '/<hr>/',
    '/<hr \/>/',
    '/<br>/',
    '/<br \/>/',
    '/<font color=gray><font size=1>(comment date .*)<\/font><\/font>/'
)
Definition at line 52 of file addcomment.column_col3.php.
$syshcvol = PVars::getObj('syshcvol')
Definition at line 10 of file addcomment.column_col3.php.
Referenced by MembersModel\addComment(), and MembersModel\checkCommentForm().
$TCom = (isset($comments[0])) ? $comments[0] : false
Definition at line 14 of file addcomment.column_col3.php.
Referenced by MembersModel\addComment(), and MemberPage\getSubmenuItems().
$ttc = $syshcvol->LenghtComments
Definition at line 11 of file addcomment.column_col3.php.
$ttLenght = array()
Definition at line 29 of file addcomment.column_col3.php.
$Username = $member->Username
Definition at line 8 of file addcomment.column_col3.php.
Referenced by VerifiedMembersViewPage\column_col3(), MOD_bw_user_Auth\doBWLogin1(), and SignupModel\UsernameInUse().
$words = $this->words
Definition at line 2 of file addcomment.column_col3.php.
$ww = $this->ww
Definition at line 3 of file addcomment.column_col3.php.
Referenced by VisualComponent\__call(), DeleteTranslationPage\column_col3(), FeedbackSentPage\column_col3(), MOD_crypt\get_crypted(), GalleryUserPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), GalleryBasePage\getUserLinksItems(), LoginFormWidget\render(), and GalleryBasePage\userLinks().
if (isset($vars['errors'])&&!empty($vars['errors'])) if (isset($TCom->comQuality)&&$TCom->comQuality=="Bad"&&$TCom->AllowEdit!=1) else
Initial value:
{
    $vars = $mem_redirect->post
Definition at line 24 of file addcomment.column_col3.php.
for($ii=0;$ii< $max;$ii++) =$words->get("CommentLength", $Username)
Definition at line 152 of file addcomment.column_col3.php.