Rox: adminwordshowlist.column_col3.php File Reference
adminwordshowlist.column_col3.php File Reference
Namespaces
Apps
Variables
$layoutbits = new MOD_layoutbits
$formkit = $this->layoutkit->formkit
$callback_tag = $formkit->setPostCallback('AdminWordController', 'showListCallback')
$this words = new MOD_words()
if ($this->noScope)
Variable Documentation
$callback_tag = $formkit->setPostCallback('AdminWordController', 'showListCallback')
$formkit = $this->layoutkit->formkit
$layoutbits = new MOD_layoutbits
if($this->noScope)
$this words = new MOD_words()
Referenced by !function(), ForumsView\__construct(), AdminWordController\__construct(), Member\__construct(), Forums\__construct(), AdminWordController\createCodeCallback(), Forums\DofTradUpdate(), AdminWordController\editCodeCallback(), AdminWordController\editTranslationCallback(), Forums\getAllTags(), Forums\getEditData(), AboutBasePage\getPageTitle(), VerifiedApprovedVerifiers\getPageTitle(), Forums\getTagsMaximum(), Forums\getTagsNamed(), GalleryUserGalleriesPage\init(), Forums\InsertInFTrad(), ForumsView\postURL(), Forums\ReplaceInFTrad(), VisualComponent\set_layoutkit(), ForumsView\showForum(), AdminWordBasePage\showScope(), ForumsView\showTopic(), ForumsView\showTopLevelCategories(), ForumsView\showTopLevelLandingPage(), ForumsView\showTopLevelRecentPosts(), GalleryGalleriesPage\teaserHeadline(), GalleryAllGalleriesPage\teaserHeadline(), AdminMassMailEnqueuePage\teaserHeadline(), AdminMassMailDetailsPage\teaserHeadline(), AdminTreasurerEditCreateDonationPage\teaserHeadline(), AdminMassMailEditCreatePage\teaserHeadline(), and ForumsView\threadURL().