Rox: admintreasurer.column_col3.php File Reference
admintreasurer.column_col3.php File Reference
Namespaces
Apps
Variables
$words = new MOD_words()
$R = MOD_right::get()
$hasRight = $R->hasRight('Treasurer')
if(isset($_SESSION['AdminTreasurerStatus']))
if($this->campaign) else
$ii = 0
Variable Documentation
$hasRight = $R->hasRight('Treasurer')
Referenced by Rox\getDonations().
$ii = 0
$R = MOD_right::get()
Referenced by MOD_words\__construct(), Rox\getDonations(), VolunteerbarModel\getNumberPersonsToAcceptInGroup(), VolunteerbarModel\getNumberPersonsToBeChecked(), SearchmembersController\index(), GeoController\index(), AdminModel\procActivitylogs(), VolunteerLinksWidget\render(), and AdminController\wordsDownload().
$words = new MOD_words()
if (isset($_SESSION['AdminTreasurerStatus'])) if ($this->campaign) else
Initial value:
{
    echo '<h3>' . $words->get("AdminTreasurerRecentDonations") . '</h3>'