Rox: C:/xampp/htdocs/rox/build/admin/templates/adminmassmailenqueue.column_col3.php File Reference
adminmassmailenqueue.column_col3.php File Reference
Variables
$activefieldset = ""
$defaultfieldset = "members"
$formkit = $this->layoutkit->formkit
$callback_tags = $formkit->setPostCallback('AdminController', 'massmailEnqueueCallback')
$errors = $this->getRedirectedMem('errors')
if(!empty($errors)) $vars = $this->getRedirectedMem('vars')
$action = $this->getRedirectedMem('action')
if(!empty($action)) else
if($this->canEnqueueMembers)
if($this->canEnqueueLocation)
if($this->canEnqueueGroup) if($this->
type== 'RemindToLog'&&$this->
canEnqueueReminder) if($this->
type== 'SuggestionReminder'&&$this->
canEnqueueSuggestionsReminder) if ($this->type== 'TermsOfUse'&&$this->canEnqueueTermsOfUse)
Variable Documentation
$action = $this->getRedirectedMem('action')
Definition at line 17 of file adminmassmailenqueue.column_col3.php.
Referenced by PollsPage\__construct(), GeoController\AdminCallback(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), AddRelationPage\column_col3(), GroupsController\createGroupCallback(), AdminModel\enqueueMassmail(), RoxPostHandler\getCallbackAction(), AdminModel\getEnqueueAction(), InviteController\InviteCallback(), LoginController\loginCallback(), MessagesController\mailBoxCallback(), AdminController\massmailEnqueueCallback(), AdminModel\massmailEnqueueVarsOk(), NotifyController\NotifyAdminCallback(), AdminModel\processMembers(), RoxFrontRouter\route_normal(), and MessagesController\sendMessageCallback().
$activefieldset = ""
Definition at line 2 of file adminmassmailenqueue.column_col3.php.
$callback_tags = $formkit->setPostCallback('AdminController', 'massmailEnqueueCallback')
Definition at line 5 of file adminmassmailenqueue.column_col3.php.
$defaultfieldset = "members"
Definition at line 3 of file adminmassmailenqueue.column_col3.php.
$errors = $this->getRedirectedMem('errors')
Definition at line 7 of file adminmassmailenqueue.column_col3.php.
$formkit = $this->layoutkit->formkit
Definition at line 4 of file adminmassmailenqueue.column_col3.php.
if (!empty($errors)) $vars = $this->getRedirectedMem('vars')
Definition at line 16 of file adminmassmailenqueue.column_col3.php.
if (!empty($action)) else
Initial value:
{
        if ($this->canEnqueueMembers) {
            $defaultfieldset =  'members';
        } elseif ($this->canEnqueueLocation) {
            $defaultfieldset =  'location';
        } elseif ($this->canEnqueueGroup) {
            $defaultfieldset =  'group';
        } elseif ($this->canEnqueueReminder) {
            $defaultfieldset =  'reminder';
        } elseif ($this->canEnqueueTermsOfUse) {
            $defaultfieldset =  'termsofuse';
        }
    }
    $words = new MOD_words()
Definition at line 36 of file adminmassmailenqueue.column_col3.php.
if ($this->canEnqueueMembers) if ($this->canEnqueueLocation) if ($this->canEnqueueGroup) if ($this->type== 'RemindToLog'&&$this->canEnqueueReminder) if ($this->type== 'SuggestionReminder'&&$this->canEnqueueSuggestionsReminder) if($this->type== 'TermsOfUse'&&$this->canEnqueueTermsOfUse)
Definition at line 167 of file adminmassmailenqueue.column_col3.php.