Rox: C:/xampp/htdocs/rox/build/admin/templates/adminmassmailenqueue.column_col3.helper.php File Reference
adminmassmailenqueue.column_col3.helper.php File Reference
Variables
if(count($this->
enqueueCountries)<> 0) else
$countries = $this->model->BulkLookup($query)
$groups = $this->model->BulkLookup($query)
Variable Documentation
$countries = $this->model->BulkLookup($query)
Definition at line 9 of file adminmassmailenqueue.column_col3.helper.php.
Referenced by AdminMassMailBasePage\__construct(), MOD_geo\getAllCountries(), Places\getAllCountries(), and Forums\getAllCountries().
$groups = $this->model->BulkLookup($query)
Definition at line 18 of file adminmassmailenqueue.column_col3.helper.php.
Referenced by AdminMassMailBasePage\__construct(), GroupsModel\getLastVisited(), GroupMembership\getMemberGroups(), and ForumsView\showTopLevelLandingPage().
if (count($this->enqueueGroups)<> 0) else
Initial value:
{
        $query = "SELECT iso_alpha2,name FROM geonames_countries ORDER BY name"
Definition at line 6 of file adminmassmailenqueue.column_col3.helper.php.