Rox: C:/xampp/htdocs/rox/inc/base.inc.php File Reference
base.inc.php File Reference
Namespaces
core
Variables
$B = DOMDocument::load(SCRIPT_BASE.'base.xml')
if(!$B) $B x = new DOMXPath($B)
$is = $B->x->query('/basedata/is')
if($is->length!=1) if($is->
item(0) ->nodeValue!= 'respice
platform PT') $version = $B->x->query('/basedata/version')
$libdir = SCRIPT_BASE.'lib'.$version
const LIB_DIR $libdir.'/'
$buildDir = 'build'
$build = $B->x->query('/basedata/build')
const BUILD_DIR SCRIPT_BASE.$buildDir.'/'
$template = $B->x->query('/basedata/template')
$templateDir = SCRIPT_BASE.'templates'
const TEMPLATE_DIR (!file_exists($templateDir)||!is_dir($templateDir)||!is_readable($templateDir)) $templateDir.'/'
$datadir = SCRIPT_BASE.'data'
const DATA_DIR (!file_exists($datadir)||!is_dir($datadir)||!is_writable($datadir)) $datadir.'/'
Variable Documentation
$B = DOMDocument::load(SCRIPT_BASE.'base.xml')
Definition at line 12 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML().
$build = $B->x->query('/basedata/build')
Definition at line 44 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML(), and EnvironmentExplorer\loadDefaults().
$buildDir = 'build'
Definition at line 43 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML().
$datadir = SCRIPT_BASE.'data'
Definition at line 69 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML().
$is = $B->x->query('/basedata/is')
Definition at line 19 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML().
$libdir = SCRIPT_BASE.'lib'.$version
Definition at line 35 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML().
$template = $B->x->query('/basedata/template')
Definition at line 56 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML(), Layoutkit\showTemplate(), and AbstractBasePage\showTemplate().
$templateDir = SCRIPT_BASE.'templates'
Definition at line 57 of file base.inc.php.
Referenced by EnvironmentExplorer\loadBaseXML().
if ($version->length!=1) $version = $B->x->query('/basedata/version')
Definition at line 28 of file base.inc.php.
Referenced by _getVersionInfo(), SimplePie_Misc\debug(), RoxComponentBase\getVersionInfo(), and EnvironmentExplorer\loadBaseXML().
const BUILD_DIR SCRIPT_BASE.$buildDir.'/'
Definition at line 53 of file base.inc.php.
Referenced by EnvironmentExplorer\loadDefaults().
const DATA_DIR(!file_exists($datadir)||!is_dir($datadir)||!is_writable($datadir)) $datadir.'/'
Definition at line 73 of file base.inc.php.
const LIB_DIR $libdir.'/'
Definition at line 40 of file base.inc.php.
const TEMPLATE_DIR(!file_exists($templateDir)||!is_dir($templateDir)||!is_readable($templateDir)) $templateDir.'/'
Definition at line 67 of file base.inc.php.
Referenced by RoxView\aboutBar(), RoxView\aboutpage(), RoxView\affiliations(), RoxView\bodpage(), SetLocationPage\body(), TourPage\body(), PageWithRoxLayout\body(), PageWithRoxLayout\columnsArea(), RoxView\commentguidelines(), PageWithRoxLayout\debugInfo(), RoxView\donate(), RoxView\donateBar(), RoxTemplate\filepath(), UserView\friends(), RoxView\getactivepage(), VolunteermenuWidget\getTemplatePath(), RoxView\globalhelppage(), RoxView\impressum(), UserView\loginForm(), RoxView\mainpage(), UserView\picture(), RoxView\privacy(), PageWithRoxLayout\quicksearch(), UserView\registerConfirm(), UserView\registerForm(), UserView\registerMail(), RoxGenericPage_OLD\render(), LinkSinglePictureLinkpathWidget\render(), UserView\searchResult(), UserView\settingsForm(), UserView\ShowInfoMessage(), DonateView\ShowSimpleTeaser(), RoxView\ShowSimpleTeaser(), RoxView\stats(), PageWithRoxLayout\submenu(), RoxView\submenuGetAnswers(), RoxView\submenuVolunteer(), RoxView\teaser(), UserView\teaser(), PageWithRoxLayout\teaser(), PageWithRoxLayout\teaserContent(), RoxView\teasergetanswers(), RoxView\teaservolunteer(), RoxView\terms(), RoxView\thepeoplepage(), PageWithRoxLayout\topmenu(), RoxView\topMenu(), ForumsView\topMenu(), PageWithRoxLayout\topnav(), RoxView\userBar(), UserView\userPage(), RoxView\volunteerpage(), RoxView\volunteersearchpage(), RoxView\volunteerToolsBar(), and RoxView\volunteertoolspage().
if (!$B) $B x = new DOMXPath($B)
Definition at line 16 of file base.inc.php.
Referenced by !function(), getxmlEl(), and if().