Rox: blogSmallMapGeoLocation.js File Reference
blogSmallMapGeoLocation.js File Reference
Functions
function initOsmMapBlogEdit ()
function removeHighlight ()
function setMap (geonameid, latitude, longitude, zoom, geonamename, countryname, countrycode, admincode)
function changeMarkerBlog (markerLatitude, markerLongitude, zoomLevel, markerDescription)
function setGeonameIdInFormBlog (geonameid, latitude, longitude, geonamename, countrycode, admincode)
Variables
var mapBuilder
var firstChange = true
Function Documentation
function changeMarkerBlog (markerLatitude, markerLongitude, zoomLevel, markerDescription)
References firstChange, jQuery, and mapBuilder.
Referenced by setMap().
function initOsmMapBlogEdit ()
References BWSimpleMapBuilder, jQuery, and mapBuilder.
function removeHighlight ()
References Element.
Referenced by setMap().
function setGeonameIdInFormBlog (geonameid, latitude, longitude, geonamename, countrycode, admincode)
References geonameid, and jQuery.
Referenced by setMap().
function setMap (geonameid, latitude, longitude, zoom, geonamename, countryname, countrycode, admincode)
called when an user click on a result of the list, to update the marker.
References changeMarkerBlog(), Element, geonameid, removeHighlight(), and setGeonameIdInFormBlog().
Variable Documentation
var firstChange = true
Referenced by changeMarkerBlog().
var mapBuilder
Referenced by changeMarkerBlog(), displayMap(), and initOsmMapBlogEdit().