Rox: C:/xampp/htdocs/rox/build/gallery/templates/image.php File Reference
image.php File Reference
Variables
$words = new MOD_words()
$request = PRequest::get()->request
$login_url = 'login/' . htmlspecialchars(implode('/', $request), ENT_QUOTES)
$Gallery = new GalleryModel
$Gallery_ctrl = new GalleryController
if($member=$this->model->
getLoggedInMember()) $GalleryRight = MOD_right::get()->hasRight('Gallery')
$d = $image
$d user_handle = MOD_member::getUserHandle($d->user_id_foreign)
$canEdit = ($member && $member->Username == $d->user_handle) ? true : false
if(!isset($vars['errors']))
echo;if(!$d->description==0){echo;}elseif($canEdit){echo;}if($canEdit||($GalleryRight >
1)){$title=htmlentities($d->
title, ENT_COMPAT, 'utf-8');$description=htmlentities($d->
description, ENT_COMPAT, 'utf-8');echo;}echo;echo '
< a id="link_'.$d-> id $d id
$d title $d description $d id
$d id
$comments = $this->model->getComments($image->id)
if(!$comments) else
$lastHandle = ''
foreach ($comments as $comment)
Variable Documentation
$canEdit = ($member && $member->Username == $d->user_handle) ? true : false
Definition at line 17 of file image.php.
$comments = $this->model->getComments($image->id)
Definition at line 113 of file image.php.
Referenced by LinkDisplayPage\column_col3(), LinkSimplePage\column_col3(), LinkModel\createLinkList(), LinkModel\getChanges(), MessagesModel\hasMessageLimitExceeded(), and SimplePie_Sanitize\sanitize().
$d = $image
Definition at line 15 of file image.php.
$Gallery = new GalleryModel
Definition at line 5 of file image.php.
$Gallery_ctrl = new GalleryController
Definition at line 6 of file image.php.
if ($member=$this->model->getLoggedInMember()) $GalleryRight = MOD_right::get()->hasRight('Gallery')
Definition at line 14 of file image.php.
$lastHandle = ''
Definition at line 118 of file image.php.
$login_url = 'login/' . htmlspecialchars(implode('/', $request), ENT_QUOTES)
Definition at line 4 of file image.php.
$request = PRequest::get()->request
Definition at line 3 of file image.php.
$words = new MOD_words()
Definition at line 2 of file image.php.
if ($member) else
Initial value:
{
    $count = 0
Definition at line 116 of file image.php.
foreach($comments as $comment)
Definition at line 119 of file image.php.
if (!isset($vars['errors'])) echo; if (!$d->description == 0) { echo ; } elseif ($canEdit) { echo ; } if ($canEdit || ($GalleryRight > 1)) { $title = htmlentities($d->title, ENT_COMPAT, 'utf-8'); $description = htmlentities($d->description, ENT_COMPAT, 'utf-8'); echo ;}echo ;echo '<a id="link_'.$d-> id $d id $d title $d description $d id $d id
Definition at line 19 of file image.php.
$d user_handle = MOD_member::getUserHandle($d->user_id_foreign)
Definition at line 16 of file image.php.