Rox: C:/xampp/htdocs/rox/build/about/magpierss/code.php File Reference
code.php File Reference
Variables
$url = 'http://blogs.bevolunteer.org/feed'
$num_items = 10
$rss = fetch_rss($url)
$items = array_slice($rss->items, 0, $num_items)
$rss channel ['title']
$rss< br > foreach ($items as $item) = '>' . $display . '</option>'
$words get(moreEntriesandComments)
</a > n
Variable Documentation
$items = array_slice($rss->items, 0, $num_items)
Definition at line 9 of file code.php.
Referenced by SimplePie\get_item(), SimplePie\get_items(), Activity\getActivitiesForMember(), ActivitiesModel\getActivitiesNearMe(), ItemlistWidget\getItems(), ItemlistWithPagination\getItemsInRange(), ActivitiesModel\getMyActivities(), SuggestionsModel\getOptions(), ActivitiesModel\getPastActivities(), ActivitiesShowPage\getSubmenuItems(), ActivitiesEditCreatePage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), ActivitiesSearchResultPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), SafetyBasePage\getSubmenuItems(), ActivitiesBasePage\getSubmenuItems(), LastCommentsPage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), GroupsBasePage\getSubmenuItems(), SuggestionsModel\getSuggestions(), PageWithRoxLayout\getTopmenuItems(), ActivitiesModel\getUpcomingActivities(), GalleryBasePage\getUserLinksItems(), SimplePie_Cache_MySQL\load(), SimplePie\merge_items(), SimplePie_Cache_DB\prepare_simplepie_object_for_cache(), Trip\reorderTripItems(), SimplePie_Cache_MySQL\save(), ActivitiesModel\searchActivities(), Activity\searchActivities(), ItemlistWidget\showItems_float(), ItemlistWidget\showItems_list(), NotifyMemberWidget\showItems_list(), ItemlistWidget\showItems_table(), and GalleryBasePage\userLinks().
$num_items = 10
Definition at line 6 of file code.php.
$rss = fetch_rss($url)
Definition at line 7 of file code.php.
Referenced by _response_to_rss(), fetch_rss(), RSSCache\get(), RSSCache\serialize(), and RSSCache\set().
$url = 'http://blogs.bevolunteer.org/feed'
Definition at line 4 of file code.php.
Referenced by _fetch_remote_file(), _getBugreportLink(), Snoopy\_httprequest(), Snoopy\_httpsrequest(), RequestRouter\addRoute(), RSSCache\cache_age(), RSSCache\check_cache(), MessagesMustloginPage\column_col3(), VerifyMustLoginPage\column_col3(), fetch_rss(), MOD_geonames\fetchFile(), RSSCache\file_name(), SimplePie_Misc\fix_protocol(), RSSCache\get(), SimplePie_Source\get_authors(), SimplePie_Item\get_authors(), SimplePie\get_authors(), SimplePie_Source\get_contributors(), SimplePie_Item\get_contributors(), SimplePie\get_contributors(), SimplePie_Item\get_enclosures(), SimplePie_Enclosure\get_extension(), ActivitiesController\getPager(), SuggestionsController\getPager(), PageWithHTML\includeLateScriptfiles(), PageWithHTML\includeScriptfiles(), PageWithHTML\includeStylesheets(), MembersController\index_loggedIn(), SimplePie\init(), MemberPage\leftsidebar(), LoginController\loginCallback(), RequestRouter\matchRoute(), SimplePie_Misc\normalize_url(), GroupsModel\notifyGroupAdmins(), PagerWidget\outputLink(), SimplePie_Cache\parse_URL(), SimplePie_Misc\parse_url(), RoxControllerBase\redirectAbsolute(), LoginFormWidget\render(), GroupsModel\sendInvitation(), RSSCache\set(), SimplePie\set_feed_url(), MessagesMustloginPage\setRedirectURL(), VerifyMustLoginPage\setRedirectURL(), VerifyMembersNotActivePage\setRedirectURL(), VerifyMyselfPage\setRedirectURL(), SuggestionsController\show(), GalleryUserPage\submenu(), GalleryBasePage\submenu(), and RequestRouter\url().
$rss channel['title']
Definition at line 11 of file code.php.
Referenced by MagpieRSS\append(), MagpieRSS\append_content(), and MagpieRSS\normalize().
foreach = '>' . $display . '</option>'
Definition at line 14 of file code.php.
Referenced by DatabaseSummaryWidget\tableCell().
tinymce tinymce tinymce c f c n
Definition at line 28 of file code.php.
Referenced by !function(), Trip\editProcess(), and ForumsView\generateClickableTagSuggestions().