Rox: C:/xampp/htdocs/rox/build/blog/templates/editcreateform.php File Reference
editcreateform.php File Reference
Namespaces
blog
Variables
if(!$member) $words = new MOD_words()
if(!isset($disableTinyMCE)||($disableTinyMCE==
'No')) if(in_array('inserror',
$vars['errors'])) if (in_array('upderror', $vars['errors'])) =$words->get('BlogCreateLabelTitle')
if (in_array('title', $vars['errors'])) =$words->get('BlogCreateLabelText')
if(in_array('text', $vars['errors']))
foreach($catIt as $c) if (in_array('category', $vars['errors'])) =$words->get('BlogCreateLabelCreateTags')
if(isset($vars['id'])&&$vars['id'])
if(isset($vars['latitude'])&&isset($vars['longitude'])&&$vars['latitude']&&$vars['longitude']) else
if (in_array('trip', $vars['errors'])) =$words->get('BlogCreateTrips_LabelStartdate')
if(in_array('startdate', $vars['errors'])) elseif (in_array('duration', $vars['errors'])) =$words->getSilent('label_search_location')
if((isset($vars['vis'])&&$vars['vis']==
'pub')||(!isset($vars['vis'])&&(!$defaultVis||($defaultVis
&&$defaultVis->valueint==2))))
if((isset($vars['vis'])&&$vars['vis']==
'prt')||(!isset($vars['vis'])&&$defaultVis
&&$defaultVis->valueint==1)) if ((isset($vars['vis'])&&$vars['vis']!= 'prt'&&$vars['vis']!= 'pub')||(!isset($vars['vis'])&&$defaultVis &&$defaultVis->valueint==0)) =$submitValue
$cloudmade_conf = PVars::getObj('cloudmade')
Variable Documentation
$cloudmade_conf = PVars::getObj('cloudmade')
Definition at line 277 of file editcreateform.php.
if (!$member) $words = new MOD_words()
Definition at line 23 of file editcreateform.php.
if (in_array('startdate', $vars['errors'])||in_array('duration', $vars['errors'])) else
Initial value:
{
    echo '<input type="hidden" id="markerLatitude" name="markerLatitude" value="0"/>'
Definition at line 128 of file editcreateform.php.
if (in_array('startdate', $vars['errors'])) elseif(in_array('duration', $vars['errors'])) =$words->getSilent('label_search_location')
Definition at line 198 of file editcreateform.php.
Referenced by SimplePie_IRI\__get(), SimplePie_IRI\__set(), Snoopy\_httprequest(), Snoopy\_httpsrequest(), SimplePie_IRI\absolutize(), GroupsController\acceptInvitation(), GroupsController\acceptMember(), GroupsController\addMemberAsAdmin(), PollsModel\AddVote(), Blog\ajaxEditPost(), MagpieRSS\append(), MagpieRSS\append_content(), GroupsController\banMember(), GeoPopupPage\body(), PollsModel\CancelVote(), SimplePie_Misc\change_encoding(), MOD_dnsblock\checkIp(), MembersModel\checkMyPreferences(), AddRelationPage\column_col3(), GeoAdminPage\column_col3(), VerifiedMembersViewPage\column_col3(), GroupMemberAdministrationPage\column_col3(), Blog\countRecentPosts(), SimplePie_Parse_Date\date_rfc2822(), GroupsController\delete(), SimplePie_Sanitize\do_strip_htmltags(), MOD_user\doLogin(), Blog\editFill(), Trip\editProcess(), AdminWordModel\editTranslationFormCheck(), SimplePie_Enclosure\embed(), MOD_layoutbits\fage_value(), MagpieRSS\feed_end_element(), SimplePie_Content_Type_Sniffer\feed_or_html(), MagpieRSS\feed_start_element(), SimplePie\fetch_data(), fetch_rss(), RoxEntityBase\findAll(), RoxEntityBase\findByWhereMany(), SimplePie_Misc\fix_protocol(), SimplePie_Item\get_authors(), SimplePie\get_base(), SimplePie_Misc\get_build(), SimplePie_Item\get_content(), SimplePie_Source\get_copyright(), SimplePie_Item\get_copyright(), SimplePie\get_copyright(), SimplePie_Misc\get_curl_version(), SimplePie_Item\get_date(), SimplePie_Item\get_description(), SimplePie_Source\get_description(), SimplePie\get_description(), SimplePie_Item\get_enclosures(), SimplePie_Item\get_id(), SimplePie\get_image_height(), SimplePie\get_image_link(), SimplePie\get_image_title(), SimplePie_Source\get_image_url(), SimplePie\get_image_url(), SimplePie\get_image_width(), SimplePie_IRI\get_iri(), SimplePie_Source\get_language(), SimplePie\get_language(), SimplePie_Source\get_latitude(), SimplePie\get_latitude(), SimplePie_Item\get_latitude(), SimplePie_Source\get_links(), SimplePie_Item\get_links(), SimplePie\get_links(), SimplePie_Item\get_local_date(), SimplePie_Source\get_longitude(), SimplePie\get_longitude(), SimplePie_Item\get_longitude(), SimplePie_Item\get_permalink(), SimplePie_Enclosure\get_real_type(), SimplePie_Source\get_title(), SimplePie_Item\get_title(), SimplePie\get_title(), SimplePie_Content_Type_Sniffer\get_type(), SimplePie\get_type(), Blog\getCategoryArray(), Blog\getCategoryFromUserIt(), Blog\getEditData(), AdminModel\getEnqueueAction(), StatsModel\getLastLoginRankGrouped(), Rox\getLastLoginRankGrouped(), RoxModelBase\getMemoryCookie(), Geo\getParent(), Blog\getRecentPostIt(), Blog\getRecentPostsArray(), Note\getText(), AdminWordModel\getTranslationData(), GroupsController\groupSettings(), MembersModel\hasAvatar(), SimplePie_Content_Type_Sniffer\image(), VerifymembersController\index(), ForumsController\index(), MembersController\index_loggedIn(), SimplePie\init(), InviteController\InviteCallback(), SimplePie_Locator\is_feed(), RoxEntityBase\isPKSet(), GroupsModel\joinGroup(), GroupsController\kickMember(), RoxLauncher\launch(), SimplePie_HTTP_Parser\linear_whitespace(), SimplePie_Cache_MySQL\load(), ExceptionLogger\logException(), MessagesController\mailBoxCallback(), main(), GroupsController\memberAdministration(), Forums\ModeratorEditTagProcess(), SimplePie_HTTP_Parser\new_line(), MagpieRSS\normalize(), NotifyController\NotifyAdminCallback(), VerifiedMembersViewPage\pagename(), SimplePie_Parser\parse(), SimplePie_Cache_DB\prepare_simplepie_object_for_cache(), Forums\prepareForum(), RoxEntityBase\preparePKWhereString(), User\registerProcess(), SimplePie_IRI\remove_dot_segments(), SimplePie_IRI\remove_iunreserved_percent_encoded(), SimplePie_Parse_Date\remove_rfc2822_comments(), SimplePie_IRI\replace_invalid_with_pct_encoding(), GroupsController\resignAsAdmin(), GeoController\SelectorInclude(), InviteModel\sendOrComplain(), SimplePie_IRI\set_authority(), SimplePie_IRI\set_host(), SimplePie_IRI\set_iri(), SimplePie_IRI\set_port(), MembersModel\set_public_profile(), SimplePie_IRI\set_scheme(), RoxFrontRouter\setBaseUri(), Group\setDescription(), MembersModel\showAvatar(), NotifyMemberWidget\showItems_list(), SimplePie_Sanitize\strip_tag(), SimplePie_Content_Type_Sniffer\text_or_binary(), SimplePie_Misc\uncomment_rfc822(), SimplePie_Content_Type_Sniffer\unknown(), GeoModel\updateUsageCounter(), GalleryController\uploadedProcess(), GalleryModel\uploadProcess(), and SimplePie_Misc\xml_encoding().
if (!isset($disableTinyMCE)||($disableTinyMCE== 'No')) if (in_array('inserror', $vars['errors'])) if(in_array('upderror', $vars['errors'])) =$words->get('BlogCreateLabelTitle')
Definition at line 48 of file editcreateform.php.
if(in_array('title', $vars['errors'])) =$words->get('BlogCreateLabelText')
Definition at line 62 of file editcreateform.php.
if (in_array('text', $vars['errors'])) foreach ($catIt as $c) if(in_array('category', $vars['errors'])) =$words->get('BlogCreateLabelCreateTags')
Definition at line 95 of file editcreateform.php.
if(in_array('trip', $vars['errors'])) =$words->get('BlogCreateTrips_LabelStartdate')
Definition at line 172 of file editcreateform.php.
if ((isset($vars['vis'])&&$vars['vis']== 'pub')||(!isset($vars['vis'])&&(!$defaultVis||($defaultVis &&$defaultVis->valueint==2)))) if ((isset($vars['vis'])&&$vars['vis']== 'prt')||(!isset($vars['vis'])&&$defaultVis &&$defaultVis->valueint==1)) if((isset($vars['vis'])&&$vars['vis']!= 'prt'&&$vars['vis']!= 'pub')||(!isset($vars['vis'])&&$defaultVis &&$defaultVis->valueint==0)) =$submitValue
Definition at line 270 of file editcreateform.php.