Rox: C:/xampp/htdocs/rox/build/forums/templates/board.php File Reference
board.php File Reference
Variables
$User = APP_User::login()
$words = new MOD_words()
$navigationPath = ''
$navichain_items = $boards->getNaviChain()
if(is_array($navichain_items)) $boardName = htmlspecialchars($boards->getBoardName(), ENT_QUOTES)
if($boardName!= 'no tags') if(($this->
BW_Right->HasRight("ForumModerator","Edit"))||($this->
BW_Right->HasRight("ForumModerator","All")))
if(isset($boards->IdSubscribe)) else
$tags = $boards->getBoardDescription()
if ($boards->hasSubBoards())
$number = $boards->getTotalThreads()
Variable Documentation
if (is_array($navichain_items)) $boardName = htmlspecialchars($boards->getBoardName(), ENT_QUOTES)
Definition at line 42 of file board.php.
$navichain_items = $boards->getNaviChain()
Definition at line 34 of file board.php.
$navigationPath = ''
Definition at line 33 of file board.php.
$number = $boards->getTotalThreads()
Definition at line 82 of file board.php.
Referenced by GeoController\GeoSearch(), Places\getAllCountries(), and SimplePie_Sanitize\strip_tag().
$tags = $boards->getBoardDescription()
Definition at line 68 of file board.php.
$User = APP_User::login()
Definition at line 28 of file board.php.
Referenced by User\avatarProcess(), SignupFinishPage\column_col3(), SignupPage\column_col3(), Forums\createProcess(), Forums\delProcess(), Forums\editProcess(), OnlineModel\GetMembers(), LastCommentsController\index(), PollsController\index(), ShoutsController\index(), LinkController\index(), ForumsController\index(), UserController\index(), User\loginProcess(), User\logout(), Forums\ModeratorEditPostProcess(), Forums\ModeratorEditTagProcess(), MembersController\myPreferencesCallback(), UserView\registerMail(), Forums\replyProcess(), Forums\reportpostProcess(), UserView\rightContent(), and UserView\settingsForm().
$words = new MOD_words()
Definition at line 30 of file board.php.
if ($number==0) else if ($number==1) else
Initial value:
{
        if (isset($boards->IdTag)) echo " <span class=\"button\"><a href=\"forums/subscribe/tag/",$boards->IdTag,"\">",$words->getBuffered('ForumSubscribe'),"</a></span>",$words->flushBuffer()
Definition at line 62 of file board.php.
if($boards->hasSubBoards())
Definition at line 73 of file board.php.