Rox: C:/xampp/htdocs/rox/build/blog/templates/usersettings.php File Reference
usersettings.php File Reference
Variables
$ctrl = new BlogController
$callbackId = $ctrl->settingsProcess()
$vars =& PPostHandler::getVars($callbackId)
$settingsText = array()
$i18n = new MOD_i18n('apps/blog/usersettings.php')
Variable Documentation
$callbackId = $ctrl->settingsProcess()
Definition at line 3 of file usersettings.php.
Referenced by AdminView\activitylogs(), User\avatarProcess(), PollsPage\column_col3(), GalleryController\commentProcess(), TripView\createForm(), TripController\createProcess(), ForumsController\createProcess(), TripController\delProcess(), Trip\delProcess(), BlogView\editForm(), GalleryController\editGalleryProcess(), ForumsView\editPost(), TripController\editProcess(), Trip\editProcess(), ForumsController\editProcess(), GalleryController\editProcess(), Forums\getEditData(), BlogController\index(), ForumsController\index(), User\loginProcess(), ForumsView\ModeditPost(), ForumsController\ModeratorEditPostProcess(), ForumsController\ModeratorEditTagProcess(), ForumsController\morelessthreadsProcess(), ForumsController\mygroupsonlyProcess(), Trip\prepareEditData(), SignupView\registerForm(), ForumsController\replyProcess(), ForumsController\replySuggestionsProcess(), ForumsController\reportpostProcess(), ForumsController\showExternalSuggestionsThreadReply(), ForumsView\showModeratorEditPost(), ForumsView\showModeratorEditTag(), ForumsView\showReportList(), ForumsView\showReportPost(), GalleryController\uploadProcess(), and GalleryView\userOverviewSimple().
$ctrl = new BlogController
Definition at line 2 of file usersettings.php.
$i18n = new MOD_i18n('apps/blog/usersettings.php')
Definition at line 7 of file usersettings.php.
$settingsText = array()
Definition at line 6 of file usersettings.php.
$vars =& PPostHandler::getVars($callbackId)
Definition at line 4 of file usersettings.php.