Rox: rss_fetch.inc File Reference
build/rox/magpierss/rss_fetch.inc File Reference
Functions
fetch_rss ($url)
error ($errormsg, $lvl=E_USER_WARNING)
debug2 ($debug2msg, $lvl=E_USER_NOTICE)
magpie_error ($errormsg="")
_fetch_remote_file ($url, $headers="")
_response_to_rss ($resp)
init2 ()
is_info ($sc)
is_success ($sc)
is_redirect ($sc)
is_error ($sc)
is_client_error ($sc)
is_server_error ($sc)
Variables
if(!defined('DIR_SEP')) if (!defined('MAGPIE_DIR'))
const MAGPIE_EXTLIB MAGPIE_DIR . 'extlib' . DIR_SEP
const MAGPIE_VERSION '0.72'
$MAGPIE_ERROR = ""
Function Documentation
_fetch_remote_file ($url, $headers = "")
References $url.
Referenced by fetch_rss().
_response_to_rss ($resp)
References $rss, and error().
Referenced by fetch_rss().
debug2 ($debug2msg, $lvl = E_USER_NOTICE)
Referenced by fetch_rss().
error ($errormsg, $lvl = E_USER_WARNING)
References $MAGPIE_ERROR.
Referenced by _response_to_rss(), and fetch_rss().
fetch_rss ($url)
References $rss, $url, _fetch_remote_file(), _response_to_rss(), debug2(), elseif, error(), init2(), and is_success().
init2 ()
References MAGPIE_VERSION.
Referenced by fetch_rss().
is_client_error ($sc)
is_error ($sc)
is_info ($sc)
is_redirect ($sc)
is_server_error ($sc)
is_success ($sc)
Referenced by fetch_rss().
magpie_error ($errormsg = "")
References $MAGPIE_ERROR.
Variable Documentation
$MAGPIE_ERROR = ""
Referenced by error(), and magpie_error().
if (!defined('DIR_SEP')) if(!defined('MAGPIE_DIR'))
const MAGPIE_EXTLIB MAGPIE_DIR . 'extlib' . DIR_SEP
const MAGPIE_VERSION '0.72'
Referenced by init2().