Rox: C:/xampp/htdocs/rox/build/blog/templates/categories.php File Reference
categories.php File Reference
Namespaces
blog
Variables
$words = new MOD_words()
$Blog = new Blog
$callback = $this->getCallbackOutput('BlogController', 'categoryProcess')
$vars = $this->getRedirectedMem('vars')
$request = PRequest::get()->request
$catText = array()
$catError = array()
$i18n = new MOD_i18n('apps/blog/categories.php')
if(!isset($vars['errors'])) if(!$member=$this->
_model->getLoggedInMember()) $catIt = $Blog->getCategoryFromUserIt($member->id)
if(in_array('upderror', $vars['errors']))
if(in_array('inserror', $vars['errors']))
if(in_array('delerror', $vars['errors']))
foreach($catIt as $cat) if(isset($request[2])&&$request[2]==
'del') else {
if(in_array('nameinvalid',
$vars['errors'])) if(in_array('namedupe',
$vars['errors'])) if (in_array('nameempty', $vars['errors'])) =$words->get('Category_label_name')
Variable Documentation
$Blog = new Blog
Definition at line 13 of file categories.php.
$callback = $this->getCallbackOutput('BlogController', 'categoryProcess')
Definition at line 14 of file categories.php.
Referenced by MethodWrap\__construct(), MethodWrap_array\__construct(), SimplePie_Parse_Date\add_callback(), RequestRouter\addRoute(), ApiController\checkFormat(), TripSingleTripPage\column_col3(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), ApiView\jsonpResponse(), AdminWordController\noUpdateNeeded(), ApiController\response(), SearchController\searchSuggestLocations(), AutoloadPlug\setCallback(), and SuggestionsController\voteAjaxRanking().
$catError = array()
Definition at line 23 of file categories.php.
if (!isset($vars['errors'])) if (!$member=$this->_model->getLoggedInMember()) $catIt = $Blog->getCategoryFromUserIt($member->id)
Definition at line 41 of file categories.php.
Referenced by BlogBasePage\categoriesList(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), BlogView\createForm(), BlogView\editForm(), and BlogView\PostsByCategory().
$catText = array()
Definition at line 22 of file categories.php.
$i18n = new MOD_i18n('apps/blog/categories.php')
Definition at line 24 of file categories.php.
$request = PRequest::get()->request
Definition at line 20 of file categories.php.
$vars = $this->getRedirectedMem('vars')
Definition at line 18 of file categories.php.
$words = new MOD_words()
Definition at line 12 of file categories.php.
if (in_array('upderror', $vars['errors'])) if (in_array('inserror', $vars['errors'])) if (in_array('delerror', $vars['errors'])) foreach ($catIt as $cat) if (isset($request[2])&&$request[2]== 'del') else {
Definition at line 80 of file categories.php.
if (in_array('nameinvalid', $vars['errors'])) if (in_array('namedupe', $vars['errors'])) if(in_array('nameempty', $vars['errors'])) =$words->get('Category_label_name')
Definition at line 98 of file categories.php.