Rox: C:/xampp/htdocs/rox/build/blog/templates/blogitem.php File Reference
blogitem.php File Reference
Namespaces
blog
Variables
$words = new MOD_words()
$format
if(!isset($headingLevel)) if ($blog->fk_countrycode) =date($format['short'], $blog->unix_created)
if($blog->flags
&Blog::FLAG_VIEW_PRIVATE)
elseif($blog->flags
&Blog::FLAG_VIEW_PROTECTED) $blogModel = new Blog
$blogView = new BlogView($blogModel)
$txt = $blogView->blogText($blog->blog_text)
$tags = $blogModel->getPostTagsIt($blog->blog_id)
$commentsCount = $blogModel->countComments($blog->blog_id)
if ($txt[1])
if($commentsCount > 0) else
if(isset($blog->latitude)&&$blog->
latitude &&isset($blog->
longitude)&&$blog->longitude) $member = $this->_model->getLoggedInMember()
Variable Documentation
if ($blog->flags &Blog::FLAG_VIEW_PRIVATE) elseif ($blog->flags &Blog::FLAG_VIEW_PROTECTED) $blogModel = new Blog
Definition at line 48 of file blogitem.php.
Referenced by ApiModel\getMemberData().
$blogView = new BlogView($blogModel)
Definition at line 49 of file blogitem.php.
$commentsCount = $blogModel->countComments($blog->blog_id)
Definition at line 52 of file blogitem.php.
$format
Initial value:
= array(
    'short'=>$words->getSilent('DateFormatShort')
)
Definition at line 17 of file blogitem.php.
if (isset($blog->latitude)&&$blog->latitude &&isset($blog->longitude)&&$blog->longitude) $member = $this->_model->getLoggedInMember()
Definition at line 91 of file blogitem.php.
Referenced by SuggestionsBaseViewPage\__construct(), SuggestionsBasePage\__construct(), Board\__construct(), AdminController\accepter(), AdminController\accepterProcessMembers(), GroupsModel\acceptGroupMember(), Role\addForMember(), GroupsModel\addGroupMemberAsAdmin(), RelatedGroupsController\addRelatedGroup(), Forums\adjustThreadsCountToShow(), GalleryController\allgalleries(), GroupsModel\banGroupMember(), BlogBasePage\categoriesList(), LoginModel\checkBWPassword(), PrivilegeScope\checkScopeExists(), TripSingleTripPage\column_col3(), DeleteTranslationPage\column_col3(), AddRelationPage\column_col3(), MyVisitorsPage\column_col3(), NotifyAdminSettingsPage\column_col3(), GalleryManagePage\column_col3(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), InvitePage\column_col3(), AboutGenericPage\column_col3(), ReadMessagePage\column_col3(), GroupInvitePage\column_col3(), GroupMemberAdministrationPage\column_col3(), Blog\commentProcess(), AdminController\commentsOverview(), Blog\countRecentPosts(), BlogView\createForm(), GalleryModel\createGallery(), MemberRole\createMemberRoleLink(), LoginModel\createMissingTBUser(), Feedback\createNew(), TripController\createProcess(), BlogController\createProcess(), PrivilegeScope\createScope(), AdminController\debugLogs(), Group\deleteGroup(), BlogController\deleteProcess(), RelatedGroupsController\deleteRelatedGroup(), MembersModel\deleteRelation(), TripView\displaySingleTrip(), BlogView\editForm(), EditProfilePage\editMyProfileFormPrepare(), BlogController\editProcess(), SuggestionsController\excludeCallback(), PrivilegeScope\findById(), MemberRole\findById(), GroupsModel\findMembersByName(), MembersModel\get_profile_language(), MembersModel\get_relation_between_members(), Blog\getCategoryArray(), RelatedGroupsModel\getGroupsForMember(), GroupsModel\getGroupsForMember(), ApiModel\getMember(), GroupMembership\getMemberGroups(), MemberRole\getMemberRoles(), Member\getNote(), ProfileNote\getNotes(), RetiredProfilePage\getPageTitle(), MemberPage\getPageTitle(), Forums\GetPostVote(), Blog\getRecentPostIt(), Blog\getRecentPostsArray(), Role\getScopesForMemberRole(), Blog\getStickyPostIt(), GalleryUserPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), Blog\getTaggedPostsIt(), Blog\getTagsIt(), LoginModel\getTBUserForBWMember(), Note\getText(), Blog\getTinyMCEPreference(), Forums\getTinyMCEPreference(), Trip\getTripData(), Trip\getTrips(), GalleryBasePage\getUserLinksItems(), PrivilegeScope\hasAnyRoleScope(), RightsModel\hasRightsAccess(), MembersController\index(), BlogController\index(), MessagesController\index(), TripController\index(), GalleryController\index(), ForumsController\index(), AdminController\index(), MembersController\index_loggedIn(), MembersController\index_loggedOut(), RoxFrontRouter\initUser(), GroupsModel\inviteMember(), Group\isGroupOwner(), AboutModel\isVolunteer(), GroupsController\join(), GroupsController\joined(), GroupsModel\joinGroup(), GroupsController\leave(), GroupsModel\leaveGroup(), GroupsController\left(), GalleryUserGalleriesPage\leftSidebar(), InactiveProfilePage\leftsidebar(), BlogCategoriesPage\leftSideBar(), BlogPage\leftSideBar(), GalleryUserPage\leftSidebar(), MemberPage\leftsidebar(), Suggestion\loadEntity(), SuggestionOption\loadEntity(), LoginModel\logout(), AdminController\massmail(), AdminController\massmailCreate(), AdminController\massmailDetails(), AdminController\massmailDetailsMailing(), AdminController\massmailEdit(), AdminController\massmailEnqueue(), AdminController\massmailTrigger(), AdminController\massmailUnqueue(), AdminController\massmailUntrigger(), GroupsModel\memberAcceptedInvitation(), ApiController\memberAction(), RelatedGroupsModel\memberAddsRelatedGroup(), GroupsController\memberAdministration(), GroupsModel\memberDeclinedInvitation(), RelatedGroupsModel\memberDeletesRelatedGroup(), MemberRole\memberHasRole(), GroupsController\memberSearchAjax(), AdminWordController\noRights(), AdminController\noRights(), GroupsModel\notifyGroupAdmins(), Forums\prepare_notification(), Trip\prepareEditData(), AdminModel\processMembers(), SignupView\registerMail(), Role\removeFromMember(), Group\removeGroupOwner(), MembersModel\reportBadComment(), GroupsModel\resignGroupAdmin(), MOD_trips\RetrieveVisitorsInCityWithAPicture(), Forums\searchUserposts(), FeedbackModel\sendFeedback(), GroupsModel\sendInvitation(), InviteModel\sendOrComplain(), MessagesModel\sendOrComplain(), LoginModel\setPreferredLanguage(), ActivitiesController\show(), MembersModel\showAvatar(), ForumsController\showExternalLatest(), NotifyMemberWidget\showListItem(), RelatedGroupsController\showRelatedGroupLog(), AdminController\spamOverview(), Forums\switchShowMyGroupsTopicsOnly(), AdminController\tempVolStart(), AdminController\treasurerEditCreateDonation(), AdminController\treasurerOverview(), AdminController\treasurerStartDonationCampaign(), AdminController\treasurerStopDonationCampaign(), GroupsModel\updateMembershipSettings(), GalleryModel\uploadProcess(), GalleryController\user(), GalleryController\usergalleries(), GalleryController\userimages(), GalleryBasePage\userLinks(), BlogView\userPosts(), SuggestionsController\voteSuggestionCallback(), AdminController\wordsOverview(), and MembersModel\writeNoteForMember().
$tags = $blogModel->getPostTagsIt($blog->blog_id)
Definition at line 51 of file blogitem.php.
Referenced by Board\__construct(), ForumsView\createTopic(), Blog\editFill(), BlogView\generateClickableTagSuggestions(), ForumsView\generateClickableTagSuggestions(), Board\getBoardName(), SimplePie_Sanitize\strip_htmltags(), SimplePie\strip_htmltags(), and Blog\updateTags().
$txt = $blogView->blogText($blog->blog_text)
Definition at line 50 of file blogitem.php.
$words = new MOD_words()
Definition at line 16 of file blogitem.php.
if ($commentsCount > 0) else
Initial value:
{
  echo '<img src="images/icons/comment_add.png" alt="'.$words->getSilent('CommentsAdd').'"/> '.$words->getSilent('CommentsAdd')
Definition at line 83 of file blogitem.php.
if($tags->numRows() > 0) =date($format['short'], $blog->unix_created)
Definition at line 37 of file blogitem.php.
if($txt[1])
Definition at line 66 of file blogitem.php.