Rox: check_ports.php File Reference
check_ports.php File Reference
Variables
if(count($_SERVER['argv'])
< 2||!in_array(strtolower($_SERVER['argv'][1]),
array('mule', 'deer'))) $table = strtoupper($_SERVER['argv'][1])
$wiki_page = file_get_contents('http://www.bevolunteer.org/wiki/Listening_servers')
$info = substr($wiki_page,strpos($wiki_page, "START {$table} SERVER TABLE"), (strpos($wiki_page, "END {$table} SERVER TABLE") - strpos($wiki_page, "START {$table} SERVER TABLE")))
$wiki_array = explode("\n", $info)
foreach($wiki_array as $key=>
$value) if(!exec('/bin/netstat-e--ip-vlp--numeric-hosts--numeric-ports',
$output)) $ports = array()
foreach($output as $line) $scream = false
Variable Documentation
$info = substr($wiki_page,strpos($wiki_page, "START {$table} SERVER TABLE"), (strpos($wiki_page, "END {$table} SERVER TABLE") - strpos($wiki_page, "START {$table} SERVER TABLE")))
Referenced by SimplePie_File\__construct(), SimplePie_Misc\debug(), RoxEntityBase\getPrimaryKey(), RoxEntityBase\getTableDescription(), RoxEntityBase\insert(), RoxEntityFactory\storeTableDescription(), RoxEntityBase\validateField(), and RoxEntityBase\validateSelf().
foreach ($wiki_array as $key=> $value) if (!exec('/bin/netstat-e--ip-vlp--numeric-hosts--numeric-ports', $output)) $ports = array()
foreach ($output as $line) $scream = false
if (count($_SERVER['argv'])< 2||!in_array(strtolower($_SERVER['argv'][1]), array('mule', 'deer'))) $table = strtoupper($_SERVER['argv'][1])
Referenced by DatabaseSummaryPage\column_col3(), RoxEntityBase\countWhere(), Member\get_language_levels(), DatabaseSummaryModel\getDatabaseTablesWithFieldsSorted(), DatabaseSummaryWidget\getTableColumns(), DatabaseSummaryWidget\tableCell(), DatabaseSummaryWidget\tableCell_name(), and DatabaseSummaryPage\tableFilter().
$wiki_array = explode("\n", $info)
$wiki_page = file_get_contents('http://www.bevolunteer.org/wiki/Listening_servers')