Rox: MagpieRSS Class Reference
MagpieRSS Class Reference
Public Member Functions
MagpieRSS ($source, $output_encoding='ISO-8859-1', $input_encoding=null, $detect_encoding=true)
feed_start_element ($p, $element, &$attrs)
feed_cdata ($p, $text)
feed_end_element ($p, $el)
concat (&$str1, $str2="")
append_content ($text)
append ($el, $text)
normalize ()
is_rss ()
is_atom ()
create_parser ($source, $out_enc, $in_enc, $detect)
php5_create_parser ($in_enc, $detect)
php4_create_parser ($source, $in_enc, $detect)
known_encoding ($enc)
error ($errormsg, $lvl=E_USER_WARNING)
MagpieRSS ($source, $output_encoding='ISO-8859-1', $input_encoding=null, $detect_encoding=true)
feed_start_element ($p, $element, &$attrs)
feed_cdata ($p, $text)
feed_end_element ($p, $el)
concat (&$str1, $str2="")
append_content ($text)
append ($el, $text)
normalize ()
is_rss ()
is_atom ()
create_parser ($source, $out_enc, $in_enc, $detect)
php5_create_parser ($in_enc, $detect)
php4_create_parser ($source, $in_enc, $detect)
known_encoding ($enc)
error ($errormsg, $lvl=E_USER_WARNING)
MagpieRSS ($source, $output_encoding='ISO-8859-1', $input_encoding=null, $detect_encoding=true)
feed_start_element ($p, $element, &$attrs)
feed_cdata ($p, $text)
feed_end_element ($p, $el)
concat (&$str1, $str2="")
append_content ($text)
append ($el, $text)
normalize ()
is_rss ()
is_atom ()
create_parser ($source, $out_enc, $in_enc, $detect)
php5_create_parser ($in_enc, $detect)
php4_create_parser ($source, $in_enc, $detect)
known_encoding ($enc)
error ($errormsg, $lvl=E_USER_WARNING)
Data Fields
$parser
$current_item = array()
$items = array()
$channel = array()
$textinput = array()
$image = array()
$feed_type
$feed_version
$encoding = ''
$_source_encoding = ''
$ERROR = ""
$WARNING = ""
$_CONTENT_CONSTRUCTS = array('content', 'summary', 'info', 'title', 'tagline', 'copyright')
$_KNOWN_ENCODINGS = array('UTF-8', 'US-ASCII', 'ISO-8859-1')
$stack = array()
$inchannel = false
$init2em = false
$incontent = false
$intextinput = false
$inimage = false
$current_namespace = false
Detailed Description
Hybrid parser, and object, takes RSS as a string and returns a simple object.
see: rss_fetch.inc for a simpler interface with integrated caching support
Member Function Documentation
MagpieRSS::append ($el, $text)
References $text, channel, concat(), elseif, and image.
Referenced by feed_cdata(), and feed_start_element().
MagpieRSS::append ($el, $text)
References $text, channel, concat(), elseif, and image.
MagpieRSS::append ($el, $text)
References $text, channel, concat(), elseif, and image.
MagpieRSS::append_content ($text)
References $text, channel, concat(), and elseif.
MagpieRSS::append_content ($text)
References $text, channel, concat(), and elseif.
MagpieRSS::append_content ($text)
References $text, channel, concat(), and elseif.
Referenced by feed_cdata(), feed_end_element(), and feed_start_element().
MagpieRSS::concat (& $str1, $str2 = "")
MagpieRSS::concat (& $str1, $str2 = "")
MagpieRSS::concat (& $str1, $str2 = "")
Referenced by append(), and append_content().
MagpieRSS::create_parser ($source, $out_enc, $in_enc, $detect)
return XML parser, and possibly re-encoded source
References $parser, php4_create_parser(), and php5_create_parser().
Referenced by MagpieRSS().
MagpieRSS::create_parser ($source, $out_enc, $in_enc, $detect)
return XML parser, and possibly re-encoded source
References $parser, php4_create_parser(), and php5_create_parser().
MagpieRSS::create_parser ($source, $out_enc, $in_enc, $detect)
return XML parser, and possibly re-encoded source
References $parser, php4_create_parser(), and php5_create_parser().
MagpieRSS::error ($errormsg, $lvl = E_USER_WARNING)
MagpieRSS::error ($errormsg, $lvl = E_USER_WARNING)
Referenced by MagpieRSS(), and php4_create_parser().
MagpieRSS::error ($errormsg, $lvl = E_USER_WARNING)
MagpieRSS::feed_cdata ($p, $text)
References $text, append(), append_content(), and ATOM.
MagpieRSS::feed_cdata ($p, $text)
References $text, append(), append_content(), and ATOM.
MagpieRSS::feed_cdata ($p, $text)
References $text, append(), append_content(), and ATOM.
MagpieRSS::feed_end_element ($p, $el)
References $current_item, append_content(), ATOM, elseif, items, and RSS.
MagpieRSS::feed_end_element ($p, $el)
References $current_item, append_content(), ATOM, elseif, items, and RSS.
MagpieRSS::feed_end_element ($p, $el)
References $current_item, append_content(), ATOM, elseif, items, and RSS.
MagpieRSS::feed_start_element ($p, $element, & $attrs)
References append(), append_content(), ATOM, elseif, and RSS.
MagpieRSS::feed_start_element ($p, $element, & $attrs)
References append(), append_content(), ATOM, elseif, and RSS.
MagpieRSS::feed_start_element ($p, $element, & $attrs)
References append(), append_content(), ATOM, elseif, and RSS.
MagpieRSS::is_atom ()
References $feed_version, and ATOM.
MagpieRSS::is_atom ()
References $feed_version, and ATOM.
MagpieRSS::is_atom ()
References $feed_version, and ATOM.
Referenced by normalize().
MagpieRSS::is_rss ()
References $feed_version, and RSS.
MagpieRSS::is_rss ()
References $feed_version, and RSS.
MagpieRSS::is_rss ()
References $feed_version, and RSS.
Referenced by normalize().
MagpieRSS::known_encoding ($enc)
MagpieRSS::known_encoding ($enc)
MagpieRSS::known_encoding ($enc)
Referenced by php4_create_parser().
MagpieRSS::MagpieRSS ($source, $output_encoding = 'ISO-8859-1', $input_encoding = null, $detect_encoding = true)
Set up XML parser, parse source, and return populated RSS object..
Parameters
string $source string containing the RSS to be parsed
NOTE: Probably a good idea to leave the encoding options alone unless you know what you're doing as PHP's character set support is a little weird.
NOTE: A lot of this is unnecessary but harmless with PHP5
Parameters
string $output_encoding output the parsed RSS in this character set defaults to ISO-8859-1 as this is PHP's default.
NOTE: might be changed to UTF-8 in future versions.
Parameters
string $input_encoding the character set of the incoming RSS source. Leave blank and Magpie will try to figure it out.
bool $detect_encoding if false Magpie won't attempt to detect source encoding. (caveat emptor)
References $parser, $status, create_parser(), error(), and normalize().
MagpieRSS::MagpieRSS ($source, $output_encoding = 'ISO-8859-1', $input_encoding = null, $detect_encoding = true)
Set up XML parser, parse source, and return populated RSS object..
Parameters
string $source string containing the RSS to be parsed
NOTE: Probably a good idea to leave the encoding options alone unless you know what you're doing as PHP's character set support is a little weird.
NOTE: A lot of this is unnecessary but harmless with PHP5
Parameters
string $output_encoding output the parsed RSS in this character set defaults to ISO-8859-1 as this is PHP's default.
NOTE: might be changed to UTF-8 in future versions.
Parameters
string $input_encoding the character set of the incoming RSS source. Leave blank and Magpie will try to figure it out.
bool $detect_encoding if false Magpie won't attempt to detect source encoding. (caveat emptor)
References $parser, $status, create_parser(), error(), and normalize().
MagpieRSS::MagpieRSS ($source, $output_encoding = 'ISO-8859-1', $input_encoding = null, $detect_encoding = true)
Set up XML parser, parse source, and return populated RSS object..
Parameters
string $source string containing the RSS to be parsed
NOTE: Probably a good idea to leave the encoding options alone unless you know what you're doing as PHP's character set support is a little weird.
NOTE: A lot of this is unnecessary but harmless with PHP5
Parameters
string $output_encoding output the parsed RSS in this character set defaults to ISO-8859-1 as this is PHP's default.
NOTE: might be changed to UTF-8 in future versions.
Parameters
string $input_encoding the character set of the incoming RSS source. Leave blank and Magpie will try to figure it out.
bool $detect_encoding if false Magpie won't attempt to detect source encoding. (caveat emptor)
References $parser, $status, create_parser(), error(), and normalize().
MagpieRSS::normalize ()
References $i, channel, elseif, is_atom(), is_rss(), items, and parse_w3cdtf().
Referenced by MagpieRSS().
MagpieRSS::normalize ()
References $i, channel, elseif, is_atom(), is_rss(), items, and parse_w3cdtf().
MagpieRSS::normalize ()
References $i, channel, elseif, is_atom(), is_rss(), items, and parse_w3cdtf().
MagpieRSS::php4_create_parser ($source, $in_enc, $detect)
Instaniate an XML parser under PHP4
Unfortunately PHP4's support for character encodings and especially XML and character encodings sucks. As long as the documents you parse only contain characters from the ISO-8859-1 character set (a superset of ASCII, and a subset of UTF-8) you're fine. However once you step out of that comfy little world things get mad, bad, and dangerous to know.
The following code is based on SJM's work with FoF
See Also
http://minutillo.com/steve/weblog/2004/6/17/php-xml-and-character-encodings-a-tale-of-sadness-rage-and-data-loss
References $m, error(), and known_encoding().
Referenced by create_parser().
MagpieRSS::php4_create_parser ($source, $in_enc, $detect)
Instaniate an XML parser under PHP4
Unfortunately PHP4's support for character encodings and especially XML and character encodings sucks. As long as the documents you parse only contain characters from the ISO-8859-1 character set (a superset of ASCII, and a subset of UTF-8) you're fine. However once you step out of that comfy little world things get mad, bad, and dangerous to know.
The following code is based on SJM's work with FoF
See Also
http://minutillo.com/steve/weblog/2004/6/17/php-xml-and-character-encodings-a-tale-of-sadness-rage-and-data-loss
References $m, error(), and known_encoding().
MagpieRSS::php4_create_parser ($source, $in_enc, $detect)
Instaniate an XML parser under PHP4
Unfortunately PHP4's support for character encodings and especially XML and character encodings sucks. As long as the documents you parse only contain characters from the ISO-8859-1 character set (a superset of ASCII, and a subset of UTF-8) you're fine. However once you step out of that comfy little world things get mad, bad, and dangerous to know.
The following code is based on SJM's work with FoF
See Also
http://minutillo.com/steve/weblog/2004/6/17/php-xml-and-character-encodings-a-tale-of-sadness-rage-and-data-loss
References $m, error(), and known_encoding().
MagpieRSS::php5_create_parser ($in_enc, $detect)
Instantiate an XML parser under PHP5
PHP5 will do a fine job of detecting input encoding if passed an empty string as the encoding.
All hail libxml2!
MagpieRSS::php5_create_parser ($in_enc, $detect)
Instantiate an XML parser under PHP5
PHP5 will do a fine job of detecting input encoding if passed an empty string as the encoding.
All hail libxml2!
MagpieRSS::php5_create_parser ($in_enc, $detect)
Instantiate an XML parser under PHP5
PHP5 will do a fine job of detecting input encoding if passed an empty string as the encoding.
All hail libxml2!
Referenced by create_parser().
Field Documentation
MagpieRSS::$_CONTENT_CONSTRUCTS = array('content', 'summary', 'info', 'title', 'tagline', 'copyright')
MagpieRSS::$_KNOWN_ENCODINGS = array('UTF-8', 'US-ASCII', 'ISO-8859-1')
MagpieRSS::$_source_encoding = ''
MagpieRSS::$channel = array()
MagpieRSS::$current_item = array()
Referenced by feed_end_element().
MagpieRSS::$current_namespace = false
MagpieRSS::$encoding = ''
MagpieRSS::$ERROR = ""
MagpieRSS::$feed_type
MagpieRSS::$feed_version
Referenced by is_atom(), and is_rss().
MagpieRSS::$image = array()
MagpieRSS::$inchannel = false
MagpieRSS::$incontent = false
MagpieRSS::$inimage = false
MagpieRSS::$init2em = false
MagpieRSS::$intextinput = false
MagpieRSS::$items = array()
MagpieRSS::$parser
Referenced by create_parser(), and MagpieRSS().
MagpieRSS::$stack = array()
MagpieRSS::$textinput = array()
MagpieRSS::$WARNING = ""
The documentation for this class was generated from the following file:
build/about/magpierss/rss_parse.inc