Rox: SearchModel Class Reference
SearchModel Class Reference
Public Member Functions
checkSearchVarsOk ($vars)
getResultsForLocation (&$vars)
suggestLocationsFromDatabase ($location)
suggestLocations ($location, $type)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Static Public Member Functions
static getOrderByArray ()
Data Fields
const EARTH_RADIUS = 6378
const ORDER_USERNAME = 2
const ORDER_AGE = 4
const ORDER_ACCOM = 6
const ORDER_LOGIN = 8
const ORDER_MEMBERSHIP = 10
const ORDER_COMMENTS = 12
const ORDER_DISTANCE = 14
const SUGGEST_MAX_ITEMS = 30
const PLACES_FILTER = " g.fclass = 'P' AND g.fcode <> 'PPLH' AND g.fcode <> 'PPLW' AND g.fcode <> 'PPLQ' AND g.fcode <> 'PPLCH' "
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 29 of file search.model.php.
Member Function Documentation
SearchModel::checkSearchVarsOk ($vars)
Definition at line 784 of file search.model.php.
References $errors, and $vars.
static SearchModel::getOrderByArray () static
Definition at line 54 of file search.model.php.
SearchModel::getResultsForLocation (& $vars)
Returns either a list of members for a selected location or a list of possible locations based on the input text
Definition at line 796 of file search.model.php.
References $query, $res, $results, $value, $vars, RoxModelBase\singleLookup(), and suggestLocationsFromDatabase().
SearchModel::suggestLocations ($location, $type)
Definition at line 1044 of file search.model.php.
References $locations.
SearchModel::suggestLocationsFromDatabase ($location)
Definition at line 956 of file search.model.php.
References $_SESSION, $count, $lang, $locations, $query, and RoxModelBase\singleLookup().
Referenced by getResultsForLocation().
Field Documentation
const SearchModel::EARTH_RADIUS = 6378
Definition at line 31 of file search.model.php.
const SearchModel::ORDER_ACCOM = 6
Definition at line 36 of file search.model.php.
const SearchModel::ORDER_AGE = 4
Definition at line 35 of file search.model.php.
const SearchModel::ORDER_COMMENTS = 12
Definition at line 39 of file search.model.php.
const SearchModel::ORDER_DISTANCE = 14
Definition at line 40 of file search.model.php.
const SearchModel::ORDER_LOGIN = 8
Definition at line 37 of file search.model.php.
const SearchModel::ORDER_MEMBERSHIP = 10
Definition at line 38 of file search.model.php.
const SearchModel::ORDER_USERNAME = 2
Definition at line 34 of file search.model.php.
const SearchModel::PLACES_FILTER = " g.fclass = 'P' AND g.fcode <> 'PPLH' AND g.fcode <> 'PPLW' AND g.fcode <> 'PPLQ' AND g.fcode <> 'PPLCH' "
Definition at line 44 of file search.model.php.
const SearchModel::SUGGEST_MAX_ITEMS = 30
Definition at line 42 of file search.model.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/search/search.model.php