Rox: FeedbackModel Class Reference
FeedbackModel Class Reference
Public Member Functions
getFeedbackCategories ()
getFeedbackCategory ($category_id)
sendFeedback ($vars)
feedbackMail ($receiver, $message_subject, $message_text, $sender)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const SOFTWARE_ISSUE = 1
const SAFETY_AND_ABUSE = 2
const ACCOUNT = 3
const COMMENT_ISSUE = 4
const MEDIA = 5
const FORUM_MODERTION = 6
const SUGGESTIONS = 7
const VOLUNTEERING = 8
const OTHER = 9
const DELETE_PROFILE = 10
const GENERAL_FEEDBACK = 11
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 13 of file feedback.model.php.
Member Function Documentation
FeedbackModel::feedbackMail ($receiver, $message_subject, $message_text, $sender)
Sends a Feedback e-mail
Parameters
string $IdMember
Definition at line 140 of file feedback.model.php.
References RoxComponentBase\logWrite().
Referenced by sendFeedback().
FeedbackModel::getFeedbackCategories ()
Definition at line 28 of file feedback.model.php.
References $categories, and RoxModelBase\bulkLookup().
FeedbackModel::getFeedbackCategory ($category_id)
Definition at line 42 of file feedback.model.php.
References RoxModelBase\singleLookup().
Referenced by sendFeedback().
FeedbackModel::sendFeedback ($vars)
Definition at line 53 of file feedback.model.php.
References $data, $member, $text, $username, $value, $vars, RoxModelBase\createEntity(), feedbackMail(), getFeedbackCategory(), RoxModelBase\getLoggedInMember(), and RoxComponentBase\getVersionInfo().
Referenced by MembersModel\sendRetiringFeedback().
Field Documentation
const FeedbackModel::ACCOUNT = 3
Definition at line 18 of file feedback.model.php.
Referenced by Feedback\getSignupFeedback().
const FeedbackModel::COMMENT_ISSUE = 4
Definition at line 19 of file feedback.model.php.
const FeedbackModel::DELETE_PROFILE = 10
Definition at line 25 of file feedback.model.php.
Referenced by MembersModel\sendRetiringFeedback().
const FeedbackModel::FORUM_MODERTION = 6
Definition at line 21 of file feedback.model.php.
const FeedbackModel::GENERAL_FEEDBACK = 11
Definition at line 26 of file feedback.model.php.
const FeedbackModel::MEDIA = 5
Definition at line 20 of file feedback.model.php.
const FeedbackModel::OTHER = 9
Definition at line 24 of file feedback.model.php.
const FeedbackModel::SAFETY_AND_ABUSE = 2
Definition at line 17 of file feedback.model.php.
const FeedbackModel::SOFTWARE_ISSUE = 1
Definition at line 16 of file feedback.model.php.
const FeedbackModel::SUGGESTIONS = 7
Definition at line 22 of file feedback.model.php.
const FeedbackModel::VOLUNTEERING = 8
Definition at line 23 of file feedback.model.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/about/feedback.model.php