Rox: RelatedGroupsModel Class Reference
RelatedGroupsModel Class Reference
Public Member Functions
__construct ()
findGroup ($groupId)
getMyGroups (Group $group)
getGroupsForMember ($memberId)
memberAddsRelatedGroup ($groupId, $relatedgroupId, $memberId)
memberDeletesRelatedGroup ($groupId, $relatedgroupId, $memberId)
showRelatedGroupsLog ($groupId, $offset=0, $limit=25)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 34 of file relatedgroups.model.php.
Constructor & Destructor Documentation
RelatedGroupsModel::__construct ()
Definition at line 38 of file relatedgroups.model.php.
Member Function Documentation
RelatedGroupsModel::findGroup ($groupId)
Find and return one group, using id
Parameters
int $groupId
Returns
mixed false or a Group entity
Definition at line 50 of file relatedgroups.model.php.
References RoxModelBase\createEntity().
RelatedGroupsModel::getGroupsForMember ($memberId)
Find all groups $memberId is member of
public
Returns
mixed Returns an array of Group entity objects or false if you're not logged in
Definition at line 95 of file relatedgroups.model.php.
References $member, and RoxModelBase\createEntity().
Referenced by getMyGroups().
RelatedGroupsModel::getMyGroups (Group $group)
Find all groups I am member of and which are not related groups of a given group
Parameters
object $group - a group entity public
Returns
array() Returns an array
Definition at line 68 of file relatedgroups.model.php.
References $_SESSION, $relatedgroups, Group\findRelatedGroups(), getGroupsForMember(), and RoxEntityBase\getPKValue().
RelatedGroupsModel::memberAddsRelatedGroup ($groupId, $relatedgroupId, $memberId)
Definition at line 109 of file relatedgroups.model.php.
References $member, and RoxModelBase\createEntity().
RelatedGroupsModel::memberDeletesRelatedGroup ($groupId, $relatedgroupId, $memberId)
Definition at line 121 of file relatedgroups.model.php.
References $member, and RoxModelBase\createEntity().
RelatedGroupsModel::showRelatedGroupsLog ($groupId, $offset = 0, $limit = 25)
Definition at line 138 of file relatedgroups.model.php.
References RoxModelBase\createEntity().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/relatedgroups/relatedgroups.model.php