Rox: MessagesController Class Reference
MessagesController Class Reference
Public Member Functions
index ($args=false)
sendMessageCallback ($args, $action, $mem_redirect, $mem_resend)
mailBoxCallback ($args, $action, $mem_redirect, $mem_resend)
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
getPageNumber ($request, $req_index)
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 11 of file messages.ctrl.php.
Member Function Documentation
MessagesController::getPageNumber ($request, $req_index) protected
Definition at line 156 of file messages.ctrl.php.
References $request.
Referenced by index().
MessagesController::index ($args = false)
decide which page to show. This method is called from RoxFrontRouter decide which page to show This method is called from RoxFrontRouter
Parameters
unknown_type $args request, post and get
unknown_type $memory_image message from redirect
Returns
unknown
Definition at line 26 of file messages.ctrl.php.
References $_SESSION, $member, $model, $request, and getPageNumber().
MessagesController::mailBoxCallback ($args, $action, $mem_redirect, $mem_resend)
callback for deleting/updating messages
Parameters
object $args
object $action
object $mem_redirect
object $mem_resend public
Returns
string
Definition at line 249 of file messages.ctrl.php.
References $action, $count, $layoutkit, $m, $mem_redirect, $model, $words, elseif, and APP_User\loggedIn().
MessagesController::sendMessageCallback ($args, $action, $mem_redirect, $mem_resend)
Enter description here...
Parameters
Object $args
Object $action
Object $mem_redirect memory for the page after redirect
Object $mem_resend memory for resending the form
Returns
string relative request for redirect
Definition at line 185 of file messages.ctrl.php.
References $action, $count, $mem_redirect, $model, $vars, and APP_User\loggedIn().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/messages/messages.ctrl.php