Rox: GeoModel Class Reference
GeoModel Class Reference
Public Member Functions
__construct ()
getDataById ($geonameId, $lang=false)
loadLocation ($name)
getLocationById ($id)
suggestLocation ($search, $max=false, $fcode= '')
getGeonamesHierarchy ($search, $style, $lang= 'en')
addGeonameId ($geonameId, $usagetype)
addHierarchy ($geonameId, $parentId)
updateUsageCounter ($geonameId, $usagetypeId, $type)
getUsagetypeId ($usagetype)
updateGeonameId ($geonameId)
updateGeoCounters ()
RenewGeo ()
getAllGeonameIds ()
checkGeonameId ($geonameId, $usagetype=false)
getContinents ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 30 of file geo.model.php.
Constructor & Destructor Documentation
GeoModel::__construct ()
Definition at line 33 of file geo.model.php.
Member Function Documentation
GeoModel::addGeonameId ($geonameId, $usagetype)
Add information for a specific geonameId to our database.
add itself and all its parents to geonames_cache
add all translations to geonames_altnames
add hierarchy information to geonames_hierarchy
Definition at line 204 of file geo.model.php.
References $data, $ii, $value, addHierarchy(), getAllGeonameIds(), getGeonamesHierarchy(), getUsagetypeId(), and updateUsageCounter().
Referenced by checkGeonameId(), and RenewGeo().
GeoModel::addHierarchy ($geonameId, $parentId)
Definition at line 309 of file geo.model.php.
References RoxModelBase\singleLookup().
Referenced by addGeonameId(), and updateGeonameId().
GeoModel::checkGeonameId ($geonameId, $usagetype = false)
Check if a geonameid exists, if not, add it to the DB.
Definition at line 735 of file geo.model.php.
References addGeonameId(), and getDataById().
GeoModel::getAllGeonameIds ()
Definition at line 714 of file geo.model.php.
References RoxModelBase\bulkLookup().
Referenced by addGeonameId(), and updateGeonameId().
GeoModel::getContinents ()
Check if a geonameid exists, if not, add it to the DB.
Definition at line 751 of file geo.model.php.
References RoxModelBase\createEntity().
GeoModel::getDataById ($geonameId, $lang = false)
getDataById will return the name (if available in the requested language i, else in english), the parent region (adm1) and country
Definition at line 43 of file geo.model.php.
References $lang, and RoxModelBase\singleLookup().
Referenced by checkGeonameId().
GeoModel::getGeonamesHierarchy ($search, $style, $lang = 'en')
Get list of Poppulated places matching $search
Definition at line 162 of file geo.model.php.
References $count, $google_conf, $lang, $results, $search, $style, and MOD_log\get().
Referenced by addGeonameId(), and updateGeonameId().
GeoModel::getLocationById ($id)
Get a location by its Geonames ID
Parameters
int $id Geonames ID of location
Returns
object|bool Geo entity, false if not found or lookup failed
Definition at line 100 of file geo.model.php.
References $id, and RoxModelBase\createEntity().
GeoModel::getUsagetypeId ($usagetype)
Definition at line 378 of file geo.model.php.
References RoxModelBase\singleLookup().
Referenced by addGeonameId(), and updateGeoCounters().
GeoModel::loadLocation ($name)
searches for geo entities, based on either id or name
Parameters
int | string $name - strange mixed param ... there are methods for loading locations by id, use them! public
Returns
array
Definition at line 76 of file geo.model.php.
References $name, and RoxModelBase\createEntity().
GeoModel::RenewGeo ()
stuff to merge existing Geodata from addreesses to the geonames
Definition at line 641 of file geo.model.php.
References $counter, $error, and addGeonameId().
GeoModel::suggestLocation ($search, $max = false, $fcode = '')
Search for locations in the geonames database using the SPAF-Webservice
Parameters
search The location to search for
Returns
The matching locations
Definition at line 111 of file geo.model.php.
References $_SESSION, $count, $google_conf, $max, $res, $results, $search, and MOD_log\get().
GeoModel::updateGeoCounters ()
update the counters in geo_usage how often is a geoid referenced by a specific usagetype
Definition at line 531 of file geo.model.php.
References $value, RoxModelBase\bulkLookup(), and getUsagetypeId().
GeoModel::updateGeonameId ($geonameId)
Updateinformation for a specific geonameId to our database.
add itself and all its parents to geonames_cache
add all translations to geonames_altnames
add hierarchy information to geonames_hierarchy
Definition at line 397 of file geo.model.php.
References $data, $value, addHierarchy(), getAllGeonameIds(), getGeonamesHierarchy(), and RoxModelBase\singleLookup().
GeoModel::updateUsageCounter ($geonameId, $usagetypeId, $type)
Definition at line 335 of file geo.model.php.
References $type, elseif, and RoxModelBase\singleLookup().
Referenced by addGeonameId().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/geo/geo.model.php