Rox: GroupsController Class Reference
GroupsController Class Reference
Public Member Functions
__construct ()
__destruct ()
showGroup ()
index ()
thumbImg ()
realImg ()
search ()
create ()
myGroups ()
featured ()
inviteMembers ()
inviteMember ()
memberSearchAjax ()
inviteMemberAjax ()
acceptInvitation ()
declineInvitation ()
banMember ()
kickMember ()
addMemberAsAdmin ()
resignAsAdmin ()
acceptMember ()
memberAdministration ()
join ()
joined ($args, $action, $mem_redirect, $mem_resend)
leave ()
left ()
memberSettings ()
groupSettings ()
delete ()
forum ()
groupForumsOverview ()
members ()
wiki ()
createGroupCallback ($args, $action, $mem_redirect, $mem_resend)
changeMemberSettings ($args, $action, $mem_redirect, $mem_resend)
changeGroupSettings ($args, $action, $mem_redirect, $mem_resend)
setFlashNotice ($message)
setFlashError ($message)
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Constructor & Destructor Documentation
GroupsController::__construct ()
GroupsController::__destruct ()
Member Function Documentation
RoxComponentBase::__call ($key, $args) inherited
RoxComponentBase::__get ($key) inherited
Referenced by Member\get_messengers().
RoxComponentBase::__set ($key, $value) inherited
References $value.
RoxComponentBase::__toString () inherited
GroupsController::acceptInvitation ()
called when a member accepts an invitation to join a group
public
Returns
object
References elseif, RoxComponentBase\getWords(), RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), RoxControllerBase\redirectToLogin(), and RoxControllerBase\setFlashNotice().
GroupsController::acceptMember ()
accepts a member to group
public
Returns
object $page
References elseif, RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), and RoxControllerBase\redirectToLogin().
GroupsController::addMemberAsAdmin ()
adds a member of a group as admin
public
Returns
object $page
References elseif, RoxComponentBase\getWords(), RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), RoxControllerBase\redirectToLogin(), RoxControllerBase\setFlashError(), and RoxControllerBase\setFlashNotice().
GroupsController::banMember ()
bans a member from a group, so they can't join up again
public
Returns
object $page
References elseif, RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), and RoxControllerBase\redirectToLogin().
GroupsController::changeGroupSettings ($args, $action, $mem_redirect, $mem_resend)
callback for changing group settings
Parameters
object $args contains vars
object $action contains something else
object $mem_redirect memory for the page after redirect
object $mem_resend memory for resending the form
public
Returns
string
References $action, $count, $mem_redirect, APP_User\loggedIn(), and RoxComponentBase\logWrite().
GroupsController::changeMemberSettings ($args, $action, $mem_redirect, $mem_resend)
callback for changing member settings
Parameters
object $args contains vars
object $action contains something else
object $mem_redirect memory for the page after redirect
object $mem_resend memory for resending the form
public
Returns
string
References $action, $comment, $count, $mem_redirect, APP_User\loggedIn(), and RoxComponentBase\logWrite().
RoxControllerBase::cleanVars ($post_vars) protected inherited
trims all values posted back to controller
Parameters
array $post_vars private
Returns
array
References $vars.
Referenced by VerifymembersController\checkPasswordCallback(), and VerifymembersController\verifyCallback().
GroupsController::create ()
shows a group creation page
public
Returns
object
References RoxControllerBase\redirectToLogin().
GroupsController::createGroupCallback ($args, $action, $mem_redirect, $mem_resend)
Callback function for createGroup page
Parameters
object $args contains vars
object $action contains something else
object $mem_redirect memory for the page after redirect
object $mem_resend memory for resending the form
Returns
string relative request for redirect
References $action, $count, $mem_redirect, APP_User\loggedIn(), and RoxComponentBase\logWrite().
GroupsController::declineInvitation ()
called when a member accepts an invitation to join a group
public
Returns
void
References RoxComponentBase\getWords(), RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), RoxControllerBase\redirectToLogin(), and RoxControllerBase\setFlashNotice().
GroupsController::delete ()
handles group deletion page
public
Returns
object $page
References $request, elseif, RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), and RoxControllerBase\redirectToLogin().
GroupsController::featured ()
fetches featured groups and shows them
public
Returns
object
References $order, $pager, and $params.
GroupsController::forum ()
handles showing group forum page
public
Returns
object $page
RoxComponentBase::get ($key) protected inherited
Referenced by SignupClosedPage\column_col3(), SignupProblemPage\column_col3(), and SignupPage\column_col3().
RoxComponentBase::getLog () protected inherited
wrapper function for MOD_log::get()
protected
Returns
object
References MOD_log\get().
Referenced by RoxComponentBase\logWrite().
RoxComponentBase::getValues () protected inherited
RoxComponentBase::getVersionInfo () protected inherited
returns the revision number saved in revision.txt
protected
Returns
string
References $version.
Referenced by FeedbackModel\sendFeedback().
RoxComponentBase::getWords () protected inherited
returns an instance of the MOD_words class
protected
Returns
object
Referenced by VisualComponent\__call(), acceptInvitation(), addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), GeoPopupPage\body(), GalleryDeletePage\breadcrumbs(), GalleryBasePage\breadcrumbs(), SuggestionsController\changeStateCallback(), MyVisitorsPage\column_col3(), GalleryFlickrPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryAllImagesPage\column_col3(), LinkUpdatePage\column_col3(), HellouniversePage\column_col3(), GeoAdminPage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), GalleryDeletePage\column_col3(), NewsletterPage\column_col3(), FeedbackSentPage\column_col3(), VerifyMembersNotActivePage\column_col3(), VerifyMyselfPage\column_col3(), OneNewsLetterPage\column_col3(), GalleryManagePage\column_col3(), GalleryAllGalleriesPage\column_col3(), VerifiedApprovedVerifiers\column_col3(), ActivitiesFindPage\column_col3(), GroupStartPage\column_col3(), GroupJoinPage\column_col3(), GroupMemberSettingsPage\column_col3(), AboutFaqPage\column_col3(), GroupDeletePage\column_col3(), GroupWikiPage\column_col3(), GroupAddRelatedGroupPage\column_col3(), GroupDeleteRelatedGroupPage\column_col3(), GroupLeavePage\column_col3(), GroupForumPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), AboutFaqsectionPage\column_col3(), PollsPage\column_col3(), VerifiedMembersViewPage\column_col3(), HellouniverseTabbedPage\column_col3(), GroupForumsOverviewPage\column_col3(), declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), Member\get_all_relations(), MembersModel\get_relation_between_members(), Member\get_trad_by_tradid(), Group\getDescription(), FullPagePager\getHtml(), Note\getIdRelMember(), Forums\GetLanguageName(), LastCommentsPage\getLastCommentsTitle(), PageWithRoxLayout\getPage_meta_description(), PageWithRoxLayout\getPage_meta_keyword(), UpdateMandatoryPage\getPageTitle(), AboutTheideaPage\getPageTitle(), ActivitiesBasePage\getPageTitle(), CityPage\getPageTitle(), CountriesPage\getPageTitle(), CountryPage\getPageTitle(), RegionPage\getPageTitle(), SafetyBasePage\getPageTitle(), SearchMembersBasePage\getPageTitle(), SuggestionsBasePage\getPageTitle(), NewsletterPage\getPageTitle(), OneNewsLetterPage\getPageTitle(), GroupsBasePage\getPageTitle(), VerifiedMembersViewPage\getPageTitle(), PollsPage\getPageTitle(), SuggestionsBasePage\getStateSelect(), DebugPage\getSubmenuItems(), GalleryUserPage\getSubmenuItems(), AboutBasePage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), PageWithHTML\head(), MembersController\index_loggedIn(), joined(), kickMember(), Forums\LanguageChoices(), leave(), left(), PageWithRoxLayout\leftoverTranslationLinks(), AboutFaqsectionPage\leftSidebar(), AboutFaqPage\leftSidebar(), InactiveProfilePage\leftsidebar(), AdminMassMailEnqueuePage\leftSidebar(), VerifyMembersPage\leftSidebar(), AdminMassMailDetailsPage\leftSidebar(), AdminMassMailEditCreatePage\leftSidebar(), VerifiedApprovedVerifiers\leftSidebar(), VerifiedMembersViewPage\leftSidebar(), PollsPage\leftSidebar(), MemberPage\leftsidebar(), LoginController\loginCallback(), GalleryController\manage(), MessagesPageWithMailbox\messageActions(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), NotifyAdminPage\notesActions(), GroupsModel\notifyGroupAdmins(), PageWithRoxLayout\quicksearch(), resignAsAdmin(), SuggestionsController\restoreOption(), GeoController\SelectorInclude(), GroupsModel\sendInvitation(), Group\setDescription(), PageWithRoxLayout\SetMetaKey(), AbstractBasePage\showTemplate(), PageWithRoxLayout\submenu(), MessagesBasePage\teaserContent(), GroupSettingsPage\teaserContent(), GroupsSearchPage\teaserContent(), GroupsMyGroupsPage\teaserContent(), GroupInvitePage\teaserContent(), GroupsCreationPage\teaserContent(), TourPage\teaserContent(), GroupsFeaturedPage\teaserContent(), GroupsOverviewPage\teaserContent(), LastCommentsPage\teaserContent(), GroupForumsOverviewPage\teaserContent(), GroupsBasePage\teaserContent(), ResetPasswordFinishPage\teaserHeadline(), ResetPasswordPage\teaserHeadline(), VerifyNoMemberSpecifiedPage\teaserHeadline(), AboutBasePage\teaserHeadline(), GalleryImageNotFoundPage\teaserHeadline(), GalleryAvatarsPage\teaserHeadline(), AboutStatisticsPage\teaserHeadline(), VerifyMyselfPage\teaserHeadline(), VerifyMembersNotActivePage\teaserHeadline(), VerifyMembersPage\teaserHeadline(), GalleryBasePage\teaserHeadline(), SearchMembersBasePage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), SuggestionsBasePage\teaserHeadline(), OneNewsLetterPage\teaserHeadline(), VerifiedMembersViewPage\teaserHeadline(), PollsPage\teaserHeadline(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), GroupMembership\updateMembership(), GalleryController\upload(), GalleryController\uploadedProcess(), GalleryController\user(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
GroupsController::groupForumsOverview ()
GroupsController::groupSettings ()
handles group settings page
public
Returns
object $page
References $request, elseif, RoxControllerBase\redirectAbsolute(), and RoxControllerBase\redirectToLogin().
GroupsController::index ()
main page of groups app
public
Returns
object
GroupsController::inviteMember ()
no-js method for inviting a member
public
Returns
object
References RoxComponentBase\logWrite(), and RoxControllerBase\redirect().
GroupsController::inviteMemberAjax ()
ajax method for inviting a member
public
Returns
object
References $vars, exit, and RoxComponentBase\logWrite().
GroupsController::inviteMembers ()
displays a page allowing a group owner to invite members to the group
public
Returns
object
References $members, and RoxControllerBase\redirectAbsolute().
GroupsController::join ()
handles member joining a group
public
Returns
object $page
References $member, and RoxControllerBase\redirectToLogin().
GroupsController::joined ($args, $action, $mem_redirect, $mem_resend)
Callback function for joining a group
Parameters
object $args contains vars
object $action contains something else
object $mem_redirect memory for the page after redirect
object $mem_resend memory for resending the form
Returns
string relative request for redirect
References $mem_redirect, $member, RoxComponentBase\getWords(), RoxComponentBase\logWrite(), RoxControllerBase\setFlashError(), and RoxControllerBase\setFlashNotice().
GroupsController::kickMember ()
kicks a member from a group, by just taking them out of the group
public
Returns
object $page
References elseif, RoxComponentBase\getWords(), RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), RoxControllerBase\redirectToLogin(), RoxControllerBase\setFlashError(), and RoxControllerBase\setFlashNotice().
GroupsController::leave ()
handles member leaving a group
public
Returns
object $page
References $member, RoxComponentBase\getWords(), RoxControllerBase\redirectToLogin(), and RoxControllerBase\setFlashError().
GroupsController::left ()
handles member leaving a group
public
Returns
object $page
References $member, RoxComponentBase\getWords(), RoxComponentBase\logWrite(), RoxControllerBase\redirectToLogin(), RoxControllerBase\setFlashError(), and RoxControllerBase\setFlashNotice().
RoxComponentBase::logWrite ($string, $type = 'Log') protected inherited
wrapper for calls to MOD_log::get->write()
Parameters
string $string
string $type protected
References $type, and RoxComponentBase\getLog().
Referenced by acceptInvitation(), acceptMember(), MembersModel\addComment(), addMemberAsAdmin(), MembersModel\addRelation(), banMember(), changeGroupSettings(), changeMemberSettings(), createGroupCallback(), declineInvitation(), delete(), MembersModel\delete_translation_multiple(), FeedbackModel\feedbackMail(), MembersController\index_loggedIn(), inviteMember(), inviteMemberAjax(), joined(), kickMember(), left(), Geo\placeType(), AdminModel\processMembers(), resignAsAdmin(), MembersModel\set_preference(), MembersModel\set_public_profile(), MembersModel\setLocation(), MembersModel\updateProfile(), and MembersModel\updateRelation().
GroupsController::memberAdministration ()
handles member administration page
public
Returns
object $page
References $member, $rights, elseif, RoxControllerBase\redirectAbsolute(), and RoxControllerBase\redirectToLogin().
GroupsController::members ()
handles showing group members page
public
Returns
object $page
GroupsController::memberSearchAjax ()
ajax method for searching for members to send group invites to
public
Returns
object
References $member, $members, exit, and json_encode().
GroupsController::memberSettings ()
handles member settings page
public
Returns
object $page
References $request, and RoxControllerBase\redirectToLogin().
GroupsController::myGroups ()
fetches the groups for the logged in member and shows them
public
Returns
object
References $pager, $params, and RoxControllerBase\redirectToLogin().
GroupsController::realImg ()
sets the proper header for outputting a binary image and sends the image shows a proper sized image
public
Returns
void
References $vars, and exit.
RoxControllerBase::redirect ($request, $get_args = '') protected inherited
References $request, and RoxControllerBase\redirectAbsolute().
Referenced by RoxController\_redirectLevel(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), ExtensionsController\index(), VerifymembersController\index(), GalleryController\index(), SignupController\index(), RoxController\index(), MembersController\index_loggedIn(), MembersController\index_loggedOut(), inviteMember(), LoginController\logIn(), GalleryController\manage(), MembersController\redirect_myprofile(), RoxControllerBase\redirectHome(), RoxControllerBase\redirectRefresh(), and GalleryController\upload().
RoxControllerBase::redirectAbsolute ($url, $get_args = '') protected inherited
References $url.
Referenced by acceptInvitation(), acceptMember(), ActivitiesController\activities(), ActivitiesController\activitiesNearMe(), addMemberAsAdmin(), banMember(), declineInvitation(), delete(), SuggestionsController\editCreate(), ActivitiesController\editcreate(), groupSettings(), RoxController\index(), inviteMembers(), kickMember(), LoginController\logOut(), AdminController\massmailTrigger(), AdminController\massmailUnqueue(), AdminController\massmailUntrigger(), memberAdministration(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), ActivitiesController\myActivities(), AdminWordController\noRights(), AdminController\noRights(), RoxControllerBase\redirect(), RoxControllerBase\redirectToLogin(), resignAsAdmin(), SafetyController\safetyContact(), SearchController\searchMembers(), SuggestionsController\show(), ActivitiesController\show(), showGroup(), SuggestionsController\suggestions(), AdminController\treasurerStopDonationCampaign(), and SuggestionsController\voteRanking().
RoxControllerBase::redirectHome ($get_args = '') protected inherited
References RoxControllerBase\redirect().
Referenced by InviteController\index(), and RoxController\index().
RoxControllerBase::redirectRefresh () protected inherited
References RoxControllerBase\redirect().
RoxControllerBase::redirectToLogin ($url_part) protected inherited
redirects to a login screen, returning the user to where it was afterwards
Parameters
string $url_part - relative url protected
References RoxControllerBase\redirectAbsolute().
Referenced by acceptInvitation(), acceptMember(), addMemberAsAdmin(), banMember(), create(), declineInvitation(), delete(), groupSettings(), GalleryController\index(), join(), kickMember(), leave(), left(), memberAdministration(), memberSettings(), and myGroups().
RoxComponentBase::refresh_get ($key) inherited
GroupsController::resignAsAdmin ()
resigns a member as admin of a group
public
Returns
object $page
References elseif, RoxComponentBase\getWords(), RoxComponentBase\logWrite(), RoxControllerBase\redirectAbsolute(), RoxControllerBase\setFlashError(), and RoxControllerBase\setFlashNotice().
GroupsController::search ()
searches for groups using GET vars
public
Returns
object
References $order, $pager, and $params.
RoxControllerBase::setFlashError ($message) inherited
Set flash error message
See Also
PageWithRoxLayout::getFlashError() for counterpart
Parameters
string $message Message text for flash
Referenced by addMemberAsAdmin(), RelatedGroupsController\addRelatedGroup(), RelatedGroupsController\deleteRelatedGroup(), MembersController\index_loggedIn(), joined(), kickMember(), leave(), left(), resignAsAdmin(), and GalleryController\uploadedProcess().
RoxControllerBase::setFlashNotice ($message) inherited
Set flash notice message
See Also
PageWithRoxLayout::getFlashNotice() for counterpart
Parameters
string $message Message text for flash
Referenced by acceptInvitation(), addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), SuggestionsController\changeStateCallback(), declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), MembersController\index_loggedIn(), joined(), kickMember(), left(), LoginController\loginCallback(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), resignAsAdmin(), SuggestionsController\restoreOption(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
RoxControllerBase::setTitle ($title) protected inherited
References $title.
Referenced by RoxControllerBase\setTitleTranslate().
RoxControllerBase::setTitleTranslate ($title) protected inherited
References $title, $words, and RoxControllerBase\setTitle().
GroupsController::showGroup ()
displays a group overview page for a group
public
Returns
object
References RoxControllerBase\redirectAbsolute().
GroupsController::thumbImg ()
sets the proper header for outputting a binary image and sends the image shows a thumbnail
public
Returns
void
References $vars, and exit.
GroupsController::wiki ()
handles showing group wiki page
public
Returns
object $page
The documentation for this class was generated from the following file:
groups.ctrl.php