Rox: VisualComponent Class Reference
VisualComponent Class Reference
Public Member Functions
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 4 of file visualcomponent.php.
Member Function Documentation
VisualComponent::__call ($methodname, $args)
fancy method for automatic template inclusion. based on the given methodname and classname, we determine a template filename and, if it exists, include it. Otherwise, look for the template file in the parent class.
Definition at line 28 of file visualcomponent.php.
References $baseuri, $words, $ww, $wwsilent, getTemplatePrefix(), and RoxComponentBase\getWords().
Referenced by PersonalStartpage\teaserContent(), and MemberPage\teaserReplacement().
VisualComponent::getAppname ($classname) protected
Definition at line 94 of file visualcomponent.php.
References ClassLoader\whereIsClass().
VisualComponent::getTemplatePrefix ($classname = false) protected
Definition at line 71 of file visualcomponent.php.
References ClassLoader\whereIsClass().
Referenced by __call().
VisualComponent::set_layoutkit (& $layoutkit) protected
called by the framework, to inject some essential values..
Parameters
unknown_type $layoutkit
Definition at line 11 of file visualcomponent.php.
References $layoutkit, $words, layoutkit, and words.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/mvc-base/visualcomponent.php