Rox: NotifyAdminPage Class Reference
NotifyAdminPage Class Reference
Public Member Functions
SetMetaKey ($ss)
SetMetaRobots ($ss)
SetMetaDescription ($ss)
getFlashNotice ($remove=false)
getFlashError ($remove=false)
render ()
addWidget (RoxWidget $widget)
setModel ($model)
createWidget ($classname)
__call ($methodname, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
teaserContent ()
getSubmenuActiveItem ()
notesActions ($callback_tag)
column_col3 ()
leftSidebar ()
getTopmenuActiveItem ()
getSubmenuItems ()
getStylesheets ()
getPage_meta_keyword ()
getPage_meta_robots ()
getPage_meta_description ()
init ()
getStylesheetPatches ()
getTopmenuItems ()
body ()
topnav ()
topmenu ()
quicksearch ()
columnsArea ()
getPageTitle ()
teaser ()
submenu ()
footer ()
leftoverTranslationLinks ()
debugInfo ()
getColumnNames ()
column_col1 ()
column_col2 ()
volunteerMenu ()
getCallbackOutput ($controller, $method)
getRedirectedMem ($array)
getCustomElements ()
getScriptfiles ()
getLateLoadScriptfiles ()
addEarlyLoadScriptFile ($file)
addLateLoadScriptFile ($file)
printHTML ()
includeStylesheets ()
includeCustomElements ()
includeJsConfig ()
includeScriptfiles ()
includeLateScriptfiles ()
head ()
getPagePermalink ()
statusMessage ()
getModel ()
showTemplate ($rel_path, $args=array())
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$meta_description
$meta_keyword
$meta_robots
Detailed Description
This page allows to create a new group
Member Function Documentation
VisualComponent::__call ($methodname, $args) inherited
fancy method for automatic template inclusion. based on the given methodname and classname, we determine a template filename and, if it exists, include it. Otherwise, look for the template file in the parent class.
References $baseuri, $words, $ww, $wwsilent, VisualComponent\getTemplatePrefix(), RoxComponentBase\getWords(), and include.
Referenced by PersonalStartpage\teaserContent(), and MemberPage\teaserReplacement().
RoxComponentBase::__get ($key) inherited
Referenced by Member\get_messengers().
RoxComponentBase::__set ($key, $value) inherited
References $value.
RoxComponentBase::__toString () inherited
PageWithHTML::addEarlyLoadScriptFile ($file) protected inherited
registers a script for early loading
Parameters
string $file - js file to early load
protected
Returns
void
PageWithHTML::addLateLoadScriptFile ($file) protected inherited
registers a script for late loading
Parameters
string $file - js file to early load
protected
Returns
void
PageWithHTML::addWidget (RoxWidget $widget) inherited
Widgets added this way will be asked for stylesheet and scriptfile information TODO: evtl not a good idea to do it this way.
Parameters
RoxWidget $widget
PageWithRoxLayout::body () protected inherited
References TEMPLATE_DIR.
Referenced by AdminMassMailEditCreatePage\__construct().
PageWithRoxLayout::column_col1 () protected inherited
PageWithRoxLayout::column_col2 () protected inherited
NotifyAdminPage::column_col3 () protected
References $callback_tag, $formkit, $layoutkit, $model, $page_url, $words, AbstractBasePage\getModel(), notesActions(), and value.
PageWithRoxLayout::columnsArea () protected inherited
References PageWithRoxLayout\getColumnNames(), and TEMPLATE_DIR.
AbstractBasePage::createWidget ($classname) inherited
References $layoutkit, and layoutkit.
Referenced by SignupResentMailPage\column_col3(), SignupMailConfirmPage\column_col3(), VerifyMustLoginPage\column_col3(), GroupJoinPage\column_col3(), GroupMemberSettingsPage\column_col3(), GroupLeavePage\column_col3(), LoginPage\column_col3(), and PageWithRoxLayout\volunteerMenu().
PageWithRoxLayout::debugInfo () protected inherited
References debug, and TEMPLATE_DIR.
PageWithRoxLayout::footer () protected inherited
RoxComponentBase::get ($key) protected inherited
Referenced by SignupClosedPage\column_col3(), SignupProblemPage\column_col3(), and SignupPage\column_col3().
VisualComponent::getAppname ($classname) protected inherited
References ClassLoader\whereIsClass().
PageWithRoxLayout::getCallbackOutput ($controller, $method) protected inherited
shortcut to get callback variables for form
Parameters
string $controller controller to callback to
string $method method in controller
protected
Returns
string
References layoutkit.
Referenced by TripSingleTripPage\column_col3(), BlogEditPage\column_col3(), and BlogCreatePage\column_col3().
PageWithRoxLayout::getColumnNames () protected inherited
Referenced by PageWithRoxLayout\columnsArea().
PageWithHTML::getCustomElements () protected inherited
skeleton method of getCustomElements
protected
Returns
array
Referenced by PageWithHTML\includeCustomElements().
PageWithRoxLayout::getFlashError ($remove = false) inherited
Get flash error message and remove from session if needed
See Also
RoxControllerBase::setFlashError() for counterpart
templates/shared/roxpage/body.php
Parameters
bool $remove True if message should be removed from session, false by default
Returns
string Flash error message
PageWithRoxLayout::getFlashNotice ($remove = false) inherited
Get flash notice message and remove from session if needed
See Also
RoxControllerBase::setFlashNotice() for counterpart
templates/shared/roxpage/body.php
Parameters
bool $remove True if message should be removed from session, false by default
Returns
string Flash notice message
PageWithHTML::getLateLoadScriptfiles () protected inherited
returns all registered late load scripts these are the scripts to be loaded at the end of the page
protected
Returns
array
Referenced by PageWithHTML\includeLateScriptfiles().
RoxComponentBase::getLog () protected inherited
wrapper function for MOD_log::get()
protected
Returns
object
References MOD_log\get().
Referenced by RoxComponentBase\logWrite().
AbstractBasePage::getModel () protected inherited
Get the model object that was stored using setModel
Referenced by NotifyAdminSettingsPage\column_col3(), MessagesPageWithMailbox\column_col3(), column_col3(), InvitePage\column_col3(), AboutGenericPage\column_col3(), GroupSettingsPage\column_col3(), GroupInvitePage\column_col3(), GroupMemberAdministrationPage\column_col3(), and MessagesPageWithMailbox\getMailboxWidget().
PageWithRoxLayout::getPage_meta_description () protected inherited
References $words, and RoxComponentBase\getWords().
PageWithRoxLayout::getPage_meta_keyword () protected inherited
References $words, and RoxComponentBase\getWords().
PageWithRoxLayout::getPage_meta_robots () protected inherited
PageWithHTML::getPagePermalink () protected inherited
PageWithRoxLayout::getPageTitle () protected inherited
PageWithRoxLayout::getRedirectedMem ($array) protected inherited
returns the redirected post vars, if any
Parameters
string $array which saved array to return from the redirected mem
protected
Returns
array
References layoutkit.
PageWithHTML::getScriptfiles () protected inherited
returns all registered early load scripts these are the scripts to be loaded in the html head element
protected
Returns
array
Referenced by PageWithHTML\includeScriptfiles().
PageWithRoxLayout::getStylesheetPatches () protected inherited
PageWithRoxLayout::getStylesheets () protected inherited
NotifyAdminPage::getSubmenuActiveItem () protected
NotifyBasePage::getSubmenuItems () protected inherited
VisualComponent::getTemplatePrefix ($classname = false) protected inherited
References ClassLoader\whereIsClass().
Referenced by VisualComponent\__call().
NotifyBasePage::getTopmenuActiveItem () protected inherited
PageWithRoxLayout::getTopmenuItems () protected inherited
Return a list of items to show in the sub menu. Each item is an array of keyword, url and translatable Word
References $_SESSION, $items, $username, and MOD_bw_user_Auth\isBWLoggedIn().
Referenced by PageWithRoxLayout\topmenu().
RoxComponentBase::getValues () protected inherited
RoxComponentBase::getVersionInfo () protected inherited
returns the revision number saved in revision.txt
protected
Returns
string
References $version.
Referenced by FeedbackModel\sendFeedback().
RoxComponentBase::getWords () protected inherited
returns an instance of the MOD_words class
protected
Returns
object
Referenced by VisualComponent\__call(), GroupsController\acceptInvitation(), GroupsController\addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), GeoPopupPage\body(), GalleryDeletePage\breadcrumbs(), GalleryBasePage\breadcrumbs(), SuggestionsController\changeStateCallback(), MyVisitorsPage\column_col3(), GalleryFlickrPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryAllImagesPage\column_col3(), GeoAdminPage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), LinkUpdatePage\column_col3(), HellouniversePage\column_col3(), GalleryDeletePage\column_col3(), NewsletterPage\column_col3(), FeedbackSentPage\column_col3(), VerifyMembersNotActivePage\column_col3(), VerifyMyselfPage\column_col3(), OneNewsLetterPage\column_col3(), GalleryManagePage\column_col3(), GalleryAllGalleriesPage\column_col3(), VerifiedApprovedVerifiers\column_col3(), ActivitiesFindPage\column_col3(), GroupStartPage\column_col3(), AboutFaqPage\column_col3(), GroupDeletePage\column_col3(), GroupJoinPage\column_col3(), GroupMemberSettingsPage\column_col3(), GroupWikiPage\column_col3(), GroupAddRelatedGroupPage\column_col3(), GroupDeleteRelatedGroupPage\column_col3(), GroupLeavePage\column_col3(), GroupForumPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), AboutFaqsectionPage\column_col3(), PollsPage\column_col3(), VerifiedMembersViewPage\column_col3(), HellouniverseTabbedPage\column_col3(), GroupForumsOverviewPage\column_col3(), GroupsController\declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), Member\get_all_relations(), MembersModel\get_relation_between_members(), Member\get_trad_by_tradid(), Group\getDescription(), FullPagePager\getHtml(), Note\getIdRelMember(), Forums\GetLanguageName(), LastCommentsPage\getLastCommentsTitle(), PageWithRoxLayout\getPage_meta_description(), PageWithRoxLayout\getPage_meta_keyword(), UpdateMandatoryPage\getPageTitle(), AboutTheideaPage\getPageTitle(), ActivitiesBasePage\getPageTitle(), CityPage\getPageTitle(), CountriesPage\getPageTitle(), CountryPage\getPageTitle(), RegionPage\getPageTitle(), SafetyBasePage\getPageTitle(), SearchMembersBasePage\getPageTitle(), SuggestionsBasePage\getPageTitle(), NewsletterPage\getPageTitle(), OneNewsLetterPage\getPageTitle(), GroupsBasePage\getPageTitle(), VerifiedMembersViewPage\getPageTitle(), PollsPage\getPageTitle(), SuggestionsBasePage\getStateSelect(), DebugPage\getSubmenuItems(), GalleryUserPage\getSubmenuItems(), AboutBasePage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), PageWithHTML\head(), MembersController\index_loggedIn(), GroupsController\joined(), GroupsController\kickMember(), Forums\LanguageChoices(), GroupsController\leave(), GroupsController\left(), PageWithRoxLayout\leftoverTranslationLinks(), AboutFaqsectionPage\leftSidebar(), AboutFaqPage\leftSidebar(), InactiveProfilePage\leftsidebar(), AdminMassMailEnqueuePage\leftSidebar(), VerifyMembersPage\leftSidebar(), AdminMassMailDetailsPage\leftSidebar(), AdminMassMailEditCreatePage\leftSidebar(), VerifiedApprovedVerifiers\leftSidebar(), VerifiedMembersViewPage\leftSidebar(), PollsPage\leftSidebar(), MemberPage\leftsidebar(), LoginController\loginCallback(), GalleryController\manage(), MessagesPageWithMailbox\messageActions(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), notesActions(), GroupsModel\notifyGroupAdmins(), PageWithRoxLayout\quicksearch(), GroupsController\resignAsAdmin(), SuggestionsController\restoreOption(), GeoController\SelectorInclude(), GroupsModel\sendInvitation(), Group\setDescription(), PageWithRoxLayout\SetMetaKey(), AbstractBasePage\showTemplate(), PageWithRoxLayout\submenu(), MessagesBasePage\teaserContent(), GroupSettingsPage\teaserContent(), GroupsSearchPage\teaserContent(), GroupsMyGroupsPage\teaserContent(), GroupInvitePage\teaserContent(), GroupsCreationPage\teaserContent(), TourPage\teaserContent(), GroupsFeaturedPage\teaserContent(), GroupsOverviewPage\teaserContent(), LastCommentsPage\teaserContent(), GroupForumsOverviewPage\teaserContent(), GroupsBasePage\teaserContent(), ResetPasswordFinishPage\teaserHeadline(), ResetPasswordPage\teaserHeadline(), VerifyNoMemberSpecifiedPage\teaserHeadline(), AboutBasePage\teaserHeadline(), GalleryImageNotFoundPage\teaserHeadline(), GalleryAvatarsPage\teaserHeadline(), AboutStatisticsPage\teaserHeadline(), VerifyMyselfPage\teaserHeadline(), VerifyMembersNotActivePage\teaserHeadline(), VerifyMembersPage\teaserHeadline(), GalleryBasePage\teaserHeadline(), SearchMembersBasePage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), SuggestionsBasePage\teaserHeadline(), OneNewsLetterPage\teaserHeadline(), VerifiedMembersViewPage\teaserHeadline(), PollsPage\teaserHeadline(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), GroupMembership\updateMembership(), GalleryController\upload(), GalleryController\uploadedProcess(), GalleryController\user(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
PageWithHTML::head () protected inherited
References $baseuri, PageWithHTML\getPageTitle(), RoxComponentBase\getWords(), PageWithHTML\includeCustomElements(), PageWithHTML\includeStylesheets(), and title.
Referenced by PageWithHTML\printHTML().
PageWithHTML::includeCustomElements () protected inherited
allows for outputting custom elements in the page <head> element
protected
References PageWithHTML\getCustomElements().
Referenced by PageWithHTML\head().
PageWithHTML::includeJsConfig () protected inherited
Inserts JavaScript configuration.
Reads [javascript] section in rox.ini and makes it available via bwroxConfig object in JavaScript.
References $value.
Referenced by PageWithHTML\printHTML().
PageWithHTML::includeLateScriptfiles () protected inherited
outputs script tags that include script files called at the end of pages
protected
Returns
void
References $url, and PageWithHTML\getLateLoadScriptfiles().
Referenced by PageWithHTML\printHTML().
PageWithHTML::includeScriptfiles () protected inherited
References $url, and PageWithHTML\getScriptfiles().
Referenced by PageWithHTML\printHTML().
PageWithHTML::includeStylesheets () protected inherited
References $url, endif, PageWithHTML\getStylesheetPatches(), and PageWithHTML\getStylesheets().
Referenced by PageWithHTML\head().
PageWithRoxLayout::init () protected inherited
PageWithRoxLayout::leftoverTranslationLinks () protected inherited
References RoxComponentBase\getWords().
NotifyBasePage::leftSidebar () protected inherited
RoxComponentBase::logWrite ($string, $type = 'Log') protected inherited
wrapper for calls to MOD_log::get->write()
Parameters
string $string
string $type protected
References $type, and RoxComponentBase\getLog().
Referenced by GroupsController\acceptInvitation(), GroupsController\acceptMember(), MembersModel\addComment(), GroupsController\addMemberAsAdmin(), MembersModel\addRelation(), GroupsController\banMember(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), GroupsController\createGroupCallback(), GroupsController\declineInvitation(), GroupsController\delete(), MembersModel\delete_translation_multiple(), FeedbackModel\feedbackMail(), MembersController\index_loggedIn(), GroupsController\inviteMember(), GroupsController\inviteMemberAjax(), GroupsController\joined(), GroupsController\kickMember(), GroupsController\left(), Geo\placeType(), AdminModel\processMembers(), GroupsController\resignAsAdmin(), MembersModel\set_preference(), MembersModel\set_public_profile(), MembersModel\setLocation(), MembersModel\updateProfile(), and MembersModel\updateRelation().
NotifyAdminPage::notesActions ($callback_tag) protected
References $words, and RoxComponentBase\getWords().
Referenced by column_col3().
PageWithHTML::printHTML () protected inherited
References PageWithHTML\head(), PageWithHTML\includeJsConfig(), PageWithHTML\includeLateScriptfiles(), PageWithHTML\includeScriptfiles(), and layoutkit.
Referenced by PageWithHTML\render().
PageWithRoxLayout::quicksearch () protected inherited
A tiny wee quicksearch box
References $_SESSION, $login_url, $request, $username, $words, MOD_online\get(), RoxComponentBase\getWords(), MOD_bw_user_Auth\isBWLoggedIn(), and TEMPLATE_DIR.
RoxComponentBase::refresh_get ($key) inherited
PageWithHTML::render () inherited
References PageWithHTML\init(), and PageWithHTML\printHTML().
VisualComponent::set_layoutkit (& $layoutkit) protected inherited
called by the framework, to inject some essential values..
Parameters
unknown_type $layoutkit
References $layoutkit, $words, layoutkit, and words.
PageWithRoxLayout::SetMetaDescription ($ss) inherited
PageWithRoxLayout::SetMetaKey ($ss) inherited
References $words, and RoxComponentBase\getWords().
PageWithRoxLayout::SetMetaRobots ($ss) inherited
AbstractBasePage::setModel ($model) inherited
some view classes need to store a model object.
References $model.
AbstractBasePage::showTemplate ($rel_path, $args = array()) protected inherited
References $template, and RoxComponentBase\getWords().
PageWithHTML::statusMessage () protected inherited
References $_SESSION, $class, and $words.
PageWithRoxLayout::submenu () protected inherited
References $words, RoxComponentBase\getWords(), and TEMPLATE_DIR.
PageWithRoxLayout::teaser () protected inherited
References TEMPLATE_DIR.
NotifyAdminPage::teaserContent () protected
References a.
PageWithRoxLayout::topmenu () protected inherited
References $_SESSION, $active_menu_item, $rights, $username, $words, PageWithRoxLayout\getTopmenuActiveItem(), PageWithRoxLayout\getTopmenuItems(), RoxComponentBase\getWords(), MOD_bw_user_Auth\isBWLoggedIn(), and TEMPLATE_DIR.
PageWithRoxLayout::topnav () protected inherited
References $_SESSION, $login_url, $request, $username, $words, MOD_online\get(), RoxComponentBase\getWords(), and TEMPLATE_DIR.
PageWithRoxLayout::volunteerMenu () protected inherited
References AbstractBasePage\createWidget().
Field Documentation
PageWithRoxLayout::$meta_description protected inherited
PageWithRoxLayout::$meta_keyword protected inherited
PageWithRoxLayout::$meta_robots protected inherited
The documentation for this class was generated from the following file:
notifyadmin.page.php