Rox: MOD_layoutbits Class Reference
MOD_layoutbits Class Reference
Public Member Functions
__construct ()
ago ($timestamp)
ago_qualified ($timestamp)
FindTrad ($IdTrad, $ReplaceWithBr=false)
GetPreference ($namepref, $idm=0)
getParams ($Param)
fage_value ($dd, $nn=false)
Static Public Member Functions
static PIC_100_100 ($username, $picfile='', $style="framed")
static PIC_75_75 ($username, $picfile='', $style="framed")
static PIC_50_50 ($username, $picfile='', $style="framed")
static PIC_40_40 ($username, $picfile='', $style="framed")
static PIC_30_30 ($username, $picfile='', $style="framed")
static PIC_15_15 ($username, $picfile='', $style="framed")
static get ()
static test ()
static linkWithPicture ($username, $picfile="", $mode="")
static linkWithPictureVar ($username, $height, $width, $quality, $picfile, $style)
static smallUserPic_userId ($userId)
static smallUserPic_username ($username)
static smallUserPic_usernameVar ($username, $height, $width, $quality)
static userPic_userId ($userId)
static userPic_username ($username)
static truncate ($string, $length, $omission= '...')
static truncate_words ($text, $limit, $ellipsis= '...')
static getGenderTranslated ($gender, $hideGender, $addGenderText=true)
Protected Member Functions
member_pic_url ()
Detailed Description
Collection of functions that create elements for a page.
An example for its use: $layoutbits = MOD_layoutbits::get(); // get the singleton instance $id = $geo->getCityID($cityname);
Author
Andreas (bw/cs:lemon-head)
Definition at line 33 of file layoutbits.lib.php.
Constructor & Destructor Documentation
MOD_layoutbits::__construct ()
Definition at line 67 of file layoutbits.lib.php.
Member Function Documentation
MOD_layoutbits::ago ($timestamp)
returns a sentence based on a given timestamp like: 20 minutes ago
Parameters
int $timestamp unix timestamp public
Returns
string
Definition at line 479 of file layoutbits.lib.php.
References $text, $words, and round.
Referenced by ApiModel\getMemberData(), MailboxWidget_Personalstart\showListItem(), and NotifyMemberWidget\showListItem().
MOD_layoutbits::ago_qualified ($timestamp)
Definition at line 503 of file layoutbits.lib.php.
References round.
MOD_layoutbits::fage_value ($dd, $nn = false)
Definition at line 643 of file layoutbits.lib.php.
References elseif.
MOD_layoutbits::FindTrad ($IdTrad, $ReplaceWithBr = false)
Definition at line 549 of file layoutbits.lib.php.
References $_SESSION.
static MOD_layoutbits::get () static
singleton getter
Parameters
void
Returns
PApps
Definition at line 83 of file layoutbits.lib.php.
Referenced by VolunteerbarModel\getNumberSpamToBeChecked().
static MOD_layoutbits::getGenderTranslated ($gender, $hideGender, $addGenderText = true) static
Returns a string with the gender if that isn't hidden. Translated of the form 'Gender: male/female/other'
Returns
string 'Gender: male/female/other/ translated or empty string
Definition at line 707 of file layoutbits.lib.php.
References $words.
MOD_layoutbits::getParams ($Param)
Definition at line 620 of file layoutbits.lib.php.
References $_SESSION.
MOD_layoutbits::GetPreference ($namepref, $idm = 0)
Definition at line 592 of file layoutbits.lib.php.
References $_SESSION.
static MOD_layoutbits::linkWithPicture ($username, $picfile = "", $mode = "") static
function LinkWithPicture build a link with picture and Username to the member profile. Optional parameter status can be used to alter the link. Old version found in FunctionsTools.php
Usually it is more convenient to use smallUserPic_userId($userId) or smallUserPic_username($username)
Parameters
string $username
string $pic alternative picture path
string $mode can be used to enable 'map_style'
Returns
string html-formatted link with picture
Definition at line 113 of file layoutbits.lib.php.
References $username, and $words.
Referenced by NotifyAdminSettingsPage\column_col3(), and GroupMemberAdministrationPage\column_col3().
static MOD_layoutbits::linkWithPictureVar ($username, $height, $width, $quality, $picfile, $style) static
function LinkWithPicture build a link with picture and Username to the member profile. Optional parameter status can be used to alter the link. Old version found in FunctionsTools.php
Usually it is more convenient to use smallUserPic_userId($userId) or smallUserPic_username($username)
Parameters
string $username
string $height of picture
string $width of picture
string $quality of picture
string $picfile alternative picture path
string $style css-class for the image-tag
Returns
string html-formatted link with picture
Definition at line 175 of file layoutbits.lib.php.
References $username, $width, and $words.
MOD_layoutbits::member_pic_url () protected
Definition at line 93 of file layoutbits.lib.php.
static MOD_layoutbits::PIC_100_100 ($username, $picfile = '', $style = "framed") static
Quasi-constant functions for userthumbnails
Definition at line 40 of file layoutbits.lib.php.
References $style, $username, and $width.
static MOD_layoutbits::PIC_15_15 ($username, $picfile = '', $style = "framed") static
Definition at line 55 of file layoutbits.lib.php.
References $style, $username, and $width.
static MOD_layoutbits::PIC_30_30 ($username, $picfile = '', $style = "framed") static
Definition at line 52 of file layoutbits.lib.php.
References $style, $username, and $width.
Referenced by MailboxWidget_Personalstart\showListItem(), NotifyMemberWidget\showListItem(), and MailboxWidget_WithMember\tableCell_from().
static MOD_layoutbits::PIC_40_40 ($username, $picfile = '', $style = "framed") static
Definition at line 49 of file layoutbits.lib.php.
References $style, $username, and $width.
static MOD_layoutbits::PIC_50_50 ($username, $picfile = '', $style = "framed") static
Definition at line 46 of file layoutbits.lib.php.
References $style, $username, and $width.
Referenced by MyVisitorsPage\column_col3(), ReadMessagePage\column_col3(), MessagesContactboxPage\mailboxDescription(), GroupMemberlistWidget\render(), and MailboxWidget\tableCell_from().
static MOD_layoutbits::PIC_75_75 ($username, $picfile = '', $style = "framed") static
Definition at line 43 of file layoutbits.lib.php.
References $style, $username, and $width.
static MOD_layoutbits::smallUserPic_userId ($userId) static
100x100 avatar picture for forums etc
Parameters
string $username
Definition at line 206 of file layoutbits.lib.php.
Referenced by RoxView\teasermain().
static MOD_layoutbits::smallUserPic_username ($username) static
100x100 avatar picture for forums etc
Parameters
string $username
Definition at line 226 of file layoutbits.lib.php.
References $username.
Referenced by InviteModel\style(), and SignupView\style().
static MOD_layoutbits::smallUserPic_usernameVar ($username, $height, $width, $quality) static
XxX avatar picture for all over the website
Parameters
string $username
Definition at line 241 of file layoutbits.lib.php.
static MOD_layoutbits::test () static
Definition at line 97 of file layoutbits.lib.php.
static MOD_layoutbits::truncate ($string, $length, $omission = '...') static
Truncate a string
Parameters
string $string Input string
int $length Maximum length of truncated version
string $omission Trailing characters indicating omission, default: '...'
Returns
string Truncated version of string
Definition at line 671 of file layoutbits.lib.php.
static MOD_layoutbits::truncate_words ($text, $limit, $ellipsis = ' ...') static
Truncate a string with full words
Parameters
string $text Input string
int $limit length of truncated version
string $ellipsis Trailing characters indicating ellipsis, default: ' ...'
Returns
string Truncated version of string
Definition at line 690 of file layoutbits.lib.php.
References $text, and $words.
static MOD_layoutbits::userPic_userId ($userId) static
Definition at line 252 of file layoutbits.lib.php.
static MOD_layoutbits::userPic_username ($username) static
Definition at line 290 of file layoutbits.lib.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/layoutbits/lib/layoutbits.lib.php