Rox: Member Class Reference
Member Class Reference
Public Member Functions
__construct ($member_id=false)
init ($values, $dao)
get_userid ()
setCryptedZip ($cryptId)
setCryptedHouseNumber ($cryptId)
setCryptedStreetName ($cryptId)
get_profile_languages ()
get_languages_spoken ()
get_all_spoken_languages ()
get_all_signed_languages ()
get_all_translatable_languages ()
getLanguagePreference ()
getLanguagePreferenceId ()
get_language_levels ()
get_TabRestrictions ()
get_TabRelationsType ()
get_TabTypicOffer ()
IsFilled ($fieldname)
get_trads_fields ()
get_phone ()
get_homephonenumber ()
get_publicProfile ()
isPublic ()
get_name ()
get_firstname ()
get_secondname ()
get_lastname ()
get_email ()
getEmailWithoutPermissionChecks ()
get_messengers ()
hasMessengers ()
get_age ()
get_gender_for_public ()
get_housenumber ()
get_street ()
get_zip ()
get_city ()
get_region ()
get_country ()
get_countrycode ()
get_regioncode ()
getFirstAddress ()
getSignupFeedback ()
count_mynotes ()
count_comments ()
getTripsArray ()
getBlogs ()
getGalleryItemsCount ()
getComingPosts ()
getGroups ()
getNote ($for)
getNotes ()
getNoteCategories ()
get_group_memberships ()
forums_posts_count ()
get_verification_status ()
update_relation ($IdRelation, $IdTrad)
get_relations ()
get_all_relations ()
get_preferences ()
getPreference ($name, $default=false)
getVisitorCount ()
getVisitorsSubset (PagerWidget $pager)
get_comments ()
get_comments_commenter ($id)
get_comments_written ()
get_trad ($fieldname, $IdLanguage, $ReplaceWithBr=False)
get_trad_by_tradid ($IdTrad, $IdLanguage, $ReplaceWithBr=False)
setEditMode ($state=false)
getProfilePictureID ()
findByUsername ($username)
getGroupMembership ($group)
getRoles ()
hasRole ($role, $object=false)
hasPrivilege ($controller, $method= '*', $object= '*')
sql_get_set ($table, $column)
sql_get_enum ($table, $column)
getAllPostVotes ()
getAllThreadVotes ()
isActive ()
isNotActiveHidden ()
isPending ()
isBanned ()
recordVisit (Member $member)
removeLanguages ()
getOldRights ()
setPassword ($pw)
logOut ()
hasOldRight (array $rights)
getPossibleStatusArray ()
inactivateProfile ()
activateProfile ()
removeProfile ()
isBrowsable ()
sendMail ($subject, $body)
refreshMemoryCookie ($newsession=false)
removeSessionMemory ($seriesToken= '', $hijacked=false)
canLogIn ()
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const ACTIVE_ALL = "'Active', 'ActiveHidden', 'ChoiceInactive', 'OutOfRemind', 'Pending'"
const ACTIVE_WITH_MESSAGES = "'Active', 'OutOfRemind', 'Pending'"
$address = null
Data Fields inherited from RoxEntityBase
$sql_order = ''
Protected Member Functions
set_profile_languages ()
get_trads ()
get_address ()
get_crypted ($crypted_id, $return_value="")
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_table_name = 'members'
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 35 of file member.entity.php.
Constructor & Destructor Documentation
Member::__construct ($member_id = false)
Definition at line 50 of file member.entity.php.
References $_SESSION, RoxEntityBase\findById(), and words.
Member Function Documentation
Member::activateProfile ()
sets the profile as active
public
Returns
bool
Definition at line 1799 of file member.entity.php.
Member::canLogIn ()
returns a bool based on whether the member is able to log in or not, based on status
public
Returns
bool
Definition at line 2015 of file member.entity.php.
Member::count_comments ()
Definition at line 685 of file member.entity.php.
References $id, RoxModelBase\bulkLookup(), and RoxEntityBase\isLoaded().
Referenced by ApiModel\getMemberData().
Member::count_mynotes ()
Definition at line 675 of file member.entity.php.
References $_SESSION, and RoxModelBase\singleLookup().
Member::findByUsername ($username)
attempts to load a member entity using username
Parameters
string $username - Username to search for public
Returns
object
Definition at line 1347 of file member.entity.php.
References $username, and RoxEntityBase\findByWhere().
Member::forums_posts_count ()
Definition at line 978 of file member.entity.php.
References RoxModelBase\createEntity().
Referenced by ApiModel\getMemberData().
Member::get_address () protected
Member address lookup TODO: Translate errors
Definition at line 888 of file member.entity.php.
References $address, $city, $cityName, $houseNumber, $id, $query, $region, $streetName, $zip, RoxModelBase\bulkLookup(), and RoxModelBase\createEntity().
Referenced by get_city(), get_country(), get_countrycode(), get_housenumber(), get_region(), get_regioncode(), get_street(), and get_zip().
Member::get_age ()
Definition at line 514 of file member.entity.php.
References $layoutbits.
Member::get_all_relations ()
Definition at line 1036 of file member.entity.php.
References $words, and RoxComponentBase\getWords().
Member::get_all_signed_languages ()
Get all available sign languages
Definition at line 184 of file member.entity.php.
Member::get_all_spoken_languages ()
Get all available spoken languages
Definition at line 177 of file member.entity.php.
Member::get_all_translatable_languages ()
Get all translatable languages
Definition at line 191 of file member.entity.php.
Referenced by getLanguagePreference().
Member::get_city ()
returns city
public
Returns
string
Definition at line 579 of file member.entity.php.
References get_address().
Member::get_comments ()
Definition at line 1139 of file member.entity.php.
References RoxModelBase\bulkLookup().
Member::get_comments_commenter ($id)
Definition at line 1170 of file member.entity.php.
References $id, and RoxModelBase\bulkLookup().
Member::get_comments_written ()
Fetches comments written by this member
Returns
array of objects
Definition at line 1202 of file member.entity.php.
References RoxModelBase\bulkLookup().
Member::get_country ()
returns country
public
Returns
string
Definition at line 605 of file member.entity.php.
References get_address().
Member::get_countrycode ()
returns countrycode
public
Returns
int
Definition at line 618 of file member.entity.php.
References get_address().
Member::get_crypted ($crypted_id, $return_value = "") protected
This needs to go someplace else, pending architectural attention
Definition at line 1308 of file member.entity.php.
References $right, MOD_crypt\AdminReadCrypted(), MOD_crypt\get_crypted(), and MOD_crypt\MemberReadCrypted().
Referenced by get_email(), get_firstname(), get_homephonenumber(), get_housenumber(), get_lastname(), get_messengers(), get_phone(), get_secondname(), get_street(), and get_zip().
Member::get_email ()
Get member's email address (uses various permission checks)
Returns
string Email address of member, empty if read permission denied
Definition at line 457 of file member.entity.php.
References get_crypted().
Member::get_firstname ()
Definition at line 441 of file member.entity.php.
References get_crypted().
Member::get_gender_for_public ()
Definition at line 526 of file member.entity.php.
Member::get_group_memberships ()
automatically called by __get('group_memberships'), when someone writes '$member->group_memberships'
Returns
unknown
Definition at line 878 of file member.entity.php.
Member::get_homephonenumber ()
Definition at line 398 of file member.entity.php.
References get_crypted().
Member::get_housenumber ()
returns 'unencrypted' housenumber
public
Returns
string
Definition at line 538 of file member.entity.php.
References get_address(), and get_crypted().
Member::get_language_levels ()
Get all possible levels of languages
Definition at line 227 of file member.entity.php.
References $table, and sql_get_enum().
Member::get_languages_spoken ()
Get languages spoken by member
Definition at line 137 of file member.entity.php.
Member::get_lastname ()
Definition at line 449 of file member.entity.php.
References get_crypted().
Member::get_messengers ()
Definition at line 469 of file member.entity.php.
References $address, $m, $messengers, RoxComponentBase\__get(), and get_crypted().
Referenced by ApiModel\getMemberData(), and hasMessengers().
Member::get_name ()
TODO: get name from crypted fields in an architecturally sane place (to be determined)
Definition at line 436 of file member.entity.php.
References $name.
Member::get_phone ()
Definition at line 387 of file member.entity.php.
References get_crypted().
Member::get_preferences ()
Definition at line 1065 of file member.entity.php.
Referenced by getPreference().
Member::get_profile_languages ()
Checks which languages profile has been translated into
Definition at line 126 of file member.entity.php.
References set_profile_languages().
Member::get_publicProfile ()
Get member's public profile
Returns
mixed Public profile entity or false if not public
Definition at line 407 of file member.entity.php.
References RoxModelBase\singleLookup().
Member::get_region ()
returns region
public
Returns
string
Definition at line 592 of file member.entity.php.
References get_address().
Member::get_regioncode ()
returns countrycode
public
Returns
int
Definition at line 632 of file member.entity.php.
References get_address().
Member::get_relations ()
Definition at line 1025 of file member.entity.php.
Member::get_secondname ()
Definition at line 445 of file member.entity.php.
References get_crypted().
Member::get_street ()
returns 'unencrypted' street
public
Returns
string
Definition at line 552 of file member.entity.php.
References get_address(), and get_crypted().
Member::get_TabRelationsType ()
Get all Restrictions for Accomodation
Definition at line 249 of file member.entity.php.
References sql_get_set().
Member::get_TabRestrictions ()
Get all Restrictions for Accomodation
Definition at line 239 of file member.entity.php.
References sql_get_set().
Member::get_TabTypicOffer ()
Get all Typical Offers possible
Definition at line 258 of file member.entity.php.
References sql_get_set().
Member::get_trad ($fieldname, $IdLanguage, $ReplaceWithBr = False)
Fetches translation of specific field in user profile. Initializes instance variable $trads if it hasn't been initialized already.
Parameters
fieldname name of the profile field
IdLanguage required translation
Returns
text of $fieldname if available, English otherwise, and empty string if field has no content
Definition at line 1239 of file member.entity.php.
References get_trad_by_tradid(), get_trads(), and IsFilled().
Referenced by ApiModel\getMemberData().
Member::get_trad_by_tradid ($IdTrad, $IdLanguage, $ReplaceWithBr = False)
Definition at line 1269 of file member.entity.php.
References $words, get_trads(), and RoxComponentBase\getWords().
Referenced by get_trad().
Member::get_trads () protected
automatically called by __get('trads'), when someone writes '$member->trads'
Returns
unknown
Definition at line 328 of file member.entity.php.
References $name, RoxModelBase\bulkLookup(), and get_trads_fields().
Referenced by get_trad(), and get_trad_by_tradid().
Member::get_trads_fields ()
Use to retrieve all the fields in members table which are a a foreign key to memberstrads This is typically neded when you want to delete a a given translation
Returns
unknown
Definition at line 277 of file member.entity.php.
Referenced by get_trads().
Member::get_userid ()
Get the member's TB user id
Definition at line 71 of file member.entity.php.
References RoxModelBase\singleLookup().
Referenced by getGalleryItemsCount().
Member::get_verification_status ()
Definition at line 987 of file member.entity.php.
References RoxModelBase\singleLookup().
Member::get_zip ()
returns 'unencrypted' zip
public
Returns
string
Definition at line 566 of file member.entity.php.
References get_address(), and get_crypted().
Member::getAllPostVotes ()
returns array of all post votes the member has cast
public
Returns
array
Definition at line 1494 of file member.entity.php.
References RoxModelBase\createEntity().
Member::getAllThreadVotes ()
returns array of all thread votes the member has cast
public
Returns
array
Definition at line 1505 of file member.entity.php.
References RoxModelBase\createEntity().
Member::getBlogs ()
return an array of blog entities that the member created
public
Returns
array
Definition at line 761 of file member.entity.php.
References $trip_data, and Username.
Member::getComingPosts ()
return an array of blog entities that have a start date that lies in the future
public
Returns
array
Definition at line 793 of file member.entity.php.
References RoxModelBase\createEntity().
Member::getEmailWithoutPermissionChecks ()
Get member's email address (no permission checks)
Returns
string|bool Email address of member, false on database error
Definition at line 465 of file member.entity.php.
References MOD_crypt\AdminReadCrypted().
Member::getFirstAddress ()
returns address entity for first address
public
Returns
Address
Definition at line 646 of file member.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Member::getGalleryItemsCount ()
Get number of gallery items
Todo:
Cache count to save database queries
Returns
integer Number of items
Definition at line 780 of file member.entity.php.
References $count, $gallery, and get_userid().
Referenced by ApiModel\getMemberData().
Member::getGroupMembership ($group)
finds a GroupMembership object for the member for a given group
Parameters
object $group - the Group to look for membership for public
Returns
object
Definition at line 1362 of file member.entity.php.
References RoxModelBase\createEntity().
Member::getGroups ()
return an array of group entities that the member is in
public
Returns
array
Definition at line 808 of file member.entity.php.
References RoxModelBase\createEntity().
Referenced by ApiModel\getMemberData().
Member::getLanguagePreference ()
Get language code from preferences.
Returns
string language ShortCode (2 to 5 letters), 'en' if no preference was found.
Definition at line 199 of file member.entity.php.
References $id, get_all_translatable_languages(), and getLanguagePreferenceId().
Member::getLanguagePreferenceId ()
Get language ID from preferences.
Returns
integer language ID, 0 if no preference was found.
Definition at line 220 of file member.entity.php.
References getPreference().
Referenced by getLanguagePreference().
Member::getNote ($for)
get_note gets the note for this member written by id
Parameters
id id of the member that wrote the note
Returns
ProfileNote entity or false
Definition at line 824 of file member.entity.php.
References $member, $note, and RoxModelBase\createEntity().
Member::getNoteCategories ()
returns an array of notes the member wrote
public
Returns
array
Definition at line 854 of file member.entity.php.
References $categories, $id, and RoxModelBase\bulkLookup().
Member::getNotes ()
returns an array of notes the member wrote
public
Returns
array
Definition at line 839 of file member.entity.php.
References RoxModelBase\createEntity().
Member::getOldRights ()
returns array of the old style rights
public
Returns
array
Definition at line 1618 of file member.entity.php.
References $query, and RoxEntityBase\isLoaded().
Member::getPossibleStatusArray ()
returns array of possible values for Status column
public
Returns
array
Definition at line 1771 of file member.entity.php.
Member::getPreference ($name, $default = false)
Get value of a user's preference.
Parameters
string $name codeName of preference.
string $default Default value of preference (if not set).
Returns
mixed Preference value, null or default if preference not set.
Definition at line 1096 of file member.entity.php.
References $name, $preference, $value, and get_preferences().
Referenced by getLanguagePreferenceId(), and recordVisit().
Member::getProfilePictureID ()
Should fetch male & female dummy pics when the member doesn't have any photos uploaded. membersphotos.id for those images = ??
Definition at line 1329 of file member.entity.php.
References $id, and RoxModelBase\singleLookup_assoc().
Member::getRoles ()
returns an array of roles for the member
public
Returns
array an array of role entities
Definition at line 1378 of file member.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isPKSet().
Referenced by hasPrivilege().
Member::getSignupFeedback ()
returns feedback entity matched to the users signup if the user left feedback then
public
Returns
Feedback
Definition at line 662 of file member.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Member::getTripsArray ()
return an array of trip entities that the member created
public
Returns
array
Definition at line 742 of file member.entity.php.
References $trip_data, and Username.
Referenced by ApiModel\getMemberData().
Member::getVisitorCount ()
returns count of profile visitors
public
Returns
int
Definition at line 1117 of file member.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Member::getVisitorsSubset (PagerWidget $pager)
returns array of members that have visited this profile
Parameters
PagerWidget $pager - pager containing details of visitor subset to fetch
public
Returns
array
Definition at line 1134 of file member.entity.php.
References RoxModelBase\createEntity().
Member::hasMessengers ()
checks if the member has set any addresses for messenger protocols
Author
Fake51 public
Returns
bool
Definition at line 498 of file member.entity.php.
References $m, and get_messengers().
Member::hasOldRight (array $rights)
checks if a member has a certain old-type right if member has one of the asked for rights returns true
Parameters
array $rights - array of right/scope pairs to check for
public
Returns
bool
Definition at line 1751 of file member.entity.php.
Member::hasPrivilege ($controller, $method = '*', $object = '*')
tests if a member has a given privilege, optionally for a given object if the object is not given, the test is for global privilege
Parameters
string $controller - the controller to test access for
string $method - the method to test access for. Default is global
mixed $object - an entity or '*' which signifies global public
Returns
bool
Definition at line 1421 of file member.entity.php.
References RoxModelBase\createEntity(), getRoles(), and RoxEntityBase\isLoaded().
Member::hasRole ($role, $object = false)
checks if member has a specific role assigned to it
Parameters
object $role - the role to check if the member has
object $object - object to check privilegescopes against public
Returns
bool
Definition at line 1396 of file member.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isPKSet().
Member::inactivateProfile ()
sets the profile as inactive
public
Returns
bool
Definition at line 1783 of file member.entity.php.
Member::init ($values, $dao)
Definition at line 62 of file member.entity.php.
References init().
Member::isActive ()
returns true if the member is Active or ActiveHidden
public
Returns
bool
Definition at line 1516 of file member.entity.php.
References RoxEntityBase\isLoaded().
Member::isBanned ()
returns true if the member is banned
public
Returns
bool
Definition at line 1559 of file member.entity.php.
References RoxEntityBase\isLoaded().
Member::isBrowsable ()
checks if the profile is displayable
public
Returns
bool
Definition at line 1837 of file member.entity.php.
Member::IsFilled ($fieldname)
Check if a property of a member is filled or not (ie: if the owner has filled something) for exemple if ->IsFilled("Hobbies") will return true if teh member has some Hobbies declared
Definition at line 268 of file member.entity.php.
Referenced by get_trad().
Member::isNotActiveHidden ()
returns true if the member is not in state ActiveHidden
public
Returns
bool
Definition at line 1531 of file member.entity.php.
References RoxEntityBase\isLoaded().
Member::isPending ()
returns true if the member is Pending
public
Returns
bool
Definition at line 1545 of file member.entity.php.
References RoxEntityBase\isLoaded().
Member::isPublic ()
Find out if member's profile is public
Returns
bool True if public, false if not
Definition at line 423 of file member.entity.php.
Referenced by ApiModel\getMemberData().
Member::logOut ()
logs a member out and deletes the session for the member
public
Returns
bool
old stuff from TB - we don't rely on this if (!isset($this->sessionName)) return false; if (!isset($_SESSION[$this->sessionName])) return false; $this->loggedIn = false; unset($_SESSION[$this->sessionName]);
Definition at line 1667 of file member.entity.php.
Member::recordVisit (Member $member)
Records visit of current member to another member's profile, respecting "Show profile visits" preference.
Parameters
Member $member Visiting member entity
Returns
bool True if visit recorded, false if not recorded
Definition at line 1575 of file member.entity.php.
References RoxModelBase\createEntity(), getPreference(), and RoxEntityBase\isLoaded().
Member::refreshMemoryCookie ($newsession = false)
Validates "stay logged in" tokens and refreshes them
Parameters
boolean $newsession, flag for a new session (no validation)
Returns
boolean true if cookie refreshed, false if cookie removed
Definition at line 1881 of file member.entity.php.
References removeSessionMemory().
Member::removeLanguages ()
deletes all a members languages
public
Returns
bool
Definition at line 1603 of file member.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Member::removeProfile ()
sets the profile as active
public
Returns
bool
Definition at line 1817 of file member.entity.php.
Member::removeSessionMemory ($seriesToken = '', $hijacked = false)
Removes "stay logged in" tokens and cookie
Parameters
boolean $hijacked, true if session was hijacked
Returns
boolean (always true)
Definition at line 1974 of file member.entity.php.
Referenced by refreshMemoryCookie().
Member::sendMail ($subject, $body)
Sends a mail to member's email address (i.e. for notifications).
Parameters
string $subject Email subject.
string $body Email body.
Definition at line 1856 of file member.entity.php.
Member::set_profile_languages () protected
automatically called by __get('trads'), when someone writes '$member->trads'
Returns
nothing but $this->profile_languages is set cave at : base on the existence of a ProfileSummary for the current member
Definition at line 310 of file member.entity.php.
References RoxModelBase\bulkLookup().
Referenced by get_profile_languages().
Member::setCryptedHouseNumber ($cryptId)
Set user's HouseNumber field in addresses table
Parameters
integer $cryptId ID of field in crypted table
Returns
boolean Result of database query execution
Definition at line 105 of file member.entity.php.
References $query.
Member::setCryptedStreetName ($cryptId)
Set user's StreetName field in addresses table
Parameters
integer $cryptId ID of field in crypted table
Returns
boolean Result of database query execution
Definition at line 116 of file member.entity.php.
References $query.
Member::setCryptedZip ($cryptId)
Set user's Zip field in addresses table
Parameters
integer $cryptId ID of field in crypted table
Returns
boolean Result of database query execution
Definition at line 94 of file member.entity.php.
References $query.
Member::setEditMode ($state = false)
Definition at line 1299 of file member.entity.php.
References $state.
Member::setPassword ($pw)
sets a new password for this member
Parameters
string $pw - new password as string
public
Returns
bool
Definition at line 1647 of file member.entity.php.
References $query, and RoxEntityBase\isLoaded().
Member::sql_get_enum ($table, $column)
Definition at line 1476 of file member.entity.php.
Referenced by get_language_levels().
Member::sql_get_set ($table, $column)
Definition at line 1462 of file member.entity.php.
Referenced by get_TabRelationsType(), get_TabRestrictions(), and get_TabTypicOffer().
Member::update_relation ($IdRelation, $IdTrad)
Definition at line 1008 of file member.entity.php.
Field Documentation
Member::$_table_name = 'members' protected
Definition at line 40 of file member.entity.php.
Member::$address = null
Definition at line 44 of file member.entity.php.
Referenced by get_address(), and get_messengers().
const Member::ACTIVE_ALL = "'Active', 'ActiveHidden', 'ChoiceInactive', 'OutOfRemind', 'Pending'"
Definition at line 37 of file member.entity.php.
Referenced by StatsModel\getLanguages(), StatsModel\getLastLoginRank(), StatsModel\getLastLoginRankGrouped(), StatsModel\getMembersPerCountry(), StatsModel\getPreferredLanguages(), Trip\getTrips(), Trip\getTripsForLocation(), and Trip\getTripsForUser().
const Member::ACTIVE_WITH_MESSAGES = "'Active', 'OutOfRemind', 'Pending'"
Definition at line 38 of file member.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/members/member.entity.php