Rox: BlogView Class Reference
BlogView Class Reference
Public Member Functions
__construct (Blog $model)
customStylesPublic ()
customStyles ()
linkRSS ($RSS=false)
teaserPublic ($userHandle)
teaser ($userHandle)
teaserquicksearch ()
submenu ($subTab)
createForm ()
editForm ($blogId, $callbackId)
blogText ($str, $stripAfterHR=true)
delete ($callbackId, $post)
allBlogs ($page=1)
pages ($pages, $currentPage, $maxPage, $request)
userPosts ($userHandle, $page=1)
PostsByCategory ($categoryId, $page=1)
stickyPosts ()
settingsForm ()
singlePost ($blog, $showComments=true)
searchPage ($posts=false, $tagsposts=false)
tags ($tag=false)
userbar ()
sidebarRSS ()
categories ()
categories_list ($categoryId, $username=false)
generateClickableTagSuggestions ($tags)
generateLocationOverview ($locations)
Public Member Functions inherited from RoxAppView
getAsString ($methodname)
Detailed Description
Definition at line 11 of file blog.view.php.
Constructor & Destructor Documentation
BlogView::__construct (Blog $model)
Definition at line 15 of file blog.view.php.
References $model.
Member Function Documentation
BlogView::allBlogs ($page = 1)
Displays Main blog/ page.
Definition at line 159 of file blog.view.php.
References $currentPage, $maxPage, $pages, and pages().
BlogView::blogText ($str, $stripAfterHR = true)
Definition at line 134 of file blog.view.php.
BlogView::categories ()
Definition at line 256 of file blog.view.php.
BlogView::categories_list ($categoryId, $username = false)
Definition at line 260 of file blog.view.php.
BlogView::createForm ()
Definition at line 54 of file blog.view.php.
References $Blog, $catIt, $errors, $google_conf, $i18n, $lang, $member, $monthNames, $request, $vars, and $words.
BlogView::customStyles ()
Definition at line 28 of file blog.view.php.
BlogView::customStylesPublic ()
Definition at line 22 of file blog.view.php.
BlogView::delete ($callbackId, $post)
Definition at line 151 of file blog.view.php.
BlogView::editForm ($blogId, $callbackId)
Definition at line 97 of file blog.view.php.
References $callbackId, $catIt, $errors, $google_conf, $i18n, $lang, $member, $monthNames, $request, $vars, and $words.
BlogView::generateClickableTagSuggestions ($tags)
Generate clickable Links to the suggested tags
Parameters
stringarray tags The new suggested tags to create the links from
Returns
Links to update the tag form
Definition at line 270 of file blog.view.php.
References $tags.
BlogView::generateLocationOverview ($locations)
Generate a list of the found locations
Parameters
locations The places to display
Returns
HTML-List of the locations
Definition at line 293 of file blog.view.php.
BlogView::linkRSS ($RSS = false)
Definition at line 33 of file blog.view.php.
References $request, and $requestStr.
BlogView::pages ($pages, $currentPage, $maxPage, $request)
Definition at line 171 of file blog.view.php.
Referenced by allBlogs(), PostsByCategory(), and userPosts().
BlogView::PostsByCategory ($categoryId, $page = 1)
Displays blog posts in a given category.
Definition at line 196 of file blog.view.php.
References $catIt, $currentPage, $maxPage, $pages, $title, and pages().
BlogView::searchPage ($posts = false, $tagsposts = false)
Definition at line 230 of file blog.view.php.
BlogView::settingsForm ()
Definition at line 219 of file blog.view.php.
BlogView::sidebarRSS ()
Definition at line 244 of file blog.view.php.
BlogView::singlePost ($blog, $showComments = true)
Displays a single blogt.
Definition at line 226 of file blog.view.php.
BlogView::stickyPosts ()
Definition at line 215 of file blog.view.php.
BlogView::submenu ($subTab)
Definition at line 48 of file blog.view.php.
BlogView::tags ($tag = false)
Definition at line 234 of file blog.view.php.
BlogView::teaser ($userHandle)
Definition at line 42 of file blog.view.php.
BlogView::teaserPublic ($userHandle)
Definition at line 39 of file blog.view.php.
BlogView::teaserquicksearch ()
Definition at line 45 of file blog.view.php.
BlogView::userbar ()
Definition at line 238 of file blog.view.php.
BlogView::userPosts ($userHandle, $page = 1)
Displays blogsite of given user.
Definition at line 179 of file blog.view.php.
References $currentPage, $maxPage, $member, $pages, and pages().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/blog/blog.view.php