Rox: APP_User Class Reference
APP_User Class Reference
Public Member Functions
__construct ()
__get ($name)
logout ()
getId ()
getHandle ()
removeCookie ()
setCookie ()
setLogout ()
isBWLoggedIn ($ExtraAllowedStatus="")
addGroup ($group)
addGroupRight ($group, $right)
addImplication ($right, $implies)
appExists ($appName)
checkAuth ($authName)
checkRight ($right, $level=0)
groupExists ($group)
hasRight ($right)
rightExists ($right)
getAuth ()
Static Public Member Functions
static activate ($userId)
static get ()
static addSetting ($userId, $setting, $value=null, $valueint=null, $valuedate=null)
static getAllSettings ($userId)
static getSetting ($userId, $setting)
static loggedIn ()
static login ($handle=false, $pw=false)
static userId ($handle)
static memberId ($handle)
static countryCode ($handle)
static passwordEncrypt ($password)
static randomString ($len)
static getTranslations ($idMember)
static getImage ($paramIdMember=0)
static getDummyImage ($Gender='IDontTell', $HideGender='Yes')
Protected Member Functions
doLogin ($handle, $password)
doBWLogin1 ($handle, $password)
setupBWSession ($handle)
updateUser ($handle, $password)
addApp ($name)
setAuth ($authId)
doBWLogin ($handle)
getAuthId ($userId)
Protected Attributes
$loggedIn = false
$authId
$sessionName
$tableName
$dao
Constructor & Destructor Documentation
APP_User::__construct ()
Parameters
void protected
References $_SESSION.
Member Function Documentation
APP_User::__get ($name)
References $name, and loggedIn().
static APP_User::activate ($userId) static
References $query.
Referenced by User\confirmRegister(), and SignupModel\confirmRegister().
MOD_user_Auth::addApp ($name) protected inherited
add a new application with given name
Parameters
string $name
Returns
int application ID
References $name, $query, and MOD_user_Auth\appExists().
Referenced by MOD_user_Auth\checkRight().
MOD_user_Auth::addGroup ($group) inherited
add a new group with given name
Parameters
string $group
Returns
int group ID
MOD_user_Auth::addGroupRight ($group, $right) inherited
adds a right to a group
if either is not set, this method will create group and right
Parameters
string $group group name
string $right right name
Returns
boolean
MOD_user_Auth::addImplication ($right, $implies) inherited
adds an implication for given right
Parameters
string $right right name, which implies
string $implies right name for right to imply
Returns
boolean
static APP_User::addSetting ($userId, $setting, $value = null, $valueint = null, $valuedate = null) static
Adds/changes a user setting
may be called statically
Parameters
int $userId
string $setting
string $value if "null", then a NULL field will be added
int $valueint if "null", then a NULL field will be added
int $valuedate UNIX timestamp - if "null", then a NULL field will be added
Returns
boolean
References $value, and value.
MOD_user_Auth::appExists ($appName) inherited
returns the id if app exists or false
Parameters
string $appName
Returns
mixed
Referenced by MOD_user_Auth\addApp().
MOD_user_Auth::checkAuth ($authName) inherited
check if given auth name exists, creates if it does not
Parameters
string $authName
Returns
mixed id or false
References $id, $query, and PException\addInfo().
Referenced by User\registerProcess().
MOD_user_Auth::checkRight ($right, $level = 0) inherited
checks if right exists
Parameters
string $right right name
int $level level
Returns
mixed id or false
References $query, $right, MOD_user_Auth\addApp(), and MOD_user_Auth\rightExists().
Referenced by MOD_user_Auth\hasRight().
static APP_User::countryCode ($handle) static
returns the country code for given handle
may be called statically
Parameters
string $handle
Returns
mixed String or false
References $d, and $query.
MOD_user::doBWLogin ($handle) protected inherited
References $_SESSION, $d, MOD_user\$sessionName, and MOD_user\setAuth().
Referenced by MOD_bw_user_Auth\doLogin().
MOD_bw_user_Auth::doBWLogin1 ($handle, $password) protected inherited
References $_SESSION, $m, $query, $Username, exit, false, and MOD_log\get().
MOD_bw_user_Auth::doLogin ($handle, $password) protected inherited
References MOD_user\doBWLogin(), exit, MOD_bw_user_Auth\isBWLoggedIn(), MOD_bw_user_Auth\logout(), MOD_bw_user_Auth\setupBWSession(), and MOD_bw_user_Auth\updateUser().
static APP_User::get () static
Referenced by User\logout(), and UserView\settingsForm().
static APP_User::getAllSettings ($userId) static
returns all existing user settings
this method returns a stdClass object, with the setting names in first level and each "value", "valueint", "valuedate" in second level may be called statically
Parameters
int $userId
Returns
stdClass
MOD_user::getAuth () inherited
Referenced by MOD_user\hasRight().
MOD_user::getAuthId ($userId) protected inherited
References MOD_user\$authId, and $d.
static MOD_user::getDummyImage ($Gender = 'IDontTell', $HideGender = 'Yes') static inherited
Returns the path to an appropriate dummy image in case no image is found.
Parameters
unknown_type $Gender
unknown_type $HideGender
Returns
unknown
APP_User::getHandle ()
returns the current handle
Parameters
void
Returns
string or false if not logged in
APP_User::getId ()
returns the current id
Parameters
void
Returns
int or false if not logged in
static MOD_user::getImage ($paramIdMember = 0) static inherited
References $_SESSION, and MOD_user\$dao.
static APP_User::getSetting ($userId, $setting) static
retrieves value(s) for one setting
may be called statically
Parameters
int $userId
string $setting
Returns
stdClass
Referenced by User\confirmRegister(), SignupModel\confirmRegister(), UserView\registerMail(), and SignupView\registerMail().
static MOD_user::getTranslations ($idMember) static inherited
References MOD_user\$dao.
MOD_user_Auth::groupExists ($group) inherited
checks if group exists
Parameters
string $group
Returns
mixed id or false
MOD_user_Auth::hasRight ($right) inherited
checks if current user has given right
Parameters
string $right
Returns
boolean
References $query, $right, MOD_user_Auth\checkRight(), and debug.
MOD_bw_user_Auth::isBWLoggedIn ($ExtraAllowedStatus = "") inherited
check if the user is a logged in member $ExtraAllowedStatus allows for a list, comma separated of extra status which can be allowed for members in addition to the basic Active and ActiveHidden members.Status this means that in the default case : (IsLoggedIn()) will return true only if the member has a session with an IdMember and a Status like Active or ActiveHidden in the extended cases (IsLoggedIn("Pending")) will also return true if the member has a a status set to Pending, this allow to give specific access to other members than the one with Active or ActiveHiddend Status
Returns
boolean
Referenced by MOD_bw_user_Auth\doLogin(), PageWithRoxLayout\getTopmenuItems(), InviteController\index(), ForumsController\index(), RoxController\index(), PageWithRoxLayout\quicksearch(), LinkSinglePictureLinkpathWidget\render(), and PageWithRoxLayout\topmenu().
static APP_User::loggedIn () static
returns a boolean value if logged in
may be called statically
Parameters
void
Returns
boolean
Referenced by __get(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), GroupsController\createGroupCallback(), InviteController\InviteCallback(), MessagesController\mailBoxCallback(), NotifyController\NotifyAdminCallback(), and MessagesController\sendMessageCallback().
static APP_User::login ($handle = false, $pw = false) static
login getter
returns either an instance of APP_User or false may be called statically
Parameters
string $handle
string $pw
Returns
mixed
Referenced by User\avatarProcess(), SignupFinishPage\column_col3(), SignupPage\column_col3(), Forums\createProcess(), Forums\delProcess(), Forums\editProcess(), User\find(), SignupModel\find(), OnlineModel\GetMembers(), LastCommentsController\index(), PollsController\index(), ShoutsController\index(), LinkController\index(), ForumsController\index(), UserController\index(), User\loginProcess(), Forums\ModeratorEditPostProcess(), Forums\ModeratorEditTagProcess(), MembersController\myPreferencesCallback(), Forums\replyProcess(), and Forums\reportpostProcess().
APP_User::logout ()
log the current user out
Parameters
void
Returns
boolean
static APP_User::memberId ($handle) static
returns the member id for given handle
may be called statically
Parameters
string $handle
Returns
mixed int or false
References $d, and $query.
static MOD_user::passwordEncrypt ($password) static inherited
Referenced by User\registerProcess(), and MOD_bw_user_Auth\updateUser().
static MOD_user::randomString ($len) static inherited
References $i.
APP_User::removeCookie ()
remove session login cookie
Parameters
void
Returns
boolean
MOD_user_Auth::rightExists ($right) inherited
checks if given right exists
Parameters
string $right
Returns
mixed id or false
References $query, $right, a, id, and r.
Referenced by MOD_user_Auth\checkRight().
MOD_user::setAuth ($authId) protected inherited
References MOD_user\$authId.
Referenced by MOD_user\doBWLogin(), and MOD_user\doLogin().
APP_User::setCookie ()
set session login cookie
Parameters
void
Returns
mixed either the session key or false
APP_User::setLogout ()
sets the loggedIn variable to false hack to be able to log out not using this class
Todo:
get rid of this whole class
MOD_bw_user_Auth::setupBWSession ($handle) protected inherited
References $_SESSION, $m, $query, MOD_log\get(), and MOD_bw_user_Auth\logout().
Referenced by MOD_bw_user_Auth\doLogin().
MOD_bw_user_Auth::updateUser ($handle, $password) protected inherited
References MOD_user\$authId, $query, and MOD_user\passwordEncrypt().
Referenced by MOD_bw_user_Auth\doLogin().
static APP_User::userId ($handle) static
returns the user id for given handle
may be called statically
Parameters
string $handle
Returns
mixed int or false
Referenced by User\confirmRegister(), SignupModel\confirmRegister(), and UserView\userPage().
Field Documentation
MOD_user::$authId protected inherited
Referenced by MOD_user_Auth\__construct(), MOD_bw_user_Auth\__construct(), MOD_user\getAuthId(), MOD_user\setAuth(), and MOD_bw_user_Auth\updateUser().
MOD_user::$dao protected inherited
Referenced by MOD_user\__construct(), MOD_user\getImage(), and MOD_user\getTranslations().
APP_User::$loggedIn = false protected
MOD_user::$sessionName protected inherited
Referenced by MOD_user\__construct(), MOD_user_Auth\__construct(), MOD_bw_user_Auth\__construct(), MOD_user\doBWLogin(), and MOD_user\doLogin().
MOD_user::$tableName protected inherited
Referenced by MOD_user\__construct(), MOD_user_Auth\__construct(), and MOD_bw_user_Auth\__construct().
The documentation for this class was generated from the following file:
build/user/lib/user.lib.php