Rox: MOD_bw_user_Auth Class Reference
MOD_bw_user_Auth Class Reference
Public Member Functions
__construct ($sessionName=false, $tableName=false, $authId=false)
isBWLoggedIn ($ExtraAllowedStatus="")
logout ()
Public Member Functions inherited from MOD_user_Auth
__construct ($sessionName=false, $tableName=false, $authId=false)
addGroup ($group)
addGroupRight ($group, $right)
addImplication ($right, $implies)
appExists ($appName)
checkAuth ($authName)
checkRight ($right, $level=0)
groupExists ($group)
hasRight ($right)
rightExists ($right)
Public Member Functions inherited from MOD_user
__destruct ()
getAuth ()
hasRight ($right)
logout ()
Protected Member Functions
doLogin ($handle, $password)
doBWLogin1 ($handle, $password)
setupBWSession ($handle)
updateUser ($handle, $password)
Protected Member Functions inherited from MOD_user_Auth
addApp ($name)
Protected Member Functions inherited from MOD_user
__construct ($sessionName=false, $tableName=false)
setAuth ($authId)
doLogin ($handle, $pw)
doBWLogin ($handle)
getAuthId ($userId)
Additional Inherited Members
Static Public Member Functions inherited from MOD_user
static passwordEncrypt ($password)
static randomString ($len)
static getTranslations ($idMember)
static getImage ($paramIdMember=0)
static getDummyImage ($Gender='IDontTell', $HideGender='Yes')
Protected Attributes inherited from MOD_user
$authId
$sessionName
$tableName
$dao
Detailed Description
Definition at line 27 of file bwauth.lib.php.
Constructor & Destructor Documentation
MOD_bw_user_Auth::__construct ($sessionName = false, $tableName = false, $authId = false)
Parameters
string $sessionName The session key under which the user id may be found
string $tableName The user table name
int $authId The authentication id
Definition at line 36 of file bwauth.lib.php.
References MOD_user\$authId, MOD_user\$sessionName, and MOD_user\$tableName.
Member Function Documentation
MOD_bw_user_Auth::doBWLogin1 ($handle, $password) protected
Definition at line 91 of file bwauth.lib.php.
References $_SESSION, $m, $query, $Username, break, exit, false, and MOD_log\get().
MOD_bw_user_Auth::doLogin ($handle, $password) protected
Definition at line 42 of file bwauth.lib.php.
References MOD_user\doBWLogin(), exit, isBWLoggedIn(), logout(), setupBWSession(), and updateUser().
MOD_bw_user_Auth::isBWLoggedIn ($ExtraAllowedStatus = "")
check if the user is a logged in member $ExtraAllowedStatus allows for a list, comma separated of extra status which can be allowed for members in addition to the basic Active and ActiveHidden members.Status this means that in the default case : (IsLoggedIn()) will return true only if the member has a session with an IdMember and a Status like Active or ActiveHidden in the extended cases (IsLoggedIn("Pending")) will also return true if the member has a a status set to Pending, this allow to give specific access to other members than the one with Active or ActiveHiddend Status
Returns
boolean
Definition at line 314 of file bwauth.lib.php.
Referenced by doLogin(), PageWithRoxLayout\getTopmenuItems(), InviteController\index(), ForumsController\index(), RoxController\index(), PageWithRoxLayout\quicksearch(), LinkSinglePictureLinkpathWidget\render(), and PageWithRoxLayout\topmenu().
MOD_bw_user_Auth::logout ()
Definition at line 363 of file bwauth.lib.php.
Referenced by doLogin(), and setupBWSession().
MOD_bw_user_Auth::setupBWSession ($handle) protected
Definition at line 210 of file bwauth.lib.php.
References $_SESSION, $m, $query, MOD_log\get(), and logout().
Referenced by doLogin().
MOD_bw_user_Auth::updateUser ($handle, $password) protected
Definition at line 270 of file bwauth.lib.php.
References MOD_user\$authId, $query, and MOD_user\passwordEncrypt().
Referenced by doLogin().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/user/lib/bwauth.lib.php