Rox: SimplePie_Misc Class Reference
SimplePie_Misc Class Reference
Static Public Member Functions
static time_hms ($seconds)
static absolutize_url ($relative, $base)
static get_element ($realname, $string)
static element_implode ($element)
static error ($message, $level, $file, $line)
static fix_protocol ($url, $http=1)
static parse_url ($url)
static compress_parse_url ($scheme= '', $authority= '', $path= '', $query= '', $fragment= '')
static normalize_url ($url)
static percent_encoding_normalization ($match)
static windows_1252_to_utf8 ($string)
static change_encoding ($data, $input, $output)
static encoding ($charset)
static get_curl_version ()
static strip_comments ($data)
static parse_date ($dt)
static entities_decode ($data)
static uncomment_rfc822 ($string)
static parse_mime ($mime)
static atom_03_construct_type ($attribs)
static atom_10_construct_type ($attribs)
static atom_10_content_construct_type ($attribs)
static is_isegment_nz_nc ($string)
static space_seperated_tokens ($string)
static codepoint_to_utf8 ($codepoint)
static parse_str ($str)
static xml_encoding ($data, $registry)
static output_javascript ()
static get_build ()
static debug (&$sp)
static silence_errors ($num, $str)
Static Protected Member Functions
static change_encoding_mbstring ($data, $input, $output)
static change_encoding_iconv ($data, $input, $output)
Detailed Description
Definition at line 50 of file Misc.php.
Member Function Documentation
static SimplePie_Misc::absolutize_url ($relative, $base) static
Definition at line 80 of file Misc.php.
References SimplePie_IRI\absolutize().
Referenced by SimplePie_File\__construct().
static SimplePie_Misc::atom_03_construct_type ($attribs) static
Definition at line 1831 of file Misc.php.
References SIMPLEPIE_CONSTRUCT_BASE64, SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_NONE, SIMPLEPIE_CONSTRUCT_TEXT, and SIMPLEPIE_CONSTRUCT_XHTML.
static SimplePie_Misc::atom_10_construct_type ($attribs) static
Definition at line 1867 of file Misc.php.
References SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_NONE, SIMPLEPIE_CONSTRUCT_TEXT, and SIMPLEPIE_CONSTRUCT_XHTML.
static SimplePie_Misc::atom_10_content_construct_type ($attribs) static
Definition at line 1889 of file Misc.php.
References $type, SIMPLEPIE_CONSTRUCT_BASE64, SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_NONE, SIMPLEPIE_CONSTRUCT_TEXT, and SIMPLEPIE_CONSTRUCT_XHTML.
static SimplePie_Misc::change_encoding ($data, $input, $output) static
Change a string from one encoding to another
Parameters
string $data Raw data in $input encoding
string $input Encoding of $data
string $output Encoding you want
Returns
string|boolean False if we can't convert it
Definition at line 287 of file Misc.php.
References $data, $i, change_encoding_iconv(), change_encoding_mbstring(), elseif, encoding(), and windows_1252_to_utf8().
Referenced by xml_encoding().
static SimplePie_Misc::change_encoding_iconv ($data, $input, $output) static protected
Definition at line 366 of file Misc.php.
References $data.
Referenced by change_encoding().
static SimplePie_Misc::change_encoding_mbstring ($data, $input, $output) static protected
Definition at line 328 of file Misc.php.
References $data.
Referenced by change_encoding().
static SimplePie_Misc::codepoint_to_utf8 ($codepoint) static
Converts a unicode codepoint to a UTF-8 character
Parameters
int $codepoint Unicode codepoint
Returns
string UTF-8 character
Definition at line 1951 of file Misc.php.
Referenced by SimplePie_Decode_HTML_Entities\entity().
static SimplePie_Misc::compress_parse_url ($scheme = '', $authority = '', $path = '', $query = '', $fragment = '') static
Definition at line 235 of file Misc.php.
References $query.
Referenced by SimplePie_File\__construct(), SimplePie_Enclosure\__construct(), and fix_protocol().
static SimplePie_Misc::debug (& $sp) static
Format debugging information
Definition at line 2191 of file Misc.php.
References $info, $version, SIMPLEPIE_BUILD, and SIMPLEPIE_VERSION.
static SimplePie_Misc::element_implode ($element) static
Definition at line 131 of file Misc.php.
References $value.
static SimplePie_Misc::encoding ($charset) static
Normalize an encoding name
This is automatically generated by create.php
To generate it, run php create.php on the command line, and copy the output to replace this function.
Parameters
string $charset Character set to standardise
Returns
string Standardised name
Definition at line 382 of file Misc.php.
Referenced by change_encoding().
static SimplePie_Misc::entities_decode ($data) static
Decode HTML entities
Deprecated:
Use DOMDocument instead
Parameters
string $data Input data
Returns
string Output data
Definition at line 1753 of file Misc.php.
References $data.
Referenced by get_element().
static SimplePie_Misc::error ($message, $level, $file, $line) static
Definition at line 150 of file Misc.php.
References $note.
static SimplePie_Misc::fix_protocol ($url, $http = 1) static
Definition at line 191 of file Misc.php.
References $url, compress_parse_url(), elseif, normalize_url(), and parse_url().
static SimplePie_Misc::get_build () static
Get the SimplePie build timestamp
Uses the git index if it exists, otherwise uses the modification time of the newest file.
Definition at line 2159 of file Misc.php.
References $mtime, and elseif.
static SimplePie_Misc::get_curl_version () static
Definition at line 1695 of file Misc.php.
References elseif.
Referenced by SimplePie_File\__construct().
static SimplePie_Misc::get_element ($realname, $string) static
Get a HTML/XML element from a HTML string
Deprecated:
Use DOMDocument instead (parsing HTML with regex is bad!)
Parameters
string $realname Element name (including namespace prefix if applicable)
string $string HTML document
Returns
array
Definition at line 94 of file Misc.php.
References $i, $matches, $name, entities_decode(), and SIMPLEPIE_PCRE_HTML_ATTRIBUTE.
static SimplePie_Misc::is_isegment_nz_nc ($string) static
Definition at line 1920 of file Misc.php.
static SimplePie_Misc::normalize_url ($url) static
Definition at line 246 of file Misc.php.
References $url.
Referenced by fix_protocol().
static SimplePie_Misc::output_javascript () static
Definition at line 2120 of file Misc.php.
References height.
static SimplePie_Misc::parse_date ($dt) static
Definition at line 1740 of file Misc.php.
References SimplePie_Parse_Date\get().
static SimplePie_Misc::parse_mime ($mime) static
Definition at line 1819 of file Misc.php.
static SimplePie_Misc::parse_str ($str) static
Similar to parse_str()
Returns an associative array of name/value pairs, where the value is an array of values that have used the same name
Parameters
string $str The input string.
Returns
array
Definition at line 1991 of file Misc.php.
References $name, and $value.
static SimplePie_Misc::parse_url ($url) static
Definition at line 223 of file Misc.php.
References $url.
Referenced by SimplePie_File\__construct(), SimplePie_Enclosure\__construct(), fix_protocol(), and SimplePie_Enclosure\get_extension().
static SimplePie_Misc::percent_encoding_normalization ($match) static
Definition at line 252 of file Misc.php.
static SimplePie_Misc::silence_errors ($num, $str) static
Definition at line 2238 of file Misc.php.
static SimplePie_Misc::space_seperated_tokens ($string) static
Definition at line 1925 of file Misc.php.
static SimplePie_Misc::strip_comments ($data) static
Strip HTML comments
Parameters
string $data Data to strip comments from
Returns
string Comment stripped string
Definition at line 1722 of file Misc.php.
References $data.
static SimplePie_Misc::time_hms ($seconds) static
Definition at line 52 of file Misc.php.
Referenced by SimplePie_Enclosure\get_duration().
static SimplePie_Misc::uncomment_rfc822 ($string) static
Remove RFC822 comments
Parameters
string $data Data to strip comments from
Returns
string Comment stripped string
Definition at line 1765 of file Misc.php.
References elseif.
static SimplePie_Misc::windows_1252_to_utf8 ($string) static
Converts a Windows-1252 encoded string to a UTF-8 encoded string
Parameters
string $string Windows-1252 encoded string
Returns
string UTF-8 encoded string
Definition at line 272 of file Misc.php.
Referenced by change_encoding().
static SimplePie_Misc::xml_encoding ($data, $registry) static
Detect XML encoding, as per XML 1.0 Appendix F.1
Todo:
Add support for EBCDIC
Parameters
string $data XML data
SimplePie_Registry $registry Class registry
Returns
array Possible encodings
Definition at line 2020 of file Misc.php.
References $data, change_encoding(), and elseif.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/templates/simplepie/library/SimplePie/Misc.php