Rox: PageWithHTML Class Reference
PageWithHTML Class Reference
Public Member Functions
render ()
addWidget (RoxWidget $widget)
Public Member Functions inherited from AbstractBasePage
setModel ($model)
createWidget ($classname)
render ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
init ()
getCustomElements ()
getStylesheets ()
getStylesheetPatches ()
getScriptfiles ()
getLateLoadScriptfiles ()
addEarlyLoadScriptFile ($file)
addLateLoadScriptFile ($file)
getPageTitle ()
printHTML ()
includeStylesheets ()
includeCustomElements ()
includeJsConfig ()
includeScriptfiles ()
includeLateScriptfiles ()
head ()
getPagePermalink ()
statusMessage ()
Protected Member Functions inherited from AbstractBasePage
getModel ()
showTemplate ($rel_path, $args=array())
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 4 of file html.page.php.
Member Function Documentation
PageWithHTML::addEarlyLoadScriptFile ($file) protected
registers a script for early loading
Parameters
string $file - js file to early load
protected
Returns
void
Definition at line 106 of file html.page.php.
PageWithHTML::addLateLoadScriptFile ($file) protected
registers a script for late loading
Parameters
string $file - js file to early load
protected
Returns
void
Definition at line 119 of file html.page.php.
PageWithHTML::addWidget (RoxWidget $widget)
Widgets added this way will be asked for stylesheet and scriptfile information TODO: evtl not a good idea to do it this way.
Parameters
RoxWidget $widget
Definition at line 136 of file html.page.php.
PageWithHTML::getCustomElements () protected
skeleton method of getCustomElements
protected
Returns
array
Definition at line 36 of file html.page.php.
Referenced by includeCustomElements().
PageWithHTML::getLateLoadScriptfiles () protected
returns all registered late load scripts these are the scripts to be loaded at the end of the page
protected
Returns
array
Definition at line 93 of file html.page.php.
Referenced by includeLateScriptfiles().
PageWithHTML::getPagePermalink () protected
Definition at line 288 of file html.page.php.
PageWithHTML::getPageTitle () protected
Definition at line 124 of file html.page.php.
Referenced by head().
PageWithHTML::getScriptfiles () protected
returns all registered early load scripts these are the scripts to be loaded in the html head element
protected
Returns
array
Definition at line 75 of file html.page.php.
Referenced by includeScriptfiles().
PageWithHTML::getStylesheetPatches () protected
Definition at line 57 of file html.page.php.
Referenced by includeStylesheets().
PageWithHTML::getStylesheets () protected
don't forget to call $stylesheets = parent::$this->getStylesheets(); when reimplementing this method!!
Definition at line 46 of file html.page.php.
Referenced by includeStylesheets().
PageWithHTML::head () protected
Definition at line 271 of file html.page.php.
References $baseuri, getPageTitle(), RoxComponentBase\getWords(), includeCustomElements(), includeStylesheets(), and title.
Referenced by printHTML().
PageWithHTML::includeCustomElements () protected
allows for outputting custom elements in the page <head> element
protected
Definition at line 205 of file html.page.php.
References getCustomElements().
Referenced by head().
PageWithHTML::includeJsConfig () protected
Inserts JavaScript configuration.
Reads [javascript] section in rox.ini and makes it available via bwroxConfig object in JavaScript.
Definition at line 222 of file html.page.php.
References $value.
Referenced by printHTML().
PageWithHTML::includeLateScriptfiles () protected
outputs script tags that include script files called at the end of pages
protected
Returns
void
Definition at line 260 of file html.page.php.
References $url, and getLateLoadScriptfiles().
Referenced by printHTML().
PageWithHTML::includeScriptfiles () protected
Definition at line 240 of file html.page.php.
References $url, and getScriptfiles().
Referenced by printHTML().
PageWithHTML::includeStylesheets () protected
Definition at line 181 of file html.page.php.
References $url, endif, getStylesheetPatches(), and getStylesheets().
Referenced by head().
PageWithHTML::init () protected
Definition at line 24 of file html.page.php.
Referenced by render().
PageWithHTML::printHTML () protected
Definition at line 142 of file html.page.php.
References head(), includeJsConfig(), includeLateScriptfiles(), includeScriptfiles(), layoutkit, and v.
Referenced by render().
PageWithHTML::render ()
Definition at line 17 of file html.page.php.
References init(), and printHTML().
PageWithHTML::statusMessage () protected
Definition at line 292 of file html.page.php.
References $_SESSION, $class, and $words.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/page/html.page.php