Rox: GeoController Class Reference
GeoController Class Reference
Public Member Functions
__construct ()
__destruct ()
index ()
AdminCallback ($args, $action, $mem_redirect, $mem_resend)
SelectorInclude ($formvars=false)
SelectorCallback ($args, $action, $mem_redirect, $mem_resend)
GeoSearch ($search, $number, $js=true, $callbacktag=false)
Detailed Description
Definition at line 32 of file geo.ctrl.php.
Constructor & Destructor Documentation
GeoController::__construct ()
Definition at line 45 of file geo.ctrl.php.
GeoController::__destruct ()
Definition at line 52 of file geo.ctrl.php.
Member Function Documentation
GeoController::AdminCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 166 of file geo.ctrl.php.
References $action, $mem_redirect, and MOD_geonames\get().
GeoController::GeoSearch ($search, $number, $js = true, $callbacktag = false)
Definition at line 244 of file geo.ctrl.php.
References $callbacktag, $locations, $number, and $search.
GeoController::index ()
The index function is called by /htdocs/index.php, if your URL looks like this: http://[fqdn]/geo/... ... and by this is the entry point to your application.
Parameters
void
Definition at line 64 of file geo.ctrl.php.
References $locations, $matches, $Page, $R, $request, $type, exit, MOD_geonames\get(), and MOD_right\get().
GeoController::SelectorCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 231 of file geo.ctrl.php.
References $_SESSION, $mem_redirect, and $value.
GeoController::SelectorInclude ($formvars = false)
Definition at line 193 of file geo.ctrl.php.
References $callbacktag, $Geo, $mem_redirect, $page_url, $value, $words, elseif, RoxComponentBase\getWords(), and layoutkit.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/geo/geo.ctrl.php