Rox: GalleryModel Class Reference
GalleryModel Class Reference
Public Member Functions
__construct ()
createGallery ($title, $desc=false)
bootstrap ()
deleteAll ()
deleteOneProcess ($image)
editProcess ($vars)
ajaxModImage ($id, $title=false, $text=false)
reorderTripItems ($items)
ajaxModGallery ($id, $title=false, $text=false)
editGalleryProcess ($vars)
deleteMultiple ($images)
deleteComments ($table_id, $table= 'gallery_items')
updateGalleryProcess ($vars=null)
deleteGalleryProcess ($galleryId)
getGallery ($galleryId)
getGalleryItems ($galleryId, $count=false)
getLatestGalleryItem ($galleryId)
getItemGallery ($imageId)
getUserGalleries ($UserId=false)
getUserItemCount ($userId)
getGalleriesNotEmpty ($UserId=false, $publicOnly=false)
getGalleriesNotEmptyEntities ()
getMemberWithUserId ($userId)
getLatestItems ($userId=false, $galleryId=false, $numRows=false, $publicOnly=false)
getNextItems ($imageId, $limit=1, $userId=false, $galleryId=false)
getPreviousItems ($imageId, $limit=1, $userId=false, $galleryId=false)
getNextGalleryItems ($imageId, $limit=1, $galleryId=false)
getPreviousGalleryItems ($imageId, $limit=1, $galleryId=false)
imageData ($itemId)
imageOwner ($imageId)
galleryOwner ($galleryId)
uploadProcess (&$vars)
createThumbnails ($dataDir, $img)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const FLAG_VIEW_PRIVATE = 1
const FLAG_VIEW_PROTECTED = 2
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 11 of file gallery.model.php.
Constructor & Destructor Documentation
GalleryModel::__construct ()
Definition at line 16 of file gallery.model.php.
References bootstrap().
Member Function Documentation
GalleryModel::ajaxModGallery ($id, $title = false, $text = false)
Definition at line 117 of file gallery.model.php.
GalleryModel::ajaxModImage ($id, $title = false, $text = false)
Definition at line 94 of file gallery.model.php.
GalleryModel::bootstrap ()
Definition at line 39 of file gallery.model.php.
Referenced by __construct().
GalleryModel::createGallery ($title, $desc = false)
Definition at line 21 of file gallery.model.php.
References $desc, $member, $query, $title, and RoxModelBase\getLoggedInMember().
GalleryModel::createThumbnails ($dataDir, $img)
Definition at line 726 of file gallery.model.php.
References false.
Referenced by uploadProcess().
GalleryModel::deleteAll ()
Definition at line 44 of file gallery.model.php.
GalleryModel::deleteComments ($table_id, $table = 'gallery_items')
Definition at line 164 of file gallery.model.php.
GalleryModel::deleteGalleryProcess ($galleryId)
Definition at line 204 of file gallery.model.php.
GalleryModel::deleteMultiple ($images)
Definition at line 135 of file gallery.model.php.
GalleryModel::deleteOneProcess ($image)
Definition at line 55 of file gallery.model.php.
GalleryModel::editGalleryProcess ($vars)
Definition at line 128 of file gallery.model.php.
GalleryModel::editProcess ($vars)
Definition at line 77 of file gallery.model.php.
GalleryModel::galleryOwner ($galleryId)
Definition at line 607 of file gallery.model.php.
References $galleryId, and $query.
GalleryModel::getGalleriesNotEmpty ($UserId = false, $publicOnly = false)
Definition at line 319 of file gallery.model.php.
GalleryModel::getGalleriesNotEmptyEntities ()
Definition at line 366 of file gallery.model.php.
References RoxModelBase\createEntity(), and g.
GalleryModel::getGallery ($galleryId)
returns a single gallery entity
Parameters
int $galleryId - id of gallery to fetch
public
Returns
Gallery|false
Definition at line 230 of file gallery.model.php.
GalleryModel::getGalleryItems ($galleryId, $count = false)
Definition at line 235 of file gallery.model.php.
GalleryModel::getItemGallery ($imageId)
Definition at line 267 of file gallery.model.php.
GalleryModel::getLatestGalleryItem ($galleryId)
Definition at line 251 of file gallery.model.php.
GalleryModel::getLatestItems ($userId = false, $galleryId = false, $numRows = false, $publicOnly = false)
Definition at line 401 of file gallery.model.php.
References $galleryId, and $query.
GalleryModel::getMemberWithUserId ($userId)
Definition at line 391 of file gallery.model.php.
References RoxModelBase\createEntity(), and RoxModelBase\singleLookup().
GalleryModel::getNextGalleryItems ($imageId, $limit = 1, $galleryId = false)
Definition at line 526 of file gallery.model.php.
References $galleryId, and $query.
GalleryModel::getNextItems ($imageId, $limit = 1, $userId = false, $galleryId = false)
Definition at line 458 of file gallery.model.php.
References $query, and if.
GalleryModel::getPreviousGalleryItems ($imageId, $limit = 1, $galleryId = false)
Definition at line 543 of file gallery.model.php.
References $galleryId, and $query.
GalleryModel::getPreviousItems ($imageId, $limit = 1, $userId = false, $galleryId = false)
Definition at line 492 of file gallery.model.php.
References $query, and if.
GalleryModel::getUserGalleries ($UserId = false)
Definition at line 282 of file gallery.model.php.
GalleryModel::getUserItemCount ($userId)
Gets number of gallery items for a user
Parameters
integer $userId Travelbook user ID
Returns
integer
Definition at line 307 of file gallery.model.php.
GalleryModel::imageData ($itemId)
Definition at line 560 of file gallery.model.php.
References $d, and $query.
GalleryModel::imageOwner ($imageId)
Definition at line 592 of file gallery.model.php.
References $query.
GalleryModel::reorderTripItems ($items)
Definition at line 105 of file gallery.model.php.
GalleryModel::updateGalleryProcess ($vars = null)
Definition at line 169 of file gallery.model.php.
GalleryModel::uploadProcess (& $vars)
processing image uploads
Todo:
sizes should be customizable
Definition at line 628 of file gallery.model.php.
References $error, $member, $title, $type, $vars, $width, PException\__toString(), createThumbnails(), elseif, and RoxModelBase\getLoggedInMember().
Field Documentation
const GalleryModel::FLAG_VIEW_PRIVATE = 1
Definition at line 13 of file gallery.model.php.
const GalleryModel::FLAG_VIEW_PROTECTED = 2
Definition at line 14 of file gallery.model.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/gallery/gallery.model.php