Rox: VolunteerBoard Class Reference
VolunteerBoard Class Reference
Public Member Functions
__construct ($id=null)
findByName ($name)
updateText ($text, Member $member)
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Attributes
$_table_name = 'volunteer_boards'
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Data Fields inherited from RoxEntityBase
$sql_order = ''
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 3 of file volunteerboard.entity.php.
Constructor & Destructor Documentation
VolunteerBoard::__construct ($id = null)
Definition at line 7 of file volunteerboard.entity.php.
References $id, and RoxEntityBase\findById().
Member Function Documentation
VolunteerBoard::findByName ($name)
fetches a board by name
Parameters
string $name - name of board
public
Returns
false|VolunteerBoard
Definition at line 24 of file volunteerboard.entity.php.
References RoxEntityBase\findByWhere().
VolunteerBoard::updateText ($text, Member $member)
updates the text of the board
Parameters
string $text
Member $member public
Returns
bool
Definition at line 38 of file volunteerboard.entity.php.
References RoxEntityBase\update().
Field Documentation
VolunteerBoard::$_table_name = 'volunteer_boards' protected
Definition at line 5 of file volunteerboard.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/volunteerboard.entity.php