Rox: ItemlistWidget Class Reference
ItemlistWidget Class Reference
Public Member Functions
render ()
__call ($methodname, $args)
Public Member Functions inherited from RoxWidget
__construct ()
render ()
getStylesheets ()
getScriptfiles ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
showItems ()
showItems_table ()
showItems_float ()
showItems_list ()
showBetweenListItems ($prev_item, $item, $i_row)
showListItem ($item, $i_row)
getItems ()
hideColumnTitles ()
Protected Member Functions inherited from RoxWidget
createEntity ()
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxWidget
$_entity_factory
Detailed Description
Definition at line 4 of file itemlist.widget.php.
Member Function Documentation
ItemlistWidget::__call ($methodname, $args)
Definition at line 11 of file itemlist.widget.php.
ItemlistWidget::getItems () protected
Definition at line 163 of file itemlist.widget.php.
References $items.
Referenced by showItems_float(), showItems_list(), and showItems_table().
ItemlistWidget::hideColumnTitles () protected
Definition at line 170 of file itemlist.widget.php.
Referenced by showItems_float(), and showItems_table().
ItemlistWidget::render ()
Definition at line 6 of file itemlist.widget.php.
References showItems().
ItemlistWidget::showBetweenListItems ($prev_item, $item, $i_row) protected
Definition at line 143 of file itemlist.widget.php.
Referenced by showItems_list().
ItemlistWidget::showItems () protected
Definition at line 23 of file itemlist.widget.php.
References showItems_table().
Referenced by render().
ItemlistWidget::showItems_float () protected
Definition at line 70 of file itemlist.widget.php.
References $items, $value, getItems(), and hideColumnTitles().
ItemlistWidget::showItems_list () protected
Definition at line 107 of file itemlist.widget.php.
References $items, getItems(), showBetweenListItems(), and showListItem().
Referenced by MailboxWidget_Personalstart\showItems().
ItemlistWidget::showItems_table () protected
Definition at line 29 of file itemlist.widget.php.
References $items, $value, getItems(), and hideColumnTitles().
Referenced by showItems().
ItemlistWidget::showListItem ($item, $i_row) protected
Override this method to get a different presentation
Parameters
unknown_type $item - the item for this row of the list
Definition at line 154 of file itemlist.widget.php.
Referenced by showItems_list().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/widget/itemlist.widget.php