Rox: MOD_crypt Class Reference
MOD_crypt Class Reference
Public Member Functions
__construct ()
IsCrypted ($IdCrypt)
Static Public Member Functions
static get ()
static enc ($function, $ss)
static getall_crypted ($IdCrypt, $return_value)
static get_crypted ($IdCrypt, $return_value)
static insertCrypted ($ss, $TableColumn, $IdRecord, $IdMember=false, $IsCrypted="crypted")
static MemberCrypt ($IdCrypt)
static MemberDeCrypt ($IdCrypt=false)
static AdminReadCrypted ($IdCrypt=false)
static MemberReadCrypted ($IdCrypt)
static ReverseCrypt ($IdCrypt)
static NewReplaceInCrypted ($ss, $TableColumn, $IdRecord, $IdCrypt, $IdMember=false, $IsCrypted="crypted")
static IsCryptedValue ($IdCrypt)
Detailed Description
Build an array with the last visits on the member IdMember assumed it is the currently logged member if no IdMember is provided
Author
Philipp Lange
Constructor & Destructor Documentation
MOD_crypt::__construct ()
Member Function Documentation
static MOD_crypt::AdminReadCrypted ($IdCrypt = false) static
AdminReadCrypted Reads the crypted fields
Referenced by Member\get_crypted(), Member\getEmailWithoutPermissionChecks(), VerifyMembersModel\LoadPrivateData(), and MembersModel\updateProfile().
static MOD_crypt::enc ($function, $ss) static
singleton getter
Parameters
void
Returns
PApps
References CryptA(), CryptM(), DeCryptA(), and DeCryptM().
static MOD_crypt::get () static
singleton getter
Parameters
void
Returns
PApps
static MOD_crypt::get_crypted ($IdCrypt, $return_value) static
get_crypted
Equals the old BW style function "PublicReadCrypted" Get a decrypted value for a given crypted_id
References $ww.
Referenced by Member\get_crypted().
static MOD_crypt::getall_crypted ($IdCrypt, $return_value) static
getall_crypted
Equals the old BW style function "PublicReadCrypted" Get a decrypted value for a given crypted_id
References $_SESSION.
static MOD_crypt::insertCrypted ($ss, $TableColumn, $IdRecord, $IdMember = false, $IsCrypted = "crypted") static
insertCrypted
Parameters
$TableComumn must be something like "members.ProfileSummary"
$Idrecord is the id of the record in the corresponding $TableColumn, it's not normalized but needed for mainteance
Returns
insertId()
References $_SESSION, and $query.
MOD_crypt::IsCrypted ($IdCrypt)
IsCrypted Get a decrypted value for a given crypted_id
Referenced by EditProfilePage\editMyProfileFormPrepare().
static MOD_crypt::IsCryptedValue ($IdCrypt) static
IsCryptedValue
Parameters
string
Returns
the content of the IsCrypted field if data is crypted
References $_SESSION.
static MOD_crypt::MemberCrypt ($IdCrypt) static
MemberCrypt
allows a member to Crypt his data (to update it)
Parameters
$TableComumn must be something like "members.ProfileSummary"
$Idrecord is the id of the record in the corresponding $TableColumn, it's not normalized but needed for mainteance
Returns
insertId()
static MOD_crypt::MemberDeCrypt ($IdCrypt = false) static
MemberCrypt
allows a member to DeCrypt his data (to update it)
Parameters
$TableComumn must be something like "members.ProfileSummary"
$Idrecord is the id of the record in the corresponding $TableColumn, it's not normalized but needed for mainteance
Returns
insertId()
static MOD_crypt::MemberReadCrypted ($IdCrypt) static
Referenced by Member\get_crypted(), and InviteModel\sendOrComplain().
static MOD_crypt::NewReplaceInCrypted ($ss, $TableColumn, $IdRecord, $IdCrypt, $IdMember = false, $IsCrypted = "crypted") static
NewReplaceInCrypted
Allows to replace an entry in cryptedfields
Parameters
$TableComumn must be something like "members.ProfileSummary"
$Idrecord is the id of the record in the corresponding $TableColumn, it's not normalized but needed for mainteance
Returns
insertId()
Referenced by MembersModel\updateProfile().
static MOD_crypt::ReverseCrypt ($IdCrypt) static
ReverseCrypt
Returns
"decrypt" if $IdCrypt correspond to a crypt field
"crypt" if $IdCrypt correspond to a not crypted field it's used to propose the proper option for the layout, no action on DB required here
The documentation for this class was generated from the following file:
crypt.lib.php