Rox: MembersController Class Reference
MembersController Class Reference
Public Member Functions
__construct ()
index ($args=false)
setLocationCallback ($args, $action, $mem_redirect, $mem_resend)
updateMandatoryCallback ($args, $action, $mem_redirect, $mem_resend)
myPreferencesCallback ($args, $action, $mem_redirect)
commentCallback ($args, $action, $mem_redirect, $mem_resend)
editMyProfileCallback ($args, $action, $mem_redirect, $mem_resend)
deleteTranslationCallback ($args, $action, $mem_redirect, $mem_resend)
RelationCallback ($args, $action, $mem_redirect, $mem_resend)
retireProfile (StdClass $args, $memory, $stuff1, $stuff2)
retired ()
setProfileInactiveCallback (StdClass $args, $memory, $stuff1, $stuff2)
setActive ()
setProfileActiveCallback (StdClass $args, $memory, $stuff1, $stuff2)
setInactive ()
resetPasswordCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
resetPassword ()
resetPasswordFinish ()
mynotes ()
addNoteCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
addNote ()
deleteNoteCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
deleteNote ()
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
index_loggedOut ($args)
index_loggedIn ($args, $member_self)
getMember ($cid)
redirect_myprofile ()
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 4 of file members.ctrl.php.
Constructor & Destructor Documentation
MembersController::__construct ()
Definition at line 7 of file members.ctrl.php.
References model.
Member Function Documentation
MembersController::addNote ()
displays the add or edit note page
public
Returns
AddNotePagePage
Definition at line 960 of file members.ctrl.php.
MembersController::addNoteCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
noteCallback
Parameters
Object $args
Object $action
Object $mem_redirect memory for the page after redirect
Object $mem_resend memory for resending the form
Returns
string relative request for redirect
Definition at line 924 of file members.ctrl.php.
MembersController::commentCallback ($args, $action, $mem_redirect, $mem_resend)
commentCallback
Parameters
Object $args
Object $action
Object $mem_redirect memory for the page after redirect
Object $mem_resend memory for resending the form
Returns
string relative request for redirect
Definition at line 526 of file members.ctrl.php.
MembersController::deleteNote ()
displays the add or edit note page
public
Returns
AddNotePagePage
Definition at line 996 of file members.ctrl.php.
MembersController::deleteNoteCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
noteCallback
Parameters
Object $args
Object $action
Object $mem_redirect memory for the page after redirect
Object $mem_resend memory for resending the form
Returns
string relative request for redirect
Definition at line 983 of file members.ctrl.php.
MembersController::deleteTranslationCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 612 of file members.ctrl.php.
MembersController::editMyProfileCallback ($args, $action, $mem_redirect, $mem_resend)
handles edit profile form post - profile updating
Parameters
object $args
object $action
object $mem_redirect
object $mem_resend public
Returns
string
Definition at line 560 of file members.ctrl.php.
MembersController::getMember ($cid) protected
Definition at line 411 of file members.ctrl.php.
References $model.
Referenced by index_loggedIn(), and index_loggedOut().
MembersController::index ($args = false)
still main function called by router
Todo:
split controller up to use routing, when proper routing is working
Parameters
object $args public
Returns
object
Definition at line 21 of file members.ctrl.php.
References $member, index_loggedIn(), index_loggedOut(), and model.
MembersController::index_loggedIn ($args, $member_self) protected
Definition at line 114 of file members.ctrl.php.
References $_SESSION, $data, $id, $member, $model, $my_groups, $myself, $pager, $params, $redirect, $request, $rights, $url, $username, elseif, getMember(), RoxComponentBase\getWords(), RoxComponentBase\logWrite(), model, RoxControllerBase\redirect(), RoxControllerBase\setFlashError(), and RoxControllerBase\setFlashNotice().
Referenced by index().
MembersController::index_loggedOut ($args) protected
Definition at line 33 of file members.ctrl.php.
References $member, $model, $my_groups, $pager, $params, $request, getMember(), model, and RoxControllerBase\redirect().
Referenced by index().
MembersController::mynotes ()
displays the a list of contacts/notes
public
Returns
MemberNotesPage
Definition at line 894 of file members.ctrl.php.
MembersController::myPreferencesCallback ($args, $action, $mem_redirect)
Definition at line 476 of file members.ctrl.php.
References $_SESSION, $errors, $mem_redirect, $query, $request, $User, $vars, APP_User\login(), and model.
MembersController::redirect_myprofile () protected
Definition at line 423 of file members.ctrl.php.
References $_SESSION, $username, and RoxControllerBase\redirect().
MembersController::RelationCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 633 of file members.ctrl.php.
MembersController::resetPassword ()
displays the reset your password page
public
Returns
ResetPasswordPage
Definition at line 868 of file members.ctrl.php.
MembersController::resetPasswordCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
callback for password reset
Parameters
stdClass $args - all sorts of variables
ReadOnlyObject $memory - memory related stuff
stuff $stuff1
stuff $stuff2 public
Returns
mixed
Definition at line 821 of file members.ctrl.php.
MembersController::resetPasswordFinish ()
displays the reset your password page
public
Returns
ResetPasswordFinishPage
Definition at line 881 of file members.ctrl.php.
MembersController::retired ()
displays a page with some text about the profile being retired
public
Returns
RetiredPage
Definition at line 711 of file members.ctrl.php.
MembersController::retireProfile (StdClass $args, $memory, $stuff1, $stuff2)
callback for profile deletion
Parameters
stdClass $args - all sorts of variables
ReadOnlyObject $memory - memory related stuff
stuff $stuff1
stuff $stuff2 public
Returns
mixed
Definition at line 692 of file members.ctrl.php.
MembersController::setActive ()
Definition at line 743 of file members.ctrl.php.
MembersController::setInactive ()
Definition at line 785 of file members.ctrl.php.
MembersController::setLocationCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 433 of file members.ctrl.php.
References $errors, $mem_redirect, $request, $value, $vars, and model.
MembersController::setProfileActiveCallback (StdClass $args, $memory, $stuff1, $stuff2)
callback to set profile inactive
Parameters
stdClass $args - all sorts of variables
ReadOnlyObject $memory - memory related stuff
stuff $stuff1
stuff $stuff2 public
Returns
mixed
Definition at line 771 of file members.ctrl.php.
MembersController::setProfileInactiveCallback (StdClass $args, $memory, $stuff1, $stuff2)
callback to set profile inactive
Parameters
stdClass $args - all sorts of variables
ReadOnlyObject $memory - memory related stuff
stuff $stuff1
stuff $stuff2 public
Returns
mixed
Definition at line 729 of file members.ctrl.php.
MembersController::updateMandatoryCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 471 of file members.ctrl.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/members/members.ctrl.php