Rox: SignupModel Class Reference
SignupModel Class Reference
Public Member Functions
__construct ($data=false)
confirmRegister ($handle, $key)
emailInUse ($email)
takeCareForNonUniqueEmailAddress ($email)
takeCareForComputerUsedByBWMember ()
find ($str)
getRealHandle ($userId)
getUser ($userId)
UsernameInUse ($Username)
registerProcess ()
writeFeedback ($feedback)
registerBWMember ($vars)
polishFormValues (&$vars)
registerTBMember ($vars)
checkRegistrationForm (&$vars)
ageValue ($dd)
checkEmail ($email)
createKey ($s1, $s2, $IdMember="", $ss="default")
confirmSignup ($username, $key)
resendConfirmationMail ($username)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const HANDLE_PREGEXP = '/^[a-z](?!.*[-_.][-_.])[a-z0-9-._]{2,18}[a-z0-9]$/i'
const HANDLE_PREGEXP_EMAIL
const YOUNGEST_MEMBER = 18
const BW_TRUE = 'Yes'
const BW_FALSE = 'No'
const BW_TRUE_A = 'True'
const BW_FALSE_A = 'False'
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 30 of file signup.model.php.
Constructor & Destructor Documentation
SignupModel::__construct ($data = false)
Constructor
Parameters
void
Definition at line 66 of file signup.model.php.
References $data.
Member Function Documentation
SignupModel::ageValue ($dd)
Returns
float (?!) value corresponding date
FIXME: copied from FunctionsTools.php fage_value; used in several places in BW website; where should this been moved to?
Definition at line 685 of file signup.model.php.
SignupModel::checkEmail ($email)
(stolen from FunctionsTools->CheckEmail)
Returns
true , if e-mail address looks valid
Definition at line 696 of file signup.model.php.
SignupModel::checkRegistrationForm (& $vars)
Check form values of registration form, do some cautious corrections
Parameters
unknown_type $vars
Returns
unknown
Definition at line 590 of file signup.model.php.
Referenced by registerProcess().
SignupModel::confirmRegister ($handle, $key)
confirmation process
Parameters
string $handle
string $key
Returns
boolean
Definition at line 78 of file signup.model.php.
References APP_User\activate(), APP_User\getSetting(), and APP_User\userId().
SignupModel::confirmSignup ($username, $key)
confirmProcess: check the given key and username
Definition at line 714 of file signup.model.php.
SignupModel::createKey ($s1, $s2, $IdMember = "", $ss = "default")
See Also
FunctionsTools.php (plain copy) compute a nearly unique key according to parameters
Definition at line 705 of file signup.model.php.
SignupModel::emailInUse ($email)
checks if e-mail address is in use
Parameters
string $email
Returns
boolean
Definition at line 98 of file signup.model.php.
References $query.
SignupModel::find ($str)
Definition at line 190 of file signup.model.php.
References $query, and APP_User\login().
SignupModel::getRealHandle ($userId)
returns handle as written in DB
Definition at line 218 of file signup.model.php.
SignupModel::getUser ($userId)
Get all user fields
Parameters
int $userId
Returns
stdClass
Definition at line 232 of file signup.model.php.
References $query.
SignupModel::polishFormValues (& $vars)
$vars is required to contain an e-mail
Definition at line 512 of file signup.model.php.
Referenced by registerProcess().
SignupModel::registerBWMember ($vars)
FIXME: IdCity is written both to the members and the address table! This is just imitating the strategy of bw/signup.php! JY Comment : wont fix, this redudancy is on purpose (this is so useful ...)
This has NOT been executed: ALTER TABLE members MODIFY COLUMN id int(11) NOT NULL COMMENT 'IdMember' As a result, we do NOT use '.$this->dao->nextId('members').',
Definition at line 393 of file signup.model.php.
References $query, $vars, firstname, geonameid, lastname, and secondname.
Referenced by registerProcess().
SignupModel::registerProcess ()
Processing registration
This is a POST callback function
See Also
/htdocs/bw/signup.php
Parameters
void
Definition at line 292 of file signup.model.php.
References $_SESSION, $errors, $id, $vars, $View, checkRegistrationForm(), MOD_log\get(), polishFormValues(), registerBWMember(), registerTBMember(), takeCareForComputerUsedByBWMember(), takeCareForNonUniqueEmailAddress(), and writeFeedback().
SignupModel::registerTBMember ($vars)
Definition at line 543 of file signup.model.php.
Referenced by registerProcess().
SignupModel::resendConfirmationMail ($username)
Resend the confirmation mail in case the user clicked on the link in the login error message
Parameters
string $username
Definition at line 756 of file signup.model.php.
SignupModel::takeCareForComputerUsedByBWMember ()
Check, if computer has previously been used by BW member
(If signup team wanna get nicer e-mails, we'll provide adequate functionalities via signup.view.php and a template.)
TODO: I wonder, why BW signup team cares for my box; member Bin L. has been logged in before at this computer, - should be nothing to them.
Returns
string text (not HTML) to be added to feedback text, in case of no cookie ''
Definition at line 176 of file signup.model.php.
References $text, and MOD_log\get().
Referenced by registerProcess().
SignupModel::takeCareForNonUniqueEmailAddress ($email)
Determine other users (plural!), who use the same e-mail address, then
add this fact to the feedback text and
write this fact to the log
FIXME: This method just finds e-mail addresses in table cryptedfields, which are plain text. TODO by jyh : this is the same stupid code as in old BW, it can be improved
Parameters
string $email lower case e-mail address
Returns
string text to be added to feedback text, in case of no hit ''
Definition at line 133 of file signup.model.php.
References $_SESSION, $query, $text, and MOD_log\get().
Referenced by registerProcess().
SignupModel::UsernameInUse ($Username)
returns "true" if Username is in use (in members or in members who have quitted)
Parameters
string $Username
Returns
boolean true if username was used before, false if not
Definition at line 259 of file signup.model.php.
References $query, and $Username.
SignupModel::writeFeedback ($feedback)
TODO: use a language column with character codes instead of integers (!?)
Definition at line 339 of file signup.model.php.
References $_SESSION, $lang, and $query.
Referenced by registerProcess().
Field Documentation
const SignupModel::BW_FALSE = 'No'
Definition at line 57 of file signup.model.php.
const SignupModel::BW_FALSE_A = 'False'
Definition at line 59 of file signup.model.php.
const SignupModel::BW_TRUE = 'Yes'
Definition at line 56 of file signup.model.php.
const SignupModel::BW_TRUE_A = 'True'
Definition at line 58 of file signup.model.php.
const SignupModel::HANDLE_PREGEXP = '/^[a-z](?!.*[-_.][-_.])[a-z0-9-._]{2,18}[a-z0-9]$/i'
PERL regular expression for handles user TODO: should get a more specific name - refactoring needed!
Definition at line 42 of file signup.model.php.
const SignupModel::HANDLE_PREGEXP_EMAIL
Initial value:
=
'^[-!#$%&\'*+\\./0-9=?A-Z^_`a-z{|}~]+@[-!#$%&\'*+\\/0-9=?A-Z^_`a-z{|}~]+\.[-!#$%&\'*+\\./0-9=?A-Z^_`a-z{|}~]+$'
TODO: check, if this is indeed the best form; I don't believe it (steinwinde, 2008-08-04)
Definition at line 47 of file signup.model.php.
const SignupModel::YOUNGEST_MEMBER = 18
FIXME: use BW constant from config file instead of this one
Definition at line 53 of file signup.model.php.
Referenced by buildBirthYearOptions(), SignupPage\buildBirthYearOptions(), and MembersModel\validateBirthdate().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/signup/signup.model.php