Rox: SimplePie_HTTP_Parser Class Reference
SimplePie_HTTP_Parser Class Reference
Public Member Functions
__construct ($data)
parse ()
Data Fields
$http_version = 0.0
$status_code = 0
$reason = ''
$headers = array()
$body = ''
Protected Member Functions
has_data ()
is_linear_whitespace ()
http_version ()
status ()
reason ()
new_line ()
name ()
linear_whitespace ()
value ()
value_char ()
quote ()
quote_char ()
quote_escaped ()
body ()
chunked ()
Protected Attributes
$state = 'http_version'
$data = ''
$data_length = 0
$position = 0
$name = ''
$value = ''
Constructor & Destructor Documentation
SimplePie_HTTP_Parser::__construct ($data)
Create an instance of the class with the input data
Parameters
string $data Input data
References $data.
Member Function Documentation
SimplePie_HTTP_Parser::body () protected
Parse the body
References headers, position, and state.
Referenced by chunked(), and parse().
SimplePie_HTTP_Parser::chunked () protected
Parsed a "Transfer-Encoding: chunked" body
References $body, $matches, body(), and state.
SimplePie_HTTP_Parser::has_data () protected
Check whether there is data beyond the pointer
Returns
bool true if there is further data, false if not
References $data_length, and position.
Referenced by linear_whitespace(), and parse().
SimplePie_HTTP_Parser::http_version () protected
Parse the HTTP version
References position, and state.
Referenced by parse().
SimplePie_HTTP_Parser::is_linear_whitespace () protected
See if the next character is LWS
Returns
bool true if the next character is LWS, false if not
References $position, and position.
Referenced by linear_whitespace(), quote(), and value().
SimplePie_HTTP_Parser::linear_whitespace () protected
Parse LWS, replacing consecutive LWS characters with a single space
References elseif, has_data(), is_linear_whitespace(), position, and value().
Referenced by quote(), and value().
SimplePie_HTTP_Parser::name () protected
Parse a header name
References position, and state.
Referenced by new_line(), and value().
SimplePie_HTTP_Parser::new_line () protected
Deal with a new line, shifting data around as needed
References $name, $value, elseif, headers, name(), position, state, and value().
SimplePie_HTTP_Parser::parse ()
Parse the input data
Returns
bool true on success, false on failure
References $state, body(), has_data(), headers, http_version(), reason(), and state.
SimplePie_HTTP_Parser::quote () protected
See what state to move to while within quoted header values
References is_linear_whitespace(), linear_whitespace(), position, and state.
SimplePie_HTTP_Parser::quote_char () protected
Parse a header value while within quotes
References position, state, and value().
SimplePie_HTTP_Parser::quote_escaped () protected
Parse an escaped character within quotes
References $position, position, state, and value().
SimplePie_HTTP_Parser::reason () protected
Parse the reason phrase
References position, and state.
Referenced by parse().
SimplePie_HTTP_Parser::status () protected
Parse the status code
References position, and state.
SimplePie_HTTP_Parser::value () protected
See what state to move to while within non-quoted header values
References is_linear_whitespace(), linear_whitespace(), name(), position, and state.
Referenced by linear_whitespace(), new_line(), quote_char(), quote_escaped(), and value_char().
SimplePie_HTTP_Parser::value_char () protected
Parse a header value while outside quotes
References position, state, and value().
Field Documentation
SimplePie_HTTP_Parser::$body = ''
Referenced by chunked().
SimplePie_HTTP_Parser::$data = '' protected
Referenced by __construct().
SimplePie_HTTP_Parser::$data_length = 0 protected
Referenced by has_data().
SimplePie_HTTP_Parser::$headers = array()
SimplePie_HTTP_Parser::$http_version = 0.0
SimplePie_HTTP_Parser::$name = '' protected
Referenced by new_line().
SimplePie_HTTP_Parser::$position = 0 protected
Referenced by is_linear_whitespace(), and quote_escaped().
SimplePie_HTTP_Parser::$reason = ''
SimplePie_HTTP_Parser::$state = 'http_version' protected
Referenced by parse().
SimplePie_HTTP_Parser::$status_code = 0
SimplePie_HTTP_Parser::$value = '' protected
Referenced by new_line().
The documentation for this class was generated from the following file:
HTTP/Parser.php