Rox: Trip Class Reference
Trip Class Reference
Public Member Functions
__construct ()
assignGallery ($tripId, $galleryId)
getBlogGeo ($geonameid)
createTrip ($vars, Member $user)
getTripsForUser ($userId)
insertTrip ($name, $description, $userId)
getTrips ($handle=false)
getTripData ()
getTrip ($tripid)
reorderTripItems ($items)
prepareEditData ($tripId, $callbackId)
editProcess ($callbackId)
delProcess ($callbackId)
getTripsDataForLocation ($search)
getTripsForLocation ()
touchTrip ($tripId)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 11 of file trip.model.php.
Constructor & Destructor Documentation
Trip::__construct ()
Definition at line 13 of file trip.model.php.
Member Function Documentation
Trip::assignGallery ($tripId, $galleryId)
Definition at line 18 of file trip.model.php.
References $galleryId, and $query.
Referenced by createTrip(), and editProcess().
Trip::createTrip ($vars, Member $user)
Definition at line 45 of file trip.model.php.
References $Gallery, $galleryId, $vars, assignGallery(), insertTrip(), and RoxEntityBase\isLoaded().
Trip::delProcess ($callbackId)
Definition at line 378 of file trip.model.php.
References $callbackId, $query, and $vars.
Trip::editProcess ($callbackId)
Definition at line 319 of file trip.model.php.
References $callbackId, $Gallery, $galleryId, $query, $vars, assignGallery(), d, elseif, and n.
Trip::getBlogGeo ($geonameid)
fetches a geo identity, by geoname_id
Parameters
int $geonameid public
Returns
object|false
Definition at line 40 of file trip.model.php.
References RoxModelBase\createEntity().
Trip::getTrip ($tripid)
Definition at line 220 of file trip.model.php.
References $query.
Trip::getTripData ()
Definition at line 171 of file trip.model.php.
References $member, $query, $trip_data, Blog\FLAG_VIEW_PRIVATE, Blog\FLAG_VIEW_PROTECTED, and RoxModelBase\getLoggedInMember().
Trip::getTrips ($handle = false)
Definition at line 121 of file trip.model.php.
References $member, $query, $trips, Member\ACTIVE_ALL, Blog\FLAG_VIEW_PRIVATE, Blog\FLAG_VIEW_PROTECTED, and RoxModelBase\getLoggedInMember().
Trip::getTripsDataForLocation ($search)
Definition at line 405 of file trip.model.php.
References $query, $search, and $trip_data.
Trip::getTripsForLocation ()
Definition at line 433 of file trip.model.php.
References $query, Member\ACTIVE_ALL, and RoxModelBase\bulkLookup().
Trip::getTripsForUser ($userId)
Intended to replace old functions: tripropdown($userID)
Definition at line 78 of file trip.model.php.
References $query, Member\ACTIVE_ALL, and RoxModelBase\bulkLookup().
Trip::insertTrip ($name, $description, $userId)
Definition at line 96 of file trip.model.php.
References $description, and $name.
Referenced by createTrip().
Trip::prepareEditData ($tripId, $callbackId)
Definition at line 290 of file trip.model.php.
References $callbackId, $member, $query, $vars, and RoxModelBase\getLoggedInMember().
Trip::reorderTripItems ($items)
Definition at line 239 of file trip.model.php.
References $items, and $query.
Trip::touchTrip ($tripId)
Definition at line 452 of file trip.model.php.
References $query.
Referenced by BlogController\createProcess(), and BlogController\editProcess().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/trip/trip.model.php