Rox: RSSCache Class Reference
RSSCache Class Reference
Public Member Functions
RSSCache ($base='', $age='')
set ($url, $rss)
get ($url)
check_cache ($url)
cache_age ($cache_key)
serialize ($rss)
unserialize ($data)
file_name ($url)
error ($errormsg, $lvl=E_USER_WARNING)
debug2 ($debug2msg, $lvl=E_USER_NOTICE)
RSSCache ($base='', $age='')
set ($url, $rss)
get ($url)
check_cache ($url)
cache_age ($cache_key)
serialize ($rss)
unserialize ($data)
file_name ($url)
error ($errormsg, $lvl=E_USER_WARNING)
debug2 ($debug2msg, $lvl=E_USER_NOTICE)
RSSCache ($base='', $age='')
set ($url, $rss)
get ($url)
check_cache ($url)
cache_age ($cache_key)
serialize ($rss)
unserialize ($data)
file_name ($url)
error ($errormsg, $lvl=E_USER_WARNING)
debug2 ($debug2msg, $lvl=E_USER_NOTICE)
Data Fields
$BASE_CACHE = './cache'
$MAX_AGE = 3600
$ERROR = ""
Member Function Documentation
RSSCache::cache_age ($cache_key)
References $mtime, $url, and file_name().
RSSCache::cache_age ($cache_key)
References $mtime, $url, and file_name().
RSSCache::cache_age ($cache_key)
References $mtime, $url, and file_name().
RSSCache::check_cache ($url)
References $mtime, $url, and file_name().
RSSCache::check_cache ($url)
References $mtime, $url, and file_name().
RSSCache::check_cache ($url)
References $mtime, $url, and file_name().
RSSCache::debug2 ($debug2msg, $lvl = E_USER_NOTICE)
References error().
Referenced by get().
RSSCache::debug2 ($debug2msg, $lvl = E_USER_NOTICE)
References error().
RSSCache::debug2 ($debug2msg, $lvl = E_USER_NOTICE)
References error().
RSSCache::error ($errormsg, $lvl = E_USER_WARNING)
Referenced by debug2(), get(), RSSCache(), and set().
RSSCache::error ($errormsg, $lvl = E_USER_WARNING)
RSSCache::error ($errormsg, $lvl = E_USER_WARNING)
RSSCache::file_name ($url)
References $url.
RSSCache::file_name ($url)
References $url.
Referenced by cache_age(), check_cache(), get(), and set().
RSSCache::file_name ($url)
References $url.
RSSCache::get ($url)
References $data, $rss, $url, debug2(), error(), file_name(), and unserialize().
RSSCache::get ($url)
References $data, $rss, $url, debug2(), error(), file_name(), and unserialize().
RSSCache::get ($url)
References $data, $rss, $url, debug2(), error(), file_name(), and unserialize().
RSSCache::RSSCache ($base = '', $age = '')
References $status, and error().
RSSCache::RSSCache ($base = '', $age = '')
References $status, and error().
RSSCache::RSSCache ($base = '', $age = '')
References $status, and error().
RSSCache::serialize ($rss)
References $rss, and serialize().
RSSCache::serialize ($rss)
References $rss.
Referenced by serialize(), and set().
RSSCache::serialize ($rss)
References $rss, and serialize().
RSSCache::set ($url, $rss)
References $data, $rss, $url, error(), file_name(), and serialize().
RSSCache::set ($url, $rss)
References $data, $rss, $url, error(), file_name(), and serialize().
RSSCache::set ($url, $rss)
References $data, $rss, $url, error(), file_name(), and serialize().
RSSCache::unserialize ($data)
References $data, and unserialize().
RSSCache::unserialize ($data)
References $data.
Referenced by get(), and unserialize().
RSSCache::unserialize ($data)
References $data, and unserialize().
Field Documentation
RSSCache::$BASE_CACHE = './cache'
RSSCache::$ERROR = ""
RSSCache::$MAX_AGE = 3600
The documentation for this class was generated from the following file:
build/about/magpierss/rss_cache.inc