Rox: MembersModel Class Reference
MembersModel Class Reference
Public Member Functions
__construct ()
getStatuses ()
getMemberFromEmail ($email)
getMemberWithUsername ($username)
getMemberWithId ($id)
getComment ($id)
reportBadComment ($username, $comment_id)
get_relation_between_members ($IdMember_rel)
setLocation ($IdMember, $geonameid=false)
set_profile_language ($langcode)
get_profile_language ()
delete_translation_multiple ($trad_ids=array(), $IdOwner, $lang_id)
set_preference ($IdMember, $IdPreference, $Value)
set_public_profile ($IdMember, $Public=false)
setCommentGuidelinesRead ()
getCommentGuidelinesRead ()
checkCommentForm (&$vars)
addComment ($TCom, &$vars)
addRelation (&$vars)
updateRelation (&$vars)
confirmRelation (&$vars)
deleteRelation ($id)
checkMyPreferences (&$vars)
editPreferences (&$vars)
setSessionLanguage ($language_id)
checkProfileForm (&$vars)
ageValue ($dd)
validateBirthdate ($birthdate)
updateProfile (&$vars)
polishProfileFormValues ($vars)
sendCommentNotification ($note, $messageWordCode, $subjectWordCode)
showAvatar ($memberId=false)
hasAvatar ($memberid, $suffix= '')
getOldPicture ($memberid)
avatarMake ($memberid, $img_file, $using_original=false)
writeMemberphoto ($memberid)
bootstrap ()
sendRetiringFeedback ($feedback= '')
writeNoteForMember ($username, $category, $comment)
deleteNoteForMember ($memberId)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const TOO_YOUNG = -1
const DATE_INVALID = -2
Protected Member Functions
ShallICrypt ($vars, $ss)
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 38 of file members.model.php.
Constructor & Destructor Documentation
MembersModel::__construct ()
Constructor
Parameters
void
Definition at line 48 of file members.model.php.
References bootstrap().
Member Function Documentation
MembersModel::addComment ($TCom, & $vars)
Definition at line 491 of file members.model.php.
References $_SESSION, $ii, $max, $note, $syshcvol, $TCom, $vars, RoxModelBase\createEntity(), getMemberWithId(), RoxComponentBase\logWrite(), sendCommentNotification(), and setCommentGuidelinesRead().
MembersModel::addRelation (& $vars)
Definition at line 603 of file members.model.php.
References $_SESSION, $note, $vars, $words, RoxModelBase\createEntity(), getMemberWithId(), RoxComponentBase\logWrite(), and RoxModelBase\singleLookup().
MembersModel::ageValue ($dd)
validates a date and outputs valid date or false checks if the age of the person is 17 > x > 100
Parameters
string $birthdate public
Returns
string|bool
Definition at line 949 of file members.model.php.
Referenced by validateBirthdate().
MembersModel::avatarMake ($memberid, $img_file, $using_original = false)
Definition at line 1440 of file members.model.php.
References $type, and writeMemberphoto().
Referenced by hasAvatar(), and updateProfile().
MembersModel::bootstrap ()
Definition at line 1494 of file members.model.php.
Referenced by __construct().
MembersModel::checkCommentForm (& $vars)
Definition at line 463 of file members.model.php.
References $errors, $ii, $max, $syshcvol, and $vars.
MembersModel::checkMyPreferences (& $vars)
Check form values of MyPreferences form,
Parameters
unknown_type $vars
Returns
unknown
Definition at line 798 of file members.model.php.
References $_SESSION, $errors, $query, $vars, and elseif.
MembersModel::checkProfileForm (& $vars)
Check form values of Mandatory form, should always be analog to /build/signup/signup.model.php !!
Parameters
unknown_type $vars
Returns
unknown
Definition at line 893 of file members.model.php.
References $errors, $res, $vars, and validateBirthdate().
MembersModel::confirmRelation (& $vars)
Definition at line 674 of file members.model.php.
References $note, $vars, $words, RoxModelBase\createEntity(), and RoxModelBase\singleLookup().
MembersModel::delete_translation_multiple ($trad_ids = array(), $IdOwner, $lang_id)
Delete a profile translation for a member
Definition at line 336 of file members.model.php.
References $count, $words, and RoxComponentBase\logWrite().
MembersModel::deleteNoteForMember ($memberId)
Deletes the note for a member
Parameters
string memberId Id of the member for which the note was written
Definition at line 1546 of file members.model.php.
References $loggedInMember, $res, and RoxModelBase\getLoggedInMember().
MembersModel::deleteRelation ($id)
Delete member special relation
Parameters
int $id ID of relation
Returns
bool Deletion result, true for success, false on error
Definition at line 713 of file members.model.php.
References $id, $member, $note, RoxModelBase\createEntity(), getMemberWithId(), and RoxModelBase\singleLookup().
MembersModel::editPreferences (& $vars)
Edit a members preferences, one at a time
Definition at line 859 of file members.model.php.
References $query, $vars, RoxModelBase\bulkLookup(), and set_preference().
MembersModel::get_profile_language ()
Definition at line 305 of file members.model.php.
References $_SESSION, $lang, $member, RoxModelBase\createEntity(), and set_profile_language().
MembersModel::get_relation_between_members ($IdMember_rel)
Definition at line 148 of file members.model.php.
References $_SESSION, $member, $myself, $words, getMemberWithId(), and RoxComponentBase\getWords().
MembersModel::getComment ($id)
retrieves a specific comment
Parameters
int $id public
Returns
Comment
Definition at line 124 of file members.model.php.
References $id, and RoxModelBase\createEntity().
Referenced by reportBadComment().
MembersModel::getCommentGuidelinesRead ()
Definition at line 455 of file members.model.php.
References $layoutbits.
MembersModel::getMemberFromEmail ($email)
Parameters
unknown $email
Returns
boolean|Ambigous <object, mixed>
this is so far the worst, most useless piece of hacky crap I've had to code for BW so far. The cause is the 'encryption' that means we cannot query for a member by email - even if emails are stored unencrypted in the database
Definition at line 71 of file members.model.php.
References RoxModelBase\createEntity(), and RoxModelBase\singleLookup().
MembersModel::getMemberWithId ($id)
Definition at line 105 of file members.model.php.
References $id, and RoxModelBase\createEntity().
Referenced by addComment(), addRelation(), deleteRelation(), get_relation_between_members(), and updateRelation().
MembersModel::getMemberWithUsername ($username)
Definition at line 100 of file members.model.php.
References $username, and RoxModelBase\createEntity().
Referenced by reportBadComment(), and writeNoteForMember().
MembersModel::getOldPicture ($memberid)
Definition at line 1413 of file members.model.php.
Referenced by hasAvatar().
MembersModel::getStatuses ()
Definition at line 54 of file members.model.php.
References $res.
MembersModel::hasAvatar ($memberid, $suffix = '')
Definition at line 1400 of file members.model.php.
References avatarMake(), elseif, and getOldPicture().
Referenced by showAvatar().
MembersModel::polishProfileFormValues ($vars)
prettify values from post request
Parameters
array $vars public
Returns
array
Definition at line 1240 of file members.model.php.
References $ii, $lang, $m, $max, $TabRestrictions, $vars, and validateBirthdate().
MembersModel::reportBadComment ($username, $comment_id)
marks a comment as problematic
Parameters
string $username - username of member with comment
int - id of comment to mark
public
Returns
bool
Definition at line 138 of file members.model.php.
References $comment, $member, $username, getComment(), and getMemberWithUsername().
MembersModel::sendCommentNotification ($note, $messageWordCode, $subjectWordCode)
Sends an email to inform the member of a new comment.
Parameters
object $note Notification configuration.
string $messageWordCode i18n code for email content.
string $subjectWordCode i18n code for email subject.
Definition at line 1334 of file members.model.php.
References $body, $note, $subject, $words, and RoxModelBase\createEntity().
Referenced by addComment().
MembersModel::sendRetiringFeedback ($feedback = '')
Definition at line 1500 of file members.model.php.
References FeedbackModel\DELETE_PROFILE, and FeedbackModel\sendFeedback().
MembersModel::set_preference ($IdMember, $IdPreference, $Value)
Set the preferred language for a member
Todo:
make sure that places that call this function uses the return code
Parameters
int $IdMember
int $IdPreference
string $Value public
Returns
bool
Definition at line 357 of file members.model.php.
References $query, RoxComponentBase\logWrite(), and RoxModelBase\singleLookup().
Referenced by editPreferences().
MembersModel::set_profile_language ($langcode)
Not totally sure it belongs here - but better this than member object? As it's more of a business of this model to know about different states of the member object to be displayed..
JY: not sure neither, anyway, I change the $langcode parameter to be either a numeric (languages.id, or a not numeric languages.ShortCode) Nota no need to test if the profile exist in the language, since this setting is used for the sub-headers of the page (profile content is something else than headers)
Definition at line 271 of file members.model.php.
References RoxModelBase\singleLookup().
Referenced by get_profile_language().
MembersModel::set_public_profile ($IdMember, $Public = false)
Set a member's profile public/private
Definition at line 395 of file members.model.php.
References elseif, RoxComponentBase\logWrite(), and RoxModelBase\singleLookup().
MembersModel::setCommentGuidelinesRead ()
Set preference if comment guidelines have been read.
Definition at line 435 of file members.model.php.
References $query, and RoxModelBase\getLoggedInMember().
Referenced by addComment().
MembersModel::setLocation ($IdMember, $geonameid = false)
set the location of a member
Definition at line 176 of file members.model.php.
References $errors, $m, $vars, RoxModelBase\createEntity(), RoxComponentBase\logWrite(), and RoxModelBase\singleLookup().
MembersModel::setSessionLanguage ($language_id)
sets the language of the current session
Parameters
int $language_id public
Returns
bool
Definition at line 877 of file members.model.php.
References $lang, and RoxModelBase\createEntity().
MembersModel::ShallICrypt ($vars, $ss) protected
Definition at line 1353 of file members.model.php.
References $vars.
Referenced by updateProfile().
MembersModel::showAvatar ($memberId = false)
Shows a members picture in different sizes
Definition at line 1364 of file members.model.php.
References $member, RoxModelBase\createEntity(), elseif, and hasAvatar().
MembersModel::updateProfile (& $vars)
Update Member's Profile
Parameters
unknown_type $vars
Returns
unknown
Definition at line 1010 of file members.model.php.
References $_SESSION, $CanTranslate, $lang, $m, $rights, $status, $vars, $words, MOD_crypt\AdminReadCrypted(), avatarMake(), RoxModelBase\createEntity(), RoxComponentBase\logWrite(), MOD_crypt\NewReplaceInCrypted(), and ShallICrypt().
MembersModel::updateRelation (& $vars)
Definition at line 643 of file members.model.php.
References $_SESSION, $note, $vars, $words, RoxModelBase\createEntity(), getMemberWithId(), RoxComponentBase\logWrite(), and RoxModelBase\singleLookup().
MembersModel::validateBirthdate ($birthdate)
Definition at line 959 of file members.model.php.
References $matches, ageValue(), and SignupModel\YOUNGEST_MEMBER.
Referenced by checkProfileForm(), and polishProfileFormValues().
MembersModel::writeMemberphoto ($memberid)
Definition at line 1470 of file members.model.php.
Referenced by avatarMake().
MembersModel::writeNoteForMember ($username, $category, $comment)
Creates or updates a note for a member
Parameters
string username Username of the member for which the note is written
string category Category under which the note is filed
string comment Comment text. May be empty
Definition at line 1519 of file members.model.php.
References $comment, $loggedInMember, $member, $res, $username, RoxModelBase\getLoggedInMember(), and getMemberWithUsername().
Field Documentation
const MembersModel::DATE_INVALID = -2
Definition at line 957 of file members.model.php.
const MembersModel::TOO_YOUNG = -1
Definition at line 956 of file members.model.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/members/members.model.php