Rox: RoxModelBase Class Reference
RoxModelBase Class Reference
Public Member Functions
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_entity_factory
Detailed Description
Acts as the base for all MVC-models and entities implements various database calls and makes sure the model and entities will always have a dao object (accessed using $this->dao)
Author
Lemon-head, Fake51
Definition at line 11 of file model.php.
Constructor & Destructor Documentation
RoxModelBase::__construct ()
used to instantiate an RoxEntityFactory - other than that, just calls the parent
public
Definition at line 35 of file model.php.
References MOD_params\get().
Member Function Documentation
RoxModelBase::bulkLookup ($query_string, $keynames = false)
This method fetches a bunch of rows from the database. It has some funny mechanics, which you can usually just ignore.
Parameters
string $query_string
array $keynames
this will trigger the funny mechanics which sort the results into a hierarchic structure
Returns
array of rows (as objects)
Definition at line 153 of file model.php.
References $i.
Referenced by PollsModel\AddVote(), PollsModel\CancelVote(), Member\count_comments(), Blog\countComments(), LinkModel\dbFriends(), LinkModel\dbFriendsID(), LinkModel\dbLinks(), MembersModel\editPreferences(), MessagesModel\filteredMailbox(), Member\get_address(), Member\get_comments(), Member\get_comments_commenter(), Member\get_comments_written(), Member\get_trads(), GeoModel\getAllGeonameIds(), RssModel\getBlogFeed(), RssModel\getBlogFeedByAuthor(), RssModel\getBlogFeedByTag(), SqltestModel\getBWMembers(), Blog\getCategoryArray(), LinkModel\getChanges(), LinkModel\getComments(), DatabaseSummaryModel\getDatabaseFieldsSorted(), DatabaseSummaryModel\getDatabaseTablesSorted(), CommunityModel\getFaqsCategorized(), AboutModel\getFaqsCategorized(), FeedbackModel\getFeedbackCategories(), RssModel\getForumFeed(), LastcommentsModel\GetLastComments(), LinkModel\getLinkPreferences(), LinkModel\getMemberdata(), Member\getNoteCategories(), NotifyModel\getNotes(), PollsModel\GetPollResults(), Blog\getRecentPostsArray(), LinkModel\getSpecialRelation(), RssModel\getTagFeed(), SqltestModel\getTBUsers(), RssModel\getThreadFeed(), Trip\getTripsForLocation(), Trip\getTripsForUser(), NewsletterModel\Load(), PollsModel\LoadPoll(), VerifyMembersModel\LoadVerified(), VerifyMembersModel\LoadVerifiers(), PollsModel\PrepareContribute(), NewsletterModel\PreviousLetters(), LinkModel\rebuildMissingLinks(), Member\set_profile_languages(), and GeoModel\updateGeoCounters().
RoxModelBase::bulkLookup_assoc ($query_string)
This is the same as the above bulkLookup, but the rows are associative arrays instead of objects.
Parameters
unknown_type $query_string
Returns
array of rows (as associative arrays)
Definition at line 205 of file model.php.
RoxModelBase::createEntity () protected
calls the entity factory to create an entity, passes along any arguments
Parameters
string - first parameter must be the name of the entity to create
Returns
object protected
Definition at line 61 of file model.php.
Referenced by GeoUse\__construct(), GroupsModel\acceptGroupMember(), MembersModel\addComment(), Role\addForMember(), GroupsModel\addGroupMemberAsAdmin(), MembersModel\addRelation(), GroupsModel\banGroupMember(), PrivilegeScope\checkForEquivalentScope(), VerifyMembersModel\checkPassword(), PrivilegeScope\checkScopeExists(), MembersModel\confirmRelation(), Role\containsPrivilege(), GroupsModel\countGroupsBySearchterms(), AdminModel\countMembersWithStatus(), GroupsModel\countMyGroups(), Group\createGroup(), GroupsModel\createGroup(), NotifyModel\createNote(), NotifyModel\deleteNotes(), RelatedGroup\deleteRelatedGroup(), MembersModel\deleteRelation(), GroupsModel\findAllGroups(), NotifyModel\findAllNotes(), GroupsModel\findGroup(), RelatedGroupsModel\findGroup(), GroupsModel\findGroups(), GroupsModel\findMembersByName(), NotifyModel\findNote(), NotifyModel\findNotes(), Member\forums_posts_count(), Member\get_address(), MembersModel\get_profile_language(), Geo\getAllAlternateNames(), Geo\getAllParents(), Member\getAllPostVotes(), RightsModel\getAllRoles(), Member\getAllThreadVotes(), Geo\getAlternateName(), AdminModel\getBadComments(), Trip\getBlogGeo(), Blog\getBlogPost(), AdminModel\getBoard(), LoginModel\getBWMemberByUsername(), Geo\getChildren(), Address\getCity(), BlogEntity\getComingPosts(), Member\getComingPosts(), MembersModel\getComment(), GeoModel\getContinents(), Geo\getCountry(), Group\getEmailAcceptingMembers(), Role\getEquivalentPrivilege(), Member\getFirstAddress(), Feedback\getFromMember(), Comment\getFromMember(), GalleryModel\getGalleriesNotEmptyEntities(), BlogEntity\getGeo(), Forums\GetGroupEntity(), GroupMembership\getGroupMembers(), Member\getGroupMembership(), Group\getGroupOwners(), Member\getGroups(), RelatedGroupsModel\getGroupsForMember(), GroupsModel\getGroupsForMember(), Group\getLastLoggedInMembers(), GeoModel\getLocationById(), getLoggedInMember(), AdminModel\getMassmailRecipientsInfo(), InviteModel\getMember(), ApiModel\getMember(), Address\getMemberAddress(), Blog\getMemberByUsername(), Group\getMemberCount(), ApiModel\getMemberData(), MembersModel\getMemberFromEmail(), GroupMembership\getMemberGroups(), MemberRole\getMemberRoles(), Group\getMembers(), MembersModel\getMemberWithId(), GalleryModel\getMemberWithUserId(), MembersModel\getMemberWithUsername(), Group\getNewMembers(), ProfileNote\getNote(), Member\getNote(), ProfileNote\getNotes(), Member\getNotes(), Geo\getParent(), Forums\GetPostVote(), RolePrivilege\getPrivilege(), PrivilegeScope\getPrivilege(), RolePrivilege\getPrivilegeRoles(), Role\getPrivileges(), RelatedGroup\getRelatedGroupsLog(), RolePrivilege\getRole(), MemberRole\getRoleMembers(), RolePrivilege\getRolePrivileges(), Member\getRoles(), Role\getScopesForMemberRole(), Member\getSignupFeedback(), Comment\getToMember(), Geo\getTotalUsage(), Geo\getUsageForAllTypes(), Member\getVisitorCount(), Member\getVisitorsSubset(), Thread\getVoteResult(), Post\getVoteResult(), Thread\getVotes(), Post\getVotes(), Member\hasPrivilege(), Member\hasRole(), GroupsModel\inviteMember(), Group\isGroupOwner(), Group\isMember(), AboutModel\isVolunteer(), GroupsModel\joinGroup(), GroupsModel\leaveGroup(), VerifyMembersModel\LoadApprovedVerifiers(), RoxEntityBase\loadEntities(), GeoModel\loadLocation(), GroupsModel\memberAcceptedInvitation(), RelatedGroupsModel\memberAddsRelatedGroup(), GroupsModel\memberDeclinedInvitation(), RelatedGroupsModel\memberDeletesRelatedGroup(), MemberRole\memberHasRole(), Group\memberJoin(), Group\memberLeave(), GroupsModel\notifyGroupAdmins(), Forums\prepare_notification(), AdminModel\processMembers(), GroupsModel\realImg(), Member\recordVisit(), Role\removeFromMember(), Group\removeGroupOwner(), Member\removeLanguages(), GroupsModel\resignGroupAdmin(), restoreLoggedInMember(), Forums\searchUserposts(), MembersModel\sendCommentNotification(), FeedbackModel\sendFeedback(), GroupsModel\sendInvitation(), InviteModel\sendOrComplain(), Group\setGroupOwner(), MembersModel\setLocation(), MembersModel\setSessionLanguage(), MembersModel\showAvatar(), RelatedGroupsModel\showRelatedGroupsLog(), GroupsModel\thumbImg(), AdminModel\treasurerEditCreateDonationVarsOk(), GroupsModel\updateMembershipSettings(), MembersModel\updateProfile(), MembersModel\updateRelation(), and AdminModel\updateVolunteerBoard().
RoxModelBase::get_dao () protected
normally the $dao should be injected. If it's not, this function creates a new one out of the blue..
Definition at line 46 of file model.php.
RoxModelBase::getDao () protected
Definition at line 68 of file model.php.
RoxModelBase::getLoggedInMember ()
returns the currently logged in member
public
Returns
object|false
Definition at line 78 of file model.php.
References $_SESSION, and createEntity().
Referenced by AdminTreasurerPage\__construct(), AdminTreasurerEditCreateDonationPage\__construct(), AdminTreasurerStartDonationCampaignPage\__construct(), Suggestion\addOption(), Forums\adjustThreadsCountToShow(), GroupsModel\canAccessGroupAdmin(), GroupsModel\canAccessGroupDelete(), ActivitiesModel\checkEditCreateActivityVarsOk(), Blog\commentProcess(), Blog\countRecentPosts(), GalleryModel\createGallery(), GroupsModel\createGroup(), AdminModel\createMassmail(), SuggestionsModel\createSuggestion(), MembersModel\deleteNoteForMember(), Suggestion\deleteOption(), Suggestion\editOption(), SuggestionsModel\editSuggestion(), RightsModel\getAllRoles(), Group\getGroupOwners(), ActivitiesModel\getMyActivities(), ActivitiesModel\getMyActivitiesCount(), ActivitiesModel\getNearMeQuery(), Forums\GetPostVote(), Blog\getRecentPostIt(), Blog\getRecentPostsArray(), Blog\getStickyPostIt(), Blog\getTaggedPostsIt(), Blog\getTagsIt(), Blog\getTinyMCEPreference(), Forums\getTinyMCEPreference(), Trip\getTripData(), Trip\getTrips(), RightsModel\hasRightsAccess(), ActivitiesModel\joinLeaveActivity(), Suggestion\loadEntity(), SuggestionOption\loadEntity(), LoginModel\logout(), GroupsModel\memberAcceptedInvitation(), GroupsModel\memberDeclinedInvitation(), Trip\prepareEditData(), GroupsModel\resignGroupAdmin(), FeedbackModel\sendFeedback(), MembersModel\setCommentGuidelinesRead(), LoginModel\setPreferredLanguage(), ActivitiesModel\setRadius(), Forums\switchShowMyGroupsTopicsOnly(), Suggestion\update(), ActivitiesModel\updateActivity(), AdminModel\updateMassmail(), AdminModel\updateVolunteerBoard(), GalleryModel\uploadProcess(), and MembersModel\writeNoteForMember().
RoxModelBase::getMemoryCookie () protected
Reads the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
Definition at line 117 of file model.php.
References $_SESSION, elseif, and setMemoryCookie().
Referenced by restoreLoggedInMember().
RoxModelBase::restoreLoggedInMember ()
Restore session if memory cookie exists
Definition at line 98 of file model.php.
References createEntity(), and getMemoryCookie().
RoxModelBase::setMemoryCookie ($id, $seriesToken = '', $authToken = '') protected
Sets the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
Definition at line 134 of file model.php.
References $id.
Referenced by getMemoryCookie().
RoxModelBase::singleLookup ($query_string)
Definition at line 217 of file model.php.
Referenced by PollsModel\AddChoice(), GeoModel\addHierarchy(), VerifyMembersModel\AddNewVerified(), MembersModel\addRelation(), PollsModel\AddVote(), PollsModel\CancelVote(), PollsModel\CanUserContribute(), MessagesModel\CaptchaNeeded(), VerifyMembersModel\CheckAndGetUsername(), LoginModel\checkBWPassword(), MembersModel\confirmRelation(), Member\count_mynotes(), LoginModel\createMissingTBUser(), MessagesModel\deleteMessage(), MembersModel\deleteRelation(), Forums\DeleteVoteForPost(), LoginModel\encryptPasswordBW(), LanguageLookupModel\findLanguageWithCode(), Member\get_publicProfile(), Member\get_userid(), Member\get_verification_status(), DonateModel\getCampaignValues(), LinkModel\getChanges(), AdminModel\getCountryCodeForGeonameId(), GeoModel\getDataById(), AdminModel\getDonation(), AdminModel\getDonationCampaignStatus(), FeedbackModel\getFeedbackCategory(), AdminModel\getGeonameIdForCountryCode(), Forums\GetIdThread(), RoxFrontRouterModel\getLanguage(), MessagesModel\getMember(), LinkModel\getMemberdata(), MembersModel\getMemberFromEmail(), LinkModel\getMemberID(), GalleryModel\getMemberWithUserId(), MessagesModel\getMessage(), PollsModel\GetPollResults(), RoxFrontRouterModel\getPossibleUrlLanguage(), SearchModel\getResultsForLocation(), LoginModel\getTBUserForBWMember(), GeoModel\getUsagetypeId(), Places\getWikiPage(), PollsModel\HasAlreadyContributed(), MessagesModel\hasMessageLimitExceeded(), PollsModel\IsMemberAllowed(), CommunityModel\isVolunteer(), NewsletterModel\Load(), VerifyMembersModel\LoadApprovedVerifiers(), PollsModel\LoadList(), PollsModel\LoadPoll(), PollsModel\PrepareContribute(), MessagesModel\sendOrComplain(), MembersModel\set_preference(), MembersModel\set_profile_language(), MembersModel\set_public_profile(), LoginModel\setBWMemberAsLoggedIn(), MembersModel\setLocation(), LoginModel\setupBWSession(), SearchModel\suggestLocationsFromDatabase(), PollsModel\UpdateChoice(), GeoModel\updateGeonameId(), PollsModel\UpdatePoll(), MembersModel\updateRelation(), MessagesModel\updateSpamInfo(), GeoModel\updateUsageCounter(), and Forums\VoteForPost().
RoxModelBase::singleLookup_assoc ($query_string)
Definition at line 231 of file model.php.
Referenced by Member\getProfilePictureID().
Field Documentation
RoxModelBase::$_entity_factory protected
Definition at line 21 of file model.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/mvc-base/model.php