Rox: NotifyAdminWidget Class Reference
NotifyAdminWidget Class Reference
Public Member Functions
render ()
Public Member Functions inherited from ItemlistWithPagination
render ()
needsPagination ()
showPagination ()
Public Member Functions inherited from ItemlistWidget
render ()
__call ($methodname, $args)
Public Member Functions inherited from RoxWidget
__construct ()
render ()
getStylesheets ()
getScriptfiles ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
hrefPage ($i_page)
getAllItems ()
getItems ()
getTableColumns ()
tableCell_select ($note)
tableCell_id ($note)
tableCell_idmember ($note)
tableCell_idrelmember ($note)
tableCell_type ($note)
tableCell_link ($note)
tableCell_wordcode ($note)
tableCell_translationparams ($note)
tableCell_checked ($note)
tableCell_sendmail ($note)
tableCell_created ($note)
Protected Member Functions inherited from ItemlistWithPagination
prepare ()
numberOfPages ()
getItems ()
getItemsForPage ($k_page)
itemsTotalBegin ()
showPageLink ($i_page)
showActivePageLink ($i_page)
getItemsInRange ($begin, $count)
itemsTotalCount ()
Protected Member Functions inherited from ItemlistWidget
showItems ()
showItems_table ()
showItems_float ()
showItems_list ()
showBetweenListItems ($prev_item, $item, $i_row)
showListItem ($item, $i_row)
getItems ()
hideColumnTitles ()
Protected Member Functions inherited from RoxWidget
createEntity ()
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxWidget
$_entity_factory
Detailed Description
Definition at line 157 of file notify.widgets.php.
Member Function Documentation
NotifyAdminWidget::getAllItems () protected
Definition at line 173 of file notify.widgets.php.
NotifyAdminWidget::getItems () protected
Definition at line 179 of file notify.widgets.php.
References model.
NotifyAdminWidget::getTableColumns () protected
Columns for notes table. The $key of a column is used as a suffix for method tableCell_$key
Returns
array table columns, as $name => Column title
Definition at line 195 of file notify.widgets.php.
References RoxWidget\createEntity().
NotifyAdminWidget::hrefPage ($i_page) protected
Definition at line 165 of file notify.widgets.php.
NotifyAdminWidget::render ()
Definition at line 159 of file notify.widgets.php.
NotifyAdminWidget::tableCell_checked ($note) protected
Definition at line 264 of file notify.widgets.php.
References $params, and $words.
NotifyAdminWidget::tableCell_created ($note) protected
Definition at line 274 of file notify.widgets.php.
References $note.
NotifyAdminWidget::tableCell_id ($note) protected
Definition at line 217 of file notify.widgets.php.
NotifyAdminWidget::tableCell_idmember ($note) protected
Definition at line 222 of file notify.widgets.php.
NotifyAdminWidget::tableCell_idrelmember ($note) protected
Definition at line 227 of file notify.widgets.php.
References $note.
NotifyAdminWidget::tableCell_link ($note) protected
Definition at line 239 of file notify.widgets.php.
References $note, a, MOD_member\getUsername(), and tableCell_type().
NotifyAdminWidget::tableCell_select ($note) protected
Table cell in column 'select', for the given $note
Parameters
unknown_type $note
Definition at line 209 of file notify.widgets.php.
NotifyAdminWidget::tableCell_sendmail ($note) protected
Definition at line 269 of file notify.widgets.php.
NotifyAdminWidget::tableCell_translationparams ($note) protected
Definition at line 251 of file notify.widgets.php.
References $note, and a.
NotifyAdminWidget::tableCell_type ($note) protected
Definition at line 234 of file notify.widgets.php.
References $note.
Referenced by tableCell_link().
NotifyAdminWidget::tableCell_wordcode ($note) protected
Definition at line 246 of file notify.widgets.php.
References $note.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/notify/notify.widgets.php