Rox: SimplePie_Content_Type_Sniffer Class Reference
SimplePie_Content_Type_Sniffer Class Reference
Public Member Functions
__construct ($file)
get_type ()
text_or_binary ()
unknown ()
image ()
feed_or_html ()
Data Fields
$file
Constructor & Destructor Documentation
SimplePie_Content_Type_Sniffer::__construct ($file)
Create an instance of the class with the input file
Parameters
SimplePie_Content_Type_Sniffer $file Input file
References $file.
Member Function Documentation
SimplePie_Content_Type_Sniffer::feed_or_html ()
Sniff HTML
Returns
string Actual Content-Type
References elseif.
Referenced by get_type().
SimplePie_Content_Type_Sniffer::get_type ()
Get the Content-Type of the specified file
Returns
string Actual Content-Type
References elseif, feed_or_html(), image(), text_or_binary(), and unknown().
SimplePie_Content_Type_Sniffer::image ()
Sniff images
Returns
string Actual Content-Type
References elseif.
Referenced by get_type().
SimplePie_Content_Type_Sniffer::text_or_binary ()
Sniff text or binary
Returns
string Actual Content-Type
References elseif.
Referenced by get_type(), and unknown().
SimplePie_Content_Type_Sniffer::unknown ()
Sniff unknown
Returns
string Actual Content-Type
References elseif, and text_or_binary().
Referenced by get_type().
Field Documentation
SimplePie_Content_Type_Sniffer::$file
Referenced by __construct().
The documentation for this class was generated from the following file:
Sniffer.php