Rox: SimplePie_Registry Class Reference
SimplePie_Registry Class Reference
Public Member Functions
__construct ()
register ($type, $class, $legacy=false)
get_class ($type)
& create ($type, $parameters=array())
& call ($type, $method, $parameters=array())
Protected Attributes
$default
$classes = array()
$legacy = array()
Constructor & Destructor Documentation
SimplePie_Registry::__construct ()
Constructor
No-op
Member Function Documentation
& SimplePie_Registry::call ($type, $method, $parameters = array())
Call a static method for a type
Parameters
string $type
string $method
array $parameters
Returns
mixed
References $class, $type, and get_class().
& SimplePie_Registry::create ($type, $parameters = array())
Create a new instance of a given type
Parameters
string $type
array $parameters Parameters to pass to the constructor
Returns
object Instance of class
References $class, $type, and get_class().
SimplePie_Registry::get_class ($type)
Get the class registered for a type
Where possible, use {
See Also
create()} or {
call()} instead
Parameters
string $type
Returns
string|null
References $type.
Referenced by call(), and create().
SimplePie_Registry::register ($type, $class, $legacy = false)
Register a class
Parameters
string $type See {
See Also
$default} for names
Parameters
string $class Class name, must subclass the corresponding default
bool $legacy Whether to enable legacy support for this class
Returns
bool Successfulness
References $class, $legacy, and $type.
Field Documentation
SimplePie_Registry::$classes = array() protected
SimplePie_Registry::$default protected
Initial value:
= array(
        'Cache' => 'SimplePie_Cache',
        'Locator' => 'SimplePie_Locator',
        'Parser' => 'SimplePie_Parser',
        'File' => 'SimplePie_File',
        'Sanitize' => 'SimplePie_Sanitize',
        'Item' => 'SimplePie_Item',
        'Author' => 'SimplePie_Author',
        'Category' => 'SimplePie_Category',
        'Enclosure' => 'SimplePie_Enclosure',
        'Caption' => 'SimplePie_Caption',
        'Copyright' => 'SimplePie_Copyright',
        'Credit' => 'SimplePie_Credit',
        'Rating' => 'SimplePie_Rating',
        'Restriction' => 'SimplePie_Restriction',
        'Content_Type_Sniffer' => 'SimplePie_Content_Type_Sniffer',
        'Source' => 'SimplePie_Source',
        'Misc' => 'SimplePie_Misc',
        'XML_Declaration_Parser' => 'SimplePie_XML_Declaration_Parser',
        'Parse_Date' => 'SimplePie_Parse_Date',
    )
SimplePie_Registry::$legacy = array() protected
Referenced by register().
The documentation for this class was generated from the following file:
Registry.php