Rox: LinkModel Class Reference
LinkModel Class Reference
Public Member Functions
__construct ()
createPath ($branch, $directlinks)
createLinkList ()
getTree ($directlinks, $startids)
rebuildLinks ()
rebuildMissingLinks ()
updateLinks ()
writeLinkList ($fields)
deleteLinkList ()
removeLink ($id)
getChanges ()
getComments ()
getSpecialRelation ()
dbFriendsID ($fromid, $degree=1, $limit=10)
dbFriends ($fromid, $degree=1, $limit=10)
dbLinks ($fromid, $toid, $limit=5)
getMemberdata ($ids)
getLinkPreferences ()
getMemberID ($username)
getIdsFromPath ($path)
getFriends ($from, $degree=1, $limit=10)
getFriendsFull ($from, $degree=1, $limit=10)
getDegree ($from, $to)
getLinks ($from, $to, $limit=10)
getLinksFull ($from, $to, $limit=10)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 10 of file link.model.php.
Constructor & Destructor Documentation
LinkModel::__construct ()
Definition at line 12 of file link.model.php.
Member Function Documentation
LinkModel::createLinkList ()
Definition at line 37 of file link.model.php.
References $comment, $comments, $value, getComments(), getLinkPreferences(), and getSpecialRelation().
Referenced by rebuildLinks(), rebuildMissingLinks(), and updateLinks().
LinkModel::createPath ($branch, $directlinks)
Functions needed to create the link network and store it to the db
Definition at line 22 of file link.model.php.
References $value.
Referenced by getTree().
LinkModel::dbFriends ($fromid, $degree = 1, $limit = 10)
Definition at line 354 of file link.model.php.
References RoxModelBase\bulkLookup().
LinkModel::dbFriendsID ($fromid, $degree = 1, $limit = 10)
functions to retrieve link infromation from the db
Definition at line 344 of file link.model.php.
References RoxModelBase\bulkLookup().
Referenced by getFriends(), and getFriendsFull().
LinkModel::dbLinks ($fromid, $toid, $limit = 5)
Definition at line 365 of file link.model.php.
References RoxModelBase\bulkLookup().
Referenced by getLinks(), and getLinksFull().
LinkModel::deleteLinkList ()
Definition at line 235 of file link.model.php.
Referenced by rebuildLinks().
LinkModel::getChanges ()
functions collecting connection data from other parts of the system
comments
special relations retrieve link information from the comment system
Definition at line 263 of file link.model.php.
References $comment, $comments, $id, $link, $relations, RoxModelBase\bulkLookup(), and RoxModelBase\singleLookup().
Referenced by updateLinks().
LinkModel::getComments ()
Definition at line 302 of file link.model.php.
References RoxModelBase\bulkLookup().
Referenced by createLinkList().
LinkModel::getDegree ($from, $to)
Definition at line 538 of file link.model.php.
LinkModel::getFriends ($from, $degree = 1, $limit = 10)
often used functions to get data from the link system returns an array of IDs get $limit number of friends of the distance of $degree for $from member (id or username) without additional $degree / $limit parameters it returnsthe ID for 10 direct friends
Definition at line 498 of file link.model.php.
References $value, dbFriendsID(), and getMemberID().
LinkModel::getFriendsFull ($from, $degree = 1, $limit = 10)
returns an array (member ID as key) with useful memberdata for all IDs get $limit number of friends of the distance of $degree for $from member (id or username) without additional $degree / $limit parameters it returnsthe ID for 10 direct friends
Definition at line 519 of file link.model.php.
References $value, dbFriendsID(), getMemberdata(), and getMemberID().
LinkModel::getIdsFromPath ($path)
Definition at line 478 of file link.model.php.
References $i.
Referenced by getLinks(), and getLinksFull().
LinkModel::getLinkPreferences ()
retrieve the Preference setting for the link network (Yes, no, hidden)
Definition at line 440 of file link.model.php.
References $value, and RoxModelBase\bulkLookup().
Referenced by createLinkList().
LinkModel::getLinks ($from, $to, $limit = 10)
Definition at line 542 of file link.model.php.
References $to, $value, dbLinks(), getIdsFromPath(), and getMemberID().
LinkModel::getLinksFull ($from, $to, $limit = 10)
Definition at line 564 of file link.model.php.
References $id, $to, $value, dbLinks(), getIdsFromPath(), getMemberdata(), and getMemberID().
LinkModel::getMemberdata ($ids)
retrieve useful information about members from the db
Definition at line 380 of file link.model.php.
References $value, RoxModelBase\bulkLookup(), and RoxModelBase\singleLookup().
Referenced by getFriendsFull(), and getLinksFull().
LinkModel::getMemberID ($username)
Definition at line 459 of file link.model.php.
References $username, and RoxModelBase\singleLookup().
Referenced by getFriends(), getFriendsFull(), getLinks(), and getLinksFull().
LinkModel::getSpecialRelation ()
retrieve link information from the special relation system
Definition at line 326 of file link.model.php.
References RoxModelBase\bulkLookup().
Referenced by createLinkList().
LinkModel::getTree ($directlinks, $startids)
Definition at line 94 of file link.model.php.
References $count, $value, createPath(), and writeLinkList().
Referenced by rebuildLinks(), rebuildMissingLinks(), and updateLinks().
LinkModel::rebuildLinks ()
/ rebuild the link database
Definition at line 165 of file link.model.php.
References $value, createLinkList(), deleteLinkList(), and getTree().
LinkModel::rebuildMissingLinks ()
Definition at line 174 of file link.model.php.
References $value, RoxModelBase\bulkLookup(), createLinkList(), and getTree().
LinkModel::removeLink ($id)
Definition at line 242 of file link.model.php.
References $id.
Referenced by updateLinks().
LinkModel::updateLinks ()
/ update the link database to integrate links changed since last called
Definition at line 201 of file link.model.php.
References $id, createLinkList(), getChanges(), getTree(), and removeLink().
LinkModel::writeLinkList ($fields)
write / flush database
Definition at line 219 of file link.model.php.
Referenced by getTree().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/link/link.model.php