Rox: ApiModel Class Reference
ApiModel Class Reference
Public Member Functions
__construct ()
getMember ($username)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Static Public Member Functions
static getMemberData (Member $member)
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
API model class.
Author
Meinhard Benn meinh.nosp@m.ard@.nosp@m.bewel.nosp@m.come.nosp@m..org
Definition at line 7 of file api.model.php.
Constructor & Destructor Documentation
ApiModel::__construct ()
Default constructor.
Definition at line 12 of file api.model.php.
Member Function Documentation
ApiModel::getMember ($username)
Get active member by username.
Parameters
string $username Username of member.
Returns
Member|false Member entity object or false if member not found or not 'Active'.
Definition at line 23 of file api.model.php.
References $member, $username, and RoxModelBase\createEntity().
static ApiModel::getMemberData (Member $member) static
Get all data for a member.
This method is a huge monolith, but should be seen as sort of an export filter and sanitiser.
Each data field has a documentation comment of this format: field : <fieldName> : <fieldType> : <occurrance> : <comment>
These comments will be used later to render the API documentation.
fieldType: Matches the type in JavaScript, so for example "number" for both integer and float.
occurance: Can be either "always" or "optional". Fields labelled as "always" will be included in each response, "optional" fields will only be included if they are visible and have content.
Parameters
Member $member Member entity object.
Returns
object Object containing member data as properties.
Definition at line 52 of file api.model.php.
References $blogModel, $city, $languages, $occupation, MOD_layoutbits\ago(), Member\count_comments(), RoxModelBase\createEntity(), Member\forums_posts_count(), Member\get_messengers(), Member\get_trad(), Member\getGalleryItemsCount(), Member\getGroups(), Member\getTripsArray(), and Member\isPublic().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/api/api.model.php