Rox: SignupView Class Reference
SignupView Class Reference
Public Member Functions
__construct (SignupModel $model)
customStylesSignup ()
ShowSimpleTeaser ($title)
confirmation ($username, $email)
registerForm ()
signupTeamMail ($vars)
registerMail ($vars, $IdMember, $idTB)
showTermsAndConditions ()
style ($text, $photo=false)
Detailed Description
Definition at line 30 of file signup.view.php.
Constructor & Destructor Documentation
SignupView::__construct (SignupModel $model)
Parameters
Signup $model
Definition at line 42 of file signup.view.php.
References $model.
Member Function Documentation
SignupView::confirmation ($username, $email)
Loading register confirm error template
Parameters
void
Definition at line 70 of file signup.view.php.
SignupView::customStylesSignup ()
Loading Custom CSS for signup
Parameters
void
Definition at line 52 of file signup.view.php.
SignupView::registerForm ()
Loading register form template
Parameters
void
Definition at line 80 of file signup.view.php.
References $birthYearOptions, $callbackId, $selYear, and $vars.
SignupView::registerMail ($vars, $IdMember, $idTB)
Sends a confirmation e-mail
Parameters
string $userId
Definition at line 155 of file signup.view.php.
References $body, $member, $subject, $title, $to, $vars, $words, MOD_log\get(), APP_User\getSetting(), and MOD_mail\sendEmail().
SignupView::ShowSimpleTeaser ($title)
Loading Simple Teaser - just needs defined title
Parameters
void
Definition at line 61 of file signup.view.php.
SignupView::showTermsAndConditions ()
Definition at line 192 of file signup.view.php.
SignupView::signupTeamMail ($vars)
Notify volunteers // TODO: create appropriate template
Parameters
array $vars with username
Definition at line 112 of file signup.view.php.
References $_SESSION, $body, $status, $subject, $to, $vars, MOD_log\get(), and MOD_mail\sendEmail().
SignupView::style ($text, $photo = false)
Definition at line 213 of file signup.view.php.
References $_SESSION, $text, and MOD_layoutbits\smallUserPic_username().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/signup/signup.view.php