Rox: SuggestionsController Class Reference
SuggestionsController Class Reference
Public Member Functions
__construct ()
suggestions ()
show ()
editCreateSuggestionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
editCreate ()
approveList ()
approveSuggestionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
approve ()
discussList ()
discuss ()
discussReply ()
editOptionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
editOption ()
deleteOptionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
deleteOption ()
restoreOption ()
addOptionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
changeStateCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
addOptions ()
addOptionsReply ()
addOptionsList ()
voteList ()
voteSuggestionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
vote ()
excludeCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
exclude ()
rankList ()
rank ()
voteRanking ()
voteAjaxRanking ()
moveOptionToImplementing ()
moveOptionToImplemented ()
devList ()
dev ()
rejectedList ()
rejected ()
resultsList ()
results ()
team ()
about ()
view ()
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const SUGGESTIONS_PER_PAGE = 50
const OPTIONS_PER_PAGE = 50
Protected Member Functions
getPager ($url, $count, $pageno, $itemsPerPage=self::SUGGESTIONS_PER_PAGE)
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
suggestions controller class.
Author
shevek
Definition at line 7 of file suggestions.ctrl.php.
Constructor & Destructor Documentation
SuggestionsController::__construct ()
Constructor.
Definition at line 15 of file suggestions.ctrl.php.
Member Function Documentation
SuggestionsController::about ()
Definition at line 624 of file suggestions.ctrl.php.
SuggestionsController::addOptionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 300 of file suggestions.ctrl.php.
References $errors, RoxComponentBase\getWords(), and RoxControllerBase\setFlashNotice().
SuggestionsController::addOptions ()
Definition at line 328 of file suggestions.ctrl.php.
References $id, $loggedInMember, and SuggestionsModel\SUGGESTIONS_ADD_OPTIONS.
SuggestionsController::addOptionsList ()
Definition at line 350 of file suggestions.ctrl.php.
References $count, getPager(), and SuggestionsModel\SUGGESTIONS_ADD_OPTIONS.
SuggestionsController::addOptionsReply ()
Definition at line 339 of file suggestions.ctrl.php.
References $id, $loggedInMember, and SuggestionsModel\SUGGESTIONS_ADD_OPTIONS.
SuggestionsController::approve ()
Definition at line 194 of file suggestions.ctrl.php.
References $loggedInMember, and SuggestionsModel\SUGGESTIONS_AWAIT_APPROVAL.
SuggestionsController::approveList ()
Definition at line 165 of file suggestions.ctrl.php.
References $count, getPager(), and SuggestionsModel\SUGGESTIONS_AWAIT_APPROVAL.
SuggestionsController::approveSuggestionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 180 of file suggestions.ctrl.php.
References RoxComponentBase\getWords(), and RoxControllerBase\setFlashNotice().
SuggestionsController::changeStateCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 314 of file suggestions.ctrl.php.
References $errors, RoxComponentBase\getWords(), and RoxControllerBase\setFlashNotice().
SuggestionsController::deleteOption ()
Definition at line 278 of file suggestions.ctrl.php.
References $id, $loggedInMember, and SuggestionsModel\SUGGESTIONS_ADD_OPTIONS.
SuggestionsController::deleteOptionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 270 of file suggestions.ctrl.php.
References RoxComponentBase\getWords(), and RoxControllerBase\setFlashNotice().
SuggestionsController::dev ()
Definition at line 560 of file suggestions.ctrl.php.
References $loggedInMember, SuggestionsModel\SUGGESTIONS_IMPLEMENTED, and SuggestionsModel\SUGGESTIONS_IMPLEMENTING.
SuggestionsController::devList ()
Definition at line 545 of file suggestions.ctrl.php.
References $count, getPager(), and SuggestionsModel\SUGGESTIONS_DEV.
SuggestionsController::discuss ()
Definition at line 218 of file suggestions.ctrl.php.
References $id, $loggedInMember, and SuggestionsModel\SUGGESTIONS_DISCUSSION.
SuggestionsController::discussList ()
Definition at line 203 of file suggestions.ctrl.php.
References $count, getPager(), and SuggestionsModel\SUGGESTIONS_DISCUSSION.
SuggestionsController::discussReply ()
Definition at line 229 of file suggestions.ctrl.php.
References $id, $loggedInMember, and SuggestionsModel\SUGGESTIONS_DISCUSSION.
SuggestionsController::editCreate ()
Definition at line 141 of file suggestions.ctrl.php.
References $loggedInMember, RoxComponentBase\getWords(), RoxControllerBase\redirect(), RoxControllerBase\redirectAbsolute(), and RoxControllerBase\setFlashNotice().
SuggestionsController::editCreateSuggestionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 120 of file suggestions.ctrl.php.
References $errors, RoxComponentBase\getWords(), RoxControllerBase\redirect(), and RoxControllerBase\setFlashNotice().
SuggestionsController::editOption ()
Definition at line 257 of file suggestions.ctrl.php.
References $id, $loggedInMember, and SuggestionsModel\SUGGESTIONS_ADD_OPTIONS.
SuggestionsController::editOptionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 240 of file suggestions.ctrl.php.
References $errors, RoxComponentBase\getWords(), and RoxControllerBase\setFlashNotice().
SuggestionsController::exclude ()
Definition at line 422 of file suggestions.ctrl.php.
References $id, $loggedInMember, and SuggestionsModel\SUGGESTIONS_VOTING.
SuggestionsController::excludeCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 413 of file suggestions.ctrl.php.
References $member, RoxComponentBase\getWords(), and RoxControllerBase\setFlashNotice().
SuggestionsController::getPager ($url, $count, $pageno, $itemsPerPage = self::SUGGESTIONS_PER_PAGE) protected
Definition at line 107 of file suggestions.ctrl.php.
References $count, $pager, $params, and $url.
Referenced by addOptionsList(), approveList(), devList(), discussList(), rankList(), rejectedList(), resultsList(), and voteList().
SuggestionsController::moveOptionToImplemented ()
Definition at line 528 of file suggestions.ctrl.php.
References $id, $loggedInMember, ENT_COMPAT, RoxComponentBase\getWords(), SuggestionOption\IMPLEMENTING, RoxControllerBase\redirectAbsolute(), and RoxControllerBase\setFlashNotice().
SuggestionsController::moveOptionToImplementing ()
Definition at line 511 of file suggestions.ctrl.php.
References $loggedInMember, ENT_COMPAT, RoxComponentBase\getWords(), SuggestionOption\RANKING, RoxControllerBase\redirectAbsolute(), and RoxControllerBase\setFlashNotice().
SuggestionsController::rank ()
Definition at line 457 of file suggestions.ctrl.php.
References $loggedInMember, and SuggestionsModel\SUGGESTIONS_RANKING.
SuggestionsController::rankList ()
Definition at line 432 of file suggestions.ctrl.php.
References $count, $options, $order, getPager(), and SuggestionOption\RANKING.
SuggestionsController::rejected ()
Definition at line 585 of file suggestions.ctrl.php.
References $loggedInMember, and SuggestionsModel\SUGGESTIONS_REJECTED.
SuggestionsController::rejectedList ()
Definition at line 570 of file suggestions.ctrl.php.
References $count, getPager(), and SuggestionsModel\SUGGESTIONS_REJECTED.
SuggestionsController::restoreOption ()
Definition at line 291 of file suggestions.ctrl.php.
References $loggedInMember, RoxComponentBase\getWords(), RoxControllerBase\setFlashNotice(), and SuggestionsModel\SUGGESTIONS_ADD_OPTIONS.
SuggestionsController::results ()
Definition at line 611 of file suggestions.ctrl.php.
References $loggedInMember.
SuggestionsController::resultsList ()
Definition at line 596 of file suggestions.ctrl.php.
References $count, getPager(), and SuggestionsModel\SUGGESTIONS_CLOSED.
SuggestionsController::show ()
Redirects for a given suggestion to the appropiate page
Definition at line 67 of file suggestions.ctrl.php.
References $id, $params, $url, RoxControllerBase\redirectAbsolute(), SuggestionsModel\SUGGESTIONS_ADD_OPTIONS, SuggestionsModel\SUGGESTIONS_AWAIT_APPROVAL, SuggestionsModel\SUGGESTIONS_DEV, SuggestionsModel\SUGGESTIONS_DISCUSSION, SuggestionsModel\SUGGESTIONS_DUPLICATE, SuggestionsModel\SUGGESTIONS_IMPLEMENTED, SuggestionsModel\SUGGESTIONS_IMPLEMENTING, SuggestionsModel\SUGGESTIONS_RANKING, SuggestionsModel\SUGGESTIONS_REJECTED, and SuggestionsModel\SUGGESTIONS_VOTING.
SuggestionsController::suggestions ()
Definition at line 20 of file suggestions.ctrl.php.
References RoxControllerBase\redirectAbsolute().
SuggestionsController::team ()
Definition at line 619 of file suggestions.ctrl.php.
SuggestionsController::view ()
Definition at line 629 of file suggestions.ctrl.php.
SuggestionsController::vote ()
Definition at line 394 of file suggestions.ctrl.php.
References $id, $loggedInMember, RoxComponentBase\getWords(), RoxControllerBase\setFlashNotice(), and SuggestionsModel\SUGGESTIONS_VOTING.
SuggestionsController::voteAjaxRanking ()
Definition at line 482 of file suggestions.ctrl.php.
References $callback, $id, exit, and json_encode().
SuggestionsController::voteList ()
Definition at line 365 of file suggestions.ctrl.php.
References $count, getPager(), and SuggestionsModel\SUGGESTIONS_VOTING.
SuggestionsController::voteRanking ()
Definition at line 465 of file suggestions.ctrl.php.
References $loggedInMember, RoxComponentBase\getWords(), SuggestionOption\RANKING, RoxControllerBase\redirectAbsolute(), and RoxControllerBase\setFlashNotice().
SuggestionsController::voteSuggestionCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 379 of file suggestions.ctrl.php.
References $errors, $member, RoxComponentBase\getWords(), and RoxControllerBase\setFlashNotice().
Field Documentation
const SuggestionsController::OPTIONS_PER_PAGE = 50
Definition at line 10 of file suggestions.ctrl.php.
const SuggestionsController::SUGGESTIONS_PER_PAGE = 50
Definition at line 9 of file suggestions.ctrl.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/suggestions/suggestions.ctrl.php