Rox: MOD_enc Class Reference
MOD_enc Class Reference
Public Member Functions
__construct ($tablename, $rownumber, $keyMember)
test ()
Data Fields
const MODE = MCRYPT_MODE_CFB
const CIPHER = MCRYPT_DES
const TABLE_NAME_REF_MEMBER = 1
const TABLE_NAME_REF_ADDR = 2
Protected Member Functions
adminEncrypt ($plainString)
adminDecrypt ($encryptedString)
memberEncrypt ($plainString)
memberDecrypt ($encryptedString)
Detailed Description
All encryption / decryption should get routed here.
See Also
htdocs/bw/lib/FunctionsCrypt.php
Definition at line 29 of file enc.lib.php.
Constructor & Destructor Documentation
MOD_enc::__construct ($tablename, $rownumber, $keyMember)
tablename and rownumber are required to build the initialization vector
Parameters
int $tablename name of table expressed as an integer, e.g. TABLE_NAME_REF_MEMBER
int $rownumber number of row in the table afore mentioned
Returns
void
Definition at line 89 of file enc.lib.php.
Member Function Documentation
MOD_enc::adminDecrypt ($encryptedString) protected
Definition at line 154 of file enc.lib.php.
Referenced by MOD_encdb\readEncryptedAdminValue(), and test().
MOD_enc::adminEncrypt ($plainString) protected
Definition at line 146 of file enc.lib.php.
Referenced by test(), and MOD_encdb\writeEncrypted().
MOD_enc::memberDecrypt ($encryptedString) protected
Definition at line 171 of file enc.lib.php.
Referenced by MOD_encdb\readEncryptedMemberValue(), and test().
MOD_enc::memberEncrypt ($plainString) protected
Definition at line 163 of file enc.lib.php.
Referenced by test(), and MOD_encdb\writeEncrypted().
MOD_enc::test ()
Definition at line 180 of file enc.lib.php.
References adminDecrypt(), adminEncrypt(), memberDecrypt(), and memberEncrypt().
Field Documentation
const MOD_enc::CIPHER = MCRYPT_DES
Definition at line 35 of file enc.lib.php.
const MOD_enc::MODE = MCRYPT_MODE_CFB
encryption strategy
Definition at line 34 of file enc.lib.php.
const MOD_enc::TABLE_NAME_REF_ADDR = 2
Definition at line 40 of file enc.lib.php.
const MOD_enc::TABLE_NAME_REF_MEMBER = 1
Definition at line 39 of file enc.lib.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/security/lib/enc.lib.php