Rox: Post Class Reference
Post Class Reference
Public Member Functions
__construct ($post_id=false)
findByPostId ($id)
getMemberPostCount (Member $member)
getVotes ()
getVoteResult ()
getPositiveVoteCount ()
getNegativeVoteCount ()
getNeutralVoteCount ()
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Attributes
$_table_name = 'forums_posts'
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Data Fields inherited from RoxEntityBase
$sql_order = ''
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
represents a single forum post
Definition at line 7 of file post.entity.php.
Constructor & Destructor Documentation
Post::__construct ($post_id = false)
Definition at line 13 of file post.entity.php.
References findByPostId().
Member Function Documentation
Post::findByPostId ($id)
fetches a post by postid
Parameters
int $id public
Returns
object|bool
Definition at line 29 of file post.entity.php.
References RoxEntityBase\findByWhere().
Referenced by __construct().
Post::getMemberPostCount (Member $member)
returns a count of how many posts a member has made
Parameters
object $member - Member entity public
Returns
int
Definition at line 41 of file post.entity.php.
References RoxEntityBase\countWhere(), and RoxEntityBase\isLoaded().
Post::getNegativeVoteCount ()
returns the count of negative votes for the post
public
Returns
int
Definition at line 97 of file post.entity.php.
Post::getNeutralVoteCount ()
returns the count of neutral votes for the post
public
Returns
int
Definition at line 108 of file post.entity.php.
Post::getPositiveVoteCount ()
returns the count of positive votes for the post
public
Returns
int
Definition at line 86 of file post.entity.php.
Post::getVoteResult ()
returns array of post votes that member has made
public
Returns
array
Definition at line 71 of file post.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Post::getVotes ()
returns array of post votes that member has made
public
Returns
array
Definition at line 56 of file post.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Field Documentation
Post::$_table_name = 'forums_posts' protected
Definition at line 10 of file post.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/forums/post.entity.php