Rox: SimplePie_XML_Declaration_Parser Class Reference
SimplePie_XML_Declaration_Parser Class Reference
Public Member Functions
__construct ($data)
parse ()
has_data ()
skip_whitespace ()
get_value ()
before_version_name ()
version_name ()
version_equals ()
version_value ()
encoding_name ()
encoding_equals ()
encoding_value ()
standalone_name ()
standalone_equals ()
standalone_value ()
Data Fields
$version = '1.0'
$encoding = 'UTF-8'
$standalone = false
$state = 'before_version_name'
$data = ''
$data_length = 0
$position = 0
Detailed Description
Definition at line 52 of file Parser.php.
Constructor & Destructor Documentation
SimplePie_XML_Declaration_Parser::__construct ($data)
Create an instance of the class with the input data
public
Parameters
string $data Input data
Definition at line 116 of file Parser.php.
References $data.
Member Function Documentation
SimplePie_XML_Declaration_Parser::before_version_name ()
Definition at line 192 of file Parser.php.
References skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::encoding_equals ()
Definition at line 266 of file Parser.php.
References position, skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::encoding_name ()
Definition at line 252 of file Parser.php.
References position, skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::encoding_value ()
Definition at line 280 of file Parser.php.
References get_value(), has_data(), skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::get_value ()
Read value
Definition at line 175 of file Parser.php.
References $value, has_data(), and position.
Referenced by encoding_value(), standalone_value(), and version_value().
SimplePie_XML_Declaration_Parser::has_data ()
Check whether there is data beyond the pointer
private
Returns
bool true if there is further data, false if not
Definition at line 155 of file Parser.php.
References $data_length, and position.
Referenced by encoding_value(), get_value(), parse(), standalone_value(), and version_value().
SimplePie_XML_Declaration_Parser::parse ()
Parse the input data
public
Returns
bool true on success, false on failure
Definition at line 128 of file Parser.php.
References $state, has_data(), state, and version.
SimplePie_XML_Declaration_Parser::skip_whitespace ()
Advance past any whitespace
Returns
int Number of whitespace characters passed
Definition at line 165 of file Parser.php.
References position.
Referenced by before_version_name(), encoding_equals(), encoding_name(), encoding_value(), standalone_equals(), standalone_name(), standalone_value(), version_equals(), version_name(), and version_value().
SimplePie_XML_Declaration_Parser::standalone_equals ()
Definition at line 314 of file Parser.php.
References position, skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::standalone_name ()
Definition at line 300 of file Parser.php.
References position, skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::standalone_value ()
Definition at line 328 of file Parser.php.
References $standalone, get_value(), has_data(), skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::version_equals ()
Definition at line 218 of file Parser.php.
References position, skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::version_name ()
Definition at line 204 of file Parser.php.
References position, skip_whitespace(), and state.
SimplePie_XML_Declaration_Parser::version_value ()
Definition at line 232 of file Parser.php.
References get_value(), has_data(), skip_whitespace(), state, and version.
Field Documentation
SimplePie_XML_Declaration_Parser::$data = ''
Definition at line 92 of file Parser.php.
Referenced by __construct().
SimplePie_XML_Declaration_Parser::$data_length = 0
Definition at line 100 of file Parser.php.
Referenced by has_data().
SimplePie_XML_Declaration_Parser::$encoding = 'UTF-8'
Definition at line 68 of file Parser.php.
SimplePie_XML_Declaration_Parser::$position = 0
Definition at line 108 of file Parser.php.
SimplePie_XML_Declaration_Parser::$standalone = false
Definition at line 76 of file Parser.php.
Referenced by standalone_value().
SimplePie_XML_Declaration_Parser::$state = 'before_version_name'
Definition at line 84 of file Parser.php.
Referenced by parse().
SimplePie_XML_Declaration_Parser::$version = '1.0'
Definition at line 60 of file Parser.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/templates/simplepie/library/SimplePie/XML/Declaration/Parser.php