Rox: RoxPostHandler Class Reference
RoxPostHandler Class Reference
Public Member Functions
__sleep ()
getCallbackAction (array $post_args)
registerCallbackMethod ($classname, $methodname, $mem_resend)
__set ($key, $value)
__get ($key)
inject ($key, $value)
Protected Member Functions
getExpiredCallbackActionAttributes ($post_args)
getSecretWord ()
get ($key)
Detailed Description
The PPostHandler sucks, so we make a new one. Unlike the singleton PPostHandler, this one will be nicest dynamic OOP.
The handler will be called from RoxLauncher.
Member Function Documentation
ObjectWithInjection::__get ($key) inherited
ObjectWithInjection::__set ($key, $value) inherited
References $value, and ObjectWithInjection\inject().
RoxPostHandler::__sleep ()
ObjectWithInjection::get ($key) protected inherited
RoxPostHandler::getCallbackAction (array $post_args)
References $action, and getExpiredCallbackActionAttributes().
RoxPostHandler::getExpiredCallbackActionAttributes ($post_args) protected
References getSecretWord().
Referenced by getCallbackAction().
RoxPostHandler::getSecretWord () protected
Referenced by getExpiredCallbackActionAttributes(), and registerCallbackMethod().
ObjectWithInjection::inject ($key, $value) inherited
References $value.
Referenced by ObjectWithInjection\__set().
RoxPostHandler::registerCallbackMethod ($classname, $methodname, $mem_resend)
References getSecretWord().
The documentation for this class was generated from the following file:
roxposthandler.class.php