Rox: AdminController Class Reference
AdminController Class Reference
Public Member Functions
__construct ()
__destruct ()
noRights ()
index ()
tempVolStart ()
debugLogs ()
accepter ()
accepterProcessMembers (stdClass $args, ReadOnlyObject $memory, $stuff3, $stuff4)
commentsOverview ()
spamOverview ()
wordsOverview ()
updateVolunteerBoard (stdClass $args, $memory, $stuff3, $stuff4)
activityLogs ()
wordsDownload ()
treasurerOverview ()
treasurerEditCreateDonationCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
treasurerEditCreateDonation ()
treasurerStartDonationCampaignCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
treasurerStartDonationCampaign ()
treasurerStopDonationCampaign ()
massmail ()
massmailEditCreateCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
massmailCreate ()
massmailDetails ()
massmailDetailsMailing ()
massmailEdit ()
getAdminUnits ()
getPlaces ()
massmailEnqueueCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
massmailEnqueue ()
massmailUnqueue ()
massmailTrigger ()
massmailUntrigger ()
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const MASSMAILEDIT = 1
const MASSMAILCREATE = 1
const MASSMAILENQUEUE = 1
const MASSMAILTRIGGER = 5
Additional Inherited Members
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 37 of file admin.ctrl.php.
Constructor & Destructor Documentation
AdminController::__construct ()
Definition at line 46 of file admin.ctrl.php.
AdminController::__destruct ()
Definition at line 52 of file admin.ctrl.php.
Member Function Documentation
AdminController::accepter ()
displays members not yet accepted into bw or in various other statuses ...
public
Returns
object
Definition at line 153 of file admin.ctrl.php.
References $member, $params, and $rights.
AdminController::accepterProcessMembers (stdClass $args, ReadOnlyObject $memory, $stuff3, $stuff4)
updates members, primarily their status
Parameters
stdClass $args - all sorts of variables
ReadOnlyObject $memory - memory related stuff
stuff stuff
stuff stuff
public
Returns
string return url
Definition at line 183 of file admin.ctrl.php.
References $member, and $rights.
AdminController::activityLogs ()
Definition at line 280 of file admin.ctrl.php.
AdminController::commentsOverview ()
comments overview method
public
Returns
object
Definition at line 207 of file admin.ctrl.php.
References $member, $params, and $rights.
AdminController::debugLogs ()
displays the php error logs
public
Returns
object
Definition at line 133 of file admin.ctrl.php.
References $member, and $rights.
AdminController::getAdminUnits ()
get admin units for country code used by enqueue to fill drop down
Returns
json encoded list of admin units
Definition at line 545 of file admin.ctrl.php.
References $countrycode, exit, and json_encode().
AdminController::getPlaces ()
get places for country code and admin unit used by enqueue to fill drop down
Returns
json encoded list of places
Definition at line 558 of file admin.ctrl.php.
References $countrycode, exit, and json_encode().
AdminController::index ()
overview page, displays tools for admins
public
Returns
object
Definition at line 103 of file admin.ctrl.php.
References $member, and $rights.
AdminController::massmail ()
overview page for mass mailings
Definition at line 454 of file admin.ctrl.php.
References $member, and $rights.
AdminController::massmailCreate ()
create a mass mailing
Definition at line 492 of file admin.ctrl.php.
References $member, and $rights.
AdminController::massmailDetails ()
show details for a mass mailing
Definition at line 503 of file admin.ctrl.php.
References $id, $member, and $rights.
AdminController::massmailDetailsMailing ()
show details about status for a mass mailing
Definition at line 515 of file admin.ctrl.php.
References $id, $member, $rights, and $type.
AdminController::massmailEdit ()
edit a mass mailing
Definition at line 532 of file admin.ctrl.php.
References $id, $member, and $rights.
AdminController::massmailEditCreateCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Massmail edit/create callback function
Definition at line 464 of file admin.ctrl.php.
References $_SESSION, and $errors.
AdminController::massmailEnqueue ()
enqueue a mass mailing
Definition at line 595 of file admin.ctrl.php.
References $id, $massmail, $member, and $rights.
AdminController::massmailEnqueueCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Massmail enqueue callback function
Definition at line 571 of file admin.ctrl.php.
References $_SESSION, $action, $count, $errors, and $massmail.
AdminController::massmailTrigger ()
trigger a mass mailing
Definition at line 621 of file admin.ctrl.php.
References $_SESSION, $count, $id, $massmail, $member, $rights, and RoxControllerBase\redirectAbsolute().
AdminController::massmailUnqueue ()
unqueue a mass mailing
Definition at line 608 of file admin.ctrl.php.
References $_SESSION, $count, $id, $massmail, $member, $rights, and RoxControllerBase\redirectAbsolute().
AdminController::massmailUntrigger ()
untrigger a mass mailing
Definition at line 634 of file admin.ctrl.php.
References $_SESSION, $count, $id, $massmail, $member, $rights, and RoxControllerBase\redirectAbsolute().
AdminController::noRights ()
displays message about not having any admin rights
public
Returns
object
Definition at line 86 of file admin.ctrl.php.
References $member, and RoxControllerBase\redirectAbsolute().
AdminController::spamOverview ()
spam overview method
public
Returns
object
Definition at line 228 of file admin.ctrl.php.
References $member, $params, and $rights.
AdminController::tempVolStart ()
tempVolStart method - will be removed after new admin pages work
public
Returns
object
Definition at line 119 of file admin.ctrl.php.
References $member, and $rights.
AdminController::treasurerEditCreateDonation ()
Treasurer edit donation method
public
Returns
object
Definition at line 381 of file admin.ctrl.php.
References $id, $member, and $rights.
AdminController::treasurerEditCreateDonationCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 340 of file admin.ctrl.php.
References $errors, $id, and $vars.
AdminController::treasurerOverview ()
Treasurer overview method
public
Returns
object
Definition at line 330 of file admin.ctrl.php.
References $member, and $rights.
AdminController::treasurerStartDonationCampaign ()
This enables the treasurer to start the donation campaign
public
Returns
object
Definition at line 425 of file admin.ctrl.php.
References $member, and $rights.
AdminController::treasurerStartDonationCampaignCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 395 of file admin.ctrl.php.
References $_SESSION, $errors, and $vars.
AdminController::treasurerStopDonationCampaign ()
This enables the treasurer to stop the donation campaign
public
Returns
object
Definition at line 438 of file admin.ctrl.php.
References $_SESSION, $member, $rights, and RoxControllerBase\redirectAbsolute().
AdminController::updateVolunteerBoard (stdClass $args, $memory, $stuff3, $stuff4)
generic board update function post callback
Parameters
stdClass $args - all sorts of variables
ReadOnlyObject $memory - memory related stuff
stuff stuff
stuff stuff
public
Returns
string return url
Definition at line 267 of file admin.ctrl.php.
AdminController::wordsDownload ()
Definition at line 302 of file admin.ctrl.php.
References $Page, and $R.
AdminController::wordsOverview ()
words overview method
public
Returns
object
Definition at line 247 of file admin.ctrl.php.
References $member, and $rights.
Field Documentation
const AdminController::MASSMAILCREATE = 1
Definition at line 40 of file admin.ctrl.php.
const AdminController::MASSMAILEDIT = 1
Definition at line 39 of file admin.ctrl.php.
const AdminController::MASSMAILENQUEUE = 1
Definition at line 41 of file admin.ctrl.php.
const AdminController::MASSMAILTRIGGER = 5
Definition at line 42 of file admin.ctrl.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/admin.ctrl.php