Rox: RoxEntityBase Class Reference
RoxEntityBase Class Reference
Public Member Functions
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
$sql_order = ''
Protected Member Functions
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
$_entity_factory
Detailed Description
Unlike an application model, an "entity" does actually represent a realworld (or imaginary) object!
This could be a group, a member, whatever.
The entity has its own database connection and can answer questions about its associations in the database.
Constructor & Destructor Documentation
RoxEntityBase::__construct ()
Member Function Documentation
RoxEntityBase::__call ($key, $args)
RoxComponentBase::__get ($key) inherited
Referenced by Member\get_messengers().
RoxComponentBase::__set ($key, $value) inherited
References $value.
RoxComponentBase::__toString () inherited
RoxModelBase::bulkLookup ($query_string, $keynames = false) inherited
This method fetches a bunch of rows from the database. It has some funny mechanics, which you can usually just ignore.
Parameters
string $query_string
array $keynames
this will trigger the funny mechanics which sort the results into a hierarchic structure
Returns
array of rows (as objects)
References $i.
Referenced by PollsModel\AddVote(), PollsModel\CancelVote(), Member\count_comments(), Blog\countComments(), LinkModel\dbFriends(), LinkModel\dbFriendsID(), LinkModel\dbLinks(), MembersModel\editPreferences(), MessagesModel\filteredMailbox(), Member\get_address(), Member\get_comments(), Member\get_comments_commenter(), Member\get_comments_written(), Member\get_trads(), GeoModel\getAllGeonameIds(), RssModel\getBlogFeed(), RssModel\getBlogFeedByAuthor(), RssModel\getBlogFeedByTag(), SqltestModel\getBWMembers(), Blog\getCategoryArray(), LinkModel\getChanges(), LinkModel\getComments(), DatabaseSummaryModel\getDatabaseFieldsSorted(), DatabaseSummaryModel\getDatabaseTablesSorted(), CommunityModel\getFaqsCategorized(), AboutModel\getFaqsCategorized(), FeedbackModel\getFeedbackCategories(), RssModel\getForumFeed(), LastcommentsModel\GetLastComments(), LinkModel\getLinkPreferences(), LinkModel\getMemberdata(), Member\getNoteCategories(), NotifyModel\getNotes(), PollsModel\GetPollResults(), Blog\getRecentPostsArray(), LinkModel\getSpecialRelation(), RssModel\getTagFeed(), SqltestModel\getTBUsers(), RssModel\getThreadFeed(), Trip\getTripsForLocation(), Trip\getTripsForUser(), NewsletterModel\Load(), PollsModel\LoadPoll(), VerifyMembersModel\LoadVerified(), VerifyMembersModel\LoadVerifiers(), PollsModel\PrepareContribute(), NewsletterModel\PreviousLetters(), LinkModel\rebuildMissingLinks(), Member\set_profile_languages(), and GeoModel\updateGeoCounters().
RoxModelBase::bulkLookup_assoc ($query_string) inherited
This is the same as the above bulkLookup, but the rows are associative arrays instead of objects.
Parameters
unknown_type $query_string
Returns
array of rows (as associative arrays)
RoxEntityBase::countAll ()
returns a count of all the rows in the entity's table
public
Returns
int
References $query, getPrimaryKey(), getTableName(), and sqlCount().
RoxEntityBase::countWhere ($where)
returns a count of all the rows in the entity's table
public
Returns
int
References $query, $table, getPrimaryKey(), getTableName(), and sqlCount().
Referenced by Post\getMemberPostCount().
RoxModelBase::createEntity () protected inherited
calls the entity factory to create an entity, passes along any arguments
Parameters
string - first parameter must be the name of the entity to create
Returns
object protected
Referenced by GeoUse\__construct(), GroupsModel\acceptGroupMember(), MembersModel\addComment(), Role\addForMember(), GroupsModel\addGroupMemberAsAdmin(), MembersModel\addRelation(), GroupsModel\banGroupMember(), PrivilegeScope\checkForEquivalentScope(), VerifyMembersModel\checkPassword(), PrivilegeScope\checkScopeExists(), MembersModel\confirmRelation(), Role\containsPrivilege(), GroupsModel\countGroupsBySearchterms(), AdminModel\countMembersWithStatus(), GroupsModel\countMyGroups(), Group\createGroup(), GroupsModel\createGroup(), NotifyModel\createNote(), NotifyModel\deleteNotes(), RelatedGroup\deleteRelatedGroup(), MembersModel\deleteRelation(), GroupsModel\findAllGroups(), NotifyModel\findAllNotes(), GroupsModel\findGroup(), RelatedGroupsModel\findGroup(), GroupsModel\findGroups(), GroupsModel\findMembersByName(), NotifyModel\findNote(), NotifyModel\findNotes(), Member\forums_posts_count(), Member\get_address(), MembersModel\get_profile_language(), Geo\getAllAlternateNames(), Geo\getAllParents(), Member\getAllPostVotes(), RightsModel\getAllRoles(), Member\getAllThreadVotes(), Geo\getAlternateName(), AdminModel\getBadComments(), Trip\getBlogGeo(), Blog\getBlogPost(), AdminModel\getBoard(), LoginModel\getBWMemberByUsername(), Geo\getChildren(), Address\getCity(), BlogEntity\getComingPosts(), Member\getComingPosts(), MembersModel\getComment(), GeoModel\getContinents(), Geo\getCountry(), Group\getEmailAcceptingMembers(), Role\getEquivalentPrivilege(), Member\getFirstAddress(), Comment\getFromMember(), Feedback\getFromMember(), GalleryModel\getGalleriesNotEmptyEntities(), BlogEntity\getGeo(), Forums\GetGroupEntity(), GroupMembership\getGroupMembers(), Member\getGroupMembership(), Group\getGroupOwners(), Member\getGroups(), RelatedGroupsModel\getGroupsForMember(), GroupsModel\getGroupsForMember(), Group\getLastLoggedInMembers(), GeoModel\getLocationById(), RoxModelBase\getLoggedInMember(), AdminModel\getMassmailRecipientsInfo(), InviteModel\getMember(), ApiModel\getMember(), Address\getMemberAddress(), Blog\getMemberByUsername(), Group\getMemberCount(), ApiModel\getMemberData(), MembersModel\getMemberFromEmail(), GroupMembership\getMemberGroups(), MemberRole\getMemberRoles(), Group\getMembers(), MembersModel\getMemberWithId(), GalleryModel\getMemberWithUserId(), MembersModel\getMemberWithUsername(), Group\getNewMembers(), ProfileNote\getNote(), Member\getNote(), ProfileNote\getNotes(), Member\getNotes(), Geo\getParent(), Forums\GetPostVote(), RolePrivilege\getPrivilege(), PrivilegeScope\getPrivilege(), RolePrivilege\getPrivilegeRoles(), Role\getPrivileges(), RelatedGroup\getRelatedGroupsLog(), RolePrivilege\getRole(), MemberRole\getRoleMembers(), RolePrivilege\getRolePrivileges(), Member\getRoles(), Role\getScopesForMemberRole(), Member\getSignupFeedback(), Comment\getToMember(), Geo\getTotalUsage(), Geo\getUsageForAllTypes(), Member\getVisitorCount(), Member\getVisitorsSubset(), Thread\getVoteResult(), Post\getVoteResult(), Thread\getVotes(), Post\getVotes(), Member\hasPrivilege(), Member\hasRole(), GroupsModel\inviteMember(), Group\isGroupOwner(), Group\isMember(), AboutModel\isVolunteer(), GroupsModel\joinGroup(), GroupsModel\leaveGroup(), VerifyMembersModel\LoadApprovedVerifiers(), loadEntities(), GeoModel\loadLocation(), GroupsModel\memberAcceptedInvitation(), RelatedGroupsModel\memberAddsRelatedGroup(), GroupsModel\memberDeclinedInvitation(), RelatedGroupsModel\memberDeletesRelatedGroup(), MemberRole\memberHasRole(), Group\memberJoin(), Group\memberLeave(), GroupsModel\notifyGroupAdmins(), Forums\prepare_notification(), AdminModel\processMembers(), GroupsModel\realImg(), Member\recordVisit(), Role\removeFromMember(), Group\removeGroupOwner(), Member\removeLanguages(), GroupsModel\resignGroupAdmin(), RoxModelBase\restoreLoggedInMember(), Forums\searchUserposts(), MembersModel\sendCommentNotification(), FeedbackModel\sendFeedback(), GroupsModel\sendInvitation(), InviteModel\sendOrComplain(), Group\setGroupOwner(), MembersModel\setLocation(), MembersModel\setSessionLanguage(), MembersModel\showAvatar(), RelatedGroupsModel\showRelatedGroupsLog(), GroupsModel\thumbImg(), AdminModel\treasurerEditCreateDonationVarsOk(), GroupsModel\updateMembershipSettings(), MembersModel\updateProfile(), MembersModel\updateRelation(), and AdminModel\updateVolunteerBoard().
RoxEntityBase::delete ()
Delete a row from a table
public
Returns
bool
Exceptions
EntityException
References $query, debug, getTableName(), isPKSet(), preparePKWhereString(), and wipeEntity().
RoxEntityBase::findAll ($offset = 0, $limit = 0)
loads all rows from a table and returns them as an array of class $this
Parameters
integer $offset - offset to start from. Defaults to 0
integer $limit - how many results to limit the query to. Defaults to 0 (no limit) public
Returns
mixed false or an array of objects of class $this
References $query, $sql_order, elseif, getTableName(), and queryForEntities().
Referenced by Note\findBySearchTerms(), Message\findBySearchTerms(), and Group\findBySearchTerms().
RoxEntityBase::findById ($id)
load an object by it's id
Parameters
int $id - id of the group to load public
Returns
mixed false or an object of class $this
References $id, $query, getPrimaryKey(), getTableName(), and queryForEntity().
Referenced by GeoAlternateName\__construct(), GeoHierarchy\__construct(), VolunteerBoard\__construct(), Role\__construct(), MemberLanguage\__construct(), Geo\__construct(), Language\__construct(), GeoType\__construct(), Privilege\__construct(), Activity\__construct(), Suggestion\__construct(), Note\__construct(), GeoUse\__construct(), SuggestionOption\__construct(), BlogEntity\__construct(), GalleryItem\__construct(), Message\__construct(), Gallery\__construct(), GalleryComment\__construct(), Feedback\__construct(), Comment\__construct(), ProfileNote\__construct(), Address\__construct(), Member\__construct(), Group\__construct(), Role\containsPrivilege(), and Role\removeFromMember().
RoxEntityBase::findBySQL ($sql)
lets you load a single entity using an sql query should only be used in cases where the other find methods won't work
Parameters
string $sql public
Returns
object
References queryForEntity().
RoxEntityBase::findBySQLMany ($sql)
lets you load an array of entities using an sql query should only be used in cases where the other find methods won't work
Parameters
string $sql public
Returns
array
References queryForEntities().
Referenced by Activity\getActivitiesForMember(), and Activity\searchActivities().
RoxEntityBase::findByWhere ($where)
load an object by a specified sql WHERE clause
Parameters
string $where - sql where clause to use public
Returns
mixed false or $this
References $query, $sql_order, getTableName(), and queryForEntity().
Referenced by PrivilegeScope\checkScopeExists(), PrivilegeScope\findById(), MemberRole\findById(), RolePrivilege\findById(), VolunteerBoard\findByName(), Role\findByName(), Post\findByPostId(), Thread\findByThreadId(), Member\findByUsername(), Privilege\findNamedPrivilege(), Group\getGroupForGeo(), GroupMembership\getMembership(), PrivilegeScope\getMemberWithRoleObjectAccess(), GeoAlternateName\getNameForLocation(), PrivilegeScope\hasAnyRoleScope(), GroupMembership\isMember(), RelatedGroup\isRelatedGroup(), GroupMembership\memberLeave(), and Role\removeFromMember().
RoxEntityBase::findByWhereMany ($where, $offset = 0, $limit = 0)
load an object by a specified sql WHERE clause
Parameters
string $where - sql where clause to use
integer $offset - offset to start from. Defaults to 0
integer $limit - how many results to limit the query to. Defaults to 0 (no limit) public
Returns
mixed false or array or entities
References $query, $sql_order, elseif, getTableName(), and queryForEntities().
Referenced by PrivilegeScope\checkForEquivalentScope(), Note\findBySearchTerms(), Message\findBySearchTerms(), Group\findBySearchTerms(), Geo\findLocationsByCoordinates(), Geo\findLocationsByName(), Group\findRelatedGroups(), GeoHierarchy\getAllChildren(), GeoHierarchy\getAllParents(), Geo\getAllParents(), Geo\getChildren(), GroupMembership\getGroupMembers(), GroupMembership\getMemberGroups(), MemberRole\getMemberRoles(), PrivilegeScope\getMembersWithRoleObjectAccess(), ProfileNote\getNotes(), RolePrivilege\getPrivilegeRoles(), RelatedGroup\getRelatedGroupsLog(), MemberRole\getRoleMembers(), RolePrivilege\getRolePrivileges(), GeoUse\getUsageForGeoByType(), and ProfileVisit\getVisitsForMember().
RoxComponentBase::get ($key) protected inherited
Referenced by SignupClosedPage\column_col3(), SignupProblemPage\column_col3(), and SignupPage\column_col3().
RoxModelBase::get_dao () protected inherited
normally the $dao should be injected. If it's not, this function creates a new one out of the blue..
RoxEntityBase::getColumns ()
returns an array of column names for the entity
public
Returns
array
References $_columns_cache, and getTableDescription().
Referenced by insert(), loadEntity(), update(), validateSelf(), and wipeEntity().
RoxModelBase::getDao () protected inherited
RoxComponentBase::getLog () protected inherited
wrapper function for MOD_log::get()
protected
Returns
object
References MOD_log\get().
Referenced by RoxComponentBase\logWrite().
RoxModelBase::getLoggedInMember () inherited
returns the currently logged in member
public
Returns
object|false
References $_SESSION, and RoxModelBase\createEntity().
Referenced by AdminTreasurerPage\__construct(), AdminTreasurerEditCreateDonationPage\__construct(), AdminTreasurerStartDonationCampaignPage\__construct(), Suggestion\addOption(), Forums\adjustThreadsCountToShow(), GroupsModel\canAccessGroupAdmin(), GroupsModel\canAccessGroupDelete(), ActivitiesModel\checkEditCreateActivityVarsOk(), Blog\commentProcess(), Blog\countRecentPosts(), GalleryModel\createGallery(), GroupsModel\createGroup(), AdminModel\createMassmail(), SuggestionsModel\createSuggestion(), MembersModel\deleteNoteForMember(), Suggestion\deleteOption(), Suggestion\editOption(), SuggestionsModel\editSuggestion(), RightsModel\getAllRoles(), SearchModel\getDefaultAdvancedOptions(), Group\getGroupOwners(), ActivitiesModel\getMyActivities(), ActivitiesModel\getMyActivitiesCount(), ActivitiesModel\getNearMeQuery(), Forums\GetPostVote(), Blog\getRecentPostIt(), Blog\getRecentPostsArray(), Blog\getStickyPostIt(), Blog\getTaggedPostsIt(), Blog\getTagsIt(), Blog\getTinyMCEPreference(), Forums\getTinyMCEPreference(), Trip\getTripData(), Trip\getTrips(), RightsModel\hasRightsAccess(), ActivitiesModel\joinLeaveActivity(), Suggestion\loadEntity(), SuggestionOption\loadEntity(), LoginModel\logout(), GroupsModel\memberAcceptedInvitation(), GroupsModel\memberDeclinedInvitation(), Trip\prepareEditData(), GroupsModel\resignGroupAdmin(), FeedbackModel\sendFeedback(), MembersModel\setCommentGuidelinesRead(), LoginModel\setPreferredLanguage(), ActivitiesModel\setRadius(), Forums\switchShowMyGroupsTopicsOnly(), Suggestion\update(), ActivitiesModel\updateActivity(), AdminModel\updateMassmail(), AdminModel\updateVolunteerBoard(), GalleryModel\uploadProcess(), and MembersModel\writeNoteForMember().
RoxModelBase::getMemoryCookie () protected inherited
Reads the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
References $_SESSION, elseif, and RoxModelBase\setMemoryCookie().
Referenced by RoxModelBase\restoreLoggedInMember().
RoxEntityBase::getPKValue ()
returns the value of the entity's primary key
public
Returns
string
References $_primary_key.
Referenced by RelatedGroup\AddRelatedGroup(), BlogEntity\delete(), RelatedGroup\deleteRelatedGroup(), GroupMembership\getMembership(), RelatedGroupsModel\getMyGroups(), GroupMembership\isMember(), RelatedGroup\isRelatedGroup(), GroupMembership\memberJoin(), GroupMembership\memberLeave(), Role\removeFromMember(), Group\setDescription(), Group\setGroupOwner(), MemberLanguage\setSpokenLanguage(), and GroupMembership\updateMembership().
RoxEntityBase::getPrimaryKey ()
returns the name of the primary key for the entity return val is string if primary key is single field array if primary key spans fields, and null for no primary key
public
Returns
string|array|null
References $_primary_key, $info, and getTableDescription().
Referenced by countAll(), countWhere(), findById(), insert(), isPKSet(), preparePKWhereString(), and update().
RoxEntityBase::getTableDescription ()
returns an array describing the table of the entity
public
Returns
array
Exceptions
EntityException
References $data, $info, and $query.
Referenced by getColumns(), getPrimaryKey(), insert(), and validateSelf().
RoxEntityBase::getTableName ()
returns the table name for the entity
public
Returns
string
References $_table_name.
Referenced by countAll(), countWhere(), delete(), findAll(), findById(), findByWhere(), findByWhereMany(), and GroupMembership\getGroupMembersCount().
RoxEntityBase::getValidationErrors ()
References $_validation_errors.
RoxComponentBase::getValues () protected inherited
RoxComponentBase::getVersionInfo () protected inherited
returns the revision number saved in revision.txt
protected
Returns
string
References $version.
Referenced by FeedbackModel\sendFeedback().
RoxComponentBase::getWords () protected inherited
returns an instance of the MOD_words class
protected
Returns
object
Referenced by VisualComponent\__call(), GroupsController\acceptInvitation(), GroupsController\addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), GeoPopupPage\body(), GalleryDeletePage\breadcrumbs(), GalleryBasePage\breadcrumbs(), SuggestionsController\changeStateCallback(), MyVisitorsPage\column_col3(), GalleryFlickrPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryAllImagesPage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), LinkUpdatePage\column_col3(), HellouniversePage\column_col3(), GeoAdminPage\column_col3(), GalleryDeletePage\column_col3(), NewsletterPage\column_col3(), FeedbackSentPage\column_col3(), VerifyMembersNotActivePage\column_col3(), VerifyMyselfPage\column_col3(), OneNewsLetterPage\column_col3(), GalleryManagePage\column_col3(), GalleryAllGalleriesPage\column_col3(), VerifiedApprovedVerifiers\column_col3(), ActivitiesFindPage\column_col3(), GroupStartPage\column_col3(), GroupMemberSettingsPage\column_col3(), AboutFaqPage\column_col3(), GroupDeletePage\column_col3(), GroupJoinPage\column_col3(), GroupWikiPage\column_col3(), GroupAddRelatedGroupPage\column_col3(), GroupDeleteRelatedGroupPage\column_col3(), GroupLeavePage\column_col3(), GroupForumPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), AboutFaqsectionPage\column_col3(), PollsPage\column_col3(), VerifiedMembersViewPage\column_col3(), HellouniverseTabbedPage\column_col3(), GroupForumsOverviewPage\column_col3(), GroupsController\declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), Member\get_all_relations(), MembersModel\get_relation_between_members(), Member\get_trad_by_tradid(), Group\getDescription(), FullPagePager\getHtml(), Note\getIdRelMember(), Forums\GetLanguageName(), LastCommentsPage\getLastCommentsTitle(), PageWithRoxLayout\getPage_meta_description(), PageWithRoxLayout\getPage_meta_keyword(), UpdateMandatoryPage\getPageTitle(), AboutTheideaPage\getPageTitle(), ActivitiesBasePage\getPageTitle(), CityPage\getPageTitle(), CountriesPage\getPageTitle(), CountryPage\getPageTitle(), RegionPage\getPageTitle(), SafetyBasePage\getPageTitle(), SearchMembersBasePage\getPageTitle(), SuggestionsBasePage\getPageTitle(), NewsletterPage\getPageTitle(), OneNewsLetterPage\getPageTitle(), GroupsBasePage\getPageTitle(), VerifiedMembersViewPage\getPageTitle(), PollsPage\getPageTitle(), SuggestionsBasePage\getStateSelect(), DebugPage\getSubmenuItems(), GalleryUserPage\getSubmenuItems(), AboutBasePage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), PageWithHTML\head(), MembersController\index_loggedIn(), GroupsController\joined(), GroupsController\kickMember(), Forums\LanguageChoices(), GroupsController\leave(), GroupsController\left(), PageWithRoxLayout\leftoverTranslationLinks(), AboutFaqsectionPage\leftSidebar(), AboutFaqPage\leftSidebar(), InactiveProfilePage\leftsidebar(), AdminMassMailEnqueuePage\leftSidebar(), VerifyMembersPage\leftSidebar(), AdminMassMailDetailsPage\leftSidebar(), AdminMassMailEditCreatePage\leftSidebar(), VerifiedApprovedVerifiers\leftSidebar(), VerifiedMembersViewPage\leftSidebar(), PollsPage\leftSidebar(), MemberPage\leftsidebar(), LoginController\loginCallback(), GalleryController\manage(), MessagesPageWithMailbox\messageActions(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), NotifyAdminPage\notesActions(), GroupsModel\notifyGroupAdmins(), PageWithRoxLayout\quicksearch(), GroupsController\resignAsAdmin(), SuggestionsController\restoreOption(), GeoController\SelectorInclude(), GroupsModel\sendInvitation(), Group\setDescription(), PageWithRoxLayout\SetMetaKey(), AbstractBasePage\showTemplate(), PageWithRoxLayout\submenu(), MessagesBasePage\teaserContent(), GroupSettingsPage\teaserContent(), GroupsSearchPage\teaserContent(), GroupsMyGroupsPage\teaserContent(), GroupsCreationPage\teaserContent(), GroupInvitePage\teaserContent(), TourPage\teaserContent(), GroupsFeaturedPage\teaserContent(), GroupsOverviewPage\teaserContent(), LastCommentsPage\teaserContent(), GroupForumsOverviewPage\teaserContent(), GroupsBasePage\teaserContent(), ResetPasswordPage\teaserHeadline(), ResetPasswordFinishPage\teaserHeadline(), VerifyNoMemberSpecifiedPage\teaserHeadline(), AboutBasePage\teaserHeadline(), GalleryImageNotFoundPage\teaserHeadline(), GalleryAvatarsPage\teaserHeadline(), AboutStatisticsPage\teaserHeadline(), VerifyMyselfPage\teaserHeadline(), VerifyMembersNotActivePage\teaserHeadline(), VerifyMembersPage\teaserHeadline(), GalleryBasePage\teaserHeadline(), SearchMembersBasePage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), SuggestionsBasePage\teaserHeadline(), OneNewsLetterPage\teaserHeadline(), VerifiedMembersViewPage\teaserHeadline(), PollsPage\teaserHeadline(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), GroupMembership\updateMembership(), GalleryController\upload(), GalleryController\uploadedProcess(), GalleryController\user(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
RoxEntityBase::init ($store, $dao)
init function, replaces part of the __construct function
Parameters
array $parameters - array of parameters to store in the entity
object $dao - data access object public
RoxEntityBase::insert ()
Attempts to insert a row into the database, in the relevant table will build a SQL query based on the set variables in the object
Returns
bool public
Exceptions
EntityException
References $description, $info, $query, getColumns(), getPrimaryKey(), getTableDescription(), and validateField().
Referenced by RelatedGroup\AddRelatedGroup(), Group\createGroup(), MemberRole\createMemberRoleLink(), Note\createNote(), RolePrivilege\createRolePrivilegeLink(), PrivilegeScope\createScope(), GroupMembership\memberJoin(), and MemberLanguage\setSpokenLanguage().
RoxEntityBase::isLoaded ()
Lets the world know if it's been loaded with data properly or not
public
Returns
bool
References $_has_loaded.
Referenced by Role\addForMember(), Member\count_comments(), MemberRole\createMemberRoleLink(), RolePrivilege\createRolePrivilegeLink(), PrivilegeScope\createScope(), Trip\createTrip(), Group\deleteGroup(), MemberLanguage\deleteMembersLanguages(), Note\deleteNote(), RelatedGroup\deleteRelatedGroup(), PrivilegeScope\deleteScope(), Geo\getAllAlternateNames(), GeoHierarchy\getAllChildren(), GeoHierarchy\getAllParents(), Geo\getAllParents(), GeoUse\getAllUsageForGeo(), Geo\getAlternateName(), Geo\getAncestorLine(), Feedback\getCategory(), Feedback\getCategoryData(), Geo\getChildren(), Address\getCity(), Geo\getCountry(), Group\getDescription(), Member\getFirstAddress(), Feedback\getFromMember(), Comment\getFromMember(), Group\getGroupForGeo(), Group\getGroupOwners(), Note\getIdRelMember(), Address\getMemberAddress(), Post\getMemberPostCount(), Role\getMembers(), Geo\getName(), GeoAlternateName\getNameForLocation(), Member\getOldRights(), Geo\getParent(), RolePrivilege\getPrivilege(), PrivilegeScope\getPrivilege(), Role\getPrivileges(), RolePrivilege\getRole(), Role\getScopesForMemberRole(), Feedback\getSignupFeedback(), Member\getSignupFeedback(), Note\getText(), Comment\getToMember(), Geo\getTotalUsage(), Geo\getUsageForAllTypes(), GeoUse\getUsageForGeoByType(), ProfileVisit\getVisitCountForMember(), ProfileVisit\getVisitingMembersSubset(), Member\getVisitorCount(), ProfileVisit\getVisitsForMember(), Thread\getVoteResult(), Post\getVoteResult(), Thread\getVotes(), Post\getVotes(), Member\hasPrivilege(), PrivilegeScope\hasScope(), Member\isActive(), Member\isBanned(), Geo\isBorough(), Geo\isCity(), Geo\isCountry(), Thread\isDeleted(), Group\isGroupOwner(), Member\isNotActiveHidden(), Member\isPending(), Geo\isRegion(), Geo\placeType(), ProfileVisit\recordVisit(), Member\recordVisit(), Role\removeFromMember(), Group\removeGroupOwner(), Member\removeLanguages(), MemberRole\removeMemberRoleLink(), Group\setDescription(), Group\setGroupOwner(), Language\setLanguage(), Member\setPassword(), MemberLanguage\setSpokenLanguage(), GroupMembership\updateMembership(), Note\updateNote(), Group\updateSettings(), and GroupMembership\updateStatus().
RoxEntityBase::isPKSet ()
checks whether all the primary key fields of an entity are set
Returns
bool public
References elseif, and getPrimaryKey().
Referenced by Role\containsPrivilege(), delete(), Role\getEquivalentPrivilege(), Member\getRoles(), Member\hasRole(), loadEntity(), and update().
RoxEntityBase::loadEntities ($result) protected
Creates entities from a result set, using findById
Parameters
resource $result - the DB resource result from the lookup protected
Returns
array
References $data, and RoxModelBase\createEntity().
Referenced by queryForEntities().
RoxEntityBase::loadEntity ($data) protected
Fills up an object with data
Parameters
array $data - associative array used to fill object with data protected
Returns
bool
References $_has_loaded, $data, getColumns(), isPKSet(), and wipeEntity().
Referenced by loadFromArray(), and queryForEntity().
RoxEntityBase::loadFromArray ($data)
Creates entities from a result set, using findById
Parameters
array $data - an array of data based on a DB lookup protected
Returns
object - passes itself back
References $data, and loadEntity().
RoxComponentBase::logWrite ($string, $type = 'Log') protected inherited
wrapper for calls to MOD_log::get->write()
Parameters
string $string
string $type protected
References $type, and RoxComponentBase\getLog().
Referenced by GroupsController\acceptInvitation(), GroupsController\acceptMember(), MembersModel\addComment(), GroupsController\addMemberAsAdmin(), MembersModel\addRelation(), GroupsController\banMember(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), GroupsController\createGroupCallback(), GroupsController\declineInvitation(), GroupsController\delete(), MembersModel\delete_translation_multiple(), FeedbackModel\feedbackMail(), MembersController\index_loggedIn(), GroupsController\inviteMember(), GroupsController\inviteMemberAjax(), GroupsController\joined(), GroupsController\kickMember(), GroupsController\left(), Geo\placeType(), AdminModel\processMembers(), GroupsController\resignAsAdmin(), MembersModel\set_preference(), MembersModel\set_public_profile(), MembersModel\setLocation(), MembersModel\updateProfile(), and MembersModel\updateRelation().
RoxEntityBase::preparePKWhereString () protected
returns a string to serve as a where clause, uniquely specifying a row
Returns
string|false protected
References elseif, and getPrimaryKey().
Referenced by delete(), and update().
RoxEntityBase::queryForEntities ($query) protected
runs an SQL query to find several entities
Parameters
string $query protected
Returns
array
Exceptions
EntityException
References $query, debug, and loadEntities().
Referenced by findAll(), findBySQLMany(), and findByWhereMany().
RoxEntityBase::queryForEntity ($query) protected
runs an SQL query to find an entity, loads the current entity with data if it finds it
Parameters
string $query protected
Returns
object|bool
Exceptions
EntityException
References $data, $query, debug, and loadEntity().
Referenced by findById(), findBySQL(), and findByWhere().
RoxComponentBase::refresh_get ($key) inherited
RoxModelBase::restoreLoggedInMember () inherited
Restore session if memory cookie exists
References RoxModelBase\createEntity(), and RoxModelBase\getMemoryCookie().
RoxModelBase::setMemoryCookie ($id, $seriesToken = '', $authToken = '') protected inherited
Sets the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
References $id.
Referenced by RoxModelBase\getMemoryCookie().
RoxModelBase::singleLookup ($query_string) inherited
Referenced by PollsModel\AddChoice(), GeoModel\addHierarchy(), VerifyMembersModel\AddNewVerified(), MembersModel\addRelation(), PollsModel\AddVote(), PollsModel\CancelVote(), PollsModel\CanUserContribute(), MessagesModel\CaptchaNeeded(), VerifyMembersModel\CheckAndGetUsername(), LoginModel\checkBWPassword(), MembersModel\confirmRelation(), Member\count_mynotes(), LoginModel\createMissingTBUser(), MessagesModel\deleteMessage(), MembersModel\deleteRelation(), Forums\DeleteVoteForPost(), LoginModel\encryptPasswordBW(), LanguageLookupModel\findLanguageWithCode(), Member\get_publicProfile(), Member\get_userid(), Member\get_verification_status(), DonateModel\getCampaignValues(), LinkModel\getChanges(), AdminModel\getCountryCodeForGeonameId(), GeoModel\getDataById(), AdminModel\getDonation(), AdminModel\getDonationCampaignStatus(), FeedbackModel\getFeedbackCategory(), AdminModel\getGeonameIdForCountryCode(), Forums\GetIdThread(), RoxFrontRouterModel\getLanguage(), MessagesModel\getMember(), LinkModel\getMemberdata(), MembersModel\getMemberFromEmail(), LinkModel\getMemberID(), GalleryModel\getMemberWithUserId(), MessagesModel\getMessage(), PollsModel\GetPollResults(), RoxFrontRouterModel\getPossibleUrlLanguage(), SearchModel\getResultsForLocation(), LoginModel\getTBUserForBWMember(), GeoModel\getUsagetypeId(), Places\getWikiPage(), PollsModel\HasAlreadyContributed(), MessagesModel\hasMessageLimitExceeded(), PollsModel\IsMemberAllowed(), CommunityModel\isVolunteer(), NewsletterModel\Load(), VerifyMembersModel\LoadApprovedVerifiers(), PollsModel\LoadList(), PollsModel\LoadPoll(), PollsModel\PrepareContribute(), MessagesModel\sendOrComplain(), MembersModel\set_preference(), MembersModel\set_profile_language(), MembersModel\set_public_profile(), LoginModel\setBWMemberAsLoggedIn(), MembersModel\setLocation(), LoginModel\setupBWSession(), SearchModel\suggestLocationsFromDatabase(), PollsModel\UpdateChoice(), GeoModel\updateGeonameId(), PollsModel\UpdatePoll(), MembersModel\updateRelation(), MessagesModel\updateSpamInfo(), GeoModel\updateUsageCounter(), and Forums\VoteForPost().
RoxModelBase::singleLookup_assoc ($query_string) inherited
Referenced by Member\getProfilePictureID().
RoxEntityBase::sqlCount ($query) protected
executes sql to count rows in a table
Parameters
string $query protected
Returns
int
Exceptions
EntityException
References $data, $query, and debug.
Referenced by countAll(), countWhere(), Activity\getActivitiesForMemberCount(), and Activity\searchActivitiesCount().
RoxEntityBase::update ()
Attempts to update a row into the database, in the relevant table will build a SQL query based on the set variables in the object
Returns
bool public
Exceptions
EntityException
References $query, debug, getColumns(), getPrimaryKey(), isPKSet(), preparePKWhereString(), and validateSelf().
Referenced by RelatedGroup\deleteRelatedGroup(), Suggestion\loadEntity(), Group\setDescription(), GroupMembership\updateMembership(), Note\updateNote(), Group\updateSettings(), GroupMembership\updateStatus(), and VolunteerBoard\updateText().
RoxEntityBase::validateField ($key, $info) protected
Checks a supplied key and value against the $_fields_array to check for validity
Parameters
string $key - the field to check
array $info - table description protected
Returns
bool
References $info, $type, and $value.
Referenced by insert(), and validateSelf().
RoxEntityBase::validateSelf ()
Checks if the vars set in an entity are valid compares with the entities $_fields_array to make sure that values needed are present and the right type
Parameters
bool $strict - whether to do a strict check or a relaxed check
Returns
bool public
References $info, getColumns(), getTableDescription(), and validateField().
Referenced by update().
RoxEntityBase::wipeEntity ()
wipes an entity clean for data and resets the has_loaded flag
public
References getColumns().
Referenced by delete(), and loadEntity().
Field Documentation
RoxEntityBase::$_columns_cache = array() protected
Referenced by getColumns().
RoxModelBase::$_entity_factory protected inherited
RoxEntityBase::$_has_loaded = false protected
Referenced by isLoaded(), and loadEntity().
RoxEntityBase::$_primary_key protected
Referenced by getPKValue(), and getPrimaryKey().
RoxEntityBase::$_table_name protected
Referenced by getTableName().
RoxEntityBase::$_validation_errors = array() protected
Referenced by getValidationErrors().
RoxEntityBase::$_validations = array() protected
RoxEntityBase::$sql_order = ''
Referenced by findAll(), findByWhere(), and findByWhereMany().
The documentation for this class was generated from the following file:
entity.php