Rox: PollsModel Class Reference
PollsModel Class Reference
Public Member Functions
CanUserContribute ($IdPoll, $Email="")
GetPollResults ($IdPoll, $Email="", $IdMember=0)
HasAlreadyContributed ($IdPoll, $Email="", $IdMember=0)
UpdatePoll ($post)
AddChoice ($post)
UpdateChoice ($post)
AddVote ($post, $Email="", $IdMember=0)
CancelVote ($IdPoll, $Email="", $IdMember=0)
PrepareContribute ($IdPoll=0)
LoadPoll ($IdPoll=0)
LoadList ($PollStatus="")
IsMemberAllowed ($rPoll, $_IdMember=0)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 11 of file polls.model.php.
Member Function Documentation
PollsModel::AddChoice ($post)
this function allows to add a choice to a give poll
Postcondition
all parameters from argpost returns true if choice was added with success
Definition at line 212 of file polls.model.php.
References $_SESSION, $IdPoll, $rPoll, $words, MOD_log\get(), MOD_right\get(), and RoxModelBase\singleLookup().
PollsModel::AddVote ($post, $Email = "", $IdMember = 0)
this function adds the vote for a given member
Postcondition
is the array of the arg_post to be given by the controller $Email is the mandatory Email which must be provided for a not logged user (optional) $IdMember id of the member (optional) returns true if the vote is added with success
Definition at line 285 of file polls.model.php.
References $IdPoll, $ii, $rPoll, RoxModelBase\bulkLookup(), elseif, MOD_log\get(), IsMemberAllowed(), and RoxModelBase\singleLookup().
PollsModel::CancelVote ($IdPoll, $Email = "", $IdMember = 0)
this function cancels the vote for a given member is the id of the poll $Email is the mandatory Email which must be provided for a not logged user (optional) $IdMember id of the member (optional) returns true if the vote is cancelled
Definition at line 399 of file polls.model.php.
References $IdPoll, $ii, $rPoll, RoxModelBase\bulkLookup(), elseif, MOD_log\get(), and RoxModelBase\singleLookup().
PollsModel::CanUserContribute ($IdPoll, $Email = "")
this function returns true if the user can contribute to this poll, false elsewher is the id of the poll $Email is the mandatory Email which must be provided for a not logged user
Definition at line 18 of file polls.model.php.
References $_SESSION, $IdPoll, $rPoll, MOD_log\get(), HasAlreadyContributed(), and RoxModelBase\singleLookup().
Referenced by LoadList().
PollsModel::GetPollResults ($IdPoll, $Email = "", $IdMember = 0)
this function returns false if the result of the poll are not available is the id of the poll
Definition at line 67 of file polls.model.php.
References $Data, $IdPoll, $rPoll, RoxModelBase\bulkLookup(), and RoxModelBase\singleLookup().
PollsModel::HasAlreadyContributed ($IdPoll, $Email = "", $IdMember = 0)
this function returns true if the user has allready contributed to the specific post is the id of the poll $Email is the mandatory Email which must be provided for a not logged user (optional) $IdMember id of the member (optional)
Definition at line 90 of file polls.model.php.
References $IdPoll, and RoxModelBase\singleLookup().
Referenced by CanUserContribute(), LoadList(), and PrepareContribute().
PollsModel::IsMemberAllowed ($rPoll, $_IdMember = 0)
this function retruns true if th member is allowed to contribute to the poll according to his groups membership $rPoll is a record of a poll table $IdMember is the member to consider if it is 0, teh current member will be used
Definition at line 595 of file polls.model.php.
References $_SESSION, $rPoll, and RoxModelBase\singleLookup().
Referenced by AddVote(), and LoadList().
PollsModel::LoadList ($PollStatus = "")
this function load the list of the polls with a certain status is the statuis which allow to filter for the status of some poll
Definition at line 513 of file polls.model.php.
References $_SESSION, $words, CanUserContribute(), MOD_right\get(), HasAlreadyContributed(), IsMemberAllowed(), and RoxModelBase\singleLookup().
PollsModel::LoadPoll ($IdPoll = 0)
this function loads the data of a poll is the id of the poll
Definition at line 498 of file polls.model.php.
References $Data, $IdPoll, RoxModelBase\bulkLookup(), and RoxModelBase\singleLookup().
PollsModel::PrepareContribute ($IdPoll = 0)
this function prepares the contribution for a poll is the id of the poll
Definition at line 480 of file polls.model.php.
References $Data, $IdPoll, RoxModelBase\bulkLookup(), HasAlreadyContributed(), and RoxModelBase\singleLookup().
PollsModel::UpdateChoice ($post)
this function allows to add a choice to a give poll
Postcondition
all parameters from argpost returns true if choice was added with success
Definition at line 250 of file polls.model.php.
References $_SESSION, $IdPoll, $rPoll, $words, MOD_log\get(), MOD_right\get(), and RoxModelBase\singleLookup().
PollsModel::UpdatePoll ($post)
this function allows to create/update poll
Postcondition
is the array of the arg_post to be given by the controller returns true if the poll is added with success according to $post['IdPoll'] the poll will be inserted or updated
Definition at line 108 of file polls.model.php.
References $_SESSION, $IdPoll, $ii, $rPoll, $words, MOD_log\get(), MOD_right\get(), and RoxModelBase\singleLookup().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/polls/polls.model.php