Rox: RequestRouter Class Reference
RequestRouter Class Reference
Public Member Functions
__construct ()
init ()
addRoute ($name, $url, $controller, $method= 'index', $callback=false)
getRoute ($name)
matchRoute ($uri, $matchcallbacks=false)
url ($route, $vars=array(), $add_base=true)
findRoute ($request)
controllerClassnameForString ($name)
getRequestAndArgs ()
Protected Member Functions
translate ($name)
defaultControllerClassname ()
loadRoutingAliasTable ()
iniParse ($file, &$alias_table)
iniWrite ($file, $alias_table)
Detailed Description
Definition at line 4 of file requestrouter.class.php.
Constructor & Destructor Documentation
RequestRouter::__construct ()
Definition at line 20 of file requestrouter.class.php.
References init().
Member Function Documentation
RequestRouter::addRoute ($name, $url, $controller, $method = 'index', $callback = false)
adds a temporary route to the routes
Parameters
string $name - name of the route
string $url - the route itself
string $controller - name of the controller
string $method - name of the method to call public
Returns
bool
Definition at line 43 of file requestrouter.class.php.
References $callback, $name, and $url.
RequestRouter::controllerClassnameForString ($name)
find the name of the controller to be called, given the first part of the request string
Parameters
string $name first part of request
Returns
string controller classname
Definition at line 192 of file requestrouter.class.php.
References $name, defaultControllerClassname(), and translate().
Referenced by findRoute().
RequestRouter::defaultControllerClassname () protected
if no controller fits the request, use a RoxController
Returns
string classname of the default controller
Definition at line 234 of file requestrouter.class.php.
Referenced by controllerClassnameForString().
RequestRouter::findRoute ($request)
checks to see if a route matches the incoming request checks through the _routes array, to see if something matches
public
Parameters
array $request
Returns
array
Definition at line 172 of file requestrouter.class.php.
References $request, controllerClassnameForString(), and matchRoute().
RequestRouter::getRequestAndArgs ()
returns the request uri plus arguments from get and post
public
Returns
object
Definition at line 295 of file requestrouter.class.php.
Referenced by PagerWidget\prepare().
RequestRouter::getRoute ($name)
returns a given route if it is set
Parameters
string $name - name of the route to return public
Returns
array
Definition at line 61 of file requestrouter.class.php.
References $name.
Referenced by url().
RequestRouter::iniParse ($file, & $alias_table) protected
Definition at line 263 of file requestrouter.class.php.
References $value.
Referenced by loadRoutingAliasTable().
RequestRouter::init ()
Definition at line 25 of file requestrouter.class.php.
Referenced by __construct().
RequestRouter::iniWrite ($file, $alias_table) protected
Definition at line 276 of file requestrouter.class.php.
Referenced by loadRoutingAliasTable().
RequestRouter::loadRoutingAliasTable () protected
Definition at line 240 of file requestrouter.class.php.
References iniParse(), and iniWrite().
Referenced by translate().
RequestRouter::matchRoute ($uri, $matchcallbacks = false)
looks for a matching route in the set routes
Parameters
string $uri - uri to check public
Returns
array - empty if nothing found, otherwise full of good stuff
Definition at line 77 of file requestrouter.class.php.
References $i, $matches, $uri, $url, and $vars.
Referenced by findRoute().
RequestRouter::translate ($name) protected
replace the first part of the request by something else.
Parameters
unknown_type $name
Returns
unknown
Definition at line 214 of file requestrouter.class.php.
References $name, and loadRoutingAliasTable().
Referenced by controllerClassnameForString().
RequestRouter::url ($route, $vars = array(), $add_base = true)
returns a url string, based on the routes url but with with placeholders replaced
Parameters
string $route - name of route to get url for
array $vars - vars to use instead of placeholders public
Returns
string
Definition at line 129 of file requestrouter.class.php.
References $matches, $url, $vars, and getRoute().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/routing/requestrouter.class.php