Rox: ForumsController Class Reference
ForumsController Class Reference
Public Member Functions
__construct ()
__destruct ()
topMenu ($currentTab)
get_forums_uri ()
index ($subforum=false)
showExternalGroupThreads ($groupId, $showsticky=true, $showNewTopicButton=true)
showExternalSuggestionsThread ($suggestionId, $groupId, $threadId)
showExternalSuggestionsThreadReply ($suggestionId, $groupId, $threadId, $urlpart)
showExternalLatest ($showGroups=false)
editProcess ()
createProcess ()
replyProcess ()
replySuggestionsProcess ()
reportpostProcess ()
ModeratorEditPostProcess ()
ModeratorEditTagProcess ()
delProcess ()
mygroupsonlyProcess ()
morelessthreadsProcess ()
Data Fields
const ACTION_VIEW = 0
const ACTION_NEW = 1
const ACTION_EDIT = 2
const ACTION_REPLY = 3
const ACTION_SUGGEST = 4
const ACTION_DELETE = 5
const ACTION_LOCATIONDROPDOWNS = 6
const ACTION_SEARCH_USERPOSTS = 7
const ACTION_RULES = 8
const ACTION_SEARCH_SUBSCRIPTION =9
const ACTION_SUBSCRIBE =10
const ACTION_MODERATOR_FULLEDITPOST =11
const ACTION_MODERATOR_EDITTAG =12
const ACTION_MODEDIT = 13
const ACTION_TRANSLATE = 14
const ACTION_VIEW_CATEGORY = 15
const ACTION_VIEW_LASTPOSTS = 16
const ACTION_VOTE_POST = 17
const ACTION_DELETEVOTE_POST = 18
const ACTION_REPORT_TO_MOD = 19
const ACTION_VIEW_LANDING = 20
const ACTION_VIEW_FORUM = 21
const ACTION_VIEW_GROUPS = 22
Protected Attributes
$BW_Right
$BW_Flag
$request
Detailed Description
Definition at line 12 of file forums.ctrl.php.
Constructor & Destructor Documentation
ForumsController::__construct ()
Definition at line 21 of file forums.ctrl.php.
References MOD_right\get(), MOD_flag\get(), and get_forums_uri().
ForumsController::__destruct ()
Definition at line 33 of file forums.ctrl.php.
Member Function Documentation
ForumsController::createProcess ()
Definition at line 559 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::delProcess ()
Definition at line 634 of file forums.ctrl.php.
Referenced by index().
ForumsController::editProcess ()
Definition at line 547 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::get_forums_uri ()
Definition at line 42 of file forums.ctrl.php.
References $request.
Referenced by __construct().
ForumsController::index ($subforum = false)
index is called when http request = ./forums or during a new topic/edit of a group
Definition at line 58 of file forums.ctrl.php.
References $_SESSION, $BW_Right, $callbackId, $member, $noForumNewTopicButton, $request, $User, $view, break, createProcess(), Forums\CV_TOPMODE_LANDING, debug, delProcess(), editProcess(), elseif, MOD_log\get(), MOD_bw_user_Auth\isBWLoggedIn(), APP_User\login(), ModeratorEditPostProcess(), ModeratorEditTagProcess(), morelessthreadsProcess(), mygroupsonlyProcess(), replyProcess(), and reportpostProcess().
Referenced by GroupForumsOverviewPage\column_col3().
ForumsController::ModeratorEditPostProcess ()
Definition at line 608 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::ModeratorEditTagProcess ()
Definition at line 621 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::morelessthreadsProcess ()
Definition at line 650 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::mygroupsonlyProcess ()
Definition at line 639 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::replyProcess ()
Definition at line 571 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::replySuggestionsProcess ()
Definition at line 583 of file forums.ctrl.php.
References $callbackId, and SuggestionsModel\getGroupId().
Referenced by showExternalSuggestionsThreadReply().
ForumsController::reportpostProcess ()
Definition at line 596 of file forums.ctrl.php.
References $callbackId.
Referenced by index().
ForumsController::showExternalGroupThreads ($groupId, $showsticky = true, $showNewTopicButton = true)
show latest threads belonging to a group
Definition at line 478 of file forums.ctrl.php.
References $request, and $showNewTopicButton.
ForumsController::showExternalLatest ($showGroups = false)
Displays a teaser list with latest threads
Parameters
bool $showGroups Set true if group name and link should be shown in teasers
Definition at line 533 of file forums.ctrl.php.
References $member, $request, and Forums\CV_TOPMODE_FORUM.
ForumsController::showExternalSuggestionsThread ($suggestionId, $groupId, $threadId)
shows one thread of the suggestions group
Definition at line 493 of file forums.ctrl.php.
References $request.
ForumsController::showExternalSuggestionsThreadReply ($suggestionId, $groupId, $threadId, $urlpart)
allows to reply to a thread in the suggestions group
Definition at line 509 of file forums.ctrl.php.
References $callbackId, $request, and replySuggestionsProcess().
ForumsController::topMenu ($currentTab)
Definition at line 38 of file forums.ctrl.php.
Field Documentation
ForumsController::$BW_Flag protected
Definition at line 18 of file forums.ctrl.php.
ForumsController::$BW_Right protected
Definition at line 17 of file forums.ctrl.php.
Referenced by index().
ForumsController::$request protected
Definition at line 19 of file forums.ctrl.php.
Referenced by get_forums_uri(), index(), showExternalGroupThreads(), showExternalLatest(), showExternalSuggestionsThread(), and showExternalSuggestionsThreadReply().
const ForumsController::ACTION_DELETE = 5
Definition at line 669 of file forums.ctrl.php.
const ForumsController::ACTION_DELETEVOTE_POST = 18
Definition at line 682 of file forums.ctrl.php.
const ForumsController::ACTION_EDIT = 2
Definition at line 666 of file forums.ctrl.php.
const ForumsController::ACTION_LOCATIONDROPDOWNS = 6
Definition at line 670 of file forums.ctrl.php.
const ForumsController::ACTION_MODEDIT = 13
Definition at line 677 of file forums.ctrl.php.
const ForumsController::ACTION_MODERATOR_EDITTAG =12
Definition at line 676 of file forums.ctrl.php.
const ForumsController::ACTION_MODERATOR_FULLEDITPOST =11
Definition at line 675 of file forums.ctrl.php.
const ForumsController::ACTION_NEW = 1
Definition at line 665 of file forums.ctrl.php.
const ForumsController::ACTION_REPLY = 3
Definition at line 667 of file forums.ctrl.php.
const ForumsController::ACTION_REPORT_TO_MOD = 19
Definition at line 683 of file forums.ctrl.php.
const ForumsController::ACTION_RULES = 8
Definition at line 672 of file forums.ctrl.php.
const ForumsController::ACTION_SEARCH_SUBSCRIPTION =9
Definition at line 673 of file forums.ctrl.php.
const ForumsController::ACTION_SEARCH_USERPOSTS = 7
Definition at line 671 of file forums.ctrl.php.
const ForumsController::ACTION_SUBSCRIBE =10
Definition at line 674 of file forums.ctrl.php.
const ForumsController::ACTION_SUGGEST = 4
Definition at line 668 of file forums.ctrl.php.
const ForumsController::ACTION_TRANSLATE = 14
Definition at line 678 of file forums.ctrl.php.
const ForumsController::ACTION_VIEW = 0
Definition at line 664 of file forums.ctrl.php.
const ForumsController::ACTION_VIEW_CATEGORY = 15
Definition at line 679 of file forums.ctrl.php.
const ForumsController::ACTION_VIEW_FORUM = 21
Definition at line 685 of file forums.ctrl.php.
const ForumsController::ACTION_VIEW_GROUPS = 22
Definition at line 686 of file forums.ctrl.php.
const ForumsController::ACTION_VIEW_LANDING = 20
Definition at line 684 of file forums.ctrl.php.
const ForumsController::ACTION_VIEW_LASTPOSTS = 16
Definition at line 680 of file forums.ctrl.php.
const ForumsController::ACTION_VOTE_POST = 17
Definition at line 681 of file forums.ctrl.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/forums/forums.ctrl.php