Rox: BlogController Class Reference
BlogController Class Reference
Public Member Functions
__construct ()
__destruct ()
index ()
createProcess ($args, $action, $mem_redirect, $mem_resend)
deleteProcess ($args, $action, $mem_redirect, $mem_resend)
editProcess ($args, $action, $mem_redirect, $mem_resend)
singlePost ($postId, $showComments=true)
userPosts ($userHandle)
stickyPosts ()
commentProcess ($args, $action, $mem_redirect, $mem_resend)
categoryProcess ($args, $action, $mem_redirect, $mem_resend)
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 11 of file blog.ctrl.php.
Constructor & Destructor Documentation
BlogController::__construct ()
Definition at line 15 of file blog.ctrl.php.
BlogController::__destruct ()
Definition at line 21 of file blog.ctrl.php.
Member Function Documentation
BlogController::categoryProcess ($args, $action, $mem_redirect, $mem_resend)
handles forms from blog/cat/
Parameters
object $args
object $action
object $mem_redirect
object $mem_resend public
Returns
false|string
Definition at line 769 of file blog.ctrl.php.
References $mem_redirect, and $vars.
BlogController::commentProcess ($args, $action, $mem_redirect, $mem_resend)
handles comment submissions
Parameters
object $args
object $action
object $mem_redirect
object $mem_resend public
Returns
false|string
Definition at line 742 of file blog.ctrl.php.
References $request, and $vars.
BlogController::createProcess ($args, $action, $mem_redirect, $mem_resend)
Processing creation of a blog.
This is a POST callback function.
Sets following errors in POST vars: title - invalid(empty) title. text - invalid(empty) text. startdate - wrongly formatted start date. enddate - wrongly formatted end date. duration - empty enddate and invalid duration. category - category is not belonging to user. trip - trip is not belonging to user. inserror - error performing db insertion. tagerror - error while updating tags.
Definition at line 467 of file blog.ctrl.php.
References $mem_redirect, $member, $request, $vars, PException\__toString(), debug, Blog\FLAG_VIEW_PRIVATE, Blog\FLAG_VIEW_PROTECTED, and Trip\touchTrip().
BlogController::deleteProcess ($args, $action, $mem_redirect, $mem_resend)
Definition at line 566 of file blog.ctrl.php.
References $member, and $vars.
BlogController::editProcess ($args, $action, $mem_redirect, $mem_resend)
Processing edit of a blog.
This is a POST callback function.
Sets following errors in POST vars: title - invalid(empty) title. startdate - wrongly formatted start date. enddate - wrongly formatted end date. duration - empty enddate and invalid duration. category - category is not belonging to user. trip - trip is not belonging to user. upderror - error performing db update. tagerror - error while updating tags.
Definition at line 604 of file blog.ctrl.php.
References $member, $vars, Blog\FLAG_STICKY, Blog\FLAG_VIEW_PRIVATE, Blog\FLAG_VIEW_PROTECTED, and Trip\touchTrip().
BlogController::index ()
Definition at line 26 of file blog.ctrl.php.
References $callbackId, $error, $locations, $member, $p, $request, $search, and $vars.
BlogController::singlePost ($postId, $showComments = true)
Definition at line 690 of file blog.ctrl.php.
BlogController::stickyPosts ()
Definition at line 709 of file blog.ctrl.php.
BlogController::userPosts ($userHandle)
Definition at line 696 of file blog.ctrl.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/blog/blog.ctrl.php