Rox: SimplePie_Parser Class Reference
SimplePie_Parser Class Reference
Public Member Functions
set_registry (SimplePie_Registry $registry)
parse (&$data, $encoding)
get_error_code ()
get_error_string ()
get_current_line ()
get_current_column ()
get_current_byte ()
get_data ()
tag_open ($parser, $tag, $attributes)
cdata ($parser, $cdata)
tag_close ($parser, $tag)
split_ns ($string)
Data Fields
$error_code
$error_string
$current_line
$current_column
$current_byte
$separator = ' '
$namespace = array('')
$element = array('')
$xml_base = array('')
$xml_base_explicit = array(false)
$xml_lang = array('')
$data = array()
$datas = array(array())
$current_xhtml_construct = -1
$encoding
Protected Attributes
$registry
Detailed Description
Definition at line 54 of file Parser.php.
Member Function Documentation
SimplePie_Parser::cdata ($parser, $cdata)
Definition at line 331 of file Parser.php.
Referenced by parse().
SimplePie_Parser::get_current_byte ()
Definition at line 258 of file Parser.php.
References $current_byte.
SimplePie_Parser::get_current_column ()
Definition at line 253 of file Parser.php.
References $current_column.
SimplePie_Parser::get_current_line ()
Definition at line 248 of file Parser.php.
References $current_line.
SimplePie_Parser::get_data ()
Definition at line 263 of file Parser.php.
References $data.
SimplePie_Parser::get_error_code ()
Definition at line 238 of file Parser.php.
References $error_code.
SimplePie_Parser::get_error_string ()
Definition at line 243 of file Parser.php.
References $error_string.
SimplePie_Parser::parse (& $data, $encoding)
Definition at line 78 of file Parser.php.
References $data, $encoding, $error, cdata(), elseif, tag_close(), and tag_open().
SimplePie_Parser::set_registry (SimplePie_Registry $registry)
Definition at line 73 of file Parser.php.
References $registry.
SimplePie_Parser::split_ns ($string)
Definition at line 366 of file Parser.php.
References $namespace, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_MEDIARSS, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG2, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG3, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG4, and SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG5.
Referenced by tag_open().
SimplePie_Parser::tag_close ($parser, $tag)
Definition at line 343 of file Parser.php.
References element, and SIMPLEPIE_NAMESPACE_XHTML.
Referenced by parse().
SimplePie_Parser::tag_open ($parser, $tag, $attributes)
Definition at line 268 of file Parser.php.
References $data, $name, $value, element, ENT_COMPAT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_NAMESPACE_XHTML, SIMPLEPIE_NAMESPACE_XML, and split_ns().
Referenced by parse().
Field Documentation
SimplePie_Parser::$current_byte
Definition at line 60 of file Parser.php.
Referenced by get_current_byte().
SimplePie_Parser::$current_column
Definition at line 59 of file Parser.php.
Referenced by get_current_column().
SimplePie_Parser::$current_line
Definition at line 58 of file Parser.php.
Referenced by get_current_line().
SimplePie_Parser::$current_xhtml_construct = -1
Definition at line 69 of file Parser.php.
SimplePie_Parser::$data = array()
Definition at line 67 of file Parser.php.
Referenced by get_data(), parse(), and tag_open().
SimplePie_Parser::$datas = array(array())
Definition at line 68 of file Parser.php.
SimplePie_Parser::$element = array('')
Definition at line 63 of file Parser.php.
SimplePie_Parser::$encoding
Definition at line 70 of file Parser.php.
Referenced by parse().
SimplePie_Parser::$error_code
Definition at line 56 of file Parser.php.
Referenced by get_error_code().
SimplePie_Parser::$error_string
Definition at line 57 of file Parser.php.
Referenced by get_error_string().
SimplePie_Parser::$namespace = array('')
Definition at line 62 of file Parser.php.
Referenced by split_ns().
SimplePie_Parser::$registry protected
Definition at line 71 of file Parser.php.
Referenced by set_registry().
SimplePie_Parser::$separator = ' '
Definition at line 61 of file Parser.php.
SimplePie_Parser::$xml_base = array('')
Definition at line 64 of file Parser.php.
SimplePie_Parser::$xml_base_explicit = array(false)
Definition at line 65 of file Parser.php.
SimplePie_Parser::$xml_lang = array('')
Definition at line 66 of file Parser.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/templates/simplepie/library/SimplePie/Parser.php