Rox: Note Class Reference
Note Class Reference
Public Member Functions
__construct ($note_id=false)
findBySearchTerms ($terms=array(), $page=0)
createNote ($input)
deleteNote ()
updateNote ($check=null, $type=null, $visible=null, $translationparams=null)
getIdRelMember ()
getText ()
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Attributes
$_table_name = 'notes'
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Data Fields inherited from RoxEntityBase
$sql_order = ''
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
represents a single group
Definition at line 9 of file note.entity.php.
Constructor & Destructor Documentation
Note::__construct ($note_id = false)
Definition at line 13 of file note.entity.php.
References RoxEntityBase\findById().
Member Function Documentation
Note::createNote ($input)
Create a note given some input
Parameters
array $input - array containing IdMember, IdRelMember and Type public
Returns
mixed Will return the insert id of the operation or false
Definition at line 65 of file note.entity.php.
References RoxEntityBase\insert().
Note::deleteNote ()
Delete a note Removes a row from the notes table and unsets data in the entity so it can't be reused
public
Returns
bool
Definition at line 84 of file note.entity.php.
References RoxEntityBase\isLoaded().
Note::findBySearchTerms ($terms = array(), $page = 0)
Uses an array of terms to create a create to search for groups with simple or search on names for now
Todo:
implement proper group search - this will wait on various db implementations
Parameters
array $terms - array of strings to be used in search
Returns
mixed false or group of arrays that match any of the terms public
Definition at line 32 of file note.entity.php.
References RoxEntityBase\findAll(), and RoxEntityBase\findByWhereMany().
Note::getIdRelMember ()
returns the description for a group
public
Returns
string
Definition at line 168 of file note.entity.php.
References RoxComponentBase\getWords(), and RoxEntityBase\isLoaded().
Note::getText ()
returns the notification's text
public
Returns
string
Definition at line 183 of file note.entity.php.
References $member, $words, elseif, MOD_member\getMember_userId(), and RoxEntityBase\isLoaded().
Note::updateNote ($check = null, $type = null, $visible = null, $translationparams = null)
updates a note
Parameters
string $description - the description of the group
string $type - how public the group is
string $visible_posts - if the forum posts of the group should be visible or not public
Returns
bool
Definition at line 111 of file note.entity.php.
References $type, RoxEntityBase\isLoaded(), and RoxEntityBase\update().
Field Documentation
Note::$_table_name = 'notes' protected
Definition at line 11 of file note.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/notify/note.entity.php