Rox: SimplePie_Core Class Reference
SimplePie_Core Class Reference
Public Member Functions
__toString ()
force_feed ($enable=false)
set_feed_url ($url)
set_file (&$file)
set_raw_data ($data)
set_timeout ($timeout=10)
force_fsockopen ($enable=false)
enable_cache ($enable=true)
set_cache_duration ($seconds=3600)
set_autodiscovery_cache_duration ($seconds=604800)
set_cache_location ($location= './cache')
enable_order_by_date ($enable=true)
set_input_encoding ($encoding=false)
set_autodiscovery_level ($level=SIMPLEPIE_LOCATOR_ALL)
& get_registry ()
set_cache_class ($class= 'SimplePie_Cache')
set_locator_class ($class= 'SimplePie_Locator')
set_parser_class ($class= 'SimplePie_Parser')
set_file_class ($class= 'SimplePie_File')
set_sanitize_class ($class= 'SimplePie_Sanitize')
set_item_class ($class= 'SimplePie_Item')
set_author_class ($class= 'SimplePie_Author')
set_category_class ($class= 'SimplePie_Category')
set_enclosure_class ($class= 'SimplePie_Enclosure')
set_caption_class ($class= 'SimplePie_Caption')
set_copyright_class ($class= 'SimplePie_Copyright')
set_credit_class ($class= 'SimplePie_Credit')
set_rating_class ($class= 'SimplePie_Rating')
set_restriction_class ($class= 'SimplePie_Restriction')
set_content_type_sniffer_class ($class= 'SimplePie_Content_Type_Sniffer')
set_source_class ($class= 'SimplePie_Source')
set_useragent ($ua=SIMPLEPIE_USERAGENT)
set_cache_name_function ($function= 'md5')
set_stupidly_fast ($set=false)
set_max_checked_feeds ($max=10)
remove_div ($enable=true)
strip_htmltags ($tags= '', $encode=null)
encode_instead_of_strip ($enable=true)
strip_attributes ($attribs= '')
set_output_encoding ($encoding= 'UTF-8')
strip_comments ($strip=false)
set_url_replacements ($element_attribute=null)
set_image_handler ($page=false, $qs= 'i')
set_item_limit ($limit=0)
init ()
error ()
get_raw_data ()
get_encoding ()
handle_content_type ($mime= 'text/html')
get_type ()
subscribe_url ()
get_feed_tags ($namespace, $tag)
get_channel_tags ($namespace, $tag)
get_image_tags ($namespace, $tag)
get_base ($element=array())
sanitize ($data, $type, $base= '')
get_title ()
get_category ($key=0)
get_categories ()
get_author ($key=0)
get_authors ()
get_contributor ($key=0)
get_contributors ()
get_link ($key=0, $rel= 'alternate')
get_permalink ()
get_links ($rel= 'alternate')
get_all_discovered_feeds ()
get_description ()
get_copyright ()
get_language ()
get_latitude ()
get_longitude ()
get_image_title ()
get_image_url ()
get_image_link ()
get_image_width ()
get_image_height ()
get_item_quantity ($max=0)
get_item ($key=0)
get_items ($start=0, $end=0)
Static Public Member Functions
static sort_items ($a, $b)
static merge_items ($urls, $start=0, $end=0, $limit=0)
Data Fields
$data = array()
$error
$sanitize
$useragent = SIMPLEPIE_USERAGENT
$feed_url
$file
$raw_data
$timeout = 10
$force_fsockopen = false
$force_feed = false
$cache = false
$cache_duration = 3600
$autodiscovery_cache_duration = 604800
$cache_location = './cache'
$cache_name_function = 'md5'
$order_by_date = true
$input_encoding = false
$autodiscovery = SIMPLEPIE_LOCATOR_ALL
$registry
$max_checked_feeds = 10
$all_discovered_feeds = array()
$image_handler = ''
$multifeed_url = array()
$multifeed_objects = array()
$config_settings = null
$item_limit = 0
$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc')
$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style')
Protected Member Functions
fetch_data (&$cache)
Member Function Documentation
SimplePie::__toString () inherited
Used for converting object to a string
SimplePie::enable_cache ($enable = true) inherited
Enable/disable caching in SimplePie.
This option allows you to disable caching all-together in SimplePie. However, disabling the cache can lead to longer load times.
Since
1.0 Preview Release
Parameters
bool $enable Enable caching
References cache.
SimplePie::enable_order_by_date ($enable = true) inherited
Set whether feed items should be sorted into reverse chronological order
Parameters
bool $enable Sort as reverse chronological order.
Referenced by SimplePie\set_stupidly_fast().
SimplePie::encode_instead_of_strip ($enable = true) inherited
References SimplePie\sanitize().
SimplePie::error () inherited
Get the error message for the occured error
Returns
string|array Error message, or array of messages for multifeeds
References SimplePie\$error.
Referenced by SimplePie\fetch_data(), and SimplePie\init().
SimplePie::fetch_data (& $cache) protected inherited
Fetch the data via SimplePie_File
If the data is already cached, attempt to fetch it from there instead
Parameters
SimplePie_Cache | false $cache Cache handler, or false to not load from the cache
Returns
array|true Returns true if the data was loaded from the cache, or an array of HTTP headers and sniffed type
References SimplePie\$cache, SimplePie\$file, elseif, SimplePie\error(), SimplePie\force_feed(), SimplePie\force_fsockopen(), SimplePie\init(), SimplePie\set_feed_url(), SIMPLEPIE_BUILD, SIMPLEPIE_FILE_SOURCE_REMOTE, and SIMPLEPIE_NAME.
Referenced by SimplePie\init().
SimplePie::force_feed ($enable = false) inherited
Force the given data/URL to be treated as a feed
This tells SimplePie to ignore the content-type provided by the server. Be careful when using this option, as it will also disable autodiscovery.
Since
1.1
Parameters
bool $enable Force the given data/URL to be treated as a feed
Referenced by SimplePie\fetch_data().
SimplePie::force_fsockopen ($enable = false) inherited
Force SimplePie to use fsockopen() instead of cURL
Since
1.0 Beta 3
Parameters
bool $enable Force fsockopen() to be used
Referenced by SimplePie\fetch_data().
SimplePie::get_all_discovered_feeds () inherited
References SimplePie\$all_discovered_feeds.
SimplePie::get_author ($key = 0) inherited
Get an author for the feed
Since
1.1
Parameters
int $key The author that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Author|null
References SimplePie\get_authors().
SimplePie::get_authors () inherited
Get all authors for the feed
Uses <atom:author>, <author>, <dc:creator> or <itunes:author>
Since
1.1
Returns
array|null List of {
See Also
SimplePie_Author} objects
References $name, $uri, $url, SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_ITUNES.
Referenced by SimplePie\get_author().
SimplePie::get_base ($element = array()) inherited
Get the base URL value from the feed
Uses <xml:base> if available, otherwise uses the first link in the feed, or failing that, the URL of the feed itself.
See Also
get_link
subscribe_url
Parameters
array $element
Returns
string
References elseif, SimplePie\get_link(), SimplePie\get_type(), SIMPLEPIE_TYPE_RSS_SYNDICATION, and SimplePie\subscribe_url().
Referenced by SimplePie\get_authors(), SimplePie\get_contributors(), SimplePie\get_copyright(), SimplePie\get_description(), SimplePie\get_image_link(), SimplePie\get_image_url(), SimplePie\get_links(), and SimplePie\get_title().
SimplePie::get_categories () inherited
Get all categories for the feed
Uses <atom:category>, <category> or <dc:subject>
Since
Unknown
Returns
array|null List of {
See Also
SimplePie_Category} objects
References $categories, SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by SimplePie\get_category().
SimplePie::get_category ($key = 0) inherited
Get a category for the feed
Since
Unknown
Parameters
int $key The category that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Category|null
References $categories, and SimplePie\get_categories().
SimplePie::get_channel_tags ($namespace, $tag) inherited
Get data for an channel-level element
This method allows you to get access to ANY element/attribute in the channel/header section of the feed.
See {
See Also
SimplePie::get_feed_tags()} for a description of the return value
Since
1.0
See Also
http://simplepie.org/wiki/faq/supported_xml_namespaces
Parameters
string $namespace The URL of the XML namespace of the elements you're trying to access
string $tag Tag name
Returns
array
References $type, SimplePie\get_feed_tags(), SimplePie\get_type(), SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_ATOM_ALL, SIMPLEPIE_TYPE_RSS_090, SIMPLEPIE_TYPE_RSS_10, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
Referenced by SimplePie\get_authors(), SimplePie\get_categories(), SimplePie\get_contributors(), SimplePie\get_copyright(), SimplePie\get_description(), SimplePie\get_image_tags(), SimplePie\get_image_url(), SimplePie\get_items(), SimplePie\get_language(), SimplePie\get_latitude(), SimplePie\get_links(), SimplePie\get_longitude(), and SimplePie\get_title().
SimplePie::get_contributor ($key = 0) inherited
Get a contributor for the feed
Since
1.1
Parameters
int $key The contrbutor that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Author|null
References SimplePie\get_contributors().
SimplePie::get_contributors () inherited
Get all contributors for the feed
Uses <atom:contributor>
Since
1.1
Returns
array|null List of {
See Also
SimplePie_Author} objects
References $name, $uri, $url, SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, and SIMPLEPIE_NAMESPACE_ATOM_10.
Referenced by SimplePie\get_contributor().
SimplePie::get_copyright () inherited
Get the copyright info for the feed
Uses <atom:rights>, <atom:copyright> or <dc:rights>
Since
1.0 (previously called get_feed_copyright() since 0.8)
Returns
string|null
References elseif, SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie::get_description () inherited
Get the content for the item
Uses <atom:subtitle>, <atom:tagline>, <description>, <dc:description>, <itunes:summary> or <itunes:subtitle>
Since
1.0 (previously called get_feed_description() since 0.8)
Returns
string|null
References elseif, SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie::get_encoding () inherited
Get the character encoding used for output
Since
Preview Release
Returns
string
References SimplePie\sanitize().
Referenced by SimplePie\handle_content_type().
SimplePie::get_feed_tags ($namespace, $tag) inherited
Get data for an feed-level element
This method allows you to get access to ANY element/attribute that is a sub-element of the opening feed tag.
The return value is an indexed array of elements matching the given namespace and tag name. Each element has attribs, data and child subkeys. For attribs and child, these contain namespace subkeys. attribs then has one level of associative name => value data (where value is a string) after the namespace. child has tag-indexed keys after the namespace, each member of which is an indexed array matching this same format.
For example:
// This is probably a bad example because we already support
// <media:content> natively, but it shows you how to parse through
// the nodes.
$group = $item->get_item_tags(SIMPLEPIE_NAMESPACE_MEDIARSS, 'group');
$content = $group[0]['child'][SIMPLEPIE_NAMESPACE_MEDIARSS]['content'];
$file = $content[0]['attribs']['']['url'];
echo $file;
Since
1.0
See Also
http://simplepie.org/wiki/faq/supported_xml_namespaces
Parameters
string $namespace The URL of the XML namespace of the elements you're trying to access
string $tag Tag name
Returns
array
References $type, SimplePie\get_type(), SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RDF, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_ATOM_03, SIMPLEPIE_TYPE_ATOM_10, SIMPLEPIE_TYPE_RSS_RDF, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
Referenced by SimplePie\get_channel_tags(), SimplePie\get_image_tags(), and SimplePie\get_items().
SimplePie::get_image_height () inherited
Get the feed logo's height
RSS 2.0 feeds are allowed to have a "feed logo" height.
Uses <image><height> or defaults to 31.0 if no height is specified and the feed is an RSS 2.0 feed.
Returns
int|float|null
References elseif, SimplePie\get_image_tags(), SimplePie\get_type(), round, SIMPLEPIE_NAMESPACE_RSS_20, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
SimplePie::get_image_link () inherited
Get the feed logo's link
RSS 0.9.0, 1.0 and 2.0 feeds are allowed to have a "feed logo" link. This points to a human-readable page that the image should link to.
Uses <itunes:image>, <atom:logo>, <atom:icon>, <image><title> or <image><dc:title>
Returns
string|null
References elseif, SimplePie\get_base(), SimplePie\get_image_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie::get_image_tags ($namespace, $tag) inherited
Get data for an channel-level element
This method allows you to get access to ANY element/attribute in the image/logo section of the feed.
See {
See Also
SimplePie::get_feed_tags()} for a description of the return value
Since
1.0
See Also
http://simplepie.org/wiki/faq/supported_xml_namespaces
Parameters
string $namespace The URL of the XML namespace of the elements you're trying to access
string $tag Tag name
Returns
array
References $image, $type, SimplePie\get_channel_tags(), SimplePie\get_feed_tags(), SimplePie\get_type(), SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_RSS_090, SIMPLEPIE_TYPE_RSS_10, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
Referenced by SimplePie\get_image_height(), SimplePie\get_image_link(), SimplePie\get_image_title(), SimplePie\get_image_url(), and SimplePie\get_image_width().
SimplePie::get_image_title () inherited
Get the feed logo's title
RSS 0.9.0, 1.0 and 2.0 feeds are allowed to have a "feed logo" title.
Uses <image><title> or <image><dc:title>
Returns
string|null
References elseif, SimplePie\get_image_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie::get_image_url () inherited
Get the feed logo's URL
RSS 0.9.0, 2.0, Atom 1.0, and feeds with iTunes RSS tags are allowed to have a "feed logo" URL. This points directly to the image itself.
Uses <itunes:image>, <atom:logo>, <atom:icon>, <image><title> or <image><dc:title>
Returns
string|null
References elseif, SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\get_image_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie::get_image_width () inherited
Get the feed logo's link
RSS 2.0 feeds are allowed to have a "feed logo" width.
Uses <image><width> or defaults to 88.0 if no width is specified and the feed is an RSS 2.0 feed.
Returns
int|float|null
References elseif, SimplePie\get_image_tags(), SimplePie\get_type(), round, SIMPLEPIE_NAMESPACE_RSS_20, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
SimplePie::get_item ($key = 0) inherited
Get a single item from the feed
This is better suited for for() loops, whereas {
See Also
get_items()} is better suited for foreach() loops.
get_item_quantity()
Since
Beta 2
Parameters
int $key The item that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Item|null
References $items, and SimplePie\get_items().
SimplePie::get_item_quantity ($max = 0) inherited
Get the number of items in the feed
This is well-suited for for() loops with {
See Also
get_item()}
Parameters
int $max Maximum value to return. 0 for no limit
Returns
int Number of items in the feed
References $max, and SimplePie\get_items().
SimplePie::get_items ($start = 0, $end = 0) inherited
Get all items from the feed
This is better suited for for() loops, whereas {
See Also
get_items()} is better suited for foreach() loops.
get_item_quantity
Since
Beta 2
Parameters
int $start Index to start at
int $end Number of items to return. 0 for all items after $start
Returns
array|null List of {
See Also
SimplePie_Item} objects
References $items, SimplePie\get_channel_tags(), SimplePie\get_feed_tags(), SimplePie\merge_items(), SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by SimplePie\get_item(), and SimplePie\get_item_quantity().
SimplePie::get_language () inherited
Get the language for the feed
Uses <language>, <dc:language>, or
Since
1.0 (previously called get_feed_language() since 0.8)
Returns
string|null
References elseif, SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RDF, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie::get_latitude () inherited
Get the latitude coordinates for the item
Compatible with the W3C WGS84 Basic Geo and GeoRSS specifications
Uses <geo:lat> or <georss:point>
Since
1.0 W3C WGS84 Basic Geo http://www.georss.org/ GeoRSS string|null
References elseif, SimplePie\get_channel_tags(), SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
SimplePie::get_link ($key = 0, $rel = 'alternate') inherited
Get a single link for the feed
Since
1.0 (previously called get_feed_link since Preview Release, get_feed_permalink() since 0.8)
Parameters
int $key The link that you want to return. Remember that arrays begin with 0, not 1
string $rel The relationship of the link to return
Returns
string|null Link URL
References SimplePie\get_links().
Referenced by SimplePie\get_base(), and SimplePie\get_permalink().
SimplePie::get_links ($rel = 'alternate') inherited
Get all links for the feed
Uses <atom:link> or <link>
Since
Beta 2
Parameters
string $rel The relationship of links to return
Returns
array|null Links found for the feed (strings)
References $link, elseif, SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_IANA_LINK_RELATIONS_REGISTRY, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by SimplePie\get_link().
SimplePie::get_longitude () inherited
Get the longitude coordinates for the feed
Compatible with the W3C WGS84 Basic Geo and GeoRSS specifications
Uses <geo:long>, <geo:lon> or <georss:point>
Since
1.0 W3C WGS84 Basic Geo http://www.georss.org/ GeoRSS string|null
References elseif, SimplePie\get_channel_tags(), SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
SimplePie::get_permalink () inherited
Get the permalink for the item
Returns the first link available with a relationship of "alternate". Identical to {
See Also
get_link()} with key 0
get_link
Since
1.0 (previously called get_feed_link since Preview Release, get_feed_permalink() since 0.8)
References SimplePie\get_link().
SimplePie::get_raw_data () inherited
Get the raw XML
This is the same as the old $feed->enable_xml_dump(true), but returns the data instead of printing it.
Returns
string|boolean Raw XML data, false if the cache is used
References SimplePie\$raw_data.
& SimplePie::get_registry () inherited
Get the class registry
Use this to override SimplePie's default classes
See Also
SimplePie_Registry
Returns
SimplePie_Registry
References SimplePie\$registry.
SimplePie::get_title () inherited
Get the title of the feed
Uses <atom:title>, <title> or <dc:title>
Since
1.0 (previously called get_feed_title since 0.8)
Returns
string|null
References elseif, SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\sanitize(), SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie::get_type () inherited
Get the type of the feed
This returns a SIMPLEPIE_TYPE_* constant, which can be tested against using bitwise operators
Since
0.8 (usage changed to using constants in 1.0)
See Also
SIMPLEPIE_TYPE_NONE Unknown.
SIMPLEPIE_TYPE_RSS_090 RSS 0.90.
SIMPLEPIE_TYPE_RSS_091_NETSCAPE RSS 0.91 (Netscape).
SIMPLEPIE_TYPE_RSS_091_USERLAND RSS 0.91 (Userland).
SIMPLEPIE_TYPE_RSS_091 RSS 0.91.
SIMPLEPIE_TYPE_RSS_092 RSS 0.92.
SIMPLEPIE_TYPE_RSS_093 RSS 0.93.
SIMPLEPIE_TYPE_RSS_094 RSS 0.94.
SIMPLEPIE_TYPE_RSS_10 RSS 1.0.
SIMPLEPIE_TYPE_RSS_20 RSS 2.0.x.
SIMPLEPIE_TYPE_RSS_RDF RDF-based RSS.
SIMPLEPIE_TYPE_RSS_SYNDICATION Non-RDF-based RSS (truly intended as syndication format).
SIMPLEPIE_TYPE_RSS_ALL Any version of RSS.
SIMPLEPIE_TYPE_ATOM_03 Atom 0.3.
SIMPLEPIE_TYPE_ATOM_10 Atom 1.0.
SIMPLEPIE_TYPE_ATOM_ALL Any version of Atom.
SIMPLEPIE_TYPE_ALL Any known/supported feed type.
Returns
int SIMPLEPIE_TYPE_* constant
References elseif, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RDF, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_ALL, SIMPLEPIE_TYPE_ATOM_03, SIMPLEPIE_TYPE_ATOM_10, SIMPLEPIE_TYPE_NONE, SIMPLEPIE_TYPE_RSS_090, SIMPLEPIE_TYPE_RSS_091, SIMPLEPIE_TYPE_RSS_091_NETSCAPE, SIMPLEPIE_TYPE_RSS_091_USERLAND, SIMPLEPIE_TYPE_RSS_092, SIMPLEPIE_TYPE_RSS_093, SIMPLEPIE_TYPE_RSS_094, SIMPLEPIE_TYPE_RSS_10, SIMPLEPIE_TYPE_RSS_20, and SIMPLEPIE_TYPE_RSS_ALL.
Referenced by SimplePie\get_base(), SimplePie\get_channel_tags(), SimplePie\get_feed_tags(), SimplePie\get_image_height(), SimplePie\get_image_tags(), SimplePie\get_image_width(), and SimplePie\init().
SimplePie::handle_content_type ($mime = 'text/html') inherited
Send the content-type header with correct encoding
This method ensures that the SimplePie-enabled page is being served with the correct mime-type and character encoding HTTP headers (character encoding determined by the {
See Also
set_output_encoding} config option).
This won't work properly if any content or whitespace has already been sent to the browser, because it relies on PHP's header() function, and these are the circumstances under which the function works.
Because it's setting these settings for the entire page (as is the nature of HTTP headers), this should only be used once per page (again, at the top).
Parameters
string $mime MIME type to serve the page as
References SimplePie\get_encoding().
SimplePie::init () inherited
Initialize the feed object
This is what makes everything happen. Period. This is where all of the configuration options get processed, feeds are fetched, cached, and parsed, and all of that other good stuff.
Returns
boolean True if successful, false otherwise
References SimplePie\$cache, SimplePie\$force_fsockopen, $i, SimplePie\$input_encoding, SimplePie\$timeout, $url, SimplePie\$useragent, cache, elseif, SimplePie\error(), SimplePie\fetch_data(), SimplePie\get_type(), SimplePie\sanitize(), SIMPLEPIE_BUILD, and SIMPLEPIE_TYPE_NONE.
Referenced by SimplePie\fetch_data().
static SimplePie::merge_items ($urls, $start = 0, $end = 0, $limit = 0) static inherited
Merge items from several feeds into one
If you're merging multiple feeds together, they need to all have dates for the items or else SimplePie will refuse to sort them.
array $urls List of SimplePie feed objects to merge int $start Starting item int $end Number of items to return int $limit Maximum number of items per feed array
References $items.
Referenced by SimplePie\get_items().
SimplePie::remove_div ($enable = true) inherited
References SimplePie\sanitize().
Referenced by SimplePie\set_stupidly_fast().
SimplePie::sanitize ($data, $type, $base = '') inherited
Sanitize feed data
private
See Also
SimplePie_Sanitize::sanitize()
Parameters
string $data Data to sanitize
int $type One of the SIMPLEPIE_CONSTRUCT_* constants
string $base Base URL to resolve URLs against
Returns
string Sanitized data
References SimplePie\$data, and $type.
Referenced by SimplePie\__construct(), SimplePie\encode_instead_of_strip(), SimplePie\get_authors(), SimplePie\get_categories(), SimplePie\get_contributors(), SimplePie\get_copyright(), SimplePie\get_description(), SimplePie\get_encoding(), SimplePie\get_image_link(), SimplePie\get_image_title(), SimplePie\get_image_url(), SimplePie\get_language(), SimplePie\get_links(), SimplePie\get_title(), SimplePie\init(), SimplePie\remove_div(), SimplePie\set_image_handler(), SimplePie\set_output_encoding(), SimplePie\set_url_replacements(), SimplePie\strip_attributes(), SimplePie\strip_comments(), SimplePie\strip_htmltags(), and SimplePie\subscribe_url().
SimplePie::set_author_class ($class = 'SimplePie_Author') inherited
Set which class SimplePie uses for handling author data
References $class.
SimplePie::set_autodiscovery_cache_duration ($seconds = 604800) inherited
Set the length of time (in seconds) that the autodiscovered feed URL will be cached
Parameters
int $seconds The autodiscovered feed URL cache duration.
SimplePie::set_autodiscovery_level ($level = SIMPLEPIE_LOCATOR_ALL) inherited
Set how much feed autodiscovery to do
See Also
SIMPLEPIE_LOCATOR_NONE
SIMPLEPIE_LOCATOR_AUTODISCOVERY
SIMPLEPIE_LOCATOR_LOCAL_EXTENSION
SIMPLEPIE_LOCATOR_LOCAL_BODY
SIMPLEPIE_LOCATOR_REMOTE_EXTENSION
SIMPLEPIE_LOCATOR_REMOTE_BODY
SIMPLEPIE_LOCATOR_ALL
Parameters
int $level Feed Autodiscovery Level (level can be a combination of the above constants, see bitwise OR operator)
SimplePie::set_cache_class ($class = 'SimplePie_Cache') inherited
#@+ Useful when you are overloading or extending SimplePie's default classes.
Deprecated:
Use {
See Also
get_registry()} instead PHP5 extends documentation string $class Name of custom class boolean True on success, false otherwise
Set which class SimplePie uses for caching
References $class.
SimplePie::set_cache_duration ($seconds = 3600) inherited
Set the length of time (in seconds) that the contents of a feed will be cached
Parameters
int $seconds The feed content cache duration
SimplePie::set_cache_location ($location = './cache') inherited
Set the file system location where the cached files should be stored
Parameters
string $location The file system location.
SimplePie::set_cache_name_function ($function = 'md5') inherited
Set callback function to create cache filename with
Parameters
mixed $function Callback function
SimplePie::set_caption_class ($class = 'SimplePie_Caption') inherited
Set which class SimplePie uses for <media:text> captions
References $class.
SimplePie::set_category_class ($class = 'SimplePie_Category') inherited
Set which class SimplePie uses for handling category data
References $class.
SimplePie::set_content_type_sniffer_class ($class = 'SimplePie_Content_Type_Sniffer') inherited
Set which class SimplePie uses for content-type sniffing
References $class.
SimplePie::set_copyright_class ($class = 'SimplePie_Copyright') inherited
Set which class SimplePie uses for <media:copyright>
References $class.
SimplePie::set_credit_class ($class = 'SimplePie_Credit') inherited
Set which class SimplePie uses for <media:credit>
References $class.
SimplePie::set_enclosure_class ($class = 'SimplePie_Enclosure') inherited
Set which class SimplePie uses for feed enclosures
References $class.
SimplePie::set_feed_url ($url) inherited
Set the URL of the feed you want to parse
This allows you to enter the URL of the feed you want to parse, or the website you want to try to use auto-discovery on. This takes priority over any set raw data.
You can set multiple feeds to mash together by passing an array instead of a string for the $url. Remember that with each additional feed comes additional processing and resources.
Since
1.0 Preview Release
See Also
set_raw_data()
Parameters
string | array $url This is the URL (or array of URLs) that you want to parse.
References $url, and $value.
Referenced by SimplePie\fetch_data().
SimplePie::set_file (& $file) inherited
Set an instance of {
See Also
SimplePie_File} to use as a feed
Parameters
SimplePie_File &$file
Returns
bool True on success, false on failure
References SimplePie\$file.
SimplePie::set_file_class ($class = 'SimplePie_File') inherited
Set which class SimplePie uses for remote file fetching
References $class.
SimplePie::set_image_handler ($page = false, $qs = 'i') inherited
Set the handler to enable the display of cached images.
Parameters
str $page Web-accessible path to the handler_image.php file.
str $qs The query string that the value should be passed to.
References SimplePie\sanitize().
Referenced by SimplePie\set_stupidly_fast().
SimplePie::set_input_encoding ($encoding = false) inherited
Set the character encoding used to parse the feed
This overrides the encoding reported by the feed, however it will fall back to the normal encoding detection if the override fails
Parameters
string $encoding Character encoding
SimplePie::set_item_class ($class = 'SimplePie_Item') inherited
Set which class SimplePie uses for handling feed items
References $class.
SimplePie::set_item_limit ($limit = 0) inherited
Set the limit for items returned per-feed with multifeeds
Parameters
integer $limit The maximum number of items to return.
SimplePie::set_locator_class ($class = 'SimplePie_Locator') inherited
Set which class SimplePie uses for auto-discovery
References $class.
SimplePie::set_max_checked_feeds ($max = 10) inherited
Set maximum number of feeds to check with autodiscovery
Parameters
int $max Maximum number of feeds to check
References $max.
SimplePie::set_output_encoding ($encoding = 'UTF-8') inherited
Set the output encoding
Allows you to override SimplePie's output to match that of your webpage. This is useful for times when your webpages are not being served as UTF-8. This setting will be obeyed by {
See Also
handle_content_type()}, and is similar to {
set_input_encoding()}.
It should be noted, however, that not all character encodings can support all characters. If your page is being served as ISO-8859-1 and you try to display a Japanese feed, you'll likely see garbled characters. Because of this, it is highly recommended to ensure that your webpages are served as UTF-8.
The number of supported character encodings depends on whether your web host supports mbstring, iconv, or both. See http://simplepie.org/wiki/faq/Supported_Character_Encodings for more information.
Parameters
string $encoding
References SimplePie\sanitize().
SimplePie::set_parser_class ($class = 'SimplePie_Parser') inherited
Set which class SimplePie uses for XML parsing
References $class.
SimplePie::set_rating_class ($class = 'SimplePie_Rating') inherited
Set which class SimplePie uses for <media:rating>
References $class.
SimplePie::set_raw_data ($data) inherited
Set the raw XML data to parse
Allows you to use a string of RSS/Atom data instead of a remote feed.
If you have a feed available as a string in PHP, you can tell SimplePie to parse that data string instead of a remote feed. Any set feed URL takes precedence.
Since
1.0 Beta 3
Parameters
string $data RSS or Atom data as a string.
See Also
set_feed_url()
References SimplePie\$data.
SimplePie::set_restriction_class ($class = 'SimplePie_Restriction') inherited
Set which class SimplePie uses for <media:restriction>
References $class.
SimplePie::set_sanitize_class ($class = 'SimplePie_Sanitize') inherited
Set which class SimplePie uses for data sanitization
References $class.
SimplePie::set_source_class ($class = 'SimplePie_Source') inherited
Set which class SimplePie uses item sources
References $class.
SimplePie::set_stupidly_fast ($set = false) inherited
Set options to make SP as fast as possible
Forgoes a substantial amount of data sanitization in favor of speed. This turns SimplePie into a dumb parser of feeds.
Parameters
bool $set Whether to set them or not
References SimplePie\enable_order_by_date(), SimplePie\remove_div(), SimplePie\set_image_handler(), SimplePie\strip_attributes(), SimplePie\strip_comments(), and SimplePie\strip_htmltags().
SimplePie::set_timeout ($timeout = 10) inherited
Set the the default timeout for fetching remote feeds
This allows you to change the maximum time the feed's server to respond and send the feed back.
Since
1.0 Beta 3
Parameters
int $timeout The maximum number of seconds to spend waiting to retrieve a feed.
References SimplePie\$timeout.
SimplePie::set_url_replacements ($element_attribute = null) inherited
Set element/attribute key/value pairs of HTML attributes containing URLs that need to be resolved relative to the feed
Defaults to |a|, |area|, |blockquote|
References SimplePie\sanitize().
SimplePie::set_useragent ($ua = SIMPLEPIE_USERAGENT) inherited
#@- Set the user agent string
Parameters
string $ua New user agent string.
static SimplePie::sort_items ($a, $b) static inherited
Sorting callback for items
private
Parameters
SimplePie $a
SimplePie $b
Returns
boolean
array Stores the default attributes to be stripped by SimplePie::strip_attributes ($attribs = '') inherited
See Also
SimplePie::strip_attributes() private
References SimplePie\$strip_attributes, and SimplePie\sanitize().
Referenced by SimplePie\set_stupidly_fast().
SimplePie::strip_comments ($strip = false) inherited
References SimplePie\sanitize().
Referenced by SimplePie\set_stupidly_fast().
array Stores the default tags to be stripped by SimplePie::strip_htmltags ($tags = '', $encode = null) inherited
See Also
SimplePie::strip_htmltags() private
References SimplePie\$strip_htmltags, $tags, and SimplePie\sanitize().
Referenced by SimplePie\set_stupidly_fast().
SimplePie::subscribe_url () inherited
Get the URL for the feed
May or may not be different from the URL passed to {
See Also
set_feed_url()}, depending on whether auto-discovery was used.
Since
Preview Release (previously called get_feed_url() since SimplePie 0.8.)
Todo:
If we have a perm redirect we should return the new URL
When we make the above change, let's support <itunes:new-feed-url> as well
Also, |atom:link|=self
Returns
string|null
References SimplePie\sanitize(), and SIMPLEPIE_CONSTRUCT_IRI.
Referenced by SimplePie\get_base().
Field Documentation
SimplePie::$all_discovered_feeds = array() inherited
Referenced by SimplePie\get_all_discovered_feeds().
SimplePie::$autodiscovery = SIMPLEPIE_LOCATOR_ALL inherited
SimplePie::$autodiscovery_cache_duration = 604800 inherited
SimplePie::$cache = false inherited
Referenced by SimplePie\fetch_data(), and SimplePie\init().
SimplePie::$cache_duration = 3600 inherited
SimplePie::$cache_location = './cache' inherited
SimplePie::$cache_name_function = 'md5' inherited
SimplePie::$config_settings = null inherited
SimplePie::$data = array() inherited
Referenced by SimplePie\sanitize(), and SimplePie\set_raw_data().
SimplePie::$error inherited
Referenced by SimplePie\error().
SimplePie::$feed_url inherited
SimplePie::$file inherited
Referenced by SimplePie\fetch_data(), and SimplePie\set_file().
SimplePie::$force_feed = false inherited
SimplePie::$force_fsockopen = false inherited
Referenced by SimplePie\init().
SimplePie::$image_handler = '' inherited
SimplePie::$input_encoding = false inherited
Referenced by SimplePie\init().
SimplePie::$item_limit = 0 inherited
SimplePie::$max_checked_feeds = 10 inherited
SimplePie::$multifeed_objects = array() inherited
SimplePie::$multifeed_url = array() inherited
SimplePie::$order_by_date = true inherited
SimplePie::$raw_data inherited
Referenced by SimplePie\get_raw_data().
SimplePie::$registry inherited
Referenced by SimplePie\get_registry().
SimplePie::$sanitize inherited
SimplePie::$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc') inherited
Referenced by SimplePie\strip_attributes().
SimplePie::$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style') inherited
Referenced by SimplePie\strip_htmltags().
SimplePie::$timeout = 10 inherited
Referenced by SimplePie\init(), and SimplePie\set_timeout().
SimplePie::$useragent = SIMPLEPIE_USERAGENT inherited
Referenced by SimplePie\init().
The documentation for this class was generated from the following file:
Core.php