Rox: VerifyMembersModel Class Reference
VerifyMembersModel Class Reference
Public Member Functions
sVerifierLevel ($member_id=-1)
AddNewVerified ($input)
LoadPrivateData ($cid, $given_password)
LoadVerifiers ($cid)
LoadApprovedVerifiers ()
LoadVerified ($username)
checkPasswordsOfMembers ($vars)
checkVerificationForm ($vars)
prepareVerificationData ($vars)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
CheckAndGetUsername ($cid)
checkPassword ($cid, $given_password)
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 12 of file verifymembers.model.php.
Member Function Documentation
VerifyMembersModel::AddNewVerified ($input)
this function inserts 2 new verified members (or replace the record if one from the same verifier exist for this member)
Postcondition
is the post from the previous form nota a member cannot verified himself
Definition at line 73 of file verifymembers.model.php.
References $m, $vars, MOD_log\get(), prepareVerificationData(), RoxModelBase\singleLookup(), and sVerifierLevel().
VerifyMembersModel::CheckAndGetUsername ($cid) protected
Checks and gets the username if the member can be displayed as a verified (he must have the proper Status) the id of the member (can also be the IdMember, it will be converted to a Username) @ returns the username or an empty string
Definition at line 350 of file verifymembers.model.php.
References $m, and RoxModelBase\singleLookup().
VerifyMembersModel::checkPassword ($cid, $given_password) protected
Check if the entered password is correct an array of values from the form
Returns
an (empty) array of errors
Definition at line 396 of file verifymembers.model.php.
References $m, and RoxModelBase\createEntity().
Referenced by checkPasswordsOfMembers(), and LoadPrivateData().
VerifyMembersModel::checkPasswordsOfMembers ($vars)
Check if the entered password is correct an array of values from the form
Returns
an (empty) array of errors
Definition at line 365 of file verifymembers.model.php.
References $errors, $vars, and checkPassword().
VerifyMembersModel::checkVerificationForm ($vars)
Check if all values are correct an array of values from the form
Returns
an (empty) array of errors
Definition at line 414 of file verifymembers.model.php.
References $errors, and $vars.
VerifyMembersModel::LoadApprovedVerifiers ()
this function load the list of the approved verifiers @ returns a structure with the data with the list of verifications or and empty structure if password/Username dont match
Definition at line 243 of file verifymembers.model.php.
References $layoutbits, $m, $query, RoxModelBase\createEntity(), and RoxModelBase\singleLookup().
VerifyMembersModel::LoadPrivateData ($cid, $given_password)
This function loads the private data of member IdMember can be an id or a username of the member. is the password sent with the form.
Returns
a structure with the data, or false if password/Username dont match
Definition at line 123 of file verifymembers.model.php.
References $data, $m, MOD_crypt\AdminReadCrypted(), and checkPassword().
VerifyMembersModel::LoadVerified ($username)
Get verifications a member has given.
Parameters
string $username Username of member
Returns
array List of verifications, empty if none
Definition at line 306 of file verifymembers.model.php.
References $query, $username, and RoxModelBase\bulkLookup().
VerifyMembersModel::LoadVerifiers ($cid)
Get verifications a member has received.
Parameters
int | string $cid User ID or username of member
Returns
array List of verifications
TODO: Restrict method usage to either user ID or username, not both
Definition at line 163 of file verifymembers.model.php.
References $query, $username, and RoxModelBase\bulkLookup().
VerifyMembersModel::prepareVerificationData ($vars)
Check if all values are correct an array of values from the form
Returns
an (empty) array of errors
Definition at line 428 of file verifymembers.model.php.
References $n, and $vars.
Referenced by AddNewVerified().
VerifyMembersModel::sVerifierLevel ($member_id = -1)
sVerifierLevel function returns the current verification level of member (optional) the Id of the member to obtaon verification level, if not provided current member in session will be use returns : a string with the member level a member can be a "Normal" member (one who was not veridied) "VerifiedByNormal" member (if he was verified by a normal member) "VerifiedByVerified" member (if he was verified by an approved verifier) "VerifiedByApproved" member (if he has right to be a verifier)
Definition at line 24 of file verifymembers.model.php.
References $_SESSION, and MOD_right\get().
Referenced by AddNewVerified().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/verifymembers/verifymembers.model.php