Rox: ExceptionPage Class Reference
ExceptionPage Class Reference
Public Member Functions
render ()
Protected Member Functions
showTraceStep ($step, $i_step)
Member Function Documentation
ExceptionPage::render ()
References $i, ENT_COMPAT, and showTraceStep().
Referenced by RoxLauncher\launch().
ExceptionPage::showTraceStep ($step, $i_step) protected
References $class, $debug, $i, and debug.
Referenced by render().
The documentation for this class was generated from the following file:
exception.page.php