Rox: NotifyMemberWidget Class Reference
NotifyMemberWidget Class Reference
Public Member Functions
render ()
Public Member Functions inherited from ItemlistWithPagination
render ()
needsPagination ()
showPagination ()
Public Member Functions inherited from ItemlistWidget
render ()
__call ($methodname, $args)
Public Member Functions inherited from RoxWidget
__construct ()
render ()
getStylesheets ()
getScriptfiles ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
getAllItems ()
showItems ()
showListItem ($item, $i_row)
showBetweenListItems ($prev_item, $item, $i_row)
showItems_list ()
showDefaultText ()
Protected Member Functions inherited from ItemlistWithPagination
prepare ()
numberOfPages ()
getItems ()
getItemsForPage ($k_page)
itemsTotalBegin ()
showPageLink ($i_page)
showActivePageLink ($i_page)
getItemsInRange ($begin, $count)
itemsTotalCount ()
Protected Member Functions inherited from ItemlistWidget
showItems ()
showItems_table ()
showItems_float ()
showItems_list ()
showBetweenListItems ($prev_item, $item, $i_row)
showListItem ($item, $i_row)
getItems ()
hideColumnTitles ()
Protected Member Functions inherited from RoxWidget
createEntity ()
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxWidget
$_entity_factory
Detailed Description
This widget shows a list of notifications for a member.
Definition at line 8 of file notify.widgets.php.
Member Function Documentation
NotifyMemberWidget::getAllItems () protected
Definition at line 20 of file notify.widgets.php.
References model.
NotifyMemberWidget::render ()
Definition at line 12 of file notify.widgets.php.
References render.
NotifyMemberWidget::showBetweenListItems ($prev_item, $item, $i_row) protected
Definition at line 115 of file notify.widgets.php.
NotifyMemberWidget::showDefaultText () protected
Definition at line 157 of file notify.widgets.php.
NotifyMemberWidget::showItems () protected
Definition at line 27 of file notify.widgets.php.
References $words, e, Effect, element, Element, Event, and showItems_list().
NotifyMemberWidget::showItems_list () protected
Definition at line 120 of file notify.widgets.php.
References $items, and elseif.
Referenced by showItems().
NotifyMemberWidget::showListItem ($item, $i_row) protected
Definition at line 75 of file notify.widgets.php.
References $member, $text, $words, a, MOD_layoutbits\ago(), p, MOD_layoutbits\PIC_30_30(), and title.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/notify/notify.widgets.php