Rox: User Class Reference
User Class Reference
Public Member Functions
__construct ()
avatarProcess ()
bootstrap ()
confirmRegister ($handle, $key)
emailInUse ($email)
find ($str)
getFriends ($userId)
getRealHandle ($userId)
getUser ($userId)
handleInUse ($handle)
hasAvatar ($userId)
loginProcess ()
logoutProcess ()
logout ()
registerProcess ()
passwordProcess ()
settingsProcess ()
getLocation ($userId)
getUserAuth ()
groupChangeProcess ()
getPicture ($username)
Data Fields
$avatarDir
const HANDLE_PREGEXP = '/^[a-z](?!.*[-_.][-_.])[a-z0-9-._]{2,18}[a-z0-9]$/i'
Constructor & Destructor Documentation
User::__construct ()
Constructor
Parameters
void
References bootstrap().
Member Function Documentation
User::avatarProcess ()
References $callbackId, $type, $User, $vars, and APP_User\login().
User::bootstrap ()
Referenced by __construct().
User::confirmRegister ($handle, $key)
confirmation process
Parameters
string $handle
string $key
Returns
boolean
References APP_User\activate(), APP_User\getSetting(), and APP_User\userId().
User::emailInUse ($email)
checks if e-mail address is in use
Parameters
string $email
Returns
boolean
References $query.
Referenced by registerProcess().
User::find ($str)
References $query, and APP_User\login().
User::getFriends ($userId)
References $query.
User::getLocation ($userId)
User::getPicture ($username)
User::getRealHandle ($userId)
returns handle as written in DB
User::getUser ($userId)
Get all user fields
Parameters
int $userId
Returns
stdClass
References $query.
User::getUserAuth ()
User::groupChangeProcess ()
User::handleInUse ($handle)
returns "true" if handle is in use
Parameters
string $handle
Returns
boolean
References $query.
Referenced by registerProcess().
User::hasAvatar ($userId)
User::loginProcess ()
Processing login
This is a POST callback function
Parameters
void
References $callbackId, $User, $vars, and APP_User\login().
User::logout ()
References $User, and APP_User\get().
Referenced by logoutProcess().
User::logoutProcess ()
References logout().
User::passwordProcess ()
User::registerProcess ()
Processing registration
This is a POST callback function
Sets following errors in POST-vars: username - general username fault uinuse - username already in use email - general email fault, email format error einuse - email in use pw - general password fault pwmismatch - password mismatch inserror - error performing db insertion
Parameters
void
References $errors, $query, $vars, MOD_user_Auth\checkAuth(), elseif, emailInUse(), HANDLE_PREGEXP, handleInUse(), and MOD_user\passwordEncrypt().
User::settingsProcess ()
Field Documentation
User::$avatarDir
const User::HANDLE_PREGEXP = '/^[a-z](?!.*[-_.][-_.])[a-z0-9-._]{2,18}[a-z0-9]$/i'
PERL regular expression for user handle
Referenced by GalleryController\index(), SignupController\index(), UserController\index(), and registerProcess().
The documentation for this class was generated from the following file:
user.model.php