Rox: AbstractBasePage Class Reference
AbstractBasePage Class Reference
Public Member Functions
setModel ($model)
createWidget ($classname)
render ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
getModel ()
showTemplate ($rel_path, $args=array())
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 4 of file page.php.
Member Function Documentation
AbstractBasePage::createWidget ($classname)
Definition at line 25 of file page.php.
References $layoutkit, and layoutkit.
Referenced by SignupResentMailPage\column_col3(), SignupMailConfirmPage\column_col3(), VerifyMustLoginPage\column_col3(), GroupJoinPage\column_col3(), GroupMemberSettingsPage\column_col3(), GroupLeavePage\column_col3(), LoginPage\column_col3(), and PageWithRoxLayout\volunteerMenu().
AbstractBasePage::getModel () protected
Get the model object that was stored using setModel
Definition at line 20 of file page.php.
Referenced by NotifyAdminSettingsPage\column_col3(), MessagesPageWithMailbox\column_col3(), NotifyAdminPage\column_col3(), InvitePage\column_col3(), AboutGenericPage\column_col3(), GroupSettingsPage\column_col3(), GroupInvitePage\column_col3(), GroupMemberAdministrationPage\column_col3(), and MessagesPageWithMailbox\getMailboxWidget().
AbstractBasePage::render () abstract
AbstractBasePage::setModel ($model)
some view classes need to store a model object.
Definition at line 12 of file page.php.
References $model.
AbstractBasePage::showTemplate ($rel_path, $args = array()) protected
Definition at line 42 of file page.php.
References $template, and RoxComponentBase\getWords().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/mvc-base/page.php