Rox: MOD_right Class Reference
MOD_right Class Reference
Public Member Functions
__construct ()
hasFlag ($Name, $_Scope="", $OptionalIdMember=0)
hasRight ($Name, $_Scope="", $OptionalIdMember=0)
hasRightAny ()
rightScope ($Name, $Scope="")
flagScope ($Name, $Scope="")
TheScope ($Name, $Scope="")
Static Public Member Functions
static get ()
Data Fields
$nomtable
Protected Member Functions
initialize ($nomdetable="")
Protected Attributes
$dao
Constructor & Destructor Documentation
MOD_right::__construct ()
References initialize().
Member Function Documentation
MOD_right_flag::flagScope ($Name, $Scope = "") inherited
References MOD_right_flag\TheScope().
static MOD_right::get () static
singleton getter
Parameters
void
Returns
PApps
Referenced by ForumsController\__construct(), MOD_words\__construct(), Forums\__construct(), Board\__construct(), PollsModel\AddChoice(), LinkShowFriendsPage\column_col3(), LinkShowPage\column_col3(), AdminWordModel\editCodeFormCheck(), EditProfilePage\editMyProfileFormPrepare(), DonateModel\getDonations(), Rox\getDonations(), OnlineModel\GetGuests(), VolunteerbarModel\getNumberPersonsToAcceptInGroup(), VolunteerbarModel\getNumberPersonsToBeAccepted(), VolunteerbarModel\getNumberPersonsToBeChecked(), VolunteerbarModel\getNumberReportedComments(), VerifyMembersProceedPage\getPageTitle(), VerifyMembersFinishPage\getPageTitle(), getShowCondition(), MemberPage\getSubmenuItems(), DebugController\index(), RssController\index(), SignupController\index(), SearchmembersController\index(), GeoController\index(), LinkPage\leftSidebar(), PollsPage\leftSidebar(), PollsModel\LoadList(), AdminModel\procActivitylogs(), VolunteerLinksWidget\render(), VerifyMembersModel\sVerifierLevel(), VerifyMembersPage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), translator_block(), PollsModel\UpdateChoice(), and PollsModel\UpdatePoll().
MOD_right_flag::hasFlag ($Name, $_Scope = "", $OptionalIdMember = 0) inherited
FIXME: this is (with little exception) copy-paste from /htdocs/bw/lib/rights.php; to be improved!
See Also
/htdocs/bw/lib/rights.php return the FlagLevel if the members has the Flag $Name optional Scope value can be send if the Scope is set to All then Scope will always match if not, the sentence in Scope must be find in RScope The function will use a cache in session ($_SESSION['Param']->ReloadRightsAndFlags == 'Yes') is used to force Rights / Flags Reloading from scope beware to the "" which must exist in the mysal table but NOT in the $Scope parameter $OptionalIdMember allow to specify another member than the current one, in this case the cache is not used This function is just an allias of the hasRight
References MOD_right_flag\hasRight().
MOD_right_flag::hasRight ($Name, $_Scope = "", $OptionalIdMember = 0) inherited
return the RightLevel if the members has the Right $Name optional Scope value can be send if the Scope is set to All then Scope will always match if not, the sentence in Scope must be find in RScope The function will use a cache in session ($_SESSION['Param']->ReloadRightsAndFlags == 'Yes') is used to force Rights / Flags Reloading from scope beware to the "" which must exist in the mysal table but NOT in the $Scope parameter $OptionalIdMember allow to specify another member than the current one, in this case the cache is not used
References $_SESSION.
Referenced by MOD_right_flag\hasFlag().
MOD_right_flag::hasRightAny () inherited
Checks, if the logged on member has any right by searching her in the table $table.volunteers
Returns
true, if the current user is logged on and exists in table $table.volunteers Improvment by JeanYves : if the member has not any right, a $_SESSION["hasRightAny"]="no" is set, this will allow for a faster test at next attempt
References $_SESSION, and $query.
MOD_right_flag::initialize ($nomdetable = "") protected inherited
MOD_right_flag::rightScope ($Name, $Scope = "") inherited
References MOD_right_flag\TheScope().
MOD_right_flag::TheScope ($Name, $Scope = "") inherited
FIXME: this is (with little exception) copy-paste from /htdocs/bw/lib/rights.php; to be improved!
See Also
/htdocs/bw/lib/rights.php
References $_SESSION.
Referenced by MOD_right_flag\flagScope(), and MOD_right_flag\rightScope().
Field Documentation
MOD_right_flag::$dao protected inherited
Referenced by MOD_right_flag\__construct().
MOD_right_flag::$nomtable inherited
The documentation for this class was generated from the following file:
right.lib.php