Rox: ItemlistWithPagination Class Reference
ItemlistWithPagination Class Reference
Public Member Functions
render ()
needsPagination ()
showPagination ()
Public Member Functions inherited from ItemlistWidget
render ()
__call ($methodname, $args)
Public Member Functions inherited from RoxWidget
__construct ()
render ()
getStylesheets ()
getScriptfiles ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
prepare ()
numberOfPages ()
getItems ()
getItemsForPage ($k_page)
itemsTotalBegin ()
showPageLink ($i_page)
showActivePageLink ($i_page)
getItemsInRange ($begin, $count)
itemsTotalCount ()
Protected Member Functions inherited from ItemlistWidget
showItems ()
showItems_table ()
showItems_float ()
showItems_list ()
showBetweenListItems ($prev_item, $item, $i_row)
showListItem ($item, $i_row)
getItems ()
hideColumnTitles ()
Protected Member Functions inherited from RoxWidget
createEntity ()
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxWidget
$_entity_factory
Detailed Description
Definition at line 4 of file pagination.widget.php.
Member Function Documentation
ItemlistWithPagination::getItems () protected
Definition at line 149 of file pagination.widget.php.
References active_page, getItemsForPage(), and prepare().
ItemlistWithPagination::getItemsForPage ($k_page) protected
Definition at line 155 of file pagination.widget.php.
References getItemsInRange(), itemsTotalBegin(), itemsTotalCount(), and prepare().
Referenced by getItems().
ItemlistWithPagination::getItemsInRange ($begin, $count) protected
Get all items with $begin <= $index < $end.
Parameters
int $begin
int $end
Returns
array items in range
Definition at line 198 of file pagination.widget.php.
References $count, and $items.
Referenced by getItemsForPage().
ItemlistWithPagination::itemsTotalBegin () protected
Definition at line 175 of file pagination.widget.php.
Referenced by getItemsForPage().
ItemlistWithPagination::itemsTotalCount () protected
Returns
int number of items on all pages together
Definition at line 212 of file pagination.widget.php.
Referenced by getItemsForPage(), and numberOfPages().
ItemlistWithPagination::needsPagination ()
Definition at line 12 of file pagination.widget.php.
References numberOfPages().
ItemlistWithPagination::numberOfPages () protected
Definition at line 142 of file pagination.widget.php.
References items_per_page, itemsTotalCount(), and prepare().
Referenced by needsPagination(), prepare(), and showPagination().
ItemlistWithPagination::prepare () protected
Definition at line 18 of file pagination.widget.php.
References active_page, items_per_page, and numberOfPages().
Referenced by getItems(), getItemsForPage(), numberOfPages(), render(), and showPagination().
ItemlistWithPagination::render ()
Definition at line 6 of file pagination.widget.php.
References prepare(), and render.
ItemlistWithPagination::showActivePageLink ($i_page) protected
Definition at line 183 of file pagination.widget.php.
Referenced by showPagination().
ItemlistWithPagination::showPageLink ($i_page) protected
Definition at line 179 of file pagination.widget.php.
Referenced by showPagination().
ItemlistWithPagination::showPagination ()
Definition at line 47 of file pagination.widget.php.
References $i, numberOfPages(), prepare(), showActivePageLink(), and showPageLink().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/widget/pagination.widget.php