Rox: RoxLauncher Class Reference
RoxLauncher Class Reference
Public Member Functions
launch ()
initBW ()
Protected Member Functions
chooseAndRunApplication ($env_explore)
initializeGlobalState ()
Detailed Description
methods in here get called by other methods in PTLauncher.
Member Function Documentation
RoxLauncher::chooseAndRunApplication ($env_explore) protected
choose a controller and call the index() function. If necessary, flush the buffered output.
Referenced by launch().
RoxLauncher::initBW ()
This is called from htdocs/bw/lib/tbinit.php
References initializeGlobalState().
RoxLauncher::initializeGlobalState () protected
References EnvironmentExplorer\initializeGlobalState().
Referenced by initBW(), and launch().
RoxLauncher::launch ()
central starting point. to be called in htdocs/index.php
References $debug, chooseAndRunApplication(), debug, elseif, error, i, initializeGlobalState(), ExceptionLogger\logException(), p, and ExceptionPage\render().
The documentation for this class was generated from the following file:
roxlauncher.php