Rox: InviteModel Class Reference
InviteModel Class Reference
Public Member Functions
__construct ()
getMember ($id)
sendOrComplain ($input)
isEmailAddress ($email)
style ($text, $photo)
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_entity_factory
Constructor & Destructor Documentation
InviteModel::__construct ()
Member Function Documentation
RoxComponentBase::__call ($key, $args) inherited
RoxComponentBase::__get ($key) inherited
Referenced by Member\get_messengers().
RoxComponentBase::__set ($key, $value) inherited
References $value.
RoxComponentBase::__toString () inherited
RoxModelBase::bulkLookup ($query_string, $keynames = false) inherited
This method fetches a bunch of rows from the database. It has some funny mechanics, which you can usually just ignore.
Parameters
string $query_string
array $keynames
this will trigger the funny mechanics which sort the results into a hierarchic structure
Returns
array of rows (as objects)
References $i.
Referenced by PollsModel\AddVote(), PollsModel\CancelVote(), Member\count_comments(), Blog\countComments(), LinkModel\dbFriends(), LinkModel\dbFriendsID(), LinkModel\dbLinks(), MembersModel\editPreferences(), MessagesModel\filteredMailbox(), Member\get_address(), Member\get_comments(), Member\get_comments_commenter(), Member\get_comments_written(), Member\get_trads(), GeoModel\getAllGeonameIds(), RssModel\getBlogFeed(), RssModel\getBlogFeedByAuthor(), RssModel\getBlogFeedByTag(), SqltestModel\getBWMembers(), Blog\getCategoryArray(), LinkModel\getChanges(), LinkModel\getComments(), DatabaseSummaryModel\getDatabaseFieldsSorted(), DatabaseSummaryModel\getDatabaseTablesSorted(), CommunityModel\getFaqsCategorized(), AboutModel\getFaqsCategorized(), FeedbackModel\getFeedbackCategories(), RssModel\getForumFeed(), LastcommentsModel\GetLastComments(), LinkModel\getLinkPreferences(), LinkModel\getMemberdata(), Member\getNoteCategories(), NotifyModel\getNotes(), PollsModel\GetPollResults(), Blog\getRecentPostsArray(), LinkModel\getSpecialRelation(), RssModel\getTagFeed(), SqltestModel\getTBUsers(), RssModel\getThreadFeed(), Trip\getTripsForLocation(), Trip\getTripsForUser(), NewsletterModel\Load(), PollsModel\LoadPoll(), VerifyMembersModel\LoadVerified(), VerifyMembersModel\LoadVerifiers(), PollsModel\PrepareContribute(), NewsletterModel\PreviousLetters(), LinkModel\rebuildMissingLinks(), Member\set_profile_languages(), and GeoModel\updateGeoCounters().
RoxModelBase::bulkLookup_assoc ($query_string) inherited
This is the same as the above bulkLookup, but the rows are associative arrays instead of objects.
Parameters
unknown_type $query_string
Returns
array of rows (as associative arrays)
RoxModelBase::createEntity () protected inherited
calls the entity factory to create an entity, passes along any arguments
Parameters
string - first parameter must be the name of the entity to create
Returns
object protected
Referenced by GeoUse\__construct(), GroupsModel\acceptGroupMember(), MembersModel\addComment(), Role\addForMember(), GroupsModel\addGroupMemberAsAdmin(), MembersModel\addRelation(), GroupsModel\banGroupMember(), PrivilegeScope\checkForEquivalentScope(), VerifyMembersModel\checkPassword(), PrivilegeScope\checkScopeExists(), MembersModel\confirmRelation(), Role\containsPrivilege(), GroupsModel\countGroupsBySearchterms(), AdminModel\countMembersWithStatus(), GroupsModel\countMyGroups(), Group\createGroup(), GroupsModel\createGroup(), NotifyModel\createNote(), NotifyModel\deleteNotes(), RelatedGroup\deleteRelatedGroup(), MembersModel\deleteRelation(), GroupsModel\findAllGroups(), NotifyModel\findAllNotes(), GroupsModel\findGroup(), RelatedGroupsModel\findGroup(), GroupsModel\findGroups(), GroupsModel\findMembersByName(), NotifyModel\findNote(), NotifyModel\findNotes(), Member\forums_posts_count(), Member\get_address(), MembersModel\get_profile_language(), Geo\getAllAlternateNames(), Geo\getAllParents(), Member\getAllPostVotes(), RightsModel\getAllRoles(), Member\getAllThreadVotes(), Geo\getAlternateName(), AdminModel\getBadComments(), Trip\getBlogGeo(), Blog\getBlogPost(), AdminModel\getBoard(), LoginModel\getBWMemberByUsername(), Geo\getChildren(), Address\getCity(), BlogEntity\getComingPosts(), Member\getComingPosts(), MembersModel\getComment(), GeoModel\getContinents(), Geo\getCountry(), Group\getEmailAcceptingMembers(), Role\getEquivalentPrivilege(), Member\getFirstAddress(), Comment\getFromMember(), Feedback\getFromMember(), GalleryModel\getGalleriesNotEmptyEntities(), BlogEntity\getGeo(), Forums\GetGroupEntity(), GroupMembership\getGroupMembers(), Member\getGroupMembership(), Group\getGroupOwners(), Member\getGroups(), RelatedGroupsModel\getGroupsForMember(), GroupsModel\getGroupsForMember(), Group\getLastLoggedInMembers(), GeoModel\getLocationById(), RoxModelBase\getLoggedInMember(), AdminModel\getMassmailRecipientsInfo(), getMember(), ApiModel\getMember(), Address\getMemberAddress(), Blog\getMemberByUsername(), Group\getMemberCount(), ApiModel\getMemberData(), MembersModel\getMemberFromEmail(), GroupMembership\getMemberGroups(), MemberRole\getMemberRoles(), Group\getMembers(), MembersModel\getMemberWithId(), GalleryModel\getMemberWithUserId(), MembersModel\getMemberWithUsername(), Group\getNewMembers(), ProfileNote\getNote(), Member\getNote(), ProfileNote\getNotes(), Member\getNotes(), Geo\getParent(), Forums\GetPostVote(), RolePrivilege\getPrivilege(), PrivilegeScope\getPrivilege(), RolePrivilege\getPrivilegeRoles(), Role\getPrivileges(), RelatedGroup\getRelatedGroupsLog(), RolePrivilege\getRole(), MemberRole\getRoleMembers(), RolePrivilege\getRolePrivileges(), Member\getRoles(), Role\getScopesForMemberRole(), Member\getSignupFeedback(), Comment\getToMember(), Geo\getTotalUsage(), Geo\getUsageForAllTypes(), Member\getVisitorCount(), Member\getVisitorsSubset(), Thread\getVoteResult(), Post\getVoteResult(), Thread\getVotes(), Post\getVotes(), Member\hasPrivilege(), Member\hasRole(), GroupsModel\inviteMember(), Group\isGroupOwner(), Group\isMember(), AboutModel\isVolunteer(), GroupsModel\joinGroup(), GroupsModel\leaveGroup(), VerifyMembersModel\LoadApprovedVerifiers(), RoxEntityBase\loadEntities(), GeoModel\loadLocation(), GroupsModel\memberAcceptedInvitation(), RelatedGroupsModel\memberAddsRelatedGroup(), GroupsModel\memberDeclinedInvitation(), RelatedGroupsModel\memberDeletesRelatedGroup(), MemberRole\memberHasRole(), Group\memberJoin(), Group\memberLeave(), GroupsModel\notifyGroupAdmins(), Forums\prepare_notification(), AdminModel\processMembers(), GroupsModel\realImg(), Member\recordVisit(), Role\removeFromMember(), Group\removeGroupOwner(), Member\removeLanguages(), GroupsModel\resignGroupAdmin(), RoxModelBase\restoreLoggedInMember(), Forums\searchUserposts(), MembersModel\sendCommentNotification(), FeedbackModel\sendFeedback(), GroupsModel\sendInvitation(), sendOrComplain(), Group\setGroupOwner(), MembersModel\setLocation(), MembersModel\setSessionLanguage(), MembersModel\showAvatar(), RelatedGroupsModel\showRelatedGroupsLog(), GroupsModel\thumbImg(), AdminModel\treasurerEditCreateDonationVarsOk(), GroupsModel\updateMembershipSettings(), MembersModel\updateProfile(), MembersModel\updateRelation(), and AdminModel\updateVolunteerBoard().
RoxComponentBase::get ($key) protected inherited
Referenced by SignupClosedPage\column_col3(), SignupProblemPage\column_col3(), and SignupPage\column_col3().
RoxModelBase::get_dao () protected inherited
normally the $dao should be injected. If it's not, this function creates a new one out of the blue..
RoxModelBase::getDao () protected inherited
RoxComponentBase::getLog () protected inherited
wrapper function for MOD_log::get()
protected
Returns
object
References MOD_log\get().
Referenced by RoxComponentBase\logWrite().
RoxModelBase::getLoggedInMember () inherited
returns the currently logged in member
public
Returns
object|false
References $_SESSION, and RoxModelBase\createEntity().
Referenced by AdminTreasurerPage\__construct(), AdminTreasurerEditCreateDonationPage\__construct(), AdminTreasurerStartDonationCampaignPage\__construct(), Suggestion\addOption(), Forums\adjustThreadsCountToShow(), GroupsModel\canAccessGroupAdmin(), GroupsModel\canAccessGroupDelete(), ActivitiesModel\checkEditCreateActivityVarsOk(), Blog\commentProcess(), Blog\countRecentPosts(), GalleryModel\createGallery(), GroupsModel\createGroup(), AdminModel\createMassmail(), SuggestionsModel\createSuggestion(), MembersModel\deleteNoteForMember(), Suggestion\deleteOption(), Suggestion\editOption(), SuggestionsModel\editSuggestion(), RightsModel\getAllRoles(), SearchModel\getDefaultAdvancedOptions(), Group\getGroupOwners(), ActivitiesModel\getMyActivities(), ActivitiesModel\getMyActivitiesCount(), ActivitiesModel\getNearMeQuery(), Forums\GetPostVote(), Blog\getRecentPostIt(), Blog\getRecentPostsArray(), Blog\getStickyPostIt(), Blog\getTaggedPostsIt(), Blog\getTagsIt(), Blog\getTinyMCEPreference(), Forums\getTinyMCEPreference(), Trip\getTripData(), Trip\getTrips(), RightsModel\hasRightsAccess(), ActivitiesModel\joinLeaveActivity(), Suggestion\loadEntity(), SuggestionOption\loadEntity(), LoginModel\logout(), GroupsModel\memberAcceptedInvitation(), GroupsModel\memberDeclinedInvitation(), Trip\prepareEditData(), GroupsModel\resignGroupAdmin(), FeedbackModel\sendFeedback(), MembersModel\setCommentGuidelinesRead(), LoginModel\setPreferredLanguage(), ActivitiesModel\setRadius(), Forums\switchShowMyGroupsTopicsOnly(), Suggestion\update(), ActivitiesModel\updateActivity(), AdminModel\updateMassmail(), AdminModel\updateVolunteerBoard(), GalleryModel\uploadProcess(), and MembersModel\writeNoteForMember().
InviteModel::getMember ($id)
References $id, and RoxModelBase\createEntity().
RoxModelBase::getMemoryCookie () protected inherited
Reads the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
References $_SESSION, elseif, and RoxModelBase\setMemoryCookie().
Referenced by RoxModelBase\restoreLoggedInMember().
RoxComponentBase::getValues () protected inherited
RoxComponentBase::getVersionInfo () protected inherited
returns the revision number saved in revision.txt
protected
Returns
string
References $version.
Referenced by FeedbackModel\sendFeedback().
RoxComponentBase::getWords () protected inherited
returns an instance of the MOD_words class
protected
Returns
object
Referenced by VisualComponent\__call(), GroupsController\acceptInvitation(), GroupsController\addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), GeoPopupPage\body(), GalleryDeletePage\breadcrumbs(), GalleryBasePage\breadcrumbs(), SuggestionsController\changeStateCallback(), MyVisitorsPage\column_col3(), GalleryFlickrPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryAllImagesPage\column_col3(), HellouniversePage\column_col3(), GeoAdminPage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), LinkUpdatePage\column_col3(), GalleryDeletePage\column_col3(), NewsletterPage\column_col3(), FeedbackSentPage\column_col3(), VerifyMembersNotActivePage\column_col3(), VerifyMyselfPage\column_col3(), OneNewsLetterPage\column_col3(), GalleryManagePage\column_col3(), GalleryAllGalleriesPage\column_col3(), VerifiedApprovedVerifiers\column_col3(), ActivitiesFindPage\column_col3(), GroupStartPage\column_col3(), GroupMemberSettingsPage\column_col3(), AboutFaqPage\column_col3(), GroupDeletePage\column_col3(), GroupJoinPage\column_col3(), GroupWikiPage\column_col3(), GroupAddRelatedGroupPage\column_col3(), GroupDeleteRelatedGroupPage\column_col3(), GroupLeavePage\column_col3(), GroupForumPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), AboutFaqsectionPage\column_col3(), PollsPage\column_col3(), VerifiedMembersViewPage\column_col3(), HellouniverseTabbedPage\column_col3(), GroupForumsOverviewPage\column_col3(), GroupsController\declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), Member\get_all_relations(), MembersModel\get_relation_between_members(), Member\get_trad_by_tradid(), Group\getDescription(), FullPagePager\getHtml(), Note\getIdRelMember(), Forums\GetLanguageName(), LastCommentsPage\getLastCommentsTitle(), PageWithRoxLayout\getPage_meta_description(), PageWithRoxLayout\getPage_meta_keyword(), UpdateMandatoryPage\getPageTitle(), AboutTheideaPage\getPageTitle(), ActivitiesBasePage\getPageTitle(), CityPage\getPageTitle(), CountriesPage\getPageTitle(), CountryPage\getPageTitle(), RegionPage\getPageTitle(), SafetyBasePage\getPageTitle(), SearchMembersBasePage\getPageTitle(), SuggestionsBasePage\getPageTitle(), NewsletterPage\getPageTitle(), OneNewsLetterPage\getPageTitle(), GroupsBasePage\getPageTitle(), VerifiedMembersViewPage\getPageTitle(), PollsPage\getPageTitle(), SuggestionsBasePage\getStateSelect(), DebugPage\getSubmenuItems(), GalleryUserPage\getSubmenuItems(), AboutBasePage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), PageWithHTML\head(), MembersController\index_loggedIn(), GroupsController\joined(), GroupsController\kickMember(), Forums\LanguageChoices(), GroupsController\leave(), GroupsController\left(), PageWithRoxLayout\leftoverTranslationLinks(), AboutFaqsectionPage\leftSidebar(), AboutFaqPage\leftSidebar(), InactiveProfilePage\leftsidebar(), AdminMassMailEnqueuePage\leftSidebar(), VerifyMembersPage\leftSidebar(), AdminMassMailDetailsPage\leftSidebar(), AdminMassMailEditCreatePage\leftSidebar(), VerifiedApprovedVerifiers\leftSidebar(), VerifiedMembersViewPage\leftSidebar(), PollsPage\leftSidebar(), MemberPage\leftsidebar(), LoginController\loginCallback(), GalleryController\manage(), MessagesPageWithMailbox\messageActions(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), NotifyAdminPage\notesActions(), GroupsModel\notifyGroupAdmins(), PageWithRoxLayout\quicksearch(), GroupsController\resignAsAdmin(), SuggestionsController\restoreOption(), GeoController\SelectorInclude(), GroupsModel\sendInvitation(), Group\setDescription(), PageWithRoxLayout\SetMetaKey(), AbstractBasePage\showTemplate(), PageWithRoxLayout\submenu(), MessagesBasePage\teaserContent(), GroupSettingsPage\teaserContent(), GroupsSearchPage\teaserContent(), GroupsMyGroupsPage\teaserContent(), GroupsCreationPage\teaserContent(), GroupInvitePage\teaserContent(), TourPage\teaserContent(), GroupsFeaturedPage\teaserContent(), GroupsOverviewPage\teaserContent(), LastCommentsPage\teaserContent(), GroupForumsOverviewPage\teaserContent(), GroupsBasePage\teaserContent(), ResetPasswordPage\teaserHeadline(), ResetPasswordFinishPage\teaserHeadline(), VerifyNoMemberSpecifiedPage\teaserHeadline(), AboutBasePage\teaserHeadline(), GalleryImageNotFoundPage\teaserHeadline(), GalleryAvatarsPage\teaserHeadline(), AboutStatisticsPage\teaserHeadline(), VerifyMyselfPage\teaserHeadline(), VerifyMembersNotActivePage\teaserHeadline(), VerifyMembersPage\teaserHeadline(), GalleryBasePage\teaserHeadline(), SearchMembersBasePage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), SuggestionsBasePage\teaserHeadline(), OneNewsLetterPage\teaserHeadline(), VerifiedMembersViewPage\teaserHeadline(), PollsPage\teaserHeadline(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), GroupMembership\updateMembership(), GalleryController\upload(), GalleryController\uploadedProcess(), GalleryController\user(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
InviteModel::isEmailAddress ($email)
Referenced by sendOrComplain().
RoxComponentBase::logWrite ($string, $type = 'Log') protected inherited
wrapper for calls to MOD_log::get->write()
Parameters
string $string
string $type protected
References $type, and RoxComponentBase\getLog().
Referenced by GroupsController\acceptInvitation(), GroupsController\acceptMember(), MembersModel\addComment(), GroupsController\addMemberAsAdmin(), MembersModel\addRelation(), GroupsController\banMember(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), GroupsController\createGroupCallback(), GroupsController\declineInvitation(), GroupsController\delete(), MembersModel\delete_translation_multiple(), FeedbackModel\feedbackMail(), MembersController\index_loggedIn(), GroupsController\inviteMember(), GroupsController\inviteMemberAjax(), GroupsController\joined(), GroupsController\kickMember(), GroupsController\left(), Geo\placeType(), AdminModel\processMembers(), GroupsController\resignAsAdmin(), MembersModel\set_preference(), MembersModel\set_public_profile(), MembersModel\setLocation(), MembersModel\updateProfile(), and MembersModel\updateRelation().
RoxComponentBase::refresh_get ($key) inherited
RoxModelBase::restoreLoggedInMember () inherited
Restore session if memory cookie exists
References RoxModelBase\createEntity(), and RoxModelBase\getMemoryCookie().
InviteModel::sendOrComplain ($input)
Look if the information in $input is ok to send. If yes, send and return a confirmation. Otherwise, return an array that tells what is missing.
required information in $input: sender_id, receiver_id, text
optional fields in $input: reply_to_id, draft_id
Parameters
unknown_type $input
References $_SESSION, $member, $problems, $status, RoxModelBase\createEntity(), elseif, isEmailAddress(), MOD_crypt\MemberReadCrypted(), MOD_mail\sendEmail(), style(), and MOD_log\write().
RoxModelBase::setMemoryCookie ($id, $seriesToken = '', $authToken = '') protected inherited
Sets the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
References $id.
Referenced by RoxModelBase\getMemoryCookie().
RoxModelBase::singleLookup ($query_string) inherited
Referenced by PollsModel\AddChoice(), GeoModel\addHierarchy(), VerifyMembersModel\AddNewVerified(), MembersModel\addRelation(), PollsModel\AddVote(), PollsModel\CancelVote(), PollsModel\CanUserContribute(), MessagesModel\CaptchaNeeded(), VerifyMembersModel\CheckAndGetUsername(), LoginModel\checkBWPassword(), MembersModel\confirmRelation(), Member\count_mynotes(), LoginModel\createMissingTBUser(), MessagesModel\deleteMessage(), MembersModel\deleteRelation(), Forums\DeleteVoteForPost(), LoginModel\encryptPasswordBW(), LanguageLookupModel\findLanguageWithCode(), Member\get_publicProfile(), Member\get_userid(), Member\get_verification_status(), DonateModel\getCampaignValues(), LinkModel\getChanges(), AdminModel\getCountryCodeForGeonameId(), GeoModel\getDataById(), AdminModel\getDonation(), AdminModel\getDonationCampaignStatus(), FeedbackModel\getFeedbackCategory(), AdminModel\getGeonameIdForCountryCode(), Forums\GetIdThread(), RoxFrontRouterModel\getLanguage(), MessagesModel\getMember(), LinkModel\getMemberdata(), MembersModel\getMemberFromEmail(), LinkModel\getMemberID(), GalleryModel\getMemberWithUserId(), MessagesModel\getMessage(), PollsModel\GetPollResults(), RoxFrontRouterModel\getPossibleUrlLanguage(), SearchModel\getResultsForLocation(), LoginModel\getTBUserForBWMember(), GeoModel\getUsagetypeId(), Places\getWikiPage(), PollsModel\HasAlreadyContributed(), MessagesModel\hasMessageLimitExceeded(), PollsModel\IsMemberAllowed(), CommunityModel\isVolunteer(), NewsletterModel\Load(), VerifyMembersModel\LoadApprovedVerifiers(), PollsModel\LoadList(), PollsModel\LoadPoll(), PollsModel\PrepareContribute(), MessagesModel\sendOrComplain(), MembersModel\set_preference(), MembersModel\set_profile_language(), MembersModel\set_public_profile(), LoginModel\setBWMemberAsLoggedIn(), MembersModel\setLocation(), LoginModel\setupBWSession(), SearchModel\suggestLocationsFromDatabase(), PollsModel\UpdateChoice(), GeoModel\updateGeonameId(), PollsModel\UpdatePoll(), MembersModel\updateRelation(), MessagesModel\updateSpamInfo(), GeoModel\updateUsageCounter(), and Forums\VoteForPost().
RoxModelBase::singleLookup_assoc ($query_string) inherited
Referenced by Member\getProfilePictureID().
InviteModel::style ($text, $photo)
References $_SESSION, $text, and MOD_layoutbits\smallUserPic_username().
Referenced by sendOrComplain().
Field Documentation
RoxModelBase::$_entity_factory protected inherited
The documentation for this class was generated from the following file:
invite.model.php