Rox: Group Class Reference
Group Class Reference
Public Member Functions
__get ($key)
__construct ($groupId=false)
findBySearchTerms ($terms=array(), $offset, $limit=10)
getNewMembers ()
getMembers ($status=false, $offset=0, $limit=null)
getLastLoggedInMembers ($numberOfMembers=20)
getEmailAcceptingMembers ()
getMemberCount ($status=false)
isMember ($memberId)
memberJoin ($memberId, $status)
memberLeave (Member $member)
createGroup ($input)
deleteGroup ()
setDescription ($description)
getDescription ()
updateSettings ($description, $type, $visible_posts, $visible_comments, $picture= '')
isGroupOwner ($member)
getGroupOwners ()
setGroupOwner (Member $member)
removeGroupOwner ($member)
getGroupForGeo (Geo $geo, $local=false)
findRelatedGroups ($groupId, $offset=0, $limit=null)
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
loadEntity (array $data)
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_table_name = 'groups'
$_validations = array('Name', 'Type')
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Data Fields inherited from RoxEntityBase
$sql_order = ''
Detailed Description
Definition at line 33 of file group.entity.php.
Constructor & Destructor Documentation
Group::__construct ($groupId = false)
Definition at line 58 of file group.entity.php.
References RoxEntityBase\findById().
Member Function Documentation
Group::__get ($key)
overrides the __get method of Component in order fix the output
Parameters
string $key - variable to get
Returns
mixed public
Definition at line 48 of file group.entity.php.
Group::createGroup ($input)
Create a group given some input
Parameters
array $input - array containing Group_ and Type public
Returns
mixed Will return the insert id of the operation or false
Definition at line 291 of file group.entity.php.
References $group_name, $type, RoxModelBase\createEntity(), and RoxEntityBase\insert().
Group::deleteGroup ()
Delete a group Removes a row from the groups table and unsets data in the entity so it can't be reused
public
Returns
bool
Definition at line 318 of file group.entity.php.
References $member, $members, getMembers(), RoxEntityBase\isLoaded(), and memberLeave().
Group::findBySearchTerms ($terms = array(), $offset, $limit = 10)
Uses an array of terms to create a create to search for groups with simple or search on names for now
Todo:
implement proper group search - this will wait on various db implementations
Parameters
array $terms - array of strings to be used in search
Returns
mixed false or group of arrays that match any of the terms public
Definition at line 102 of file group.entity.php.
References RoxEntityBase\findAll(), and RoxEntityBase\findByWhereMany().
Group::findRelatedGroups ($groupId, $offset = 0, $limit = null)
find related groups for a group
Parameters
int $groupId - id of the group
Returns
mixed false or array of groups that are related with the group public
Definition at line 534 of file group.entity.php.
References RoxEntityBase\findByWhereMany().
Referenced by RelatedGroupsModel\getMyGroups().
Group::getDescription ()
returns the description for a group
public
Returns
string
Definition at line 380 of file group.entity.php.
References RoxComponentBase\getWords(), and RoxEntityBase\isLoaded().
Group::getEmailAcceptingMembers ()
return the members of the group accepting email from the other group members
Parameters
string $status - which status to check for (In, WantToBeIn, Kicked) public
Returns
array
Definition at line 196 of file group.entity.php.
References RoxModelBase\createEntity().
Group::getGroupForGeo (Geo $geo, $local = false)
finds a local group for a geo location
Parameters
object $geo public
Returns
object|false
Definition at line 517 of file group.entity.php.
References RoxEntityBase\findByWhere(), and RoxEntityBase\isLoaded().
Group::getGroupOwners ()
returns member entities representing the group owners, if group has owners
Returns
mixed - member entities or false public
Definition at line 444 of file group.entity.php.
References RoxModelBase\createEntity(), RoxModelBase\getLoggedInMember(), and RoxEntityBase\isLoaded().
Group::getLastLoggedInMembers ($numberOfMembers = 20)
return the x recently logged in members of the group
Parameters
int $numberOfMembers- number of last logged in members to return public
Returns
array - GroupMembership entities of x recently logged in members
Definition at line 174 of file group.entity.php.
References RoxModelBase\createEntity().
Group::getMemberCount ($status = false)
return the members of the group
Parameters
string $status - which status to check for (In, WantToBeIn, Kicked) public
Returns
int
Definition at line 213 of file group.entity.php.
References $status, and RoxModelBase\createEntity().
Group::getMembers ($status = false, $offset = 0, $limit = null)
return the members of the group
Parameters
string $status - which status to check for (In, WantToBeIn, Kicked)
int $offset
int $limit public
Returns
array
Definition at line 154 of file group.entity.php.
References $status, and RoxModelBase\createEntity().
Referenced by deleteGroup().
Group::getNewMembers ()
return the members of the group that have joined in the last two weeks
public
Returns
array
Definition at line 134 of file group.entity.php.
References RoxModelBase\createEntity().
Group::isGroupOwner ($member)
checks whether a given member entity is the owner of the group
Parameters
object $member - entity to check for
Returns
bool public
Definition at line 426 of file group.entity.php.
References $member, RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Referenced by memberLeave(), and removeGroupOwner().
Group::isMember ($memberId)
Check if a member id is connected with a group
Parameters
int $memberId - id of the member to check public
Returns
bool
Definition at line 235 of file group.entity.php.
References RoxModelBase\createEntity().
Referenced by RelatedGroup\AddRelatedGroup(), and setGroupOwner().
Group::loadEntity (array $data) protected
Definition at line 73 of file group.entity.php.
References $query, and $status.
Group::memberJoin ($memberId, $status)
puts a member in a group, aka joining the group
Parameters
int $memberId - id of the member that joins public
Returns
bool
Definition at line 252 of file group.entity.php.
References $status, and RoxModelBase\createEntity().
Group::memberLeave (Member $member)
deletes a member from a group, aka leaving the group
Parameters
object $member - the member that leaves public
Returns
bool
Definition at line 269 of file group.entity.php.
References RoxModelBase\createEntity(), isGroupOwner(), and removeGroupOwner().
Referenced by deleteGroup().
Group::removeGroupOwner ($member)
removes ownership of group from member
public
Returns
bool
Definition at line 497 of file group.entity.php.
References $member, RoxModelBase\createEntity(), isGroupOwner(), and RoxEntityBase\isLoaded().
Referenced by memberLeave().
Group::setDescription ($description)
sets or updates the description for a group
Parameters
string $description - string describing the group
Returns
bool public
Definition at line 349 of file group.entity.php.
References $description, $words, elseif, RoxEntityBase\getPKValue(), RoxComponentBase\getWords(), RoxEntityBase\isLoaded(), and RoxEntityBase\update().
Referenced by updateSettings().
Group::setGroupOwner (Member $member)
sets ownership for a group - owner has admin powers + more for a group
Parameters
object $member public
Returns
bool
Definition at line 481 of file group.entity.php.
References RoxModelBase\createEntity(), RoxEntityBase\getPKValue(), RoxEntityBase\isLoaded(), and isMember().
Group::updateSettings ($description, $type, $visible_posts, $visible_comments, $picture = '')
updates a groups settings
Parameters
string $description - the description of the group
string $type - how public the group is
string $visible_posts - if the forum posts of the group should be visible or not public
Returns
bool
Definition at line 399 of file group.entity.php.
References $description, $type, RoxEntityBase\isLoaded(), setDescription(), and RoxEntityBase\update().
Field Documentation
Group::$_table_name = 'groups' protected
Definition at line 36 of file group.entity.php.
Group::$_validations = array('Name', 'Type') protected
Definition at line 38 of file group.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/groups/group.entity.php