Rox: RoxFrontRouter Class Reference
RoxFrontRouter Class Reference
Public Member Functions
__construct ()
route ()
Protected Member Functions
setBaseUri ()
initUser ()
setLanguage ()
setLanguageByBrowser ()
setSessionLanguage ()
route_ajax ($keyword)
route_normal ()
traditionalPostHandling ()
try_unserialize ($str)
runControllerAjaxMethod ($classname, $keyword)
runControllerMethod ($classname, $method, $request, $route_vars)
renderPage ($page)
createController ($classname)
createLayoutkit ()
Detailed Description
Definition at line 4 of file roxfrontrouter.class.php.
Constructor & Destructor Documentation
RoxFrontRouter::__construct ()
Definition at line 10 of file roxfrontrouter.class.php.
Member Function Documentation
RoxFrontRouter::createController ($classname) protected
create a controller and inject some data
Parameters
unknown_type $classname
Definition at line 474 of file roxfrontrouter.class.php.
RoxFrontRouter::createLayoutkit () protected
Definition at line 484 of file roxfrontrouter.class.php.
References $formkit, and $layoutkit.
Referenced by renderPage().
RoxFrontRouter::initUser () protected
Initialise the current user. Sets language and online status.
Definition at line 72 of file roxfrontrouter.class.php.
References $_SESSION, $member, $roxModelBase, MOD_online\get(), and setLanguage().
Referenced by route().
RoxFrontRouter::renderPage ($page) protected
Definition at line 449 of file roxfrontrouter.class.php.
References createLayoutkit().
Referenced by runControllerMethod().
RoxFrontRouter::route ()
choose a controller and call the index() function. If necessary, flush the buffered output.
Definition at line 20 of file roxfrontrouter.class.php.
References $request, initUser(), route_ajax(), route_normal(), and setBaseUri().
RoxFrontRouter::route_ajax ($keyword) protected
Definition at line 194 of file roxfrontrouter.class.php.
References $request, $vars, and runControllerAjaxMethod().
Referenced by route().
RoxFrontRouter::route_normal () protected
Definition at line 202 of file roxfrontrouter.class.php.
References $action, $request, $vars, runControllerMethod(), and traditionalPostHandling().
Referenced by route().
RoxFrontRouter::runControllerAjaxMethod ($classname, $keyword) protected
Definition at line 339 of file roxfrontrouter.class.php.
References json_encode().
Referenced by route_ajax().
RoxFrontRouter::runControllerMethod ($classname, $method, $request, $route_vars) protected
Definition at line 395 of file roxfrontrouter.class.php.
References $request, and renderPage().
Referenced by route_normal().
RoxFrontRouter::setBaseUri () protected
Definition at line 40 of file roxfrontrouter.class.php.
References elseif.
Referenced by route().
RoxFrontRouter::setLanguage () protected
Definition at line 114 of file roxfrontrouter.class.php.
References $_SESSION, and setLanguageByBrowser().
Referenced by initUser().
RoxFrontRouter::setLanguageByBrowser () protected
Definition at line 153 of file roxfrontrouter.class.php.
References $_SESSION.
Referenced by setLanguage().
RoxFrontRouter::setSessionLanguage () protected
Definition at line 190 of file roxfrontrouter.class.php.
RoxFrontRouter::traditionalPostHandling () protected
Definition at line 306 of file roxfrontrouter.class.php.
References $_SESSION, and try_unserialize().
Referenced by route_normal().
RoxFrontRouter::try_unserialize ($str) protected
Definition at line 320 of file roxfrontrouter.class.php.
References $error, and $res.
Referenced by traditionalPostHandling().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/routing/roxfrontrouter.class.php