Rox: GalleryController Class Reference
GalleryController Class Reference
Public Member Functions
__construct ()
__destruct ()
index ()
overview ()
gallery (Gallery $gallery, $upload=false)
deleteGallery (Gallery $gallery, $status)
gallerydetails (Gallery $gallery)
allgalleries ()
user ($userId)
manage ()
upload ()
usergalleries ($userId)
userimages ($userId)
image ($image)
deleteImage ($image)
uploadedProcess ($args, $action, $mem_redirect, $mem_resend)
ajaxlatestimages ($galleryId=false, $nopagination=false)
createGalleryCallback ($args, $action, $mem_redirect, $mem_resend)
editProcess ()
editGalleryProcess ()
manageCallback ($args, $action, $mem_redirect, $mem_resend)
updateGalleryCallback ($args, $action, $mem_redirect, $mem_resend)
commentProcess ($image=false)
uploadProcess ()
thumbImg ($id)
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 11 of file gallery.ctrl.php.
Constructor & Destructor Documentation
GalleryController::__construct ()
Definition at line 15 of file gallery.ctrl.php.
GalleryController::__destruct ()
Definition at line 23 of file gallery.ctrl.php.
Member Function Documentation
GalleryController::ajaxlatestimages ($galleryId = false, $nopagination = false)
handles showing all images of a user
public
Returns
string
Definition at line 507 of file gallery.ctrl.php.
References $galleryId, $loggedInMember, and $statement.
Referenced by index().
GalleryController::allgalleries ()
handles showing all galleries available
public
Returns
object $page
Definition at line 314 of file gallery.ctrl.php.
References $loggedInMember, and $member.
Referenced by index().
GalleryController::commentProcess ($image = false)
Definition at line 685 of file gallery.ctrl.php.
References $callbackId, $image, and $vars.
GalleryController::createGalleryCallback ($args, $action, $mem_redirect, $mem_resend)
createGalleryCallback
Parameters
Object $args
Object $action
Object $mem_redirect memory for the page after redirect
Object $mem_resend memory for resending the form
Returns
string relative request for redirect
Definition at line 586 of file gallery.ctrl.php.
References $desc, $errors, $galleryId, $mem_redirect, $request, and $vars.
GalleryController::deleteGallery (Gallery $gallery, $status)
handles the deletion of a gallery
Parameters
Gallery $gallery - gallery to delete
public
Returns
object $page
Definition at line 272 of file gallery.ctrl.php.
References $gallery, $loggedInMember, and $status.
Referenced by index().
GalleryController::deleteImage ($image)
handles the deletion of a single image
public
Returns
object $page
Definition at line 464 of file gallery.ctrl.php.
References $image, $loggedInMember, image(), and user().
Referenced by index().
GalleryController::editGalleryProcess ()
xxx
public
Definition at line 641 of file gallery.ctrl.php.
References $callbackId, and $vars.
GalleryController::editProcess ()
xxx
public
Definition at line 616 of file gallery.ctrl.php.
References $callbackId, and $vars.
GalleryController::gallery (Gallery $gallery, $upload = false)
handles showing a page for a single gallery
Parameters
Gallery $gallery - gallery to work on
public
Returns
object $page
Definition at line 248 of file gallery.ctrl.php.
References $gallery, $loggedInMember, and MOD_member\getUserHandle().
Referenced by index().
GalleryController::gallerydetails (Gallery $gallery)
handles showing a page for a single gallery
public
Returns
object $page
Definition at line 290 of file gallery.ctrl.php.
References $gallery, $loggedInMember, and $request.
Referenced by index().
GalleryController::image ($image)
handles showing a page for a single image
public
Returns
object $page
Definition at line 445 of file gallery.ctrl.php.
References $image.
Referenced by deleteImage(), and index().
GalleryController::index ()
Definition at line 28 of file gallery.ctrl.php.
References $gallery, $galleryId, $id, $image, $loggedInMember, $member, $name, $request, $status, $subTab, $vars, ajaxlatestimages(), allgalleries(), deleteGallery(), deleteImage(), gallery(), gallerydetails(), User\HANDLE_PREGEXP, image(), manage(), overview(), RoxControllerBase\redirect(), RoxControllerBase\redirectToLogin(), thumbImg(), upload(), uploadedProcess(), user(), and userimages().
GalleryController::manage ()
handles showing a page where the user manages all his pictures
public
Returns
object $page
Definition at line 365 of file gallery.ctrl.php.
References $loggedInMember, $words, RoxComponentBase\getWords(), and RoxControllerBase\redirect().
Referenced by index().
GalleryController::manageCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 661 of file gallery.ctrl.php.
References $mem_redirect, $request, and $vars.
GalleryController::overview ()
handles showing gallery overview page
public
Returns
object $page
Definition at line 224 of file gallery.ctrl.php.
Referenced by index().
GalleryController::thumbImg ($id)
Definition at line 718 of file gallery.ctrl.php.
References $d, and $id.
Referenced by index().
GalleryController::updateGalleryCallback ($args, $action, $mem_redirect, $mem_resend)
Definition at line 673 of file gallery.ctrl.php.
References $mem_redirect, $request, and $vars.
GalleryController::upload ()
handles showing a page where the user uploads pictures
public
Returns
object $page
Definition at line 387 of file gallery.ctrl.php.
References $loggedInMember, $words, RoxComponentBase\getWords(), and RoxControllerBase\redirect().
Referenced by index().
GalleryController::uploadedProcess ($args, $action, $mem_redirect, $mem_resend)
Definition at line 478 of file gallery.ctrl.php.
References $username, $vars, $words, elseif, RoxComponentBase\getWords(), and RoxControllerBase\setFlashError().
Referenced by index().
GalleryController::uploadProcess ()
Definition at line 703 of file gallery.ctrl.php.
References $callbackId, and $vars.
GalleryController::user ($userId)
handles showing an overview of images and galleries of a user
public
Returns
object $page
Definition at line 335 of file gallery.ctrl.php.
References $loggedInMember, $member, $words, and RoxComponentBase\getWords().
Referenced by deleteImage(), and index().
GalleryController::usergalleries ($userId)
handles showing all galleries of a user
public
Returns
object $page
Definition at line 405 of file gallery.ctrl.php.
References $loggedInMember, and $member.
GalleryController::userimages ($userId)
handles showing all images of a user
public
Returns
object $page
Definition at line 427 of file gallery.ctrl.php.
References $loggedInMember, and $member.
Referenced by index().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/gallery/gallery.ctrl.php