Rox: ActivitiesController Class Reference
ActivitiesController Class Reference
Public Member Functions
__construct ()
activities ()
joinLeaveActivityCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
cancelUncancelActivityCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
show ()
editCreateActivityCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
editcreate ()
myActivities ()
upcomingActivities ()
pastActivities ()
setRadiusCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
activitiesNearMe ()
searchActivitiesCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
search ()
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const ACTIVITIES_PER_PAGE = 10
const ATTENDEES_PER_PAGE = 10
Protected Member Functions
getPager ($url, $count, $pageno, $itemsPerPage=self::ACTIVITIES_PER_PAGE)
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Activities controller class.
Author
shevek
Definition at line 7 of file activities.ctrl.php.
Constructor & Destructor Documentation
ActivitiesController::__construct ()
Constructor.
Definition at line 21 of file activities.ctrl.php.
Member Function Documentation
ActivitiesController::activities ()
Redirects to my activities if a member is logged in otherwise shows upcoming activities
Definition at line 30 of file activities.ctrl.php.
References RoxControllerBase\redirectAbsolute().
ActivitiesController::activitiesNearMe ()
Definition at line 249 of file activities.ctrl.php.
References $count, $distance, $loggedInMember, getPager(), and RoxControllerBase\redirectAbsolute().
ActivitiesController::cancelUncancelActivityCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 57 of file activities.ctrl.php.
References $_SESSION, and $errors.
ActivitiesController::editcreate ()
Definition at line 147 of file activities.ctrl.php.
References $id, $loggedInMember, and RoxControllerBase\redirectAbsolute().
ActivitiesController::editCreateActivityCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 127 of file activities.ctrl.php.
References $_SESSION, and $errors.
ActivitiesController::getPager ($url, $count, $pageno, $itemsPerPage = self::ACTIVITIES_PER_PAGE) protected
Definition at line 75 of file activities.ctrl.php.
References $count, $pager, $params, and $url.
Referenced by activitiesNearMe(), myActivities(), pastActivities(), search(), and upcomingActivities().
ActivitiesController::joinLeaveActivityCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 38 of file activities.ctrl.php.
References $_SESSION, and $errors.
ActivitiesController::myActivities ()
Definition at line 176 of file activities.ctrl.php.
References $count, $loggedInMember, getPager(), and RoxControllerBase\redirectAbsolute().
ActivitiesController::pastActivities ()
Definition at line 220 of file activities.ctrl.php.
References $count, $loggedInMember, and getPager().
ActivitiesController::search ()
Definition at line 283 of file activities.ctrl.php.
References $count, $loggedInMember, and getPager().
ActivitiesController::searchActivitiesCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 271 of file activities.ctrl.php.
References $_SESSION, and $errors.
ActivitiesController::setRadiusCallback (StdClass $args, ReadOnlyObject $action, ReadWriteObject $mem_redirect, ReadWriteObject $mem_resend)
Definition at line 242 of file activities.ctrl.php.
ActivitiesController::show ()
Definition at line 88 of file activities.ctrl.php.
References $id, $loggedInMember, $member, $params, and RoxControllerBase\redirectAbsolute().
ActivitiesController::upcomingActivities ()
Definition at line 197 of file activities.ctrl.php.
References $count, $loggedInMember, and getPager().
Field Documentation
const ActivitiesController::ACTIVITIES_PER_PAGE = 10
Definition at line 9 of file activities.ctrl.php.
const ActivitiesController::ATTENDEES_PER_PAGE = 10
Definition at line 10 of file activities.ctrl.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/activities/activities.ctrl.php