Rox: Suggestion Class Reference
Suggestion Class Reference
Public Member Functions
__construct ($suggestionId=false)
update ($status=false)
addOption ($summary, $description)
editOption ($optionId, $summary, $description)
deleteOption ($optionId)
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
loadEntity (array $data)
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_table_name = 'suggestions'
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Data Fields inherited from RoxEntityBase
$sql_order = ''
Detailed Description
represents a single suggestion
Definition at line 7 of file suggestion.entity.php.
Constructor & Destructor Documentation
Suggestion::__construct ($suggestionId = false)
Definition at line 11 of file suggestion.entity.php.
References RoxEntityBase\findById().
Member Function Documentation
Suggestion::addOption ($summary, $description)
Definition at line 222 of file suggestion.entity.php.
References $description, $id, and RoxModelBase\getLoggedInMember().
Suggestion::deleteOption ($optionId)
Definition at line 244 of file suggestion.entity.php.
References RoxModelBase\getLoggedInMember().
Suggestion::editOption ($optionId, $summary, $description)
Definition at line 234 of file suggestion.entity.php.
References $description, and RoxModelBase\getLoggedInMember().
Suggestion::loadEntity (array $data) protected
overloads RoxEntityBase::loadEntity to load related data
Parameters
array $data protected
Returns
bool
Definition at line 28 of file suggestion.entity.php.
References $id, $member, $query, $status, SuggestionsModel\DURATION_ADDOPTIONS, SuggestionsModel\DURATION_DISCUSSION, SuggestionsModel\DURATION_VOTING, SuggestionsModel\DURATION_VOTING_STARTS, RoxModelBase\getLoggedInMember(), options, state, SuggestionsModel\SUGGESTIONS_ADD_OPTIONS, SuggestionsModel\SUGGESTIONS_DISCUSSION, SuggestionsModel\SUGGESTIONS_IMPLEMENTED, SuggestionsModel\SUGGESTIONS_IMPLEMENTING, SuggestionsModel\SUGGESTIONS_RANKING, SuggestionsModel\SUGGESTIONS_REJECTED, SuggestionsModel\SUGGESTIONS_VOTING, and RoxEntityBase\update().
Suggestion::update ($status = false)
Definition at line 191 of file suggestion.entity.php.
References $id, $query, $status, RoxModelBase\getLoggedInMember(), state, SuggestionsModel\SUGGESTIONS_RANKING, SuggestionsModel\SUGGESTIONS_VOTING, and update.
Field Documentation
Suggestion::$_table_name = 'suggestions' protected
Definition at line 9 of file suggestion.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/suggestions/suggestion.entity.php