Rox: SimplePie_File Class Reference
SimplePie_File Class Reference
Public Member Functions
__construct ($url, $timeout=10, $redirects=5, $headers=null, $useragent=null, $force_fsockopen=false)
Data Fields
$url
$useragent
$success = true
$headers = array()
$body
$status_code
$redirects = 0
$error
$method = SIMPLEPIE_FILE_SOURCE_NONE
Constructor & Destructor Documentation
SimplePie_File::__construct ($url, $timeout = 10, $redirects = 5, $headers = null, $useragent = null, $force_fsockopen = false)
References $headers, $info, $redirects, $url, $useragent, $value, SimplePie_Misc\absolutize_url(), SimplePie_Misc\compress_parse_url(), error, SimplePie_Misc\get_curl_version(), headers, SimplePie_Misc\parse_url(), SIMPLEPIE_FILE_SOURCE_CURL, SIMPLEPIE_FILE_SOURCE_FILE_GET_CONTENTS, SIMPLEPIE_FILE_SOURCE_FSOCKOPEN, SIMPLEPIE_FILE_SOURCE_LOCAL, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Field Documentation
SimplePie_File::$body
SimplePie_File::$error
SimplePie_File::$headers = array()
Referenced by __construct().
SimplePie_File::$method = SIMPLEPIE_FILE_SOURCE_NONE
SimplePie_File::$redirects = 0
Referenced by __construct().
SimplePie_File::$status_code
SimplePie_File::$success = true
SimplePie_File::$url
Referenced by __construct().
SimplePie_File::$useragent
Referenced by __construct().
The documentation for this class was generated from the following file:
File.php