Rox: Forums Class Reference
Forums Class Reference
Public Member Functions
GetLanguageChoosen ()
InsertInFTrad ($ss, $TableColumn, $IdRecord, $_IdMember=0, $_IdLanguage=-1, $IdTrad=-1)
ReplaceInFTrad ($ss, $TableColumn, $IdRecord, $IdTrad=0, $IdOwner=0)
GetPostVote ($IdPost)
GetIdThread ($IdPost)
VoteForPost ($IdPost, $Value)
DeleteVoteForPost ($IdPost)
FindAppropriatedLanguage ($IdPost=0)
__construct ()
switchForumOrderList ()
adjustThreadsCountToShow ($step=1)
switchShowMyGroupsTopicsOnly ()
checkGroupMembership ($group_id)
getAllCountries ($continent)
getAllLocations ($countrycode, $admincode)
getGroupName ($Name)
getAllAdmincodes ($country_code)
prepareForum ($showsticky=true)
getBoard ()
createProcess ()
getEditData ($callbackId)
editProcess ()
DofTradUpdate ($IdForumTrads, $P_Sentence, $P_IdLanguage=0)
replyProcess ($suggestion=false)
reportpostProcess ()
GetReports ($IdPost, $IdReporter=0)
prepareReportPost ($IdPost, $IdWriter)
prepareReportList ($IdMember, $StatusList)
countReportList ($IdMember, $StatusList)
prepareModeratorEditPost ($IdPost)
ModeratorEditPostProcess ()
ModeratorEditTagProcess ()
delProcess ()
prepareTopic ($WithDetail=false)
initLastPosts ()
searchSubscriptions ($cid=0, $IdThread=0, $IdTag=0)
UnsubscribeThread ($IdSubscribe=0, $Key="")
UnsubscribeThreadDirect ($IdThread=0, $ParamIdMember=0)
SubscribeThread ($IdThread, $ParamIdMember=0)
UnsubscribeTag ($IdSubscribe=0, $Key="")
UnsubscribeTagDirect ($IdTag=0, $ParamIdMember=0)
SubscribeTag ($IdTag, $ParamIdMember=0)
searchUserposts ($cid=0)
getTopic ()
isTopic ()
setTopMode ($Mode)
getTopMode ()
setGeonameid ($geonameid)
getGeonameid ()
setCountryCode ($countrycode)
getCountryCode ()
setAdminCode ($admincode)
getAdminCode ()
addTag ($tagid)
getTags ()
setGroupId ($IdGroup)
setThreadId ($threadid)
getThreadId ()
getIdGroup ()
setContinent ($continent)
getContinent ()
getPage ()
setPage ($page)
getPageArray ()
setPageArray ($page_array)
pushToPageArray ($page)
setMessageId ($messageid)
getMessageId ()
getIdContent ()
getTagsNamed ()
getAllTags ()
getTagsMaximum ()
getTopCategoryLevelTags ()
suggestTags ($search)
GetLanguageName ($IdLanguage)
LanguageChoices ($DefIdLanguage=-1)
ModeratorGroupChoice ()
GroupChoice ()
prepareModeratorEditTag ($IdTag)
getAllContinents ()
NotAllowedForGroup ($IdMember, $rPost)
prepare_notification ($postId, $type)
IsGroupSubscribed ($IdGroup=0, $ParamIdMember=0)
IsThreadSubscribed ($IdThread=0, $ParamIdMember=0)
IsTagSubscribed ($IdTag=0, $ParamIdMember=0)
isMembersForumPostsPagePublic ($userId=0)
GetThreadVisibility ($IdThread)
GetPostVisibility ($IdPost)
GetGroupEntity ($IdGroup)
getTinyMCEPreference ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const CV_THREADS_PER_PAGE = 15
const CV_POSTS_PER_PAGE = 200
const CV_TOPMODE_CATEGORY =1
const CV_TOPMODE_LASTPOSTS =2
const CV_TOPMODE_LANDING =3
const CV_TOPMODE_FORUM =4
const CV_TOPMODE_GROUPS =5
const NUMBER_LAST_POSTS_PREVIEW = 5
$THREADS_PER_PAGE
$POSTS_PER_PAGE
$words
$ForumOrderList
$BW_Right
Static Public Attributes
static $continents
Protected Member Functions
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_entity_factory
Constructor & Destructor Documentation
Forums::__construct ()
References $_SESSION, $layoutbits, CV_POSTS_PER_PAGE, CV_THREADS_PER_PAGE, CV_TOPMODE_CATEGORY, CV_TOPMODE_FORUM, CV_TOPMODE_LANDING, MOD_right\get(), SuggestionsModel\getGroupId(), setTopMode(), and words.
Member Function Documentation
RoxComponentBase::__call ($key, $args) inherited
RoxComponentBase::__get ($key) inherited
Referenced by Member\get_messengers().
RoxComponentBase::__set ($key, $value) inherited
References $value.
RoxComponentBase::__toString () inherited
Forums::addTag ($tagid)
Forums::adjustThreadsCountToShow ($step = 1)
References $layoutbits, $member, $query, $vars, RoxModelBase\getLoggedInMember(), and max.
RoxModelBase::bulkLookup ($query_string, $keynames = false) inherited
This method fetches a bunch of rows from the database. It has some funny mechanics, which you can usually just ignore.
Parameters
string $query_string
array $keynames
this will trigger the funny mechanics which sort the results into a hierarchic structure
Returns
array of rows (as objects)
References $i.
Referenced by PollsModel\AddVote(), PollsModel\CancelVote(), Member\count_comments(), Blog\countComments(), LinkModel\dbFriends(), LinkModel\dbFriendsID(), LinkModel\dbLinks(), MembersModel\editPreferences(), MessagesModel\filteredMailbox(), Member\get_address(), Member\get_comments(), Member\get_comments_commenter(), Member\get_comments_written(), Member\get_trads(), GeoModel\getAllGeonameIds(), RssModel\getBlogFeed(), RssModel\getBlogFeedByAuthor(), RssModel\getBlogFeedByTag(), SqltestModel\getBWMembers(), Blog\getCategoryArray(), LinkModel\getChanges(), LinkModel\getComments(), DatabaseSummaryModel\getDatabaseFieldsSorted(), DatabaseSummaryModel\getDatabaseTablesSorted(), CommunityModel\getFaqsCategorized(), AboutModel\getFaqsCategorized(), FeedbackModel\getFeedbackCategories(), RssModel\getForumFeed(), LastcommentsModel\GetLastComments(), LinkModel\getLinkPreferences(), LinkModel\getMemberdata(), Member\getNoteCategories(), NotifyModel\getNotes(), PollsModel\GetPollResults(), Blog\getRecentPostsArray(), LinkModel\getSpecialRelation(), RssModel\getTagFeed(), SqltestModel\getTBUsers(), RssModel\getThreadFeed(), Trip\getTripsForLocation(), Trip\getTripsForUser(), NewsletterModel\Load(), PollsModel\LoadPoll(), VerifyMembersModel\LoadVerified(), VerifyMembersModel\LoadVerifiers(), PollsModel\PrepareContribute(), NewsletterModel\PreviousLetters(), LinkModel\rebuildMissingLinks(), Member\set_profile_languages(), and GeoModel\updateGeoCounters().
RoxModelBase::bulkLookup_assoc ($query_string) inherited
This is the same as the above bulkLookup, but the rows are associative arrays instead of objects.
Parameters
unknown_type $query_string
Returns
array of rows (as associative arrays)
Forums::checkGroupMembership ($group_id)
References $group_id.
Forums::countReportList ($IdMember, $StatusList)
This function count the list of links to reports : if to 0 it means for all moderators, if not 0 it mean for a given moderator : is the list of reports status to consider, if empty it means all status returns and integer
RoxModelBase::createEntity () protected inherited
calls the entity factory to create an entity, passes along any arguments
Parameters
string - first parameter must be the name of the entity to create
Returns
object protected
Referenced by GeoUse\__construct(), GroupsModel\acceptGroupMember(), MembersModel\addComment(), Role\addForMember(), GroupsModel\addGroupMemberAsAdmin(), MembersModel\addRelation(), GroupsModel\banGroupMember(), PrivilegeScope\checkForEquivalentScope(), VerifyMembersModel\checkPassword(), PrivilegeScope\checkScopeExists(), MembersModel\confirmRelation(), Role\containsPrivilege(), GroupsModel\countGroupsBySearchterms(), AdminModel\countMembersWithStatus(), GroupsModel\countMyGroups(), Group\createGroup(), GroupsModel\createGroup(), NotifyModel\createNote(), NotifyModel\deleteNotes(), RelatedGroup\deleteRelatedGroup(), MembersModel\deleteRelation(), GroupsModel\findAllGroups(), NotifyModel\findAllNotes(), GroupsModel\findGroup(), RelatedGroupsModel\findGroup(), GroupsModel\findGroups(), GroupsModel\findMembersByName(), NotifyModel\findNote(), NotifyModel\findNotes(), Member\forums_posts_count(), Member\get_address(), MembersModel\get_profile_language(), Geo\getAllAlternateNames(), Geo\getAllParents(), Member\getAllPostVotes(), RightsModel\getAllRoles(), Member\getAllThreadVotes(), Geo\getAlternateName(), AdminModel\getBadComments(), Trip\getBlogGeo(), Blog\getBlogPost(), AdminModel\getBoard(), LoginModel\getBWMemberByUsername(), Geo\getChildren(), Address\getCity(), BlogEntity\getComingPosts(), Member\getComingPosts(), MembersModel\getComment(), GeoModel\getContinents(), Geo\getCountry(), Group\getEmailAcceptingMembers(), Role\getEquivalentPrivilege(), Member\getFirstAddress(), Comment\getFromMember(), Feedback\getFromMember(), GalleryModel\getGalleriesNotEmptyEntities(), BlogEntity\getGeo(), GetGroupEntity(), GroupMembership\getGroupMembers(), Member\getGroupMembership(), Group\getGroupOwners(), Member\getGroups(), RelatedGroupsModel\getGroupsForMember(), GroupsModel\getGroupsForMember(), Group\getLastLoggedInMembers(), GeoModel\getLocationById(), RoxModelBase\getLoggedInMember(), AdminModel\getMassmailRecipientsInfo(), InviteModel\getMember(), ApiModel\getMember(), Address\getMemberAddress(), Blog\getMemberByUsername(), Group\getMemberCount(), ApiModel\getMemberData(), MembersModel\getMemberFromEmail(), GroupMembership\getMemberGroups(), MemberRole\getMemberRoles(), Group\getMembers(), MembersModel\getMemberWithId(), GalleryModel\getMemberWithUserId(), MembersModel\getMemberWithUsername(), Group\getNewMembers(), ProfileNote\getNote(), Member\getNote(), ProfileNote\getNotes(), Member\getNotes(), Geo\getParent(), GetPostVote(), RolePrivilege\getPrivilege(), PrivilegeScope\getPrivilege(), RolePrivilege\getPrivilegeRoles(), Role\getPrivileges(), RelatedGroup\getRelatedGroupsLog(), RolePrivilege\getRole(), MemberRole\getRoleMembers(), RolePrivilege\getRolePrivileges(), Member\getRoles(), Role\getScopesForMemberRole(), Member\getSignupFeedback(), Comment\getToMember(), Geo\getTotalUsage(), Geo\getUsageForAllTypes(), Member\getVisitorCount(), Member\getVisitorsSubset(), Thread\getVoteResult(), Post\getVoteResult(), Thread\getVotes(), Post\getVotes(), Member\hasPrivilege(), Member\hasRole(), GroupsModel\inviteMember(), Group\isGroupOwner(), Group\isMember(), AboutModel\isVolunteer(), GroupsModel\joinGroup(), GroupsModel\leaveGroup(), VerifyMembersModel\LoadApprovedVerifiers(), RoxEntityBase\loadEntities(), GeoModel\loadLocation(), GroupsModel\memberAcceptedInvitation(), RelatedGroupsModel\memberAddsRelatedGroup(), GroupsModel\memberDeclinedInvitation(), RelatedGroupsModel\memberDeletesRelatedGroup(), MemberRole\memberHasRole(), Group\memberJoin(), Group\memberLeave(), GroupsModel\notifyGroupAdmins(), prepare_notification(), AdminModel\processMembers(), GroupsModel\realImg(), Member\recordVisit(), Role\removeFromMember(), Group\removeGroupOwner(), Member\removeLanguages(), GroupsModel\resignGroupAdmin(), RoxModelBase\restoreLoggedInMember(), searchUserposts(), MembersModel\sendCommentNotification(), FeedbackModel\sendFeedback(), GroupsModel\sendInvitation(), InviteModel\sendOrComplain(), Group\setGroupOwner(), MembersModel\setLocation(), MembersModel\setSessionLanguage(), MembersModel\showAvatar(), RelatedGroupsModel\showRelatedGroupsLog(), GroupsModel\thumbImg(), AdminModel\treasurerEditCreateDonationVarsOk(), GroupsModel\updateMembershipSettings(), MembersModel\updateProfile(), MembersModel\updateRelation(), and AdminModel\updateVolunteerBoard().
Forums::createProcess ()
References $User, $vars, and APP_User\login().
Forums::DeleteVoteForPost ($IdPost)
this function allows to vote for the given IdPost with teh value $Value
References $_SESSION, MOD_log\get(), and RoxModelBase\singleLookup().
Forums::delProcess ()
References $query, $User, MOD_log\get(), APP_User\login(), and prepare_notification().
Forums::DofTradUpdate ($IdForumTrads, $P_Sentence, $P_IdLanguage = 0)
the function DofTradUpdate() update a forum translation is the primary key of the parameter to update
References $_SESSION, $id, MOD_log\get(), and words.
Referenced by ModeratorEditPostProcess(), and ModeratorEditTagProcess().
Forums::editProcess ()
References $_SESSION, $query, $User, $vars, and APP_User\login().
Forums::FindAppropriatedLanguage ($IdPost = 0)
FindAppropriatedLanguage function will retrieve the appropriated default language for a member who want to reply to a thread (started with the# post) this retriewal is made according to the language of the post, the current language of the user
References $_SESSION, and $query.
RoxComponentBase::get ($key) protected inherited
Referenced by SignupClosedPage\column_col3(), SignupProblemPage\column_col3(), and SignupPage\column_col3().
RoxModelBase::get_dao () protected inherited
normally the $dao should be injected. If it's not, this function creates a new one out of the blue..
Forums::getAdminCode ()
Forums::getAllAdmincodes ($country_code)
References $query.
Forums::getAllContinents ()
References $continents.
Forums::getAllCountries ($continent)
References $countries, and $query.
Forums::getAllLocations ($countrycode, $admincode)
References $locations, and $query.
Forums::getAllTags ()
References $query, and words.
Forums::getBoard ()
Forums::getContinent ()
Forums::getCountryCode ()
RoxModelBase::getDao () protected inherited
Forums::getEditData ($callbackId)
References $callbackId, $query, $vars, geonameid, and words.
Forums::getGeonameid ()
Forums::GetGroupEntity ($IdGroup)
References RoxModelBase\createEntity().
Forums::getGroupName ($Name)
Referenced by GroupChoice(), and ModeratorGroupChoice().
Forums::getIdContent ()
References $query.
Forums::getIdGroup ()
Forums::GetIdThread ($IdPost)
this function returns the Id of the thread corresponding to a certain $IdPost
References RoxModelBase\singleLookup().
Forums::GetLanguageChoosen ()
GetLanguageChoosen function
This return the language choosen by the user this function is supposed to be called after a new post, and editpost or a reply it return the language choosen if any
References $_SESSION.
Forums::GetLanguageName ($IdLanguage)
References $query, and RoxComponentBase\getWords().
Referenced by LanguageChoices().
RoxComponentBase::getLog () protected inherited
wrapper function for MOD_log::get()
protected
Returns
object
References MOD_log\get().
Referenced by RoxComponentBase\logWrite().
RoxModelBase::getLoggedInMember () inherited
returns the currently logged in member
public
Returns
object|false
References $_SESSION, and RoxModelBase\createEntity().
Referenced by AdminTreasurerPage\__construct(), AdminTreasurerEditCreateDonationPage\__construct(), AdminTreasurerStartDonationCampaignPage\__construct(), Suggestion\addOption(), adjustThreadsCountToShow(), GroupsModel\canAccessGroupAdmin(), GroupsModel\canAccessGroupDelete(), ActivitiesModel\checkEditCreateActivityVarsOk(), Blog\commentProcess(), Blog\countRecentPosts(), GalleryModel\createGallery(), GroupsModel\createGroup(), AdminModel\createMassmail(), SuggestionsModel\createSuggestion(), MembersModel\deleteNoteForMember(), Suggestion\deleteOption(), Suggestion\editOption(), SuggestionsModel\editSuggestion(), RightsModel\getAllRoles(), SearchModel\getDefaultAdvancedOptions(), Group\getGroupOwners(), ActivitiesModel\getMyActivities(), ActivitiesModel\getMyActivitiesCount(), ActivitiesModel\getNearMeQuery(), GetPostVote(), Blog\getRecentPostIt(), Blog\getRecentPostsArray(), Blog\getStickyPostIt(), Blog\getTaggedPostsIt(), Blog\getTagsIt(), Blog\getTinyMCEPreference(), getTinyMCEPreference(), Trip\getTripData(), Trip\getTrips(), RightsModel\hasRightsAccess(), ActivitiesModel\joinLeaveActivity(), Suggestion\loadEntity(), SuggestionOption\loadEntity(), LoginModel\logout(), GroupsModel\memberAcceptedInvitation(), GroupsModel\memberDeclinedInvitation(), Trip\prepareEditData(), GroupsModel\resignGroupAdmin(), FeedbackModel\sendFeedback(), MembersModel\setCommentGuidelinesRead(), LoginModel\setPreferredLanguage(), ActivitiesModel\setRadius(), switchShowMyGroupsTopicsOnly(), Suggestion\update(), ActivitiesModel\updateActivity(), AdminModel\updateMassmail(), AdminModel\updateVolunteerBoard(), GalleryModel\uploadProcess(), and MembersModel\writeNoteForMember().
RoxModelBase::getMemoryCookie () protected inherited
Reads the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
References $_SESSION, elseif, and RoxModelBase\setMemoryCookie().
Referenced by RoxModelBase\restoreLoggedInMember().
Forums::getMessageId ()
Forums::getPage ()
Referenced by prepareTopic().
Forums::getPageArray ()
Forums::GetPostVisibility ($IdPost)
References $query.
Forums::GetPostVote ($IdPost)
this function returns a structure with the result of a vote for a given IdPost according to the current logged member
References $_SESSION, $member, RoxModelBase\createEntity(), and RoxModelBase\getLoggedInMember().
Referenced by prepareTopic().
Forums::GetReports ($IdPost, $IdReporter = 0)
This will return the list of reports for a given post : Id of the post to process with their status : OPtional id of teh member for a specific report, in this case a record is returned7 in other case an array of reports is returned
References $IdReporter.
Forums::getTags ()
Forums::getTagsMaximum ()
References $counter, $maximum, $query, max, and words.
Forums::getTagsNamed ()
References $query, and words.
Forums::getThreadId ()
Forums::GetThreadVisibility ($IdThread)
Forums::getTinyMCEPreference ()
References $member, and RoxModelBase\getLoggedInMember().
Forums::getTopCategoryLevelTags ()
References $query.
Forums::getTopic ()
Forums::getTopMode ()
RoxComponentBase::getValues () protected inherited
RoxComponentBase::getVersionInfo () protected inherited
returns the revision number saved in revision.txt
protected
Returns
string
References $version.
Referenced by FeedbackModel\sendFeedback().
RoxComponentBase::getWords () protected inherited
returns an instance of the MOD_words class
protected
Returns
object
Referenced by VisualComponent\__call(), GroupsController\acceptInvitation(), GroupsController\addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), GeoPopupPage\body(), GalleryDeletePage\breadcrumbs(), GalleryBasePage\breadcrumbs(), SuggestionsController\changeStateCallback(), MyVisitorsPage\column_col3(), GalleryFlickrPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryAllImagesPage\column_col3(), HellouniversePage\column_col3(), GeoAdminPage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), LinkUpdatePage\column_col3(), GalleryDeletePage\column_col3(), NewsletterPage\column_col3(), FeedbackSentPage\column_col3(), VerifyMembersNotActivePage\column_col3(), VerifyMyselfPage\column_col3(), OneNewsLetterPage\column_col3(), GalleryManagePage\column_col3(), GalleryAllGalleriesPage\column_col3(), VerifiedApprovedVerifiers\column_col3(), ActivitiesFindPage\column_col3(), GroupStartPage\column_col3(), GroupDeletePage\column_col3(), GroupJoinPage\column_col3(), GroupMemberSettingsPage\column_col3(), AboutFaqPage\column_col3(), GroupWikiPage\column_col3(), GroupAddRelatedGroupPage\column_col3(), GroupDeleteRelatedGroupPage\column_col3(), GroupLeavePage\column_col3(), GroupForumPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), AboutFaqsectionPage\column_col3(), PollsPage\column_col3(), VerifiedMembersViewPage\column_col3(), HellouniverseTabbedPage\column_col3(), GroupForumsOverviewPage\column_col3(), GroupsController\declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), Member\get_all_relations(), MembersModel\get_relation_between_members(), Member\get_trad_by_tradid(), Group\getDescription(), FullPagePager\getHtml(), Note\getIdRelMember(), GetLanguageName(), LastCommentsPage\getLastCommentsTitle(), PageWithRoxLayout\getPage_meta_description(), PageWithRoxLayout\getPage_meta_keyword(), UpdateMandatoryPage\getPageTitle(), AboutTheideaPage\getPageTitle(), ActivitiesBasePage\getPageTitle(), CityPage\getPageTitle(), CountriesPage\getPageTitle(), CountryPage\getPageTitle(), RegionPage\getPageTitle(), SafetyBasePage\getPageTitle(), SearchMembersBasePage\getPageTitle(), SuggestionsBasePage\getPageTitle(), NewsletterPage\getPageTitle(), OneNewsLetterPage\getPageTitle(), GroupsBasePage\getPageTitle(), VerifiedMembersViewPage\getPageTitle(), PollsPage\getPageTitle(), SuggestionsBasePage\getStateSelect(), DebugPage\getSubmenuItems(), GalleryUserPage\getSubmenuItems(), AboutBasePage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), PageWithHTML\head(), MembersController\index_loggedIn(), GroupsController\joined(), GroupsController\kickMember(), LanguageChoices(), GroupsController\leave(), GroupsController\left(), PageWithRoxLayout\leftoverTranslationLinks(), AboutFaqsectionPage\leftSidebar(), AboutFaqPage\leftSidebar(), InactiveProfilePage\leftsidebar(), AdminMassMailEnqueuePage\leftSidebar(), VerifyMembersPage\leftSidebar(), AdminMassMailDetailsPage\leftSidebar(), AdminMassMailEditCreatePage\leftSidebar(), VerifiedApprovedVerifiers\leftSidebar(), VerifiedMembersViewPage\leftSidebar(), PollsPage\leftSidebar(), MemberPage\leftsidebar(), LoginController\loginCallback(), GalleryController\manage(), MessagesPageWithMailbox\messageActions(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), NotifyAdminPage\notesActions(), GroupsModel\notifyGroupAdmins(), PageWithRoxLayout\quicksearch(), GroupsController\resignAsAdmin(), SuggestionsController\restoreOption(), GeoController\SelectorInclude(), GroupsModel\sendInvitation(), Group\setDescription(), PageWithRoxLayout\SetMetaKey(), AbstractBasePage\showTemplate(), PageWithRoxLayout\submenu(), MessagesBasePage\teaserContent(), GroupSettingsPage\teaserContent(), GroupsSearchPage\teaserContent(), GroupsMyGroupsPage\teaserContent(), GroupsCreationPage\teaserContent(), GroupInvitePage\teaserContent(), TourPage\teaserContent(), GroupsFeaturedPage\teaserContent(), GroupsOverviewPage\teaserContent(), LastCommentsPage\teaserContent(), GroupForumsOverviewPage\teaserContent(), GroupsBasePage\teaserContent(), ResetPasswordPage\teaserHeadline(), ResetPasswordFinishPage\teaserHeadline(), VerifyNoMemberSpecifiedPage\teaserHeadline(), AboutBasePage\teaserHeadline(), GalleryImageNotFoundPage\teaserHeadline(), GalleryAvatarsPage\teaserHeadline(), AboutStatisticsPage\teaserHeadline(), VerifyMyselfPage\teaserHeadline(), VerifyMembersNotActivePage\teaserHeadline(), VerifyMembersPage\teaserHeadline(), GalleryBasePage\teaserHeadline(), SearchMembersBasePage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), SuggestionsBasePage\teaserHeadline(), OneNewsLetterPage\teaserHeadline(), VerifiedMembersViewPage\teaserHeadline(), PollsPage\teaserHeadline(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), GroupMembership\updateMembership(), GalleryController\upload(), GalleryController\uploadedProcess(), GalleryController\user(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
Forums::GroupChoice ()
References $query, and getGroupName().
Forums::initLastPosts ()
References $query, and NUMBER_LAST_POSTS_PREVIEW.
Forums::InsertInFTrad ($ss, $TableColumn, $IdRecord, $_IdMember = 0, $_IdLanguage = -1, $IdTrad = -1)
InsertInfTrad function
This InsertInFTrad create a new translatable text in forum_trads $ss is for the content of the text $TableColumn refers to the table and coilumn the trad is associated to $IdRecord is the num of the record in this table $_IdMember ; is the id of the member who own the record $_IdLanguage $IdTrad is probably useless (I don't remmber why I defined it)
Warning : as default language this function will use by priority : 1) the content of $_IdLanguage if it is set to something else than -1 2) the content of an optional $_POST[IdLanguage] if it is set 3) the content of the current $_SESSION['IdLanguage'] of the current membr if it set 4) The default language (0)
returns the id of the created trad
References words.
Referenced by ModeratorEditPostProcess().
Forums::IsGroupSubscribed ($IdGroup = 0, $ParamIdMember = 0)
Forums::isMembersForumPostsPagePublic ($userId = 0)
Forums::IsTagSubscribed ($IdTag = 0, $ParamIdMember = 0)
Referenced by SubscribeTag().
Forums::IsThreadSubscribed ($IdThread = 0, $ParamIdMember = 0)
Referenced by SubscribeThread().
Forums::isTopic ()
Check if it's a topic or a forum
Returns
bool true on topic
bool false on forum
Forums::LanguageChoices ($DefIdLanguage = -1)
References $_SESSION, $ii, $query, GetLanguageName(), and RoxComponentBase\getWords().
RoxComponentBase::logWrite ($string, $type = 'Log') protected inherited
wrapper for calls to MOD_log::get->write()
Parameters
string $string
string $type protected
References $type, and RoxComponentBase\getLog().
Referenced by GroupsController\acceptInvitation(), GroupsController\acceptMember(), MembersModel\addComment(), GroupsController\addMemberAsAdmin(), MembersModel\addRelation(), GroupsController\banMember(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), GroupsController\createGroupCallback(), GroupsController\declineInvitation(), GroupsController\delete(), MembersModel\delete_translation_multiple(), FeedbackModel\feedbackMail(), MembersController\index_loggedIn(), GroupsController\inviteMember(), GroupsController\inviteMemberAjax(), GroupsController\joined(), GroupsController\kickMember(), GroupsController\left(), Geo\placeType(), AdminModel\processMembers(), GroupsController\resignAsAdmin(), MembersModel\set_preference(), MembersModel\set_public_profile(), MembersModel\setLocation(), MembersModel\updateProfile(), and MembersModel\updateRelation().
Forums::ModeratorEditPostProcess ()
References $_SESSION, $User, $vars, DofTradUpdate(), MOD_log\get(), InsertInFTrad(), and APP_User\login().
Forums::ModeratorEditTagProcess ()
References $_SESSION, $User, $vars, DofTradUpdate(), elseif, MOD_log\get(), APP_User\login(), and ReplaceInFTrad().
Forums::ModeratorGroupChoice ()
References $query, and getGroupName().
Referenced by prepareModeratorEditPost().
Forums::NotAllowedForGroup ($IdMember, $rPost)
Return true if the Member is not allowed to see the given post because of groups restrictions $IdMember : Id of the member $rPost data about the post (Thread and Post visibility, id of the group and delettion status) return true or false !! Becareful, in case the member has moderator right, his moderator rights will not be considerated
References $query.
Forums::prepare_notification ($postId, $type)
Handle forum notifications (public to be able to call it from suggestions)
References $count, $member, $members, $query, $res, $type, and RoxModelBase\createEntity().
Referenced by delProcess().
Forums::prepareForum ($showsticky = true)
Fetch all required data for the view to display a forum this data are stored in $this->board
References CV_TOPMODE_CATEGORY, CV_TOPMODE_FORUM, CV_TOPMODE_GROUPS, CV_TOPMODE_LANDING, CV_TOPMODE_LASTPOSTS, debug, elseif, and geonameid.
Forums::prepareModeratorEditPost ($IdPost)
This will prepare a post for a full edit moderator action : Id of the post to process
References $query, and ModeratorGroupChoice().
Forums::prepareModeratorEditTag ($IdTag)
This will prepare a post for a moderator action : Id of the post to process
References $query.
Forums::prepareReportList ($IdMember, $StatusList)
This function loads the list of links to reports : if to 0 it means for all moderators, if not 0 it mean for a given moderator : is the list of reports status to consider, if empty it means all status
returns an array
Forums::prepareReportPost ($IdPost, $IdWriter)
This will prepare the additional data to process a report : Id of the post to process is the id of the writer
References $query.
Forums::prepareTopic ($WithDetail = false)
function prepareTopic prepares the detail of a topic for display according to threadid if $WithDetail is set to true, additional details (available languages and original author are displayed)
References $_SESSION, $query, false, getPage(), and GetPostVote().
Forums::pushToPageArray ($page)
RoxComponentBase::refresh_get ($key) inherited
Forums::ReplaceInFTrad ($ss, $TableColumn, $IdRecord, $IdTrad = 0, $IdOwner = 0)
ReplaceInFTrad function
This ReplaceInFTrad replace or create translatable text in forum_trads $ss is for the content of the text $TableColumn refers to the table and column the trad is associated to $IdRecord is the num of the record in this table $IdTrad is the record in forum_trads to replace (unique for each IdLanguage) $Owner ; is the id of the member who own the record
Warning : as default language this function will use by priority : 1) the content of $_IdLanguage if it is set to something else than -1 2) the content of an optional $_POST[IdLanguage] if it is set 3) the content of the current $_SESSION['IdLanguage'] of the current membr if it set 4) The default language (0)
References words.
Referenced by ModeratorEditTagProcess().
Forums::replyProcess ($suggestion = false)
References $User, $vars, APP_User\login(), and setThreadId().
Forums::reportpostProcess ()
References $_SESSION, $IdReporter, $Status, $Type, $User, $vars, MOD_log\get(), and APP_User\login().
RoxModelBase::restoreLoggedInMember () inherited
Restore session if memory cookie exists
References RoxModelBase\createEntity(), and RoxModelBase\getMemoryCookie().
Forums::searchSubscriptions ($cid = 0, $IdThread = 0, $IdTag = 0)
This function retrieve the subscriptions for the member $cid and/or the the thread IdThread and/or theIdTag $cid : either the IdMember or the username of the member we are searching the subscription this $cid and $IdThread and $IdTag parameters are only used if the current member has moderator rights It returns a $TResults structure Very important : member who are not moderators cannot see other people subscriptions
References $_SESSION, and $query.
Forums::searchUserposts ($cid = 0)
References $member, $query, and RoxModelBase\createEntity().
Forums::setAdminCode ($admincode)
Forums::setContinent ($continent)
Forums::setCountryCode ($countrycode)
Forums::setGeonameid ($geonameid)
References geonameid.
Forums::setGroupId ($IdGroup)
RoxModelBase::setMemoryCookie ($id, $seriesToken = '', $authToken = '') protected inherited
Sets the contents of the memory cookie (for "stay logged in")
Returns
array/boolean Contents of cookie or FALSE
References $id.
Referenced by RoxModelBase\getMemoryCookie().
Forums::setMessageId ($messageid)
Forums::setPage ($page)
Forums::setPageArray ($page_array)
Forums::setThreadId ($threadid)
Referenced by replyProcess().
Forums::setTopMode ($Mode)
Referenced by __construct().
RoxModelBase::singleLookup ($query_string) inherited
Referenced by PollsModel\AddChoice(), GeoModel\addHierarchy(), VerifyMembersModel\AddNewVerified(), MembersModel\addRelation(), PollsModel\AddVote(), PollsModel\CancelVote(), PollsModel\CanUserContribute(), MessagesModel\CaptchaNeeded(), VerifyMembersModel\CheckAndGetUsername(), LoginModel\checkBWPassword(), MembersModel\confirmRelation(), Member\count_mynotes(), LoginModel\createMissingTBUser(), MessagesModel\deleteMessage(), MembersModel\deleteRelation(), DeleteVoteForPost(), LoginModel\encryptPasswordBW(), LanguageLookupModel\findLanguageWithCode(), Member\get_publicProfile(), Member\get_userid(), Member\get_verification_status(), DonateModel\getCampaignValues(), LinkModel\getChanges(), AdminModel\getCountryCodeForGeonameId(), GeoModel\getDataById(), AdminModel\getDonation(), AdminModel\getDonationCampaignStatus(), FeedbackModel\getFeedbackCategory(), AdminModel\getGeonameIdForCountryCode(), GetIdThread(), RoxFrontRouterModel\getLanguage(), MessagesModel\getMember(), LinkModel\getMemberdata(), MembersModel\getMemberFromEmail(), LinkModel\getMemberID(), GalleryModel\getMemberWithUserId(), MessagesModel\getMessage(), PollsModel\GetPollResults(), RoxFrontRouterModel\getPossibleUrlLanguage(), SearchModel\getResultsForLocation(), LoginModel\getTBUserForBWMember(), GeoModel\getUsagetypeId(), Places\getWikiPage(), PollsModel\HasAlreadyContributed(), MessagesModel\hasMessageLimitExceeded(), PollsModel\IsMemberAllowed(), CommunityModel\isVolunteer(), NewsletterModel\Load(), VerifyMembersModel\LoadApprovedVerifiers(), PollsModel\LoadList(), PollsModel\LoadPoll(), PollsModel\PrepareContribute(), MessagesModel\sendOrComplain(), MembersModel\set_preference(), MembersModel\set_profile_language(), MembersModel\set_public_profile(), LoginModel\setBWMemberAsLoggedIn(), MembersModel\setLocation(), LoginModel\setupBWSession(), SearchModel\suggestLocationsFromDatabase(), PollsModel\UpdateChoice(), GeoModel\updateGeonameId(), PollsModel\UpdatePoll(), MembersModel\updateRelation(), MessagesModel\updateSpamInfo(), GeoModel\updateUsageCounter(), and VoteForPost().
RoxModelBase::singleLookup_assoc ($query_string) inherited
Referenced by Member\getProfilePictureID().
Forums::SubscribeTag ($IdTag, $ParamIdMember = 0)
This function allow to subscribe to a Tag
$IdTag : The Tag we want the user to subscribe to $ParamIdMember optional IdMember, by default set to 0 in this case current logged member will be used It also check that member is not yet subscribing to Tag
References $_SESSION, $query, MOD_log\get(), and IsTagSubscribed().
Forums::SubscribeThread ($IdThread, $ParamIdMember = 0)
This function allow to subscribe to a thread
$IdThread : The thread we want the user to subscribe to $ParamIdMember optional IdMember, by default set to 0 in this case current logged member will be used It also check that member is not yet subscribing to thread
References $_SESSION, $query, MOD_log\get(), and IsThreadSubscribed().
Forums::suggestTags ($search)
References $_SESSION, $i, $query, and $search.
Forums::switchForumOrderList ()
References $_SESSION, and MOD_log\get().
Forums::switchShowMyGroupsTopicsOnly ()
References $_SESSION, $member, $preference, $query, and RoxModelBase\getLoggedInMember().
Forums::UnsubscribeTag ($IdSubscribe = 0, $Key = "")
This function remove the subscription marked by IdSubscribe is the primary key of the members_tags_subscribed area to remove is the key to check to be sure it is not an abuse of url It returns a $res=1 if ok
References $_SESSION, $query, and MOD_log\get().
Forums::UnsubscribeTagDirect ($IdTag = 0, $ParamIdMember = 0)
This function remove the subscription without checking the key
Parameters
unknown_type $IdTag the id of the Tag to unsubscribe to
unknown_type $ParamIdMember the member to unsubscribe, if 0, the current member will eb used
Returns
unknown
References $_SESSION, $query, and MOD_log\get().
Forums::UnsubscribeThread ($IdSubscribe = 0, $Key = "")
This function remove the subscription marked by IdSubscribe is the primary key of the members_threads_subscribed area to remove is the key to check to be sure it is not an abuse of url It returns a $res=1 if ok
References $_SESSION, $query, and MOD_log\get().
Forums::UnsubscribeThreadDirect ($IdThread = 0, $ParamIdMember = 0)
This function remove the subscription without checking the key
Parameters
unknown_type $IdThread the id of the thread to unsubscribe to
unknown_type $ParamIdMember the member to unsubscribe, if 0, the current member will eb used
Returns
unknown
References $_SESSION, $query, and MOD_log\get().
Forums::VoteForPost ($IdPost, $Value)
this function allows to vote for the given IdPost with teh value $Value
References $_SESSION, MOD_log\get(), and RoxModelBase\singleLookup().
Field Documentation
RoxModelBase::$_entity_factory protected inherited
Forums::$BW_Right
Forums::$continents static
Initial value:
= array(
        'AF' => 'Africa',
        'AN' => 'Antarctica',
        'AS' => 'Asia',
        'EU' => 'Europe',
        'NA' => 'North America',
        'SA' => 'South Amercia',
        'OC' => 'Oceania'
    )
Forums::$ForumOrderList
Forums::$POSTS_PER_PAGE
Forums::$THREADS_PER_PAGE
Forums::$words
const Forums::CV_POSTS_PER_PAGE = 200
Referenced by __construct(), and Board\__construct().
const Forums::CV_THREADS_PER_PAGE = 15
Referenced by __construct(), and Board\__construct().
const Forums::CV_TOPMODE_CATEGORY =1
Referenced by __construct(), and prepareForum().
const Forums::CV_TOPMODE_FORUM =4
Referenced by __construct(), prepareForum(), and ForumsController\showExternalLatest().
const Forums::CV_TOPMODE_GROUPS =5
Referenced by prepareForum().
const Forums::CV_TOPMODE_LANDING =3
Referenced by __construct(), ForumsController\index(), and prepareForum().
const Forums::CV_TOPMODE_LASTPOSTS =2
Referenced by prepareForum().
const Forums::NUMBER_LAST_POSTS_PREVIEW = 5
Referenced by initLastPosts().
The documentation for this class was generated from the following file:
forums.model.php