Rox: AdminModel Class Reference
AdminModel Class Reference
Public Member Functions
getMembersWithStatus ($status, $pager)
countMembersWithStatus ($status)
getStatusOverview ()
processMembers (array $post)
getAccepterBoard ()
getBoard ($name)
updateVolunteerBoard ($boardname, $text)
getBadComments ()
procActivitylogs ($vars, $level=0)
getMassMailings ($specific=false, $general=false)
getMassmail ($id)
getMassmailRecipientsInfo ($id, $type, $start, $limit)
getMassmailRecipientsCount ($id, $type)
createMassmail ($name, $type, $subject, $body, $description)
updateMassmail ($id, $name, $type, $subject, $body)
massmailEditCreateVarsOk (&$vars)
getAdminUnits ($countrycode)
getPlaces ($countrycode, $adminunit)
getEnqueueAction ($vars)
massmailEnqueueVarsOk (&$vars)
enqueueMassmail ($vars)
unqueueMassMail ($id)
untriggerMassMail ($id)
triggerMassMail ($id)
getSuggestionsReminderCount ()
treasurerEditCreateDonationVarsOk (&$vars)
getGeonameIdForCountryCode ($countrycode)
getCountryCodeForGeonameId ($geonameid)
createDonation ($memberid, $donatedon, $amount, $comment, $countryid)
updateDonation ($id, $memberid, $donatedon, $amount, $comment, $countryid)
getRecentDonations ()
getStatForDonations ()
getDonationCampaignValues ()
getDonation ($id)
getDonationCampaignStatus ()
treasurerStartDonationCampaignVarsOk (&$vars)
startDonationCampaign ($vars)
stopDonationCampaign ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 36 of file admin.model.php.
Member Function Documentation
AdminModel::countMembersWithStatus ($status)
counts members with a given status
Parameters
stsring $status public
Returns
int
Definition at line 60 of file admin.model.php.
References RoxModelBase\createEntity().
AdminModel::createDonation ($memberid, $donatedon, $amount, $comment, $countryid)
Definition at line 1149 of file admin.model.php.
References $comment, and $query.
AdminModel::createMassmail ($name, $type, $subject, $body, $description)
Definition at line 580 of file admin.model.php.
References $_SESSION, $body, $description, $name, $query, $subject, $type, and RoxModelBase\getLoggedInMember().
AdminModel::enqueueMassmail ($vars)
Definition at line 967 of file admin.model.php.
References $action, $count, $countrycode, $id, $vars, and getEnqueueAction().
AdminModel::getAccepterBoard ()
returns the text glob object for accepters
public
Returns
VolunteerBoard
Definition at line 233 of file admin.model.php.
References getBoard().
AdminModel::getAdminUnits ($countrycode)
Definition at line 699 of file admin.model.php.
References $countrycode, and $query.
AdminModel::getBadComments ()
returns all comments marked bad
public
Returns
array
Definition at line 278 of file admin.model.php.
References RoxModelBase\createEntity().
AdminModel::getBoard ($name)
returns a board given it's name
Parameters
string $name public
Returns
VolunteerBoard
Definition at line 246 of file admin.model.php.
References $name, and RoxModelBase\createEntity().
Referenced by getAccepterBoard().
AdminModel::getCountryCodeForGeonameId ($geonameid)
Definition at line 1134 of file admin.model.php.
References $query, and RoxModelBase\singleLookup().
AdminModel::getDonation ($id)
Definition at line 1215 of file admin.model.php.
References $id, $query, and RoxModelBase\singleLookup().
AdminModel::getDonationCampaignStatus ()
Definition at line 1226 of file admin.model.php.
References $query, and RoxModelBase\singleLookup().
Referenced by AdminTreasurerPage\__construct().
AdminModel::getDonationCampaignValues ()
Definition at line 1210 of file admin.model.php.
AdminModel::getEnqueueAction ($vars)
Definition at line 729 of file admin.model.php.
References $action, $vars, and elseif.
Referenced by enqueueMassmail(), and massmailEnqueueVarsOk().
AdminModel::getGeonameIdForCountryCode ($countrycode)
Definition at line 1118 of file admin.model.php.
References $countrycode, $query, and RoxModelBase\singleLookup().
AdminModel::getMassmail ($id)
Definition at line 442 of file admin.model.php.
References $count, $id, $query, and $status.
AdminModel::getMassMailings ($specific = false, $general = false)
returns the broadcast messages in the database including information about the current state (number of enqueued, triggered and sent messages)
Returns
array of broadcast messages
Definition at line 372 of file admin.model.php.
References $query.
AdminModel::getMassmailRecipientsCount ($id, $type)
Definition at line 557 of file admin.model.php.
References $id, $query, $status, and $type.
AdminModel::getMassmailRecipientsInfo ($id, $type, $start, $limit)
Definition at line 504 of file admin.model.php.
References $id, $languages, $m, $query, $status, $type, and RoxModelBase\createEntity().
AdminModel::getMembersWithStatus ($status, $pager)
gets an array of members with a given status
Parameters
stsring $status public
Returns
array
Definition at line 47 of file admin.model.php.
References $pager.
AdminModel::getPlaces ($countrycode, $adminunit)
Definition at line 713 of file admin.model.php.
References $countrycode, and $query.
AdminModel::getRecentDonations ()
Definition at line 1200 of file admin.model.php.
Referenced by AdminTreasurerPage\__construct().
AdminModel::getStatForDonations ()
Definition at line 1205 of file admin.model.php.
Referenced by AdminTreasurerPage\__construct().
AdminModel::getStatusOverview ()
Definition at line 65 of file admin.model.php.
References $query, and $results.
AdminModel::getSuggestionsReminderCount ()
Get the count of members to be invited randomly
Maximum number of votes ever casted for one suggestion times three
Definition at line 1053 of file admin.model.php.
References $query.
AdminModel::massmailEditCreateVarsOk (& $vars)
Definition at line 660 of file admin.model.php.
References $body, $description, $errors, $id, $name, $subject, $type, $vars, and $words.
AdminModel::massmailEnqueueVarsOk (& $vars)
Definition at line 747 of file admin.model.php.
References $action, $errors, $vars, and getEnqueueAction().
AdminModel::procActivitylogs ($vars, $level = 0)
Definition at line 284 of file admin.model.php.
References $_SESSION, $query, $R, $type, $username, $vars, and MOD_right\get().
AdminModel::processMembers (array $post)
updates member statuses according to a post array
Parameters
array $post public
Returns
array
Definition at line 87 of file admin.model.php.
References $action, $id, $member, RoxModelBase\createEntity(), and RoxComponentBase\logWrite().
AdminModel::startDonationCampaign ($vars)
Definition at line 1261 of file admin.model.php.
References $query, and $vars.
AdminModel::stopDonationCampaign ()
Definition at line 1279 of file admin.model.php.
References $query.
AdminModel::treasurerEditCreateDonationVarsOk (& $vars)
Definition at line 1079 of file admin.model.php.
References $errors, $vars, and RoxModelBase\createEntity().
AdminModel::treasurerStartDonationCampaignVarsOk (& $vars)
Definition at line 1239 of file admin.model.php.
References $errors, and $vars.
AdminModel::triggerMassMail ($id)
Definition at line 1035 of file admin.model.php.
References $id, and $query.
AdminModel::unqueueMassMail ($id)
Definition at line 1013 of file admin.model.php.
References $id, and $query.
AdminModel::untriggerMassMail ($id)
Definition at line 1024 of file admin.model.php.
References $id, and $query.
AdminModel::updateDonation ($id, $memberid, $donatedon, $amount, $comment, $countryid)
Definition at line 1175 of file admin.model.php.
References $comment, $id, and $query.
AdminModel::updateMassmail ($id, $name, $type, $subject, $body)
Definition at line 621 of file admin.model.php.
References $_SESSION, $body, $id, $name, $query, $subject, $type, and RoxModelBase\getLoggedInMember().
AdminModel::updateVolunteerBoard ($boardname, $text)
updates a given volunteer board
Parameters
string $boardname - name of board to update
string $text - text to update with
public
Returns
bool
Definition at line 260 of file admin.model.php.
References $text, RoxModelBase\createEntity(), and RoxModelBase\getLoggedInMember().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/admin.model.php