Rox: VolunteerbarModel Class Reference
VolunteerbarModel Class Reference
Public Member Functions
getNumberPersonsToBeAccepted ()
getNumberReportedComments ()
getNumberPersonsToBeChecked ($_AccepterScope="")
getNumberPersonsToAcceptInGroup ($_GroupScope="")
getNumberMessagesToBeChecked ()
getNumberSpamToBeChecked ()
Member Function Documentation
VolunteerbarModel::getNumberMessagesToBeChecked ()
Returns the number of messages, which should be checked.
References $query.
VolunteerbarModel::getNumberPersonsToAcceptInGroup ($_GroupScope = "")
Returns the number of people due to be checked to problems or what. The number depends on the scope of the person logged on.
$_GroupScope="" is an optional value for group Scope which can be used for performance if it was already fetched from database
Returns
integer indicating the number of people wiche need to be accepted in a Group if the current member has right to accept them
References $query, $R, and MOD_right\get().
VolunteerbarModel::getNumberPersonsToBeAccepted ()
Returns the number of people due to be accepted. The number depends on the scope of the person logged on.
Returns
integer Number of members with Pending status in user's scope
References $query, and MOD_right\get().
VolunteerbarModel::getNumberPersonsToBeChecked ($_AccepterScope = "")
Returns the number of people due to be checked to problems or what. The number depends on the scope of the person logged on.
$_AccepterScope="" is an optional value for accepter Scope which can be used for performance if it was already fetched from database
Returns
integer indicating the number of people in need to be checked
References $query, $R, and MOD_right\get().
VolunteerbarModel::getNumberReportedComments ()
Returns the number of reported comments due to be reviewed.
Returns
integer Number of comments that need to be reviewed
References $query, and MOD_right\get().
VolunteerbarModel::getNumberSpamToBeChecked ()
Returns the number of spam messages
References $layoutbits, $query, and MOD_layoutbits\get().
The documentation for this class was generated from the following file:
volunteerbar.model.php