Rox: MOD_log Class Reference
MOD_log Class Reference
Public Member Functions
writeIdMember ($IdMember, $message="", $type="Log")
write ($message="", $type="Log")
Static Public Member Functions
static get ()
Data Fields
const LOG2FILE = false
const LOG_FILE = '/tmp/bw.log'
Detailed Description
Writes and reads from the logs table. Replacement for old BW LogStr method.
Author
Felix van Hove, fvanh.nosp@m.ove@.nosp@m.gmx.d.nosp@m.e
Definition at line 29 of file log.lib.php.
Member Function Documentation
static MOD_log::get () static
singleton getter
Parameters
void
Returns
PApps
Definition at line 68 of file log.lib.php.
Referenced by PollsModel\AddChoice(), VerifyMembersModel\AddNewVerified(), PollsModel\AddVote(), PollsModel\CancelVote(), PollsModel\CanUserContribute(), LoginModel\checkBWPassword(), MOD_dnsblock\checkIp(), MessagesModel\deleteMessage(), Forums\DeleteVoteForPost(), Forums\delProcess(), MOD_bw_user_Auth\doBWLogin1(), Forums\DofTradUpdate(), LoginModel\encryptPasswordBW(), GeoModel\getGeonamesHierarchy(), RoxComponentBase\getLog(), RssController\index(), DonateController\index(), PollsController\index(), SignupController\index(), ForumsController\index(), MessagesModel\markReadMessage(), Forums\ModeratorEditPostProcess(), Forums\ModeratorEditTagProcess(), SignupView\registerMail(), SignupModel\registerProcess(), Forums\reportpostProcess(), DonateModel\returnFromPayPal(), Rox\returnFromPayPal(), MessagesModel\sendOrComplain(), LoginModel\setBWMemberAsLoggedIn(), MOD_bw_user_Auth\setupBWSession(), LoginModel\setupBWSession(), SignupController\signupFormCallback(), SignupView\signupTeamMail(), Forums\SubscribeTag(), Forums\SubscribeThread(), GeoModel\suggestLocation(), Forums\switchForumOrderList(), SignupModel\takeCareForComputerUsedByBWMember(), SignupModel\takeCareForNonUniqueEmailAddress(), Forums\UnsubscribeTag(), Forums\UnsubscribeTagDirect(), Forums\UnsubscribeThread(), Forums\UnsubscribeThreadDirect(), PollsModel\UpdateChoice(), PollsModel\UpdatePoll(), and Forums\VoteForPost().
MOD_log::write ($message = "", $type = "Log")
Add one entry to log table. If log2file is enabled write to logfile before write to table. addslashes is executed on the message string inside the method.
Parameters
string $message the parameter to print
string $type the event, which causes the log method to be called
Definition at line 120 of file log.lib.php.
References $_SESSION, $query, $text, $type, LOG2FILE, and LOG_FILE.
Referenced by InviteModel\sendOrComplain(), and writeIdMember().
MOD_log::writeIdMember ($IdMember, $message = "", $type = "Log")
Add one entry to log table. If log2file is enabled write to logfile before write to table. addslashes is executed on the message string inside the method.
@param int $IdMember is the id of the member the log will be applied to
Parameters
string $message the parameter to print
string $type the event, which causes the log method to be called
BeWare this function does a nasty parameter change with the $_SESSION["IdMember"] but it restores it as it was before in any cases
Definition at line 93 of file log.lib.php.
References $_SESSION, $type, and write().
Field Documentation
const MOD_log::LOG2FILE = false
if LOG2FILE is true, stuff gets additionally loged to file
Definition at line 35 of file log.lib.php.
Referenced by write().
const MOD_log::LOG_FILE = '/tmp/bw.log'
points to the file, which can be used for additionally loging
Definition at line 41 of file log.lib.php.
Referenced by write().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/log/lib/log.lib.php