Rox: SimplePie_Decode_HTML_Entities Class Reference
SimplePie_Decode_HTML_Entities Class Reference
Public Member Functions
__construct ($data)
parse ()
consume ()
consume_range ($chars)
unconsume ()
entity ()
Data Fields
$data = ''
$consumed = ''
$position = 0
Constructor & Destructor Documentation
SimplePie_Decode_HTML_Entities::__construct ($data)
Create an instance of the class with the input data
public
Parameters
string $data Input data
References $data.
Member Function Documentation
SimplePie_Decode_HTML_Entities::consume ()
Consume the next byte
private
Returns
mixed The next byte, or false, if there is no more data
References $position, and position.
Referenced by entity(), and parse().
SimplePie_Decode_HTML_Entities::consume_range ($chars)
Consume a range of characters
private
Parameters
string $chars Characters to consume
Returns
mixed A series of characters that match the range, or false
References $data, and position.
Referenced by entity().
SimplePie_Decode_HTML_Entities::entity ()
Decode an entity
private
References $consumed, $i, SimplePie_Misc\codepoint_to_utf8(), consume(), consume_range(), position, and unconsume().
Referenced by parse().
SimplePie_Decode_HTML_Entities::parse ()
Parse the input data
public
Returns
string Output data
References $data, consume(), entity(), and position.
SimplePie_Decode_HTML_Entities::unconsume ()
Unconsume one byte
private
References position.
Referenced by entity().
Field Documentation
SimplePie_Decode_HTML_Entities::$consumed = ''
Referenced by entity().
SimplePie_Decode_HTML_Entities::$data = ''
Referenced by __construct(), consume_range(), and parse().
SimplePie_Decode_HTML_Entities::$position = 0
Referenced by consume().
The documentation for this class was generated from the following file:
Entities.php