Rox: SimplePie_Sanitize Class Reference
SimplePie_Sanitize Class Reference
Public Member Functions
__construct ()
remove_div ($enable=true)
set_image_handler ($page=false)
set_registry (SimplePie_Registry $registry)
pass_cache_data ($enable_cache=true, $cache_location= './cache', $cache_name_function= 'md5', $cache_class= 'SimplePie_Cache')
pass_file_data ($file_class= 'SimplePie_File', $timeout=10, $useragent= '', $force_fsockopen=false)
strip_htmltags ($tags=array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style'))
encode_instead_of_strip ($encode=false)
strip_attributes ($attribs=array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc'))
strip_comments ($strip=false)
set_output_encoding ($encoding= 'UTF-8')
set_url_replacements ($element_attribute=null)
sanitize ($data, $type, $base= '')
replace_urls ($document, $tag, $attributes)
do_strip_htmltags ($match)
Data Fields
$base
$remove_div = true
$image_handler = ''
$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style')
$encode_instead_of_strip = false
$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc')
$strip_comments = false
$output_encoding = 'UTF-8'
$enable_cache = true
$cache_location = './cache'
$cache_name_function = 'md5'
$timeout = 10
$useragent = ''
$force_fsockopen = false
$replace_url_attributes = null
Protected Member Functions
preprocess ($html, $type)
strip_tag ($tag, $document, $type)
strip_attr ($attrib, $document)
Constructor & Destructor Documentation
SimplePie_Sanitize::__construct ()
References set_url_replacements().
Member Function Documentation
SimplePie_Sanitize::do_strip_htmltags ($match)
References elseif, encode_instead_of_strip(), and ENT_COMPAT.
SimplePie_Sanitize::encode_instead_of_strip ($encode = false)
Referenced by do_strip_htmltags(), and strip_tag().
SimplePie_Sanitize::pass_cache_data ($enable_cache = true, $cache_location = './cache', $cache_name_function = 'md5', $cache_class = 'SimplePie_Cache')
References $cache_location, $cache_name_function, and $enable_cache.
SimplePie_Sanitize::pass_file_data ($file_class = 'SimplePie_File', $timeout = 10, $useragent = '', $force_fsockopen = false)
References $force_fsockopen, $timeout, and $useragent.
SimplePie_Sanitize::preprocess ($html, $type) protected
References $type, and SIMPLEPIE_CONSTRUCT_XHTML.
Referenced by sanitize().
SimplePie_Sanitize::remove_div ($enable = true)
Referenced by sanitize().
SimplePie_Sanitize::replace_urls ($document, $tag, $attributes)
References $base, $value, and strip_htmltags().
Referenced by sanitize().
SimplePie_Sanitize::sanitize ($data, $type, $base = '')
References $base, $comment, $comments, $data, $type, ENT_COMPAT, preprocess(), remove_div(), replace_urls(), SIMPLEPIE_CONSTRUCT_BASE64, SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_CONSTRUCT_XHTML, SIMPLEPIE_FILE_SOURCE_REMOTE, SIMPLEPIE_PCRE_HTML_ATTRIBUTE, SIMPLEPIE_PCRE_XML_ATTRIBUTE, strip_attr(), strip_attributes(), strip_comments(), strip_htmltags(), and strip_tag().
SimplePie_Sanitize::set_image_handler ($page = false)
SimplePie_Sanitize::set_output_encoding ($encoding = 'UTF-8')
SimplePie_Sanitize::set_registry (SimplePie_Registry $registry)
SimplePie_Sanitize::set_url_replacements ($element_attribute = null)
Set element/attribute key/value pairs of HTML attributes containing URLs that need to be resolved relative to the feed
Defaults to |a|, |area|, |blockquote|
Referenced by __construct().
SimplePie_Sanitize::strip_attr ($attrib, $document) protected
Referenced by sanitize().
SimplePie_Sanitize::strip_attributes ($attribs = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc'))
Referenced by sanitize().
SimplePie_Sanitize::strip_comments ($strip = false)
Referenced by sanitize().
SimplePie_Sanitize::strip_htmltags ($tags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style'))
References $tags.
Referenced by replace_urls(), and sanitize().
SimplePie_Sanitize::strip_tag ($tag, $document, $type) protected
References $i, $name, $number, $text, $type, $value, elseif, encode_instead_of_strip(), SIMPLEPIE_CONSTRUCT_HTML, and SIMPLEPIE_CONSTRUCT_XHTML.
Referenced by sanitize().
Field Documentation
SimplePie_Sanitize::$base
Referenced by replace_urls(), and sanitize().
SimplePie_Sanitize::$cache_location = './cache'
Referenced by pass_cache_data().
SimplePie_Sanitize::$cache_name_function = 'md5'
Referenced by pass_cache_data().
SimplePie_Sanitize::$enable_cache = true
Referenced by pass_cache_data().
SimplePie_Sanitize::$encode_instead_of_strip = false
SimplePie_Sanitize::$force_fsockopen = false
Referenced by pass_file_data().
SimplePie_Sanitize::$image_handler = ''
SimplePie_Sanitize::$output_encoding = 'UTF-8'
SimplePie_Sanitize::$remove_div = true
SimplePie_Sanitize::$replace_url_attributes = null
SimplePie_Sanitize::$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc')
SimplePie_Sanitize::$strip_comments = false
SimplePie_Sanitize::$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style')
SimplePie_Sanitize::$timeout = 10
Referenced by pass_file_data().
SimplePie_Sanitize::$useragent = ''
Referenced by pass_file_data().
The documentation for this class was generated from the following file:
Sanitize.php