Rox: MOD_encdb Class Reference
MOD_encdb Class Reference
Public Member Functions
__construct ($tablename, $rownumber, $idMember, $keyMember)
writeEncrypted ($plainString)
readEncryptedMemberValue ($id)
readEncryptedAdminValue ($id)
test ()
Public Member Functions inherited from MOD_enc
__construct ($tablename, $rownumber, $keyMember)
test ()
Data Fields
const TABLE_NAME = 'safe'
Data Fields inherited from MOD_enc
const MODE = MCRYPT_MODE_CFB
const CIPHER = MCRYPT_DES
const TABLE_NAME_REF_MEMBER = 1
const TABLE_NAME_REF_ADDR = 2
Additional Inherited Members
Protected Member Functions inherited from MOD_enc
adminEncrypt ($plainString)
adminDecrypt ($encryptedString)
memberEncrypt ($plainString)
memberDecrypt ($encryptedString)
Detailed Description
All r/w operations on potentially encrypted fields in database should get initiated here.
TODO: would this enum be a good example for other tables? TODO: do we use InnoDB? TODO: do I use the correct character sets? TODO: should we use binary fields and don't use base64? TODO: what mysql datatype is appropriate for base64?
CREATE TABLE safe (id int(11) NOT NULL auto_increment, val_admin text collate utf8_unicode_ci NOT NULL, val_member text collate utf8_unicode_ci NOT NULL, id_member int(11) NOT NULL, encryption enum('Y', 'N') collate utf8_unicode_ci NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='sensitive data' AUTO_INCREMENT=0;
See Also
htdocs/bw/lib/FunctionsCrypt.php
Definition at line 49 of file encdb.lib.php.
Constructor & Destructor Documentation
MOD_encdb::__construct ($tablename, $rownumber, $idMember, $keyMember)
Parameters
int $tablename name of table expressed as an integer, e.g. MOD_enc::TABLE_NAME_REF_MEMBER
int $rownumber number of row in the table afore mentioned
Returns
void
Definition at line 61 of file encdb.lib.php.
Member Function Documentation
MOD_encdb::readEncryptedAdminValue ($id)
Parameters
int id of recordset
Returns
string decrypted plain string, gained by admin key
Definition at line 124 of file encdb.lib.php.
References $id, $query, MOD_enc\adminDecrypt(), and TABLE_NAME.
Referenced by test().
MOD_encdb::readEncryptedMemberValue ($id)
Parameters
int id of recordset
Returns
string decrypted plain string, gained by member key
Definition at line 105 of file encdb.lib.php.
References $id, $query, MOD_enc\memberDecrypt(), and TABLE_NAME.
Referenced by test().
MOD_encdb::test ()
Definition at line 139 of file encdb.lib.php.
References $id, readEncryptedAdminValue(), readEncryptedMemberValue(), and writeEncrypted().
MOD_encdb::writeEncrypted ($plainString)
Parameters
string $plainString to be added after encrypting in new row
Returns
int rownumber of new row
Definition at line 78 of file encdb.lib.php.
References $id, $query, MOD_enc\adminEncrypt(), MOD_enc\memberEncrypt(), and TABLE_NAME.
Referenced by test().
Field Documentation
const MOD_encdb::TABLE_NAME = 'safe'
Definition at line 51 of file encdb.lib.php.
Referenced by readEncryptedAdminValue(), readEncryptedMemberValue(), and writeEncrypted().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/security/lib/encdb.lib.php