Rox: MOD_online Class Reference
MOD_online Class Reference
Public Member Functions
iAmOnline ($ip, $member_id=false)
howManyMembersOnline ($interval=false)
howManyGuestsOnline ($interval=false)
Static Public Member Functions
static get ()
Protected Attributes
$dao
$online_interval
Detailed Description
Definition at line 4 of file online.lib.php.
Member Function Documentation
static MOD_online::get () static
as long as we have no decent dependency injection whatever, we make this a singleton.
Definition at line 34 of file online.lib.php.
Referenced by RoxFrontRouter\initUser(), PageWithRoxLayout\quicksearch(), and PageWithRoxLayout\topnav().
MOD_online::howManyGuestsOnline ($interval = false)
find out how many guests have been online in the last $interval minutes
Parameters
int $interval
Returns
int
Definition at line 207 of file online.lib.php.
References $online_interval.
MOD_online::howManyMembersOnline ($interval = false)
find out how many members have been online in the last $interval minutes
Parameters
int $interval
Returns
int
Definition at line 170 of file online.lib.php.
References $online_interval.
MOD_online::iAmOnline ($ip, $member_id = false)
Update activity trackers in table membersonline and/or guestsonline
This function should be called in the bootstrap.
Parameters
int $ip
int $member_id
Definition at line 53 of file online.lib.php.
References $_SESSION.
Field Documentation
MOD_online::$dao protected
Definition at line 6 of file online.lib.php.
MOD_online::$online_interval protected
Definition at line 7 of file online.lib.php.
Referenced by howManyGuestsOnline(), and howManyMembersOnline().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/user/lib/online.lib.php