Rox: MOD_user Class Reference
MOD_user Class Reference
Public Member Functions
__destruct ()
getAuth ()
hasRight ($right)
logout ()
Static Public Member Functions
static passwordEncrypt ($password)
static randomString ($len)
static getTranslations ($idMember)
static getImage ($paramIdMember=0)
static getDummyImage ($Gender='IDontTell', $HideGender='Yes')
Protected Member Functions
__construct ($sessionName=false, $tableName=false)
setAuth ($authId)
doLogin ($handle, $pw)
doBWLogin ($handle)
getAuthId ($userId)
Protected Attributes
$authId
$sessionName
$tableName
$dao
Detailed Description
Author
Philipp Hunstein & Seong-Min Kang info@.nosp@m.resp.nosp@m.ice.d.nosp@m.e
Version
v2.0.0 Pre-Alpha
Constructor & Destructor Documentation
MOD_user::__construct ($sessionName = false, $tableName = false) protected
References $dao, $sessionName, and $tableName.
MOD_user::__destruct ()
Member Function Documentation
MOD_user::doBWLogin ($handle) protected
References $_SESSION, $d, $sessionName, and setAuth().
Referenced by MOD_bw_user_Auth\doLogin().
MOD_user::doLogin ($handle, $pw) protected
References $_SESSION, $d, $matches, $sessionName, elseif, and setAuth().
MOD_user::getAuth ()
Referenced by hasRight().
MOD_user::getAuthId ($userId) protected
References $authId, and $d.
static MOD_user::getDummyImage ($Gender = 'IDontTell', $HideGender = 'Yes') static
Returns the path to an appropriate dummy image in case no image is found.
Parameters
unknown_type $Gender
unknown_type $HideGender
Returns
unknown
static MOD_user::getImage ($paramIdMember = 0) static
References $_SESSION, and $dao.
static MOD_user::getTranslations ($idMember) static
References $dao.
MOD_user::hasRight ($right)
References $right, and getAuth().
MOD_user::logout ()
References $_SESSION.
static MOD_user::passwordEncrypt ($password) static
Referenced by User\registerProcess(), and MOD_bw_user_Auth\updateUser().
static MOD_user::randomString ($len) static
References $i.
MOD_user::setAuth ($authId) protected
References $authId.
Referenced by doBWLogin(), and doLogin().
Field Documentation
MOD_user::$authId protected
Referenced by MOD_user_Auth\__construct(), MOD_bw_user_Auth\__construct(), getAuthId(), setAuth(), and MOD_bw_user_Auth\updateUser().
MOD_user::$dao protected
Referenced by __construct(), getImage(), and getTranslations().
MOD_user::$sessionName protected
Referenced by __construct(), MOD_user_Auth\__construct(), MOD_bw_user_Auth\__construct(), doBWLogin(), and doLogin().
MOD_user::$tableName protected
Referenced by __construct(), MOD_user_Auth\__construct(), and MOD_bw_user_Auth\__construct().
The documentation for this class was generated from the following file:
modules/user/lib/user.lib.php