Rox: NotifyMemberWidget_Personalstart Class Reference
NotifyMemberWidget_Personalstart Class Reference
Public Member Functions
render ()
needsPagination ()
showPagination ()
__call ($methodname, $args)
getStylesheets ()
getScriptfiles ()
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
getAllItems ()
showItems ()
showListItem ($item, $i_row)
showBetweenListItems ($prev_item, $item, $i_row)
showItems_list ()
showDefaultText ()
prepare ()
numberOfPages ()
getItems ()
getItemsForPage ($k_page)
itemsTotalBegin ()
showPageLink ($i_page)
showActivePageLink ($i_page)
getItemsInRange ($begin, $count)
itemsTotalCount ()
showItems_table ()
showItems_float ()
hideColumnTitles ()
createEntity ()
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$_entity_factory
Member Function Documentation
ItemlistWidget::__call ($methodname, $args) inherited
RoxComponentBase::__get ($key) inherited
Referenced by Member\get_messengers().
RoxComponentBase::__set ($key, $value) inherited
References $value.
RoxComponentBase::__toString () inherited
RoxWidget::createEntity () protected inherited
calls the entity factory to create an entity, passes along any arguments
Parameters
string - first parameter must be the name of the entity to create
Returns
object protected
Referenced by NotifyAdminWidget\getTableColumns().
RoxComponentBase::get ($key) protected inherited
Referenced by SignupClosedPage\column_col3(), SignupProblemPage\column_col3(), and SignupPage\column_col3().
NotifyMemberWidget::getAllItems () protected inherited
References model.
VisualComponent::getAppname ($classname) protected inherited
References ClassLoader\whereIsClass().
ItemlistWithPagination::getItems () protected inherited
References active_page, ItemlistWithPagination\getItemsForPage(), and ItemlistWithPagination\prepare().
ItemlistWithPagination::getItemsForPage ($k_page) protected inherited
References ItemlistWithPagination\getItemsInRange(), ItemlistWithPagination\itemsTotalBegin(), ItemlistWithPagination\itemsTotalCount(), and ItemlistWithPagination\prepare().
Referenced by ItemlistWithPagination\getItems().
ItemlistWithPagination::getItemsInRange ($begin, $count) protected inherited
Get all items with $begin <= $index < $end.
Parameters
int $begin
int $end
Returns
array items in range
References $count, and $items.
Referenced by ItemlistWithPagination\getItemsForPage().
RoxComponentBase::getLog () protected inherited
wrapper function for MOD_log::get()
protected
Returns
object
References MOD_log\get().
Referenced by RoxComponentBase\logWrite().
RoxWidget::getScriptfiles () inherited
RoxWidget::getStylesheets () inherited
VisualComponent::getTemplatePrefix ($classname = false) protected inherited
References ClassLoader\whereIsClass().
Referenced by VisualComponent\__call().
RoxComponentBase::getValues () protected inherited
RoxComponentBase::getVersionInfo () protected inherited
returns the revision number saved in revision.txt
protected
Returns
string
References $version.
Referenced by FeedbackModel\sendFeedback().
RoxComponentBase::getWords () protected inherited
returns an instance of the MOD_words class
protected
Returns
object
Referenced by VisualComponent\__call(), GroupsController\acceptInvitation(), GroupsController\addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), GeoPopupPage\body(), GalleryDeletePage\breadcrumbs(), GalleryBasePage\breadcrumbs(), SuggestionsController\changeStateCallback(), MyVisitorsPage\column_col3(), GalleryFlickrPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryAllImagesPage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), LinkUpdatePage\column_col3(), HellouniversePage\column_col3(), GeoAdminPage\column_col3(), GalleryDeletePage\column_col3(), NewsletterPage\column_col3(), FeedbackSentPage\column_col3(), VerifyMembersNotActivePage\column_col3(), VerifyMyselfPage\column_col3(), OneNewsLetterPage\column_col3(), GalleryManagePage\column_col3(), GalleryAllGalleriesPage\column_col3(), VerifiedApprovedVerifiers\column_col3(), ActivitiesFindPage\column_col3(), GroupStartPage\column_col3(), GroupJoinPage\column_col3(), GroupMemberSettingsPage\column_col3(), AboutFaqPage\column_col3(), GroupDeletePage\column_col3(), GroupWikiPage\column_col3(), GroupAddRelatedGroupPage\column_col3(), GroupDeleteRelatedGroupPage\column_col3(), GroupLeavePage\column_col3(), GroupForumPage\column_col3(), GroupRelatedGroupLogPage\column_col3(), AboutFaqsectionPage\column_col3(), PollsPage\column_col3(), VerifiedMembersViewPage\column_col3(), HellouniverseTabbedPage\column_col3(), GroupForumsOverviewPage\column_col3(), GroupsController\declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), Member\get_all_relations(), MembersModel\get_relation_between_members(), Member\get_trad_by_tradid(), Group\getDescription(), FullPagePager\getHtml(), Note\getIdRelMember(), Forums\GetLanguageName(), LastCommentsPage\getLastCommentsTitle(), PageWithRoxLayout\getPage_meta_description(), PageWithRoxLayout\getPage_meta_keyword(), UpdateMandatoryPage\getPageTitle(), AboutTheideaPage\getPageTitle(), ActivitiesBasePage\getPageTitle(), CityPage\getPageTitle(), CountriesPage\getPageTitle(), CountryPage\getPageTitle(), RegionPage\getPageTitle(), SafetyBasePage\getPageTitle(), SearchMembersBasePage\getPageTitle(), SuggestionsBasePage\getPageTitle(), NewsletterPage\getPageTitle(), OneNewsLetterPage\getPageTitle(), GroupsBasePage\getPageTitle(), VerifiedMembersViewPage\getPageTitle(), PollsPage\getPageTitle(), SuggestionsBasePage\getStateSelect(), DebugPage\getSubmenuItems(), GalleryUserPage\getSubmenuItems(), AboutBasePage\getSubmenuItems(), SuggestionsEditCreatePage\getSubmenuItems(), SuggestionsViewPage\getSubmenuItems(), MessagesBasePage\getSubmenuItems(), GroupsSearchPage\getSubmenuItems(), GroupsMyGroupsPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), SuggestionsBasePage\getSubmenuItems(), PageWithHTML\head(), MembersController\index_loggedIn(), GroupsController\joined(), GroupsController\kickMember(), Forums\LanguageChoices(), GroupsController\leave(), GroupsController\left(), PageWithRoxLayout\leftoverTranslationLinks(), AboutFaqsectionPage\leftSidebar(), AboutFaqPage\leftSidebar(), InactiveProfilePage\leftsidebar(), AdminMassMailEnqueuePage\leftSidebar(), VerifyMembersPage\leftSidebar(), AdminMassMailDetailsPage\leftSidebar(), AdminMassMailEditCreatePage\leftSidebar(), VerifiedApprovedVerifiers\leftSidebar(), VerifiedMembersViewPage\leftSidebar(), PollsPage\leftSidebar(), MemberPage\leftsidebar(), LoginController\loginCallback(), GalleryController\manage(), MessagesPageWithMailbox\messageActions(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), SuggestionsController\moveSuggestionToImplemented(), NotifyAdminPage\notesActions(), GroupsModel\notifyGroupAdmins(), PageWithRoxLayout\quicksearch(), GroupsController\resignAsAdmin(), SuggestionsController\restoreOption(), GeoController\SelectorInclude(), GroupsModel\sendInvitation(), Group\setDescription(), PageWithRoxLayout\SetMetaKey(), AbstractBasePage\showTemplate(), PageWithRoxLayout\submenu(), MessagesBasePage\teaserContent(), GroupSettingsPage\teaserContent(), GroupsSearchPage\teaserContent(), GroupsMyGroupsPage\teaserContent(), GroupInvitePage\teaserContent(), GroupsCreationPage\teaserContent(), TourPage\teaserContent(), GroupsFeaturedPage\teaserContent(), GroupsOverviewPage\teaserContent(), LastCommentsPage\teaserContent(), GroupForumsOverviewPage\teaserContent(), GroupsBasePage\teaserContent(), ResetPasswordFinishPage\teaserHeadline(), ResetPasswordPage\teaserHeadline(), VerifyNoMemberSpecifiedPage\teaserHeadline(), AboutBasePage\teaserHeadline(), GalleryImageNotFoundPage\teaserHeadline(), GalleryAvatarsPage\teaserHeadline(), AboutStatisticsPage\teaserHeadline(), VerifyMyselfPage\teaserHeadline(), VerifyMembersNotActivePage\teaserHeadline(), VerifyMembersPage\teaserHeadline(), GalleryBasePage\teaserHeadline(), SearchMembersBasePage\teaserHeadline(), VerifiedApprovedVerifiers\teaserHeadline(), SuggestionsBasePage\teaserHeadline(), OneNewsLetterPage\teaserHeadline(), VerifiedMembersViewPage\teaserHeadline(), PollsPage\teaserHeadline(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), GroupMembership\updateMembership(), GalleryController\upload(), GalleryController\uploadedProcess(), GalleryController\user(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
ItemlistWidget::hideColumnTitles () protected inherited
Referenced by ItemlistWidget\showItems_float(), and ItemlistWidget\showItems_table().
ItemlistWithPagination::itemsTotalBegin () protected inherited
Referenced by ItemlistWithPagination\getItemsForPage().
ItemlistWithPagination::itemsTotalCount () protected inherited
Returns
int number of items on all pages together
Referenced by ItemlistWithPagination\getItemsForPage(), and ItemlistWithPagination\numberOfPages().
RoxComponentBase::logWrite ($string, $type = 'Log') protected inherited
wrapper for calls to MOD_log::get->write()
Parameters
string $string
string $type protected
References $type, and RoxComponentBase\getLog().
Referenced by GroupsController\acceptInvitation(), GroupsController\acceptMember(), MembersModel\addComment(), GroupsController\addMemberAsAdmin(), MembersModel\addRelation(), GroupsController\banMember(), GroupsController\changeGroupSettings(), GroupsController\changeMemberSettings(), GroupsController\createGroupCallback(), GroupsController\declineInvitation(), GroupsController\delete(), MembersModel\delete_translation_multiple(), FeedbackModel\feedbackMail(), MembersController\index_loggedIn(), GroupsController\inviteMember(), GroupsController\inviteMemberAjax(), GroupsController\joined(), GroupsController\kickMember(), GroupsController\left(), Geo\placeType(), AdminModel\processMembers(), GroupsController\resignAsAdmin(), MembersModel\set_preference(), MembersModel\set_public_profile(), MembersModel\setLocation(), MembersModel\updateProfile(), and MembersModel\updateRelation().
ItemlistWithPagination::needsPagination () inherited
References ItemlistWithPagination\numberOfPages().
ItemlistWithPagination::numberOfPages () protected inherited
References items_per_page, ItemlistWithPagination\itemsTotalCount(), and ItemlistWithPagination\prepare().
Referenced by ItemlistWithPagination\needsPagination(), ItemlistWithPagination\prepare(), and ItemlistWithPagination\showPagination().
ItemlistWithPagination::prepare () protected inherited
References active_page, items_per_page, and ItemlistWithPagination\numberOfPages().
Referenced by ItemlistWithPagination\getItems(), ItemlistWithPagination\getItemsForPage(), ItemlistWithPagination\numberOfPages(), ItemlistWithPagination\render(), and ItemlistWithPagination\showPagination().
RoxComponentBase::refresh_get ($key) inherited
NotifyMemberWidget::render () inherited
References render.
VisualComponent::set_layoutkit (& $layoutkit) protected inherited
called by the framework, to inject some essential values..
Parameters
unknown_type $layoutkit
References $layoutkit, $words, layoutkit, and words.
ItemlistWithPagination::showActivePageLink ($i_page) protected inherited
Referenced by ItemlistWithPagination\showPagination().
NotifyMemberWidget::showBetweenListItems ($prev_item, $item, $i_row) protected inherited
NotifyMemberWidget::showDefaultText () protected inherited
NotifyMemberWidget::showItems () protected inherited
References $words, e, Effect, element, Element, Event, and NotifyMemberWidget\showItems_list().
ItemlistWidget::showItems_float () protected inherited
References $items, $value, ItemlistWidget\getItems(), and ItemlistWidget\hideColumnTitles().
NotifyMemberWidget::showItems_list () protected inherited
References $items, and elseif.
Referenced by NotifyMemberWidget\showItems().
ItemlistWidget::showItems_table () protected inherited
References $items, $value, ItemlistWidget\getItems(), and ItemlistWidget\hideColumnTitles().
Referenced by ItemlistWidget\showItems().
NotifyMemberWidget::showListItem ($item, $i_row) protected inherited
References $member, $text, $words, a, MOD_layoutbits\ago(), p, MOD_layoutbits\PIC_30_30(), and title.
ItemlistWithPagination::showPageLink ($i_page) protected inherited
Referenced by ItemlistWithPagination\showPagination().
ItemlistWithPagination::showPagination () inherited
References $i, ItemlistWithPagination\numberOfPages(), ItemlistWithPagination\prepare(), ItemlistWithPagination\showActivePageLink(), and ItemlistWithPagination\showPageLink().
Field Documentation
RoxWidget::$_entity_factory protected inherited
The documentation for this class was generated from the following file:
personalstart.page.php