Rox: FullPagePager Class Reference
FullPagePager Class Reference
Public Member Functions
__construct ()
render ()
getHtml ()
Public Member Functions inherited from RoxWidget
__construct ()
render ()
getStylesheets ()
getScriptfiles ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const block_links = 2
Additional Inherited Members
Protected Member Functions inherited from RoxWidget
createEntity ()
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxWidget
$_entity_factory
Detailed Description
Definition at line 3 of file fullpagepager.widget.php.
Constructor & Destructor Documentation
FullPagePager::__construct ()
Definition at line 8 of file fullpagepager.widget.php.
Member Function Documentation
FullPagePager::getHtml ()
returns rather than renders the pager
public
Returns
string
Definition at line 53 of file fullpagepager.widget.php.
References $i, $pager, $pages, active_page, and RoxComponentBase\getWords().
Referenced by render().
FullPagePager::render ()
outputs a list of list links, to reflect paging
public
Returns
void
Definition at line 18 of file fullpagepager.widget.php.
References getHtml().
Field Documentation
const FullPagePager::block_links = 2
Definition at line 5 of file fullpagepager.widget.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/widget/fullpagepager.widget.php