Rox: MessagesModel Class Reference
MessagesModel Class Reference
Public Member Functions
__construct ()
filteredMailbox ($where_filters, $sort_string=false)
sortFilters ($sort_element=false)
receivedMailbox ($sort_element=false)
sentMailbox ($sort_element=false)
spamMailbox ($sort_element=false)
getMessage ($message_id)
deleteMessage ($message_id)
markReadMessage ($message_id, $read=true)
moveMessage ($message_id, $folder)
updateSpamInfo ($message_id, $marks_to_add, $marks_to_remove, $spam_info=null)
getMember ($username)
getMessagesWith ($contact_id)
hasMessageLimitExceeded ($memberId)
getSpamCheckStatus ($IdSender, $IdReceiver)
sendOrComplain ($input)
DisplayCaptcha ($value)
CaptchaNeeded ($IdMember)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
$sort_element
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 11 of file messages.model.php.
Constructor & Destructor Documentation
MessagesModel::__construct ()
Definition at line 15 of file messages.model.php.
Member Function Documentation
MessagesModel::CaptchaNeeded ($IdMember)
Definition at line 511 of file messages.model.php.
References RoxModelBase\singleLookup().
MessagesModel::deleteMessage ($message_id)
Definition at line 151 of file messages.model.php.
References $_SESSION, MOD_log\get(), and RoxModelBase\singleLookup().
MessagesModel::DisplayCaptcha ($value)
Definition at line 503 of file messages.model.php.
References $_SESSION, and $value.
MessagesModel::filteredMailbox ($where_filters, $sort_string = false)
Definition at line 21 of file messages.model.php.
References $query, RoxModelBase\bulkLookup(), and sortFilters().
Referenced by getMessagesWith(), receivedMailbox(), sentMailbox(), and spamMailbox().
MessagesModel::getMember ($username)
Definition at line 250 of file messages.model.php.
References RoxModelBase\singleLookup().
Referenced by sendOrComplain().
MessagesModel::getMessage ($message_id)
Definition at line 115 of file messages.model.php.
References $_SESSION, and RoxModelBase\singleLookup().
Referenced by sendOrComplain().
MessagesModel::getMessagesWith ($contact_id)
Definition at line 260 of file messages.model.php.
References $_SESSION, and filteredMailbox().
MessagesModel::getSpamCheckStatus ($IdSender, $IdReceiver)
Definition at line 345 of file messages.model.php.
References $ii, $max, and $Status.
MessagesModel::hasMessageLimitExceeded ($memberId)
Tests if a member has exceeded its limit for sending messages
Parameters
int $memberId ID of member
Returns
bool|string False if not exceeded, error message if exceeded
Definition at line 278 of file messages.model.php.
References $comments, $id, $query, $words, and RoxModelBase\singleLookup().
Referenced by sendOrComplain().
MessagesModel::markReadMessage ($message_id, $read = true)
Definition at line 185 of file messages.model.php.
References MOD_log\get().
MessagesModel::moveMessage ($message_id, $folder)
Definition at line 199 of file messages.model.php.
MessagesModel::receivedMailbox ($sort_element = false)
Definition at line 76 of file messages.model.php.
References $_SESSION, $sort_element, filteredMailbox(), and sortFilters().
MessagesModel::sendOrComplain ($input)
Look if the information in $input is ok to send. If yes, send and return a confirmation. Otherwise, return an array that tells what is missing.
required information in $input: sender_id, receiver_id, text
optional fields in $input: reply_to_id, draft_id
Parameters
unknown_type $input
Definition at line 413 of file messages.model.php.
References $_SESSION, $member, $problems, MOD_log\get(), getMember(), getMessage(), hasMessageLimitExceeded(), and RoxModelBase\singleLookup().
MessagesModel::sentMailbox ($sort_element = false)
Definition at line 89 of file messages.model.php.
References $_SESSION, $sort_element, filteredMailbox(), and sortFilters().
MessagesModel::sortFilters ($sort_element = false)
Definition at line 56 of file messages.model.php.
References $sort_element.
Referenced by filteredMailbox(), receivedMailbox(), sentMailbox(), and spamMailbox().
MessagesModel::spamMailbox ($sort_element = false)
Definition at line 102 of file messages.model.php.
References $_SESSION, $sort_element, filteredMailbox(), and sortFilters().
MessagesModel::updateSpamInfo ($message_id, $marks_to_add, $marks_to_remove, $spam_info = null)
add and remove marks from the SpamInfo of a message
Parameters
integer $message_id
array/string $marks_to_add
array/string $marks_to_remove
string $spam_info current value of the SpamInfo column (optional)
Returns
void
Definition at line 220 of file messages.model.php.
References RoxModelBase\singleLookup().
Field Documentation
MessagesModel::$sort_element
Definition at line 13 of file messages.model.php.
Referenced by receivedMailbox(), sentMailbox(), sortFilters(), and spamMailbox().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/messages/messages.model.php