Rox: LoginModel Class Reference
LoginModel Class Reference
Public Member Functions
encryptPasswordBW ($password)
encryptPasswordTB ($password)
checkAuth ($authName)
createMissingTBUser ($member, $password)
checkBWPassword ($member, $password)
checkTBPassword ($tb_user, $password)
getBWMemberByUsername ($username)
getTBUserForBWMember ($member)
setBWMemberAsLoggedIn ($m)
setupBWSession ($m)
setTBUserAsLoggedIn ($tb_user)
setPreferredLanguage ()
logout ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const KEY_IN_SESSION = 'APP_User_id'
Protected Member Functions
randomString ($len)
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 33 of file login.model.php.
Member Function Documentation
LoginModel::checkAuth ($authName)
check if given auth name exists, creates if it does not
Parameters
string $authName
Returns
mixed id or false
Definition at line 88 of file login.model.php.
References $id, and PException\addInfo().
Referenced by createMissingTBUser().
LoginModel::checkBWPassword ($member, $password)
Definition at line 205 of file login.model.php.
References $member, MOD_log\get(), and RoxModelBase\singleLookup().
LoginModel::checkTBPassword ($tb_user, $password)
Definition at line 225 of file login.model.php.
References $matches.
LoginModel::createMissingTBUser ($member, $password)
Definition at line 134 of file login.model.php.
References $member, checkAuth(), encryptPasswordTB(), and RoxModelBase\singleLookup().
LoginModel::encryptPasswordBW ($password)
Definition at line 38 of file login.model.php.
References MOD_log\get(), and RoxModelBase\singleLookup().
LoginModel::encryptPasswordTB ($password)
Definition at line 55 of file login.model.php.
References randomString().
Referenced by createMissingTBUser().
LoginModel::getBWMemberByUsername ($username)
gets a BW member by username
Parameters
string $username - user handle
public
Returns
false|Member
Definition at line 263 of file login.model.php.
References $m, $username, and RoxModelBase\createEntity().
LoginModel::getTBUserForBWMember ($member)
Definition at line 282 of file login.model.php.
References $member, and RoxModelBase\singleLookup().
LoginModel::logout ()
Definition at line 524 of file login.model.php.
References $member, and RoxModelBase\getLoggedInMember().
Referenced by setupBWSession().
LoginModel::randomString ($len) protected
Definition at line 68 of file login.model.php.
References $i.
Referenced by encryptPasswordTB().
LoginModel::setBWMemberAsLoggedIn ($m)
Definition at line 305 of file login.model.php.
References $_SESSION, $m, break, false, MOD_log\get(), and RoxModelBase\singleLookup().
LoginModel::setPreferredLanguage ()
Definition at line 505 of file login.model.php.
References $_SESSION, $member, and RoxModelBase\getLoggedInMember().
LoginModel::setTBUserAsLoggedIn ($tb_user)
Definition at line 490 of file login.model.php.
References $_SESSION.
LoginModel::setupBWSession ($m)
Definition at line 381 of file login.model.php.
References $_SESSION, $m, MOD_log\get(), if, logout(), and RoxModelBase\singleLookup().
Field Documentation
const LoginModel::KEY_IN_SESSION = 'APP_User_id'
Definition at line 35 of file login.model.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/login/login.model.php