Rox: ClassLoader Class Reference
ClassLoader Class Reference
Public Member Functions
addClassesForAutoloadInisInFolder ($path, $subdir_level=1)
addClassesFromIniSettings ($ini_settings, $path_prefix=false)
addClass ($classname, $file)
autoload ($classname)
showClasses ()
whereIsClass ($classname)
camelCaseExplode ($string, $lowercase=true, $example_string= 'AA Bc', $glue=false)
Protected Member Functions
recursiveIniParsing (&$settings, $start_path, $rel_path, $subdir_level)
iniParsing (&$settings, $filename, $rel_path)
createIniFile ($filename, $settings)
addClassesFromIniRow ($file, $string_with_classnames)
requireFile ($rel_path, $classname=false)
requireFileAbsolute ($abs_path, $classname=false)
Detailed Description
This thing can be plugged into the AutoloadPlug, by AutoloadPlug::setCallback(array(new ClassLoader, 'autoload'));
Definition at line 8 of file classloader.php.
Member Function Documentation
ClassLoader::addClass ($classname, $file)
Definition at line 137 of file classloader.php.
Referenced by addClassesForAutoloadInisInFolder(), and addClassesFromIniRow().
ClassLoader::addClassesForAutoloadInisInFolder ($path, $subdir_level = 1)
Definition at line 12 of file classloader.php.
References addClass(), createIniFile(), iniParsing(), and recursiveIniParsing().
ClassLoader::addClassesFromIniRow ($file, $string_with_classnames) protected
Definition at line 130 of file classloader.php.
References addClass().
Referenced by addClassesFromIniSettings().
ClassLoader::addClassesFromIniSettings ($ini_settings, $path_prefix = false)
Definition at line 116 of file classloader.php.
References addClassesFromIniRow().
ClassLoader::autoload ($classname)
Definition at line 144 of file classloader.php.
References camelCaseExplode(), requireFile(), and requireFileAbsolute().
ClassLoader::camelCaseExplode ($string, $lowercase = true, $example_string = 'AA Bc', $glue = false)
thanks a lot Charl van Niekerk, http://blog.charlvn.za.net/2007/11/php-camelcase-explode-20.html
Parameters
string $name
boolean $lowercase
Returns
array of string segments
Definition at line 244 of file classloader.php.
Referenced by autoload().
ClassLoader::createIniFile ($filename, $settings) protected
Definition at line 99 of file classloader.php.
Referenced by addClassesForAutoloadInisInFolder().
ClassLoader::iniParsing (& $settings, $filename, $rel_path) protected
Definition at line 68 of file classloader.php.
Referenced by addClassesForAutoloadInisInFolder(), and recursiveIniParsing().
ClassLoader::recursiveIniParsing (& $settings, $start_path, $rel_path, $subdir_level) protected
Definition at line 40 of file classloader.php.
References iniParsing().
Referenced by addClassesForAutoloadInisInFolder().
ClassLoader::requireFile ($rel_path, $classname = false) protected
Definition at line 197 of file classloader.php.
References requireFileAbsolute().
Referenced by autoload().
ClassLoader::requireFileAbsolute ($abs_path, $classname = false) protected
Definition at line 202 of file classloader.php.
Referenced by autoload(), and requireFile().
ClassLoader::showClasses ()
Definition at line 220 of file classloader.php.
ClassLoader::whereIsClass ($classname)
Definition at line 226 of file classloader.php.
Referenced by VisualComponent\getAppname(), and VisualComponent\getTemplatePrefix().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/roxlauncher/classloader.php