Rox: PageWithRoxLayout Class Reference
PageWithRoxLayout Class Reference
Public Member Functions
SetMetaKey ($ss)
SetMetaRobots ($ss)
SetMetaDescription ($ss)
getFlashNotice ($remove=false)
getFlashError ($remove=false)
Public Member Functions inherited from PageWithHTML
render ()
addWidget (RoxWidget $widget)
Public Member Functions inherited from AbstractBasePage
setModel ($model)
createWidget ($classname)
render ()
Public Member Functions inherited from VisualComponent
__call ($methodname, $args)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
getStylesheets ()
getPage_meta_keyword ()
getPage_meta_robots ()
getPage_meta_description ()
init ()
getStylesheetPatches ()
getTopmenuItems ()
getTopmenuActiveItem ()
getSubmenuItems ()
getSubmenuActiveItem ()
body ()
topnav ()
topmenu ()
quicksearch ()
columnsArea ()
getPageTitle ()
teaser ()
teaserContent ()
submenu ()
footer ()
leftoverTranslationLinks ()
debugInfo ()
getColumnNames ()
column_col1 ()
column_col2 ()
volunteerMenu ()
getCallbackOutput ($controller, $method)
getRedirectedMem ($array)
Protected Member Functions inherited from PageWithHTML
init ()
getCustomElements ()
getStylesheets ()
getStylesheetPatches ()
getScriptfiles ()
getLateLoadScriptfiles ()
addEarlyLoadScriptFile ($file)
addLateLoadScriptFile ($file)
getPageTitle ()
printHTML ()
includeStylesheets ()
includeCustomElements ()
includeJsConfig ()
includeScriptfiles ()
includeLateScriptfiles ()
head ()
getPagePermalink ()
statusMessage ()
Protected Member Functions inherited from AbstractBasePage
getModel ()
showTemplate ($rel_path, $args=array())
Protected Member Functions inherited from VisualComponent
set_layoutkit (&$layoutkit)
getTemplatePrefix ($classname=false)
getAppname ($classname)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes
$meta_description
$meta_keyword
$meta_robots
Detailed Description
Definition at line 6 of file roxlayout.page.php.
Member Function Documentation
PageWithRoxLayout::body () protected
Definition at line 121 of file roxlayout.page.php.
References TEMPLATE_DIR.
Referenced by AdminMassMailEditCreatePage\__construct().
PageWithRoxLayout::column_col1 () protected
Definition at line 285 of file roxlayout.page.php.
PageWithRoxLayout::column_col2 () protected
Definition at line 290 of file roxlayout.page.php.
PageWithRoxLayout::columnsArea () protected
Definition at line 221 of file roxlayout.page.php.
References getColumnNames(), and TEMPLATE_DIR.
PageWithRoxLayout::debugInfo () protected
Definition at line 268 of file roxlayout.page.php.
References debug, and TEMPLATE_DIR.
PageWithRoxLayout::footer () protected
Definition at line 252 of file roxlayout.page.php.
PageWithRoxLayout::getCallbackOutput ($controller, $method) protected
shortcut to get callback variables for form
Parameters
string $controller controller to callback to
string $method method in controller
protected
Returns
string
Definition at line 309 of file roxlayout.page.php.
References layoutkit.
Referenced by TripSingleTripPage\column_col3(), BlogCreatePage\column_col3(), and BlogEditPage\column_col3().
PageWithRoxLayout::getColumnNames () protected
Definition at line 275 of file roxlayout.page.php.
Referenced by columnsArea().
PageWithRoxLayout::getFlashError ($remove = false)
Get flash error message and remove from session if needed
See Also
RoxControllerBase::setFlashError() for counterpart
templates/shared/roxpage/body.php
Parameters
bool $remove True if message should be removed from session, false by default
Returns
string Flash error message
Definition at line 380 of file roxlayout.page.php.
PageWithRoxLayout::getFlashNotice ($remove = false)
Get flash notice message and remove from session if needed
See Also
RoxControllerBase::setFlashNotice() for counterpart
templates/shared/roxpage/body.php
Parameters
bool $remove True if message should be removed from session, false by default
Returns
string Flash notice message
Definition at line 366 of file roxlayout.page.php.
PageWithRoxLayout::getPage_meta_description () protected
Definition at line 51 of file roxlayout.page.php.
References $words, and RoxComponentBase\getWords().
PageWithRoxLayout::getPage_meta_keyword () protected
Definition at line 23 of file roxlayout.page.php.
References $words, and RoxComponentBase\getWords().
PageWithRoxLayout::getPage_meta_robots () protected
Definition at line 38 of file roxlayout.page.php.
PageWithRoxLayout::getPageTitle () protected
Definition at line 229 of file roxlayout.page.php.
PageWithRoxLayout::getRedirectedMem ($array) protected
returns the redirected post vars, if any
Parameters
string $array which saved array to return from the redirected mem
protected
Returns
array
Definition at line 322 of file roxlayout.page.php.
References layoutkit.
PageWithRoxLayout::getStylesheetPatches () protected
Definition at line 72 of file roxlayout.page.php.
PageWithRoxLayout::getStylesheets () protected
Definition at line 16 of file roxlayout.page.php.
PageWithRoxLayout::getSubmenuActiveItem () protected
Definition at line 117 of file roxlayout.page.php.
Referenced by MemberPage\leftsidebar().
PageWithRoxLayout::getSubmenuItems () protected
Definition at line 113 of file roxlayout.page.php.
PageWithRoxLayout::getTopmenuActiveItem () protected
Definition at line 109 of file roxlayout.page.php.
Referenced by topmenu().
PageWithRoxLayout::getTopmenuItems () protected
Return a list of items to show in the sub menu. Each item is an array of keyword, url and translatable Word
Definition at line 83 of file roxlayout.page.php.
References $_SESSION, $items, $username, and MOD_bw_user_Auth\isBWLoggedIn().
Referenced by topmenu().
PageWithRoxLayout::init () protected
Definition at line 64 of file roxlayout.page.php.
PageWithRoxLayout::leftoverTranslationLinks () protected
Definition at line 257 of file roxlayout.page.php.
References RoxComponentBase\getWords().
PageWithRoxLayout::quicksearch () protected
A tiny wee quicksearch box
Definition at line 185 of file roxlayout.page.php.
References $_SESSION, $login_url, $request, $username, $words, MOD_online\get(), RoxComponentBase\getWords(), MOD_bw_user_Auth\isBWLoggedIn(), and TEMPLATE_DIR.
PageWithRoxLayout::SetMetaDescription ($ss)
Definition at line 59 of file roxlayout.page.php.
PageWithRoxLayout::SetMetaKey ($ss)
Definition at line 32 of file roxlayout.page.php.
References $words, and RoxComponentBase\getWords().
PageWithRoxLayout::SetMetaRobots ($ss)
Definition at line 46 of file roxlayout.page.php.
PageWithRoxLayout::submenu () protected
Definition at line 244 of file roxlayout.page.php.
References $words, RoxComponentBase\getWords(), and TEMPLATE_DIR.
PageWithRoxLayout::teaser () protected
Definition at line 233 of file roxlayout.page.php.
References TEMPLATE_DIR.
PageWithRoxLayout::teaserContent () protected
Definition at line 239 of file roxlayout.page.php.
References TEMPLATE_DIR.
PageWithRoxLayout::topmenu () protected
Definition at line 170 of file roxlayout.page.php.
References $_SESSION, $active_menu_item, $rights, $username, $words, getTopmenuActiveItem(), getTopmenuItems(), RoxComponentBase\getWords(), MOD_bw_user_Auth\isBWLoggedIn(), and TEMPLATE_DIR.
PageWithRoxLayout::topnav () protected
Definition at line 129 of file roxlayout.page.php.
References $_SESSION, $login_url, $request, $username, $words, MOD_online\get(), RoxComponentBase\getWords(), and TEMPLATE_DIR.
PageWithRoxLayout::volunteerMenu () protected
Definition at line 294 of file roxlayout.page.php.
References AbstractBasePage\createWidget().
Field Documentation
PageWithRoxLayout::$meta_description protected
Definition at line 9 of file roxlayout.page.php.
PageWithRoxLayout::$meta_keyword protected
Definition at line 10 of file roxlayout.page.php.
PageWithRoxLayout::$meta_robots protected
Definition at line 11 of file roxlayout.page.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/page/roxlayout.page.php