Rox: SimplePie_Source Class Reference
SimplePie_Source Class Reference
Public Member Functions
__construct ($item, $data)
set_registry (SimplePie_Registry $registry)
__toString ()
get_source_tags ($namespace, $tag)
get_base ($element=array())
sanitize ($data, $type, $base= '')
get_item ()
get_title ()
get_category ($key=0)
get_categories ()
get_author ($key=0)
get_authors ()
get_contributor ($key=0)
get_contributors ()
get_link ($key=0, $rel= 'alternate')
get_permalink ()
get_links ($rel= 'alternate')
get_description ()
get_copyright ()
get_language ()
get_latitude ()
get_longitude ()
get_image_url ()
Data Fields
$item
$data = array()
Protected Attributes
$registry
Detailed Description
Definition at line 55 of file Source.php.
Constructor & Destructor Documentation
SimplePie_Source::__construct ($item, $data)
Definition at line 61 of file Source.php.
References $data, and $item.
Member Function Documentation
SimplePie_Source::__toString ()
Definition at line 72 of file Source.php.
SimplePie_Source::get_author ($key = 0)
Definition at line 210 of file Source.php.
References get_authors().
SimplePie_Source::get_authors ()
Definition at line 223 of file Source.php.
References $name, $uri, $url, get_base(), get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_ITUNES.
Referenced by get_author().
SimplePie_Source::get_base ($element = array())
Definition at line 89 of file Source.php.
Referenced by get_authors(), get_contributors(), get_copyright(), get_description(), get_image_url(), get_links(), and get_title().
SimplePie_Source::get_categories ()
Definition at line 153 of file Source.php.
References $categories, get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_category().
SimplePie_Source::get_category ($key = 0)
Definition at line 140 of file Source.php.
References $categories, and get_categories().
SimplePie_Source::get_contributor ($key = 0)
Definition at line 293 of file Source.php.
References get_contributors().
SimplePie_Source::get_contributors ()
Definition at line 306 of file Source.php.
References $name, $uri, $url, get_base(), get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, and SIMPLEPIE_NAMESPACE_ATOM_10.
Referenced by get_contributor().
SimplePie_Source::get_copyright ()
Definition at line 503 of file Source.php.
References elseif, get_base(), get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie_Source::get_description ()
Definition at line 459 of file Source.php.
References elseif, get_base(), get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie_Source::get_image_url ()
Definition at line 591 of file Source.php.
References elseif, get_base(), get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_NAMESPACE_ATOM_10, and SIMPLEPIE_NAMESPACE_ITUNES.
SimplePie_Source::get_item ()
Definition at line 99 of file Source.php.
References $item.
SimplePie_Source::get_language ()
Definition at line 531 of file Source.php.
References elseif, get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie_Source::get_latitude ()
Definition at line 555 of file Source.php.
References elseif, get_source_tags(), SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
SimplePie_Source::get_link ($key = 0, $rel = 'alternate')
Definition at line 364 of file Source.php.
References get_links().
Referenced by get_permalink().
SimplePie_Source::get_links ($rel = 'alternate')
Definition at line 385 of file Source.php.
References $link, elseif, get_base(), get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_IANA_LINK_RELATIONS_REGISTRY, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_link().
SimplePie_Source::get_longitude ()
Definition at line 571 of file Source.php.
References elseif, get_source_tags(), SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
SimplePie_Source::get_permalink ()
Added for parity between the parent-level and the item/entry-level.
Definition at line 380 of file Source.php.
References get_link().
SimplePie_Source::get_source_tags ($namespace, $tag)
Definition at line 77 of file Source.php.
Referenced by get_authors(), get_categories(), get_contributors(), get_copyright(), get_description(), get_image_url(), get_language(), get_latitude(), get_links(), get_longitude(), and get_title().
SimplePie_Source::get_title ()
Definition at line 104 of file Source.php.
References elseif, get_base(), get_source_tags(), sanitize(), SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
SimplePie_Source::sanitize ($data, $type, $base = '')
Definition at line 94 of file Source.php.
References $data, and $type.
Referenced by get_authors(), get_categories(), get_contributors(), get_copyright(), get_description(), get_image_url(), get_language(), get_links(), and get_title().
SimplePie_Source::set_registry (SimplePie_Registry $registry)
Definition at line 67 of file Source.php.
References $registry.
Field Documentation
SimplePie_Source::$data = array()
Definition at line 58 of file Source.php.
Referenced by __construct(), and sanitize().
SimplePie_Source::$item
Definition at line 57 of file Source.php.
Referenced by __construct(), and get_item().
SimplePie_Source::$registry protected
Definition at line 59 of file Source.php.
Referenced by set_registry().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/templates/simplepie/library/SimplePie/Source.php