Rox: ForumsView Class Reference
ForumsView Class Reference
Public Member Functions
__construct (Forums &$model)
SetPageTitle ($Title)
createTopic (&$callbackId, $IdGroup=0)
getURI ()
threadURL ($thread, $baseurl=false)
postURL ($post, $baseurl=false)
replyTopic (&$callbackId)
editPost (&$callbackId, $translate=false)
ModeditPost (&$callbackId)
showTopic ()
showModeratorEditPost (&$callbackId, $DataPost)
showReportPost (&$callbackId, $DataPost)
showReportList (&$callbackId, $DataPost)
showModeratorEditTag (&$callbackId, $DataTag)
showExternal ($showGroups=false, $showsticky=true, $showNewTopicButton=true)
teaser ()
userBar ()
showCategoriesContinentsTagcloud ()
rules ()
customStyles ()
topMenu ($currentTab)
showForum ()
showTopLevelLandingPage ($ownGroupsButtonCallbackId=false, $moreLessThreadsCallbackId=false)
showTopLevelRecentPosts ($ownGroupsButtonCallbackId=false, $noForumNewTopicButton=false)
showTopLevelCategories ()
displaySearchResultSubscriptions ($TResults)
displaySearchResultPosts ($posts)
SubscribeTag ($res)
SubscribeThread ($res)
Unsubscribe ($res)
generateClickableTagSuggestions ($tags)
getLocationDropdowns ()
showFeatureIsClosed ()
Public Member Functions inherited from RoxAppView
getAsString ($methodname)
Data Fields
$page
$uri
$forum_uri
$BW_Right
Detailed Description
Definition at line 12 of file forums.view.php.
Constructor & Destructor Documentation
ForumsView::__construct (Forums & $model)
Definition at line 20 of file forums.view.php.
References $model, getURI(), and words.
Member Function Documentation
ForumsView::createTopic (& $callbackId, $IdGroup = 0)
Create a new topic in the current forum
Definition at line 37 of file forums.view.php.
References $tags, and getLocationDropdowns().
ForumsView::customStyles ()
Definition at line 314 of file forums.view.php.
ForumsView::displaySearchResultPosts ($posts)
Definition at line 425 of file forums.view.php.
ForumsView::displaySearchResultSubscriptions ($TResults)
Definition at line 422 of file forums.view.php.
ForumsView::editPost (& $callbackId, $translate = false)
Definition at line 126 of file forums.view.php.
References $_SESSION, $callbackId, $vars, and getLocationDropdowns().
ForumsView::generateClickableTagSuggestions ($tags)
Definition at line 479 of file forums.view.php.
References $tags, and n.
ForumsView::getLocationDropdowns ()
Definition at line 689 of file forums.view.php.
Referenced by createTopic(), editPost(), and ModeditPost().
ForumsView::getURI ()
Definition at line 57 of file forums.view.php.
References $forum_uri.
Referenced by __construct().
ForumsView::ModeditPost (& $callbackId)
Definition at line 162 of file forums.view.php.
References $_SESSION, $callbackId, $vars, and getLocationDropdowns().
ForumsView::postURL ($post, $baseurl = false)
Definition at line 77 of file forums.view.php.
References $uri, and words.
ForumsView::replyTopic (& $callbackId)
Definition at line 86 of file forums.view.php.
References $_SESSION.
ForumsView::rules ()
Definition at line 310 of file forums.view.php.
ForumsView::SetPageTitle ($Title)
Definition at line 30 of file forums.view.php.
Referenced by showForum(), showModeratorEditPost(), showModeratorEditTag(), showReportList(), showReportPost(), showTopic(), showTopLevelCategories(), showTopLevelLandingPage(), and showTopLevelRecentPosts().
ForumsView::showCategoriesContinentsTagcloud ()
Definition at line 303 of file forums.view.php.
ForumsView::showExternal ($showGroups = false, $showsticky = true, $showNewTopicButton = true)
Display thread teasers externally
Parameters
bool $showGroups Set true if group name and link should be shown in teasers
Definition at line 280 of file forums.view.php.
References $request.
ForumsView::showFeatureIsClosed ()
Definition at line 712 of file forums.view.php.
ForumsView::showForum ()
Definition at line 326 of file forums.view.php.
References $currentPage, $max, $maxPage, $pages, $request, $uri, SetPageTitle(), and words.
ForumsView::showModeratorEditPost (& $callbackId, $DataPost)
Display the form for a Moderator edit This is the form with the list of all available translations for a given post
Definition at line 242 of file forums.view.php.
References $callbackId, $vars, and SetPageTitle().
ForumsView::showModeratorEditTag (& $callbackId, $DataTag)
Display the form for a Moderator edit
Definition at line 267 of file forums.view.php.
References $callbackId, $vars, and SetPageTitle().
ForumsView::showReportList (& $callbackId, $DataPost)
Definition at line 257 of file forums.view.php.
References $callbackId, $vars, and SetPageTitle().
ForumsView::showReportPost (& $callbackId, $DataPost)
Definition at line 250 of file forums.view.php.
References $callbackId, $vars, and SetPageTitle().
ForumsView::showTopic ()
Display a topic
Definition at line 187 of file forums.view.php.
References $_SESSION, $currentPage, $group_id, $ii, $max, $maxPage, $pages, $request, $uri, SetPageTitle(), and words.
ForumsView::showTopLevelCategories ()
Definition at line 404 of file forums.view.php.
References $currentPage, $max, $maxPage, $pages, $request, SetPageTitle(), and words.
ForumsView::showTopLevelLandingPage ($ownGroupsButtonCallbackId = false, $moreLessThreadsCallbackId = false)
Definition at line 345 of file forums.view.php.
References $groups, $pages, $request, SetPageTitle(), and words.
ForumsView::showTopLevelRecentPosts ($ownGroupsButtonCallbackId = false, $noForumNewTopicButton = false)
Definition at line 382 of file forums.view.php.
References $currentPage, $max, $maxPage, $pages, $request, SetPageTitle(), and words.
ForumsView::SubscribeTag ($res)
Definition at line 430 of file forums.view.php.
ForumsView::SubscribeThread ($res)
Definition at line 434 of file forums.view.php.
ForumsView::teaser ()
Display a forum
Definition at line 291 of file forums.view.php.
References $request.
ForumsView::threadURL ($thread, $baseurl = false)
returns a good-looking url for a forum thread // TODO: maybe there's a better place for this.
Parameters
$thread as read from the threads database with mysql_fetch_object
Returns
string to be used as url
Definition at line 69 of file forums.view.php.
References $uri, and words.
ForumsView::topMenu ($currentTab)
Definition at line 320 of file forums.view.php.
References TEMPLATE_DIR.
ForumsView::Unsubscribe ($res)
Definition at line 438 of file forums.view.php.
ForumsView::userBar ()
Definition at line 297 of file forums.view.php.
References $_SESSION.
Field Documentation
ForumsView::$BW_Right
Definition at line 18 of file forums.view.php.
ForumsView::$forum_uri
Definition at line 17 of file forums.view.php.
Referenced by getURI().
ForumsView::$page
Definition at line 14 of file forums.view.php.
ForumsView::$uri
Definition at line 16 of file forums.view.php.
Referenced by postURL(), showForum(), showTopic(), and threadURL().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/forums/forums.view.php