Rox: SimplePie_Locator Class Reference
SimplePie_Locator Class Reference
Public Member Functions
__construct (SimplePie_File $file, $timeout=10, $useragent=null, $max_checked_feeds=10)
set_registry (SimplePie_Registry $registry)
find ($type=SIMPLEPIE_LOCATOR_ALL, &$working)
is_feed ($file)
get_base ()
autodiscovery ()
get_links ()
extension (&$array)
body (&$array)
Data Fields
$useragent
$timeout
$file
$local = array()
$elsewhere = array()
$cached_entities = array()
$http_base
$base
$base_location = 0
$checked_feeds = 0
$max_checked_feeds = 10
Protected Member Functions
search_elements_by_tag ($name, &$done, $feeds)
Protected Attributes
$registry
Detailed Description
Definition at line 53 of file Locator.php.
Constructor & Destructor Documentation
SimplePie_Locator::__construct (SimplePie_File $file, $timeout = 10, $useragent = null, $max_checked_feeds = 10)
Definition at line 68 of file Locator.php.
References $file, $max_checked_feeds, $timeout, and $useragent.
Member Function Documentation
SimplePie_Locator::autodiscovery ()
Definition at line 179 of file Locator.php.
References search_elements_by_tag().
Referenced by find().
SimplePie_Locator::body (& $array)
Definition at line 310 of file Locator.php.
References $feed, $value, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by find().
SimplePie_Locator::extension (& $array)
Definition at line 281 of file Locator.php.
References $feed, $value, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by find().
SimplePie_Locator::find ($type = SIMPLEPIE_LOCATOR_ALL, & $working)
Definition at line 87 of file Locator.php.
References $file, $type, autodiscovery(), body(), extension(), get_base(), get_links(), is_feed(), SIMPLEPIE_FILE_SOURCE_REMOTE, SIMPLEPIE_LOCATOR_AUTODISCOVERY, SIMPLEPIE_LOCATOR_LOCAL_BODY, SIMPLEPIE_LOCATOR_LOCAL_EXTENSION, SIMPLEPIE_LOCATOR_NONE, SIMPLEPIE_LOCATOR_REMOTE_BODY, and SIMPLEPIE_LOCATOR_REMOTE_EXTENSION.
SimplePie_Locator::get_base ()
Definition at line 163 of file Locator.php.
References $http_base.
Referenced by find().
SimplePie_Locator::get_links ()
Definition at line 239 of file Locator.php.
References $link.
Referenced by find().
SimplePie_Locator::is_feed ($file)
Definition at line 138 of file Locator.php.
References $file, elseif, SIMPLEPIE_FILE_SOURCE_LOCAL, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by find().
SimplePie_Locator::search_elements_by_tag ($name, & $done, $feeds) protected
Definition at line 197 of file Locator.php.
References $feed, $link, $name, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by autodiscovery().
SimplePie_Locator::set_registry (SimplePie_Registry $registry)
Definition at line 82 of file Locator.php.
References $registry.
Field Documentation
SimplePie_Locator::$base
Definition at line 62 of file Locator.php.
SimplePie_Locator::$base_location = 0
Definition at line 63 of file Locator.php.
SimplePie_Locator::$cached_entities = array()
Definition at line 60 of file Locator.php.
SimplePie_Locator::$checked_feeds = 0
Definition at line 64 of file Locator.php.
SimplePie_Locator::$elsewhere = array()
Definition at line 59 of file Locator.php.
SimplePie_Locator::$file
Definition at line 57 of file Locator.php.
Referenced by __construct(), find(), and is_feed().
SimplePie_Locator::$http_base
Definition at line 61 of file Locator.php.
Referenced by get_base().
SimplePie_Locator::$local = array()
Definition at line 58 of file Locator.php.
SimplePie_Locator::$max_checked_feeds = 10
Definition at line 65 of file Locator.php.
Referenced by __construct().
SimplePie_Locator::$registry protected
Definition at line 66 of file Locator.php.
Referenced by set_registry().
SimplePie_Locator::$timeout
Definition at line 56 of file Locator.php.
Referenced by __construct().
SimplePie_Locator::$useragent
Definition at line 55 of file Locator.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/templates/simplepie/library/SimplePie/Locator.php