Rox: EnvironmentExplorer Class Reference
EnvironmentExplorer Class Reference
Public Member Functions
initializeGlobalState ()
loadBaseXML ()
Protected Member Functions
simulateMissingFunctions ()
checkEnvironment ()
loadSettings ()
loadConfiguration ()
loadDefaults ($xpath, $settings)
loadPTClasses ($Classes)
fillSessionWithValues ()
loadPModules ($class_loader)
loadPApps ($class_loader)
initSession ($settings)
loadRoxClasses ($class_loader)
Member Function Documentation
EnvironmentExplorer::checkEnvironment () protected
this is called at some point to check some environment stuff.
Referenced by initializeGlobalState().
EnvironmentExplorer::fillSessionWithValues () protected
some fields in the $_SESSION need to be filled with default values, if they are empty.
EnvironmentExplorer::initializeGlobalState ()
References checkEnvironment(), initSession(), loadBaseXML(), loadConfiguration(), loadDefaults(), loadPApps(), loadPModules(), loadPTClasses(), loadRoxClasses(), Classes\set(), AutoloadPlug\setCallback(), and simulateMissingFunctions().
Referenced by RoxLauncher\initializeGlobalState().
EnvironmentExplorer::initSession ($settings) protected
do some things which are necessary to start using the $_SESSION
Referenced by initializeGlobalState().
EnvironmentExplorer::loadBaseXML ()
References $B, $build, $buildDir, $datadir, $is, $libdir, $template, $templateDir, and $version.
Referenced by initializeGlobalState().
EnvironmentExplorer::loadConfiguration () protected
we override the parent method that would only load the inc/config.inc.php we get the information from ini files instead. if required ini files are missing, they can be created automatically from inc/config.inc.php if there is no inc/config.inc.php either, a warning is shown.
Referenced by initializeGlobalState().
EnvironmentExplorer::loadDefaults ($xpath, $settings) protected
again, PT needs it.
References $build, $debug, $susp, and BUILD_DIR.
Referenced by initializeGlobalState().
EnvironmentExplorer::loadPApps ($class_loader) protected
Referenced by initializeGlobalState().
EnvironmentExplorer::loadPModules ($class_loader) protected
Referenced by initializeGlobalState().
EnvironmentExplorer::loadPTClasses ($Classes) protected
Referenced by initializeGlobalState().
EnvironmentExplorer::loadRoxClasses ($class_loader) protected
References $_SESSION.
Referenced by initializeGlobalState().
EnvironmentExplorer::loadSettings () protected
EnvironmentExplorer::simulateMissingFunctions () protected
some native PHP functions could be missing, if they require a newer PHP version.
Referenced by initializeGlobalState().
The documentation for this class was generated from the following file:
environmentexplorer.php