Rox: ActivitiesModel Class Reference
ActivitiesModel Class Reference
Public Member Functions
__construct ()
getUpcomingActivitiesCount ($onlyPublic)
getUpcomingActivities ($onlyPublic, $pageno, $items)
getMyActivitiesCount ()
getMyActivities ($pageno, $items)
getPastActivitiesCount ($onlyPublic)
getPastActivities ($onlyPublic, $pageno, $items)
setRadius ($args)
getRadius ()
getActivitiesNearMeCount ($distance)
getActivitiesNearMe ($distance, $pageno, $items)
searchActivitiesCount ($onlyPublic, $keyword)
searchActivities ($onlyPublic, $keyword, $pageno, $items)
checkEditCreateActivityVarsOk ($args)
checkJoinLeaveActivityVarsOk ($args)
joinLeaveActivity ($post)
cancelUncancelActivity ($post)
createActivity ($args)
updateActivity ($args)
checkSearchActivitiesVarsOk ($args)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const ACTIVITY_ADDRESS_LIMIT = 320
const ACTIVITY_DESCRIPTION_LIMIT = 65535
Protected Member Functions
getUpcomingQuery ($onlyPublic)
getPastQuery ($onlyPublic)
getNearMeQuery ($distance, $count=false)
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Additional Inherited Members
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Activities model class.
Author
shevek
Definition at line 7 of file activities.model.php.
Constructor & Destructor Documentation
ActivitiesModel::__construct ()
Default constructor.
Definition at line 16 of file activities.model.php.
Member Function Documentation
ActivitiesModel::cancelUncancelActivity ($post)
Definition at line 305 of file activities.model.php.
ActivitiesModel::checkEditCreateActivityVarsOk ($args)
checks if the entered data on the activity-create-form is correct
There is one situation however where we can't determine if the form data is correct This occurs when the user selects a location that isn't yet in the geonames_cache table As the location will only be added after the form is validated there is no way to check if the content of activity-location and activity-location-id match.
To ensure that the user at least used the search button to set the activity-location-id one check is added. If activity-location-id is still 0, the content of activity-location must match the city of the member.
Returns
array with the found problems
Definition at line 190 of file activities.model.php.
References $errors, and RoxModelBase\getLoggedInMember().
ActivitiesModel::checkJoinLeaveActivityVarsOk ($args)
Definition at line 242 of file activities.model.php.
References $errors, and $status.
ActivitiesModel::checkSearchActivitiesVarsOk ($args)
Definition at line 384 of file activities.model.php.
References $errors.
ActivitiesModel::createActivity ($args)
Definition at line 334 of file activities.model.php.
ActivitiesModel::getActivitiesNearMe ($distance, $pageno, $items)
Definition at line 157 of file activities.model.php.
References $distance, $items, $query, and getNearMeQuery().
ActivitiesModel::getActivitiesNearMeCount ($distance)
Definition at line 147 of file activities.model.php.
References $distance, $query, and getNearMeQuery().
ActivitiesModel::getMyActivities ($pageno, $items)
Definition at line 49 of file activities.model.php.
References $items, and RoxModelBase\getLoggedInMember().
ActivitiesModel::getMyActivitiesCount ()
Definition at line 44 of file activities.model.php.
References RoxModelBase\getLoggedInMember().
ActivitiesModel::getNearMeQuery ($distance, $count = false) protected
Definition at line 102 of file activities.model.php.
References $count, $distance, $loggedInMember, $query, and RoxModelBase\getLoggedInMember().
Referenced by getActivitiesNearMe(), and getActivitiesNearMeCount().
ActivitiesModel::getPastActivities ($onlyPublic, $pageno, $items)
Definition at line 69 of file activities.model.php.
References $items, and getPastQuery().
ActivitiesModel::getPastActivitiesCount ($onlyPublic)
Definition at line 63 of file activities.model.php.
References $count, and getPastQuery().
ActivitiesModel::getPastQuery ($onlyPublic) protected
Definition at line 54 of file activities.model.php.
Referenced by getPastActivities(), and getPastActivitiesCount().
ActivitiesModel::getRadius ()
Definition at line 97 of file activities.model.php.
References $layoutbits.
ActivitiesModel::getUpcomingActivities ($onlyPublic, $pageno, $items)
Definition at line 36 of file activities.model.php.
References $items, $query, and getUpcomingQuery().
ActivitiesModel::getUpcomingActivitiesCount ($onlyPublic)
Definition at line 30 of file activities.model.php.
References $count, and getUpcomingQuery().
ActivitiesModel::getUpcomingQuery ($onlyPublic) protected
Definition at line 20 of file activities.model.php.
Referenced by getUpcomingActivities(), and getUpcomingActivitiesCount().
ActivitiesModel::joinLeaveActivity ($post)
Definition at line 269 of file activities.model.php.
References $query, $status, and RoxModelBase\getLoggedInMember().
ActivitiesModel::searchActivities ($onlyPublic, $keyword, $pageno, $items)
Definition at line 171 of file activities.model.php.
References $items.
ActivitiesModel::searchActivitiesCount ($onlyPublic, $keyword)
Definition at line 166 of file activities.model.php.
ActivitiesModel::setRadius ($args)
Definition at line 76 of file activities.model.php.
References $query, and RoxModelBase\getLoggedInMember().
ActivitiesModel::updateActivity ($args)
Definition at line 361 of file activities.model.php.
References RoxModelBase\getLoggedInMember().
Field Documentation
const ActivitiesModel::ACTIVITY_ADDRESS_LIMIT = 320
Definition at line 10 of file activities.model.php.
const ActivitiesModel::ACTIVITY_DESCRIPTION_LIMIT = 65535
Definition at line 11 of file activities.model.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/activities/activities.model.php