Rox: GroupsModel Class Reference
GroupsModel Class Reference
Public Member Functions
__construct ()
findGroup ($groupId)
inviteMember ($group, $memberId)
findMembersByName ($group, $name)
countGroupsBySearchterms ($terms)
findGroups ($terms= '', $page=1, $order= '', $amount=10)
findAllGroups ($offset=0, $limit=0)
countMyGroups ()
getMembershipStatus (Group $group, $memberid)
getMyGroups ()
getGroupsForMember ($memberId)
setGroupVisit ($groupId)
getLastVisited ()
createGroup ($input)
updateMembershipSettings ($memberId, $groupId, $acceptgroupmail, $comment)
canAccessGroupAdmin ($group)
canAccessGroupDelete ($group)
joinGroup ($member, $group)
leaveGroup ($member, $group)
deleteGroup ($group)
updateGroupSettings ($group, $description, $type, $visible_posts, $visible_comments)
thumbImg ($id)
realImg ($id)
banGroupMember ($group, $memberId, $ban=false)
addGroupMemberAsAdmin ($group, $memberId)
resignGroupAdmin ($group, $memberId)
acceptGroupMember ($group, $memberId, $acceptedbyId)
sendInvitation ($group, $memberId, $from)
memberAcceptedInvitation ($group, $memberId)
memberDeclinedInvitation ($group, $memberId)
notifyGroupAdmins ($group, $member)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 34 of file groups.model.php.
Constructor & Destructor Documentation
GroupsModel::__construct ()
Definition at line 38 of file groups.model.php.
Member Function Documentation
GroupsModel::acceptGroupMember ($group, $memberId, $acceptedbyId)
accepts a member into a group
Parameters
object $group - group entity
int $memberId
Returns
bool public
Definition at line 736 of file groups.model.php.
References $member, $note, and RoxModelBase\createEntity().
GroupsModel::addGroupMemberAsAdmin ($group, $memberId)
adds a member as admin of the group
Parameters
object $group - group entity
int $memberId
Returns
bool public
Definition at line 691 of file groups.model.php.
References $member, and RoxModelBase\createEntity().
GroupsModel::banGroupMember ($group, $memberId, $ban = false)
bans a member from a group
Parameters
object $group - group entity
int $memberId
Returns
bool public
Definition at line 655 of file groups.model.php.
References $member, $rights, and RoxModelBase\createEntity().
GroupsModel::canAccessGroupAdmin ($group)
checks if a the current logged member can access the groups admin page
Parameters
object $group - group entity public
Returns
bool
Definition at line 424 of file groups.model.php.
References RoxModelBase\getLoggedInMember().
GroupsModel::canAccessGroupDelete ($group)
checks if a the current logged member can delete groups
Parameters
object $group - group entity public
Returns
bool
Definition at line 445 of file groups.model.php.
References RoxModelBase\getLoggedInMember().
GroupsModel::countGroupsBySearchterms ($terms)
returns count of groups that match the provided term(s)
Parameters
array $terms public
Returns
int
Definition at line 115 of file groups.model.php.
References RoxModelBase\createEntity().
GroupsModel::countMyGroups ()
returns a count of how many groups a member is in
public
Returns
int
Definition at line 216 of file groups.model.php.
References RoxModelBase\createEntity().
GroupsModel::createGroup ($input)
handles input checking for group creation
Parameters
array $input - Post vars public
Returns
array
Definition at line 326 of file groups.model.php.
References $problems, RoxModelBase\createEntity(), and RoxModelBase\getLoggedInMember().
GroupsModel::deleteGroup ($group)
handles deleting groups
Parameters
object $group - group entity to be deleted
Returns
bool public
Definition at line 521 of file groups.model.php.
GroupsModel::findAllGroups ($offset = 0, $limit = 0)
Find all groups
public
Returns
array Returns an array of Group entity objects
Definition at line 198 of file groups.model.php.
References RoxModelBase\createEntity().
GroupsModel::findGroup ($groupId)
Find and return one group, using id
Parameters
int $groupId
Returns
mixed false or a Group entity
Definition at line 49 of file groups.model.php.
References RoxModelBase\createEntity().
Referenced by getLastVisited().
GroupsModel::findGroups ($terms = '', $page = 1, $order = '', $amount = 10)
Find and return groups, using search terms from search page
Parameters
string $terms - search terms
int $page - offset to start from
string $order - sortorder
int $amount how many results to find
Returns
mixed false or an array of Groups
Definition at line 142 of file groups.model.php.
References $order, and RoxModelBase\createEntity().
GroupsModel::findMembersByName ($group, $name)
searches for members, using username if group is provided, any members found that are in that group will not be returned
Parameters
string $name public
Returns
array
Definition at line 89 of file groups.model.php.
References $member, $members, $name, and RoxModelBase\createEntity().
GroupsModel::getGroupsForMember ($memberId)
Find all groups $memberId is member of
public
Returns
mixed Returns an array of Group entity objects or false if you're not logged in
Definition at line 267 of file groups.model.php.
References $member, and RoxModelBase\createEntity().
Referenced by getMyGroups().
GroupsModel::getLastVisited ()
Definition at line 302 of file groups.model.php.
References $_SESSION, $groups, $id, and findGroup().
GroupsModel::getMembershipStatus (Group $group, $memberid)
returns the status of a membership
public
Returns
string
Definition at line 228 of file groups.model.php.
References $status.
GroupsModel::getMyGroups ()
Find all groups I am member of
public
Returns
mixed Returns an array of Group entity objects or false if you're not logged in
Definition at line 249 of file groups.model.php.
References $_SESSION, and getGroupsForMember().
GroupsModel::inviteMember ($group, $memberId)
creates a membership for a member and sets the status to invited
Parameters
object $group - Group entity
int $memberId - id of member to invite public
Returns
bool
Definition at line 70 of file groups.model.php.
References $member, and RoxModelBase\createEntity().
GroupsModel::joinGroup ($member, $group)
handles a user joining a group
Parameters
object $member - member entity of the user joining
object $group - group entity for the group joined
Returns
bool public
Definition at line 468 of file groups.model.php.
References $member, $status, RoxModelBase\createEntity(), elseif, and notifyGroupAdmins().
GroupsModel::leaveGroup ($member, $group)
handles a user leaving a group
Parameters
object $member - member entity of the user joining
object $group - group entity for the group joined
Returns
bool public
Definition at line 499 of file groups.model.php.
References $member, and RoxModelBase\createEntity().
GroupsModel::memberAcceptedInvitation ($group, $memberId)
changes a membership from invited to in
Parameters
object $group
int $memberId public
Returns
bool
Definition at line 808 of file groups.model.php.
References $member, RoxModelBase\createEntity(), and RoxModelBase\getLoggedInMember().
GroupsModel::memberDeclinedInvitation ($group, $memberId)
deletes a membership
Parameters
object $group
int $memberId public
Returns
bool
Definition at line 832 of file groups.model.php.
References $member, RoxModelBase\createEntity(), and RoxModelBase\getLoggedInMember().
GroupsModel::notifyGroupAdmins ($group, $member)
creates a message for the group admins, that a new member wants to join
Parameters
object $group
object $member - member entity public
Definition at line 856 of file groups.model.php.
References $member, $url, $words, RoxModelBase\createEntity(), and RoxComponentBase\getWords().
Referenced by joinGroup().
GroupsModel::realImg ($id)
sends headers, reads out an image and then exits
Parameters
int $id - id of group to get thumbnail for public
Definition at line 627 of file groups.model.php.
References $id, and RoxModelBase\createEntity().
GroupsModel::resignGroupAdmin ($group, $memberId)
resigns as admin of the group
Parameters
object $group - group entity
int $memberId
Returns
bool public
Definition at line 710 of file groups.model.php.
References $member, $rights, RoxModelBase\createEntity(), and RoxModelBase\getLoggedInMember().
GroupsModel::sendInvitation ($group, $memberId, $from)
creates a message for the invited member
Parameters
object $group
int $memberId
object $from - member entity public
Definition at line 768 of file groups.model.php.
References $member, $note, $url, $words, RoxModelBase\createEntity(), and RoxComponentBase\getWords().
GroupsModel::setGroupVisit ($groupId)
remember the last visited groups, so
Parameters
int $now_groupId id of the group you are visiting now
Definition at line 285 of file groups.model.php.
References $_SESSION.
GroupsModel::thumbImg ($id)
sends headers, reads out a thumbnail image and then exits
Parameters
int $id - id of group to get thumbnail for public
Definition at line 601 of file groups.model.php.
References $id, and RoxModelBase\createEntity().
GroupsModel::updateGroupSettings ($group, $description, $type, $visible_posts, $visible_comments)
update group settings for a given group
Parameters
object $group - group entity
string $description - description of the group
string $type - how public the group is
string $visible_posts - if the posts of the group should be visible or not
Returns
bool public
Definition at line 540 of file groups.model.php.
References $description, and $type.
GroupsModel::updateMembershipSettings ($memberId, $groupId, $acceptgroupmail, $comment)
update membership settings for a given member and group
Parameters
int $memberId
int $groupId
string $acceptgroupmail
string $comment
Returns
bool public
Definition at line 405 of file groups.model.php.
References $comment, $member, and RoxModelBase\createEntity().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/groups/groups.model.php