Rox: MOD_user_Auth Class Reference
MOD_user_Auth Class Reference
Public Member Functions
__construct ($sessionName=false, $tableName=false, $authId=false)
addGroup ($group)
addGroupRight ($group, $right)
addImplication ($right, $implies)
appExists ($appName)
checkAuth ($authName)
checkRight ($right, $level=0)
groupExists ($group)
hasRight ($right)
rightExists ($right)
getAuth ()
logout ()
Static Public Member Functions
static passwordEncrypt ($password)
static randomString ($len)
static getTranslations ($idMember)
static getImage ($paramIdMember=0)
static getDummyImage ($Gender='IDontTell', $HideGender='Yes')
Protected Member Functions
addApp ($name)
setAuth ($authId)
doLogin ($handle, $pw)
doBWLogin ($handle)
getAuthId ($userId)
Protected Attributes
$authId
$sessionName
$tableName
$dao
Constructor & Destructor Documentation
MOD_user_Auth::__construct ($sessionName = false, $tableName = false, $authId = false)
Parameters
string $sessionName The session key under which the user id may be found
string $tableName The user table name
int $authId The authentication id
References MOD_user\$authId, MOD_user\$sessionName, and MOD_user\$tableName.
Member Function Documentation
MOD_user_Auth::addApp ($name) protected
add a new application with given name
Parameters
string $name
Returns
int application ID
References $name, $query, and appExists().
Referenced by checkRight().
MOD_user_Auth::addGroup ($group)
add a new group with given name
Parameters
string $group
Returns
int group ID
MOD_user_Auth::addGroupRight ($group, $right)
adds a right to a group
if either is not set, this method will create group and right
Parameters
string $group group name
string $right right name
Returns
boolean
MOD_user_Auth::addImplication ($right, $implies)
adds an implication for given right
Parameters
string $right right name, which implies
string $implies right name for right to imply
Returns
boolean
MOD_user_Auth::appExists ($appName)
returns the id if app exists or false
Parameters
string $appName
Returns
mixed
Referenced by addApp().
MOD_user_Auth::checkAuth ($authName)
check if given auth name exists, creates if it does not
Parameters
string $authName
Returns
mixed id or false
References $id, $query, and PException\addInfo().
Referenced by User\registerProcess().
MOD_user_Auth::checkRight ($right, $level = 0)
checks if right exists
Parameters
string $right right name
int $level level
Returns
mixed id or false
References $query, $right, addApp(), and rightExists().
Referenced by hasRight().
MOD_user::doBWLogin ($handle) protected inherited
References $_SESSION, $d, MOD_user\$sessionName, and MOD_user\setAuth().
Referenced by MOD_bw_user_Auth\doLogin().
MOD_user::doLogin ($handle, $pw) protected inherited
References $_SESSION, $d, $matches, MOD_user\$sessionName, elseif, and MOD_user\setAuth().
MOD_user::getAuth () inherited
Referenced by MOD_user\hasRight().
MOD_user::getAuthId ($userId) protected inherited
References MOD_user\$authId, and $d.
static MOD_user::getDummyImage ($Gender = 'IDontTell', $HideGender = 'Yes') static inherited
Returns the path to an appropriate dummy image in case no image is found.
Parameters
unknown_type $Gender
unknown_type $HideGender
Returns
unknown
static MOD_user::getImage ($paramIdMember = 0) static inherited
References $_SESSION, and MOD_user\$dao.
static MOD_user::getTranslations ($idMember) static inherited
References MOD_user\$dao.
MOD_user_Auth::groupExists ($group)
checks if group exists
Parameters
string $group
Returns
mixed id or false
MOD_user_Auth::hasRight ($right)
checks if current user has given right
Parameters
string $right
Returns
boolean
References $query, $right, checkRight(), and debug.
MOD_user::logout () inherited
References $_SESSION.
static MOD_user::passwordEncrypt ($password) static inherited
Referenced by User\registerProcess(), and MOD_bw_user_Auth\updateUser().
static MOD_user::randomString ($len) static inherited
References $i.
MOD_user_Auth::rightExists ($right)
checks if given right exists
Parameters
string $right
Returns
mixed id or false
References $query, $right, a, id, and r.
Referenced by checkRight().
MOD_user::setAuth ($authId) protected inherited
References MOD_user\$authId.
Referenced by MOD_user\doBWLogin(), and MOD_user\doLogin().
Field Documentation
MOD_user::$authId protected inherited
Referenced by __construct(), MOD_bw_user_Auth\__construct(), MOD_user\getAuthId(), MOD_user\setAuth(), and MOD_bw_user_Auth\updateUser().
MOD_user::$dao protected inherited
Referenced by MOD_user\__construct(), MOD_user\getImage(), and MOD_user\getTranslations().
MOD_user::$sessionName protected inherited
Referenced by MOD_user\__construct(), __construct(), MOD_bw_user_Auth\__construct(), MOD_user\doBWLogin(), and MOD_user\doLogin().
MOD_user::$tableName protected inherited
Referenced by MOD_user\__construct(), __construct(), and MOD_bw_user_Auth\__construct().
The documentation for this class was generated from the following file:
auth.lib.php