Rox: VerifymembersController Class Reference
VerifymembersController Class Reference
Public Member Functions
__construct ()
index ($args=false)
checkPasswordCallback ($args, $action, $mem_redirect, $mem_resend)
verifyCallback ($args, $action, $mem_redirect, $mem_resend)
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
getMember ($cid)
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 12 of file verifymembers.ctrl.php.
Constructor & Destructor Documentation
VerifymembersController::__construct ()
Definition at line 15 of file verifymembers.ctrl.php.
References model.
Member Function Documentation
VerifymembersController::checkPasswordCallback ($args, $action, $mem_redirect, $mem_resend)
handles edit profile form post - profile updating
Parameters
object $args
object $action
object $mem_redirect
object $mem_resend public
Returns
string
Definition at line 123 of file verifymembers.ctrl.php.
References $errors, $mem_redirect, $request, $vars, RoxControllerBase\cleanVars(), and model.
VerifymembersController::getMember ($cid) protected
Definition at line 101 of file verifymembers.ctrl.php.
References $model.
Referenced by index().
VerifymembersController::index ($args = false)
decide which page to show. This method is called automatically
Definition at line 25 of file verifymembers.ctrl.php.
References $_SESSION, $mem_redirect, $model, $request, break, elseif, getMember(), model, and RoxControllerBase\redirect().
VerifymembersController::verifyCallback ($args, $action, $mem_redirect, $mem_resend)
handles verification form post
Parameters
object $args
object $action
object $mem_redirect
object $mem_resend public
Returns
string
Definition at line 165 of file verifymembers.ctrl.php.
References $errors, $mem_redirect, $request, $vars, RoxControllerBase\cleanVars(), and model.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/verifymembers/verifymembers.ctrl.php