Rox: NotifyController Class Reference
NotifyController Class Reference
Public Member Functions
__construct ()
__destruct ()
index ()
NotifyAdminCallback ($args, $action, $mem_redirect, $mem_resend)
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
getPageNumber ($request, $req_index)
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
This controller is called when the request is 'groups/...'
Definition at line 6 of file notify.ctrl.php.
Constructor & Destructor Documentation
NotifyController::__construct ()
Definition at line 9 of file notify.ctrl.php.
NotifyController::__destruct ()
Definition at line 15 of file notify.ctrl.php.
Member Function Documentation
NotifyController::getPageNumber ($request, $req_index) protected
Definition at line 156 of file notify.ctrl.php.
References $request.
Referenced by index().
NotifyController::index ()
Definition at line 20 of file notify.ctrl.php.
References $note, $order, $request, and getPageNumber().
NotifyController::NotifyAdminCallback ($args, $action, $mem_redirect, $mem_resend)
callback for deleting/updating notes
Parameters
object $args
object $action
object $mem_redirect
object $mem_resend public
Returns
string
Definition at line 116 of file notify.ctrl.php.
References $action, $count, $layoutkit, $mem_redirect, elseif, and APP_User\loggedIn().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/notify/notify.ctrl.php