Rox: MemberRole Class Reference
MemberRole Class Reference
Public Member Functions
__construct ()
getRoleMembers ($role)
getMemberRoles ($member)
memberHasRole ($member, $role)
findById ($member, $role)
createMemberRoleLink ($member, $role)
removeMemberRoleLink ()
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Attributes
$_table_name = 'members_roles'
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Data Fields inherited from RoxEntityBase
$sql_order = ''
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 3 of file memberrole.entity.php.
Constructor & Destructor Documentation
MemberRole::__construct ()
Definition at line 7 of file memberrole.entity.php.
Member Function Documentation
MemberRole::createMemberRoleLink ($member, $role)
adds a role to a member
Parameters
object $role - role to set privilege for
object $privilege - privilege to add to role public
Returns
bool
Definition at line 111 of file memberrole.entity.php.
References $member, RoxEntityBase\insert(), and RoxEntityBase\isLoaded().
MemberRole::findById ($member, $role)
tries to load this entity using a member and a role entity overloads RoxEntityBase::findById
Parameters
object $member - the member part
object $role - the role part public
Returns
mixed - the loaded entity or false
Definition at line 92 of file memberrole.entity.php.
References $member, $query, and RoxEntityBase\findByWhere().
MemberRole::getMemberRoles ($member)
returns a member's roles
Parameters
object $role - the member to find roles for public
Returns
array
Definition at line 45 of file memberrole.entity.php.
References $id, $member, RoxModelBase\createEntity(), and RoxEntityBase\findByWhereMany().
MemberRole::getRoleMembers ($role)
returns members that have a given role
Parameters
object $role - the role to find members for public
Returns
array
Definition at line 19 of file memberrole.entity.php.
References $id, $member_ids, $members, RoxModelBase\createEntity(), and RoxEntityBase\findByWhereMany().
MemberRole::memberHasRole ($member, $role)
checks if a given member has a given role
Parameters
object $member - member entity
object $role - role entity public
Returns
bool
Definition at line 72 of file memberrole.entity.php.
References $member, and RoxModelBase\createEntity().
MemberRole::removeMemberRoleLink ()
removes a role from a member. Load the MemberRole, then call removeMemberRoleLink()
public
Returns
bool
Definition at line 130 of file memberrole.entity.php.
References RoxEntityBase\isLoaded().
Field Documentation
MemberRole::$_table_name = 'members_roles' protected
Definition at line 5 of file memberrole.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/rights/memberrole.entity.php