Rox: Geo Class Reference
Geo Class Reference
Public Member Functions
__construct ($location_id=false)
getParent ()
getAncestorLine ()
getCountry ()
getChildren ()
getAllParents ()
getAlternateName ($lang)
getName ($lang=null)
getAllAlternateNames ()
getUsageForAllTypes ()
getTotalUsage ()
placeType ()
isCity ()
isBorough ()
isRegion ()
isCountry ()
findLocationsByName ($name)
findLocationsByCoordinates (array $coordinates)
Public Member Functions inherited from RoxEntityBase
__construct ()
init ($store, $dao)
getColumns ()
getTableName ()
getTableDescription ()
getPrimaryKey ()
getPKValue ()
__call ($key, $args)
isLoaded ()
findById ($id)
findByWhere ($where)
findByWhereMany ($where, $offset=0, $limit=0)
findBySQL ($sql)
findBySQLMany ($sql)
findAll ($offset=0, $limit=0)
countAll ()
countWhere ($where)
loadFromArray ($data)
wipeEntity ()
insert ()
update ()
delete ()
validateSelf ()
getValidationErrors ()
isPKSet ()
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Attributes
$_table_name = 'geonames'
$alt_names = array()
Protected Attributes inherited from RoxEntityBase
$_table_name
$_columns_cache = array()
$_primary_key
$_has_loaded = false
$_validations = array()
$_validation_errors = array()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Data Fields inherited from RoxEntityBase
$sql_order = ''
Protected Member Functions inherited from RoxEntityBase
queryForEntity ($query)
queryForEntities ($query)
sqlCount ($query)
loadEntities ($result)
loadEntity ($data)
validateField ($key, $info)
preparePKWhereString ()
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 3 of file geo.entity.php.
Constructor & Destructor Documentation
Geo::__construct ($location_id = false)
Definition at line 8 of file geo.entity.php.
References RoxEntityBase\findById().
Member Function Documentation
Geo::findLocationsByCoordinates (array $coordinates)
returns of array of Geo entities
Parameters
array $coordinates
Exceptions
Exception public
Returns
array
Definition at line 418 of file geo.entity.php.
References RoxEntityBase\findByWhereMany().
Geo::findLocationsByName ($name)
looks for a location by name and alternate name
Parameters
string $name - name to look for
public
Returns
array
Definition at line 375 of file geo.entity.php.
References $name, $query, RoxEntityBase\findByWhereMany(), and geonameid.
Geo::getAllAlternateNames ()
returns array of all alternate names for a location
public
Returns
array
Definition at line 209 of file geo.entity.php.
References $name, RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Geo::getAllParents ()
returns array of all parent locations of the current geo entity uses geo_hierarchy to find the parents
public
Returns
array
Definition at line 131 of file geo.entity.php.
References RoxModelBase\createEntity(), RoxEntityBase\findByWhereMany(), and RoxEntityBase\isLoaded().
Geo::getAlternateName ($lang)
returns alternate name for the location in the language provided if no alternate name can be found for that language, uses the default
Parameters
string
public
Returns
string
Definition at line 159 of file geo.entity.php.
References $lang, $name, RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Referenced by getName().
Geo::getAncestorLine ()
returns the line of ancestors in an array
public
Returns
array
Definition at line 56 of file geo.entity.php.
References getCountry(), and RoxEntityBase\isLoaded().
Geo::getChildren ()
returns array of all children locations of the current geo entity uses geo_hierarchy to find the children
public
Returns
array
Definition at line 105 of file geo.entity.php.
References RoxModelBase\createEntity(), RoxEntityBase\findByWhereMany(), and RoxEntityBase\isLoaded().
Geo::getCountry ()
returns the geo object for the country
public
Returns
Geo
Definition at line 83 of file geo.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Referenced by getAncestorLine().
Geo::getName ($lang = null)
returns the name of the location
Parameters
string $lang - if provided, the name in this language is tried
public
Returns
string
Definition at line 187 of file geo.entity.php.
References $lang, $name, getAlternateName(), and RoxEntityBase\isLoaded().
Geo::getParent ()
returns the parent geo entity of this one
public
Returns
Geo|false
Definition at line 25 of file geo.entity.php.
References RoxModelBase\createEntity(), elseif, and RoxEntityBase\isLoaded().
Geo::getTotalUsage ()
returns total usage count for location
public
Returns
int
Definition at line 248 of file geo.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Geo::getUsageForAllTypes ()
returns array of usage counters for location
public
Returns
array
Definition at line 229 of file geo.entity.php.
References RoxModelBase\createEntity(), and RoxEntityBase\isLoaded().
Geo::isBorough ()
returns true if the entity is a borough
public
Returns
bool
Definition at line 328 of file geo.entity.php.
References RoxEntityBase\isLoaded(), and placeType().
Geo::isCity ()
returns true if the entity is a city
public
Returns
bool
Definition at line 313 of file geo.entity.php.
References RoxEntityBase\isLoaded(), and placeType().
Geo::isCountry ()
returns true if the entity is a country
public
Returns
bool
Definition at line 358 of file geo.entity.php.
References RoxEntityBase\isLoaded(), and placeType().
Geo::isRegion ()
returns true if the entity is a region
public
Returns
bool
Definition at line 343 of file geo.entity.php.
References RoxEntityBase\isLoaded(), and placeType().
Geo::placeType ()
returns the type of the object
public
Returns
string
Definition at line 267 of file geo.entity.php.
References RoxEntityBase\isLoaded(), and RoxComponentBase\logWrite().
Referenced by isBorough(), isCity(), isCountry(), and isRegion().
Field Documentation
Geo::$_table_name = 'geonames' protected
Definition at line 5 of file geo.entity.php.
Geo::$alt_names = array() protected
Definition at line 6 of file geo.entity.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/geo/geo.entity.php