Rox: UserView Class Reference
UserView Class Reference
Public Member Functions
__construct (User $model)
avatar ($userId)
friends ($friends)
ShowInfoMessage ($message, $messagetitle)
loginForm ($redirect_url=false)
registerConfirm ($error=false)
registerForm ()
registerMail ($userId)
searchResult ($res)
settingsForm ()
passwordForm ()
userPage ($userHandle)
teaser ()
customStyles ()
rightContent ()
picture ($picture)
Detailed Description
Definition at line 11 of file user.view.php.
Constructor & Destructor Documentation
UserView::__construct (User $model)
Parameters
User $model
Definition at line 23 of file user.view.php.
References $model.
Member Function Documentation
UserView::avatar ($userId)
Definition at line 28 of file user.view.php.
UserView::customStyles ()
Definition at line 215 of file user.view.php.
UserView::friends ($friends)
Definition at line 50 of file user.view.php.
References TEMPLATE_DIR.
UserView::loginForm ($redirect_url = false)
Loading login form template
Parameters
void
Definition at line 70 of file user.view.php.
References $request, and TEMPLATE_DIR.
UserView::passwordForm ()
Definition at line 173 of file user.view.php.
UserView::picture ($picture)
Definition at line 227 of file user.view.php.
References TEMPLATE_DIR.
UserView::registerConfirm ($error = false)
Loading register confirm error template
Parameters
void
Definition at line 85 of file user.view.php.
References TEMPLATE_DIR.
UserView::registerForm ()
Loading register form template
Parameters
void
Definition at line 95 of file user.view.php.
References TEMPLATE_DIR.
UserView::registerMail ($userId)
Sends a confirmation e-mail
Parameters
string $userId
Definition at line 105 of file user.view.php.
References $mailText, $registerMailText, $subject, $User, MOD_mail_Multipart\addAttachment(), PException\addInfo(), APP_User\getSetting(), and TEMPLATE_DIR.
UserView::rightContent ()
Definition at line 222 of file user.view.php.
References $User.
UserView::searchResult ($res)
Definition at line 157 of file user.view.php.
References TEMPLATE_DIR.
UserView::settingsForm ()
Definition at line 162 of file user.view.php.
References $User, APP_User\get(), and TEMPLATE_DIR.
UserView::ShowInfoMessage ($message, $messagetitle)
Loading Official Message template
Parameters
void
Definition at line 60 of file user.view.php.
References TEMPLATE_DIR.
UserView::teaser ()
Definition at line 211 of file user.view.php.
References TEMPLATE_DIR.
UserView::userPage ($userHandle)
Definition at line 178 of file user.view.php.
References TEMPLATE_DIR, and APP_User\userId().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/user/user.view.php