Rox: SafeHTML Class Reference
SafeHTML Class Reference
Public Member Functions
SafeHTML ()
_writeAttrs ($attrs)
_openHandler (&$parser, $name, $attrs)
_closeHandler (&$parser, $name)
_closeTag ($tag)
_dataHandler (&$parser, $data)
_escapeHandler (&$parser, $data)
getXHTML ()
clear ()
parse ($doc)
repackUTF7 ($str)
repackUTF7Callback ($str)
repackUTF7Back ($str)
Data Fields
$_xhtml = ''
$_counter = array()
$_stack = array()
$_dcCounter = array()
$_dcStack = array()
$_listScope = 0
$_liStack = array()
$_protoRegexps = array()
$_cssRegexps = array()
$singleTags = array('area', 'br', 'img', 'input', 'hr', 'wbr',)
$deleteTags
$deleteTagsContent = array('script', 'style', 'title', 'xml',)
$protocolFiltering = 'white'
$blackProtocols
$whiteProtocols
$protocolAttributes
$cssKeywords
$noClose = array()
$closeParagraph
$tableTags
$listTags = array('dir', 'menu', 'ol', 'ul', 'dl',)
$attributes = array('dynsrc', 'id', 'name',)
$attributesNS = array('xml:lang',)
Member Function Documentation
SafeHTML::_closeHandler (& $parser, $name)
Closing tag handler - called from HTMLSax
Parameters
object $parsers HTML parser
string $name tag name
Returns
boolean private
References $name, and _closeTag().
Referenced by _openHandler().
SafeHTML::_closeTag ($tag)
Closes tag
Parameters
string $tag tag name
Returns
boolean private
Referenced by _closeHandler(), and getXHTML().
SafeHTML::_dataHandler (& $parser, $data)
Character data handler - called from HTMLSax
Parameters
object $parser HTML parser
string $data textual data
Returns
boolean private
References $data.
SafeHTML::_escapeHandler (& $parser, $data)
Escape handler - called from HTMLSax
Parameters
object $parser HTML parser
string $data comments or other type of data
Returns
boolean private
SafeHTML::_openHandler (& $parser, $name, $attrs)
Opening tag handler - called from HTMLSax
Parameters
object $parser HTML Parser
string $name tag name
array $attrs tag attributes
Returns
boolean private
References $name, _closeHandler(), and _writeAttrs().
SafeHTML::_writeAttrs ($attrs)
Handles the writing of attributes - called from $this->_openHandler()
Parameters
array $attrs array of attributes $name => $value
Returns
boolean private
References $name, $proto, and $value.
Referenced by _openHandler().
SafeHTML::clear ()
Clears current document data
Returns
boolean public
SafeHTML::getXHTML ()
Returns the XHTML document
Returns
string Processed (X)HTML document public
References $_xhtml, and _closeTag().
Referenced by parse().
SafeHTML::parse ($doc)
Main parsing fuction
Parameters
string $doc HTML document for processing
Returns
string Processed (X)HTML document public
References getXHTML(), and repackUTF7().
SafeHTML::repackUTF7 ($str)
UTF-7 decoding fuction
Parameters
string $str HTML document for recode ASCII part of UTF-7 back to ASCII
Returns
string Decoded document private
Referenced by parse().
SafeHTML::repackUTF7Back ($str)
Additional UTF-7 encoding fuction
Parameters
string $str String for recode ASCII part of UTF-7 back to ASCII
Returns
string Recoded string private
SafeHTML::repackUTF7Callback ($str)
Additional UTF-7 decoding fuction
Parameters
string $str String for recode ASCII part of UTF-7 back to ASCII
Returns
string Recoded string private
SafeHTML::SafeHTML ()
Constructs class
public
References $i, and $proto.
Field Documentation
SafeHTML::$_counter = array()
SafeHTML::$_cssRegexps = array()
SafeHTML::$_dcCounter = array()
SafeHTML::$_dcStack = array()
SafeHTML::$_liStack = array()
SafeHTML::$_listScope = 0
SafeHTML::$_protoRegexps = array()
SafeHTML::$_stack = array()
SafeHTML::$_xhtml = ''
Referenced by getXHTML().
SafeHTML::$attributes = array('dynsrc', 'id', 'name',)
SafeHTML::$attributesNS = array('xml:lang',)
SafeHTML::$blackProtocols
Initial value:
= array(
        'about',   'chrome',     'data',       'disk',     'hcp',
        'help',    'javascript', 'livescript', 'lynxcgi',  'lynxexec',
        'ms-help', 'ms-its',     'mhtml',      'mocha',    'opera',
        'res',     'resource',   'shell',      'vbscript', 'view-source',
        'vnd.ms.radio',          'wysiwyg',
        )
SafeHTML::$closeParagraph
Initial value:
= array(
        'address', 'blockquote', 'center', 'dd',      'dir',       'div',
        'dl',      'dt',         'h1',     'h2',      'h3',        'h4',
        'h5',      'h6',         'hr',     'isindex', 'listing',   'marquee',
        'menu',    'multicol',   'ol',     'p',       'plaintext', 'pre',
        'table',   'ul',         'xmp',
        )
SafeHTML::$cssKeywords
Initial value:
= array(
        'absolute', 'behavior',       'behaviour',   'content', 'expression',
        'fixed',    'include-source', 'moz-binding',
        )
SafeHTML::$deleteTags
Initial value:
= array(
        'applet', 'base',   'basefont', 'bgsound', 'blink',  'body',
        'embed',  'frame',  'frameset', 'head',    'html',   'ilayer',
        'iframe', 'layer',  'link',     'meta',    'object', 'style',
        'title',  'script', 'font',     'marquee',
        )
SafeHTML::$deleteTagsContent = array('script', 'style', 'title', 'xml',)
SafeHTML::$listTags = array('dir', 'menu', 'ol', 'ul', 'dl',)
SafeHTML::$noClose = array()
SafeHTML::$protocolAttributes
Initial value:
= array(
        'action', 'background', 'codebase', 'dynsrc', 'href', 'lowsrc', 'src',
        )
SafeHTML::$protocolFiltering = 'white'
SafeHTML::$singleTags = array('area', 'br', 'img', 'input', 'hr', 'wbr',)
SafeHTML::$tableTags
Initial value:
= array(
        'caption', 'col', 'colgroup', 'tbody', 'td', 'tfoot', 'th',
        'thead',   'tr',
        )
SafeHTML::$whiteProtocols
Initial value:
= array(
        'ed2k',   'file', 'ftp',  'gopher', 'http',  'https',
        'irc',    'mailto', 'news', 'nntp', 'telnet', 'webcal',
        'xmpp',   'callto',
        )
The documentation for this class was generated from the following file:
safehtml.php