Rox: ApiController Class Reference
ApiController Class Reference
Public Member Functions
__construct ()
__destruct ()
checkFormat ()
success ($data)
error ($message)
response ($resultType, $data)
index ()
memberAction ()
Public Member Functions inherited from RoxControllerBase
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Data Fields
const FORMAT_JSON = 'json'
const FORMAT_JS = 'js'
$supportedFormats = array(self::FORMAT_JSON, self::FORMAT_JS)
Additional Inherited Members
Protected Member Functions inherited from RoxControllerBase
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
API controller class.
Author
Meinhard Benn meinh.nosp@m.ard@.nosp@m.bewel.nosp@m.come.nosp@m..org
Definition at line 7 of file api.ctrl.php.
Constructor & Destructor Documentation
ApiController::__construct ()
Constructor.
Definition at line 29 of file api.ctrl.php.
ApiController::__destruct ()
Deconstructor.
Definition at line 38 of file api.ctrl.php.
Member Function Documentation
ApiController::checkFormat ()
Check if requested data format is valid.
This will do nothing if format is supported and has neccesary parameters, but will send a raw error message response otherwise.
Definition at line 49 of file api.ctrl.php.
References $callback, and $format.
Referenced by memberAction().
ApiController::error ($message)
Send a response containing an error message, using the requested format.
Parameters
string $message Error message.
Definition at line 76 of file api.ctrl.php.
References $data, and response().
Referenced by memberAction().
ApiController::index ()
Default index.
Sends placeholder message as plain text response.
Definition at line 109 of file api.ctrl.php.
ApiController::memberAction ()
Member API action.
Fetches data, checks permissions and initiates response.
Definition at line 118 of file api.ctrl.php.
References $member, $username, checkFormat(), error(), and success().
ApiController::response ($resultType, $data)
Prepare response data and send it to view, using requested format.
Parameters
string $resultType Descriptive result type included in response.
object $data Object containing data fields for response.
Definition at line 88 of file api.ctrl.php.
References $callback, $data, and $format.
Referenced by error(), and success().
ApiController::success ($data)
Send a successful response.
Parameters
object $data Object containing data fields for response.
Definition at line 67 of file api.ctrl.php.
References $data, and response().
Referenced by memberAction().
Field Documentation
ApiController::$supportedFormats = array(self::FORMAT_JSON, self::FORMAT_JS)
Defining formats supported by the API.
Definition at line 24 of file api.ctrl.php.
const ApiController::FORMAT_JS = 'js'
Definition at line 19 of file api.ctrl.php.
const ApiController::FORMAT_JSON = 'json'
Defining class constants.
Definition at line 18 of file api.ctrl.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/api/api.ctrl.php