Rox: AdminWordModel Class Reference
AdminWordModel Class Reference
Public Member Functions
getEnglishTotalLength ()
getTranslationLength ($idLanguage=false)
getFindData ($params)
getEngSentByCode ($code)
getTranslationData ($type, $limit, $shortcode, $wordcode=false)
getWordcodeById ($id)
wordcodeExist ($code, $shortcode)
getLangarr ($scope)
updateNoChanges ($id)
updateSingleTranslation ($form)
createCodeFormCheck ($form)
editCodeFormCheck ($form)
editTranslationFormCheck ($form)
findTranslationsFormCheck ($form)
setNoUpdateNeeded ($id)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Protected Attributes inherited from RoxModelBase
$_entity_factory
Detailed Description
Definition at line 35 of file adminword.model.php.
Member Function Documentation
AdminWordModel::createCodeFormCheck ($form)
Definition at line 395 of file adminword.model.php.
References $errors.
Referenced by editCodeFormCheck().
AdminWordModel::editCodeFormCheck ($form)
Definition at line 426 of file adminword.model.php.
References $errors, $rights, createCodeFormCheck(), and MOD_right\get().
AdminWordModel::editTranslationFormCheck ($form)
Definition at line 451 of file adminword.model.php.
References $errors, $query, $res, and elseif.
AdminWordModel::findTranslationsFormCheck ($form)
Definition at line 486 of file adminword.model.php.
References $errors.
AdminWordModel::getEnglishTotalLength ()
Definition at line 45 of file adminword.model.php.
References $query.
AdminWordModel::getEngSentByCode ($code)
Definition at line 127 of file adminword.model.php.
References $query, and $res.
AdminWordModel::getFindData ($params)
Definition at line 96 of file adminword.model.php.
References $params.
AdminWordModel::getLangarr ($scope)
Definition at line 284 of file adminword.model.php.
References $res.
AdminWordModel::getTranslationData ($type, $limit, $shortcode, $wordcode = false)
Definition at line 149 of file adminword.model.php.
References $data, $type, and elseif.
AdminWordModel::getTranslationLength ($idLanguage = false)
Definition at line 64 of file adminword.model.php.
AdminWordModel::getWordcodeById ($id)
Definition at line 249 of file adminword.model.php.
References $id, and $query.
AdminWordModel::setNoUpdateNeeded ($id)
Definition at line 509 of file adminword.model.php.
References $id, and updateNoChanges().
AdminWordModel::updateNoChanges ($id)
Definition at line 315 of file adminword.model.php.
References $id.
Referenced by setNoUpdateNeeded().
AdminWordModel::updateSingleTranslation ($form)
Definition at line 327 of file adminword.model.php.
References $_SESSION, and $desc.
AdminWordModel::wordcodeExist ($code, $shortcode)
Definition at line 265 of file adminword.model.php.
References $query.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/adminword.model.php