Rox: UserController Class Reference
UserController Class Reference
Public Member Functions
__construct ()
__destruct ()
index ()
displayLoginForm ($redirect_url=false)
Detailed Description
Definition at line 33 of file user.ctrl.php.
Constructor & Destructor Documentation
UserController::__construct ()
Constructor
Parameters
void
Definition at line 52 of file user.ctrl.php.
References moduleLoaded().
UserController::__destruct ()
Destructor
Parameters
void
Definition at line 66 of file user.ctrl.php.
Member Function Documentation
UserController::displayLoginForm ($redirect_url = false)
Displays login form at once
Parameters
void
Definition at line 293 of file user.ctrl.php.
UserController::index ()
Index function
Currently the index consists of following possible requests: checkemail - prints either "0" or "1" depending on e-mail validity checkhandle - like "checkemail" with user handle register - registration form to page content
Parameters
void
Definition at line 81 of file user.ctrl.php.
References $error, $Page, $request, $res, $User, User\HANDLE_PREGEXP, APP_User\login(), and moduleLoaded().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/user/user.ctrl.php