Rox: RoxControllerBase Class Reference
RoxControllerBase Class Reference
Public Member Functions
setFlashNotice ($message)
setFlashError ($message)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Member Functions
redirect ($request, $get_args= '')
redirectHome ($get_args= '')
redirectRefresh ()
redirectAbsolute ($url, $get_args= '')
setTitle ($title)
setTitleTranslate ($title)
cleanVars ($post_vars)
redirectToLogin ($url_part)
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 4 of file ctrl.php.
Member Function Documentation
RoxControllerBase::cleanVars ($post_vars) protected
trims all values posted back to controller
Parameters
array $post_vars private
Returns
array
Definition at line 50 of file ctrl.php.
References $vars.
Referenced by VerifymembersController\checkPasswordCallback(), and VerifymembersController\verifyCallback().
RoxControllerBase::redirect ($request, $get_args = '') protected
Definition at line 6 of file ctrl.php.
References $request, and redirectAbsolute().
Referenced by RoxController\_redirectLevel(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), ExtensionsController\index(), VerifymembersController\index(), GalleryController\index(), SignupController\index(), RoxController\index(), MembersController\index_loggedIn(), MembersController\index_loggedOut(), GroupsController\inviteMember(), LoginController\logIn(), GalleryController\manage(), MembersController\redirect_myprofile(), redirectHome(), redirectRefresh(), and GalleryController\upload().
RoxControllerBase::redirectAbsolute ($url, $get_args = '') protected
Definition at line 22 of file ctrl.php.
References $url.
Referenced by GroupsController\acceptInvitation(), GroupsController\acceptMember(), ActivitiesController\activities(), ActivitiesController\activitiesNearMe(), GroupsController\addMemberAsAdmin(), GroupsController\banMember(), GroupsController\declineInvitation(), GroupsController\delete(), SuggestionsController\editCreate(), ActivitiesController\editcreate(), GroupsController\groupSettings(), RoxController\index(), GroupsController\inviteMembers(), GroupsController\kickMember(), LoginController\logOut(), AdminController\massmailTrigger(), AdminController\massmailUnqueue(), AdminController\massmailUntrigger(), GroupsController\memberAdministration(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), ActivitiesController\myActivities(), AdminWordController\noRights(), AdminController\noRights(), redirect(), redirectToLogin(), GroupsController\resignAsAdmin(), SafetyController\safetyContact(), SearchController\searchMembers(), SuggestionsController\show(), ActivitiesController\show(), GroupsController\showGroup(), SuggestionsController\suggestions(), AdminController\treasurerStopDonationCampaign(), and SuggestionsController\voteRanking().
RoxControllerBase::redirectHome ($get_args = '') protected
Definition at line 14 of file ctrl.php.
References redirect().
Referenced by InviteController\index(), and RoxController\index().
RoxControllerBase::redirectRefresh () protected
Definition at line 18 of file ctrl.php.
References redirect().
RoxControllerBase::redirectToLogin ($url_part) protected
redirects to a login screen, returning the user to where it was afterwards
Parameters
string $url_part - relative url protected
Definition at line 70 of file ctrl.php.
References redirectAbsolute().
Referenced by GroupsController\acceptInvitation(), GroupsController\acceptMember(), GroupsController\addMemberAsAdmin(), GroupsController\banMember(), GroupsController\create(), GroupsController\declineInvitation(), GroupsController\delete(), GroupsController\groupSettings(), GalleryController\index(), GroupsController\join(), GroupsController\kickMember(), GroupsController\leave(), GroupsController\left(), GroupsController\memberAdministration(), GroupsController\memberSettings(), and GroupsController\myGroups().
RoxControllerBase::setFlashError ($message)
Set flash error message
See Also
PageWithRoxLayout::getFlashError() for counterpart
Parameters
string $message Message text for flash
Definition at line 103 of file ctrl.php.
Referenced by GroupsController\addMemberAsAdmin(), RelatedGroupsController\addRelatedGroup(), RelatedGroupsController\deleteRelatedGroup(), MembersController\index_loggedIn(), GroupsController\joined(), GroupsController\kickMember(), GroupsController\leave(), GroupsController\left(), GroupsController\resignAsAdmin(), and GalleryController\uploadedProcess().
RoxControllerBase::setFlashNotice ($message)
Set flash notice message
See Also
PageWithRoxLayout::getFlashNotice() for counterpart
Parameters
string $message Message text for flash
Definition at line 93 of file ctrl.php.
Referenced by GroupsController\acceptInvitation(), GroupsController\addMemberAsAdmin(), SuggestionsController\addOptionCallback(), RelatedGroupsController\addRelatedGroup(), SuggestionsController\approveSuggestionCallback(), SuggestionsController\changeStateCallback(), GroupsController\declineInvitation(), SuggestionsController\deleteOptionCallback(), RelatedGroupsController\deleteRelatedGroup(), SuggestionsController\editCreate(), SuggestionsController\editCreateSuggestionCallback(), SuggestionsController\editOptionCallback(), SuggestionsController\excludeCallback(), MembersController\index_loggedIn(), GroupsController\joined(), GroupsController\kickMember(), GroupsController\left(), LoginController\loginCallback(), SuggestionsController\moveOptionToImplemented(), SuggestionsController\moveOptionToImplementing(), GroupsController\resignAsAdmin(), SuggestionsController\restoreOption(), SuggestionsController\vote(), SuggestionsController\voteRanking(), and SuggestionsController\voteSuggestionCallback().
RoxControllerBase::setTitle ($title) protected
Definition at line 34 of file ctrl.php.
References $title.
Referenced by setTitleTranslate().
RoxControllerBase::setTitleTranslate ($title) protected
Definition at line 38 of file ctrl.php.
References $title, $words, and setTitle().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/tools/mvc-base/ctrl.php