Rox: MOD_member Class Reference
MOD_member Class Reference
Public Member Functions
getUsername ($userId=false)
getUserId ()
getTBuserId ()
getFromMembersTable ($select_string)
hasPublicProfile ()
getPreference_prefId ($preference_id)
getPreference_prefName ($preference_name)
Static Public Member Functions
static getUserHandle ($user_id)
static getMember_username ($username)
static getMember_userId ($userId)
Detailed Description
Get information about a specific member. A member is someone with a profile on BeWelcome. The user is the person who is currently surfing the site. This module is about members, not users.
Associated database tables:
members
memberspublicprofiles
An example for its use: $layoutbits = MOD_layoutbits::get(); // get the singleton instance $id = $geo->getCityID($cityname);
Author
Andreas (bw/cs:lemon-head)
Definition at line 42 of file member.lib.php.
Member Function Documentation
MOD_member::getFromMembersTable ($select_string)
Definition at line 169 of file member.lib.php.
static MOD_member::getMember_userId ($userId) static
Creates a member object for a given user id.
Parameters
int $userId
Returns
MOD_member a member object that provides access to member attributes.
Definition at line 127 of file member.lib.php.
Referenced by Note\getText().
static MOD_member::getMember_username ($username) static
Creates a member object for a given username.
Parameters
string $username
Returns
MOD_member a member object that provides access to member attributes.
Definition at line 108 of file member.lib.php.
References $username.
MOD_member::getPreference_prefId ($preference_id)
Definition at line 194 of file member.lib.php.
MOD_member::getPreference_prefName ($preference_name)
Definition at line 216 of file member.lib.php.
MOD_member::getTBuserId ()
Definition at line 158 of file member.lib.php.
References $d, and $query.
static MOD_member::getUserHandle ($user_id) static
returns the handle from a TB user, given tb user id
Parameters
int $user_id id of user
public
Returns
string
Definition at line 84 of file member.lib.php.
Referenced by GalleryController\gallery().
MOD_member::getUserId ()
Definition at line 153 of file member.lib.php.
MOD_member::getUsername ($userId = false)
Definition at line 140 of file member.lib.php.
References $d, and $query.
Referenced by NotifyAdminWidget\tableCell_link().
MOD_member::hasPublicProfile ()
Definition at line 179 of file member.lib.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/user/lib/member.lib.php