Rox: Snoopy Class Reference
Snoopy Class Reference
Public Member Functions
fetch ($URI)
_striplinks ($document)
_stripform ($document)
_striptext ($document)
_expandlinks ($links, $URI)
_httprequest ($url, $fp, $URI, $http_method, $content_type="", $body="")
_httpsrequest ($url, $URI, $http_method, $content_type="", $body="")
setcookies ()
_check_timeout ($fp)
_connect (&$fp)
_disconnect ($fp)
_prepare_post_body ($formvars, $formfiles)
fetch ($URI)
_striplinks ($document)
_stripform ($document)
_striptext ($document)
_expandlinks ($links, $URI)
_httprequest ($url, $fp, $URI, $http_method, $content_type="", $body="")
_httpsrequest ($url, $URI, $http_method, $content_type="", $body="")
setcookies ()
_check_timeout ($fp)
_connect (&$fp)
_disconnect ($fp)
_prepare_post_body ($formvars, $formfiles)
fetch ($URI)
_striplinks ($document)
_stripform ($document)
_striptext ($document)
_expandlinks ($links, $URI)
_httprequest ($url, $fp, $URI, $http_method, $content_type="", $body="")
_httpsrequest ($url, $URI, $http_method, $content_type="", $body="")
setcookies ()
_check_timeout ($fp)
_connect (&$fp)
_disconnect ($fp)
_prepare_post_body ($formvars, $formfiles)
Data Fields
$host = "www.php.net"
$port = 80
$proxy_host = ""
$proxy_port = ""
$agent = "Snoopy v1.0"
$referer = ""
$cookies = array()
$rawheaders = array()
$maxredirs = 5
$lastredirectaddr = ""
$offsiteok = true
$maxframes = 0
$expandlinks = true
$passcookies = true
$user = ""
$pass = ""
$accept = "image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*"
$results = ""
$error = ""
$response_code = ""
$headers = array()
$maxlength = 500000
$read_timeout = 0
$timed_out = false
$status = 0
$curl_path = "/usr/bin/curl"
$use_gzip = true
$_maxlinelen = 4096
$_httpmethod = "GET"
$_httpversion = "HTTP/1.0"
$_submit_method = "POST"
$_submit_type = "application/x-www-form-urlencoded"
$_mime_boundary = ""
$_redirectaddr = false
$_redirectdepth = 0
$_frameurls = array()
$_framedepth = 0
$_isproxy = false
$_fp_timeout = 30
Detailed Description
Definition at line 38 of file Snoopy.class.inc.
Member Function Documentation
Snoopy::_check_timeout ($fp)
Definition at line 753 of file Snoopy.class.inc.
Referenced by _httprequest().
Snoopy::_check_timeout ($fp)
Definition at line 753 of file Snoopy.class.inc.
Snoopy::_check_timeout ($fp)
Definition at line 753 of file Snoopy.class.inc.
Snoopy::_connect (& $fp)
Definition at line 771 of file Snoopy.class.inc.
References $host, $port, $proxy_host, $proxy_port, and error.
Snoopy::_connect (& $fp)
Definition at line 771 of file Snoopy.class.inc.
References $host, $port, $proxy_host, $proxy_port, and error.
Referenced by fetch().
Snoopy::_connect (& $fp)
Definition at line 771 of file Snoopy.class.inc.
References $host, $port, $proxy_host, $proxy_port, and error.
Snoopy::_disconnect ($fp)
Definition at line 823 of file Snoopy.class.inc.
Snoopy::_disconnect ($fp)
Definition at line 823 of file Snoopy.class.inc.
Referenced by fetch().
Snoopy::_disconnect ($fp)
Definition at line 823 of file Snoopy.class.inc.
Snoopy::_expandlinks ($links, $URI)
Definition at line 373 of file Snoopy.class.inc.
References $search.
Snoopy::_expandlinks ($links, $URI)
Definition at line 373 of file Snoopy.class.inc.
References $search.
Referenced by _httprequest(), and _httpsrequest().
Snoopy::_expandlinks ($links, $URI)
Definition at line 373 of file Snoopy.class.inc.
References $search.
Snoopy::_httprequest ($url, $fp, $URI, $http_method, $content_type = "", $body = "")
Definition at line 407 of file Snoopy.class.inc.
References $body, $data, $headers, $matches, $port, $results, $status, $url, _check_timeout(), _expandlinks(), each(), elseif, headers, and setcookies().
Snoopy::_httprequest ($url, $fp, $URI, $http_method, $content_type = "", $body = "")
Definition at line 407 of file Snoopy.class.inc.
References $body, $data, $headers, $matches, $port, $results, $status, $url, _check_timeout(), _expandlinks(), each(), elseif, headers, and setcookies().
Referenced by fetch().
Snoopy::_httprequest ($url, $fp, $URI, $http_method, $content_type = "", $body = "")
Definition at line 407 of file Snoopy.class.inc.
References $body, $data, $headers, $matches, $port, $results, $status, $url, _check_timeout(), _expandlinks(), each(), elseif, headers, and setcookies().
Snoopy::_httpsrequest ($url, $URI, $http_method, $content_type = "", $body = "")
Definition at line 590 of file Snoopy.class.inc.
References $body, $headers, $matches, $port, $results, $url, _expandlinks(), each(), elseif, error, headers, and setcookies().
Snoopy::_httpsrequest ($url, $URI, $http_method, $content_type = "", $body = "")
Definition at line 590 of file Snoopy.class.inc.
References $body, $headers, $matches, $port, $results, $url, _expandlinks(), each(), elseif, error, headers, and setcookies().
Snoopy::_httpsrequest ($url, $URI, $http_method, $content_type = "", $body = "")
Definition at line 590 of file Snoopy.class.inc.
References $body, $headers, $matches, $port, $results, $url, _expandlinks(), each(), elseif, error, headers, and setcookies().
Referenced by fetch().
Snoopy::_prepare_post_body ($formvars, $formfiles)
Definition at line 837 of file Snoopy.class.inc.
References each().
Snoopy::_prepare_post_body ($formvars, $formfiles)
Definition at line 837 of file Snoopy.class.inc.
References each().
Snoopy::_prepare_post_body ($formvars, $formfiles)
Definition at line 837 of file Snoopy.class.inc.
References each().
Snoopy::_stripform ($document)
Definition at line 307 of file Snoopy.class.inc.
Snoopy::_stripform ($document)
Definition at line 307 of file Snoopy.class.inc.
Snoopy::_stripform ($document)
Definition at line 307 of file Snoopy.class.inc.
Snoopy::_striplinks ($document)
Definition at line 273 of file Snoopy.class.inc.
References each().
Snoopy::_striplinks ($document)
Definition at line 273 of file Snoopy.class.inc.
References each().
Snoopy::_striplinks ($document)
Definition at line 273 of file Snoopy.class.inc.
References each().
Snoopy::_striptext ($document)
Definition at line 327 of file Snoopy.class.inc.
References $search, and $text.
Snoopy::_striptext ($document)
Definition at line 327 of file Snoopy.class.inc.
References $search, and $text.
Snoopy::_striptext ($document)
Definition at line 327 of file Snoopy.class.inc.
References $search, and $text.
Snoopy::fetch ($URI)
Definition at line 125 of file Snoopy.class.inc.
References $_frameurls, $_redirectaddr, _connect(), _disconnect(), _httprequest(), _httpsrequest(), each(), and error.
Referenced by fetch().
Snoopy::fetch ($URI)
Definition at line 125 of file Snoopy.class.inc.
References $_frameurls, $_redirectaddr, _connect(), _disconnect(), _httprequest(), _httpsrequest(), each(), error, and fetch().
Snoopy::fetch ($URI)
Definition at line 125 of file Snoopy.class.inc.
References $_frameurls, $_redirectaddr, _connect(), _disconnect(), _httprequest(), _httpsrequest(), each(), error, and fetch().
Snoopy::setcookies ()
Definition at line 737 of file Snoopy.class.inc.
References headers.
Snoopy::setcookies ()
Definition at line 737 of file Snoopy.class.inc.
References headers.
Snoopy::setcookies ()
Definition at line 737 of file Snoopy.class.inc.
References headers.
Referenced by _httprequest(), and _httpsrequest().
Field Documentation
Snoopy::$_fp_timeout = 30
Definition at line 114 of file Snoopy.class.inc.
Snoopy::$_framedepth = 0
Definition at line 111 of file Snoopy.class.inc.
Snoopy::$_frameurls = array()
Definition at line 110 of file Snoopy.class.inc.
Referenced by fetch().
Snoopy::$_httpmethod = "GET"
Definition at line 103 of file Snoopy.class.inc.
Snoopy::$_httpversion = "HTTP/1.0"
Definition at line 104 of file Snoopy.class.inc.
Snoopy::$_isproxy = false
Definition at line 113 of file Snoopy.class.inc.
Snoopy::$_maxlinelen = 4096
Definition at line 101 of file Snoopy.class.inc.
Snoopy::$_mime_boundary = ""
Definition at line 107 of file Snoopy.class.inc.
Snoopy::$_redirectaddr = false
Definition at line 108 of file Snoopy.class.inc.
Referenced by fetch().
Snoopy::$_redirectdepth = 0
Definition at line 109 of file Snoopy.class.inc.
Snoopy::$_submit_method = "POST"
Definition at line 105 of file Snoopy.class.inc.
Snoopy::$_submit_type = "application/x-www-form-urlencoded"
Definition at line 106 of file Snoopy.class.inc.
Snoopy::$accept = "image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*"
Definition at line 70 of file Snoopy.class.inc.
Snoopy::$agent = "Snoopy v1.0"
Definition at line 48 of file Snoopy.class.inc.
Snoopy::$cookies = array()
Definition at line 50 of file Snoopy.class.inc.
Snoopy::$curl_path = "/usr/bin/curl"
Definition at line 84 of file Snoopy.class.inc.
Snoopy::$error = ""
Definition at line 74 of file Snoopy.class.inc.
Snoopy::$expandlinks = true
Definition at line 59 of file Snoopy.class.inc.
Snoopy::$headers = array()
Definition at line 76 of file Snoopy.class.inc.
Referenced by _httprequest(), and _httpsrequest().
Snoopy::$host = "www.php.net"
Definition at line 44 of file Snoopy.class.inc.
Referenced by _connect().
Snoopy::$lastredirectaddr = ""
Definition at line 56 of file Snoopy.class.inc.
Snoopy::$maxframes = 0
Definition at line 58 of file Snoopy.class.inc.
Snoopy::$maxlength = 500000
Definition at line 77 of file Snoopy.class.inc.
Snoopy::$maxredirs = 5
Definition at line 55 of file Snoopy.class.inc.
Snoopy::$offsiteok = true
Definition at line 57 of file Snoopy.class.inc.
Snoopy::$pass = ""
Definition at line 67 of file Snoopy.class.inc.
Snoopy::$passcookies = true
Definition at line 62 of file Snoopy.class.inc.
Snoopy::$port = 80
Definition at line 45 of file Snoopy.class.inc.
Referenced by _connect(), _httprequest(), and _httpsrequest().
Snoopy::$proxy_host = ""
Definition at line 46 of file Snoopy.class.inc.
Referenced by _connect().
Snoopy::$proxy_port = ""
Definition at line 47 of file Snoopy.class.inc.
Referenced by _connect().
Snoopy::$rawheaders = array()
Definition at line 52 of file Snoopy.class.inc.
Snoopy::$read_timeout = 0
Definition at line 78 of file Snoopy.class.inc.
Snoopy::$referer = ""
Definition at line 49 of file Snoopy.class.inc.
Snoopy::$response_code = ""
Definition at line 75 of file Snoopy.class.inc.
Snoopy::$results = ""
Definition at line 72 of file Snoopy.class.inc.
Referenced by _httprequest(), and _httpsrequest().
Snoopy::$status = 0
Definition at line 82 of file Snoopy.class.inc.
Referenced by _httprequest().
Snoopy::$timed_out = false
Definition at line 81 of file Snoopy.class.inc.
Snoopy::$use_gzip = true
Definition at line 97 of file Snoopy.class.inc.
Snoopy::$user = ""
Definition at line 66 of file Snoopy.class.inc.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/about/magpierss/extlib/Snoopy.class.inc