Rox: MOD_bw_memcache Class Reference
MOD_bw_memcache Class Reference
Public Member Functions
__construct ($tablename="words", $Column="Sentence", $Code="code")
GetValue ($Code, $IdLanguage)
AddValue ($Code, $IdLanguage, $value)
ReplaceValue ($Code, $IdLanguage, $value)
LookUp ($Code, $IdLanguage)
Detailed Description
Definition at line 51 of file bw_memcache.lib.php.
Constructor & Destructor Documentation
MOD_bw_memcache::__construct ($tablename = "words", $Column = "Sentence", $Code = "code")
is the name of the table to consider is the name of the column which is supposed to have the value in the table
Definition at line 63 of file bw_memcache.lib.php.
References $_SESSION.
Member Function Documentation
MOD_bw_memcache::AddValue ($Code, $IdLanguage, $value)
This function adds a value in memcache $Code : the code for the value $IdLanguage : the language for the value $value : the value
Definition at line 164 of file bw_memcache.lib.php.
References $value.
Referenced by GetValue().
MOD_bw_memcache::GetValue ($Code, $IdLanguage)
This function is the core one it tries to find in memchache the given value for $Code in $IdLanguage if it fails, it then tries to query it from the database if it success, if the value is marked as expired, it update it from the database, mark it as uptodate and returns the value to caller if the value is not marked as expired it returns to caller (this is expected to be the most common case !) it stored it in memcache and returns the value to caller if it fails it store in memcache infor
Definition at line 105 of file bw_memcache.lib.php.
References $value, AddValue(), and LookUp().
MOD_bw_memcache::LookUp ($Code, $IdLanguage)
This function looks in the database for the value correspondig to a Code and a Language it returns false if it fails to find something
Definition at line 196 of file bw_memcache.lib.php.
Referenced by GetValue().
MOD_bw_memcache::ReplaceValue ($Code, $IdLanguage, $value)
This function replace a value in memcache $Code : the code for the value $IdLanguage : the language for the value $value : the value
Definition at line 181 of file bw_memcache.lib.php.
References $value.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/modules/i18n/lib/bw_memcache.lib.php