Rox: SimplePie_Enclosure Class Reference
SimplePie_Enclosure Class Reference
Public Member Functions
__construct ($link=null, $type=null, $length=null, $javascript=null, $bitrate=null, $captions=null, $categories=null, $channels=null, $copyright=null, $credits=null, $description=null, $duration=null, $expression=null, $framerate=null, $hashes=null, $height=null, $keywords=null, $lang=null, $medium=null, $player=null, $ratings=null, $restrictions=null, $samplingrate=null, $thumbnails=null, $title=null, $width=null)
__toString ()
get_bitrate ()
get_caption ($key=0)
get_captions ()
get_category ($key=0)
get_categories ()
get_channels ()
get_copyright ()
get_credit ($key=0)
get_credits ()
get_description ()
get_duration ($convert=false)
get_expression ()
get_extension ()
get_framerate ()
get_handler ()
get_hash ($key=0)
get_hashes ()
get_height ()
get_language ()
get_keyword ($key=0)
get_keywords ()
get_length ()
get_link ()
get_medium ()
get_player ()
get_rating ($key=0)
get_ratings ()
get_restriction ($key=0)
get_restrictions ()
get_sampling_rate ()
get_size ()
get_thumbnail ($key=0)
get_thumbnails ()
get_title ()
get_type ()
get_width ()
native_embed ($options='')
embed ($options= '', $native=false)
get_real_type ($find_handler=false)
Data Fields
$bitrate
$captions
$categories
$channels
$copyright
$credits
$description
$duration
$expression
$framerate
$handler
$hashes
$height
$javascript
$keywords
$lang
$length
$link
$medium
$player
$ratings
$restrictions
$samplingrate
$thumbnails
$title
$type
$width
Constructor & Destructor Documentation
SimplePie_Enclosure::__construct ($link = null, $type = null, $length = null, $javascript = null, $bitrate = null, $captions = null, $categories = null, $channels = null, $copyright = null, $credits = null, $description = null, $duration = null, $expression = null, $framerate = null, $hashes = null, $height = null, $keywords = null, $lang = null, $medium = null, $player = null, $ratings = null, $restrictions = null, $samplingrate = null, $thumbnails = null, $title = null, $width = null)
Constructor, used to input the data
For documentation on all the parameters, see the corresponding properties and their accessors
idna_convert If available, this will convert an IDN
References $bitrate, $captions, $categories, $channels, $copyright, $credits, $description, $duration, $expression, $framerate, $hashes, $height, $keywords, $lang, $length, $link, $medium, $player, $ratings, $restrictions, $samplingrate, $thumbnails, $title, $type, $width, SimplePie_Misc\compress_parse_url(), get_handler(), height, SimplePie_Misc\parse_url(), and title.
Member Function Documentation
SimplePie_Enclosure::__toString ()
String-ified version
Returns
string
SimplePie_Enclosure::embed ($options = '', $native = false)
Embed the enclosure using Javascript
$options is an array or comma-separated key:value string, with the following properties:
alt (string): Alternate content for when an end-user does not have the appropriate handler installed or when a file type is unsupported. Can be any text or HTML. Defaults to blank.
altclass (string): If a file type is unsupported, the end-user will see the alt text (above) linked directly to the content. That link will have this value as its class name. Defaults to blank.
audio (string): This is an image that should be used as a placeholder for audio files before they're loaded (QuickTime-only). Can be any relative or absolute URL. Defaults to blank.
bgcolor (string): The background color for the media, if not already transparent. Defaults to #ffffff.
height (integer): The height of the embedded media. Accepts any numeric pixel value (such as 360) or auto. Defaults to auto, and it is recommended that you use this default.
loop (boolean): Do you want the media to loop when its done? Defaults to false.
mediaplayer (string): The location of the included mediaplayer.swf file. This allows for the playback of Flash Video (.flv) files, and is the default handler for non-Odeo MP3's. Defaults to blank.
video (string): This is an image that should be used as a placeholder for video files before they're loaded (QuickTime-only). Can be any relative or absolute URL. Defaults to blank.
width (integer): The width of the embedded media. Accepts any numeric pixel value (such as 480) or auto. Defaults to auto, and it is recommended that you use this default.
widescreen (boolean): Is the enclosure widescreen or standard? This applies only to video enclosures, and will automatically resize the content appropriately. Defaults to false, implying 4:3 mode.
Note: Non-widescreen (4:3) mode with width and height set to auto will default to 480x360 video resolution. Widescreen (16:9) mode with width and height set to auto will default to 480x270 video resolution.
Todo:
If the dimensions for media:content are defined, use them when width/height are set to 'auto'.
Parameters
array | string $options Comma-separated key:value list, or array
bool $native Use <embed>
Returns
string HTML string to output
References $handler, $height, $options, $type, $width, elseif, get_extension(), get_handler(), get_link(), get_real_type(), and round.
Referenced by native_embed().
SimplePie_Enclosure::get_bitrate ()
Get the bitrate
Returns
string|null
References $bitrate.
SimplePie_Enclosure::get_caption ($key = 0)
Get a single caption
Parameters
int $key
Returns
SimplePie_Caption|null
References $captions, and get_captions().
SimplePie_Enclosure::get_captions ()
Get all captions
Returns
array|null Array of {
See Also
SimplePie_Caption} objects
References $captions.
Referenced by get_caption().
SimplePie_Enclosure::get_categories ()
Get all categories
Returns
array|null Array of {
See Also
SimplePie_Category} objects
References $categories.
Referenced by get_category().
SimplePie_Enclosure::get_category ($key = 0)
Get a single category
Parameters
int $key
Returns
SimplePie_Category|null
References $categories, and get_categories().
SimplePie_Enclosure::get_channels ()
Get the number of audio channels
Returns
int|null
References $channels.
SimplePie_Enclosure::get_copyright ()
Get the copyright information
Returns
SimplePie_Copyright|null
References $copyright.
SimplePie_Enclosure::get_credit ($key = 0)
Get a single credit
Parameters
int $key
Returns
SimplePie_Credit|null
References $credits, and get_credits().
SimplePie_Enclosure::get_credits ()
Get all credits
Returns
array|null Array of {
See Also
SimplePie_Credit} objects
References $credits.
Referenced by get_credit().
SimplePie_Enclosure::get_description ()
Get the description of the enclosure
Returns
string|null
References $description.
SimplePie_Enclosure::get_duration ($convert = false)
Get the duration of the enclosure
Parameters
string $convert Convert seconds into hh:mm:ss
Returns
string|int|null 'hh:mm:ss' string if $convert was specified, otherwise integer (or null if none found)
References $duration, and SimplePie_Misc\time_hms().
SimplePie_Enclosure::get_expression ()
Get the expression
Returns
string Probably one of 'sample', 'full', 'nonstop', 'clip'. Defaults to 'full'
References $expression.
SimplePie_Enclosure::get_extension ()
Get the file extension
Returns
string|null
References $url, and SimplePie_Misc\parse_url().
Referenced by embed(), and get_real_type().
SimplePie_Enclosure::get_framerate ()
Get the framerate (in frames-per-second)
Returns
string|null
References $framerate.
SimplePie_Enclosure::get_handler ()
Get the preferred handler
Returns
string|null One of 'flash', 'fmedia', 'quicktime', 'wmedia', 'mp3'
References get_real_type().
Referenced by __construct(), and embed().
SimplePie_Enclosure::get_hash ($key = 0)
Get a single hash
int $key string|null Hash as per media:hash, prefixed with "$algo:"
References $hashes, and get_hashes().
SimplePie_Enclosure::get_hashes ()
Get all credits
Returns
array|null Array of strings, see {
See Also
get_hash()}
References $hashes.
Referenced by get_hash().
SimplePie_Enclosure::get_height ()
Get the height
Returns
string|null
References $height, and height.
SimplePie_Enclosure::get_keyword ($key = 0)
Get a single keyword
Parameters
int $key
Returns
string|null
References $keywords, and get_keywords().
SimplePie_Enclosure::get_keywords ()
Get all keywords
Returns
array|null Array of strings
References $keywords.
Referenced by get_keyword().
SimplePie_Enclosure::get_language ()
Get the language
string|null Language code as per RFC 3066
References $lang.
SimplePie_Enclosure::get_length ()
Get length
Returns
float Length in bytes
References $length.
Referenced by get_size().
SimplePie_Enclosure::get_link ()
Get the URL
Returns
string|null
Referenced by embed().
SimplePie_Enclosure::get_medium ()
Get the medium
string|null Should be one of 'image', 'audio', 'video', 'document', 'executable'
References $medium.
SimplePie_Enclosure::get_player ()
Get the player URL
Typically the same as {
See Also
get_permalink()}
Returns
string|null Player URL
References $player.
SimplePie_Enclosure::get_rating ($key = 0)
Get a single rating
Parameters
int $key
Returns
SimplePie_Rating|null
References $ratings, and get_ratings().
SimplePie_Enclosure::get_ratings ()
Get all ratings
Returns
array|null Array of {
See Also
SimplePie_Rating} objects
References $ratings.
Referenced by get_rating().
SimplePie_Enclosure::get_real_type ($find_handler = false)
Get the real media type
Often, feeds lie to us, necessitating a bit of deeper inspection. This converts types to their canonical representations based on the file extension
See Also
get_type()
Parameters
bool $find_handler Internal use only, use {
See Also
get_handler()} instead
Returns
string MIME type
References $type, elseif, get_extension(), and get_type().
Referenced by embed(), and get_handler().
SimplePie_Enclosure::get_restriction ($key = 0)
Get a single restriction
Parameters
int $key
Returns
SimplePie_Restriction|null
References $restrictions, and get_restrictions().
SimplePie_Enclosure::get_restrictions ()
Get all restrictions
Returns
array|null Array of {
See Also
SimplePie_Restriction} objects
References $restrictions.
Referenced by get_restriction().
SimplePie_Enclosure::get_sampling_rate ()
Get the sampling rate (in kHz)
Returns
string|null
References $samplingrate.
SimplePie_Enclosure::get_size ()
Get the file size (in MiB)
Returns
float|null File size in mebibytes (1048 bytes)
References $length, get_length(), and round.
SimplePie_Enclosure::get_thumbnail ($key = 0)
Get a single thumbnail
Parameters
int $key
Returns
string|null Thumbnail URL
References $thumbnails, and get_thumbnails().
SimplePie_Enclosure::get_thumbnails ()
Get all thumbnails
Returns
array|null Array of thumbnail URLs
References $thumbnails.
Referenced by get_thumbnail().
SimplePie_Enclosure::get_title ()
Get the title
Returns
string|null
References $title, and title.
SimplePie_Enclosure::get_type ()
Get mimetype of the enclosure
See Also
get_real_type()
Returns
string|null MIME type
References $type.
Referenced by get_real_type().
SimplePie_Enclosure::get_width ()
Get the width
Returns
string|null
References $width.
SimplePie_Enclosure::native_embed ($options = '')
Embed the enclosure using <embed>
Deprecated:
Use the second parameter to {
See Also
embed} instead
Parameters
array | string $options See first paramter to {
See Also
embed}
Returns
string HTML string to output
References $options, and embed().
Field Documentation
SimplePie_Enclosure::$bitrate
Referenced by __construct(), and get_bitrate().
SimplePie_Enclosure::$captions
Referenced by __construct(), get_caption(), and get_captions().
SimplePie_Enclosure::$categories
Referenced by __construct(), get_categories(), and get_category().
SimplePie_Enclosure::$channels
Referenced by __construct(), and get_channels().
SimplePie_Enclosure::$copyright
Referenced by __construct(), and get_copyright().
SimplePie_Enclosure::$credits
Referenced by __construct(), get_credit(), and get_credits().
SimplePie_Enclosure::$description
Referenced by __construct(), and get_description().
SimplePie_Enclosure::$duration
Referenced by __construct(), and get_duration().
SimplePie_Enclosure::$expression
Referenced by __construct(), and get_expression().
SimplePie_Enclosure::$framerate
Referenced by __construct(), and get_framerate().
SimplePie_Enclosure::$handler
Referenced by embed().
SimplePie_Enclosure::$hashes
Referenced by __construct(), get_hash(), and get_hashes().
SimplePie_Enclosure::$height
Referenced by __construct(), embed(), and get_height().
SimplePie_Enclosure::$javascript
SimplePie_Enclosure::$keywords
Referenced by __construct(), get_keyword(), and get_keywords().
SimplePie_Enclosure::$lang
Referenced by __construct(), and get_language().
SimplePie_Enclosure::$length
Referenced by __construct(), get_length(), and get_size().
SimplePie_Enclosure::$link
Referenced by __construct().
SimplePie_Enclosure::$medium
Referenced by __construct(), and get_medium().
SimplePie_Enclosure::$player
Referenced by __construct(), and get_player().
SimplePie_Enclosure::$ratings
Referenced by __construct(), get_rating(), and get_ratings().
SimplePie_Enclosure::$restrictions
Referenced by __construct(), get_restriction(), and get_restrictions().
SimplePie_Enclosure::$samplingrate
Referenced by __construct(), and get_sampling_rate().
SimplePie_Enclosure::$thumbnails
Referenced by __construct(), get_thumbnail(), and get_thumbnails().
SimplePie_Enclosure::$title
Referenced by __construct(), and get_title().
SimplePie_Enclosure::$type
Referenced by __construct(), embed(), get_real_type(), and get_type().
SimplePie_Enclosure::$width
Referenced by __construct(), embed(), and get_width().
The documentation for this class was generated from the following file:
Enclosure.php