Rox: Formkit Class Reference
Formkit Class Reference
Public Member Functions
getMemFromRedirect ()
setPostCallback ($classname, $methodname, $extra_args=array())
setMemForRecovery ($memory=false)
setRedirect ($req)
__set ($key, $value)
__get ($key)
inject ($key, $value)
Protected Member Functions
get ($key)
Member Function Documentation
ObjectWithInjection::__get ($key) inherited
ObjectWithInjection::__set ($key, $value) inherited
References $value, and ObjectWithInjection\inject().
ObjectWithInjection::get ($key) protected inherited
Formkit::getMemFromRedirect ()
Referenced by setMemForRecovery().
ObjectWithInjection::inject ($key, $value) inherited
References $value.
Referenced by ObjectWithInjection\__set().
Formkit::setMemForRecovery ($memory = false)
References getMemFromRedirect().
Formkit::setPostCallback ($classname, $methodname, $extra_args = array())
Formkit::setRedirect ($req)
The documentation for this class was generated from the following file:
formkit.class.php