Rox: SimplePie_IRI Class Reference
SimplePie_IRI Class Reference
Public Member Functions
__toString ()
__set ($name, $value)
__get ($name)
__isset ($name)
__unset ($name)
__construct ($iri=null)
is_valid ()
set_iri ($iri)
set_scheme ($scheme)
set_authority ($authority)
set_userinfo ($iuserinfo)
set_host ($ihost)
set_port ($port)
set_path ($ipath)
set_query ($iquery)
set_fragment ($ifragment)
to_uri ($string)
get_iri ()
get_uri ()
Static Public Member Functions
static absolutize ($base, $relative)
Protected Member Functions
parse_iri ($iri)
remove_dot_segments ($input)
replace_invalid_with_pct_encoding ($string, $extra_chars, $iprivate=false)
remove_iunreserved_percent_encoded ($match)
scheme_normalization ()
get_iauthority ()
get_authority ()
Protected Attributes
$scheme = null
$iuserinfo = null
$ihost = null
$port = null
$ipath = ''
$iquery = null
$ifragment = null
$normalization
Detailed Description
Definition at line 56 of file IRI.php.
Constructor & Destructor Documentation
SimplePie_IRI::__construct ($iri = null)
Create a new IRI object, from a specified string
Parameters
string $iri
Definition at line 257 of file IRI.php.
References set_iri().
Member Function Documentation
SimplePie_IRI::__get ($name)
Overload __get() to provide access via properties
Parameters
string $name Property name
Returns
mixed
Definition at line 174 of file IRI.php.
References $name, $scheme, and elseif.
SimplePie_IRI::__isset ($name)
Overload __isset() to provide access via properties
Parameters
string $name Property name
Returns
bool
Definition at line 227 of file IRI.php.
References $name.
SimplePie_IRI::__set ($name, $value)
Overload __set() to provide access via properties
Parameters
string $name Property name
mixed $value Property value
Definition at line 149 of file IRI.php.
References $name, $value, and elseif.
SimplePie_IRI::__toString ()
Return the entire IRI when you try and read the object as a string
Returns
string
Definition at line 138 of file IRI.php.
References get_iri().
SimplePie_IRI::__unset ($name)
Overload __unset() to provide access via properties
Parameters
string $name Property name
Definition at line 244 of file IRI.php.
References $name.
static SimplePie_IRI::absolutize ($base, $relative) static
Create a new IRI object by resolving a relative IRI
Returns false if $base is not absolute, otherwise an IRI.
Parameters
IRI | string $base (Absolute) Base IRI
IRI | string $relative Relative IRI
Returns
IRI|false
Definition at line 271 of file IRI.php.
References elseif.
Referenced by SimplePie_Misc\absolutize_url().
SimplePie_IRI::get_authority () protected
Get the complete authority
Returns
string
Definition at line 1226 of file IRI.php.
References get_iauthority(), and to_uri().
SimplePie_IRI::get_iauthority () protected
Get the complete iauthority
Returns
string
Definition at line 1196 of file IRI.php.
References $ihost, and $port.
Referenced by get_authority(), and get_iri().
SimplePie_IRI::get_iri ()
Get the complete IRI
Returns
string
Definition at line 1145 of file IRI.php.
References $ifragment, $ipath, $iquery, $scheme, elseif, get_iauthority(), and is_valid().
Referenced by __toString(), and get_uri().
SimplePie_IRI::get_uri ()
Get the complete URI
Returns
string
Definition at line 1186 of file IRI.php.
References get_iri(), and to_uri().
SimplePie_IRI::is_valid ()
Check if the object represents a valid IRI. This needs to be done on each call as some things change depending on another part of the IRI.
Returns
bool
Definition at line 769 of file IRI.php.
Referenced by get_iri().
SimplePie_IRI::parse_iri ($iri) protected
Parse an IRI into scheme/authority/path/query/fragment segments
Parameters
string $iri
Returns
array
Definition at line 364 of file IRI.php.
Referenced by set_iri().
SimplePie_IRI::remove_dot_segments ($input) protected
Remove dot segments from a path
Parameters
string $input
Returns
string
Definition at line 404 of file IRI.php.
References elseif.
Referenced by set_path().
SimplePie_IRI::remove_iunreserved_percent_encoded ($match) protected
Callback function for preg_replace_callback.
Removes sequences of percent encoded bytes that represent UTF-8 encoded characters in iunreserved
Parameters
array $match PCRE match
Returns
string Replacement
Definition at line 603 of file IRI.php.
References $i, $value, and elseif.
SimplePie_IRI::replace_invalid_with_pct_encoding ($string, $extra_chars, $iprivate = false) protected
Replace invalid character with percent encoding
Parameters
string $string Input string
string $extra_chars Valid characters not in iunreserved or iprivate (this is ASCII-only)
bool $iprivate Allow iprivate
Returns
string
Definition at line 467 of file IRI.php.
References $value, and elseif.
Referenced by set_fragment(), set_host(), set_path(), set_query(), and set_userinfo().
SimplePie_IRI::scheme_normalization () protected
Definition at line 735 of file IRI.php.
Referenced by set_fragment(), set_host(), set_path(), set_port(), set_query(), and set_userinfo().
SimplePie_IRI::set_authority ($authority)
Set the authority. Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $authority
Returns
bool
Definition at line 878 of file IRI.php.
References $iuserinfo, $port, elseif, set_host(), set_port(), and set_userinfo().
Referenced by set_iri().
SimplePie_IRI::set_fragment ($ifragment)
Set the ifragment.
Parameters
string $ifragment
Returns
bool
Definition at line 1101 of file IRI.php.
References $ifragment, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_iri().
SimplePie_IRI::set_host ($ihost)
Set the ihost. Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $ihost
Returns
bool
Definition at line 966 of file IRI.php.
References $ihost, SimplePie_Net_IPv6\check_ipv6(), SimplePie_Net_IPv6\compress(), elseif, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_authority().
SimplePie_IRI::set_iri ($iri)
Set the entire IRI. Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $iri
Returns
bool
Definition at line 800 of file IRI.php.
References elseif, parse_iri(), set_authority(), set_fragment(), set_path(), set_query(), and set_scheme().
Referenced by __construct().
SimplePie_IRI::set_path ($ipath)
Set the ipath.
Parameters
string $ipath
Returns
bool
Definition at line 1048 of file IRI.php.
References $ipath, remove_dot_segments(), replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_iri().
SimplePie_IRI::set_port ($port)
Set the port. Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $port
Returns
bool
Definition at line 1022 of file IRI.php.
References $port, elseif, and scheme_normalization().
Referenced by set_authority().
SimplePie_IRI::set_query ($iquery)
Set the iquery.
Parameters
string $iquery
Returns
bool
Definition at line 1081 of file IRI.php.
References $iquery, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_iri().
SimplePie_IRI::set_scheme ($scheme)
Set the scheme. Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $scheme
Returns
bool
Definition at line 853 of file IRI.php.
References $scheme, and elseif.
Referenced by set_iri().
SimplePie_IRI::set_userinfo ($iuserinfo)
Set the iuserinfo.
Parameters
string $iuserinfo
Returns
bool
Definition at line 944 of file IRI.php.
References $iuserinfo, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_authority().
SimplePie_IRI::to_uri ($string)
Convert an IRI to a URI (or parts thereof)
Returns
string
Definition at line 1120 of file IRI.php.
Referenced by get_authority(), and get_uri().
Field Documentation
SimplePie_IRI::$ifragment = null protected
Definition at line 105 of file IRI.php.
Referenced by get_iri(), and set_fragment().
SimplePie_IRI::$ihost = null protected
Definition at line 77 of file IRI.php.
Referenced by get_iauthority(), and set_host().
SimplePie_IRI::$ipath = '' protected
Definition at line 91 of file IRI.php.
Referenced by get_iri(), and set_path().
SimplePie_IRI::$iquery = null protected
Definition at line 98 of file IRI.php.
Referenced by get_iri(), and set_query().
SimplePie_IRI::$iuserinfo = null protected
Definition at line 70 of file IRI.php.
Referenced by set_authority(), and set_userinfo().
SimplePie_IRI::$normalization protected
Initial value:
= array(
        'acap' => array(
            'port' => 674
        ),
        'dict' => array(
            'port' => 2628
        ),
        'file' => array(
            'ihost' => 'localhost'
        ),
        'http' => array(
            'port' => 80,
            'ipath' => '/'
        ),
        'https' => array(
            'port' => 443,
            'ipath' => '/'
        ),
    )
Normalization database
Each key is the scheme, each value is an array with each key as the IRI part and value as the default value for that part.
Definition at line 113 of file IRI.php.
SimplePie_IRI::$port = null protected
Definition at line 84 of file IRI.php.
Referenced by get_iauthority(), set_authority(), and set_port().
SimplePie_IRI::$scheme = null protected
Definition at line 63 of file IRI.php.
Referenced by __get(), get_iri(), and set_scheme().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/admin/templates/simplepie/library/SimplePie/IRI.php