Rox: RssModel Class Reference
RssModel Class Reference
Public Member Functions
getPosts ()
getForumFeed ()
getThreadFeed ($thread)
getBlogFeed ()
getBlogFeedByAuthor ($author)
getBlogFeedByTag ($tag)
getTagFeed ($tag)
Public Member Functions inherited from RoxModelBase
__construct ()
getLoggedInMember ()
restoreLoggedInMember ()
bulkLookup ($query_string, $keynames=false)
bulkLookup_assoc ($query_string)
singleLookup ($query_string)
singleLookup_assoc ($query_string)
Public Member Functions inherited from RoxComponentBase
__construct ()
__call ($key, $args)
__get ($key)
__set ($key, $value)
refresh_get ($key)
__toString ()
Protected Attributes
$posts
Protected Attributes inherited from RoxModelBase
$_entity_factory
Additional Inherited Members
Protected Member Functions inherited from RoxModelBase
get_dao ()
createEntity ()
getDao ()
getMemoryCookie ()
setMemoryCookie ($id, $seriesToken='', $authToken='')
Protected Member Functions inherited from RoxComponentBase
get ($key)
getValues ()
getWords ()
logWrite ($string, $type= 'Log')
getLog ()
getVersionInfo ()
Detailed Description
Definition at line 10 of file rss.model.php.
Member Function Documentation
RssModel::getBlogFeed ()
Definition at line 94 of file rss.model.php.
References $query, and RoxModelBase\bulkLookup().
RssModel::getBlogFeedByAuthor ($author)
Definition at line 120 of file rss.model.php.
References $query, and RoxModelBase\bulkLookup().
RssModel::getBlogFeedByTag ($tag)
Definition at line 148 of file rss.model.php.
References $query, and RoxModelBase\bulkLookup().
RssModel::getForumFeed ()
All forum posts bw/htdocs/rss
Definition at line 23 of file rss.model.php.
References RoxModelBase\bulkLookup().
RssModel::getPosts ()
Definition at line 15 of file rss.model.php.
References $posts.
RssModel::getTagFeed ($tag)
Specific tag rss/tag rss/tag/2 rss/tag/Milk
Definition at line 196 of file rss.model.php.
References $query, and RoxModelBase\bulkLookup().
RssModel::getThreadFeed ($thread)
Specific thread, e.g. rss/thread/2 rss/thread/test
Definition at line 57 of file rss.model.php.
References $query, and RoxModelBase\bulkLookup().
Field Documentation
RssModel::$posts protected
Definition at line 13 of file rss.model.php.
Referenced by getPosts().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/rox/build/rss/rss.model.php