Rox: C:/xampp/htdocs/rox/build/members/templates/comments.column_col3.helper.php File Reference
comments.column_col3.helper.php File Reference
Functions
foreach($member_ids as $id) cmp ($a, $b)
Variables
$member = $this->member
$comments_received = $this->member->comments
$comments_written = $this->member->get_comments_written()
$comments_from = array()
$comment_for_self = false
$member_ids = array()
foreach($comments_received as $c) $comments_to = array()
foreach($comments_written as $c) $comment_to_self_exists = false
$visitor = $this->model->getLoggedInMember()
if($visitor &&($visitor->id
<> $member->id)&&(in_array($visitor->
id, $member_ids))) $i = 0
$comments = array()
if($comment_to_self_exists
&&(!isset($comments_from[$visitor->
id]))) $username = $this->member->Username
$layoutbits = new MOD_layoutbits()
Function Documentation
foreach ($member_ids as $id) cmp ($a, $b)
Definition at line 63 of file comments.column_col3.helper.php.
Variable Documentation
$comment_for_self = false
Definition at line 7 of file comments.column_col3.helper.php.
foreach ($comments_written as $c) $comment_to_self_exists = false
Definition at line 27 of file comments.column_col3.helper.php.
$comments = array()
Definition at line 36 of file comments.column_col3.helper.php.
$comments_from = array()
Definition at line 6 of file comments.column_col3.helper.php.
$comments_received = $this->member->comments
Definition at line 3 of file comments.column_col3.helper.php.
foreach ($comments_received as $c) $comments_to = array()
Definition at line 17 of file comments.column_col3.helper.php.
$comments_written = $this->member->get_comments_written()
Definition at line 4 of file comments.column_col3.helper.php.
if ($visitor &&($visitor->id<> $member->id)&&(in_array($visitor->id, $member_ids))) $i = 0
Definition at line 35 of file comments.column_col3.helper.php.
$layoutbits = new MOD_layoutbits()
Definition at line 83 of file comments.column_col3.helper.php.
$member = $this->member
Definition at line 2 of file comments.column_col3.helper.php.
$member_ids = array()
Definition at line 9 of file comments.column_col3.helper.php.
Referenced by MemberRole\getRoleMembers().
if ($comment_to_self_exists &&(!isset($comments_from[$visitor->id]))) $username = $this->member->Username
Definition at line 82 of file comments.column_col3.helper.php.
Referenced by SqltestModel\analyse(), GalleryUserOverviewPage\column_col3(), SqltestPage\column_col3(), GalleryUserPage\column_col3(), Member\findByUsername(), LoginModel\getBWMemberByUsername(), ApiModel\getMember(), MOD_member\getMember_username(), LinkModel\getMemberID(), MembersModel\getMemberWithUsername(), GallerySetPage\getSubmenuItems(), MemberPage\getSubmenuItems(), PageWithRoxLayout\getTopmenuItems(), MembersController\index_loggedIn(), GalleryManagePage\leftSidebar(), GalleryUserGalleriesPage\leftSidebar(), GalleryUserPage\leftSidebar(), MOD_layoutbits\linkWithPicture(), MOD_layoutbits\linkWithPictureVar(), VerifyMembersModel\LoadVerified(), VerifyMembersModel\LoadVerifiers(), LoginController\loginCallback(), ApiController\memberAction(), MOD_layoutbits\PIC_100_100(), MOD_layoutbits\PIC_15_15(), MOD_layoutbits\PIC_30_30(), MOD_layoutbits\PIC_40_40(), MOD_layoutbits\PIC_50_50(), MOD_layoutbits\PIC_75_75(), AdminModel\procActivitylogs(), PageWithRoxLayout\quicksearch(), MembersController\redirect_myprofile(), MembersModel\reportBadComment(), FeedbackModel\sendFeedback(), MOD_layoutbits\smallUserPic_username(), MessagesBasePage\teaserContent(), PageWithRoxLayout\topmenu(), PageWithRoxLayout\topnav(), GalleryController\uploadedProcess(), and MembersModel\writeNoteForMember().
$visitor = $this->model->getLoggedInMember()
Definition at line 28 of file comments.column_col3.helper.php.