Rox: defaults.inc.php File Reference
defaults.inc.php File Reference
Namespaces
core
Functions
PPckup ()
translate ($request)
Variables
$susp = $B->x->query('/basedata/suspended')
if($susp->length > 0) $debug = $B->x->query('/basedata/debug')
Function Documentation
PPckup ()
This function returns the default controller (if no valid request is made)
Parameters
void
Returns
string The class name of the default controller
translate ($request)
This function returns the real application names for several aliases
Parameters
string $request the requested app
Returns
string the real app name
References $request.
Referenced by !function(), and translator_block().
Variable Documentation
if ($susp->length > 0) $debug = $B->x->query('/basedata/debug')
Referenced by RoxLauncher\launch(), EnvironmentExplorer\loadDefaults(), and ExceptionPage\showTraceStep().
$susp = $B->x->query('/basedata/suspended')
Referenced by EnvironmentExplorer\loadDefaults().