Rox: deletenote.column_col3.php File Reference
deletenote.column_col3.php File Reference
Variables
$vars = array()
$words = $this->words
$layoutbits = new MOD_layoutbits()
$member = $this->member
$Username = $member->Username
$edit_mode = false
$categories = $this->loggedInMember->getNoteCategories()
$mem_redirect = $this->layoutkit->formkit->getMemFromRedirect()
if(!$mem_redirect) else
$note = new StdClass
$note Category = $vars['ProfileNoteCategory']
$note CategoryFree = $vars['ProfileNoteCategoryFree']
$note Comment = $vars['ProfileNoteComment']
if(isset($vars['errors'])) $formkit = $this->layoutkit->formkit
$callback_tag = $formkit->setPostCallback('MembersController', 'deleteNoteCallback')
$m = $this->model->getMemberWithId($note->IdContact)
$purifier = MOD_htmlpure::getAdvancedHtmlPurifier()
Variable Documentation
$callback_tag = $formkit->setPostCallback('MembersController', 'deleteNoteCallback')
$categories = $this->loggedInMember->getNoteCategories()
$edit_mode = false
if (isset($vars['errors'])) $formkit = $this->layoutkit->formkit
$layoutbits = new MOD_layoutbits()
$m = $this->model->getMemberWithId($note->IdContact)
Referenced by AdminTreasurerEditCreateDonationPage\__construct(), VerifyMembersModel\AddNewVerified(), SqltestModel\analyse(), VerifyMembersModel\CheckAndGetUsername(), VerifyMembersModel\checkPassword(), MyVisitorsPage\column_col3(), MOD_bw_user_Auth\doBWLogin1(), Member\get_messengers(), LoginModel\getBWMemberByUsername(), AdminModel\getMassmailRecipientsInfo(), Member\hasMessengers(), VerifyMembersModel\LoadApprovedVerifiers(), VerifyMembersModel\LoadPrivateData(), MessagesController\mailBoxCallback(), MagpieRSS\php4_create_parser(), MembersModel\polishProfileFormValues(), DonateModel\returnFromPayPal(), Rox\returnFromPayPal(), LoginModel\setBWMemberAsLoggedIn(), MembersModel\setLocation(), MOD_bw_user_Auth\setupBWSession(), LoginModel\setupBWSession(), and MembersModel\updateProfile().
$mem_redirect = $this->layoutkit->formkit->getMemFromRedirect()
$member = $this->member
$note = new StdClass
$purifier = MOD_htmlpure::getAdvancedHtmlPurifier()
$Username = $member->Username
$vars = array()
$words = $this->words
$note Category = $vars['ProfileNoteCategory']
$note CategoryFree = $vars['ProfileNoteCategoryFree']
$note Comment = $vars['ProfileNoteComment']
if (!$mem_redirect) else
Initial value:
{
            $vars = $mem_redirect->post