Rox: C:/xampp/htdocs/rox/build/donate/templates/donate_list.php File Reference
donate_list.php File Reference
Variables
$words = new MOD_words()
$R = MOD_right::get()
$hasRight = $R->hasRight('Treasurer')
$i18n = new MOD_i18n('date.php')
$max =count($TDonationArray)
for ($ii=0;$ii<$max;$ii++) =$words->getFormatted("polls_vote")
Variable Documentation
$hasRight = $R->hasRight('Treasurer')
Definition at line 26 of file donate_list.php.
$i18n = new MOD_i18n('date.php')
Definition at line 27 of file donate_list.php.
$max =count($TDonationArray)
Definition at line 33 of file donate_list.php.
Referenced by MembersModel\addComment(), MembersModel\checkCommentForm(), AddRelationPage\column_col3(), ReadMessagePage\column_col3(), SimplePie_Net_IPv6\compress(), SimplePie\get_item_quantity(), MessagesModel\getSpamCheckStatus(), MembersModel\polishProfileFormValues(), SimplePie\set_max_checked_feeds(), Blog\setTripPosition(), ForumsView\showForum(), ForumsView\showTopic(), ForumsView\showTopLevelCategories(), ForumsView\showTopLevelRecentPosts(), and GeoModel\suggestLocation().
$R = MOD_right::get()
Definition at line 25 of file donate_list.php.
$words = new MOD_words()
Definition at line 24 of file donate_list.php.
for =$words->getFormatted("polls_vote")
Definition at line 35 of file donate_list.php.