Rox: editmyprofile.column_col3.helper.php File Reference
editmyprofile.column_col3.helper.php File Reference
Variables
$member = $this->member
$layoutkit = $this->layoutkit
$formkit = $layoutkit->formkit
$callback_tag = $formkit->setPostCallback('MembersController', 'editMyProfileCallback')
$page_url = PVars::getObj('env')->baseuri . implode('/', PRequest::get()->request)
$lang = $this->model->get_profile_language()
$profile_language = $lang->id
$profile_language_code = $lang->ShortCode
$profile_language_name = $lang->Name
$languages = $member->profile_languages
$languages_spoken = $member->languages_spoken
$CanTranslate = false
$vars = $this->editMyProfileFormPrepare($member)
$old_member_born = date('Y') - 100
$young_member_born = date('Y') - SignupModel::YOUNGEST_MEMBER
$birthYearOptions = ''
for($i=$young_member_born;$i >
$old_member_born;$i--) $statusOptions = ''
if(is_array($this->statuses))
if(isset($vars['errors']) and
count($vars['errors']) > 0) else
Variable Documentation
$birthYearOptions = ''
Referenced by SignupPage\column_col3(), and SignupView\registerForm().
$callback_tag = $formkit->setPostCallback('MembersController', 'editMyProfileCallback')
$CanTranslate = false
Referenced by MembersModel\updateProfile().
$formkit = $layoutkit->formkit
$lang = $this->model->get_profile_language()
Referenced by LookedUpWord\__construct(), _languageOptions(), TripSingleTripPage\column_col3(), DeleteTranslationPage\column_col3(), AddRelationPage\column_col3(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), BlogView\createForm(), BlogView\editForm(), EditProfilePage\editMyProfileFormPrepare(), SimplePie_Item\get_enclosures(), MembersModel\get_profile_language(), Geo\getAlternateName(), GeoModel\getDataById(), GeoModel\getGeonamesHierarchy(), Rox\getLangNames(), Searchmembers\getLangNames(), Geo\getName(), SuggestionsModel\getRanksAsArray(), SuggestionOption\getStatesAsArray(), MemberPage\getSubmenuItems(), Searchmembers\isValidLang(), Rox\isValidLang(), MembersModel\polishProfileFormValues(), MembersModel\setSessionLanguage(), SearchModel\suggestLocationsFromDatabase(), TranslationModule\translate(), MembersModel\updateProfile(), and SignupModel\writeFeedback().
$languages = $member->profile_languages
Referenced by _languageOptions(), _languageSelector(), ReadMessagePage\column_col3(), StatsModel\generateStatsImages(), getLanguagesOptionsDropDown(), AdminModel\getMassmailRecipientsInfo(), and ApiModel\getMemberData().
$languages_spoken = $member->languages_spoken
$layoutkit = $this->layoutkit
$member = $this->member
$old_member_born = date('Y') - 100
Referenced by buildBirthYearOptions(), and SignupPage\buildBirthYearOptions().
$page_url = PVars::getObj('env')->baseuri . implode('/', PRequest::get()->request)
$profile_language = $lang->id
Referenced by DeleteTranslationPage\column_col3(), and EditProfilePage\editMyProfileFormPrepare().
$profile_language_code = $lang->ShortCode
Referenced by EditProfilePage\editMyProfileFormPrepare(), and MemberPage\getSubmenuItems().
$profile_language_name = $lang->Name
Referenced by EditProfilePage\editMyProfileFormPrepare().
for ($i=$young_member_born;$i > $old_member_born;$i--) $statusOptions = ''
$vars = $this->editMyProfileFormPrepare($member)
$young_member_born = date('Y') - SignupModel::YOUNGEST_MEMBER
Referenced by buildBirthYearOptions(), and SignupPage\buildBirthYearOptions().
if (is_array($this->statuses)) if (isset($vars['errors']) and count($vars['errors']) > 0) else
Initial value:
{
    if ($this->status == 'finish') {
          echo '<div class="success">'.$words->getFormatted("EditmyprofileFinish", $profile_language_name,
                '<a href="members/'. $member->Username . '/' . $profile_language_code . '">', '</a>') . '</div>';
    }
    $vars['errors'] = array()