Rox: C:/xampp/htdocs/rox/htdocs/script/effects.js File Reference
effects.js File Reference
Functions
Object extend (Object.extend(Effect.ScopedQueue.prototype, Enumerable),{initialize:function(){this.effects=[];this.interval=null;}, _each:function(iterator){this.effects._each(iterator);}, add:function(effect){var timestamp=new Date().getTime();var position=(typeof effect.options.queue== 'string')?effect.options.queue:effect.options.queue.position;switch(position){case 'front':this.effects.findAll(function(e){return e.state=='idle'}).each(function(e){e.startOn+=effect.finishOn;e.finishOn+=effect.finishOn;});break;case 'with-last':timestamp=this.effects.pluck('startOn').max()||timestamp;break;case 'end':timestamp=this.effects.pluck('finishOn').max()||timestamp;break;}effect.startOn+=timestamp;effect.finishOn+=timestamp;if(!effect.options.queue.limit||(this.effects.length< effect.options.queue.limit)) this.effects.push(effect);if(!this.interval) this.interval=setInterval(this.loop.bind(this), 15);}, remove:function(effect){this.effects=this.effects.reject(function(e){return e==effect});if(this.effects.length==0){clearInterval(this.interval);this.interval=null;}}, loop:function(){var timePos=new Date().getTime();for(var i=0, len=this.effects.length;i< len;i++) if(this.effects[i]) this.effects[i].loop(timePos);}})
Object extend (Object.extend(Effect.Parallel.prototype, Effect.Base.prototype),{initialize:function(effects){this.effects=effects||[];this.start(arguments[1]);}, update:function(position){this.effects.invoke('render', position);}, finish:function(position){this.effects.each(function(effect){effect.render(1.0);effect.cancel();effect.event('beforeFinish');if(effect.finish) effect.finish(position);effect.event('afterFinish');});}})
Object extend (Object.extend(Effect.Event.prototype, Effect.Base.prototype),{initialize:function(){var options=Object.extend({duration:0}, arguments[0]||{});this.start(options);}, update:Prototype.emptyFunction})
Object extend (Object.extend(Effect.Opacity.prototype, Effect.Base.prototype),{initialize:function(element){this.element=$(element);if(!this.element) throw(Effect._elementDoesNotExistError);if(/MSIE/.test(navigator.userAgent)&&!window.opera &&(!this.element.currentStyle.hasLayout)) this.element.setStyle({zoom:1});var options=Object.extend({from:this.element.getOpacity()||0.0, to:1.0}, arguments[1]||{});this.start(options);}, update:function(position){this.element.setOpacity(position);}})
Object extend (Object.extend(Effect.Move.prototype, Effect.Base.prototype),{initialize:function(element){this.element=$(element);if(!this.element) throw(Effect._elementDoesNotExistError);var options=Object.extend({x:0, y:0, mode: 'relative'}, arguments[1]||{});this.start(options);}, setup:function(){this.element.makePositioned();this.originalLeft=parseFloat(this.element.getStyle('left')|| '0');this.originalTop=parseFloat(this.element.getStyle('top')|| '0');if(this.options.mode== 'absolute'){this.options.x=this.options.x-this.originalLeft;this.options.y=this.options.y-this.originalTop;}}, update:function(position){this.element.setStyle({left:Math.round(this.options.x *position+this.originalLeft)+ 'px', top:Math.round(this.options.y *position+this.originalTop)+ 'px'});}})
Object extend (Object.extend(Effect.Scale.prototype, Effect.Base.prototype),{initialize:function(element, percent){this.element=$(element);if(!this.element) throw(Effect._elementDoesNotExistError);var options=Object.extend({scaleX:true, scaleY:true, scaleContent:true, scaleFromCenter:false, scaleMode: 'box', scaleFrom:100.0, scaleTo:percent}, arguments[2]||{});this.start(options);}, setup:function(){this.restoreAfterFinish=this.options.restoreAfterFinish||false;this.elementPositioning=this.element.getStyle('position');this.originalStyle={};['top','left','width','height','fontSize'].each(function(k){this.originalStyle[k]=this.element.style[k];}.bind(this));this.originalTop=this.element.offsetTop;this.originalLeft=this.element.offsetLeft;var fontSize=this.element.getStyle('font-size')|| '100%';['em','px','%','pt'].each(function(fontSizeType){if(fontSize.indexOf(fontSizeType)>0){this.fontSize=parseFloat(fontSize);this.fontSizeType=fontSizeType;}}.bind(this));this.factor=(this.options.scaleTo-this.options.scaleFrom)/100;this.dims=null;if(this.options.scaleMode=='box') this.dims=[this.element.offsetHeight, this.element.offsetWidth];if(/^content/.test(this.options.scaleMode)) this.dims=[this.element.scrollHeight, this.element.scrollWidth];if(!this.dims) this.dims=[this.options.scaleMode.originalHeight, this.options.scaleMode.originalWidth];}, update:function(position){var currentScale=(this.options.scaleFrom/100.0)+(this.factor *position);if(this.options.scaleContent &&this.fontSize) this.element.setStyle({fontSize:this.fontSize *currentScale+this.fontSizeType});this.setDimensions(this.dims[0]*currentScale, this.dims[1]*currentScale);}, finish:function(position){if(this.restoreAfterFinish) this.element.setStyle(this.originalStyle);}, setDimensions:function(height, width){var d={};if(this.options.scaleX) d.width=Math.round(width)+ 'px';if(this.options.scaleY) d.height=Math.round(height)+ 'px';if(this.options.scaleFromCenter){var topd=(height-this.dims[0])/2;var leftd=(width-this.dims[1])/2;if(this.elementPositioning== 'absolute'){if(this.options.scaleY) d.top=this.originalTop-topd+ 'px';if(this.options.scaleX) d.left=this.originalLeft-leftd+ 'px';}else{if(this.options.scaleY) d.top=-topd+ 'px';if(this.options.scaleX) d.left=-leftd+ 'px';}}this.element.setStyle(d);}})
Variables
String prototype parseColor
Array prototype call
var Effect2 = Effect
Effect Transitions
Effect ScopedQueue = Class.create()
Effect Queues
Effect DefaultOptions
Effect Base prototype
Effect Event = Class.create()
Effect Opacity = Class.create()
Effect Move = Class.create()
Effect MoveBy
Effect Scale = Class.create()
Effect Highlight = Class.create()
Function Documentation
Object extend (Object. extendEffect.ScopedQueue.prototype, Enumerable, {initialize:function(){this.effects=[];this.interval=null;}, _each:function(iterator){this.effects._each(iterator);}, add:function(effect){var timestamp=new Date().getTime();var position=(typeof effect.options.queue== 'string')?effect.options.queue:effect.options.queue.position;switch(position){case 'front':this.effects.findAll(function(e){return e.state=='idle'}).each(function(e){e.startOn+=effect.finishOn;e.finishOn+=effect.finishOn;});break;case 'with-last':timestamp=this.effects.pluck('startOn').max()||timestamp;break;case 'end':timestamp=this.effects.pluck('finishOn').max()||timestamp;break;}effect.startOn+=timestamp;effect.finishOn+=timestamp;if(!effect.options.queue.limit||(this.effects.length< effect.options.queue.limit)) this.effects.push(effect);if(!this.interval) this.interval=setInterval(this.loop.bind(this), 15);}, remove:function(effect){this.effects=this.effects.reject(function(e){return e==effect});if(this.effects.length==0){clearInterval(this.interval);this.interval=null;}}, loop:function(){var timePos=new Date().getTime();for(var i=0, len=this.effects.length;i< len;i++) if(this.effects[i]) this.effects[i].loop(timePos);}})
Object extend (Object. extendEffect.Parallel.prototype, Effect.Base.prototype, {initialize:function(effects){this.effects=effects||[];this.start(arguments[1]);}, update:function(position){this.effects.invoke('render', position);}, finish:function(position){this.effects.each(function(effect){effect.render(1.0);effect.cancel();effect.event('beforeFinish');if(effect.finish) effect.finish(position);effect.event('afterFinish');});}})
Object extend (Object. extendEffect.Event.prototype, Effect.Base.prototype, {initialize:function(){var options=Object.extend({duration:0}, arguments[0]||{});this.start(options);}, update:Prototype.emptyFunction})
Object extend (Object. extendEffect.Opacity.prototype, Effect.Base.prototype, {initialize:function(element){this.element=$(element);if(!this.element) throw(Effect._elementDoesNotExistError);if(/MSIE/.test(navigator.userAgent)&&!window.opera &&(!this.element.currentStyle.hasLayout)) this.element.setStyle({zoom:1});var options=Object.extend({from:this.element.getOpacity()||0.0, to:1.0}, arguments[1]||{});this.start(options);}, update:function(position){this.element.setOpacity(position);}})
Object extend (Object. extendEffect.Move.prototype, Effect.Base.prototype, {initialize:function(element){this.element=$(element);if(!this.element) throw(Effect._elementDoesNotExistError);var options=Object.extend({x:0, y:0, mode: 'relative'}, arguments[1]||{});this.start(options);}, setup:function(){this.element.makePositioned();this.originalLeft=parseFloat(this.element.getStyle('left')|| '0');this.originalTop=parseFloat(this.element.getStyle('top')|| '0');if(this.options.mode== 'absolute'){this.options.x=this.options.x-this.originalLeft;this.options.y=this.options.y-this.originalTop;}}, update:function(position){this.element.setStyle({left:Math.round(this.options.x *position+this.originalLeft)+ 'px', top:Math.round(this.options.y *position+this.originalTop)+ 'px'});}})
Object extend (Object. extendEffect.Scale.prototype, Effect.Base.prototype, {initialize:function(element, percent){this.element=$(element);if(!this.element) throw(Effect._elementDoesNotExistError);var options=Object.extend({scaleX:true, scaleY:true, scaleContent:true, scaleFromCenter:false, scaleMode: 'box', scaleFrom:100.0, scaleTo:percent}, arguments[2]||{});this.start(options);}, setup:function(){this.restoreAfterFinish=this.options.restoreAfterFinish||false;this.elementPositioning=this.element.getStyle('position');this.originalStyle={};['top','left','width','height','fontSize'].each(function(k){this.originalStyle[k]=this.element.style[k];}.bind(this));this.originalTop=this.element.offsetTop;this.originalLeft=this.element.offsetLeft;var fontSize=this.element.getStyle('font-size')|| '100%';['em','px','%','pt'].each(function(fontSizeType){if(fontSize.indexOf(fontSizeType)>0){this.fontSize=parseFloat(fontSize);this.fontSizeType=fontSizeType;}}.bind(this));this.factor=(this.options.scaleTo-this.options.scaleFrom)/100;this.dims=null;if(this.options.scaleMode=='box') this.dims=[this.element.offsetHeight, this.element.offsetWidth];if(/^content/.test(this.options.scaleMode)) this.dims=[this.element.scrollHeight, this.element.scrollWidth];if(!this.dims) this.dims=[this.options.scaleMode.originalHeight, this.options.scaleMode.originalWidth];}, update:function(position){var currentScale=(this.options.scaleFrom/100.0)+(this.factor *position);if(this.options.scaleContent &&this.fontSize) this.element.setStyle({fontSize:this.fontSize *currentScale+this.fontSizeType});this.setDimensions(this.dims[0]*currentScale, this.dims[1]*currentScale);}, finish:function(position){if(this.restoreAfterFinish) this.element.setStyle(this.originalStyle);}, setDimensions:function(height, width){var d={};if(this.options.scaleX) d.width=Math.round(width)+ 'px';if(this.options.scaleY) d.height=Math.round(height)+ 'px';if(this.options.scaleFromCenter){var topd=(height-this.dims[0])/2;var leftd=(width-this.dims[1])/2;if(this.elementPositioning== 'absolute'){if(this.options.scaleY) d.top=this.originalTop-topd+ 'px';if(this.options.scaleX) d.left=this.originalLeft-leftd+ 'px';}else{if(this.options.scaleY) d.top=-topd+ 'px';if(this.options.scaleX) d.left=-leftd+ 'px';}}this.element.setStyle(d);}})
Variable Documentation
Array prototype call
Definition at line 75 of file effects.js.
Referenced by createTweens().
Effect DefaultOptions
Initial value:
= {
  transition: Effect.Transitions.sinoidal,
  duration:   1.0,
  fps:        60.0,
  sync:       false,
  from:       0.0,
  to:         1.0,
  delay:      0.0,
  queue:      'parallel'
}
Effect.Base = function() {}
Definition at line 246 of file effects.js.
var Effect2 = Effect
Definition at line 142 of file effects.js.
Effect Event = Class.create()
Definition at line 344 of file effects.js.
Referenced by NotifyAdminSettingsPage::column_col3(), GroupMemberAdministrationPage::column_col3(), flipSortDirection(), hookUpPager(), if(), and NotifyMemberWidget::showItems().
Effect Highlight = Class.create()
Definition at line 489 of file effects.js.
Effect Move = Class.create()
Definition at line 374 of file effects.js.
Effect MoveBy
Initial value:
= function(element, toTop, toLeft) {
  return new Effect.Move(element,
    Object.extend({ x: toLeft, y: toTop }, arguments[3] || {}));
}
Definition at line 409 of file effects.js.
Effect Opacity = Class.create()
Definition at line 355 of file effects.js.
String prototype parseColor
Definition at line 14 of file effects.js.
Effect Base prototype
Definition at line 258 of file effects.js.
Effect Queues
Initial value:
= {
  instances: $H(),
  get: function(queueName) {
    if(typeof queueName != 'string') return queueName;
    if(!this.instances[queueName])
      this.instances[queueName] = new Effect.ScopedQueue();
    return this.instances[queueName];
  }
}
Effect.Queue = Effect.Queues.get('global')
Definition at line 233 of file effects.js.
Effect Scale = Class.create()
Definition at line 414 of file effects.js.
Effect ScopedQueue = Class.create()
Definition at line 178 of file effects.js.
Effect Transitions
Initial value:
= {
  linear: Prototype.K,
  sinoidal: function(pos) {
    return (-Math.cos(pos*Math.PI)/2) + 0.5;
  },
  reverse: function(pos) {
    return 1-pos;
  },
  flicker: function(pos) {
    return ((-Math.cos(pos*Math.PI)/4) + 0.75) + Math.random()/4;
  },
  wobble: function(pos) {
    return (-Math.cos(pos*Math.PI*(9*pos))/2) + 0.5;
  },
  pulse: function(pos, pulses) {
    pulses = pulses || 5;
    return (
      Math.round((pos % (1/pulses)) * pulses) == 0 ?
            ((pos * pulses * 2) - Math.floor(pos * pulses * 2)) :
        1 - ((pos * pulses * 2) - Math.floor(pos * pulses * 2))
      );
  },
  none: function(pos) {
    return 0;
  },
  full: function(pos) {
    return 1;
  }
}
Definition at line 146 of file effects.js.