Rox: C:/xampp/htdocs/rox/build/about/templates/feedback.column_col3.php File Reference
feedback.column_col3.php File Reference
Variables
$words = new MOD_words()
$IdCategory = '11'
$RequestURI = ''
$redirect = ''
$data = ''
if(isset($_GET['redirect'])&&$_GET['redirect'])
if(isset($_GET['data'])&&$_GET['data']) $mem = $this->getRedirectedMem('post')
if(isset($mem['redirect'])) if(isset($mem['data'])) $FeedbackQuestion = isset($mem['FeedbackQuestion']) ? $mem['FeedbackQuestion'] : ''
$FeedbackEmail = isset($mem['FeedbackEmail']) ? $mem['FeedbackEmail'] : ''
$answernotneeded = isset($mem['answernotneeded']) ? $mem['answernotneeded'] : null
$errors = $this->getRedirectedMem('errors')
if ($errors=$this->getRedirectedMem('errors'))
if(in_array('FeedbackErrorDataMissing',
$errors)) else
Variable Documentation
$answernotneeded = isset($mem['answernotneeded']) ? $mem['answernotneeded'] : null
Definition at line 49 of file feedback.column_col3.php.
$data = ''
Definition at line 28 of file feedback.column_col3.php.
Referenced by SignupModel\__construct(), SafeHTML\_dataHandler(), Snoopy\_httprequest(), MOD_mail_Multipart\addAttachment(), GeoModel\addGeonameId(), SimplePie_Misc\change_encoding(), SimplePie_Misc\change_encoding_iconv(), SimplePie_Misc\change_encoding_mbstring(), LastCommentsPage\column_col3(), AdminWordController\editTranslation(), SimplePie_Misc\entities_decode(), ApiController\error(), MOD_geonames\fetchFile(), GeoView\GeoDisplayLocation(), RSSCache\get(), Places\getAllCountries(), RoxEntityBase\getTableDescription(), AdminWordModel\getTranslationData(), MembersController\index_loggedIn(), BlogEntity\insert(), SimplePie_Cache_Memcache\load(), SimplePie_Cache_MySQL\load(), RoxEntityBase\loadEntities(), RoxEntityBase\loadEntity(), RoxEntityBase\loadFromArray(), VerifyMembersModel\LoadPrivateData(), SimplePie_Cache_Memcache\mtime(), SimplePie_Cache_DB\prepare_simplepie_object_for_cache(), RoxEntityBase\queryForEntity(), ApiController\response(), SimplePie_Sanitize\sanitize(), SimplePie_Cache_File\save(), SimplePie_Cache_Memcache\save(), SimplePie_Cache_MySQL\save(), FeedbackModel\sendFeedback(), RSSCache\set(), RoxEntityBase\sqlCount(), SimplePie_Misc\strip_comments(), ApiController\success(), SimplePie_Cache_Memcache\touch(), RSSCache\unserialize(), BlogEntity\update(), GeoModel\updateGeonameId(), and SimplePie_Misc\xml_encoding().
$errors = $this->getRedirectedMem('errors')
Definition at line 50 of file feedback.column_col3.php.
Referenced by SuggestionsController\addOptionCallback(), ActivitiesController\cancelUncancelActivityCallback(), SuggestionsController\changeStateCallback(), SuggestionsModel\checkAddOptionVarsOk(), MembersModel\checkCommentForm(), ActivitiesModel\checkEditCreateActivityVarsOk(), SuggestionsModel\checkEditCreateSuggestionVarsOk(), ActivitiesModel\checkJoinLeaveActivityVarsOk(), MembersModel\checkMyPreferences(), VerifymembersController\checkPasswordCallback(), VerifyMembersModel\checkPasswordsOfMembers(), MembersModel\checkProfileForm(), ActivitiesModel\checkSearchActivitiesVarsOk(), SearchModel\checkSearchVarsOk(), VerifyMembersModel\checkVerificationForm(), TripSingleTripPage\column_col3(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), AdminWordModel\createCodeFormCheck(), BlogView\createForm(), GalleryController\createGalleryCallback(), AdminWordModel\editCodeFormCheck(), ActivitiesController\editCreateActivityCallback(), SuggestionsController\editCreateSuggestionCallback(), BlogView\editForm(), SuggestionsController\editOptionCallback(), AdminWordModel\editTranslationFormCheck(), AdminWordModel\findTranslationsFormCheck(), ActivitiesController\joinLeaveActivityCallback(), AdminController\massmailEditCreateCallback(), AdminModel\massmailEditCreateVarsOk(), AdminController\massmailEnqueueCallback(), AdminModel\massmailEnqueueVarsOk(), MembersController\myPreferencesCallback(), User\registerProcess(), SignupModel\registerProcess(), ActivitiesController\searchActivitiesCallback(), SearchController\searchMembersCallback(), MembersModel\setLocation(), MembersController\setLocationCallback(), SignupController\signupFormCallback(), AdminController\treasurerEditCreateDonationCallback(), AdminModel\treasurerEditCreateDonationVarsOk(), AdminController\treasurerStartDonationCampaignCallback(), AdminModel\treasurerStartDonationCampaignVarsOk(), VerifymembersController\verifyCallback(), and SuggestionsController\voteSuggestionCallback().
$FeedbackEmail = isset($mem['FeedbackEmail']) ? $mem['FeedbackEmail'] : ''
Definition at line 48 of file feedback.column_col3.php.
if (isset($mem['redirect'])) if (isset($mem['data'])) $FeedbackQuestion = isset($mem['FeedbackQuestion']) ? $mem['FeedbackQuestion'] : ''
Definition at line 47 of file feedback.column_col3.php.
$IdCategory = '11'
Definition at line 25 of file feedback.column_col3.php.
if (isset($_GET['redirect'])&&$_GET['redirect']) if (isset($_GET['data'])&&$_GET['data']) $mem = $this->getRedirectedMem('post')
Definition at line 38 of file feedback.column_col3.php.
$redirect = ''
Definition at line 27 of file feedback.column_col3.php.
Referenced by MembersController\index_loggedIn().
$RequestURI = ''
Definition at line 26 of file feedback.column_col3.php.
$words = new MOD_words()
Definition at line 24 of file feedback.column_col3.php.
if (!$this->model->getLoggedInMember()) (in_array('FeedbackErrorBadEmail', $errors)) else
Definition at line 83 of file feedback.column_col3.php.
if($answernotneeded) echo"checked
Initial value:
='checked'";?>/> <label for="feedbackAnswernotneeded"> <?php echo $words->get("FeedBackIDoNotWantAnAnswer")?></label></p>
    </div> <!-- type-check -->
    <div class="type-button">
        <input type="submit" id="submit" name="submit" value="<?php echo $words->getSilent("FeedbackSubmit")
Definition at line 52 of file feedback.column_col3.php.