Rox: C:/xampp/htdocs/rox/build/rox/templates/footer.helper.php File Reference
footer.helper.php File Reference
Functions
_getVersionInfo ()
_getBugreportLink ()
translator_block ()
Variables
$words = new MOD_words()
$versionInfo = _getVersionInfo()
$mtime = filemtime(__FILE__)
$deploymentDate = date("j M Y", $mtime)
$deploymentDateTime = date(DATE_RSS, $mtime)
$bugreportLink = _getBugreportLink()
$query_list = PVars::get()->query_history
Function Documentation
_getBugreportLink ()
used in footer
Definition at line 34 of file footer.helper.php.
References $url.
_getVersionInfo ()
remove and use $versionInfo = $this->getVersionInfo(); instead once htdocs/bw/layout/footer.php is gone
Definition at line 13 of file footer.helper.php.
References $version.
translator_block ()
Definition at line 49 of file footer.helper.php.
References $words, a, MOD_right\get(), and translate().
Variable Documentation
$bugreportLink = _getBugreportLink()
Definition at line 45 of file footer.helper.php.
$deploymentDate = date("j M Y", $mtime)
Definition at line 28 of file footer.helper.php.
$deploymentDateTime = date(DATE_RSS, $mtime)
Definition at line 29 of file footer.helper.php.
$mtime = filemtime(__FILE__)
Definition at line 27 of file footer.helper.php.
Referenced by RSSCache\cache_age(), RSSCache\check_cache(), SimplePie_Misc\get_build(), and SimplePie_gzdecode\parse().
$query_list = PVars::get()->query_history
Definition at line 47 of file footer.helper.php.
$versionInfo = _getVersionInfo()
Definition at line 24 of file footer.helper.php.
$words = new MOD_words()
Definition at line 7 of file footer.helper.php.
Referenced by translator_block().