Rox: C:/xampp/htdocs/rox/build/groups/templates/groupstart.php File Reference
groupstart.php File Reference
Variables
endforeach
$group_name_html = htmlspecialchars($this->getGroupTitle(), ENT_QUOTES)
$purifier = MOD_htmlpure::getBasicHtmlPurifier()
if(!$this->isGroupMember()&&$this->
group->latestPost) $showNewTopicButton = false
$suggestionsGroupId = PVars::getObj('suggestions')->groupid
if($this->isGroupMember()) if ($group_id==$suggestionsGroupId)
if(!APP_user::isBWLoggedIn('NeedMore,
Pending')) else
switch ($model->getMembershipStatus($this->group, $memberId)) = $words->get('GroupMembers')
$memberlist_widget render()?>
</div >< p ><?php if($memberCount!if($memberCount==$visibleMemberCount) $relatedgroups = $this->group->findRelatedGroups($group_id)
Variable Documentation
$group_name_html = htmlspecialchars($this->getGroupTitle(), ENT_QUOTES)
Definition at line 5 of file groupstart.php.
Referenced by GroupJoinPage\column_col3().
$purifier = MOD_htmlpure::getBasicHtmlPurifier()
Definition at line 6 of file groupstart.php.
$memberlist_widget render () ?> </div> <p><?php if ($memberCount ! if ($memberCount==$visibleMemberCount) $relatedgroups = $this->group->findRelatedGroups($group_id)
Definition at line 134 of file groupstart.php.
Referenced by GroupDeleteRelatedGroupPage\column_col3(), and RelatedGroupsModel\getMyGroups().
if (!$this->isGroupMember()&&$this->group->latestPost) $showNewTopicButton = false
Definition at line 26 of file groupstart.php.
Referenced by ForumsController\showExternalGroupThreads().
$suggestionsGroupId = PVars::getObj('suggestions')->groupid
Definition at line 27 of file groupstart.php.
if (!empty($relatedgroups))foreach ($relatedgroups as $group_data) (strlen($group_data->Picture) > 0) else
Initial value:
{
                    $model = new GroupsModel()
Definition at line 47 of file groupstart.php.
endforeach
Definition at line 3 of file groupstart.php.
if ($this->isGroupMember()) if($group_id==$suggestionsGroupId)
Definition at line 31 of file groupstart.php.
switch ($model->$this->group, $memberId) = $words->get('GroupMembers')
Definition at line 82 of file groupstart.php.