Rox: C:/xampp/htdocs/rox/build/groups/templates/groupscreation.column_col3.php File Reference
groupscreation.column_col3.php File Reference
Variables
$layoutkit = $this->layoutkit
$words = $layoutkit->getWords()
$model = $this->getModel()
$page_url = PVars::getObj('env')->baseuri . implode('/', PRequest::get()->request)
$formkit = $layoutkit->formkit
$callback_tag = $formkit->setPostCallback('GroupsController', 'createGroupCallback')
if($redirected=$formkit->
mem_from_redirect) else
$GroupDesc_ = ''
$Type = false
$VisiblePosts = false
$problems = array()
Variable Documentation
$callback_tag = $formkit->setPostCallback('GroupsController', 'createGroupCallback')
Definition at line 10 of file groupscreation.column_col3.php.
$formkit = $layoutkit->formkit
Definition at line 9 of file groupscreation.column_col3.php.
$GroupDesc_ = ''
Definition at line 23 of file groupscreation.column_col3.php.
Referenced by GroupSettingsPage\column_col3().
$layoutkit = $this->layoutkit
Definition at line 3 of file groupscreation.column_col3.php.
$model = $this->getModel()
Definition at line 5 of file groupscreation.column_col3.php.
Referenced by DonateView\__construct(), OnlineView\__construct(), TripView\__construct(), BlogView\__construct(), GalleryView\__construct(), ShoutsView\__construct(), TourView\__construct(), ApiView\__construct(), ActivitiesView\__construct(), ForumsView\__construct(), UserView\__construct(), RoxView\__construct(), GeoView\__construct(), SearchmembersView\__construct(), BlogBasePage\__construct(), AdminView\__construct(), SignupView\__construct(), _languageOptions(), _languageSelector(), LinkShowFriendsPage\column_col3(), LinkDisplayPage\column_col3(), LinkRebuildPage\column_col3(), LinkSimplePage\column_col3(), LinkUpdatePage\column_col3(), LinkShowPage\column_col3(), NotifyAdminSettingsPage\column_col3(), OnlinePage\column_col3(), MessagesPageWithMailbox\column_col3(), NotifyAdminPage\column_col3(), DatabaseSummaryPage\column_col3(), InvitePage\column_col3(), AboutGenericPage\column_col3(), ReadMessagePage\column_col3(), GroupSettingsPage\column_col3(), GroupInvitePage\column_col3(), GroupMemberAdministrationPage\column_col3(), AboutController\feedbackCallback(), VerifymembersController\getMember(), MembersController\getMember(), RssController\index(), OnlineController\index(), TourController\index(), NewsletterController\index(), VerifymembersController\index(), PollsController\index(), MessagesController\index(), LinkController\index(), SignupController\index(), MembersController\index_loggedIn(), MembersController\index_loggedOut(), MessagesController\mailBoxCallback(), MessagesController\sendMessageCallback(), AbstractBasePage\setModel(), PageWithGivenRSS\setModel(), SignupController\signupFormCallback(), and OnlinePage\teaserContent().
$page_url = PVars::getObj('env')->baseuri . implode('/', PRequest::get()->request)
Definition at line 7 of file groupscreation.column_col3.php.
$problems = array()
Definition at line 26 of file groupscreation.column_col3.php.
Referenced by InvitePage\column_col3(), GroupSettingsPage\column_col3(), GroupsModel\createGroup(), InviteModel\sendOrComplain(), and MessagesModel\sendOrComplain().
$Type = false
Definition at line 24 of file groupscreation.column_col3.php.
Referenced by GroupSettingsPage\column_col3(), and Forums\reportpostProcess().
$VisiblePosts = false
Definition at line 25 of file groupscreation.column_col3.php.
Referenced by GroupSettingsPage\column_col3().
$words = $layoutkit->getWords()
Definition at line 4 of file groupscreation.column_col3.php.
if ($redirected=$formkit->mem_from_redirect) else
Initial value:
{
        $Group_ = ''
Definition at line 21 of file groupscreation.column_col3.php.