Rox: json_encode.php File Reference
json_encode.php File Reference
Functions
json_encode ($a=false)
Function Documentation
json_encode ($a = false)
This function is from http://de2.php.net/manual/en/function.json-encode.php#82904
It can replace the native json_encode function of php. It is only included if the native function is not found. (this can happen if we run an older php version)
Parameters
unknown_type $a
Returns
unknown
References $i.
Referenced by AdminController\getAdminUnits(), AdminController\getPlaces(), ApiView\jsonpResponse(), ApiView\jsonResponse(), GroupsController\memberSearchAjax(), AdminWordController\noUpdateNeeded(), RoxFrontRouter\runControllerAjaxMethod(), SearchController\searchSuggestLocations(), and SuggestionsController\voteAjaxRanking().