Rox: leaflet-test.js File Reference
leaflet-test.js File Reference
Functions
jQuery (document).ready(function()
Function Documentation
jQuery (document)
References L, and map.
Referenced by enableMultiSelect(), initOsmMap(), initTripMap(), loadMap(), monkeyPatchAutocomplete(), processVote(), and searchByAddressPoint().