Rox: C:/xampp/htdocs/rox/htdocs/script/main.js File Reference
main.js File Reference
Functions
function BWRox ()
bwrox selectScripts ([{file:"jquery-1.9.1.js", pages:["searchmembers","search","signup/3","setlocation","blog","trip","admin/massmail/enqueue","admin/word/list/update","suggestions/rank","activities/","about/faq","faq"]},{file:"jquery-ui-1.10.3.custom.min.js", pages:["activities","search"]},{file:"jquery-ui-timepicker-addon.js?1", pages:["activities"]},{file:"jquery-hashchange-1.4.min.js", pages:["about/faq","faq"]},{file:"leaflet/0.5.1/leaflet.js", pages:["searchmembers","signup/3","setlocation","blog","trip","activities"]},{file:"leaflet/plugins/Leaflet.markercluster/2013-04-09/leaflet.markercluster.js", pages:["activities"]},{file:"leaflet/plugins/Leaflet.markercluster/2013-04-09/include_markercluster_css.js", pages:["activities"]},{file:"//maps.googleapis.com/maps/api/js?sensor=false", remote:true, pages:["searchmembers","signup/3","setlocation","blog","trip"]},{file:"leaflet/plugins/Google.js", pages:["searchmembers","signup/3","setlocation","blog","trip"]},{file:"prototype162.js"},{file:"fabtabulous.js"},{file:"scriptaculous18/scriptaculous.js?load=effects,controls,builder,dragdrop"},{file:"registerrox.js", pages:["signup"]},{file:"geo_suggest.js?1", pages:["signup","setlocation"]},{file:"tinymce/tinymce.min.js", pages:["activities","blog","forums","groups","suggestions","trip"]},{file:"blog_suggest.js", pages:["blog","trip"]},{file:"act_suggest.js", pages:["activities"]},{file:"datepicker.js", pages:["activities","blog","trip","admin/treasurer"]},{file:"fieldset.js", pages:["blog/create","blog/edit","user/settings","trip/create","trip/edit","trip","gallery/show/image","message/write","editmyprofile","admin/massmail","members/"]},{file:"gallery.js", pages:["blog/create","editmyprofile"]},{file:"uploader.js", pages:["blog/create","editmyprofile"]},{file:"lightview.js", pages:["gallery","tour/meet"]},{file:"transition.js", pages:["thepeople"]},{file:"prototip.js?1", pages:["searchmembers"]},{file:"fancyzoom.js", pages:["members","editmyprofile","mypreferences","myvisitors","deleteprofile","people"]},{file:"util/console.js"},{file:"map/include_css.js?1", pages:["searchmembers","signup/3","setlocation","blog","trip","activities"]},{file:"map/geolocation/BWGoogleMapReverseGeolocator.js?1", pages:["searchmembers","signup/3","setlocation","blog","trip"]},{file:"map/leaflet/LeafletFlagIcon.js", pages:["signup/3","setlocation","blog","trip"]},{file:"map/builder/BWSimpleMapBuilder.js?1", pages:["signup/3","setlocation","blog","trip"]},{file:"map/builder/BWGeosearchMapBuilder.js", pages:["searchmembers"]},{file:"map/BWMapMaths.js", pages:["searchmembers","signup/3","setlocation","blog","trip"]},{file:"map/BWMapAddressPoint.js", pages:["searchmembers","signup/3","setlocation","blog","trip"]},{file:"map/BWMapHostPoint.js", pages:["searchmembers"]},{file:"map/BWMapSearchResult.js", pages:["searchmembers"]},{file:"map/small/smallMapGeoLocation.js", pages:["signup/3","setlocation"]},{file:"map/small/blogSmallMapGeoLocation.js?1", pages:["blog","trip"]},{file:"map/small/blogMap.js", pages:["blog"]},{file:"map/small/singlePost.js", pages:["blog"]},{file:"map/small/tripMap.js", pages:["trip"]},{file:"searchmembers.js?1", pages:["searchmembers"]},{file:"search/search.js", pages:["search"]},{file:"map/activities/activities_map.js", pages:["activities"]}])
Variables
var agt = navigator.userAgent.toLowerCase()
var is_op = (agt.indexOf("opera") != -1)
var is_ie = (agt.indexOf("msie") != -1) && document.all && !is_op
var is_ie5 = (agt.indexOf("msie 5") != -1) && document.all && !is_op
var is_mac = (agt.indexOf("mac") != -1)
var is_gk = (agt.indexOf("gecko") != -1)
var is_sf = (agt.indexOf("safari") != -1)
var is_kq = (agt.indexOf("konqueror") != -1)
var http_baseuri = new String(document.getElementById('baseuri').href)
var req = new String(location.pathname).toLowerCase()
var loc = new String(location)
BWRox prototype selectScripts
BWRox prototype includeScript
var bwrox = new BWRox
Function Documentation
function BWRox ()
Creating "BWRox" namespace.
Definition at line 32 of file main.js.
bwrox selectScripts ([{file:"jquery-1.9.1.js", pages:["searchmembers","search","signup/3","setlocation","blog","trip","admin/massmail/enqueue","admin/word/list/update","suggestions/rank","activities/","about/faq","faq"] } , {file:"jquery-ui-1.10.3.custom.min.js", pages:["activities","search"]} , {file:"jquery-ui-timepicker-addon.js?1", pages:["activities"]} , {file:"jquery-hashchange-1.4.min.js", pages:["about/faq","faq"]} , {file:"leaflet/0.5.1/leaflet.js", pages:["searchmembers","signup/3","setlocation","blog","trip","activities"]} , {file:"leaflet/plugins/Leaflet.markercluster/2013-04-09/leaflet.markercluster.js", pages:["activities"]} , {file:"leaflet/plugins/Leaflet.markercluster/2013-04-09/include_markercluster_css.js", pages:["activities"]} , {file:"//maps.googleapis.com/maps/api/js?sensor=false", remote:true, pages:["searchmembers","signup/3","setlocation","blog","trip"]} , {file:"leaflet/plugins/Google.js", pages:["searchmembers","signup/3","setlocation","blog","trip"]} , {file:"prototype162.js"} , {file:"fabtabulous.js"} , {file:"scriptaculous18/scriptaculous.js?load=effects,controls,builder,dragdrop"} , {file:"registerrox.js", pages:["signup"]} , {file:"geo_suggest.js?1", pages:["signup","setlocation"]} , {file:"tinymce/tinymce.min.js", pages:["activities","blog","forums","groups","suggestions","trip"]} , {file:"blog_suggest.js", pages:["blog","trip"]} , {file:"act_suggest.js", pages:["activities"]} , {file:"datepicker.js", pages:["activities","blog","trip","admin/treasurer"]} , {file:"fieldset.js", pages:["blog/create","blog/edit","user/settings","trip/create","trip/edit","trip","gallery/show/image","message/write","editmyprofile","admin/massmail","members/"]} , {file:"gallery.js", pages:["blog/create","editmyprofile"]} , {file:"uploader.js", pages:["blog/create","editmyprofile"]} , {file:"lightview.js", pages:["gallery","tour/meet"]} , {file:"transition.js", pages:["thepeople"]} , {file:"prototip.js?1", pages:["searchmembers"]} , {file:"fancyzoom.js", pages:["members","editmyprofile","mypreferences","myvisitors","deleteprofile","people"]} , {file:"util/console.js"} , {file:"map/include_css.js?1", pages:["searchmembers","signup/3","setlocation","blog","trip","activities"]} , {file:"map/geolocation/BWGoogleMapReverseGeolocator.js?1", pages:["searchmembers","signup/3","setlocation","blog","trip"]} , {file:"map/leaflet/LeafletFlagIcon.js", pages:["signup/3","setlocation","blog","trip"]} , {file:"map/builder/BWSimpleMapBuilder.js?1", pages:["signup/3","setlocation","blog","trip"]} , {file:"map/builder/BWGeosearchMapBuilder.js", pages:["searchmembers"]} , {file:"map/BWMapMaths.js", pages:["searchmembers","signup/3","setlocation","blog","trip"]} , {file:"map/BWMapAddressPoint.js", pages:["searchmembers","signup/3","setlocation","blog","trip"]} , {file:"map/BWMapHostPoint.js", pages:["searchmembers"]} , {file:"map/BWMapSearchResult.js", pages:["searchmembers"]} , {file:"map/small/smallMapGeoLocation.js", pages:["signup/3","setlocation"]} , {file:"map/small/blogSmallMapGeoLocation.js?1", pages:["blog","trip"]} , {file:"map/small/blogMap.js", pages:["blog"]} , {file:"map/small/singlePost.js", pages:["blog"]} , {file:"map/small/tripMap.js", pages:["trip"]} , {file:"searchmembers.js?1", pages:["searchmembers"]} , {file:"search/search.js", pages:["search"]} , {file:"map/activities/activities_map.js", pages:["activities"]}])
Variable Documentation
var agt = navigator.userAgent.toLowerCase()
Definition at line 15 of file main.js.
var bwrox = new BWRox
Definition at line 83 of file main.js.
Referenced by addMarkers(), calculateDistance(), displayMap(), initMap(), initOsmMap(), initOsmMapBlogEdit(), initTripMap(), loadMap(), searchByAddressPoint(), and searchByText().
var http_baseuri = new String(document.getElementById('baseuri').href)
Definition at line 25 of file main.js.
Referenced by newWindow().
BWRox prototype includeScript
Initial value:
= function(src) {
  document.write('<script type="text/javascript" src="' + src + '"></script>');
}
Include a JavaScript file.
Parameters
{string} src Location of script file.
Definition at line 76 of file main.js.
var is_gk = (agt.indexOf("gecko") != -1)
Definition at line 21 of file main.js.
var is_ie = (agt.indexOf("msie") != -1) && document.all && !is_op
Definition at line 18 of file main.js.
Referenced by InactiveProfilePage::leftsidebar(), and MemberPage::leftsidebar().
var is_ie5 = (agt.indexOf("msie 5") != -1) && document.all && !is_op
Definition at line 19 of file main.js.
var is_kq = (agt.indexOf("konqueror") != -1)
Definition at line 23 of file main.js.
var is_mac = (agt.indexOf("mac") != -1)
Definition at line 20 of file main.js.
var is_op = (agt.indexOf("opera") != -1)
Definition at line 17 of file main.js.
var is_sf = (agt.indexOf("safari") != -1)
Definition at line 22 of file main.js.
var loc = new String(location)
Definition at line 27 of file main.js.
var req = new String(location.pathname).toLowerCase()
Definition at line 26 of file main.js.
Referenced by LoadMap(), and loadMap().
BWRox prototype selectScripts
Initial value:
= function(scripts) {
  for (var i = 0; i < scripts.length; i++) {
    var script = scripts[i];
    if (typeof script.remote === "boolean" && script.remote === true) {
      var prefix = '';
    } else {
      var prefix = 'script/';
    }
    var src = prefix + script.file;
    if (typeof(script.pages) == 'object' && script.pages.length > 0) {
      for (var j = 0; j < script.pages.length; j++) {
        var currentPage = req.substring(1, req.length);
        if (currentPage.indexOf(script.pages[j]) == 0) {
          this.includeScript(src);
        }
      }
    } else {
      this.includeScript(src);
    }
  }
}
Select scripts to include on current page.
Parameters
{array} scripts Object list with available scripts, object properties:
file: Script file name, relative to scripts folder
pages: Array with names of pages the script should be included on. Matches if request path starts with given page name (pattern: "^name.*"). If pages property is omitted the script will be included on every page.
Definition at line 43 of file main.js.