Rox: C:/xampp/htdocs/rox/build/members/templates/member.teasercontent.helper.php File Reference
member.teasercontent.helper.php File Reference
Variables
$member = $this->member
$lang = $this->model->get_profile_language()
$profile_language = $lang->id
$profile_language_code = $lang->ShortCode
$words = $this->getWords()
$ww = $this->ww
$wwsilent = $this->wwsilent
$comments_count = $member->count_comments()
$layoutbits = new MOD_layoutbits
$right = new MOD_right()
$verification_status = $member->verification_status
$agestr = ""
if($member->age=="hidden") else
Variable Documentation
$agestr = ""
Definition at line 20 of file member.teasercontent.helper.php.
$comments_count = $member->count_comments()
Definition at line 12 of file member.teasercontent.helper.php.
Referenced by MemberPage\getSubmenuItems().
$lang = $this->model->get_profile_language()
Definition at line 5 of file member.teasercontent.helper.php.
$layoutbits = new MOD_layoutbits
Definition at line 14 of file member.teasercontent.helper.php.
$member = $this->member
Definition at line 3 of file member.teasercontent.helper.php.
$profile_language = $lang->id
Definition at line 6 of file member.teasercontent.helper.php.
$profile_language_code = $lang->ShortCode
Definition at line 7 of file member.teasercontent.helper.php.
$right = new MOD_right()
Definition at line 15 of file member.teasercontent.helper.php.
Referenced by MOD_user_Auth\checkRight(), Member\get_crypted(), MOD_user\hasRight(), MOD_user_Auth\hasRight(), and MOD_user_Auth\rightExists().
$verification_status = $member->verification_status
Definition at line 17 of file member.teasercontent.helper.php.
$words = $this->getWords()
Definition at line 9 of file member.teasercontent.helper.php.
$ww = $this->ww
Definition at line 10 of file member.teasercontent.helper.php.
$wwsilent = $this->wwsilent
Definition at line 11 of file member.teasercontent.helper.php.
Referenced by VisualComponent\__call(), GalleryUserPage\getSubmenuItems(), MemberPage\getSubmenuItems(), GallerySetPage\getSubmenuItems(), and LoginFormWidget\render().
if ($member->age=="hidden") else
Initial value:
{
    if ($this->passedAway) {
        $agestr= $ww->AgeEqualX($layoutbits->fage_value($member->BirthDate, substr($member->updated, 0, 10)));
    } else {
        $agestr= $ww->AgeEqualX($layoutbits->fage_value($member->BirthDate));
    }
}
$occupation = $member->get_trad("Occupation", $profile_language,true)
Definition at line 23 of file member.teasercontent.helper.php.