Rox: C:/xampp/htdocs/rox/build/members/templates/mypreferences.column_col3.helper.php File Reference
mypreferences.column_col3.helper.php File Reference
Functions
cmpPrefLang ($a, $b)
Variables
$words = $this->getWords()
$layoutkit = $this->layoutkit
$formkit = $layoutkit->formkit
$callback_tag = $formkit->setPostCallback('MembersController', 'myPreferencesCallback')
$flaglist = new FlaglistModel()
$languages = $flaglist->getLanguages()
$value = $this->member->get_publicProfile()
$pref_publicprofile = (isset($value) && $value) ? true : false
$p = $this->member->preferences
$baseuri = PVars::getObj('env')->baseuri
if(PVars::getObj('env') ->
force_ssl_sensitive) if(!isset($p['PreferenceLanguage']->
Value)) $ii = 1
if(!$memory=$formkit->
getMemFromRedirect()) else
Function Documentation
cmpPrefLang ($a, $b)
Definition at line 2 of file mypreferences.column_col3.helper.php.
Variable Documentation
$baseuri = PVars::getObj('env')->baseuri
Definition at line 25 of file mypreferences.column_col3.helper.php.
Referenced by VisualComponent\__call(), SignupPage\column_col3(), PageWithHTML\head(), and LoginFormWidget\render().
$callback_tag = $formkit->setPostCallback('MembersController', 'myPreferencesCallback')
Definition at line 13 of file mypreferences.column_col3.helper.php.
$flaglist = new FlaglistModel()
Definition at line 14 of file mypreferences.column_col3.helper.php.
$formkit = $layoutkit->formkit
Definition at line 12 of file mypreferences.column_col3.helper.php.
if (PVars::getObj('env') ->force_ssl_sensitive) if (!isset($p['PreferenceLanguage']->Value)) $ii = 1
Definition at line 36 of file mypreferences.column_col3.helper.php.
$languages = $flaglist->getLanguages()
Definition at line 15 of file mypreferences.column_col3.helper.php.
$layoutkit = $this->layoutkit
Definition at line 11 of file mypreferences.column_col3.helper.php.
$p = $this->member->preferences
Definition at line 22 of file mypreferences.column_col3.helper.php.
$pref_publicprofile = (isset($value) && $value) ? true : false
Definition at line 21 of file mypreferences.column_col3.helper.php.
$value = $this->member->get_publicProfile()
Definition at line 20 of file mypreferences.column_col3.helper.php.
Referenced by SimplePie_File\__construct(), ObjectWithInjection\__set(), ReadAndAddObject\__set(), ReadWriteObject\__set(), SessionMemory\__set(), RoxGenericPage_OLD\__set(), RoxComponentBase\__set(), SimplePie_IRI\__set(), RoxController\_redirectLevel(), SafeHTML\_writeAttrs(), GeoModel\addGeonameId(), APP_User\addSetting(), MOD_bw_memcache\AddValue(), SimplePie_Locator\body(), SimplePie_Net_IPv6\check_ipv6(), LinkShowFriendsPage\column_col3(), ExtensionsPage\column_col3(), LinkShowPage\column_col3(), SignupPage\column_col3(), RoxLoader\create_ini_file(), LinkModel\createLinkList(), LinkModel\createPath(), MessagesModel\DisplayCaptcha(), EditProfilePage\editMyProfileFormPrepare(), SimplePie_Misc\element_implode(), SimplePie_Locator\extension(), RoxLoader\get(), SimplePie_Item\get_enclosures(), SimplePie_XML_Declaration_Parser\get_value(), LinkModel\getFriends(), LinkModel\getFriendsFull(), LinkModel\getLinkPreferences(), LinkModel\getLinks(), LinkModel\getLinksFull(), LinkModel\getMemberdata(), Member\getPreference(), SearchModel\getResultsForLocation(), LinkModel\getTree(), MOD_bw_memcache\GetValue(), RoxLocalSettingsImporter\importConfigPHP(), PageWithHTML\includeJsConfig(), DebugController\index(), RequestRouter\iniParse(), ObjectWithInjection\inject(), RoxLoader\load(), BlogEntity\loadEntity(), ExceptionLogger\logException(), SimplePie_Misc\parse_str(), LinkModel\rebuildLinks(), LinkModel\rebuildMissingLinks(), SimplePie_IRI\remove_iunreserved_percent_encoded(), RoxGenericPage_OLD\render(), SimplePie_IRI\replace_invalid_with_pct_encoding(), SimplePie_Sanitize\replace_urls(), MOD_bw_memcache\ReplaceValue(), GeoController\SelectorCallback(), GeoController\SelectorInclude(), FeedbackModel\sendFeedback(), SimplePie\set_feed_url(), MOD_i18n\setEnvVar(), MembersController\setLocationCallback(), ItemlistWidget\showItems_float(), ItemlistWidget\showItems_table(), RoxTemplate\showTemplate(), SignupController\signupFormCallback(), SimplePie_Sanitize\strip_tag(), DatabaseSummaryWidget\tableCell(), DatabaseSummaryWidget\tableCell_name(), SimplePie_Parser\tag_open(), BlogEntity\update(), GeoModel\updateGeoCounters(), GeoModel\updateGeonameId(), and RoxEntityBase\validateField().
$words = $this->getWords()
Definition at line 10 of file mypreferences.column_col3.helper.php.
if (!$memory=$formkit->getMemFromRedirect()) else
Definition at line 40 of file mypreferences.column_col3.helper.php.