Rox: personalstart.teasercontent.php File Reference
personalstart.teasercontent.php File Reference
Functions
setMap (geonameid, latitude, longitude, zoom, geonamename, countryname, countrycode, admincode)
init ()
Variables
if(!$ShowDonateBar) if($ShowDonateBar) if (isset($_mainPageNewMessagesMessage)) =$words->getSilent('InviteAFriend')
geonamename geonamecountry $vars ['geonamename']
geonamename geonamecountry
$vars['geonamecountry'] var marker = new GMarker(new GLatLng('.$vars['latitude'].', '.$vars['longitude'].'), '.$desc.')
geonameid latitude longitude
geonamename countryname
geonamecountrycode admincode
countryname newgeo locations
window onunload = GUnload
Function Documentation
init ()
Referenced by !function(), if(), GalleryUploadPage\init(), Member\init(), and MOD_mail\sendEmail().
setMap (geonameid , latitude , longitude , zoom , geonamename , countryname , countrycode , admincode)
Variable Documentation
geonamename geonamecountry $vars['geonamename']
if (!$ShowDonateBar) if ($ShowDonateBar) if(isset($_mainPageNewMessagesMessage)) =$words->getSilent('InviteAFriend')
geonameid latitude longitude geonamename countryname geonamecountrycode admincode countryname newgeo locations
geonamename geonamecountry $vars ['geonamecountry'] var marker = new GMarker(new GLatLng('.$vars['latitude'].', '.$vars['longitude'].'), '.$desc.')
Referenced by addMarkers(), createMarker(), displayMap(), initTripMap(), LoadMap(), MarkerManager(), and setupOfficeMarkers().
window onunload = GUnload