Rox: C:/xampp/htdocs/rox/build/rox/templates/personalstart.column_col3.helper.php File Reference
personalstart.column_col3.helper.php File Reference
Variables
$Forums = new ForumsController
$citylatlong = $this->model->getAllCityLatLong()
$google_conf = PVars::getObj('config_google')
$roxModelBase = new RoxModelBase()
$member = $roxModelBase->getLoggedInMember()
$preference = $member->getPreference('PreferenceShowProfileVisits', 'Yes')
if($preference== 'Yes') else
$Blog = new Blog()
$postIt = $Blog->getTaggedPostsIt('Community News for the frontpage', true)
$format = array('short'=>$words->getSilent('DateFormatShort'))
Variable Documentation
$Blog = new Blog()
Definition at line 21 of file personalstart.column_col3.helper.php.
$citylatlong = $this->model->getAllCityLatLong()
Definition at line 4 of file personalstart.column_col3.helper.php.
Referenced by RoxView\mainpage().
$format = array('short'=>$words->getSilent('DateFormatShort'))
Definition at line 23 of file personalstart.column_col3.helper.php.
$Forums = new ForumsController
Definition at line 3 of file personalstart.column_col3.helper.php.
Referenced by GroupStartPage\column_col3(), GroupForumPage\column_col3(), GroupForumsOverviewPage\column_col3(), and RoxView\mainpage().
$google_conf = PVars::getObj('config_google')
Definition at line 5 of file personalstart.column_col3.helper.php.
Referenced by TripSingleTripPage\column_col3(), BlogCreatePage\column_col3(), BlogEditPage\column_col3(), BlogView\createForm(), BlogView\editForm(), GeoModel\getGeonamesHierarchy(), SearchmembersController\index(), RoxView\mainpage(), SearchmembersView\search_column_col3(), SearchmembersView\searchmembers(), and GeoModel\suggestLocation().
$member = $roxModelBase->getLoggedInMember()
Definition at line 10 of file personalstart.column_col3.helper.php.
$postIt = $Blog->getTaggedPostsIt('Community News for the frontpage', true)
Definition at line 22 of file personalstart.column_col3.helper.php.
$preference = $member->getPreference('PreferenceShowProfileVisits', 'Yes')
Definition at line 13 of file personalstart.column_col3.helper.php.
Referenced by Member\getPreference(), and Forums\switchShowMyGroupsTopicsOnly().
$roxModelBase = new RoxModelBase()
Definition at line 9 of file personalstart.column_col3.helper.php.
Referenced by RoxFrontRouter\initUser().
if ($preference== 'Yes') else
Initial value:
{
    $showVisitors = false
Definition at line 16 of file personalstart.column_col3.helper.php.