Rox: C:/xampp/htdocs/rox/build/members/templates/profile.subcolumn_left.php File Reference
profile.subcolumn_left.php File Reference
Variables
if ($showEditLinks)
endif
$purifier = MOD_htmlpure::getAdvancedHtmlPurifier()
$my_groups = $member->getGroups()
$group_id = $my_groups[$i]->id
$group_name = htmlspecialchars($my_groups[$i]->Name, ENT_QUOTES)
$comment = $purifier->purify($words->mInTrad($member->getGroupMembership($my_groups[$i])->Comment,$profile_language))
echo;endfor;echo;endif;?>if ($this->model->getLoggedInMember()&&!$this->passedAway) ($showEditLinks)
Variable Documentation
$comment = $purifier->purify($words->mInTrad($member->getGroupMembership($my_groups[$i])->Comment,$profile_language))
Definition at line 132 of file profile.subcolumn_left.php.
Referenced by GroupsController\changeMemberSettings(), AddRelationPage\column_col3(), LinkSimplePage\column_col3(), AdminModel\createDonation(), LinkModel\createLinkList(), LinkModel\getChanges(), MembersModel\reportBadComment(), SimplePie_Sanitize\sanitize(), AdminModel\updateDonation(), GroupMembership\updateMembership(), GroupsModel\updateMembershipSettings(), and MembersModel\writeNoteForMember().
$group_id = $my_groups[$i]->id
Definition at line 130 of file profile.subcolumn_left.php.
Referenced by Gallery\__construct(), GalleryComment\__construct(), GalleryItem\__construct(), Forums\checkGroupMembership(), GroupStartPage\column_col3(), GroupWikiPage\column_col3(), GroupForumPage\column_col3(), GroupSettingsPage\column_col3(), GroupMembership\getGroupMembers(), GroupMembership\getGroupMembersCount(), GroupMembership\getMembership(), GroupsBasePage\getSubmenuItems(), GroupMembership\isMember(), GroupMembership\memberJoin(), GroupMembership\memberLeave(), and ForumsView\showTopic().
$group_name = htmlspecialchars($my_groups[$i]->Name, ENT_QUOTES)
Definition at line 131 of file profile.subcolumn_left.php.
Referenced by Group\createGroup().
$my_groups = $member->getGroups()
Definition at line 114 of file profile.subcolumn_left.php.
$purifier = MOD_htmlpure::getAdvancedHtmlPurifier()
Definition at line 10 of file profile.subcolumn_left.php.
echo; endfor; echo ; endif;?>if ($this->model->getLoggedInMember()&&!$this->passedAway)($showEditLinks)
Definition at line 152 of file profile.subcolumn_left.php.
endif
Definition at line 7 of file profile.subcolumn_left.php.
if ($member->get_trad("Hobbies", $profile_language, true)!="") if ($member->get_trad("Books", $profile_language, true)!="") if ($member->get_trad("Music", $profile_language, true)!="") if ($member->get_trad("Movies", $profile_language, true)!="") if ($member->get_trad("Organizations", $profile_language, true)!="") echo; } if ($member->get_trad("PastTrips", $profile_language,true) != "" || $member->get_trad("PlannedTrips", $profile_language,true) != "") {?><divid="travel"class="floatboxbox"> if($showEditLinks) ($showEditLinks)
Definition at line 3 of file profile.subcolumn_left.php.