Rox: profileversion.php File Reference
profileversion.php File Reference
Functions
cmpProfileLang ($a, $b)
indexedLanguages ($languages)
sortLanguages ($languages)
Variables
$lang = $this->model->get_profile_language()
$profile_language = $lang->id
$profile_language_code = $lang->ShortCode
$profile_language_name = $lang->Name
$languages = indexedLanguages($member->profile_languages)
$languages_spoken = indexedLanguages($member->languages_spoken)
$all_written_languages = sortLanguages($member->get_all_translatable_languages())
$words = $this->getWords()
$myself = $this->myself
Function Documentation
cmpProfileLang ($a, $b)
indexedLanguages ($languages)
References $lang, and $languages.
Referenced by sortLanguages().
sortLanguages ($languages)
References $languages, $words, and indexedLanguages().
Variable Documentation
$all_written_languages = sortLanguages($member->get_all_translatable_languages())
$lang = $this->model->get_profile_language()
Referenced by indexedLanguages().
$languages = indexedLanguages($member->profile_languages)
Referenced by indexedLanguages(), and sortLanguages().
$languages_spoken = indexedLanguages($member->languages_spoken)
$myself = $this->myself
$profile_language = $lang->id
$profile_language_code = $lang->ShortCode
$profile_language_name = $lang->Name
$words = $this->getWords()
Referenced by sortLanguages().