Rox: C:/xampp/htdocs/rox/build/members/templates/profile.subcolumn_right.php File Reference
profile.subcolumn_right.php File Reference
Variables
if (!$this->passedAway) ($showEditLinks)
endif
$icons = array()
switch($member->Accomodation)
if(strstr($member->TypicOffer,"CanHostWeelChair"))
if(strstr($member->TypicOffer,"guidedtour"))
if(strstr($member->TypicOffer,"dinner"))
if(strstr($member->
Restrictions,"NoSmoker")) if(strstr($member->
Restrictions,"NoAlchool")) if(strstr($member->
Restrictions,"NoDrugs")) $modul = count($icons) < 5 ? $modul = 5 : $modul = 2
for($ii=0;$ii< count($icons);$ii++)
if($member->MaxGuest!=0
&&$member->MaxGuest!="") if($member->
get_trad("MaxLenghtOfStay",
$profile_language, true)!="")
if($member->get_trad("ILiveWith",
$profile_language, true)!="")
if($member->get_trad("PleaseBring",
$profile_language, true)!="")
if($member->get_trad("OfferGuests",
$profile_language, true)!="")
if($member->get_trad("OfferHosts",
$profile_language, true)!="")
if($member->get_trad("AdditionalAccomodationInfo",
$profile_language, true)!=""or
$member->get_trad("InformationToGuest",
$profile_language, true)!="")
if($member->get_trad("PublicTransport",
$profile_language, true)!="") $TabRestrictions = explode(",", $member->Restrictions)
$max = count($TabRestrictions)
<?if(isset($_SESSION["IdMember"])&&strcmp($member-> id
<?if(isset($_SESSION["IdMember"])&&strcmp($member->
$_SESSION["IdMember"] $purifier = MOD_htmlpure::getBasicHtmlPurifier()
$relations = $member->relations
if(count($relations) > 0) $comments = $this->member->comments
$username = $this->member->Username
$layoutbits = new MOD_layoutbits()
if(count($comments) > 0) if($comingposts=$member->
getComingPosts()) $userid = $member->userid
$gallery = new GalleryModel
$statement = $userid ? $gallery->getLatestItems($userid) : false
Variable Documentation
if (count($relations) > 0) $comments = $this->member->comments
Definition at line 183 of file profile.subcolumn_right.php.
$gallery = new GalleryModel
Definition at line 281 of file profile.subcolumn_right.php.
Referenced by GalleryDeletePage\column_col3(), GallerySetDetailsPage\column_col3(), GalleryPage\column_col3(), GallerySetPage\column_col3(), GalleryController\deleteGallery(), GalleryController\gallery(), GalleryController\gallerydetails(), Member\getGalleryItemsCount(), GallerySetPage\getSubmenuItems(), and GalleryController\index().
$icons = array()
Definition at line 11 of file profile.subcolumn_right.php.
Referenced by GetOfferIcons(), and GetRestrictionIcons().
$layoutbits = new MOD_layoutbits()
Definition at line 185 of file profile.subcolumn_right.php.
$max = count($TabRestrictions)
Definition at line 110 of file profile.subcolumn_right.php.
switch ($member->Accomodation) if (strstr($member->TypicOffer,"CanHostWeelChair")) if (strstr($member->TypicOffer,"guidedtour")) if (strstr($member->TypicOffer,"dinner")) if (strstr($member->Restrictions,"NoSmoker")) if (strstr($member->Restrictions,"NoAlchool")) if (strstr($member->Restrictions,"NoDrugs")) $modul = count($icons) < 5 ? $modul = 5 : $modul = 2
Definition at line 53 of file profile.subcolumn_right.php.
<?if(isset($_SESSION["IdMember"])&&strcmp($member-> $_SESSION ["IdMember"] $purifier = MOD_htmlpure::getBasicHtmlPurifier()
Definition at line 144 of file profile.subcolumn_right.php.
$relations = $member->relations
Definition at line 145 of file profile.subcolumn_right.php.
Referenced by LinkModel\getChanges().
$statement = $userid ? $gallery->getLatestItems($userid) : false
Definition at line 282 of file profile.subcolumn_right.php.
Referenced by GalleryController\ajaxlatestimages(), GalleryAllImagesPage\column_col3(), GalleryUserImagesPage\column_col3(), GalleryUserOverviewPage\column_col3(), GallerySetDetailsPage\column_col3(), GalleryDeletePage\column_col3(), GalleryGalleriesPage\column_col3(), GalleryPage\column_col3(), GalleryAllGalleriesPage\column_col3(), GalleryManagePage\column_col3(), GalleryUserGalleriesPage\column_col3(), GalleryOverviewPage\column_col3(), GallerySetPage\column_col3(), and GalleryUserPage\column_col3().
for ($ii=0;$ii< count($icons);$ii++) if ($member->MaxGuest!=0 &&$member->MaxGuest!="") if ($member->get_trad("MaxLenghtOfStay", $profile_language, true)!="") if ($member->get_trad("ILiveWith", $profile_language, true)!="") if ($member->get_trad("PleaseBring", $profile_language, true)!="") if ($member->get_trad("OfferGuests", $profile_language, true)!="") if ($member->get_trad("OfferHosts", $profile_language, true)!="") if ($member->get_trad("AdditionalAccomodationInfo", $profile_language, true)!=""or $member->get_trad("InformationToGuest", $profile_language, true)!="") if ($member->get_trad("PublicTransport", $profile_language, true)!="") $TabRestrictions = explode(",", $member->Restrictions)
Definition at line 109 of file profile.subcolumn_right.php.
Referenced by MembersModel\polishProfileFormValues().
if (count($comments) > 0) if ($comingposts=$member->getComingPosts()) $userid = $member->userid
Definition at line 280 of file profile.subcolumn_right.php.
Referenced by Blog\getCategoryFromUserIt().
$username = $this->member->Username
Definition at line 184 of file profile.subcolumn_right.php.
if (!$this->passedAway)($showEditLinks)
Definition at line 1 of file profile.subcolumn_right.php.
if (($max > 0 and $TabRestrictions[0]!="") or($member->Restrictions!="")) endif
Definition at line 7 of file profile.subcolumn_right.php.
<?if(isset($_SESSION["IdMember"])&&strcmp($member-> id
Definition at line 136 of file profile.subcolumn_right.php.