Rox: C:/xampp/htdocs/rox/templates/apps/user/registerform.php File Reference
registerform.php File Reference
Variables
$User = new User
$callbackId = $User->registerProcess()
$vars =& PPostHandler::getVars($callbackId)
$request = PRequest::get()->request
$regText = array()
$errors = array()
$i18n = new MOD_i18n('apps/user/register.php')
$error = $i18n->getText('errors')
if($User=APP_User::login()) if(!isset($request[2])||$request[2]!=
'finish') else {
Variable Documentation
$callbackId = $User->registerProcess()
Definition at line 5 of file registerform.php.
$error = $i18n->getText('errors')
Definition at line 19 of file registerform.php.
Referenced by PollsPage\__construct(), GroupJoinPage\column_col3(), DonateController\index(), TripController\index(), BlogController\index(), SignupController\index(), SearchmembersController\index(), UserController\index(), SimplePie_Parser\parse(), GeoModel\RenewGeo(), DonateModel\returnFromPayPal(), Rox\returnFromPayPal(), RoxFrontRouter\try_unserialize(), and GalleryModel\uploadProcess().
$errors = array()
Definition at line 16 of file registerform.php.
$i18n = new MOD_i18n('apps/user/register.php')
Definition at line 17 of file registerform.php.
$regText = array()
Definition at line 15 of file registerform.php.
$request = PRequest::get()->request
Definition at line 9 of file registerform.php.
$User = new User
Definition at line 3 of file registerform.php.
$vars =& PPostHandler::getVars($callbackId)
Definition at line 7 of file registerform.php.
if ($User=APP_User::login()) if (!isset($request[2])||$request[2]!= 'finish') else {
Definition at line 107 of file registerform.php.