Rox: C:/xampp/htdocs/rox/build/forums/templates/reportslist.php File Reference
reportslist.php File Reference
Variables
$request = PRequest::get()->request
if(!isset($vars['errors'])||!is_array($vars['errors'])) $list =$DataPost
$words = new MOD_words()
$styles = array('highlight', 'blank')
$iiMax = count($list)
Variable Documentation
$iiMax = count($list)
Definition at line 37 of file reportslist.php.
Referenced by LastCommentsPage\column_col3().
if (!isset($vars['errors'])||!is_array($vars['errors'])) $list =$DataPost
Definition at line 33 of file reportslist.php.
Referenced by VerifiedApprovedVerifiers\column_col3(), and SafetyModel\getListOfMembers().
$request = PRequest::get()->request
Definition at line 27 of file reportslist.php.
$styles = array('highlight', 'blank')
Definition at line 36 of file reportslist.php.
$words = new MOD_words()
Definition at line 35 of file reportslist.php.