Rox: C:/xampp/htdocs/rox/build/search/templates/searchmemberstext.column_col3.php File Reference
searchmemberstext.column_col3.php File Reference
Functions
ShowAccommodation ($accom, $Accommodation)
GetOfferIcons ($offer)
GetRestrictionIcons ($restrictions)
Variables
$errors = $this->getRedirectedMem('errors')
$vars = $this->getRedirectedMem('vars')
if(empty($vars)) $members = array ()
$locations = array ()
$results = $this->getRedirectedMem('results')
if($results) $Accommodation = array()
$Accommodation ['anytime'] = $words->getBuffered('Accomodation_anytime')
$Accommodation ['dependonrequest'] = $words->getBuffered('Accomodation_dependonrequest')
$Accommodation ['neverask'] = $words->getBuffered('Accomodation_neverask')
$orderBy = array()
$orderArray = SearchModel::getOrderByArray()
$orderBy [$key+1] = $words->getSilent($orderArray[$key]['WordCode']. 'Desc')
endforeach
$layoutbits = new MOD_layoutbits()
endif
$canHost = array(1 => '1', 2 => '2', 3 => '3', 4 => '4', 5 => '5', 10 => '10', 20 => '20')
foreach($canHost as $value=>
$display) if ($value==$vars['search-can-host'])
$distance = array(0 => $words->getSilent("SearchExactMatch"), 5 => '5 km/3 mi', 10 => '10 km/6 mi', 25 => '25 km/15 mi', 50 => '50 km/30 mi', 100 => '100 km/60 mi')
foreach($distance as $value=>
$display) if ($value==$vars['search-distance'])
if($this->showAdvanced) $numberOfItems = array('5', '10', '20', '50', '100')
$select = '<select name="search-number-items">'
if(!empty($members))(!$this->
member) $params = new StdClass
$params strategy = new FullPagePager()
$params page_url = "/search/members/text?" . http_build_query($vars)
$params page_url_marker = 'search-page-'
$params page_method = 'form'
if($this->member) else
$params active_page = $vars['search-page-current']
$params items_per_page = $vars['search-number-items']
$pager = new PagerWidget($params)
$ii = 0
if(isset($results['biggest']))
foreach($results['biggest'] as
$big)($big->cnt >0)($i%3) break
case __pad0__
case __pad1__
endswitch
else __pad2__
else $big cnt
$i
case __pad3__
case __pad4__
else __pad5__
case admin1s
case __pad6__
case __pad7__
case countries
case __pad8__
case __pad9__
Function Documentation
GetOfferIcons ($offer)
Definition at line 389 of file searchmemberstext.column_col3.php.
References $icons, and $words.
GetRestrictionIcons ($restrictions)
Definition at line 408 of file searchmemberstext.column_col3.php.
References $icons, and $words.
ShowAccommodation ($accom, $Accommodation)
Definition at line 380 of file searchmemberstext.column_col3.php.
Variable Documentation
if ($results) $Accommodation = array()
Definition at line 37 of file searchmemberstext.column_col3.php.
$Accommodation['anytime'] = $words->getBuffered('Accomodation_anytime')
Definition at line 38 of file searchmemberstext.column_col3.php.
$Accommodation['dependonrequest'] = $words->getBuffered('Accomodation_dependonrequest')
Definition at line 39 of file searchmemberstext.column_col3.php.
$Accommodation['neverask'] = $words->getBuffered('Accomodation_neverask')
Definition at line 40 of file searchmemberstext.column_col3.php.
$canHost = array(1 => '1', 2 => '2', 3 => '3', 4 => '4', 5 => '5', 10 => '10', 20 => '20')
Definition at line 82 of file searchmemberstext.column_col3.php.
$distance = array(0 => $words->getSilent("SearchExactMatch"), 5 => '5 km/3 mi', 10 => '10 km/6 mi', 25 => '25 km/15 mi', 50 => '50 km/30 mi', 100 => '100 km/60 mi')
Definition at line 94 of file searchmemberstext.column_col3.php.
$errors = $this->getRedirectedMem('errors')
Definition at line 4 of file searchmemberstext.column_col3.php.
$i
Definition at line 275 of file searchmemberstext.column_col3.php.
$ii = 0
Definition at line 174 of file searchmemberstext.column_col3.php.
$layoutbits = new MOD_layoutbits()
Definition at line 49 of file searchmemberstext.column_col3.php.
$locations = array ()
Definition at line 18 of file searchmemberstext.column_col3.php.
Referenced by GeoView\generateLocationOverview(), GeoView\generateLocationOverviewNoJs(), GeoController\GeoSearch(), Forums\getAllLocations(), BlogController\index(), GeoController\index(), SearchController\searchSuggestLocations(), SearchModel\suggestLocations(), and SearchModel\suggestLocationsFromDatabase().
if (empty($vars)) $members = array ()
Definition at line 17 of file searchmemberstext.column_col3.php.
if ($this->showAdvanced) $numberOfItems = array('5', '10', '20', '50', '100')
Definition at line 114 of file searchmemberstext.column_col3.php.
$orderArray = SearchModel::getOrderByArray()
Definition at line 43 of file searchmemberstext.column_col3.php.
$orderBy = array()
Definition at line 42 of file searchmemberstext.column_col3.php.
$orderBy[$key+1] = $words->getSilent($orderArray[$key]['WordCode']. 'Desc')
Definition at line 46 of file searchmemberstext.column_col3.php.
$pager = new PagerWidget($params)
Definition at line 166 of file searchmemberstext.column_col3.php.
if (!empty($members)) (!$this->member) $params = new StdClass
Definition at line 154 of file searchmemberstext.column_col3.php.
$results = $this->getRedirectedMem('results')
Definition at line 19 of file searchmemberstext.column_col3.php.
Referenced by GeoModel\getGeonamesHierarchy(), SearchModel\getResultsForLocation(), AdminModel\getStatusOverview(), and GeoModel\suggestLocation().
$select = '<select name="search-number-items">'
Definition at line 115 of file searchmemberstext.column_col3.php.
Referenced by SuggestionsBasePage\getStateSelect().
$vars = $this->getRedirectedMem('vars')
Definition at line 5 of file searchmemberstext.column_col3.php.
case __pad0__
Definition at line 258 of file searchmemberstext.column_col3.php.
case __pad1__
Definition at line 261 of file searchmemberstext.column_col3.php.
else __pad2__
Definition at line 269 of file searchmemberstext.column_col3.php.
case __pad3__
Definition at line 296 of file searchmemberstext.column_col3.php.
case __pad4__
Definition at line 299 of file searchmemberstext.column_col3.php.
else __pad5__
Definition at line 307 of file searchmemberstext.column_col3.php.
case __pad6__
Definition at line 329 of file searchmemberstext.column_col3.php.
case __pad7__
Definition at line 332 of file searchmemberstext.column_col3.php.
case __pad8__
Definition at line 356 of file searchmemberstext.column_col3.php.
case __pad9__
Definition at line 359 of file searchmemberstext.column_col3.php.
$params active_page = $vars['search-page-current']
Definition at line 164 of file searchmemberstext.column_col3.php.
case admin1s
Definition at line 322 of file searchmemberstext.column_col3.php.
break
Definition at line 250 of file searchmemberstext.column_col3.php.
Referenced by Forums\__construct(), PollsPage\column_col3(), MOD_bw_user_Auth\doBWLogin1(), RssController\index(), PollsController\index(), VerifymembersController\index(), LinkController\index(), ForumsController\index(), and LoginModel\setBWMemberAsLoggedIn().
else $location cnt
Definition at line 269 of file searchmemberstext.column_col3.php.
Referenced by Rox\getMembersPerCountry().
case countries
Definition at line 349 of file searchmemberstext.column_col3.php.
if ($this->member) else
Initial value:
{
            $params->items = $results['countOfPublicMembers']
Definition at line 161 of file searchmemberstext.column_col3.php.
endforeach
Definition at line 47 of file searchmemberstext.column_col3.php.
endif
Definition at line 60 of file searchmemberstext.column_col3.php.
endswitch
Definition at line 263 of file searchmemberstext.column_col3.php.
foreach ($canHost as $value=> $display) if($value==$vars['search-can-host'])
Definition at line 85 of file searchmemberstext.column_col3.php.
foreach ($distance as $value=> $display) if($value==$vars['search-distance'])
Definition at line 97 of file searchmemberstext.column_col3.php.
$params items_per_page = $vars['search-number-items']
Definition at line 165 of file searchmemberstext.column_col3.php.
$params page_method = 'form'
Definition at line 158 of file searchmemberstext.column_col3.php.
$params page_url = "/search/members/text?" . http_build_query($vars)
Definition at line 156 of file searchmemberstext.column_col3.php.
$params page_url_marker = 'search-page-'
Definition at line 157 of file searchmemberstext.column_col3.php.
$params strategy = new FullPagePager()
Definition at line 155 of file searchmemberstext.column_col3.php.