Rox: search.js File Reference
search.js File Reference
Functions
function monkeyPatchAutocomplete ()
jQuery (function(){monkeyPatchAutocomplete();})
jQuery widget ("custom.catcomplete", jQuery.ui.autocomplete,{_renderMenu:function(ul, items){var that=this, currentCategory="";jQuery.each(items, function(index, item){if(item.category!=currentCategory){ul.append("<li class='ui-autocomplete-category'>"+item.category+"</li>");currentCategory=item.category;}that._renderItemData(ul, item);});}})
function enableMultiSelect ()
Function Documentation
function enableMultiSelect ()
References jQuery().
jQuery (function(){monkeyPatchAutocomplete();})
Referenced by enableMultiSelect(), and monkeyPatchAutocomplete().
function monkeyPatchAutocomplete ()
References jQuery().
jQuery widget ("custom.catcomplete" , jQuery.ui. autocomplete, {_renderMenu:function(ul, items){var that=this, currentCategory="";jQuery.each(items, function(index, item){if(item.category!=currentCategory){ul.append("<li class='ui-autocomplete-category'>"+item.category+"</li>");currentCategory=item.category;}that._renderItemData(ul, item);});}})