Rox: C:/xampp/htdocs/rox/htdocs/script/searchmembers.js File Reference
searchmembers.js File Reference
Functions
function searchGlobal (i)
function searchByMap (i)
function searchByText (address, i)
function searchByAddressPoint (addressPoint)
function searchByAddressPoint (addressPoint, i)
function flipSortDirection (e)
function loadMap (i)
function hookUpPager (container_id, per_page)
function toggle_map ()
function getxmlEl (x, s)
function page_navigate (i)
function get_val (field)
function put_val (field, s)
function get_html (field)
function put_html (field, s)
function getFieldHelp (name)
function chkEnt (field, e)
function newWindow (un)
jQuery (function(){bwrox.initSearchMembers();})
Variables
var gmarkers = []
var index = 0
var state = ''
var map_scale
var geocoder = null
var map_showing = true
var geosearchMapBuilder
var reverseGeolocator
BWRox prototype initSearchMembers
Function Documentation
function chkEnt (field, e)
Definition at line 394 of file searchmembers.js.
References e, and window.
function flipSortDirection (e)
Definition at line 142 of file searchmembers.js.
References e, Event, loadMap(), and window.
function get_html (field)
Definition at line 382 of file searchmembers.js.
function get_val (field)
Definition at line 374 of file searchmembers.js.
Referenced by hookUpPager(), and page_navigate().
function getFieldHelp (name)
Definition at line 390 of file searchmembers.js.
References eval(), and put_html().
function getxmlEl (x, s)
Definition at line 361 of file searchmembers.js.
References s, and x.
function hookUpPager (container_id, per_page)
Definition at line 333 of file searchmembers.js.
References a, d, e, Event, get_val(), loadMap(), searchByMap(), searchByText(), and state.
Referenced by loadMap().
jQuery (function(){bwrox.initSearchMembers();})
Definition at line 2 of file leaflet-test.js.
Referenced by loadMap(), and searchByAddressPoint().
function loadMap (i)
Definition at line 150 of file searchmembers.js.
References BWMapSearchResult, bwrox, calculateDistance(), calculateZoomLevel(), e, geosearchMapBuilder, gmarkers, hookUpPager(), i, if, index, innerHTML, jQuery(), map_scale, put_html(), put_val(), req, state, toggle_map(), and value.
Referenced by flipSortDirection(), hookUpPager(), page_navigate(), searchByAddressPoint(), searchByMap(), and searchGlobal().
function newWindow (un)
Definition at line 408 of file searchmembers.js.
References http_baseuri, and window.
function page_navigate (i)
Definition at line 365 of file searchmembers.js.
References get_val(), i, loadMap(), searchByMap(), searchByText(), and state.
function put_html (field, s)
Definition at line 386 of file searchmembers.js.
References s.
Referenced by getFieldHelp(), loadMap(), searchByMap(), searchByText(), and searchGlobal().
function put_val (field, s)
Definition at line 378 of file searchmembers.js.
References s.
Referenced by loadMap(), searchByMap(), searchByText(), and searchGlobal().
function searchByAddressPoint (addressPoint)
Definition at line 110 of file searchmembers.js.
References geosearchMapBuilder, jQuery(), loadMap(), and value.
Referenced by searchByText().
function searchByAddressPoint (addressPoint, i)
Definition at line 122 of file searchmembers.js.
References bwrox, geosearchMapBuilder, i, innerHTML, loadMap(), map_scale, and value.
function searchByMap (i)
Definition at line 63 of file searchmembers.js.
References bounds, geosearchMapBuilder, i, innerHTML, loadMap(), put_html(), put_val(), state, and value.
Referenced by hookUpPager(), and page_navigate().
function searchByText (address, i)
Definition at line 89 of file searchmembers.js.
References bwrox, i, innerHTML, put_html(), put_val(), reverseGeolocator, searchByAddressPoint(), state, and value.
Referenced by hookUpPager(), and page_navigate().
function searchGlobal (i)
Definition at line 48 of file searchmembers.js.
References i, innerHTML, loadMap(), put_html(), put_val(), state, and value.
function toggle_map ()
Definition at line 351 of file searchmembers.js.
References map_showing.
Referenced by loadMap().
Variable Documentation
var geocoder = null
Definition at line 6 of file searchmembers.js.
var geosearchMapBuilder
Definition at line 9 of file searchmembers.js.
Referenced by loadMap(), searchByAddressPoint(), and searchByMap().
var gmarkers = []
Definition at line 1 of file searchmembers.js.
Referenced by loadMap().
var index = 0
Definition at line 2 of file searchmembers.js.
Referenced by !function(), addMarkers(), Animation(), defaultPrefilter(), loadMap(), propFilter(), and showHide().
BWRox prototype initSearchMembers
Definition at line 12 of file searchmembers.js.
var map_scale
Definition at line 5 of file searchmembers.js.
Referenced by loadMap(), searchByAddressPoint(), and showAddress().
var map_showing = true
Definition at line 7 of file searchmembers.js.
Referenced by toggle_map().
var reverseGeolocator
Definition at line 10 of file searchmembers.js.
Referenced by searchByText().
var state = ''
Definition at line 3 of file searchmembers.js.
Referenced by hookUpPager(), loadMap(), page_navigate(), searchByMap(), searchByText(), and searchGlobal().