Rox: smallMapGeoLocation.js File Reference
smallMapGeoLocation.js File Reference
Functions
jQuery (function(){if($('geoselector')){$('geoselector').style.display= 'none';}if($('geoselector')){$('geoselectorjs').style.display= 'block';}if($('geoselector')){$('spaf_map').style.display= 'block';}GeoSuggest.initialize('geo-form');initOsmMap();})
function initOsmMap ()
function removeHighlight ()
function setMap (geonameid, latitude, longitude, zoom, geonamename, countryname, countrycode, admincode)
function changeMarker (markerLatitude, markerLongitude, zoomLevel, markerDescription)
function setGeonameIdInForm (geonameid, latitude, longitude, geonamename, countryname, countrycode, admincode)
Variables
var mapBuilder
Function Documentation
function changeMarker (markerLatitude, markerLongitude, zoomLevel, markerDescription)
Referenced by setMap().
function initOsmMap ()
References BWSimpleMapBuilder, and jQuery().
jQuery (function(){if($('geoselector')){$('geoselector').style.display= 'none';}if($('geoselector')){$('geoselectorjs').style.display= 'block';}if($('geoselector')){$('spaf_map').style.display= 'block';}GeoSuggest.initialize('geo-form');initOsmMap();})
Referenced by initOsmMap().
function removeHighlight ()
References Element.
Referenced by setMap().
function setGeonameIdInForm (geonameid, latitude, longitude, geonamename, countryname, countrycode, admincode)
References geonameid, and value.
Referenced by setMap().
function setMap (geonameid, latitude, longitude, zoom, geonamename, countryname, countrycode, admincode)
called when an user click on a result of the list, to update the marker.
References changeMarker(), Element, geonameid, removeHighlight(), and setGeonameIdInForm().
Variable Documentation
var mapBuilder