Rox: C:/xampp/htdocs/rox/build/blog/templates/stickyposts.php File Reference
stickyposts.php File Reference
Namespaces
blog
Variables
$Blog = new Blog()
$BlogView = new BlogView($Blog)
$request = PRequest::get()->request
$requestStr = implode('/', $request)
$matches = array()
if(preg_match('%/page(\d+)%',
$requestStr, $matches)) else
$postIt = $Blog->getStickyPostIt()
$pages = PFunctions::paginate($postIt, $page)
$maxPage = $pages[2]
$currentPage = $page
Variable Documentation
$Blog = new Blog()
Definition at line 13 of file stickyposts.php.
$BlogView = new BlogView($Blog)
Definition at line 14 of file stickyposts.php.
$currentPage = $page
Definition at line 34 of file stickyposts.php.
Referenced by BlogView\allBlogs(), TripView\displayTrips(), BlogView\PostsByCategory(), ForumsView\showForum(), ForumsView\showTopic(), ForumsView\showTopLevelCategories(), ForumsView\showTopLevelRecentPosts(), and BlogView\userPosts().
$matches = array()
Definition at line 20 of file stickyposts.php.
Referenced by Snoopy\_httprequest(), Snoopy\_httpsrequest(), LoginModel\checkTBPassword(), SimplePie_HTTP_Parser\chunked(), SimplePie_Net_IPv6\compress(), MOD_user\doLogin(), SimplePie_Misc\get_element(), GeoController\index(), RequestRouter\matchRoute(), RequestRouter\url(), and MembersModel\validateBirthdate().
$maxPage = $pages[2]
Definition at line 32 of file stickyposts.php.
Referenced by BlogView\allBlogs(), TripView\displayTrips(), BlogView\PostsByCategory(), ForumsView\showForum(), ForumsView\showTopic(), ForumsView\showTopLevelCategories(), ForumsView\showTopLevelRecentPosts(), and BlogView\userPosts().
$pages = PFunctions::paginate($postIt, $page)
Definition at line 30 of file stickyposts.php.
Referenced by BlogView\allBlogs(), TripView\displayTrips(), FullPagePager\getHtml(), HalfPagePager\getHtml(), BlogView\PostsByCategory(), ForumsView\showForum(), ForumsView\showTopic(), ForumsView\showTopLevelCategories(), ForumsView\showTopLevelLandingPage(), ForumsView\showTopLevelRecentPosts(), and BlogView\userPosts().
$postIt = $Blog->getStickyPostIt()
Definition at line 29 of file stickyposts.php.
$request = PRequest::get()->request
Definition at line 18 of file stickyposts.php.
$requestStr = implode('/', $request)
Definition at line 19 of file stickyposts.php.
if (preg_match('%/page(\d+)%', $requestStr, $matches)) else
Initial value:
{
        $page = 1
Definition at line 23 of file stickyposts.php.