Rox: teaserCountry.php File Reference
teaserCountry.php File Reference
Variables
$words = new MOD_words()
$countrycode = htmlspecialchars($countrycode)
$region = htmlspecialchars($region)
if(isset($country->name)) $city = htmlspecialchars($city)
if(!$countrycode OR!isset($country->
name)) else
Variable Documentation
if (isset($country->name)) $city = htmlspecialchars($city)
Referenced by Member\get_address(), and ApiModel\getMemberData().
$countrycode = htmlspecialchars($countrycode)
Referenced by Board\__construct(), Places\checkRegionExists(), AdminModel\enqueueMassmail(), AdminController\getAdminUnits(), AdminModel\getAdminUnits(), Places\getAllCities(), Places\getAllRegions(), AdminModel\getGeonameIdForCountryCode(), Places\getMembersOfCountry(), Places\getMembersOfRegion(), AdminController\getPlaces(), and AdminModel\getPlaces().
$region = htmlspecialchars($region)
Referenced by Member\get_address(), and Places\getAllRegions().
$words = new MOD_words()
if (!$city) else
Initial value:
{
        echo '<a href="places">'.$words->getFormatted('CountryTitle').'</a>'