Rox: topnav.php File Reference
topnav.php File Reference
Variables
$words = new MOD_words()
$model = new VolunteerbarModel()
$numberPersonsToBeAccepted = $model->getNumberPersonsToBeAccepted()
$numberReportedComments = $model->getNumberReportedComments()
$numberPersonsToBeChecked = $model->getNumberPersonsToBeChecked()
$numberSpamToBeChecked = $model->getNumberSpamToBeChecked()
$numberPersonsToAcceptInGroup = $model->getNumberPersonsToAcceptInGroup()
$R = MOD_right::get()
$res = ""
$request = PRequest::get()->request
$link = ""
if(count($request) > 1) $array_of_items
if($logged_in) foreach($array_of_items
as $item) if($logged_in) else {
Variable Documentation
if (count($request) > 1) $array_of_items
Initial value:
=
        array(
            array(
                'Comments',
                'bw/admin/admincomments.php',
                'Negative comments (' . $numberReportedComments . ')',
                'Review negative comments'
            ),
            array(
                'Checker',
                'bw/admin/adminchecker.php?action=viewSpamSayMember',
                'Reported messages ('.$numberSpamToBeChecked.')',
                'Review messages reported by users as spam'
            ),
            array(
                'Group',
                'bw/admin/admingroups.php',
                'Group applications ('.$numberPersonsToAcceptInGroup.')',
                'Review join requests for groups'
            )
        )
$link = ""
$model = new VolunteerbarModel()
$numberPersonsToAcceptInGroup = $model->getNumberPersonsToAcceptInGroup()
Referenced by VolunteerLinksWidget\render().
$numberPersonsToBeAccepted = $model->getNumberPersonsToBeAccepted()
Referenced by VolunteerLinksWidget\render().
$numberPersonsToBeChecked = $model->getNumberPersonsToBeChecked()
Referenced by VolunteerLinksWidget\render().
$numberReportedComments = $model->getNumberReportedComments()
$numberSpamToBeChecked = $model->getNumberSpamToBeChecked()
Referenced by VolunteerLinksWidget\render().
$R = MOD_right::get()
$request = PRequest::get()->request
$res = ""
$words = new MOD_words()
if ($logged_in) foreach ($array_of_items as $item) if ($logged_in) else {