Rox: C:/xampp/htdocs/rox/htdocs/script/map/small/tripMap.js File Reference
tripMap.js File Reference
Functions
jQuery (function(){initTripMap();})
function initTripMap ()
function addMarker (markerLatitude, markerLongitude, markerDescription, tripId)
Variables
var mapBuilder
Function Documentation
function addMarker (markerLatitude, markerLongitude, markerDescription, tripId)
Definition at line 38 of file tripMap.js.
Referenced by initTripMap().
function initTripMap ()
Definition at line 8 of file tripMap.js.
References addMarker(), bwrox, BWSimpleMapBuilder, i, jQuery(), marker, and markers.
jQuery (function(){initTripMap();})
Definition at line 2 of file leaflet-test.js.
Referenced by initTripMap().
Variable Documentation
var mapBuilder
Definition at line 6 of file tripMap.js.