Rox: C:/xampp/htdocs/rox/build/trip/templates/map.php File Reference
map.php File Reference
Variables
$words = new MOD_words()
$request = PRequest::get()->request
$sub = ''
if (isset($request[1])&&$request[1]== 'show'&&isset($request[2]))
markers = new Array()
$zoomLevel = 4
$point = 0
$locations = array()
if($locations!=null &&$point!=null
&&$locations[$point]!=null) else
$lng = '-0.09'
Variable Documentation
$lng = '-0.09'
Definition at line 118 of file map.php.
$locations = array()
Definition at line 38 of file map.php.
foreach ($trips as $trip) $point = 0
Definition at line 37 of file map.php.
$request = PRequest::get()->request
Definition at line 3 of file map.php.
$sub = ''
Definition at line 4 of file map.php.
Referenced by DonateView\donate(), and DonateController\index().
$words = new MOD_words()
Definition at line 2 of file map.php.
$zoomLevel = 4
Definition at line 36 of file map.php.
if ($locations!=null &&$point!=null &&$locations[$point]!=null) else
Initial value:
{
        $lat = '51.505'
Definition at line 115 of file map.php.
if(isset($request[1])&&$request[1]== 'show'&&isset($request[2]))
Definition at line 5 of file map.php.
markers = new Array()
Definition at line 34 of file map.php.
Referenced by addMarkers(), initTripMap(), LoadMap(), and setupOfficeMarkers().