Rox: C:/xampp/htdocs/rox/htdocs/script/trip_functions.js File Reference
trip_functions.js File Reference
Functions
function load ()
function zoomfit (map)
function getIcon (images)
function setupOfficeMarkers ()
function createMarker (posn, title, icon)
function deleteMarker ()
function clearMarkers ()
function reloadMarkers ()
Variables
var map
var mgr
var icons = {}
var allmarkers = []
var bounds = new GLatLngBounds()
Function Documentation
function clearMarkers ()
Definition at line 87 of file trip_functions.js.
References mgr.
function createMarker (posn, title, icon)
Definition at line 76 of file trip_functions.js.
References icon, marker, mgr, and title.
Referenced by setupOfficeMarkers().
function deleteMarker ()
Definition at line 82 of file trip_functions.js.
References allmarkers, and mgr.
function getIcon (images)
Definition at line 34 of file trip_functions.js.
References icon, and icons.
Referenced by setupOfficeMarkers().
function load ()
Definition at line 11 of file trip_functions.js.
References map, MarkerManager(), mgr, setupOfficeMarkers(), window, and zoomfit().
function reloadMarkers ()
Definition at line 91 of file trip_functions.js.
References setupOfficeMarkers().
function setupOfficeMarkers ()
Definition at line 56 of file trip_functions.js.
References allmarkers, bounds, createMarker(), getIcon(), i, icon, marker, markers, mgr, and title.
Referenced by load(), and reloadMarkers().
function zoomfit (map)
Definition at line 28 of file trip_functions.js.
References bounds, and map.
Referenced by load().
Variable Documentation
var allmarkers = []
Definition at line 8 of file trip_functions.js.
Referenced by deleteMarker(), and setupOfficeMarkers().
var bounds = new GLatLngBounds()
Definition at line 9 of file trip_functions.js.
Referenced by fitMapToBounds(), searchByMap(), setupOfficeMarkers(), update_map_loc(), and zoomfit().
var icons = {}
Definition at line 7 of file trip_functions.js.
Referenced by getIcon().
var map
Definition at line 5 of file trip_functions.js.
Referenced by load(), and zoomfit().
var mgr
Definition at line 6 of file trip_functions.js.
Referenced by clearMarkers(), createMarker(), deleteMarker(), load(), and setupOfficeMarkers().