Rox: C:/xampp/htdocs/rox/build/members/templates/updatemandatory.column_col3.helper.php File Reference
updatemandatory.column_col3.helper.php File Reference
Functions
buildBirthYearOptions ($selYear=0)
Variables
$callback_tag = $this->layoutkit->formkit->setPostCallback('MembersController', 'updateMandatoryCallback')
$member = $this->member
$m firstname = MOD_crypt::MemberReadCrypted($member->FirstName,'')
$m secondname = MOD_crypt::MemberReadCrypted($member->SecondName,'')
$m lastname = MOD_crypt::MemberReadCrypted($member->LastName,'')
$m geonameid = $member->IdCity
$m street = MOD_crypt::MemberReadCrypted($member->address->StreetName)
$m housenumber = MOD_crypt::MemberReadCrypted($member->address->HouseNumber)
$m zip = MOD_crypt::MemberReadCrypted($member->address->Zip)
$m birthday = date("d",strtotime($member->BirthDate))
$m birthmonth = date("m",strtotime($member->BirthDate))
$selYear = date("Y",strtotime($member->BirthDate))
$birthYearOptions = buildBirthYearOptions($selYear)
$m gender = $member->Gender
if(!$mem_redirect=$this->
layoutkit->formkit->
getMemFromRedirect()) else
$lang = $this->model->get_profile_language()
$profile_language = $lang->id
$profile_language_code = $lang->ShortCode
$words = $this->getWords()
$messengers = $member->messengers()
$website = $member->WebSite
$groups = $member->get_group_memberships()
Function Documentation
buildBirthYearOptions ($selYear = 0)
Definition at line 4 of file updatemandatory.column_col3.helper.php.
References $i, $old_member_born, $selYear, $young_member_born, and SignupModel\YOUNGEST_MEMBER.
Variable Documentation
$birthYearOptions = buildBirthYearOptions($selYear)
Definition at line 33 of file updatemandatory.column_col3.helper.php.
$callback_tag = $this->layoutkit->formkit->setPostCallback('MembersController', 'updateMandatoryCallback')
Definition at line 21 of file updatemandatory.column_col3.helper.php.
$groups = $member->get_group_memberships()
Definition at line 60 of file updatemandatory.column_col3.helper.php.
$lang = $this->model->get_profile_language()
Definition at line 52 of file updatemandatory.column_col3.helper.php.
$member = $this->member
Definition at line 22 of file updatemandatory.column_col3.helper.php.
$messengers = $member->messengers()
Definition at line 57 of file updatemandatory.column_col3.helper.php.
$profile_language = $lang->id
Definition at line 53 of file updatemandatory.column_col3.helper.php.
$profile_language_code = $lang->ShortCode
Definition at line 54 of file updatemandatory.column_col3.helper.php.
$selYear = date("Y",strtotime($member->BirthDate))
Definition at line 32 of file updatemandatory.column_col3.helper.php.
Referenced by buildBirthYearOptions(), SignupPage\buildBirthYearOptions(), SignupPage\column_col3(), and SignupView\registerForm().
$website = $member->WebSite
Definition at line 58 of file updatemandatory.column_col3.helper.php.
$words = $this->getWords()
Definition at line 55 of file updatemandatory.column_col3.helper.php.
$m birthday = date("d",strtotime($member->BirthDate))
Definition at line 30 of file updatemandatory.column_col3.helper.php.
$m birthmonth = date("m",strtotime($member->BirthDate))
Definition at line 31 of file updatemandatory.column_col3.helper.php.
if (!$mem_redirect=$this->layoutkit->formkit->getMemFromRedirect()) else
Initial value:
{
    $vars = $mem_redirect->post
Definition at line 48 of file updatemandatory.column_col3.helper.php.
$m firstname = MOD_crypt::MemberReadCrypted($member->FirstName,'')
Definition at line 23 of file updatemandatory.column_col3.helper.php.
$m gender = $member->Gender
Definition at line 34 of file updatemandatory.column_col3.helper.php.
$m geonameid = $member->IdCity
Definition at line 26 of file updatemandatory.column_col3.helper.php.
$m housenumber = MOD_crypt::MemberReadCrypted($member->address->HouseNumber)
Definition at line 28 of file updatemandatory.column_col3.helper.php.
$m lastname = MOD_crypt::MemberReadCrypted($member->LastName,'')
Definition at line 25 of file updatemandatory.column_col3.helper.php.
$m secondname = MOD_crypt::MemberReadCrypted($member->SecondName,'')
Definition at line 24 of file updatemandatory.column_col3.helper.php.
$m street = MOD_crypt::MemberReadCrypted($member->address->StreetName)
Definition at line 27 of file updatemandatory.column_col3.helper.php.
$m zip = MOD_crypt::MemberReadCrypted($member->address->Zip)
Definition at line 29 of file updatemandatory.column_col3.helper.php.