Rox: C:/xampp/htdocs/rox/build/gallery/templates/uploadform.php File Reference
uploadform.php File Reference
Variables
$layoutkit = $this->layoutkit
$formkit = $layoutkit->formkit
$vars = $formkit->mem_from_redirect
$callbacktag = $formkit->setPostCallback('GalleryController', 'uploadedProcess')
$galleryId = isset($this->galleryId) ? $this->galleryId : false
$words = $this->words
$postURL = 'gallery/uploaded'
Variable Documentation
$callbacktag = $formkit->setPostCallback('GalleryController', 'uploadedProcess')
Definition at line 5 of file uploadform.php.
Referenced by GeoPopupPage\body(), GroupMemberSettingsPage\column_col3(), GeoView\generateLocationOverviewNoJs(), GeoController\GeoSearch(), and GeoController\SelectorInclude().
$formkit = $layoutkit->formkit
Definition at line 3 of file uploadform.php.
$galleryId = isset($this->galleryId) ? $this->galleryId : false
Definition at line 10 of file uploadform.php.
Referenced by GalleryController\ajaxlatestimages(), Trip\assignGallery(), GalleryController\createGalleryCallback(), Trip\createTrip(), Trip\editProcess(), GalleryModel\galleryOwner(), GalleryModel\getLatestItems(), GalleryModel\getNextGalleryItems(), GalleryModel\getPreviousGalleryItems(), and GalleryController\index().
$layoutkit = $this->layoutkit
Definition at line 2 of file uploadform.php.
$postURL = 'gallery/uploaded'
Definition at line 25 of file uploadform.php.
$vars = $formkit->mem_from_redirect
Definition at line 4 of file uploadform.php.
$words = $this->words
Definition at line 12 of file uploadform.php.