Rox: verifydata.template.php File Reference
verifydata.template.php File Reference
Variables
$verification_status = $m->verification_status
$houseNumber = empty($m->member_data->HouseNumber) ? '&nbsp;' : $m->member_data->HouseNumber
$streetName = empty($m->member_data->StreetName) ? '&nbsp;' : $m->member_data->StreetName
$zip = empty($m->member_data->Zip) ? '&nbsp;' : $m->member_data->Zip
$cityName = empty($m->member_data->CityName) ? '&nbsp;' : $m->member_data->CityName
Variable Documentation
$cityName = empty($m->member_data->CityName) ? '&nbsp;' : $m->member_data->CityName
Referenced by PlacesController\city(), and Member\get_address().
$houseNumber = empty($m->member_data->HouseNumber) ? '&nbsp;' : $m->member_data->HouseNumber
Referenced by Member\get_address().
$streetName = empty($m->member_data->StreetName) ? '&nbsp;' : $m->member_data->StreetName
Referenced by Member\get_address().
$verification_status = $m->verification_status
$zip = empty($m->member_data->Zip) ? '&nbsp;' : $m->member_data->Zip
Referenced by Member\get_address().