services:
    Rox\Admin\Controller\LogsController:
        class: Rox\Admin\Controller\LogsController
        autowire: true

    Rox\Admin\Controller\MockupsController:
        class: Rox\Admin\Controller\MockupsController
        autowire: true
