services:
    Rox\Admin\Controller\LogsController:
        class: Rox\Admin\Controller\LogsController
        parent: Rox\Core\Controller\AbstractController
        autowire: true

    Rox\Admin\Controller\MockupsController:
        class: Rox\Admin\Controller\MockupsController
        parent: Rox\Core\Controller\AbstractController
        autowire: true
