# TODO change route names to use slashes
# TODO use unquoted class names

mockups:
    path: /mockups/{mockup}
    defaults:
      _controller: Rox\Admin\Controller\MockupsController:showMockup

admin/logs:
    path:     /admin/logs
    methods: [GET]
    defaults:
        _controller: Rox\Admin\Controller\LogsController:showOverview

admin_queries:
    path:     /admin/queries
    methods: [GET, POST]
    defaults:
        _controller: Rox\Admin\Queries\QueriesController::showOverview
        currentPage: 1
        itemsPerPage: 20

admin_queries_fetch_parameters:
    path:     /admin/queries/fetchparameters
    methods: [GET]
    defaults:
        _controller: Rox\Admin\Queries\QueriesController::fetchParameterElements

admin/communitynews:
    path:     /admin/communitynews
    methods: [GET]
    defaults:
        _controller: Rox\Admin\Controller\CommunityNewsController::showList

admin/communitynews/create:
    path:     /admin/communitynews/create
    defaults:
        _controller: Rox\Admin\Controller\CommunityNewsController::createAction

admin/communitynews/edit:
    path:     /admin/communitynews/{id}/edit
    defaults:
        _controller: Rox\Admin\Controller\CommunityNewsController::editAction
    requirements:
        id:         \d+

admin/communitynews/delete:
    path:     /admin/communitynews/{id}/delete
    methods: [GET]
    defaults:
        _controller: Rox\Admin\Controller\CommunityNewsController::deleteAction
    requirements:
        id:         \d+

admin/communitynews/show:
    path:     /admin/communitynews/{id}/show
    methods: [GET]
    defaults:
        _controller: Rox\Admin\Controller\CommunityNewsController::showAction
    requirements:
        id:         \d+

admin/communitynews/hide:
    path:     /admin/communitynews/{id}/hide
    methods: [GET]
    defaults:
        _controller: Rox\Admin\Controller\CommunityNewsController::hideAction
    requirements:
        id:         \d+
