
# a stub for a real nice Makefile -- some day

# just start collecting some (more or less) sensible commands in here

# chmod a+w data/
# apt-get install php5-gd


# svn co https://www.bewelcome.org/svn/develstuff/trunk/testdb/
# cd testdb
# gzip -d hcvoltest.sql.gz

#  mysql -u username -p
# mysql> CREATE DATABASE mtb
# mysql> Ctrl-D
#  mysql -u username -p mtb < hcvoltest.sql