services:
    Rox\Activity\Model\Activity:
        class: Rox\Activity\Model\Activity
        autowiring_types: Rox\CommunityNews\Repository\ActivityRepositoryInterface

    Rox\CommunityNews\Service\ActivityService:
        class: Rox\Activity\Service\ActivityService
        autowiring_types: Rox\Activity\Service\ActivityServiceInterface
