<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sun, 26 Feb 2017 10:08:01 +0000
 */
$conf['title'] = 'BeWelcome Wiki';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['basedir'] = '/wiki/';
$conf['userewrite'] = 1;
$conf['authtype']    = 'authrox';